### PR TITLE
copr: use `to_vec` instead of `as_slice` in unit tests

### PR DESCRIPTION
**Pull request by skyzh**
### What problem does this PR solve?

Problem Summary:

As the proposed `ChunkedVec` doesn't support `as_slice`, we replaced all `as_balahbalah_slice` with `as_balahbalah_vec`. Furthermore, we ensure that the `as_vec` call only occurs in tests, so as to reduce overhead in copr framework.

### What is changed and how it works?

Proposal: [RFC: Using chunk format in coprocessor framework](https://github.com/tikv/rfcs/pull/43/)

Related Issue: #7724

What's Changed:

* Remove `as_balahbalah_slice` interface for `VectorValue`.
* Add `as_balahbalah_vec` interface for `VectorValue`.

### Check List 

Tests 

- Unit test

Side effects

- Performance regression when running unit tests

### CODE REVIEW

**Comment by skyzh** [comment]
@breeswish @TennyZhuang PTAL~ Thanks!

**Comment by skyzh** [comment]
> According to [Rust's API guideline](https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv), maybe it's better to use `to_xxx_vec`. You can perform a global replace I guess :) The rest LGTM

Thanks for reviewing! I've changed all APIs.

**Comment by breeswish** [comment]
LGTM

**Pull request merged**
