### PR TITLE
server: add server info metrics for DBasS

### PR DESCRIPTION
**Pull request by iosmanthus**
Signed-off-by: iosmanthus <myosmanthustree@gmail.com>

### What problem does this PR solve?

This pull request adds server info metrics via a `GaugeVec` in format: `(version, githash) -> startup_ts`.

Problem Summary:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

```sh
http get 'http://localhost:9090/api/datasources/proxy/1/api/v1/query_range?query=tikv_server_info&start=1611738330&end=1611738465&step=15'

{
    "data": {
        "result": [
            {
                "metric": {
                    "__name__": "tikv_server_info",
                    "hash": "None",
                    "instance": "127.0.0.1:20180",
                    "job": "tikv",
                    "version": "5.0.0-rc.x"
                },
                "values": [
                    [
                        1611738360,
                        "1611738218"
                    ],
                    [
                        1611738375,
                        "1611738218"
                    ],
                    [
                        1611738390,
                        "1611738218"
                    ],
                    [
                        1611738405,
                        "1611738218"
                    ]
                ]
            }
        ],
        "resultType": "matrix"
    },
    "status": "success"
}

```

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- server: add server info metrics for DBasS

### CODE REVIEW

**Comment by breeswish** [comment]
Could you provide information about how it looks like?

**Comment by iosmanthus** [comment]
> Could you provide information about how it looks like?

image

**Review by crazycs520 — COMMENTED** [review]
LGTM

**Comment by zhongzc** [comment]
Is `1.612B` duplicate for this metric?

**Comment by zhongzc** [comment]
> Is `1.612B` duplicate on this metric?

Metric itself contains the timestamp information.

**Comment by iosmanthus** [comment]
> > Is `1.612B` duplicate on this metric?
> 
> Metric itself contains the timestamp information.

But the metrics' timestamps don't stand for the server startup timestamp...

**Comment by breeswish** [comment]
Missing leading `v` in the version?

**Pull request merged**
