### PR TITLE
raftstore: fix snap gen cancellation

### LINKED ISSUE #17226: tikv panic with "unexpected error: Store(Other(\\\"[components/raftstore/src/store/peer_storage.rs:545]: failed to get snapshot after 5 times\\\"  when injection network partition
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   8.2.0
Edition:           Community
Git Commit Hash:   5075a221e9f1e5faba54e3955c10b2422136174d
Git Commit Branch: HEAD
UTC Build Time:    2024-07-01 08:38:41
Rust Version:      rustc 1.77.0-nightly (89e2160c4 2023-12-27)
Enable Features:   memory-engine pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine trace-async-tasks openssl-vendored
Profile:           dist_release
2024-07-01T18:21:24.632+0800

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、run tpcc
2、injection network partition to one of tikv

### What did you expect?
no panic

### What did happened?
tikv panic 

`{"level":"FATAL","log":"[lib.rs:478] [\"unexpected error: Store(Other(\\\"[components/raftstore/src/store/peer_storage.rs:545]: failed to get snapshot after 5 times\\\")), raft_id: 5389057, region_id: 786\"] [backtrace=\"   0: tikv_util::set_panic_hook::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:477:18\\n   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2029:9\\n      std::panicking::rust_panic_with_hook\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:783:13\\n   2: std::panicking::begin_panic_handler::{{closure}}\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:657:13\\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:171:18\\n   4: rust_begin_unwind\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:645:5\\n   5: core::panicking::panic_fmt\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:72:14\\n   6: raft::raft::RaftCore<T>::prepare_send_snapshot\\n             at var/cache/cargohome/git/checkouts/raft-rs-42b8049ef2e3af07/a76fb6e/src/raft.rs:697:13\\n   7: raft::raft::RaftCore<T>::maybe_send_append\\n             at var/cache/cargohome/git/checkouts/raft-rs-42b8049ef2e3af07/a76fb6e/src/raft.rs:840:25\\n   8: raft::raft::RaftCore<T>::send_append\\n             at var/cache/cargohome/git/checkouts/raft-rs-42b8049ef2e3af07/a76fb6e/src/raft.rs:776:9\\n      raft::raft::Raft<T>::bcast_append::{{closure}}\\n             at var/cache/cargohome/git/checkouts/raft-rs-42b8049ef2e3af07/a76fb6e/src/raft.rs:907:39\\n      core::iter::traits::iterator::Iterator::for_each::call::{{closure}}\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:855:29\\n      core::iter::adapters::filter::filter_fold::{{closure}}\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/filter.rs:41:44\\n      core::iter::traits::iterator::Iterator::fold\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2640:21\\n      <core::iter::adapters::filter::Filter<I,P> as core::iter::traits::iterator::Iterator>::fold\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/filter.rs:157:9\\n      core::iter::traits::iterator::Iterator::for_each\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:858:9\\n      raft::raft::Raft<T>::bcast_append\\n             at var/cache/cargohome/git/checkouts/raft-rs-42b8049ef2e3af07/a76fb6e/src/raft.rs:904:9\\n      raft::raft::Raft<T>::step_leader\\n             at var/cache/cargohome/git/checkouts/raft-rs-42b8049ef2e3af07/a76fb6e/src/raft.rs:2129:17\\n      raft::raft::Raft<T>::step\\n             at var/cache/cargohome/git/checkouts/raft-rs-42b8049ef2e3af07/a76fb6e/src/raft.rs:1520:38\\n   9: raft::raw_node::RawNode<T>::propose\\n             at var/cache/cargohome/git/checkouts/raft-rs-42b8049ef2e3af07/a76fb6e/src/raw_node.rs:362:9\\n      raftstore::store::peer::Peer<EK,ER>::propose_normal\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/peer.rs:4605:9\\n  10: raftstore::store::peer::Peer<EK,ER>::propose::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/peer.rs:3789:35\\n      core::result::Result<T,E>::and_then\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1316:22\\n      raftstore::store::peer::Peer<EK,ER>::propose\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/peer.rs:3788:17\\n  11: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::propose_raft_command_internal\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:5797:12\\n  12: raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::propose_pending_batch_raft_command\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:794:9\\n      raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::on_loop_finished\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:763:13\\n      raftstore::store::fsm::peer::PeerFsmDelegate<EK,ER,T>::handle_msgs\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/peer.rs:724:9\\n  13: <raftstore::store::fsm::store::RaftPoller<EK,ER,T> as batch_system::batch::PollHandler<raftstore::store::fsm::peer::PeerFsm<EK,ER>,raftstore::store::fsm::store::StoreFsm<EK>>>::handle_normal\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/store.rs:1100:9\\n  14: batch_system::batch::Poller<N,C,Handler>::poll\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:422:27\\n  15: batch_system::batch::BatchSystem<N,C>::start_poller::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:551:17\\n      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}\\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:438:13\\n      std::sys_common::backtrace::__rust_begin_short_backtrace\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:155:18\\n  16: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:529:17\\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9\\n      std::panicking::try::do_call\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:40\\n      std::panicking::try\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:516:19\\n      std::panic::catch_unwind\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:142:14\\n      std::thread::Builder::spawn_unchecked_::{{closure}}\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:528:30\\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5\\n  17: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9\\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9\\n      std::sys::unix::thread::Thread::new::thread_start\\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17\\n  18: start_thread\\n  19: __GI___clone3\\n\"] [location=/var/cache/cargohome/git/checkouts/raft-rs-42b8049ef2e3af07/a76fb6e/src/raft.rs:697] [thread_name=raftstore-13-0] [thread_id=114]","pod":"tc-tikv-0","container":"tikv","namespace":"ha-test-tikv-failure-rpt-tps-7597058-1-91"}`

### PR DESCRIPTION
**Pull request by hbisheng**
### What is changed and how it works?

Issue Number: Close #17226

What's Changed:

```commit-message
As a follow-up of #17215, this commit fixes an issue with the
`cancel_generating_snap` function to ensure that `snap_tried_cnt`
within PeerStorage is not unexpectedly incremented.

Background:
In PeerStorage, `snap_tried_cnt` is used to track the number of
snapshot generation attempts. As with what happened in #17226, TiKV
would panic if `snap_tried_cnt` exceeds the limit (currently hardcoded
to 5). By design, `snap_tried_cnt` should only be incremented when an
actual failure happens during the snapshot generation process. It
should not be incremented if the snapshot generation is intentionally
canceled.

Although its name suggests so, the `cancel_generating_snap` function
doesn't always cancel the snapshot generation. If the inputting
`compact_to` is so small that it doesn't make the snapshot stale,
`cancel_generating_snap` will return early and won't set `cancel` to
true. In the fix, we ensure that we only cancel the precheck when
`cancel` is set to true. Without it, `snapshot()` will see a 
`TryRecvError::Disconnected` error while `last_canceled` is false and 
increment `tried_cnt`.

Note that `cancel_generating_snap` is only called with a `compact_to`
value in `on_compact_raftlog`, which I believe to be the trigger of
issue #17226.

Also, this commit fixes a similar problem to ensure that `tried_cnt` is
not incremented in another potential scenario—when the peer requesting
snapshot is unknown.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by hbisheng** [comment]
@overvenus Should we remove the `needs-cherry-pick-release-8.2` tag since we have removed this feature from v8.2.0?

**Comment by glorv** [comment]
> @overvenus Should we remove the `needs-cherry-pick-release-8.2` tag since we have removed this feature from v8.2.0?

Yes, as related PR were already rolled back.

**Comment by hbisheng** [comment]
@glorv The bot added the tag back after the removal... maybe we need to remove `affects-8.2` from #17226 first.

**Pull request merged**
