### PR TITLE
raftstore-v2: optimize the slowness detection on the Io-Hang scenario.

### PR DESCRIPTION
**Pull request by LykxSassinator**
### What is changed and how it works?

Issue Number: Ref #15070

What's Changed:

```commit-message
This pr includes:
* Polish the annotations in `raftstore-v2/src/worker/pd/slowness.rs`.
* Optimize the detection and the interval of reporting statistics on the io hang case.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
None.
```

### CODE REVIEW

**Comment by LykxSassinator** [comment]
/cc @overvenus

PTAL, thx

**Review by innerr — APPROVED** [review]
LGTM

**Review by overvenus — APPROVED** [review]

**Pull request merged**
