### PR TITLE
raftstore-v2: fix compilation errors.

### LINKED ISSUE #13968: raftstore-v2: exists compilation errors
### What version of TiKV are you using?

master

### What operating system and CPU are you using?

Linux kernel version: 
> Linux version 3.10.0-957.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Nov 8 23:39:32 UTC 2018

CPU info:
> Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz

### Steps to reproduce

Failed to compile the whole repo on master branch.

### What did you expect?
Compile successfully.

### What did happened?
```Cmake
Compiling raftstore-v2 v0.1.0 (/nvme1n1/lucasliang/workspace/tikv/components/raftstore-v2)

error[E0412]: cannot find type `FlushChannel` in this scope
   --> components/raftstore-v2/src/router/response_channel.rs:606:16
    |
239 | pub struct BaseChannel<Res> {
    | --------------------------- similarly named struct `BaseChannel` defined here
...
606 | impl Debug for FlushChannel {
    |                ^^^^^^^^^^^^ help: a struct with a similar name exists: `BaseChannel`
```

### LINKED ISSUE #13970: raftstore-v2: fix compilation errors.
## Development Task
Fix compilation erros in raftstore-v2.

Existing compilation errors can be reviewed as follows:
```Cmake
Compiling raftstore-v2 v0.1.0 (/nvme1n1/lucasliang/workspace/tikv/components/raftstore-v2)

error[E0412]: cannot find type `FlushChannel` in this scope
   --> components/raftstore-v2/src/router/response_channel.rs:606:16
    |
239 | pub struct BaseChannel<Res> {
    | --------------------------- similarly named struct `BaseChannel` defined here
...
606 | impl Debug for FlushChannel {
    |                ^^^^^^^^^^^^ help: a struct with a similar name exists: `BaseChannel`
```

### PR DESCRIPTION
**Pull request by LykxSassinator**
Signed-off-by: Lucasliang <nkcs_lykx@hotmail.com>

### What is changed and how it works?

Issue Number: Close #13970 

What's Changed:

```commit-message
Fix compilation errors.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by BusyJay — APPROVED** [review]

**Comment by LykxSassinator** [comment]
cc @BusyJay As I do not have the right to merge, please trigger the merge operation.

**Pull request merged**
