### PR TITLE
Rollup of 3 cherry-picks

### PR DESCRIPTION
**Pull request by overvenus**
Cherry pick #4125, #4223 and #3885.

### CODE REVIEW

**Comment by overvenus** [comment]
/run-all-tests tidb=release-2.1 pd=release-2.1 tidb-test=release-2.1 tidb-private-test=release-2.1

**Comment by overvenus** [comment]
/run-all-tests tidb=release-2.1 pd=release-2.1 tidb-test=release-2.1 tidb-private-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-all-tests tidb=release-2.1 pd=release-2.1 tidb-test=release-2.1 tidb-private-test=release-2.1

**Comment by overvenus** [comment]
/run-all-tests tidb=release-2.1 pd=release-2.1 tidb-test=release-2.1 tidb-private-test=release-2.1

**Comment by overvenus** [comment]
/run-all-tests tidb=release-2.1 pd=release-2.1 tidb-test=release-2.1 tidb-private-test=release-2.1

**Pull request merged**
