### PR TITLE
Add a few constructor tests to engine_traits_tests

### PR DESCRIPTION
**Pull request by brson**
### What problem does this PR solve?

Issue: https://github.com/tikv/tikv/issues/6402

Problem Summary:

Adding tests that storage engines create their output directory, and error if that directory is not writable.

### Release note 

- No release note.

### CODE REVIEW

**Review by nrc — APPROVED** [review]
lgtm

**Comment by brson** [comment]
@5kbpers can you review?

**Comment by brson** [comment]
I'll just include these changes in a future engine_traits_tests patch

**Pull request closed without merging**
