### PR TITLE
README.md: replace TiKV roadmap url

### PR DESCRIPTION
**Pull request by hongrubb**
The previous file is inaccessible. so I changed the url.

### CODE REVIEW

**Review by skyzh — COMMENTED** [review]
Roadmap for TiKV 4.0 is not applicable to current version. @tisonkun do we still have our roadmap tracked on GitHub? If not, I suggest removing this section or replace this URL with TiDB Internals.

**Comment by tisonkun** [comment]
@skyzh agree. At least we should remove misleading information.

**Comment by skyzh** [comment]
@hongrubb would you please help remove that section in this PR? By the way, it seems that you are using different email for git command line and GitHub, which makes your avatar missing from that commit.

**Comment by hongrubb** [comment]
> @hongrubb would you please help remove that section in this PR? By the way, it seems that you are using different email for git command line and GitHub, which makes your avatar missing from that commit.

sure, I will try to fix this.

**Comment by hongrubb** [comment]
> @hongrubb would you please help remove that section in this PR? By the way, it seems that you are using different email for git command line and GitHub, which makes your avatar missing from that commit.

Very thanks for pointing out the problem with the avatar. 

But unfortunately, I don't know why, I couldn't update the commit to this PR... 
I can get the commit log in my own repo, but they are not connected. 
As you can see, on this page, the link in the title `hongrubb:master` is grey.

**Comment by skyzh** [comment]
I have no idea either. You may open a new PR, attach a link to this PR, and cc me and tisonkun for review.

**Pull request closed without merging**
