### PR TITLE
copr: vectorize sub_duration_and_string and fix unit test

### PR DESCRIPTION
**Pull request by hongrubb**
Signed-off-by: hongrubb <hongru52@gmail.com>

### What problem does this PR solve?

Issue Number: #9016

Problem Summary: This PR is for vectorizing functions in impl_time.rs

### What is changed and how it works?

What's Changed: vectorize sub_duration_and_string, fix unit test in test_add_durationand_string()

### Related changes

none

### Check List 

Tests 

- Unit test

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by skyzh — COMMENTED** [review]
LGTM. Previously in https://github.com/tikv/tikv/pull/9931, we found that TiDB might be using different types from TiKV coprocessor for date related function. So I'll run some integration tests, and give my approval later.

**Comment by skyzh** [comment]
> LGTM. Previously in #9931, we found that TiDB might be using different types from TiKV coprocessor for date related function. So I'll run some integration tests, and give my approval later.

Unfortunately, it doesn't work. I'll take some time to look into this...

**Review by skyzh — APPROVED** [review]
LGTM. copr-test may require all date-time-related arithmetic functions to be implemented before it could pass, so we just ignore that result for now. Thanks for your contribution, and if you have time, you may try implementing all date-time-related arithmetic functions to make pushdown of datetime functions possible.

**Review by Xuanwo — APPROVED** [review]

**Comment by hongrubb** [comment]
> LGTM. copr-test may require all date-time-related arithmetic functions to be implemented before it could pass, so we just ignore that result for now. Thanks for your contribution, and if you have time, you may try implementing all date-time-related arithmetic functions to make pushdown of datetime functions possible.

Thanks, I will implement the rest of date-time-related arithmetic functions soon.

**Pull request merged**
