### PR TITLE
tidb_query_datatype: Fix Geometry FieldType support

### LINKED ISSUE #13651: "Unsupported FieldType" for FieldTypeTp::Geometry
## Bug Report

With a branch of TiDB that has initial support for geometric data types everything works with the unistore, but not with TiKV.

### PR DESCRIPTION
**Pull request by dveeden**
### What is changed and how it works?

Issue Number: Close #13651

What's Changed:

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by XuHuaiyu** [comment]
LGTM
But I do not have the reviewer priority of tikv repo.😄

**Review by BusyJay — APPROVED** [review]
On behalf of @XuHuaiyu

**Review by sticnarf — APPROVED** [review]

**Pull request merged**
