### PR TITLE
Update OWNERS_ALIASES

### PR DESCRIPTION
**Pull request by wuhuizuo**
### What is changed and how it works?

Issue Number: Ref #17004

What's Changed:

```commit-message
add `zhangjinpeng87` into alias: `sig-critical-approvers-config-src` to approval tikv storage parts.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [x] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by wuhuizuo** [comment]
/cc  @kevin-xianliu @cfzjywxk @easonn7

PTAL

**Comment by wuhuizuo** [comment]
/hold
wait for more LGTMs.

**Review by cfzjywxk — APPROVED** [review]

**Review by LykxSassinator — APPROVED** [review]

**Comment by LykxSassinator** [comment]
/unhold

It's ready to merge.

**Pull request merged**
