### PR TITLE
jenkins: remove useless jenkins file

### PR DESCRIPTION
**Pull request by hi-rustin**
Signed-off-by: hi-rustin <rustin.liu@gmail.com>

### What problem does this PR solve?
close https://github.com/tikv/tikv/issues/11214

Problem Summary:

### What is changed and how it works?

What's Changed:

remove useless jenkins file

### Related changes

None

### Check List 

Tests 

- No code

Side effects

None

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
/cc @tisonkun @zhouqiang-cl 

Although it was mainly used for testing cdc's tests, I think the change itself is valid.

**Review by tisonkun — APPROVED** [review]
LGTM

**Comment by hi-rustin** [comment]
/cc @BusyJay 

Could you please take a look? Thanks!

**Review by BusyJay — APPROVED** [review]

**Pull request merged**
