### PR TITLE
status_server: Fix output of jeprof

### LINKED ISSUE #17607: [status_server] no heap dump result via http
### What version of TiKV are you using?

nightly

### Steps to reproduce

Enable malloc_conf with "prof:ture,prof_active:ture", and dump heap via status server.

### What did you expect?

Get the heap dump.

### What did happened?

Get nothing.

### PR DESCRIPTION
**Pull request by Hexilee**
### What is changed and how it works?

Issue Number: Close #17607

What's Changed:

```commit-message
```
Refer to https://doc.rust-lang.org/std/process/struct.Command.html#method.stdout, when a `std::process::Command` is spawned, it will inherit `stdin`, `stdout` and `stderr` from its parent process.

In the `jeprof_heap_profile` of status server, we spawn `jeprof.in` and wait for its `stdout` or `stdout`, so we need configure them with `piped` instead of `inherit` to get expected output.

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [x] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Fix unexpected jeprof output when log-file is not specified
```

### CODE REVIEW

**Review by Connor1996 — COMMENTED** [review]
Without this fix, it would mix up with tikv's output when log-file is not specified. Am I right?

**Comment by Hexilee** [comment]
> Without this fix, it would mix up with tikv's output when log-file is not specified. Am I right?

Yes, and we cannot get the pprof result as expected.

**Review by Connor1996 — APPROVED** [review]

**Review by glorv — APPROVED** [review]

**Pull request merged**
