### PR TITLE
tidb_query: fix converting bytes to bool

### PR DESCRIPTION
**Pull request by zhongzc**
Signed-off-by: zhongzc zhongzc_arch@outlook.com

### What problem does this PR solve?
Fix compatibility with MySQL.
See: pingcap/tidb#16014

### What is changed and how it works?
Bytes is converted to an `f64` type instead of an int type to determine the bool value.

### CODE REVIEW

**Comment by Reminiscent** [comment]
@breeswish @sticnarf PTAL. And please cherry-pick to `tikv 2.1/ 3.0/ 3.1/ 4.0`. Thx!

**Comment by sticnarf** [comment]
Could you add a simple unit test for it?

**Comment by breeswish** [comment]
Do we need to add back from randgen test thanks to this fix?

**Comment by breeswish** [comment]
Remember that for branch 2.1, 3.0 and 3.1, the non-vec execution framework also need to be fixed.

**Pull request merged**
