### PR TITLE
metrics: fix compaction pending bytes metrics (#8991)

### LINKED ISSUE #8834: Wrong compaction pending bytes metrics
### What version of TiKV are you using?

master, 3.0, 4.0

### What operating system and CPU are you using?

N/A

### Steps to reproduce

View "compaction pending bytes" metrics in TiKV detail and TiKV fast tune.

### What did happened?

Metric is displayed using `sum(rate(..))` expressions. However `tikv_engine_pending_compaction_bytes` is a Gauge.

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #8991 to release-4.0

---

Signed-off-by: tabokie <xy.tao@outlook.com>

### What problem does this PR solve?

Issue Number: close #8834

Problem Summary:

Fix compaction pending bytes metrics, from `sum(rate(v))` to `v`. 

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

### Related changes

- Need to cherry-pick to the release branch

### Release note 

- No release note

### CODE REVIEW

**Review by tabokie — APPROVED** [review]

**Review by yiwu-arbug — APPROVED** [review]
LGTM

**Comment by breeswish** [comment]
Could you try with multiple TiKV instances? I guess a `SUM()` may need to be added (See https://github.com/tikv/tikv/pull/8991#issuecomment-723968177)

**Comment by yiwu-arbug** [comment]
> #8991 (comment)

sum across different instance is less meaningful though.

**Comment by tabokie** [comment]
> Could you try with multiple TiKV instances? I guess a `SUM()` may need to be added (See [#8991 (comment)](https://github.com/tikv/tikv/pull/8991#issuecomment-723968177))

You are right, and @yiwu-arbug I think by default `TiKV details` is a cluster-wise panel.

**Review by breeswish — APPROVED** [review]

**Pull request merged**
