### PR TITLE
security: add log redaction check (#9250)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #9250 to release-4.0

---

### What problem does this PR solve?

Issue Number: close https://github.com/tikv/tikv/issues/9249

Problem Summary:

Fix some logs not being redact when `security.redact-info-log = true`

### What is changed and how it works?

What's Changed:

We have added a script to find all occurrence of `hex::encode_upper`. If one is found in any file, then it will complain.

If you want to print key hex in log, you should always wrap it with `log_wrappers::Value::key(key)`.

If you really want to use `hex::encode_upper`, use `log_wrappers::encode_upper` instead.

### Check List 

Tests 

- Unit test

Side effects

### Release note 

Fix some logs not being redact when `security.redact-info-log = true`

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
@skyzh can you help resolve the conflict? thanks!

**Comment by skyzh** [comment]
> @skyzh can you help resolve the conflict? thanks!

Done, PTAL, thanks!

**Comment by gregwebs** [comment]
It looks like there is still a conflicting file?

**Comment by skyzh** [comment]
> It looks like there is still a conflicting file?

The master is updated again :(

I'll resolve conflict soon.

**Comment by skyzh** [comment]
I've resolved conflicts. PTAL, thanks!

**Review by yiwu-arbug — APPROVED** [review]
LGTM

**Review by BusyJay — APPROVED** [review]

**Comment by yiwu-arbug** [comment]
@zhouqiang-cl can we unfreeze the branch? thanks!

**Comment by zhouqiang-cl** [comment]
> @zhouqiang-cl can we unfreeze the branch? thanks!

No. we can not. 4.0.10 will release soon.

**Comment by yiwu-arbug** [comment]
@zhouqiang-cl thanks. I didn't notice the release plan. Sent merge request instead.

**Pull request merged**
