### PR TITLE
test: clean some fail_point after test finished

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: ref #15990

What's Changed:

```commit-message
Add some missing fail::remove
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by Connor1996** [comment]
> @Connor1996 @overvenus maybe we can change the `fail::cfg` interface to return a drop guard so manually call `fail::remove` is no longer needed in most cases, what do you think?

lgtm

**Comment by overvenus** [comment]
The `failpoints`'s custom_test_frameworks automatically remove all failpoints after tests finishes.

https://github.com/tikv/tikv/blob/0151ee39b1048bf598c902d0f7e4de9c1e4267fe/tests/failpoints/mod.rs#L5C27-L5C46

**Comment by glorv** [comment]
closed since the test framework can ensure all failpoints are cleaned after test finished.

**Pull request closed without merging**
