### PR TITLE
raftclient: enable delay only in high load (#11772)

### LINKED ISSUE #11769: 21% tps degradation on ycsb workloada from commit 74cd8a
### What version of TiKV are you using?

v5.4.0
### What operating system and CPU are you using?

x86-64
### Steps to reproduce

1

```
    export AWS_ACCESS_KEY_ID=xyz AWS_SECRET_ACCESS_KEY=xyz
    br restore db --db=test --pd "pd-peer:2379" \
        --storage "s3://benchmark/ycsb-100m-v5.0.0" \
        --s3.endpoint "http://xyz" \
        --send-credentials-to-tikv=true \
                --checksum-concurrency 64 \
                --check-requirements=false

go-ycsb run mysql -P /ycsb/workloads/workloada -p mysql.host=tiup-peer -p mysql.port=3390 -p recordcount=100000000 -p operationcount=50000000 -p workload=core -p fieldcount=10 -p fieldlength=100 -p threadcount=500 -p requestdistribution=zipfian
```

compared the ycsb workoada between 74cd8ae2a9ff930460cba15acdf1847726eb6db8 and the previous commit
### What did you expect?
no performance degradation

### What did happened?
21% tps degradation

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #11772, https://github.com/tikv/tikv/pull/11785, https://github.com/tikv/tikv/pull/11825 to release-5.3

You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/11844
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/11844:release-5.3-1859674c9da6
```

---

### What is changed and how it works?

Close #11769 

What's Changed:

#11705 adds delay to raft client, which can reduce syscalls and improve CPU efficiency under high load. But it turns out this can lead to significant regression in normal load. So this PR adds CPU stats and only enabling delay in high load.

This is also the same strategy used in v4.x.

### Check List 

Tests 

- Unit test
- Integration test
- Manual test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by glorv — APPROVED** [review]

**Review by Connor1996 — COMMENTED** [review]
why the difference is larger than original one

**Comment by glorv** [comment]
> why the difference is larger than original one

Jay cherry-pick another 3 PR into this PR manually.

**Comment by BusyJay** [comment]
> Jay cherry-picked another 3 PRs into this PR manually.

Yes. Sorry forget to change the description. I pick https://github.com/tikv/tikv/pull/11785, https://github.com/tikv/tikv/pull/11825 and https://github.com/tikv/tikv/pull/11772 just like #11845 did.

**Pull request merged**
