### PR TITLE
copr: vectorize LocateBinary3Args

### PR DESCRIPTION
**Pull request by MaiCw4J**
Signed-off-by: mak <610546069@qq.com>

PCP #5751 
###  What have you changed?

Add vectorized LocateBinary3Args

###  What is the type of the changes?

Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?
Please select the tests that you ran to verify your changes:
- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No. It should not change the behavior.

###  Does this PR affect `tidb-ansible`?

No

### CODE REVIEW

**Comment by MaiCw4J** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/64

**Comment by breeswish** [comment]
Please fix conflicts :(

**Comment by MaiCw4J** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/64

**Comment by MaiCw4J** [comment]
> Please change your copr-test to test against `locate`. There is no `locate_binary_3_args` in the `all_functions_reference.txt`.

i got it, I found that the `locate` test already exists ;)

**Comment by breeswish** [comment]
@MaiCw4J Yes! I just added it since I found there is already a PR did it.

**Pull request merged**
