### PR TITLE
raftstore/store: fix duplicated plus assign (#5038)

### PR DESCRIPTION
**Pull request by lonng**
## What have you changed? (mandatory)

Cherry-pick #5038 for release-3.0

### CODE REVIEW

**Comment by lonng** [comment]
@overvenus @BusyJay PTAL

**Comment by kennytm** [comment]
/run-integration-common-test tidb=release-3.0 pd=release-3.0 tidb-test=release-3.0

**Comment by kennytm** [comment]
/run-integration-common-test tidb=release-3.0 pd=release-3.0 tidb-test=release-3.0

**Comment by lonng** [comment]
/run-integration-common-test tidb=release-3.0 pd=release-3.0 tidb-test=release-3.0

**Comment by kennytm** [comment]
/run-integration-common-test tidb=release-3.0 pd=release-3.0 tidb-test=release-3.0

**Pull request merged**
