### PR TITLE
Update procinfo-rs to support pid status parse in kernel 5.x (#12263)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #12263 to release-6.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/12265
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/12265:release-6.0-e08932448738
```

---

Signed-off-by: Xintao <hunterlxt@live.com>

### What is changed and how it works?

Issue Number: Close #xxx

FYI https://github.com/tikv/procinfo-rs/pull/12

What's Changed:

```commit-message
Update procinfo-rs to support pid status parse in kernel 5.x.
```

### Related changes

- Need to cherry-pick to the release 6.0 branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

Side effects

None

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tabokie — APPROVED** [review]

**Comment by hunterlxt** [comment]
@VelocityLight PTAL

**Review by hunterlxt — APPROVED** [review]

**Comment by you06** [comment]
Can't believe it can suffer failure from fetching the package 2 times.

**Comment by hunterlxt** [comment]
Congratulations @you06

**Pull request merged**
