### PR TITLE
In-memory engine: enable compaction filter for HybridEngine

### LINKED ISSUE #17086: implement missing part of compaction filter for in-memory engine
## Development Task
Compaction Filter is not implemented for HybridEngine. It may not be easily implemented for HybridEngine directly cause RocksEngine is directly used in GcContext :
```
pub struct GcContext {
    pub(crate) db: Option<RocksEngine>,
    pub(crate) store_id: u64,
    pub(crate) safe_point: Arc<AtomicU64>,
    pub(crate) cfg_tracker: GcWorkerConfigManager,
    feature_gate: FeatureGate,
    pub(crate) gc_scheduler: Scheduler<GcTask<RocksEngine>>,
    pub(crate) region_info_provider: Arc<dyn RegionInfoProvider + 'static>,
    #[cfg(any(test, feature = "failpoints"))]
    callbacks_on_drop: Vec<Arc<dyn Fn(&WriteCompactionFilter) + Send + Sync>>,
}
```
We may implement it by using the disk_engine of HybridEngine.

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
### What is changed and how it works?

Issue Number: Close #17086 Ref #16141

What's Changed:

```commit-message
enable compaction filter for HybridEngine
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by SpadeA-Tang** [comment]
Maybe a manual test for this is suffient? @overvenus

**Review by overvenus — APPROVED** [review]
LGTM

**Review by LykxSassinator — APPROVED** [review]
LGTM

**Pull request merged**
