### PR TITLE
*: replace crc by crc32fast and crc64fast

### PR DESCRIPTION
**Pull request by kennytm**
###  What have you changed?

Replaced all direct use of the [`crc` package](https://github.com/mrhooray/crc-rs) by either [`crc32fast`](https://github.com/srijs/rust-crc32fast) or [`crc64fast`](https://github.com/tikv/crc64fast).

Both packages use the PCLMULQDQ instruction to speed up CRC calculation by 35–50× on x86_64 (for long input), and use batch processing on other CPUs which still give 5–7× speed improvement. 

TiDB's `ADMIN CHECKSUM TABLE` itself uses crc64 on each KV pair individually. Usually the entries are short (less than 1 KiB each) and iteration also takes time, so the speed up is less dramatic, but still there is 20% improvement.

<details><summary>Simple timing on ADMIN CHECKSUM TABLE of a 2 GiB table</summary>

Before this PR:

```
mysql> admin checksum table testdb.s0;
+---------+------------+---------------------+-----------+-------------+
| Db_name | Table_name | Checksum_crc64_xor  | Total_kvs | Total_bytes |
+---------+------------+---------------------+-----------+-------------+
| testdb  | s0         | 1750840243208935704 |   7601472 |  2284061381 |
+---------+------------+---------------------+-----------+-------------+
1 row in set (4.93 sec)
```

After this PR:

```
mysql> admin checksum table testdb.s0;
+---------+------------+---------------------+-----------+-------------+
| Db_name | Table_name | Checksum_crc64_xor  | Total_kvs | Total_bytes |
+---------+------------+---------------------+-----------+-------------+
| testdb  | s0         | 1750840243208935704 |   7601472 |  2284061381 |
+---------+------------+---------------------+-----------+-------------+
1 row in set (3.94 sec)
```

</details>

###  What is the type of the changes?

Pick one of the following and delete the others:

- Engineering (engineering change which doesn't change any feature or fix any issue)

###  How is the PR tested?
Please select the tests that you ran to verify your changes:

- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No

###  Does this PR affect `tidb-ansible`?

No

### CODE REVIEW

**Comment by kennytm** [comment]
@Connor1996 updated to include the result of ADMIN CHECKSUM TABLE. As for the micro-benchmark of the CRC routines themselves, they are already documented in the README of the two projects respectively.

PTAL @overvenus, maybe you could include the result from BR as you've got the first-hand information 🙂.

**Comment by overvenus** [comment]
From flame graphs during backup, crc64fast improves a lot.

The crc crate:

image

The crc64fast crate:
 
image

**Comment by kennytm** [comment]
(#5676)

**Comment by kennytm** [comment]
Resolved merge conflict with #5975, PTAL again @Connor1996 @overvenus thanks.

**Pull request merged**
