### PR TITLE
resolved_ts: fix resolved_ts can't update after merge

### PR DESCRIPTION
**Pull request by NingLin-P**
Signed-off-by: linning <linningde25@gmail.com>

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

https://github.com/tikv/tikv/pull/10215 add the `last_merge_index` check to reject stale `(index, ts)` item, but if the region did not has any incoming write after merge, `idx <= self.last_merge_index` will reject any incoming `(index, ts)` item where the `idx` is equal to `last_merge_index`

### What is changed and how it works?

What's Changed:

Change `idx <= self.last_merge_index` to `idx < self.last_merge_index`

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

### Release note 

```release-note
fix resolved_ts can't update after merge
```

### CODE REVIEW

**Review by nolouch — APPROVED** [review]
lgtm

**Comment by nolouch** [comment]
@NingLin-P  ci failed

**Review by JmPotato — APPROVED** [review]

**Pull request merged**
