### PR TITLE
server: make grpc metrics consistent

### PR DESCRIPTION
**Pull request by bufferflies**
### What is changed and how it works?

Issue Number: : ref https://github.com/tikv/tikv/issues/15803

What's Changed:

```commit-message
the grpc duration should not  include the stream sink.
```

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by SpadeA-Tang — APPROVED** [review]

**Review by HuSharp — APPROVED** [review]
please link issue

**Review by Connor1996 — APPROVED** [review]
Please follow the PR title format which starts with the component name

**Pull request merged**
