### PR TITLE
pd_client: replace PD_REQUEST_HISTOGRAM_VEC with static metrics

### LINKED ISSUE #14086: replace pd_client PD_REQUEST_HISTOGRAM_VEC with static metrics
## Development Task

PD_REQUEST_HISTOGRAM_VEC can be changed to use static metrics to improve performance.

### PR DESCRIPTION
**Pull request by HuSharp**
Signed-off-by: husharp <jinhao.hu@pingcap.com>

### What is changed and how it works?

Issue Number: Close #14086

What's Changed:

```commit-message
PD_REQUEST_HISTOGRAM_VEC can be changed to use static metrics to improve performance.
```

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by JmPotato — APPROVED** [review]

**Comment by HuSharp** [comment]
@Connor1996 can u leave a `merge`? Thx! :)

**Pull request merged**
