### PR TITLE
Extract txn types component

### PR DESCRIPTION
**Pull request by Connor1996**
###  What have you changed?
Extract txn related types to a new component, so that `sst_importer` can use them to parse the key and value. This PR changes:
- move `UnixSecs` from `component/keys` to `component/tikv_util`
- move `timestamps.rs` and `types.rs` from `component/keys` to new `component/txn_types`
- extract `Mutation`, `write.rs` and `lock.rs` from `raftstore` to new `component/txn_types`

###  What is the type of the changes?
- Engineering (engineering change which doesn't change any feature or fix any issue)

###  How is the PR tested?
- No code

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?
No

###  Does this PR affect `tidb-ansible`?
No

### CODE REVIEW

**Comment by sticnarf** [comment]
Why can't sst_importer just use them in the keys crate?

**Comment by Connor1996** [comment]
@sticnarf keys crate mixes up the region key with txn related types, so divide into two components to make the logic clear.

**Pull request merged**
