### PR TITLE
copr: early stop paging copr when resultset is drained.

### LINKED ISSUE #14254: copr: paging not stop with limit executor
### What version of TiKV are you using?

```
TiKV 
Release Version:   6.7.0-alpha
Edition:           Community
Git Commit Hash:   061d874c297307a0c6184d827577c58378ae4b72
Git Commit Branch: heads/refs/tags/v6.7.0-alpha
UTC Build Time:    2023-02-21 14:34:16
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
```

### What operating system and CPU are you using?

x64 CPU.

### Steps to reproduce

Run the latest tikv with tidb v6.5.0.

Prepare

```sql
CREATE TABLE t(id int PRIMARY KEY, val int)
PARTITION BY RANGE (id)
(PARTITION p1 VALUES LESS THAN (100),
 PARTITION p2 VALUES LESS THAN (200),
 PARTITION p3 VALUES LESS THAN (300));

INSERT INTO t VALUES(50, 50), (51, 51), (52, 52), (53, 53), (150, 150), (250, 250);
ANALYZE TABLE t;
```

Run

```sql
TRACE SELECT * FROM t ORDER BY id ASC LIMIT 1;
```

### What did you expect?

Only one task to each partition because it's limit 1.

### What did happened?

The paging request is calling repeatly.

```sql
MySQL [test]> TRACE SELECT * FROM t ORDER BY id ASC LIMIT 1;
+-------------------------------------------------------------------------------+-----------------+------------+
| operation                                                                     | startTS         | duration   |
+-------------------------------------------------------------------------------+-----------------+------------+
| trace                                                                         | 13:42:52.980185 | 7.519375ms |
|   ├─session.ExecuteStmt                                                       | 13:42:52.980194 | 638.348µs  |
|   │ ├─executor.Compile                                                        | 13:42:52.980229 | 283.415µs  |
|   │ └─session.runStmt                                                         | 13:42:52.980537 | 272.381µs  |
|   │   └─TableReaderExecutor.Open                                              | 13:42:52.980669 | 96.38µs    |
|   │     └─distsql.Select                                                      | 13:42:52.980693 | 60.134µs   |
|   │       ├─regionRequest.SendReqCtx                                          | 13:42:52.980916 | 942.087µs  |
|   │       │ ├─rpcClient.SendRequest, region ID: 98, type: Cop                 | 13:42:52.980966 | 860.443µs  |
|   │       │ │ └─tikv.RPC                                                      | 13:42:52.980972 | 432.666µs  |
|   │       │ │   └─tikv.Wait                                                   | 13:42:52.980972 | 99.314µs   |
|   │       │ │     └─tikv.GetSnapshot                                          | 13:42:52.980972 | 99.314µs   |
|   │       │ └─regionRequest.SendReqCtx                                        | 13:42:52.981908 | 740.805µs  |
|   │       │   ├─rpcClient.SendRequest, region ID: 98, type: Cop               | 13:42:52.981936 | 686.328µs  |
|   │       │   │ └─tikv.RPC                                                    | 13:42:52.981944 | 304.019µs  |
|   │       │   │   └─tikv.Wait                                                 | 13:42:52.981944 | 36.318µs   |
|   │       │   │     └─tikv.GetSnapshot                                        | 13:42:52.981944 | 36.318µs   |
|   │       │   └─regionRequest.SendReqCtx                                      | 13:42:52.982701 | 562.919µs  |
|   │       │     ├─rpcClient.SendRequest, region ID: 98, type: Cop             | 13:42:52.982733 | 517.313µs  |
|   │       │     │ └─tikv.RPC                                                  | 13:42:52.982737 | 252.825µs  |
|   │       │     │   └─tikv.Wait                                               | 13:42:52.982737 | 27.098µs   |
|   │       │     │     └─tikv.GetSnapshot                                      | 13:42:52.982737 | 27.098µs   |
|   │       │     └─regionRequest.SendReqCtx                                    | 13:42:52.983291 | 541.478µs  |
|   │       │       ├─rpcClient.SendRequest, region ID: 98, type: Cop           | 13:42:52.983311 | 502.926µs  |
|   │       │       │ └─tikv.RPC                                                | 13:42:52.983314 | 231.314µs  |
|   │       │       │   └─tikv.Wait                                             | 13:42:52.983314 | 20.253µs   |
|   │       │       │     └─tikv.GetSnapshot                                    | 13:42:52.983314 | 20.253µs   |
|   │       │       └─regionRequest.SendReqCtx                                  | 13:42:52.983871 | 597.84µs   |
|   │       │         └─rpcClient.SendRequest, region ID: 98, type: Cop         | 13:42:52.983892 | 559.009µs  |
|   │       │           └─tikv.RPC                                              | 13:42:52.983895 | 270.215µs  |
|   │       │             └─tikv.Wait                                           | 13:42:52.983895 | 22.768µs   |
|   │       │               └─tikv.GetSnapshot                                  | 13:42:52.983895 | 22.768µs   |
|   │       ├─regionRequest.SendReqCtx                                          | 13:42:52.984562 | 862.957µs  |
|   │       │ ├─rpcClient.SendRequest, region ID: 100, type: Cop                | 13:42:52.984585 | 814.907µs  |
|   │       │ │ └─tikv.RPC                                                      | 13:42:52.984588 | 417.091µs  |
|   │       │ │   └─tikv.Wait                                                   | 13:42:52.984588 | 141.637µs  |
|   │       │ │     └─tikv.GetSnapshot                                          | 13:42:52.984588 | 141.637µs  |
|   │       │ └─regionRequest.SendReqCtx                                        | 13:42:52.985471 | 597.141µs  |
|   │       │   └─rpcClient.SendRequest, region ID: 100, type: Cop              | 13:42:52.985513 | 535.891µs  |
|   │       │     └─tikv.RPC                                                    | 13:42:52.985517 | 216.368µs  |
|   │       │       └─tikv.Wait                                                 | 13:42:52.985517 | 21.511µs   |
|   │       │         └─tikv.GetSnapshot                                        | 13:42:52.985517 | 21.511µs   |
|   │       └─regionRequest.SendReqCtx                                          | 13:42:52.986157 | 718.665µs  |
|   │         ├─rpcClient.SendRequest, region ID: 10, type: Cop                 | 13:42:52.986193 | 647.567µs  |
|   │         │ └─tikv.RPC                                                      | 13:42:52.986197 | 243.047µs  |
|   │         │   └─tikv.Wait                                                   | 13:42:52.986197 | 84.647µs   |
|   │         │     └─tikv.GetSnapshot                                          | 13:42:52.986197 | 84.647µs   |
|   │         └─regionRequest.SendReqCtx                                        | 13:42:52.986952 | 596.513µs  |
|   │           └─rpcClient.SendRequest, region ID: 10, type: Cop               | 13:42:52.986990 | 544.551µs  |
|   │             └─tikv.RPC                                                    | 13:42:52.986994 | 236.203µs  |
|   │               └─tikv.Wait                                                 | 13:42:52.986994 | 28.914µs   |
|   │                 └─tikv.GetSnapshot                                        | 13:42:52.986994 | 28.914µs   |
|   ├─*executor.TopNExec.Next                                                   | 13:42:52.980851 | 6.792049ms |
|   │ ├─*executor.TableReaderExecutor.Next                                      | 13:42:52.980863 | 1.146303ms |
|   │ ├─*executor.TableReaderExecutor.Next                                      | 13:42:52.982048 | 5.549715ms |
|   │ └─*executor.TableReaderExecutor.Next                                      | 13:42:52.987615 | 17.6µs     |
|   └─*executor.TopNExec.Next                                                   | 13:42:52.987658 | 2.375µs    |
+-------------------------------------------------------------------------------+-----------------+------------+
56 rows in set (0.009 sec)
```

### PR DESCRIPTION
**Pull request by you06**
Signed-off-by: you06 <you1474600@gmail.com>

### What is changed and how it works?

Issue Number: Close #14254

What's Changed:

```commit-message
When the result set is drained, it indicates that no more data is required in the range.
This PR set the scanned range to None to avoid the following paging requests in the current range.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
- Breaking backward compatibility

### Release note 

```release-note
copr: reduce latency and resource usage of the paging protocol by early stop.
```

### CODE REVIEW

**Review by tiancaiamao — COMMENTED** [review]
LGTM, though my reivew does not count.

**Review by cfzjywxk — APPROVED** [review]

**Review by wshwsh12 — APPROVED** [review]

**Pull request merged**
