### PR TITLE
txn: don't require min_commit_ts to be zero in async commit

### PR DESCRIPTION
**Pull request by youjiali1995**
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### What problem does this PR solve?

Problem Summary:

Async commit doesn't require the `min_commit_ts` to be zero. As long as it's not changed after prewrite, it can meet the requirement.

### What is changed and how it works?

What's Changed:
Remove the assert.

### Check List 

Tests 

- No code

Side effects

### Release note 
* No release note

### CODE REVIEW

**Comment by cfzjywxk** [comment]
LGTM

**Comment by sticnarf** [comment]
LGTM

**Comment by MyonKeminta** [comment]
ah, why is this closed?

**Comment by nrc** [comment]
> ah, why is this closed?

@youjiali1995 PTAL

**Comment by youjiali1995** [comment]
It has removed by https://github.com/tikv/tikv/pull/8363. @nrc @MyonKeminta

**Pull request closed without merging**
