### PR TITLE
raft-engine: update raft-engine to newest version

### LINKED ISSUE #15462: [Dynamic Regions] periodical performance jitter due to raft-engine log recycle
### What version of TiKV are you using?

nightly

### What operating system and CPU are you using?

aws ec2 m52xlarge(8c64gb with 4000iops 288MB io-bandwidth)

### Steps to reproduce

Deploy a tidb cluster with 1 tikv instance and set replica-count = 1 
use sysbench to  prepare 32 tables with each 10000000 rows of data.
Run sysbench oltp_write_only workload.

The sysbench  scripts is customized with a padding field of 3kb:
```
 CREATE TABLE `sbtest1` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `k` bigint(20) NOT NULL DEFAULT '0',
  `c` varchar(300) NOT NULL DEFAULT '',
  `pad` varchar(3000) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `k_1` (`k`)
)
```

### What did you expect?
The performance should be stable when the workload doesn't reach any of the hardware bottleneck.

### What did happened?
The qps is unstable and the qps dropped period match the period when raft-engine's `append-recycle` files count is 0.

image

852d002f-c109-4aeb-b815-c3d027d238bc

fea554bf-838d-4c72-be66-fe0062a5551c

From the snapshot I can see when the `append-recycle` files count drops to 0 the write duration increases drastically

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: Close #15462

What's Changed:

Update raft-engine to include https://github.com/tikv/raft-engine/pull/331

```
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tonyxuqqi — APPROVED** [review]

**Comment by tonyxuqqi** [comment]
@glorv There're build errors

**Comment by glorv** [comment]
I saw the clippy error is related to fail-point, seems clippy can't recognize that failpoint! macro is only enabled under feature `failpoint`, it should be a false-positive error. Will take a look again after #15584 is merge. Maybe the newer compiler already optimized this issue.

**Comment by glorv** [comment]
@Connor1996  PTAL

**Review by Connor1996 — APPROVED** [review]
LGTM

**Pull request merged**
