### PR TITLE
raftstore: check state after resuming apply fsm

### PR DESCRIPTION
**Pull request by gengliqi**
Signed-off-by: Liqi Geng <gengliqiii@gmail.com>

### What problem does this PR solve?

Problem Summary:

### What is changed and how it works?

In https://github.com/tikv/tikv/pull/6487, we introduce a new case to interrupt the execution of apply fsm except merging. Applying log after resuming may encounter another yield or commit merge, but we can't release this apply fsm if it is interrupted due to yield. (The source region will send a message to the target region if it has applied all needed logs so we can safely release the target region's apply fsm.)
If we release apply fsm incorrectly and this region A should be merged another region B, region A and B may be stuck forever because no new message will be sent to A and B still wait for A to apply all needed logs. 

### Related changes

- Need to cherry-pick to the release branch
Need to cherry-pick to release 3.0, 3.1, 4.0 and 3.0.5.hotfix

### Check List 

Tests 

- Integration test

Side effects

No.

### Release note 
Fix an issue that a region may be stuck during multi-times merging

### CODE REVIEW

**Comment by BusyJay** [comment]
The test fails occasionally on my local machine
```
thread 'raftstore::test_merge::test_merge_cascade_merge_isolated' panicked at 'region id: 1000 end_key: 6B32 region_epoch { conf_ver: 1 version: 2 } peers { id: 1001 store_id: 1 } peers { id: 1002 store_id: 2
} peers { id: 1003 store_id: 3 } is still not merged.', components/test_raftstore/src/pd.rs:904:21
```

**Comment by gengliqi** [comment]
> The test fails occasionally on my local machine
> 
> ```
> thread 'raftstore::test_merge::test_merge_cascade_merge_isolated' panicked at 'region id: 1000 end_key: 6B32 region_epoch { conf_ver: 1 version: 2 } peers { id: 1001 store_id: 1 } peers { id: 1002 store_id: 2
> } peers { id: 1003 store_id: 3 } is still not merged.', components/test_raftstore/src/pd.rs:904:21
> ```

Because there may be some leader on store 3 which will be isolated soon. I add some transfer leader to make test stable.

**Comment by BusyJay** [comment]
May need to pick to 3.0.5-hotfix /cc @AndreMouche

**Pull request merged**
