### PR TITLE
cdc: reduce resolved ts message size

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/ticdc/issues/2448

Problem Summary:

Reduce resolved ts message size to save network bandwidth.

### What is changed and how it works?

What's Changed:

Only attaching region ids that are captured by connections.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
Reduce resolved ts message size to save network bandwidth.
```

### CODE REVIEW

**Comment by liuzix** [comment]
Is it possible to maintain the list of all subscribed regions as a `hashset`, and pass the resolved regions in as a `vector`? This way we can avoid having to build a hashset whenever we want to send a resolved event, saving some CPU.

**Comment by overvenus** [comment]
> Is it possible to maintain the list of all subscribed regions as a `hashset`, and pass the resolved regions in as a `vector`? This way we can avoid having to build a hashset whenever we want to send a resolved event, saving some CPU.

It can save some CPU, although I don't think it the bottleneck for now. In tests, capturing 10k region takes ~1.5% CPU.

**Comment by hi-rustin** [comment]
/cc

I will help look at it tonight or tomorrow.

**Review by liuzix — APPROVED** [review]

**Review by 5kbpers — APPROVED** [review]

**Pull request merged**
