### PR TITLE
copr: Vectorize `uncompress`.

### PR DESCRIPTION
**Pull request by cireu**
Signed-off-by: Zhu Zihao <all_but_last@163.com>

PCP #5751 

###  What have you changed?
Vectorize `uncompress`

###  What is the type of the changes?

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?
Please select the tests that you ran to verify your changes:
- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No

###  Does this PR affect `tidb-ansible`?
No

### CODE REVIEW

**Comment by cireu** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/85

**Comment by cireu** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/85

**Comment by breeswish** [comment]
@shafreeck @tabokie PTAL, thanks!

**Comment by breeswish** [comment]
@cireu Please fix conflicts. Thank you!

**Comment by cireu** [comment]
> @cireu Please fix conflicts. Thank you!

Done.

**Comment by cireu** [comment]
> Looks like your implementation have some issues, please fix it:
> 
> https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_integration-copr-test/detail/tikv_ghpr_integration-copr-test/1134/pipelin

**Comment by cireu** [comment]
Close accidentally. I will reopen it

**Comment by cireu** [comment]
> Looks like your implementation have some issues, please fix it:
> 
> https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_integration-copr-test/detail/tikv_ghpr_integration-copr-test/1134/pipeline

A guess, the rpn function create a lot of `ZlibDecoder` and runs out of memory.

**Comment by tabokie** [comment]
@cireu you might need [this](https://gist.github.com/robertpainsi/2c42c15f1ce6dab03a0675348edd4e2c) to reopen the PR.

**Pull request closed without merging**
