### PR TITLE
in_memory_engine: do not force disable in memory engine for replica read

### PR DESCRIPTION
**Pull request by glorv**
This reverts commit e7a810b8947ba95117d42f45bf14248eea06a5b5.

### What is changed and how it works?

Issue Number: ref #16141

What's Changed:

```commit-message
This commit rollback PR #17927 as it is not the root cause. This rollback can all use IME for following read scenario. 
NOTE: We decide not cherry-pick it back to v8.5 as there may be other potential issue.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]

**Comment by glorv** [comment]
@Connor1996 @hbisheng PTAL

**Review by Connor1996 — APPROVED** [review]

**Pull request merged**
