### PR TITLE
config: deprecated rocksdb log configs

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: ref #15990

What's Changed:

```commit-message
The rocksdb log is replace by tikv log in #7358 about 4 years ago. After this PR, rocksdb configs `info_log_max_size`, `info_log_roll_time`, `info_log_keep_log_file_num` and `info_log_level` are no long taken effect. This PR marks these configs as deprecated and clean up related code.
```

### Related changes

- [x] PR to update `pingcap/docs`/`pingcap/docs-cn`: https://github.com/pingcap/docs-cn/pull/17321
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by zhangjinpeng87** [comment]
How about existing clusters already used rocksdb log configs upgrade to the new version?

**Comment by glorv** [comment]
> How about existing clusters already used rocksdb log configs upgrade to the new version?

@zhangjinpeng87 The behavior is not changed, that is, from v5.0, rocksdb log config won't take effect anymore.

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by zhangjinpeng87 — APPROVED** [review]
LGTM

**Comment by glorv** [comment]
@cfzjywxk PTAL

**Review by cfzjywxk — APPROVED** [review]

**Pull request merged**
