### PR TITLE
rocksdb: reduce rocksdb block size to 16KB

### LINKED ISSUE #14052: RocksDB block size (64KB) is not efficient for heavy head scenario
Consider to change it to 16KB by default.

### PR DESCRIPTION
**Pull request by tonyxuqqi**
Signed-off-by: Qi Xu <tonyxuqqi@outlook.com>

### What is changed and how it works?

Issue Number: Close #14052

What's Changed:

```commit-message
The writecf and defaultcf's default block size is changed to 16KB to improve read performance (reduce read amplification)
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more IOPS
- Breaking backward compatibility

### Release note 

```release-note
Change the default value of rocksdb's defaultcf and write fc's SST block size from 64KB to 16KB. 
This change can improve read performance by reducing read amplification and improve the block cache utilization, at the cost of needing more IOPS. It's estimated to have 1.4 times IOPS of the original setting. 
```

### CODE REVIEW

**Comment by BusyJay** [comment]
Any test report?

**Comment by tonyxuqqi** [comment]
> Any test report?
The multi-rocksdb and single-rocksdb tpcc result is the proof.

**Review by tabokie — COMMENTED** [review]
Sysbench point-select and read-only would be more persuasive (with small and large memory). Also this change would require updating dataset for benchbot etc.

**Comment by tonyxuqqi** [comment]
> Sysbench point-select and read-only would be more persuasive (with small and large memory). Also this change would require updating dataset for benchbot etc.

QPS comparison

block-size | 4KB | 8KB | 16KB | 32KB | 48KB | 64KB | 128KB | 256KB
point_select | 18610.19 | 18510.92 | 18342.34 | 18397.36 | 18630.23 | 17708.04 | 15059.51 | 13280.67
read_only | 676.23 | 673.76 | 680.13 | 666.84 | 656.87 | 668.61 | 601.21 | 625.11
update_index | 1213.41 | 1293.45 | 1281.39 | 1284.23 | 1311.48 | 1277.53 | 1206.97 | 1145.58
insert | 1442.53 | 1415.76 | 1448.68 | 1480.1 | 1461.75 | 1429.91 | 1426.27 | 1377.59
read_write | 438.4 | 429.78 | 440.78 | 436.18 | 440.02 | 429.25 | 420.08 | 400.91

From TPS perspective, it's roughly same. 
But the key is read amplification, in point select, the 16KB block size is only have 5.7x read amplification and the 64KB has 12.1 read amplification.  This will greatly improve the multiple index lookup scenario where TiDB's performance is not outstanding.

**Review by BusyJay — APPROVED** [review]
The large block size can reduce filter/index size. Please make sure it will not cause other problems like lower hit rate or OOM.

**Review by tabokie — APPROVED** [review]

**Pull request merged**
