### PR TITLE
metrics: add grafana and alertmanager scripts

### PR DESCRIPTION
**Pull request by lucklove**
Signed-off-by: lucklove <gnu.crazier@gmail.com>

###  What have you changed?

To maintain the grafana and alert manager scripts in TiKV repo, I add a directory to store grafana config files from tidb-ansible repo.
There are some scripts in overview.json, I don't know how to maintain them.

###  What is the type of the changes?

- Misc (other changes)

###  How is the PR tested?

- No code

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No

###  Does this PR affect `tidb-ansible`?

No

### CODE REVIEW

**Comment by lucklove** [comment]
@mahjonp PTAL

**Comment by siddontang** [comment]
any reason why to add these in TiKV repo directly?

how to manage the configs in tidb-ansible at the same time?

**Comment by liubo0127** [comment]
Maybe also need to add `br.json`.

**Comment by lucklove** [comment]
> Maybe also need to add `br.json` `performance_write.json` `performance_read.json`.

has add performance_write.json and performance_read.json, but it seems br is a standalone project, maybe br.json should be add to https://github.com/pingcap/br

**Comment by zhouqiang-cl** [comment]
@zhangjinpeng1987 PTAL too

**Pull request merged**
