### PR TITLE
test: fix test test_ingest_key_manager_delete_file_failed (#9150)

### LINKED ISSUE #9138: cases::test_import_service::test_ingest_key_manager_delete_file_failed failed
cases::test_import_service::test_ingest_key_manager_delete_file_failed

 Latest failed builds: 
https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/36408/consoleFull

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #9150 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #9138

Problem Summary:

### What is changed and how it works?
Add a loop of sleep to wait until the async action `clean sst` finished before exec the second upload.

### Check List 

Tests 
- Unit test

Side effects

### Release note 
- No Release Note

### CODE REVIEW

**Review by kennytm — APPROVED** [review]
LGTM

**Comment by overvenus** [comment]
LGTM

**Comment by glorv** [comment]
So we should wait until v4.0.9 is released to merge this pr.

**Review by BusyJay — APPROVED** [review]

**Pull request merged**
