### PR TITLE
[release-2.1] cherry-pick: Add end_key limit to kv_scan interface (#3720)

### PR DESCRIPTION
**Pull request by MyonKeminta**
## What have you changed? (mandatory)

This PR cherry-picks #3720 to release-2.1 branch.

## What are the type of the changes? (mandatory)

- Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)

By CI

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

No.

## Does this PR affect tidb-ansible update? (mandatory)

No.

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
Please fix conflict.

**Comment by hicqu** [comment]
LGTM.

**Comment by MyonKeminta** [comment]
Can this be merged?

**Comment by MyonKeminta** [comment]
@zhangjinpeng1987 PTAL

**Pull request merged**
