### PR TITLE
copr: add vectorized truncate_decimal()

### PR DESCRIPTION
**Pull request by mashenjun**
Signed-off-by: mashenjun <mashenjun0902@gmail.com>

### What problem does this PR solve?

Issue Number: part of #9016

Problem Summary:

### What is changed and how it works?

What's Changed: 
add `fn truncate_decimal` for vectorized framework

### Check List 

Tests 

- Unit test under `impl_math.rs`

### Release note 
- No release note

### CODE REVIEW

**Comment by Xuanwo** [comment]
Hi, this pr is duplicated with https://github.com/tikv/tikv/pull/9618, please check its progress to avoid duplication of work.

**Comment by mashenjun** [comment]
ok, I will close this one and try others.

**Pull request closed without merging**
