### PR TITLE
pessimistic-txn: support lock wait timeout (#5680)

### PR DESCRIPTION
**Pull request by youjiali1995**
###  What have you changed?
Cherry pick #5680

### CODE REVIEW

**Comment by youjiali1995** [comment]
@MyonKeminta @sticnarf @AndreMouche PTAL

**Comment by youjiali1995** [comment]
@MyonKeminta @AndreMouche PTAL. I have added it to release note and https://github.com/pingcap/tidb/pull/13165 is merging.

**Comment by coocood** [comment]
LGTM

**Comment by youjiali1995** [comment]
@MyonKeminta @AndreMouche PTAL. Thanks!

**Pull request merged**
