### PR TITLE
No dynamic allocations in Decimal

### PR DESCRIPTION
**Pull request by breeswish**
## What have you changed? (mandatory)

This PR removes the dynamic allocation in Decimal. Previously we did that to reduce the struct size of Decimal, however it is rarely useful since:

1. In non-batch executors, the unit of single operation is `Datum`, whose size is already large enough due to https://github.com/chronotope/chrono-tz/issues/27 so that reducing Decimal size does not have effect.

2. In batch executors, the unit of single operation is `Vec`, whose size does not depend on the size of `Decimal`.

## What are the type of the changes? (mandatory)

- Improvement (change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)

No need.

## Benchmark result if necessary (optional)

TPC-H Q1 improved by 20%

### CODE REVIEW

**Comment by sticnarf** [comment]
Could you edit the pr description stating that Decimal is rarely moved, so we are inclined to save the allocatio instead of controlling the struct size?

**Comment by breeswish** [comment]
@sticnarf Done.

**Comment by siddontang** [comment]
@breeswish 

can you paste the detailed benchmark result?

**Comment by breeswish** [comment]
@siddontang TPC-H Q1 (Scale Factor = 10) improved from 15s to 12s. Other queries are not tested since this outcome is effective enough.

**Pull request merged**
