### PR TITLE
raftstore: log not matched store

### PR DESCRIPTION
**Pull request by BusyJay**
## What have you changed? (mandatory)

We need to report store id in v2.1.x too.

## What are the type of the changes? (mandatory)

- Improvement

## Does this PR affect documentation (docs) update? (mandatory)

No.

## Does this PR affect tidb-ansible update? (mandatory)

No.

## Refer to a related PR or issue link (optional)

#3885

### CODE REVIEW

**Comment by BusyJay** [comment]
/run-all-tests tidb=release-2.1 pd=release-2.1 tidb-test=release-2.1

**Comment by AndreMouche** [comment]
test failed, seems caused by the wrong version of `kvproto`?

**Comment by BusyJay** [comment]
Seems kvproto is updated before #4284 is ready.

**Comment by overvenus** [comment]
Cherry-picked on #4284 .

**Comment by BusyJay** [comment]
PTAL, /release

**Pull request merged**
