### PR TITLE
inline values to write cf whose size <= 255 bytes

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
Signed-off-by: zhangjinpeng1987 <zhangjinpeng@pingcap.com>

###  What have you changed?

Change short value upper limit from 64 to 255, so these values whose size le 255 bytes can be inlined in write cf, this can improve the point select queries.

###  What is the type of the changes?

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?

- [x] sysbench insert test
sysbench insert test shows there is no regression.

- [x] sysbench point select test
sysbench point select test show there is 10% improvement in this case.

```
short value = 255
mysql> set @@tidb_distsql_scan_concurrency=1;
mysql> select count(1) from sbtest1;
+----------+
| count(1) |
+----------+
|  1000000 |
+----------+
1 row in set (0.67 sec)

short value = 64
mysql> set @@tidb_distsql_scan_concurrency=1;
mysql> select count(*) from sbtest1;
+----------+
| count(*) |
+----------+
|  1000000 |
+----------+
1 row in set (0.62 sec)
```

- [x] bench var u16 encode/decode VS read u8

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No

###  Does this PR affect `tidb-ansible`?

No

### CODE REVIEW

**Comment by lonng** [comment]
Is there any compatible issue?

**Comment by hicqu** [comment]
How about change the len field to variable codec? Here is a benchmark result:
```
test bench_parse_u8    ... bench:         960 ns/iter (+/- 8)
test bench_parse_var64 ... bench:       7,186 ns/iter (+/- 180)
```
And it's compatible with fixed-len codec because the old limit is `64`, which is less than `128`.

**Comment by breeswish** [comment]
@hicqu According to the benchmark, parse var64 is notably slower. Why do we need to switch to it?

**Comment by zhangjinpeng1987** [comment]
The point select doesn't make too much difference in CI bench is because the dataset is in old format which short value is 64.

**Pull request merged**
