### PR TITLE
tests: replace `std::time::SystemTime` with `std::time::Instant`

### PR DESCRIPTION
**Pull request by lhy1024**
Signed-off-by: lhy1024 <admin@liudos.us>

### What is changed and how it works?

According to https://github.com/tikv/tikv/pull/10386/files#r874333838

Tests 

- Unit test

### Release note 

```release-note
None.

```

### CODE REVIEW

**Review by sticnarf — APPROVED** [review]

**Review by BusyJay — APPROVED** [review]

**Comment by lhy1024** [comment]
@BusyJay @sticnarf

**Comment by BusyJay** [comment]
I suggest to merge #12562 instead, which also makes some cases stable.

**Pull request closed without merging**
