### PR TITLE
import: remove verify checksum in apply thread (#10950)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #10950 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/11258
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/11258:release-5.1-2c742a1b8989
```

---

Signed-off-by: Little-Wallace <bupt2013211450@gmail.com>

### What problem does this PR solve?
close https://github.com/tikv/tikv/issues/11239
Problem Summary:
We introduce the method `verify_checksum` to apply_thread in this PR: https://github.com/tikv/tikv/pull/9924
But verify checksum will read the while file and it will block the apply thread too long.  Since 5.1 TiKV will ingest all file in one thread and it will make the problem worse.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
move verify_checksum to import-thread from apply-thread.
```

### CODE REVIEW

**Comment by sticnarf** [comment]
PTAL @3pointer @kennytm

**Comment by sticnarf** [comment]
@kennytm @3pointer @glorv PTAL

**Review by glorv — APPROVED** [review]

**Review by sticnarf — APPROVED** [review]

**Pull request merged**
