### PR TITLE
Fix incorrect processed / total keys counter (#7563)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #7563 to release-4.0

---

Signed-off-by: Breezewish <breezewish@pingcap.com>

### What problem does this PR solve?

This PR fixed incorrect processed_keys / total_keys passed to TiDB, as well as missing RocksDB metrics.

### What is changed and how it works?

1. Changed processed -> processed_versions (number of visible versions in write CF)
2. Changed total -> total_versions (**approximate** number of all meet versions in write CF)
3. Added RocksDB PerfContext to the Coprocessor response.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test: WIP

### Release note 

- Report RocksDB metrics to TiDB
- Fix incorrect process_keys and total_keys

### CODE REVIEW

**Review by iosmanthus — APPROVED** [review]
LGTM

**Comment by Connor1996** [comment]
@breeswish Please fix the conflict

**Comment by breeswish** [comment]
Close for https://github.com/tikv/tikv/pull/9316

**Pull request closed without merging**
