### PR TITLE
docs: fix the issue with the Slack link not allowing external users to join

### PR DESCRIPTION
**Pull request by hazel1225**
The original community entry link was limited to PingCAP internal members, and has now been replaced.

### What is changed and how it works?

Issue Number: ref #15990

What's Changed:

```commit-message

```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by you06 — APPROVED** [review]
LGTM to use the same link as [slack sector](https://github.com/tikv/tikv?tab=readme-ov-file#slack).

I take a look at a related PR and found this https://github.com/tikv/tikv/pull/9663#discussion_r579024694. While it's unlikely we'll ever see the feature on tikv.org, I personally prefer that approach.

**Comment by you06** [comment]
Can you also update this link to slack?
https://github.com/tikv/tikv/blob/c1e506eff743ea7236e76b2af64a1257233d2771/CONTRIBUTING.md?plain=1#L5

**Review by Connor1996 — APPROVED** [review]

**Pull request merged**
