### PR TITLE
res_meter: fix assertion failure

### LINKED ISSUE #12234: after upgrade from v4.0.0  to v6.0.0, tikv report " [FATAL] [lib.rs:468] ["assertion failed: self.others.is_empty()"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}"
### What version of TiKV are you using?
 ["Git Commit Hash:   5b59a1e4c3cfd98dda93f36f7a6d67463c3dae98"]

### Steps to reproduce
upgrade from 4.0.0 to v6.0.0, 4 tikv node in cluster
scale out tikv:20560
scale in tikv: 20160

detail config and log please see in clinic:
["clinic link"] [url="https://clinic.pingcap.com:4433/diag/files?uuid=99ddf1bf22478d51-42afbae221c1ac1d-af79a0b55e8efcdf"]

### What did you expect?
no panic

### What did happened?
[2022/03/23 07:22:15.410 +08:00] [FATAL] [lib.rs:468] ["assertion failed: self.others.is_empty()"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:467:18\n   1: std::panicking::rust_panic_with_hook\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:702:17\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:586:13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:138:18\n   4: rust_begin_unwind\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:584:5\n   5: core::panicking::panic_fmt\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:143:14\n   6: core::panicking::panic\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panicking.rs:48:5\n   7: resource_metering::model::Records::is_empty\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/resource_metering/src/model.rs:289:13\n      resource_metering::reporter::Reporter::upload\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/resource_metering/src/reporter/mod.rs:132:12\n      <resource_metering::reporter::Reporter as tikv_util::worker::pool::RunnableWithTimer>::on_timeout\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/resource_metering/src/reporter/mod.rs:64:9\n      tikv_util::worker::pool::Worker::start_with_timer_impl::{{closure}}\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/worker/pool.rs:465:25\n      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/future/mod.rs:84:19\n      yatp::task::future::RawTask<F>::poll\n             at /rust/git/checkouts/yatp-e704b73c3ee279b6/5f3d580/src/task/future.rs:59:9\n   8: yatp::task::future::TaskCell::poll\n             at /rust/git/checkouts/yatp-e704b73c3ee279b6/5f3d580/src/task/future.rs:103:9\n      <yatp::task::future::Runner as yatp::pool::runner::Runner>::handle\n             at /rust/git/checkouts/yatp-e704b73c3ee279b6/5f3d580/src/task/future.rs:387:20\n   9: <tikv_util::yatp_pool::YatpPoolRunner<T> as yatp::pool::runner::Runner>::handle\n             at /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/mod.rs:104:24\n      yatp::pool::worker::WorkerThread<T,R>::run\n             at /rust/git/checkouts/yatp-e704b73c3ee279b6/5f3d580/src/pool/worker.rs:48:13\n      yatp::pool::builder::LazyBuilder<T>::build::{{closure}}\n             at /rust/git/checkouts/yatp-e704b73c3ee279b6/5f3d580/src/pool/builder.rs:114:25\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys_common/backtrace.rs:122:18\n  10: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/thread/mod.rs:498:17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/panic/unwind_safe.rs:271:9\n      std::panicking::try::do_call\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:492:40\n      std::panicking::try\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panicking.rs:456:19\n      std::panic::catch_unwind\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/panic.rs:137:14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/thread/mod.rs:497:30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/core/src/ops/function.rs:227:5\n  11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/boxed.rs:1854:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/alloc/src/boxed.rs:1854:9\n      std::sys::unix::thread::Thread::new::thread_start\n             at /rustc/1e12aef3fab243407f9d71ba9956cb2a1bf105d5/library/std/src/sys/unix/thread.rs:108:17\n  12: start_thread\n

### PR DESCRIPTION
**Pull request by mornyx**
Issue Number: close #12234

Signed-off-by: mornyx <mornyx.z@gmail.com>

#### Before

In the past, we used assertions to ensure that when tagged `Records.records` was empty, untagged `Records.others` must also be empty:

```rust
pub fn is_empty(&self) -> bool {
    if self.records.is_empty() {
        assert!(self.others.is_empty());
        true
    } else {
        false
    }
}
```

This is reasonable in the general case, but will trigger an assertion failure under some special condition...

In a certain round of collection, when we collect tags that exceed the maximum number limit (`max_resource_group`), and all these tags correspond to equal `cpu_time`, then our `records.top_k()` action will get 0 `top` and many `evicted`:

```rust
fn handle_records(&mut self, records: Arc<RawRecords>) {
    let ts = records.begin_unix_time_secs;
    if self.config.max_resource_groups >= records.records.len() {
        self.records.append(ts, records.records.iter());
        return;
    }
    // Here we got 0 top and many evicted.
    let (top, evicted) = records.top_k(self.config.max_resource_groups);
    self.records.append(ts, top);
    let others = self.records.others.entry(ts).or_default();
    evicted.for_each(|(_, v)| {
        others.merge(v);
    });
}
```

At this point, a scheduled report is triggered and an empty check is performed. So the assertion fails.

#### After

We changed the basis for `Records` to be empty to `Records.records` and `Records.others` are both empty:

```rust
pub fn is_empty(&self) -> bool {
    self.records.is_empty() && self.others.is_empty()
}
```

So when the above scenario occurs, only reporting `Records.others` without `Records.records` is allowed.

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by breeswish — APPROVED** [review]
I'm also interested in how this is discovered.

**Review by zhongzc — APPROVED** [review]

**Review by breeswish — APPROVED** [review]
Approve again

**Comment by breeswish** [comment]
The description of the PR is very verbose. It helped me a lot. Great job!

**Pull request merged**
