### PR TITLE
raftstore: enable apply committed log before persistence by default

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: ref #16717

What's Changed:

```commit-message
Change the default value of `raftstore.max_apply_unpersisted_log_limit` from 0 to 1024 to enable apply committed log before persistence by default.
```

In our internal benchmark, with 3*8c tikv instances, when running sysbench oltp_write_only workload with 100 threads, the performance is almost the same when this feature is enabled/disabled. The result matches our expectation that this feature won't bring any performance impact.

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by tonyxuqqi — APPROVED** [review]

**Comment by tonyxuqqi** [comment]
We expect there's no regression in normal scenario right? @glorv

**Comment by glorv** [comment]
> We expect there's no regression in normal scenario right? @glorv

Yes, in our benchmark, there is no significant performance impact.

**Comment by glorv** [comment]
@overvenus @LykxSassinator  Please help take a look, thanks~

**Comment by LykxSassinator** [comment]
@glorv One tip, it's better to upload essential performance testing reports that compare the impact of enabling and disabling this feature.

**Comment by glorv** [comment]
> @glorv One tip, it's better to upload essential performance testing reports that compare the impact of enabling and disabling this feature.

Thanks for the remind. I add a brief description of the bench result of performance impact when this feature is enabled.

**Review by LykxSassinator — APPROVED** [review]

**Pull request merged**
