### PR TITLE
server: wait for reset-to-version task completion

### LINKED ISSUE #13829: reset-to-version segfault
### What version of TiKV are you using?

TiKV with reset-to-version functionality.

### What operating system and CPU are you using?

N/A

### Steps to reproduce

```bash
tiup playground nightly --tiflash 0 --kv 1
kill tikv-seerver
tiup ctl:nightly tikv  --config ~/.tiup/data/*/tikv-0/tikv.toml --data-dir ~/.tiup/data/*/tikv-0/data/   --pd [127.0.0.1:2379](http://127.0.0.1:2379/) reset-to-version -v 437518324818771969
```

### What did you expect?

Succeed.

### What did happened?

Aborted.

### PR DESCRIPTION
**Pull request by tabokie**
Signed-off-by: tabokie <xy.tao@outlook.com>

### What is changed and how it works?

Issue Number: Close #13829

What's Changed:

Wait for completion so that the main thread doesn't exit when the worker thread is still using some static variables.

```commit-message
Fix a segfault when executing reset-to-version with tikv-ctl
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

```release-note
Fix a segfault when executing reset-to-version with tikv-ctl
```

### CODE REVIEW

**Review by BusyJay — APPROVED** [review]
Why not waiting will segment fault?

**Comment by tabokie** [comment]
> Why not waiting will segment fault?

I haven't really verified the fix yet, but from my understanding the detached thread cannot reliably access static variables (comparator returned from `ByteswiseComparator()` for instance).

**Review by Connor1996 — APPROVED** [review]
LGTM

**Pull request merged**
