### PR TITLE
sst_importer: write delete type key for sst service (#8624)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #8624 to release-4.0

---

### What problem does this PR solve?
part of PiTR(https://github.com/pingcap/br/issues/325), we should let tikv sst_importer handle delete type key.

block on https://github.com/pingcap/kvproto/pull/676/files
### What is changed and how it works?

What's Changed:
if write a key without value. change it to a `WriteType:Delete` record.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

Side effects

### Release note 

- No release note

### CODE REVIEW

**Comment by solotzg** [comment]
any update? @3pointer

**Comment by 3pointer** [comment]
This PR update the kvproto to latest release-4.0, so we need https://github.com/tikv/tikv/pull/8622 to merge first

**Review by overvenus — APPROVED** [review]
LGTM

**Review by kennytm — APPROVED** [review]
lgtm

**Review by 5kbpers — APPROVED** [review]

**Pull request merged**
