### PR TITLE
Cheery pick #4303

### PR DESCRIPTION
**Pull request by breeswish**
Signed-off-by: Breezewish <breezewish@pingcap.com>

## What have you changed? (mandatory)

This PR cherry picks https://github.com/tikv/tikv/pull/4303

### CODE REVIEW

**Comment by breeswish** [comment]
/run-all-tests tidb=release-2.1 pd=release-2.1 tidb-test=release-2.1 tidb-private-test=release-2.1

**Comment by breeswish** [comment]
/run-all-tests tidb=release-2.1 pd=release-2.1 tidb-test=release-2.1 tidb-private-test=release-2.1

**Comment by breeswish** [comment]
/run-all-tests tidb=release-2.1 pd=release-2.1 tidb-test=release-2.1 tidb-private-test=release-2.1

**Comment by overvenus** [comment]
/run-all-tests tidb=release-2.1 pd=release-2.1 tidb-test=release-2.1 tidb-private-test=release-2.1

**Pull request merged**
