### PR TITLE
Fix TiKV panicked when system time back

### LINKED ISSUE #9392: TiKV  panicked when system time back
## Bug Report

AskTUG link: https://asktug.com/t/topic/67390

### What version of TiKV are you using?

v4.0.9

### Steps to reproduce

The ntp service changed the system time back.

### What did happened?
TiKV panicked 

image

### PR DESCRIPTION
**Pull request by lhy1024**
Signed-off-by: lhy1024 <admin@liudos.us>

### What problem does this PR solve?

Issue Number: close #9392

Problem Summary: ignore it

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 
- No release note

### CODE REVIEW

**Comment by lhy1024** [comment]
@BusyJay @HunDunDM PTAL

**Review by BusyJay — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]

**Review by nolouch — APPROVED** [review]
lgtm

**Review by HunDunDM — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]

**Pull request merged**
