### PR TITLE
copr: vectorize any_value

### PR DESCRIPTION
**Pull request by koushiro**
PCP #5751 

Signed-off-by: koushiro <koushiro.cqx@gmail.com>

###  What have you changed?

* Improve miscellaneous impls and tests
* Vectorize `any_value`

###  What is the type of the changes?

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?

- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No

###  Does this PR affect `tidb-ansible`?

No

### CODE REVIEW

**Comment by koushiro** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/101

**Comment by breeswish** [comment]
Hi, could you separate the PR into two, one for any_value, one for other improvements? The other improvements of your PR changes a lot.. which will take long time to review..

**Pull request merged**
