### PR TITLE
copr: migrate `Bytes` and `Json` to ChunkedVec

### PR DESCRIPTION
**Pull request by skyzh**
### What problem does this PR solve?

**Problem Summary**

This PR introduces `ChunkedVec`, the new vector type with more compact memory layout, for `Bytes`.

**Overview**

In [RFC: Using chunk format in coprocessor framework](https://github.com/tikv/rfcs/pull/43/files), we proposed a `ChunkedVec` struct to support Chunk-based computing. We plan to:

1. Migrate current co-processor framework to use interface compatible with `ChunkedVec`.  (Done)
2. Introduce `ChunkedVec`.

Now all interfaces in copr framework is ready for migration process. We can finally introduce `ChunkedVec` into TiKV. Then, we may further optimize performance by merging null parameters, etc.

### What is changed and how it works?

Proposal: [RFC: Using chunk format in coprocessor framework](https://github.com/tikv/rfcs/pull/43/)

Related Issue: #7724

**What's Changed**

* add `ChunkedVecBytes`
* add  `ChunkedVecJson`
* common parts of `ChunkedVec*` are moved to a common module
* update related code to use this structure
* phase out `NotChunkedVec`

This marks the completion of Full Chunk-based Computing.

Our next steps include:

* directly move `ChunkedVec` data into `Column` structure
* Writer / Guard support

### Check List 

Tests 

- Unit test

Side effects

- Performance

### CODE REVIEW

**Comment by TennyZhuang** [comment]
@ti-sre-bot /bench +tpcc +tpch

**Comment by TennyZhuang** [comment]
@sre-bot /bench +tpcc +tpch

**Comment by skyzh** [comment]
@breeswish @TennyZhuang Just rebased this PR onto latest master. PTAL~

**Pull request merged**
