### PR TITLE
In-memory engine: fix save point empty assertion fail

### LINKED ISSUE #17630: In-memory engine: save point empty assertion failed
## Bug Report

[2024/10/10 12:07:50.516 +00:00] [FATAL] [lib.rs:479] ["assertion failed: self.save_points.is_empty()"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:478:18\n   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2029:9\n      std::panicking::rust_panic_with_hook\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:783:13\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:649:13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:171:18\n   4: rust_begin_unwind\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:645:5\n   5: core::panicking::panic_fmt\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:72:14\n   6: core::panicking::panic\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:144:5\n   7: in_memory_engine::write_batch::RegionCacheWriteBatch::evict_current_region\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/in_memory_engine/src/write_batch.rs:229:9\n   8: in_memory_engine::write_batch::RegionCacheWriteBatch::process_cf_operation\n      <in_memory_engine::write_batch::RegionCacheWriteBatch as engine_traits::write_batch::Mutable>::put_cf\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/in_memory_engine/src/write_batch.rs:525:9\n   9: <hybrid_engine::observer::write_batch::HybridObservableWriteBatch as engine_traits::write_batch::Mutable>::put_cf\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/hybrid_engine/src/observer/write_batch.rs:115:13\n  10: <raftstore::coprocessor::read_write::write_batch::WriteBatchWrapper<WB> as engine_traits::write_batch::Mutable>::put\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/coprocessor/read_write/write_batch.rs:126:13\n      raftstore::store::fsm::apply::ApplyDelegate<EK>::handle_put\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:1883:13\n      raftstore::store::fsm::apply::ApplyDelegate<EK>::exec_write_cmd\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:1789:33\n      raftstore::store::fsm::apply::ApplyDelegate<EK>::exec_raft_cmd\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:1717:13\n      raftstore::store::fsm::apply::ApplyDelegate<EK>::apply_raft_cmd\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:1476:45\n  11: raftstore::store::fsm::apply::ApplyDelegate<EK>::process_raft_cmd\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:1412:52\n  12: raftstore::store::fsm::apply::ApplyDelegate<EK>::handle_raft_entry_normal\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:1290:24\n      raftstore::store::fsm::apply::ApplyDelegate<EK>::handle_raft_committed_entries\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:1162:43\n  13: raftstore::store::fsm::apply::ApplyFsm<EK>::handle_apply\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:4087:9\n  14: raftstore::store::fsm::apply::ApplyFsm<EK>::handle_tasks\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:4441:25\n  15: <raftstore::store::fsm::apply::ApplyPoller<EK> as batch_system::batch::PollHandler<raftstore::store::fsm::apply::ApplyFsm<EK>,raftstore::store::fsm::apply::ControlFsm>>::handle_normal\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/raftstore/src/store/fsm/apply.rs:4733:9\n  16: batch_system::batch::Poller<N,C,Handler>::poll\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:380:27\n  17: batch_system::batch::BatchSystem<N,C>::start_poller::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/batch-system/src/batch.rs:551:17\n      <std::thread::Builder as tikv_util::sys::thread::StdThreadBuildWrapper>::spawn_wrapper::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/sys/thread.rs:438:13\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:155:18\n  18: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:529:17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9\n      std::panicking::try::do_call\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:552:40\n      std::panicking::try\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:516:19\n      std::panic::catch_unwind\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:142:14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:528:30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5\n  19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9\n      std::sys::unix::thread::Thread::new::thread_start\n             at rust/toolchains/nightly-2023-12-28-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17\n  20: start_thread\n  21: clone3\n"] [location=components/in_memory_engine/src/write_batch.rs:229] [thread_name=apply-0] [thread_id=110]

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
### What is changed and how it works?

Issue Number: Close #17630 Ref #16141 

What's Changed:

```commit-message
fix save point empty assertion fail
```
Save point empty assertion can fail. For simplifity, does not release evicted region's buffer (it is intended to release memory quickly so that the next region have chances not to be evicted due to memory limit) as eviction during write is rare.

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by glorv — APPROVED** [review]

**Review by overvenus — COMMENTED** [review]
Could you add a test?

**Comment by SpadeA-Tang** [comment]
> Could you add a test?

Test what? This PR fixes a assertion fail by removing the related code without add anything new.

**Review by overvenus — APPROVED** [review]
A test is not just for new code; it also verifies bug fixes, such as the unexpected assert failure in this pull request, to ensure that bug never occurs again.

Anyway, with the simple change it makes, LGTM.

**Comment by SpadeA-Tang** [comment]
PTAL thansk @zhangjinpeng87

**Pull request merged**
