### PR TITLE
Fix check-sse4_2.sh on GDB 8

### LINKED ISSUE #4367: error: ./target/debug/tikv-server does not enable sse4.2
## Bug Report

**What version of Rust are you using?**

rustc 1.35.0-nightly (a9da8fc9c 2019-03-04)

**What operating system and CPU are you using?**

Ubuntu 18.04.2 LTS
Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

**What did you do?**

run "make dev"

**What did you expect to see?**
Successful building and testing

**What did you see instead?**
When "checking binary ./target/debug/tikv-server for sse4.2",
I met an error:
error: ./target/debug/tikv-server does not enable sse4.2

### PR DESCRIPTION
**Pull request by sticnarf**
## What have you changed? (mandatory)

Extract the function address from `nm` and disassemble the function using that address. This is a workaround for the `symbol not found` failure occurring on GDB 8.

## What are the type of the changes? (mandatory)

Bug fix

## How has this PR been tested? (mandatory)

I have run `make dev` on my PC with GDB 8. 
Hope this will also work for CI (which is equipped with GDB 7).

## Does this PR affect documentation (docs) update? (mandatory)

No.

## Does this PR affect tidb-ansible update? (mandatory)

No.

## Refer to a related PR or issue link (optional)
Fix #4367

### CODE REVIEW

**Comment by sticnarf** [comment]
CI seems to use the check-sse4_2.sh on the master branch instead of the updated one. How can it be tested before merged?

This pr just helps developers using gdb 8. So I don't know if a test validating whether this works for GDB 8 should be added.

**Comment by breeswish** [comment]
Additionally I prefer to remove the check of sse4.2 for `make dev`, which just doesn't make sense for development builds. We can leave it only for CI or release build. @overvenus How do you think?

**Comment by sticnarf** [comment]
> Additionally I prefer to remove the check of sse4.2 for `make dev`, which just doesn't make sense for development builds. We can leave it only for CI or release build. @overvenus How do you think?

Ok, I will close this.

**Comment by overvenus** [comment]
I agree it is better to leave this check release and ci only.

**Pull request closed without merging**
