### PR TITLE
cdc: fix unstable test

### PR DESCRIPTION
**Pull request by 5kbpers**
Signed-off-by: 5kbpers <tangminghua@pingcap.com>

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:
Sometimes `test_connections_register` would fail.

### What is changed and how it works?

What's Changed:
Use loop to fix `test_connections_register`.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 
* N/A

### CODE REVIEW

**Comment by flycash** [comment]
I got the same issue. Why closed this PR?

**Comment by 5kbpers** [comment]
> I got the same issue. Why closed this PR?

It was fixed on another one, did you meet this issue on the current master branch?

**Comment by flycash** [comment]
Yes, I updated master branch and ran `make dev` command, it failed.
Here is the log:
```shell
thread 'test_register::test_connections_register' panicked at 'unknown event Entries { entries { start_ts: 2 r_type: Prewrite op_type: Put key: 6B657931 value: 76616C7565 } entries { r_type: Initialized } }', components/cdc/tests/failpoints/test_register.rs:163:18
stack backtrace:
test test_register::test_merge ... ok
   0: rust_begin_unwind
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panicking.rs:483:5
   1: std::panicking::begin_panic_fmt
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panicking.rs:437:5
   2: failpoints::test_register::test_connections_register
             at ./tests/failpoints/test_register.rs:163:18
   3: failpoints::test_register::test_connections_register::{{closure}}
             at ./tests/failpoints/test_register.rs:108:1
   4: core::ops::function::FnOnce::call_once
             at /Users/mindeng/.rustup/toolchains/nightly-2020-10-19-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/ops/function.rs:227:5
```

**Comment by flycash** [comment]
The commit id is: b2ea544495d7dc43f83a5522804e0d98e08b5969

**Pull request closed without merging**
