### PR TITLE
copr: add duration_string_time_diff function

### PR DESCRIPTION
**Pull request by Jayice-zjw**
Signed-off-by: Jayice <1185430411@qq.com>

Hi,i participated in TiKV community for the first time

### What problem does this PR solve?

according to
(https://github.com/tikv/tikv/issues/5751#issuecomment-909765143)

Problem Summary:
migrating `duration_string_time_diff` from TiDB

### What is changed and how it works?

What's Changed:

implement ` duration_string_time_diff`

### Related changes

- No Related Changes

Tests 

- Unit test

### Release note 

```release-note
implement  duration_string_time_diff
```

### CODE REVIEW

**Review by zhongzc — APPROVED** [review]

**Review by skyzh — APPROVED** [review]

**Comment by Jayice-zjw** [comment]
> /merge

thanks Chi ! 😘

**Comment by skyzh** [comment]
> [FORMAT CHECKER NOTIFICATION]
> 
> Please provide the associated issue number in the commit messages, for example: `close #12345`, or `ref #12345`.

By the way, please reference #5751 in your commit message, so that this PR could be merged. You may use `--amend` to change the commit message.

```
git commit --amend
git push -f
```

**Comment by skyzh** [comment]
Looks like the commit message didn't changed 🤣

**Comment by Jayice-zjw** [comment]
> > [FORMAT CHECKER NOTIFICATION]
> > Please provide the associated issue number in the commit messages, for example: `close #12345`, or `ref #12345`.
> 
> By the way, please reference #5751 in your commit message, so that this PR could be merged. You may use `--amend` to change the commit message.
> 
> ```
> git commit --amend
> git push -f
> ```

done. PTAL

> Looks like the commit message didn't get changed 🤣

really?it seems to have been changed. 🤨

**Comment by Jayice-zjw** [comment]
> Looks like the commit message didn't get changed 🤣

really? It seems to have been changed. 🤨

**Comment by skyzh** [comment]
> > Looks like the commit message didn't get changed 🤣
> 
> really? It seems to have been changed. 🤨

Oops, I see it in commit message body. Current format checker only accepts `ref #xxx` instead of `refer`. Please change the message again 🤣

**Comment by skyzh** [comment]
I'll look into this issue later. Looks like the format checker is not functioning correctly.

**Comment by Xuanwo** [comment]
I think maybe something wrong in the regex: https://github.com/ti-community-infra/tichi/blob/1d9018000d2a9a313f2a29acd1af4fdfa7abaa48/configs/prow-dev/config/external_plugins_config.yaml#L105-L114

**Comment by skyzh** [comment]
> I think maybe something wrong in the regex: https://github.com/ti-community-infra/tichi/blob/1d9018000d2a9a313f2a29acd1af4fdfa7abaa48/configs/prow-dev/config/external_plugins_config.yaml#L105-L114

It didn't take GitHub's URL into account. In previous commits, the plain commit message contains `ref https://github.com/xxxx/pulls/id` instead of `ref #id`.

**Pull request merged**
