### PR TITLE
Add test for panic in load-base-split

### PR DESCRIPTION
**Pull request by lhy1024**
Signed-off-by: lhy1024 <admin@liudos.us>

### What problem does this PR solve?

Problem Summary:

Add test for panic in load-base-split https://github.com/pingcap/tidb/issues/22963

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)
Before #9720, it will panic always
image

### Release note 

- No Release note

### CODE REVIEW

**Comment by cosven** [comment]
What are the affected versions?
Is the range `[v4.0.0:v4.0.11],[v5.0.0-rc]` correct?

**Comment by lhy1024** [comment]
> Which versions are affected?
> Is the range `[v4.0.0:v4.0.11],[v5.0.0-rc]` correct?

v4.0.11 and v5.0.0-rc, it is It is introduced by #9256

**Comment by lhy1024** [comment]
@BusyJay @nolouch PTAL

**Review by nolouch — APPROVED** [review]
lgtm

**Review by BusyJay — APPROVED** [review]

**Pull request merged**
