### PR TITLE
raftstore: Fix group commit is mistakenly enabled in sync recover state

### LINKED ISSUE #15817: Commit can't advance for region in joint state when dr auto sync is enabled
### What version of TiKV are you using?

v6.5.4

### What operating system and CPU are you using?

Not related

### Steps to reproduce

image
Consider the case, where there are two data centers and dr-auto-sync is enabled. The region is in state 1. In the primary data center (dc-1), there are three voters, and in the backup data center, there are two voters and one learner.

If all instances in the backup data center are down. The cluster is scale out with new instances, referred to as dc-2'. At this point, the region is in state 2. You can see that the peers that were previously in dc-2 are still present in metadata but as "down."

PD scheduling begins to remove the down peers from dc-2 and add new peers to dc-2'. During these scheduling processes, the region may transition to state 3, entering a joint state. "Demoting Voter" indicates a voter that is about to become a learner, and "Incoming Voter" indicates a learner that is about to become a voter. In the joint state, committing requires both "Voter + Demoting" and "Voter + Incoming Voter" to meet the log commit conditions. At this time, the cluster is in a SyncRecover state due to a bug error that enabled group commit.

In the context of group commit, it is necessary to ensure that the logs are present on peers in both the primary data center (dc-2 and dc-2') and satisfy the quorum conditions simultaneously to commit. Therefore, the commitment criteria in state 3 are as follows:

Among Store 1, Store 2, Store 3, and Store 5, at least 3 out of 3 Voter + Demoting Voter must have the log, and Demoting Voter must have the log.
Among Store 1, Store 2, Store 3, and Store 7, at least 3 out of 3 Voter + Incoming Voter must have the log, and Incoming Voter must have the log.
Since Demoting Voter is on the failed store-5, it can never have the log, which prevents the commit from progressing, leading to the region being unable to exit the joint state and unable to handle read and write requests normally.

### What did you expect?
Commit can advance

### What did happened?
Commit can't advance

### PR DESCRIPTION
**Pull request by Connor1996**
### What is changed and how it works?

Issue Number: Close #15817

What's Changed:

```commit-message
When splitting a region, group commit is mistakenly enabled in the sync-recover state. 
If the region is in joint state and demoting voter is down, the commit condition can't meet. 
Fix group commit is mistakenly enabled in sync recover state
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

```release-note
Fix possible timeout leave joint state for dr auto sync when doing scaling out
```

### CODE REVIEW

**Review by TonsnakeLin — APPROVED** [review]
LGTM

**Review by nolouch — APPROVED** [review]
lgtm

**Review by glorv — APPROVED** [review]

**Comment by nolouch** [comment]
ci failed.

**Review by tonyxuqqi — APPROVED** [review]

**Pull request merged**
