### PR TITLE
Add builtin_string.rs function.

### PR DESCRIPTION
**Pull request by kg88**
- Summarize your change (mandatory)
1 I write a builtin function concat_ws(line 82) in builtin_string.rs.
2 And i change builtin_string.rs and scalar_function.rs
3 I write a test in builtin_string.rs(line 937), it works!

Please **NOTE** that:
This is the first time i try to become a contributor, so please forgiven me if the change is not perfect.

This is my commit message
Signed-off-by: kg88 <1374913837@qq.com>

### CODE REVIEW

**Comment by huachaohuang** [comment]
@breeswish Looks like there are some related changes with you, PTAL

**Comment by kg88** [comment]
I changed my commit message , why the DCO is not right???

**Comment by kg88** [comment]
Should i commit a new PR?

**Comment by ice1000** [comment]
你可以改了commit message后force push到你的分支去

**Comment by kg88** [comment]
@ice1000
Thank you!

**Pull request closed without merging**
