### PR TITLE
log-backup: fix uploading to gcs error

### LINKED ISSUE #13106: log backup failed when use GCS as external storage
### What version of TiKV are you using?

master

### What operating system and CPU are you using?

linux

### Steps to reproduce

start log backup with GCS storage

### What did you expect?

log backup task status is normal

### What did happened?

log backup task status is **error**

### PR DESCRIPTION
**Pull request by WangLe1321**
Signed-off-by: WangLe1321 <wangle1321@163.com>

### What is changed and how it works?

Issue Number: Close #13106

What's Changed:

Modify `est_len` to real file size, so that the value of `content-length` in http header is equal to the size of http body when put object to gcs.

```commit-message
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
test steps and test results is described in this [document](https://pingcap.feishu.cn/docx/doxcnBGEEzJRL48uuaGjYoYrcxE#doxcnKSYK6aGOcsk6MWAuVw1ZS1)

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
support gcs storage in log backup
```

### CODE REVIEW

**Review by overvenus — COMMENTED** [review]
Could you mock a storage that checks the given `est_len` and reader content strictly?

**Review by overvenus — APPROVED** [review]

**Review by 3pointer — APPROVED** [review]

**Pull request merged**
