### PR TITLE
tests: fix one flaky testcase

### PR DESCRIPTION
**Pull request by cosven**
Signed-off-by: cosven <yinshaowen241@gmail.com>

### What is changed and how it works?

Issue Number: Close https://github.com/tikv/tikv/issues/13603

What's Changed:

```commit-message
fix one flaky testcase
```

### Release note 

```release-note
```

### CODE REVIEW

**Review by 3pointer — APPROVED** [review]

**Review by hicqu — APPROVED** [review]

**Comment by cosven** [comment]
@hicqu please help merge this PR ❤️.

**Pull request merged**
