### PR TITLE
tests: stablize test_request_snapshot_after_propose_merge (#9379)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #9379 to release-4.0

---

Signed-off-by: 5kbpers <tangminghua@pingcap.com>

### What problem does this PR solve?

Problem Summary:
`test_request_snapshot_after_propose_merge` is not stable by potential reasons:
1. merge proposal may be skipped by log gap limit
2. time between proposing premerge and requesting snapshot is uncertain
3. leader could be changed

### What is changed and how it works?

What's Changed:
1. increase log gap limit
2. use `proposed_cb` to ensure premerge proposed before requesting snapshot
3. increase election timeout

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 
* N/A

### CODE REVIEW

**Review by hicqu — APPROVED** [review]

**Comment by hi-rustin** [comment]
This cherry pick PR is for a release branch and has not yet been approved by release team. Adding the do-not-merge/cherry-pick-not-approved label.
To merge this cherry pick, it must first be approved (/lgtm + /merge) by the collaborators.
AFTER it has been approved by collaborators, please ping the release team in a comment to request a cherry pick review

**Review by NingLin-P — APPROVED** [review]
/LGTM

**Pull request merged**
