### PR TITLE
Upgrade rust to nightly-2019-07-19

### PR DESCRIPTION
**Pull request by brson**
## What have you changed? (mandatory)

Upgrade the toolchain in an attempt to fix likely pipelining error, "error: crate `librocksdb_sys` required to be available in rlib format, but was not found in this form". re
https://github.com/tikv/tikv/issues/5130

As noted on the issue, a pipelining bug was fixed after we adopted pipelining. This upgrade may fix the error @BusyJay and others have been seeing.

## What are the type of the changes? (mandatory)

- Engineering (engineering change which doesn't change any feature or fix any issue)

## How has this PR been tested? (mandatory)

make dev

## Does this PR affect documentation (docs) or release note? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No

## Refer to a related PR or issue link (optional)

https://github.com/tikv/tikv/issues/5130

### CODE REVIEW

**Comment by siddontang** [comment]
you also need to run `./scripts/gen-dockerfile.sh` to update the toolchain in docker.

**Comment by breeswish** [comment]
You will need to update the docker file as suggested by @siddontang and also sign off your commits :)

**Comment by breeswish** [comment]
Additionally CI failed because of some deprecate notes maybe you need to take a look.

**Comment by BusyJay** [comment]
Is #4301 resolved by this version?

**Comment by siddontang** [comment]
CI still failed @brson

**Comment by siddontang** [comment]
Ping @brson

**Comment by brson** [comment]
I'm still working through clippy changes.

**Comment by brson** [comment]
This is updated to fix all the clippy lints. I tried updated to a newer toolchain but they are broken with an error about "unrecognized option: json-rendered".

**Comment by breeswish** [comment]
Looks like there are still some warnings according to CI:
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/7275/pipeline

**Comment by breeswish** [comment]
The rest looks good to me and I will approve it once CI is passed :)

**Comment by siddontang** [comment]
em, CI still failed 

maybe we need to upgrade to the latest toolchain?

**Pull request merged**
