### PR TITLE
tests: stop log compact for transferring leader (#9321)

### LINKED ISSUE #9232: cases::test_stale_read::test_read_index_when_transfer_leader_2 failed
Latest build: <a href="https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37642/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tikv_ghpr_test/37642/display/redirect</a>

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #9321 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #9232 

Problem Summary:

Transferring leader can fail due to log gap, which is introduced by new
log compact proposal.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 
- No release note

### CODE REVIEW

**Comment by BusyJay** [comment]
@NingLin-P @hicqu PTAL

**Review by NingLin-P — APPROVED** [review]

**Review by hicqu — APPROVED** [review]

**Pull request merged**
