### PR TITLE
*: fix license

### PR DESCRIPTION
**Pull request by BusyJay**
### What problem does this PR solve?

Problem Summary:

The text is not in correct and I copy one from
https://www.apache.org/licenses/LICENSE-2.0.txt.

### Check List 

Tests 

- No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by zhangjinpeng1987 — APPROVED** [review]
LGTM

**Comment by it2911** [comment]
Looks like some problems exist.

**Review by zhouqiang-cl — APPROVED** [review]
LGTM

**Pull request merged**
