### PR TITLE
cdc: limit scan task concurrency (#10262)

### PR DESCRIPTION
**Pull request by overvenus**
cherry-pick #10262 to release-5.1

-----------

### What problem does this PR solve?

Close https://github.com/tikv/tikv/issues/10114
Close https://github.com/pingcap/ticdc/issues/1844
Problem Summary:

### What is changed and how it works?

Limit CDC scan concurrency.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test

Tested with TiCDC v4.0.13

<b style="font-weight:normal;" ><div dir="ltr" style="margin-left:0pt;" align="left">
v5.0.2 | This PR
-- | --
image  | image
image | image
image | image

</div></b>

### Release note 

```release-note
Fix OOM when TiCDC resumes a changefeed in a cluster that has lots of regions being captured. 
```

### CODE REVIEW

**Review by amyangfei — APPROVED** [review]

**Review by liuzix — APPROVED** [review]

**Comment by overvenus** [comment]
/run-test

raftstore::test_region_heartbeat::test_region_heartbeat_report_approximate_size fails.

**Comment by overvenus** [comment]
/run-test

cases::test_merge::test_node_failed_merge_before_succeed_merge fails

**Comment by overvenus** [comment]
/run-test

raftstore::test_region_heartbeat::test_region_heartbeat_report_approximate_size fails.

https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/2105/pipeline

**Comment by overvenus** [comment]
/run-test

raftstore::test_region_heartbeat::test_region_heartbeat_report_approximate_size fails.

https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/2106/pipeline/

**Comment by overvenus** [comment]
/run-test

raftstore::test_region_heartbeat::test_region_heartbeat_report_approximate_size fails.

https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/2109/pipeline

**Pull request merged**
