### PR TITLE
Move http server to a standalone package - [WIP]

### PR DESCRIPTION
**Pull request by liufuyang**
Signed-off-by: Fuyang Liu <fuyangl@spotify.com>

## What have you changed? (mandatory)

Following up on #4444 and #4997, I try to put the http module into a standalone crate.

Do you think it can be done and it should be done?
I currently have **some issues** while trying to do so:
* Not sure how to have a TiKVConfig reference from this component crate
* Not sure why the logging seems not working (the one such as`info!(...)` seems not printing logs)

Perhaps you can give some help or comments?

## What are the type of the changes? (mandatory)

The currently defined types are listed below, please pick one of the types for this PR by removing the others:
- Improvement (change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)

unit tested

### CODE REVIEW

**Comment by liufuyang** [comment]
@siddontang @breeswish Do you think moving the http server to a standalone crate isa good idea or ? 🤔 
CC @jlerche @Hoverbear

**Comment by siddontang** [comment]
Maybe not now. The reason is that we just want to move the basic mod into components, but I can guess the HTTP server may use some TiKV upper mod like raftstore later. You can think the HTTP server just a unified place to hold all other components like gRPC server. 

But if we can have a way to refactor this and speed up the compiling time, it is fine. 

/cc  @brson @BusyJay

**Comment by BusyJay** [comment]
Just a module instead of component is OK.

**Comment by liufuyang** [comment]
I also just tried to import actix-web at the beginning, noticing the total number of packages needed to download and compile from something like 350 to 450 (can't remember the exact number)...

**Pull request closed without merging**
