### PR TITLE
components: only check output schema field type when set resp encode type

### LINKED ISSUE #14818: The `encode_type` in rpc resp could improve
### What version of TiKV are you using?

master

### What operating system and CPU are you using?

not related

### Steps to reproduce

ref https://github.com/pingcap/tidb/issues/44123
Although there is a column with a field type `set` in the index, it will not be populated into the resp, so the encode type in the resp should not be affected by it.

### What did you expect?

The `encode_type` for indexReq is `EncodeType_TypeChunk`

### What did happened?

The `encode_type` for indexReq is `EncodeType_TypeDefault`

### PR DESCRIPTION
**Pull request by Defined2014**
### What is changed and how it works?

Issue Number: close #14818

What's Changed:

```
The resp encode type only affected by returned filed types.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by wshwsh12 — APPROVED** [review]

**Comment by Defined2014** [comment]
@breezewish could you help me merge this PR? Thx

**Pull request merged**
