### PR TITLE
titan: Share blob cache with block cache

### PR DESCRIPTION
**Pull request by Connor1996**
### What is changed and how it works?

Issue Number: Ref https://github.com/tikv/tikv/issues/16245

What's Changed:

```commit-message
Share block cache with blob cache
```

### Related changes

- [x] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Share block cache with blob cache
```

### CODE REVIEW

**Review by tonyxuqqi — APPROVED** [review]
please remembered to remove the Cargo.toml change before the merge

**Review by v01dstar — APPROVED** [review]
LGTM

**Review by tonyxuqqi — APPROVED** [review]

**Review by v01dstar — APPROVED** [review]

**Pull request merged**
