### PR TITLE
Modify the return value of the scan function under the RawStorage trait.

### LINKED ISSUE #15246: The scan function return in RawStorage in coprocessor_plugin does not meet expectations
### Steps to reproduce

I defined a coprocessor plugin, when I use the scan function in the RawStorage trait, I expect to return KvPair to filter by key, but in fact it only returns Value.

### PR DESCRIPTION
**Pull request by joker53-1**
### What is changed and how it works?

Issue Number: Close #15246 

What's Changed:

```commit-message
Modify the return value of the scan function under the RawStorage trait.

* fix the scan function only return Value.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by andylokandy — APPROVED** [review]

**Comment by ekexium** [comment]
I'm not sure about the status of coprocessor-v2. Do we have any compatibility concerns?

**Comment by joker53-1** [comment]
@ekexium When I am using coprocessor-v2, I want to use the scan() function to get an array of Kvpair , but in fact I get an array of Value.I looked at the scan function under Storage, it also returns the Kvpair array.

**Comment by ekexium** [comment]
> @ekexium When I am using coprocessor-v2, I want to use the scan() function to get an array of Kvpair , but in fact I get an array of Value.I looked at the scan function under Storage, it also returns the Kvpair array.

I see. This looks like a breaking change and we can only accept it if we believe it won't break somebody else' usage.

**Comment by joker53-1** [comment]
> > @ekexium When I am using coprocessor-v2, I want to use the scan() function to get an array of Kvpair , but in fact I get an array of Value.I looked at the scan function under Storage, it also returns the Kvpair array.
> 
> I see. This looks like a breaking change and we can only accept it if we believe it won't break somebody else' usage.

Yes, this may affect others using coprocessor-v2.We are using coprocessor-v2 now, will this issue be fixed soon?

**Comment by andylokandy** [comment]
> I see. This looks like a breaking change and we can only accept it if we believe it won't break somebody else' usage.

@ekexium I kinda believe it'll not break other users, because it's unusable with the previous API.

**Comment by joker53-1** [comment]
> > @ekexium When I am using coprocessor-v2, I want to use the scan() function to get an array of Kvpair , but in fact I get an array of Value.I looked at the scan function under Storage, it also returns the Kvpair array.
> 
> I see. This looks like a breaking change and we can only accept it if we believe it won't break somebody else' usage.

 I also believe it'll not break other users,because its API is broken until I commited a PR  in tikv-client(rust) recently.[https://github.com/tikv/client-rust/pull/394](url)

**Comment by joker53-1** [comment]
@andylokandy Is it able to be merged or is there another way?

**Review by ekexium — APPROVED** [review]

**Comment by joker53-1** [comment]
Can this PR be merged? @andylokandy

**Pull request merged**
