### PR TITLE
raftstore: Fix incorrect raftstore applys memory trace

### LINKED ISSUE #15371: The applys count of memory trace keeps growing
### What version of TiKV are you using?

master

### What operating system and CPU are you using?

Not related

### What did you expect?
The applys count of memory trace keeps growing when merging and spliting regions back and forth.

### What did happened?
截屏2023-08-21 15 44 31

### PR DESCRIPTION
**Pull request by Connor1996**
### What is changed and how it works?

Issue Number: Close #15371 

What's Changed:

```commit-message
Fix incorrect raftstore applys memory trace. When performing dropping apply fsm, it should reset the 
memory trace to zero instead of calling `update_memory_trace`, otherwise it would record extra footage
of the interior vector capacity.
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
With this PR, the memory trace doesn't keep growing anymore.
image

### Release note 

```release-note
Fix incorrect raftstore applys memory trace
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]
Could you fix raftstore-v2 too?

**Comment by Connor1996** [comment]
> Could you fix raftstore-v2 too?

v2 doesn't have memory trace yet

**Review by overvenus — APPROVED** [review]

**Review by tonyxuqqi — APPROVED** [review]

**Pull request merged**
