### PR TITLE
raftstore: handle the race between creating new peer and splitting correctly

### PR DESCRIPTION
**Pull request by gengliqi**
### What problem does this PR solve?

Problem Summary:

cherry pick #8084 #8454 #9495 to release-4.0

### What is changed and how it works?

What's Changed:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

Side effects

- No

### Release note 
* Fix an issue that split may panic and corrupt the metadata if the split process is too slow and region merge is open.

### CODE REVIEW

**Comment by gengliqi** [comment]
The failed test `test_applied_lock_collector` will be fixed by https://github.com/tikv/tikv/pull/9510.
I cherry-pick this PR and this test can pass 100 times.

**Review by lhy1024 — APPROVED** [review]

**Review by NingLin-P — APPROVED** [review]

**Review by 5kbpers — APPROVED** [review]

**Pull request merged**
