### PR TITLE
external_storage: return io::TimedOut when error is retryable

### PR DESCRIPTION
**Pull request by YuJuncen**
#### Problem Summary: 

Before, even we have `RetryError` in `tikv_utils::stream`, sometimes we still fail when facing a long enough S3 outage (see https://github.com/pingcap/br/issues/774). Returning more detailed error info when meeting external storage error can make a more flexible retry strategy when we meeting problem likewise(That is, we don't need to update TiKV in the cluster but a BR binary). 

#### What's Changed:

For some errors that implements `RetryError`, when accessing external storage meeting them,  interface of `EnternalStorage` returns a `io::ErrorKind::TimedOut` now, which indices this would be retryable.

A new error variant of `backup.Error` is added (https://github.com/pingcap/kvproto/pull/735). So BR can identify retryable errors.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)

Added an integration test in `br_s3`, which introduced a 20s s3 outage. Retry at client side can be triggered.

image

### Release note 

- No release notes.

### CODE REVIEW

**Comment by gregwebs** [comment]
I have enhanced error handling in [my PR](https://github.com/tikv/tikv/pull/9706) which is tested and ready to merge but waiting on reviews. This PR will have a merge conflict :(
The enhanced error handling here is mostly complementary.

**Comment by gregwebs** [comment]
I would be happy to work with you to help get this merged. We definitely need more focus on refining error types, their meaning, and ensuring that failure messages propagate.

**Comment by gregwebs** [comment]
My PR is merged now. Sorry it ended up taking so long. These changes look good but of course have conflicts. Let me know if you are still able to push this forward.

**Comment by YuJuncen** [comment]
> My PR is merged now. Sorry it ended up taking so long. These changes look good but of course have conflicts. Let me know if you are still able to push this forward.

Awesome!  I'm not sure whether we should keep going on this PR... Seems a total rewrite is needed. Maybe close it and make a new one would be better? (BTW, I'm afraid I cannot push this forward before July due to things in my college... Also sorry for the delayed reply.)

**Comment by gregwebs** [comment]
A new PR is fine as well

**Comment by YuJuncen** [comment]
OK, let's close it.

**Pull request closed without merging**
