### PR TITLE
[DNM] Scheduler rw lock

### PR DESCRIPTION
**Pull request by hicqu**
only for tests, do not merge.

### CODE REVIEW

**Comment by siddontang** [comment]
How about the performance?

**Comment by siddontang** [comment]
have you tried https://github.com/Amanieu/parking_lot?

**Comment by hicqu** [comment]
A oltp_insert test shows TPS increases from 31k to 37k, but I didn't keep it because I was busy at debugging. I will benchmark it again with bug fixed version.

**Comment by zhangjinpeng1987** [comment]
https://github.com/tikv/tikv/pull/4829 has done the optimization.

**Pull request closed without merging**
