### PR TITLE
PCP: reduce size of tikv::storage::errors::Error

### PR DESCRIPTION
**Pull request by Renkai**
Signed-off-by: Renkai <gaelookair@gmail.com>

###  What have you changed?

This is an attempt to solve https://github.com/tikv/tikv/issues/5700 .
Since I am new to both Rust and TiKV, it might not be the final solution, I hope I can get some comment from reviewers to continue.

`std::mem::size_of::<tikv::storage::errors::Error>()` is now `120`, quite smaller than 200.

###  What is the type of the changes?
- Engineering (engineering change which doesn't change any feature or fix any issue)

###  How is the PR tested?
- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?
No 

###  Does this PR affect `tidb-ansible`?
No 
###  Refer to a related PR or issue link (optional)
https://github.com/tikv/tikv/issues/5700

### CODE REVIEW

**Comment by breeswish** [comment]
I don't think 120 makes difference in the performance, which requires a heavy memory copy as usual. An acceptable improvement would be reducing the error size to 8 bytes.

**Comment by Renkai** [comment]
@breeswish I will try to solve this issue in another way,this merge request can be closed.

**Comment by Renkai** [comment]
@breeswish Even a simple enum like this have a size of 16. 8 bytes might be too strict and we need  to change a lot of design to achieve it?
```
enum EE {
    A(Box<String>),
    B(i32)
}

fn main() {
    println!("{}", std::mem::size_of::<EE>()); // 16
}
```

**Comment by Renkai** [comment]
@breeswish I tried to wrap all referenced errors in box, but the size is still 24.I below definition is accepted,I will try to finish the rest job, but  the optimize result will temporary stay in 24.
```rust
quick_error! {
    #[derive(Debug)]
    pub enum Error2 {
        Engine(err: Box<EngineError>) {
            from()
            cause(err)
            description(err.description())
        }
        Txn(err: Box<txn::Error>) {
            from()
            cause(err)
            description(err.description())
        }
        Mvcc(err: Box<mvcc::Error>) {
            from()
            cause(err)
            description(err.description())
        }
        Closed {
            description("storage is closed.")
        }
        Other(err: Box<dyn error::Error + Send + Sync>) {
            from()
            cause(err.as_ref())
            description(err.description())
        }
        Io(err: Box<IoError>) {
            from()
            cause(err)
            description(err.description())
        }
        SchedTooBusy {
            description("scheduler is too busy")
        }
        GCWorkerTooBusy {
            description("gc worker is too busy")
        }
        KeyTooLarge(size: usize, limit: usize) {
            description("max key size exceeded")
            display("max key size exceeded, size: {}, limit: {}", size, limit)
        }
        InvalidCf (cf_name: Box<String>) {
            description("invalid cf name")
            display("invalid cf name: {}", cf_name)
        }
        PessimisticTxnNotEnabled {
            description("pessimistic transaction is not enabled")
        }
    }
}
```

**Comment by Renkai** [comment]
created https://github.com/tikv/tikv/pull/5940 another PR which reduce size to 24, any further suggests are welcomed.

**Pull request closed without merging**
