### PR TITLE
set master version to 3.0.0-alpha

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

## What have you changed? (mandatory)
Now it is 2.1.0-rc.2. When users switch from master to release-2.1, it looks they are upgrading but they are actually downgrading. So change version of master to 3.0.0-alpha

## What are the type of the changes? (mandatory)
- Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)
No code changes.

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)
No

## Does this PR affect tidb-ansible update? (mandatory)
No

### CODE REVIEW

**Comment by siddontang** [comment]
CI failed @breeswish 

```
test coprocessor::endpoint::tests::test_handle_time ... thread 'coprocessor::endpoint::tests::test_handle_time' panicked at 'assertion failed: resp[1].get_exec_details().get_handle_time().get_process_ms() >= 1500', src/coprocessor/endpoint.rs:1170:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:409
   6: tikv::coprocessor::endpoint::tests::test_handle_time
             at src/coprocessor/endpoint.rs:1170
   7: tikv::__test::TESTS::{{closure}}
             at src/coprocessor/endpoint.rs:1012
   8: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
   9: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1454
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:640
  10: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:106
```

**Comment by Connor1996** [comment]
Are we sure that the next version is 3.0 not 2.2?

**Comment by disksing** [comment]
@Connor1996 I guess so. /cc @siddontang

**Comment by disksing** [comment]
PTAL @siddontang

**Comment by siddontang** [comment]
yes, 3.0

**Pull request merged**
