### PR TITLE
github: Remove the pingcap/tidb-ansible from the PR template

### PR DESCRIPTION
**Pull request by hi-rustin**
### What is changed and how it works?

Issue Number: close https://github.com/tikv/tikv/issues/12103

What's Changed:

Remove the pingcap/tidb-ansible from the PR template. It has been archived.
### Related changes

None

### Check List 

Tests 

- No code

Side effects

None

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
/cc @BusyJay @skyzh 
Could you please take a look? Thanks! 💚 💙 💜 💛 ❤️

**Review by skyzh — APPROVED** [review]

**Review by ngaut — APPROVED** [review]

**Comment by hi-rustin** [comment]
/assign @skyzh 

Could you please hep me merge this PR?

**Pull request merged**
