### PR TITLE
replace rust-crypto with rust-openssl

### PR DESCRIPTION
**Pull request by niedhui**
Signed-off-by: niedhui <niedhui@gmail.com>

## What have you changed? (mandatory)

since rust-crypto hasn't been updated for couple of years, replace it with rust-openssl.
and will use it to implement other builtin encryption functions

## What are the type of the changes? (mandatory)

Improvement 

## How has this PR been tested? (mandatory)

unit test

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

no

## Does this PR affect tidb-ansible update? (mandatory)

no

## Refer to a related PR or issue link (optional)

#3875 #3275

### CODE REVIEW

**Comment by breeswish** [comment]
Seems that the build fails on CI. Maybe need to install openssl in system?

**Comment by niedhui** [comment]
crate `grpcio` links BoringSSL, which is incompatible with OpenSSL.  https://github.com/sfackler/rust-openssl/issues/765

**Comment by overvenus** [comment]
@niedhui FYI, we release grpcio 0.4.1 recently, which supports openssl.

**Comment by niedhui** [comment]
Good to know it. I'll take a look later.

**Comment by niedhui** [comment]
Ok, CI passed, seems openssl is alread installed on the CI server

some ontes:
1. after this change, build TiKV will need openssl to be installed
2. on MacOS,  `OPENSSL_ROOT_DIR` need to be export to run `cargo build`, eg: 
```
export OPENSSL_ROOT_DIR=$(brew --prefix openssl)
```

@overvenus can `grpcio` provide a 'vendor OpenSSL ' feature , like `openssl` crate?

**Comment by overvenus** [comment]
@niedhui We can enable the `vendor` feature in TiKV, I think openssl will be statically linked. https://docs.rs/openssl/0.10.15/openssl/#vendored

**Comment by niedhui** [comment]
hi @overvenus 
I tried this before, in Cargo.toml
```
grpcio = { version = "0.4", features = [ "openssl" ] }
openssl = { version = "0.10", features = ["vendored"] }
```
`grpcio` will complain to `Could NOT find OpenSSL`.   if we want `grpcio` to use the static linked openssl, it will need to use `openssl-src`  to tell it  where to find openssl.

**Comment by ice1000** [comment]
@niedhui Is it possible to modify grpcio to achieve what you want?
It's maintained by us.

**Comment by niedhui** [comment]
@ice1000 zero experiences with golang & c . Mabybe I'll try this later.
If `openssl` as a prerequisite is acceptable, we can process this PR first

**Comment by niedhui** [comment]
had opened PR in `grpcio` https://github.com/pingcap/grpc-rs/pull/262

**Comment by Hijiao** [comment]
Hi, @niedhui  could you please benchmark it and compare it to #3644 ?

**Comment by niedhui** [comment]
hi @Hijiao , we can use https://github.com/briansmith/crypto-bench to benchmark the `rust-crypto` and `openssl`.  for digest, if input data is small, `rust-crypto` is a little faster, when input data grows, `openssl` wins.
below is a simple code I wrote for benchmark `md5`. on my Mac, when length of data is 2000,  we got
```
MD5/crypto md5          time:   [4.6412 us 4.6596 us 4.6790 us]
MD5/openssl md5         time:   [3.1871 us 3.2029 us 3.2197 us]
```

```
#[macro_use]
extern crate criterion;
extern crate crypto;
extern crate hex;
extern crate openssl;

use criterion::{Criterion, Fun};
criterion_group!(benches, criterion_benchmark);
criterion_main!(benches);

fn md5_using_crypto(input: &[u8]) -> Vec<u8> {
    use crypto::{digest::Digest, md5::Md5};
    let mut hasher = Md5::new();
    let mut buff: [u8; 16] = [0; 16];
    hasher.input(input);
    hasher.result(&mut buff);
    hex::encode(buff).into_bytes()
}

fn md5_using_openssl(input: &[u8]) -> Vec<u8> {
    use openssl::hash::{self, MessageDigest};
    hash::hash(MessageDigest::md5(), input)
        .map(|digest| hex::encode(digest).into_bytes())
        .unwrap()
}

fn criterion_benchmark(c: &mut Criterion) {
    let crypto_md5 = Fun::new("crypto md5", |b, total| {
        b.iter(|| {
            let s = vec![0; *total];
            md5_using_crypto(&s);
        })
    });
    let openssl_md5 = Fun::new("openssl md5", |b, total| {
        b.iter(|| {
            let s = vec![0; *total];
            md5_using_openssl(&s);
        })
    });
    let functions = vec![crypto_md5, openssl_md5];
    c.bench_functions("MD5", functions, 2000);
}
```

**Comment by niedhui** [comment]
friendly ping @AndreMouche, I had refined this PR,  PTAL

**Comment by niedhui** [comment]
@overvenus resolve cargo.lock conflicts, please review again, thanks ~

**Comment by Hoverbear** [comment]
Hey this fixes! #5313 , cool!

**Comment by Hoverbear** [comment]
@niedhui Thanks for this. :)

**Pull request merged**
