### PR TITLE
Modify default value of high_pri_pool_ratio

### PR DESCRIPTION
**Pull request by pentium3**
Signed-off-by: pentium3 <celerond@msn.com>

## What have you changed? (mandatory)

Changes: Change default value of high_pri_pool_ratio.

## What are the type of the changes? (mandatory)

Improvement.

## How has this PR been tested? (mandatory)

Manually tested.

## Does this PR affect documentation (docs) or release note? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No

## Refer to a related PR or issue link (optional)

Test Log: https://internal.pingcap.net/confluence/pages/viewpage.action?pageId=62882849

### CODE REVIEW

**Comment by siddontang** [comment]
can you give the reason why do we need to change it?

**Comment by pentium3** [comment]
We compared the performance between different values [ https://internal.pingcap.net/confluence/pages/viewpage.action?pageId=62882849 ], and it shows that 0.8 is an appropriate value.

**Comment by siddontang** [comment]
Cool

But don't past our internal test link in the PR, you can paste the benchmark result directly.

**Comment by siddontang** [comment]
How about sysbench result?

**Comment by yiwu-arbug** [comment]
@siddontang regarding sysbench, benchbot shows neutral result.

**Comment by yiwu-arbug** [comment]
We got some data points for this change:
* YCSB with 80G data set and small block cache (either 100M and 50M) shows setting high-pri-pool-ratio to between 0.6-0.8 works better in most cases. (test 1 of https://internal.pingcap.net/confluence/pages/viewpage.action?pageId=62882849)
* YCSB with 80G data set and ~50G block cache show neutral result (test 2 of https://internal.pingcap.net/confluence/pages/viewpage.action?pageId=62882849)
* In the ElasticBF/Monkey test, enabling mid-point insertion (high-pri-pool-ratio=0.5) improves performance for rocksdb/ElasticBF/monkey performance consistently. https://internal.pingcap.net/confluence/display/TT/2019-09+Monkey+vs+Rocksdb

The rational of the change being:
* for small block cache, setting mid-point to something close to 1.0 reserve more of the cache for higher value entries (e.g. index and filters), and discard other entries quickly.
* for large block cache, midpoint insertion result in neutral result

For reference: 
* MyRocks has mid-point insertion enabled by default and the default mid-point is set to 0.5.
* RocksDB enable mid-point insertion (midpoint set at 0.5) by default from 6.4: https://github.com/facebook/rocksdb/commit/15fd3be07bd7a6fa29604277e9a9be21f458c426
* YogaByte default enable midpoint insertion (midpoint set at 0.8): https://github.com/yugabyte/yugabyte-db/blob/master/src/yb/rocksdb/util/cache.cc#L42

**Comment by Connor1996** [comment]
@yiwu-arbug should we cherry-pick the default value to release-3.0/release-2.1?

**Comment by yiwu-arbug** [comment]
> @yiwu-arbug should we cherry-pick the default value to release-3.0/release-2.1?

I don't think we need to. This can wait for the 4.0 release cycle.

**Pull request merged**
