### PR TITLE
clippy: Fix cargo-deny install for make clippy

### LINKED ISSUE #17928: Make clippy failed to install cargo-deny
## Bug Report

```shell
$ make clippy
info: component 'clippy' for target 'aarch64-apple-darwin' is up to date
Security check passed.
Log style check passed.
./metrics/grafana/tikv_details.json: OK
Dashboards check passed.
Docker build check passed.
License check passed.
    Updating crates.io index
  Installing cargo-deny v0.14.3
    Updating crates.io index
warning: profile package spec `insta` in profile `dev` did not match any packages

        Did you mean `bstr`?
warning: profile package spec `similar` in profile `dev` did not match any packages
error: failed to compile `cargo-deny v0.14.3`, intermediate artifacts can be found at `/var/folders/l4/mhxyx7851cq8mxshxt5vsyq40000gn/T/cargo-installXdA3Wh`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  package `cargo-platform v0.1.9` cannot be built because it requires rustc 1.78 or newer, while the currently active rustc version is 1.77.0-nightly
  Try re-running cargo install with `--locked`
```

### PR DESCRIPTION
**Pull request by Connor1996**
### What is changed and how it works?

Issue Number: Close #17928 

What's Changed:

Use `--locked` to make sure `cargo-deny` follows TiKV's `cargo.lock` for dependency 
```commit-message
Fix cargo-deny install for make clippy
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by glorv — APPROVED** [review]

**Review by hbisheng — APPROVED** [review]

**Comment by wuhuizuo** [comment]
@Connor1996 v8.1.x also need to be fix.

**Pull request merged**
