### PR TITLE
Replace futures' oneshot implementation with tokio's oneshot implementation

### LINKED ISSUE #5580: proposal: use tokio oneshot instead of futures'
### Is your feature request related to a problem? Please describe:

No

### Describe the feature you'd like:

I find that tokio has already provided a oneshot implementation, see https://docs.rs/tokio/0.1.15/tokio/sync/oneshot/fn.channel.html, so I did a simple test:

```rust
use test;
use futures::sync::oneshot as FutureOneshot;
use futures::{lazy, Future, future};
use tokio_sync::oneshot as TokioOneshot;
use tokio_threadpool;

#[bench]
fn benchmark_future_oneshot(b: &mut test::Bencher) {
    b.iter(move || {
        let (tx, rx) = FutureOneshot::channel();

        tx.send(1).unwrap();
        rx.wait().unwrap();
    });
}

#[bench]
fn benchmark_tokio_oneshot(b: &mut test::Bencher) {
    b.iter(move || {
        let (tx, rx) = TokioOneshot::channel();

        tx.send(1).unwrap();
        rx.wait().unwrap();
    });
}

#[bench]
fn benchmark_future_oneshot_pool(b: &mut test::Bencher) {
    let pool = tokio_threadpool::Builder::new().pool_size(1).build();
    let sender = pool.sender();

    b.iter(move || {
        let (tx, rx) = FutureOneshot::channel();

        sender.spawn(lazy(|| {
            tx.send(1).unwrap();
            future::ok::<(), ()>(())
        }));

        rx.wait().unwrap();
    });

    pool.shutdown().wait().unwrap();
}

#[bench]
fn benchmark_tokio_oneshot_pool(b: &mut test::Bencher) {
    let pool = tokio_threadpool::Builder::new().pool_size(1).build();
    let sender = pool.sender();

    b.iter(move || {
        let (tx, rx) = TokioOneshot::channel();

        sender.spawn(lazy(|| {
            tx.send(1).unwrap();
            future::ok::<(), ()>(())
        }));

        rx.wait().unwrap();
    });

    pool.shutdown().wait().unwrap();
}
```

```
test benchmark_future_oneshot              ... bench:         193 ns/iter (+/- 17)
test benchmark_future_oneshot_pool         ... bench:       9,591 ns/iter (+/- 1,421)
test benchmark_tokio_oneshot               ... bench:         138 ns/iter (+/- 12)
test benchmark_tokio_oneshot_pool          ... bench:       9,161 ns/iter (+/- 4,972)
```

The result is promising, as we can see, tokio oneshot is a bit faster, and it is easy for us to replace the futures' oneshot.

### Describe alternatives you've considered:
No

### Teachability, Documentation, Adoption, Migration Strategy:
No

### PR DESCRIPTION
**Pull request by psinghal20**
###  What have you changed?
Replace future's oneshot with tokio's oneshot implementation
The tokio's oneshot implementation is a little bit faster. Benchmarks for the same can be found on the issue #5580 

Replaced the `Cancelled` error found in futures' implementation with the tokio's `RecvError` error. 

###  What is the type of the changes?
Engineering

###  How is the PR tested?
I haven't run any test due to resource constraints on my local machine. I would need to depend on the CI for the tests. Ran `cargo-check`.

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?
No

###  Does this PR affect `tidb-ansible`?
No

###  Refer to a related PR or issue link (optional)
Resolves #5580

###  Benchmark result if necessary (optional)
I haven't run any benchmark for this change and would love a little help with that.

### CODE REVIEW

**Comment by siddontang** [comment]
Thanks, @psinghal20

**Comment by siddontang** [comment]
@zhouqiang-cl seems CI is down?

**Comment by zhouqiang-cl** [comment]
it must run after tests are passed. we will refector this

**Comment by siddontang** [comment]
PTAL @BusyJay

**Pull request merged**
