### PR TITLE
ci: add codecov.yaml file

### LINKED ISSUE #14995: Add codecov.yaml
## Development Task

- [ ] upload coverage with flags to separate types of testsing.
- [ ] ignore coverage path for integration and fuzz test cases and tools.

### PR DESCRIPTION
**Pull request by wuhuizuo**
### What is changed and how it works?

Issue Number: Close #14995

What's Changed:

```commit-message
ci: add codecov.yaml file
```

Ref:
- https://github.com/PingCAP-QE/ci/issues/2171

### Related changes

- None

### Check List 

Tests 

- No code

Side effects

- None

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tonyxuqqi — APPROVED** [review]

**Review by LykxSassinator — APPROVED** [review]
LGTM

**Review by purelind — APPROVED** [review]
/lgtm

**Pull request merged**
