### PR TITLE
Fix unstable test_joint_confchange test

### PR DESCRIPTION
**Pull request by hi-rustin**
Signed-off-by: hi-rustin <rustin.liu@gmail.com>

### What problem does this PR solve?

close https://github.com/tikv/tikv/pull/10692

Problem Summary:

### What is changed and how it works?

What's Changed:

Fix unstable test_joint_confchange test. Set correct min_ts_interval.

### Related changes

None

### Check List 

Tests 

- Unit test
- 
Side effects

None

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by zhouqiang-cl — APPROVED** [review]
LGTM

**Review by hicqu — APPROVED** [review]

**Comment by hi-rustin** [comment]
/unhold

Register cdc_ob before the node starts.

**Review by 5kbpers — APPROVED** [review]

**Pull request merged**
