### PR TITLE
split_controller: move sample_threshold check out of the split_key iteration

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

### What is changed and how it works?

What's Changed:

```commit-message
split_controller: move sample_threshold check out of the split_key iteration
```

Since the `evaluated_key_num` will always equal to the length of `self.key_ranges` inside a `Recorder`, so we do not need to do this check in every iteration of the `samples.split_key`. This PR moves `sample_threshold` check out of the `split_key` iteration to reduce the branch checking inside a loop.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
None.
```

### CODE REVIEW

**Comment by lhy1024** [comment]
What happens if a region has less than sample_threshold keys but qps exceeds the threshold？

**Review by lhy1024 — COMMENTED** [review]
What happens if a region has less than sample_threshold keys but qps exceeds the threshold？

**Comment by JmPotato** [comment]
> What happens if a region has less than sample_threshold keys but qps exceeds the threshold？

I will return an empty split key result as before.

**Review by lhy1024 — APPROVED** [review]

**Review by rleungx — APPROVED** [review]

**Review by disksing — APPROVED** [review]

**Pull request merged**
