### PR TITLE
metrics: add panels for slow score

### PR DESCRIPTION
**Pull request by 5kbpers**
Signed-off-by: 5kbpers <tangminghua@pingcap.com>

### What problem does this PR solve?

Problem Summary:
Add metric panels for slow score.

### What is changed and how it works?

What's Changed:

Add grafana panels to tikv-details pd.
image

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hunterlxt** [comment]
It is recommended to pull json content from the grafana instead of manually modifying the file

**Review by hunterlxt — APPROVED** [review]
LGTM except the trivial suggestion above

**Review by hicqu — APPROVED** [review]

**Pull request merged**
