### PR TITLE
[Dynamic Regions] Supplement extra uts for test_storage.rs.

### PR DESCRIPTION
**Pull request by LykxSassinator**
### What is changed and how it works?

Issue Number: ref #15409 

What's Changed:

```commit-message

This pr contains several necessary uts and some enhancements for `raftstore-v2`:
- Supply extra test cases, including integration tests and unit tests for raftstore-v2 on `storage`.
- Transplant the necessary options on setting `deadline` for `SimpleWrite` in raftstore-v2.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
None.
```

### CODE REVIEW

**Comment by LykxSassinator** [comment]
/cc @tonyxuqqi @SpadeA-Tang @overvenus.

PTAL, thx

**Review by SpadeA-Tang — APPROVED** [review]

**Review by overvenus — APPROVED** [review]

**Pull request merged**
