### PR TITLE
update kvproto for PR kvproto#777 (#10480)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #10480 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/10498
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/10498:release-5.1-094aeb001dbf
```

---

### What problem does this PR solve?

update kvproto for https://github.com/pingcap/kvproto/pull/777

### What is changed and how it works?

ditto

### Related changes

None

### Check List 

Tests 

- Unit test
- Integration test

Side effects

None

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by breeswish — APPROVED** [review]

**Comment by dragonly** [comment]
@breeswish @Little-Wallace PTAL again, thanks!

**Review by breeswish — APPROVED** [review]

**Review by Little-Wallace — APPROVED** [review]
LGTM

**Pull request merged**
