### PR TITLE
copr: (feat) Implement operator PartitionTopN

### PR DESCRIPTION
**Pull request by LittleFall**
### What is changed and how it works?

Issue Number: Ref https://github.com/tikv/tikv/issues/13936

What's Changed: 

Support operator PartitionTopN push down. 

This is the extended version of TopN, adding a new field "partition_by".

This will return TopN of each partition.

### Check List 

Tests 

- Unit test

### Release note 

(This feature's release note will be added in TiDB's pr)

```release-note
None
```

### CODE REVIEW

**Comment by LittleFall** [comment]
unrelated test failed
```

[2023-02-07T03:54:01.619Z] --- TRY 3 STDERR:        cdc::failpoints test_endpoint::test_cdc_rawkv_resolved_ts ---
[2023-02-07T03:54:01.619Z] thread 'test_endpoint::test_cdc_rawkv_resolved_ts' panicked at '6 8', components/cdc/tests/failpoints/test_endpoint.rs:518:5
[2023-02-07T03:54:01.619Z] stack backtrace:
[2023-02-07T03:54:01.619Z]    0: rust_begin_unwind
[2023-02-07T03:54:01.619Z]              at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/panicking.rs:575:5
[2023-02-07T03:54:01.619Z]    1: core::panicking::panic_fmt
[2023-02-07T03:54:01.619Z]              at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/core/src/panicking.rs:65:14
[2023-02-07T03:54:01.619Z]    2: failpoints::test_endpoint::test_cdc_rawkv_resolved_ts
[2023-02-07T03:54:01.620Z]    3: failpoints::test_endpoint::test_cdc_rawkv_resolved_ts::{{closure}}
[2023-02-07T03:54:01.620Z]    4: core::ops::function::FnOnce::call_once
[2023-02-07T03:54:01.620Z]    5: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}
[2023-02-07T03:54:01.620Z]    6: core::ops::function::FnOnce::call_once{{vtable.shim}}
[2023-02-07T03:54:01.620Z]    7: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
[2023-02-07T03:54:01.620Z]              at /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/alloc/src/boxed.rs:2000:9
[2023-02-07T03:54:01.620Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2023-02-07T03:54:01.620Z] 
[2023-02-07T03:54:01.620Z] error: test run failed
[2023-02-07T03:54:01.620Z] + gdb -c 'core.*' -batch -ex 'info threads' -ex 'thread apply all bt'
[2023-02-07T03:54:01.620Z] /home/jenkins/agent/tikv-master/build/core.*: No such file or directory.
[2023-02-07T03:54:01.620Z] No threads.
```

**Review by sticnarf — APPROVED** [review]
LGTM

**Review by wshwsh12 — APPROVED** [review]

**Pull request merged**
