### PR TITLE
*: log errors via box_err

### PR DESCRIPTION
**Pull request by overvenus**
## What have you changed? (mandatory)

There a lot of other error in tikv code base, and most of they do not produce any log. It becomes a hard task to track other errors if it happens. This PR produce an error level log when we can `box_err`.

## What are the type of the changes? (mandatory)

- Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)

No.

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

No.

## Does this PR affect tidb-ansible update? (mandatory)

No.

## Add a few positive/negative examples (optional)

It may print more logs compares to the current tikv and leads to log file bloat.

### CODE REVIEW

**Comment by BusyJay** [comment]
This seems an abuse and I'm afraid logs will be noisy and confusing.

**Comment by overvenus** [comment]
It is helpful for debugging. By logging errors, we can locate problems easily.

**Comment by siddontang** [comment]
can we use downcast to convert the Error to a specific type, then record the metric?

**Comment by breeswish** [comment]
Seems that this PR made recommendations to heavily use box_err (which produce Error::Other) because only `box_err` will automatically output error logs.

**Comment by MyonKeminta** [comment]
I used to thought that it's not a good idea to use box_err everywhere...

**Comment by overvenus** [comment]
> I used to thought that it's not a good idea to use box_err everywhere...

This PR by no means encourages to use `box_err!`, please do not misuse. I propose this PR because there are other errors displayed in grafana, and we can not find the cause of them.

**Pull request closed without merging**
