### PR TITLE
copr: support cast enum to any type

### PR DESCRIPTION
**Pull request by wshwsh12**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:
In pr https://github.com/tikv/tikv/pull/9648, it implements enum push down. But only implement cast enum to int/real/string. We need more types to support.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 

- No release note.

### CODE REVIEW

**Review by skyzh — APPROVED** [review]
Seems that `write_enum_to_chunk` is the same as `write_enum`. Is it necessary?

By the way, would you please explain a little bit about all these functions and when to use them? (Better in docstring)

**Review by Xuanwo — APPROVED** [review]

**Comment by wshwsh12** [comment]
> Seems that `write_enum_to_chunk` is the same as `write_enum`. Is it necessary?
> 
Only `write_enum_to_chunk` is ok.

**Pull request merged**
