### PR TITLE
workflows: add github review statistics in 7 days

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
Signed-off-by: zhangjinpeng1987 <zhangjinpeng@pingcap.com>

### What is changed and how it works?

close https://github.com/tikv/tikv/issues/12879

What's Changed:

```
Workflows: add github review statistics in latest 7 days, so contributors are easy to find associated reviewers for his PR.
```
ref to https://github.com/marketplace/actions/pull-request-stats

### Related changes

- No

### Check List 

Tests 

- No code

Side effects

No

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tonyxuqqi — APPROVED** [review]

**Review by BornChanger — APPROVED** [review]
LGTM~

**Review by nolouch — APPROVED** [review]

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by Connor1996 — COMMENTED** [review]
I don't see the stats in PR comment. Maybe you should change the file name

**Comment by zhangjinpeng1987** [comment]
This may encounter some permission issues, close it temporarily to prevent potential security issue.

**Pull request closed without merging**
