### PR TITLE
raftstore: reply to stale peer with tombstone message everytime

### PR DESCRIPTION
**Pull request by gengliqi**
Signed-off-by: gengliqi <gengliqiii@gmail.com>

### What problem does this PR solve?

Problem Summary:
If a leader receives the message from a stale peer(follower or learner), it may not reply to this peer a tombstone msg which may cause a stale region can not be destroyed for a long time. 
Also, https://github.com/tikv/tikv/issues/10341 the problem described here can be alleviated.

### What is changed and how it works?

What's Changed:
Since the number of msg from stale peers should be small, this PR totally removes the condition of whether to send tombstone msg or not. 

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

Side effects

- No

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by solotzg** [comment]
lgtm

**Review by NingLin-P — APPROVED** [review]

**Review by nolouch — APPROVED** [review]
lgtm

**Review by BusyJay — CHANGES_REQUESTED** [review]
I don't think it's a good idea. If a peer is not isolated, it should remove it self in the end by applying logs.

**Comment by NingLin-P** [comment]
> I don't think it's a good idea. If a peer is not isolated, it should remove it self in the end by applying logs.

Which could take minutes, and even longer for the learner. And with this PR, the peer only destroys itself by gc msg when it can't destroy itself by applying logs.

**Comment by BusyJay** [comment]
> ...when it can't destroy itself by applying logs.

How? The PR only checks epoch, so even `MsgAppendResponse` can also trigger self-destruction.

**Comment by NingLin-P** [comment]
> > ...when it can't destroy itself by applying logs.
> 
> How? The PR only checks epoch, so even `MsgAppendResponse` can also trigger self-destruction.

The leader won't send any msg to a removed peer. So in this case, the peer can only destroy itself if it has the `confchange` log and knows the log is committed. And when it receives a gc msg, it will send msg to destroy the apply fsm first, so the committed `confchange` log (if any) will be applied before destroy.

**Comment by BusyJay** [comment]
> The leader won't send any msg to a removed peer. So in this case, the peer can only destroy itself if it has the `confchange` log and knows the log is committed. And when it receives a gc msg, it will send msg to destroy the apply fsm first, so the committed `confchange` log (if any) will be applied before destroy.

For example, leader sends two messages to follower, the first one is MsgAppend with latest logs and commit index, the second one is gc message and follower handles two messages during a ready. So it will not wait applying entries, instead remove it self directly.

**Comment by NingLin-P** [comment]
> For example, leader sends two messages to follower, the first one is MsgAppend with latest logs and commit index, the second one is gc message and follower handles two messages during a ready. So it will not wait applying entries, instead remove it self directly.

It seems to be a rare case that the raft msg (carry the commitment of the `confchange`) and the gc msg are handled in the same `Ready`, and I think it is totally valid to destroy a peer by gc msg even the peer is not isolated, since we already allow to doing so.

**Comment by BusyJay** [comment]
> ...since we already allow to doing so.

This only happens after some time, and follower is unlikely to catch up logs.

I suggest to only handle non-response message instead.

**Comment by NingLin-P** [comment]
> This only happens after some time, and follower is unlikely to catch up logs.

This could happen as long as the leader applies the `confchange` log before the follower's `MsgAppendResponse` of the `confchange`arrived. And in cases I encountered there is no network isolation.

**Comment by gengliqi** [comment]
> > For example, leader sends two messages to follower, the first one is MsgAppend with latest logs and commit index, the second one is gc message and follower handles two messages during a ready. So it will not wait applying entries, instead remove it self directly.
> 
> It seems to be a rare case that the raft msg (carry the commitment of the `confchange`) and the gc msg are handled in the same `Ready`, and I think it is totally valid to destroy a peer by gc msg even the peer is not isolated (and has the `confchange` log), since we already allow to doing so.

I agree it's a rare case. If leader has applied the conf change log, it won't send any append msg to this removed peer. Only after that, leader will send a tombstone msg to this removed peer when receiving any msg from this peer. In other words, the peer can not catch up when receiving tombstone msg. 
If we want to try our best to make peer removed after applying conf change, it's better to make the peer apply all the committed raft log before removing rather than not sending tombstone msg in some cases on leader side.

**Comment by BusyJay** [comment]
> ...it's better to make the peer apply all the committed raft log before removing...

This looks good to me too.

**Comment by NingLin-P** [comment]
> > ...it's better to make the peer apply all the committed raft log before removing...
> 
> This looks good to me too.

Besides the abovementioned case (assume msg arrive in order), the peer will apply all known committed logs before destroy. And for that case, while handling gc msg, I think we can get a `Ready` and send the committed log to apply worker first and then send another msg to destroy apply fsm.

**Comment by NingLin-P** [comment]
Or we can handle the gc msg on the next round, so all know committed logs will be handled and apply before the gc msg remove destroy the `ApplyFsm` and `PeerFsm`. We can do it by keeping the gc msg in `poll_ctx` and resend the msg at `PollHandler::end` (also add some flag to distinguish the gc msg that can handle without delay).

**Comment by gengliqi** [comment]
> Or we can handle the gc msg on the next round, so all known committed logs will be handled and applied before the gc msg destroy the `ApplyFsm` and `PeerFsm`. We can do it by keeping the gc msg in `poll_ctx` and resend the msg at `PollHandler::end` (also add some flag to distinguish the gc msg that can be handled without delay).
I make a small change that is similar to this method.
Add a new `PeerMsg::Destroy` and send it after handling `tombstone msg`. Thus we can ensure the committed entries are applied as many as possible.

**Review by BusyJay — APPROVED** [review]

**Review by NingLin-P — APPROVED** [review]

**Pull request merged**
