### PR TITLE
release: update version and CHANGELOG.md for v2.1.2

### PR DESCRIPTION
**Pull request by huachaohuang**

### CODE REVIEW

**Comment by huachaohuang** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by huachaohuang** [comment]
/run-all-tests tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by zhouqiang-cl** [comment]
/run-integration-common-test tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Comment by huachaohuang** [comment]
/run-integration-common-test tidb=release-2.1 tikv=release-2.1 tidb-test=release-2.1

**Pull request merged**
