### PR TITLE
Update .dockerignore

### PR DESCRIPTION
**Pull request by Connor1996**
## What have you changed? (mandatory)
add `target` to `.dockerignore` to save time for `docker build`

## What are the type of the changes? (mandatory)
- Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)
manual test

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)
No 

## Does this PR affect tidb-ansible update? (mandatory)
No 

## Add a few positive/negative examples (optional)
before:
```bash
docker build -t hub.pingcap.com/pingcap/tikv:v2.1.0-rc.1 .
Sending build context to Docker daemon  23.65GB
```

after:
```bash
docker build -t hub.pingcap.com/pingcap/tikv:v2.1.0-rc.1 .
Sending build context to Docker daemon  312.6MB
```

### CODE REVIEW

**Comment by tennix** [comment]
It will not make a big Docker image, it only affects the build process, it will send all current directory contents to Docker daemon but the resulting image is still the same size.

**Comment by siddontang** [comment]
But this can still save the disk space? @tennix

**Comment by tennix** [comment]
It saves time building the Docker image. My above comment is to point the incorrect description of the first comment
> add `target` to `.dockerignore`, otherwise it will make too large image when `docker build`

**Comment by Connor1996** [comment]
@tennix oh, got it

**Pull request merged**
