### PR TITLE
txn: Check constraint when retrying prewrite of non-pessimistic-locked keys in pessimistic transactions

### PR DESCRIPTION
**Pull request by MyonKeminta**
### What problem does this PR solve?

ref  #11187
(Imperfect fix, so do not close that issue).

Problem Summary: Prewrites of pessimistic transactions skips checking constraints on data. For a pessimistic transaction, if a prewrite request on a non-pessimistic-lock key is repeated due to something like network issues, it's possible that it successfully acquires the lock even the transaction has already been successfully committed (and maybe even some more versions were written to the key).

This affects CDC and stale read (luckily CDC has other approach to avoid this problem), and might affect data consistency in some very rare cases.

In this PR, prewrite requests of non-pessimistic-lock keys in pessimistic transactions with is_retry_request flags (......) won't skip constraint check, which mostly solves the problem but still imperfect (considering that it's  theoretically possible that the first request arrives later than a retrying request).

### What is changed and how it works?

What's Changed: This PR changes the logic of `skip_constraint_check` function so that pessimistic prewrite requests of those kind stated above will not skip constraint check.
This change also covers the case in https://github.com/tikv/tikv/pull/10600 , but should have no affect to it.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression

### Release note 

```release-note
Fix the bug that prewrite request retrying in pessimistic transactions have risk to affect data consistency in some rare cases.
```

I actually don't know how to write release note for this thing...

### CODE REVIEW

**Comment by cfzjywxk** [comment]
` prewrite requests of non-pessimistic-lock keys in pessimistic transactions with is_retry_request flags (......)` 
Quite a long phrase

**Review by cfzjywxk — APPROVED** [review]
LGTM

**Review by sticnarf — APPROVED** [review]
LGTM

**Pull request merged**
