### PR TITLE
raftstore: Add hibernate region metrics (#10152)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #10152 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/10273
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/10273:release-5.0-0f5f66632b4d
```

---

### What problem does this PR solve?

Adding hibernate region metrics

Problem Summary:

### What is changed and how it works?

What's Changed:
Adding the following metrics
* region count in different hibernate state, breakdown by leader/non-leader
* leader count in different hibernate leader state (awaken/poll/hibernated)

example:
It is in the "Server" pannel.
Screen Shot 2021-05-26 at 11 27 55 PM

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release notes

### CODE REVIEW

**Review by yiwu-arbug — APPROVED** [review]

**Review by 5kbpers — APPROVED** [review]

**Comment by yiwu-arbug** [comment]
Test consistently failing on `raftstore::test_replica_read::test_read_index_retry_lock_checking ... thread 'main' panicked at 'assertion failed: resp1.recv_timeout(Duration::from_secs(2)).is_err()', tests/integrations/raftstore/test_replica_read.rs:343:5`. Not sure if it is related.

**Comment by yiwu-arbug** [comment]
1

> Test consistently failing on `raftstore::test_replica_read::test_read_index_retry_lock_checking ... thread 'main' panicked at 'assertion failed: resp1.recv_timeout(Duration::from_secs(2)).is_err()', tests/integrations/raftstore/test_replica_read.rs:343:5`. Not sure if it is related.

cc @BusyJay

**Comment by yiwu-arbug** [comment]
cc @sticnarf

**Comment by sticnarf** [comment]
> cc @sticnarf

This test consistently fails at my place now. I will investigate and solve it...

**Pull request merged**
