### PR TITLE
storage: remove local storage create directory (#9062)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #9062 to release-4.0

---

Signed-off-by: 3pointer <luancheng@pingcap.com>

### What problem does this PR solve?

Issue Number: close https://github.com/tikv/tikv/issues/9051

### What is changed and how it works?

What's Changed:
stop create directory in local storage.
### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

### Release note 
- No release note.

### CODE REVIEW

**Comment by kennytm** [comment]
please fix merge conflict @3pointer

**Comment by overvenus** [comment]
I'll solve conflicts.

**Comment by overvenus** [comment]
LGTM

**Review by lichunzhu — APPROVED** [review]
LGTM

**Review by BusyJay — APPROVED** [review]

**Pull request merged**
