### PR TITLE
metrics: fix grafana expr for `tikv_gc_compaction_filtered`

### LINKED ISSUE #13537: The expr for `GC in Compaction Filter` meets parse error
origin_img_v2_e7109ee1-4839-4449-842d-a30beaed413g

### PR DESCRIPTION
**Pull request by Defined2014**
### What is changed and how it works?

Issue Number: Close #13537

What's Changed: 

```commit-message
fix error grafana expr for `tikv_gc_compaction_filtered `
```

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
image
No error in grafana.

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by Defined2014** [comment]
/cc @sticnarf @5kbpers 
PTAL

**Review by sticnarf — APPROVED** [review]
LGTM

**Comment by sticnarf** [comment]
cc @ystaticy

**Review by 5kbpers — APPROVED** [review]

**Pull request merged**
