### PR TITLE
[DNM] Unistore storage: separate latest version and history versions

### PR DESCRIPTION
**Pull request by zhangjinpeng87**
Implement [Unistore storage](https://github.com/ngaut/unistore): separate latest version and history versions.

### CODE REVIEW

**Comment by mahjonp** [comment]
/bench
```
workload:
  prepare: true
```

**Comment by zhangjinpeng1987** [comment]
/bench
```
workload:
  prepare: true
```

**Comment by zhangjinpeng1987** [comment]
/bench
```
workload:
  prepare: true
  threads: 512
```

**Comment by zhangjinpeng87** [comment]
Close PR since it is stale for years.

**Pull request closed without merging**
