### PR TITLE
readpool: fix pending tasks counter

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: ref #16026

What's Changed:

```
Decrease pending tasks counter when spawn return "Full" error
```

### Check List 

Tests 

- Unit test

Side effects

### Release note 

```release-note
Fix the bug that read-pool running tasks count maybe incorrect when the queue is near full
```

### CODE REVIEW

**Comment by glorv** [comment]
@nolouch @Connor1996 PTAL

**Review by nolouch — APPROVED** [review]
lgtm

**Review by Connor1996 — APPROVED** [review]
LGTM

**Pull request merged**
