### PR TITLE
cdc: move old value code to a separate file

### PR DESCRIPTION
**Pull request by 5kbpers**
Signed-off-by: 5kbpers <tangminghua@pingcap.com>

### What problem does this PR solve?

Problem Summary:
Code related to old value exists in serval files.

### What is changed and how it works?

What's Changed:
Reorg them into one separate file.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:

### Check List 

Tests 

- Unit test
- Integration test

### Release note 
* N/A

### CODE REVIEW

**Review by MyonKeminta — APPROVED** [review]

**Review by overvenus — COMMENTED** [review]
/lgtm

**Pull request merged**
