### PR TITLE
cop: remove Copy trait of RpnFnCallPayload

### PR DESCRIPTION
**Pull request by H-ZeX**
Signed-off-by: H-ZeX <hzx20112012@gmail.com>

## What have you changed? (mandatory)

-  remove Copy trait of `RpnFnCallPayload`

## What are the type of the changes? (mandatory)

- Engineering (engineering change which doesn't change any feature or fix any issue)

## How has this PR been tested? (mandatory)

No.

## Does this PR affect documentation (docs) or release note? (mandatory)

No.

## Does this PR affect tidb-ansible update? (mandatory)

No.

## Refer to a related PR or issue link (optional)

https://github.com/tikv/tikv/pull/4973#issuecomment-506310744

### CODE REVIEW

**Comment by breeswish** [comment]
Why is it removed?

**Comment by H-ZeX** [comment]
@breeswish Because the `RpnFnCallPayload` is very large(24B, include the padding), pass it by reference is much better.

**Comment by breeswish** [comment]
I think this doesn't mean that `Copy` should not be implemented. In fact `Copy` is still preferred over `Clone` if you *really* want a copy of the data.

**Comment by breeswish** [comment]
Maybe a complete removal of `RpnFnCallPayload` can be considered. `RpnFnCallPayload` is introduced only to **group** parameters necessary when evaluating a function. Previously we needed to write out all these necessary parameters when introducing a UDF, no matter whether they are really needed or not, which is pretty verbose. Now we have `#[rpn_fn]` and the signature can be pretty clean in most of the cases when these raw parameters in `RpnFnCallPayload` are not needed.

**Comment by breeswish** [comment]
@sticnarf Please also take a look

**Comment by sticnarf** [comment]
Yes, I agree we can consider removing the payload.
The only reason why I suggest removing `Copy` is to make clippy happy...

**Comment by breeswish** [comment]
Closing for https://github.com/tikv/tikv/pull/5007 since it will remove Copy (and Clone).

**Pull request closed without merging**
