### PR TITLE
Cleanup IO rate limiter related code

### PR DESCRIPTION
**Pull request by tabokie**
Signed-off-by: tabokie <xy.tao@outlook.com>

### What problem does this PR solve?

Prepping for #9197

### What is changed and how it works?

What's Changed:

1. Purge unnecessary dependency on global IO rate limiter
2. Port some RocksDB accessors
3. Introduce `LevelZeroCompaction` IO type
4. Fix some broken IO tagging

### Check List

Tests
- Unit test

### Release note

- No release note

### CODE REVIEW

**Review by yiwu-arbug — APPROVED** [review]
Looking good overall to me. Defer to @Connor1996 for more detailed review.

**Review by Connor1996 — APPROVED** [review]
LGTM

**Pull request merged**
