### PR TITLE
grafana: filter out untouched storage command (#10999)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #10999 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/11001
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/11001:release-5.0-f13318c93af8
```

---

### What problem does this PR solve?

Problem Summary:

Previously, all storage commands are shown no matter whether it is used. There's always the case that verbose "Scheduler - raw-xxx" rows occupy the screen and draw one crazy when looking through the metrics back and forth. 
image

### What is changed and how it works?

What's Changed:

Filter out the untouched storage command, so only the command that has been called ever will show up in the dashboard.

before:
截屏2021-09-28 下午3 54 47

after:
截屏2021-09-28 下午3 54 35
### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

### Release note 

```release-note
Hide untouched storage commands' metrics in grafana dashboard
```

### CODE REVIEW

**Review by gengliqi — APPROVED** [review]

**Comment by zhouqiang-cl** [comment]
@ti-chi-bot

**Pull request merged**
