### PR TITLE
copr: Add vectorize to_seconds

### PR DESCRIPTION
**Pull request by mantuliu**
### What problem does this PR solve?
Add vectorize to_seconds

### What is changed and how it works?

- Improvement (a change which is an improvement to an existing feature)

### Check List 

Tests 

- Unit test

### CODE REVIEW

**Comment by skyzh** [comment]
You may remove billable from attributes for better performance. Please refer to examples at the end of this RFC for more information. https://github.com/tikv/rfcs/pull/43

**Comment by skyzh** [comment]
#8365 also serves as an example :)

**Comment by Fullstop000** [comment]
LGTM

**Comment by Fullstop000** [comment]
@breeswish

**Comment by TennyZhuang** [comment]
@breeswish

**Pull request merged**
