### PR TITLE
raftstore: Reject transferring leader to store that having log lag after a restart

### PR DESCRIPTION
**Pull request by Connor1996**
### What is changed and how it works?

A part of #11409  

What's Changed:
- Collect replicate log lag in `raft_log_gc_tick` and apply log lag in `on_apply_res`
- Reject transfer leader to the store having region with replicate log lag within 10min after the start
- Reject transfer leader to the store having region with apply log lag within 10min after the start

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
Reject transferring leader to store that having log lag after a restart
```

### CODE REVIEW

**Comment by BusyJay** [comment]
> ...within 10min after the start

Why?

**Comment by Connor1996** [comment]
> > ...within 10min after the start
> 
> Why?

In heavy write workload, it may have apply log lag due to high apply duration. In that case, it's unexpected to reject transferring log. So just check it within a time span after restart. 10min is just a time span with which log lag should be possibly caught up.

**Comment by BusyJay** [comment]
> In heavy write workload, it may have apply log lag due to high apply duration.

Yes, but isn't it checked by the current pre-transfer implementation already? Why need a time span?

> In that case, it's unexpected to reject transferring log.

I don't get it, if it has large apply log lag, then reject transferring should be a safe move.

**Comment by Connor1996** [comment]
> Yes, but isn't it checked by the current pre-transfer implementation already? Why need a time span?

What the current implementation does is reject transferring leader if the region has log lag. This PR does if the store has any regions having log lag, reject transferring leader to the store no matter which region.

**Comment by Connor1996** [comment]
> I don't get it, if it has large apply log lag, then reject transferring should be a safe move.

If all the stores are under high apply duration, then the cluster wouldn't do any transfer leader operation. It's unexpected.

**Comment by Connor1996** [comment]
Why it's unexpected? The reason it doesn't transfer leader is to avoid triggering down time for any regions.

That's why only limit this PR's mechanism within 10min after a restart. The current pre-transfer implementation is still kept.

> I don't think it's a good idea. A single peer has log lag may just because it's a hotspot. Other peers can still apply logs in a reasonable speed. We have developed yield mechanism which allows idle peers apply logs even being scheduled with a busy peer.

Even with yield mechanism, the high apply duration still affects the tail latency. See 
截屏2022-01-17 下午5 22 50
截屏2022-01-17 下午5 23 06

**Comment by BusyJay** [comment]
Why not just let PD don't schedule leader to a recently started busy node if possible?

**Comment by Connor1996** [comment]
> Why not just let PD don't schedule leader to a recently started busy node if possible?

But how to define `busy`. Still need TiKV to check the replicate log lag and apply log lag. The replicate log lag can be only checked on the leader side, it's a little weird to report other stores' statuses by leader's store heartbeat report.

**Comment by BusyJay** [comment]
> But how to define `busy`. Still need TiKV to check the replicate log lag and apply log lag. The replicate log lag can be only checked on the leader side, it's a little weird to report other stores' statuses by leader's store heartbeat report.

It can just check the apply duration. Actually log gap is an indirect observation of busy, the CPU usage or the apply duration is a direct observation. On the other hand, scheduling an operator and let it timeout is just a waste. But make PD not scheduling such operator in the first place is a win for all.

**Comment by Connor1996** [comment]
> It can just check the apply duration. Actually log gap is an indirect observation of busy, the CPU usage or the apply duration is a direct observation. On the other hand, scheduling an operator and let it timeout is just a waste. But make PD not scheduling such operator in the first place is a win for all.

I agree not letting PD schedule transfer leader operator is a better choice for apply log lag. But how does it handle replicate log lag. Before logs are caught up, the apply duration is still low. At that time, PD would permit transfer leader, whereas after the log are caught up, the apply duration may high but the leaders are already on that store.

**Comment by NingLin-P** [comment]
> I agree not letting PD schedule transfer leader operator is a better choice for apply log lag. But how does it handle replicate log lag. Before logs are caught up, the apply duration is still low. At that time, PD would permit transfer leader, whereas after the log are caught up, the apply duration may high but the leaders are already on that store.

The pre-transfer mechanism check `last_index >= index + ctx.cfg.leader_transfer_max_log_lag` where `last_index` is the index of leader's last raft log and `index` is the follower's applied index, so both apply/replicate log lag should have been checked.

But with the default config `leader_transfer_max_log_lag: 128` and `raft_entry_max_size: ReadableSize::mb(8)`, the size of the lagging logs may still be quite large due to write hotspot and request batching (which batch multiple requests into one raft log).

**Comment by Connor1996** [comment]
Implemented in https://github.com/tikv/tikv/pull/16239

**Pull request closed without merging**
