### PR TITLE
copr: read value when common handle only contain prefix column

### PR DESCRIPTION
**Pull request by lysu**
Signed-off-by: lysu <sulifx@gmail.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/22811

Problem Summary:

tikv will avoid read value when required column in common handle

but common handle's columns maybe not contain full columns value (like `primary key(c(1))`)

### What is changed and how it works?

What's Changed:

read kv's value when required column in common handle is the prefix of column

need merge https://github.com/pingcap/tidb/pull/22829 first

### Related changes

- n/a

### Check List 

Tests 

- Integration test(WIP)

Side effects

- n/a

### Release note 

- no release note

---
This change is [Reviewable](https://reviewable.io/reviews/tikv/tikv/9670)

### CODE REVIEW

**Comment by lysu** [comment]
@sticnarf @MyonKeminta @iosmanthus PTAL if free thanks

**Review by sticnarf — COMMENTED** [review]
The fix lgtm. Yet I prefer there could be a unit test here for a prefix column pk.

**Review by sticnarf — APPROVED** [review]
LGTM

**Comment by lysu** [comment]
@iosmanthus @breeswish @AndreMouche PTAL, need help from bug jail :sob:

**Review by wjhuang2016 — COMMENTED** [review]
/lgtm

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Comment by lysu** [comment]
hi @wjhuang2016 please help re-LGTM by correct posture https://book.prow.tidb.io/#/plugins/lgtm again if free

**Comment by lysu** [comment]
@sticnarf Please help merge thank :smile:

**Pull request merged**
