### PR TITLE
config: enable dynamically change config pessimistic-txn.pipelined (#8422)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #8422 to release-4.0

---

### What problem does this PR solve?

Problem Summary:

`pessimistic-txn.pipelined` was marked as can be dynamically changed, but did not update the value in where the config used.

### What is changed and how it works?

What's Changed:

Use `Arc<AtomicBool>` to keep sync with the latest value of `pessimistic-txn.pipelined`.

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 
- config: enable dynamically change config pessimistic-txn.pipelined

### CODE REVIEW

**Comment by gengliqi** [comment]
How is it going?

**Comment by NingLin-P** [comment]
There are lots of changes this PR depend on didn't cherry-pick to release-4.0, so I think we better disable the dynamically change feature for `pessimistic-txn.pipelined` on release-4.0 /cc @youjiali1995

**Comment by youjiali1995** [comment]
> There are lots of changes this PR depend on didn't cherry-pick to release-4.0, so I think we better disable the dynamically change feature for `pessimistic-txn.pipelined` on release-4.0 /cc @youjiali1995

OK. I will cherry pick by manual when I'm free.

**Review by youjiali1995 — APPROVED** [review]

**Review by gengliqi — APPROVED** [review]

**Review by 5kbpers — APPROVED** [review]

**Pull request merged**
