### PR TITLE
res_meter: upgrade kvproto

### LINKED ISSUE #11748: Upgrade kvproto for resource_metering
## Development Task

Co-update TiKV's `kvproto` with https://github.com/pingcap/kvproto/pull/847

### PR DESCRIPTION
**Pull request by mornyx**
Signed-off-by: mornyx <mornyx.z@gmail.com>

### What is changed and how it works?

Close #11748

- Upgrade `kvproto` to https://github.com/pingcap/kvproto/pull/847

### Related PR

- https://github.com/pingcap/kvproto/pull/847
- https://github.com/pingcap/ng-monitoring/pull/81

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by mornyx** [comment]
/cc @zhongzc @breeswish 

PTAL, Thanks

**Review by breeswish — APPROVED** [review]

**Comment by breeswish** [comment]
@mornyx Please update to use the master branch of kvproto. Thanks!

**Review by breeswish — APPROVED** [review]

**Comment by breeswish** [comment]
@zhongzc PTAL

**Review by zhongzc — APPROVED** [review]

**Pull request merged**
