### PR TITLE
*: upgrade toolchain to 2020-07-01

### PR DESCRIPTION
**Pull request by sticnarf**
### What is changed and how it works?

https://blog.rust-lang.org/inside-rust/2020/06/29/lto-improvements.html mentions a series of optimizations that improve disk space and LTO.

On my PC, upgrading the toolchain to latest reduces clean `make release` time from 6m30s to 6m04s.

The new compiler also detects a bug in the previous code because `#[cfg(linux)]` actually invalidate the decorated code.

The rest changes are fixing clippy lints.

It is also worth mentioning that, the new compiler marks specialization an incomplete feature. Some kind of use of specialization is unsound. An issue https://github.com/tikv/tikv/issues/8170 is created to track it.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

Upgrade the Rust toolchain to 2020-07-01.

### CODE REVIEW

**Comment by AndreMouche** [comment]
LGTM

**Comment by sticnarf** [comment]
@youjiali1995 @breeswish Upgrading the toolchain exposes another problem that the `test_load_info` test will actually fail. A fix is on the way.

**Comment by youjiali1995** [comment]
We should upgrade it more frequently. 😅

**Comment by AndreMouche** [comment]
LGTM cancel

**Comment by youjiali1995** [comment]
LGTM

**Pull request merged**
