### PR TITLE
upgrade crossbeam_channel

### PR DESCRIPTION
**Pull request by hawkingrei**
What have you changed? (mandatory)

Bump crossbeam_channel to 0.2.43 and simple code 

What are the type of the changes? (mandatory)

Improvement
How has this PR been tested? (mandatory)

unittest
Does this PR affect documentation (docs/docs-cn) update? (mandatory)

No
Does this PR affect tidb-ansible update? (mandatory)

No

### CODE REVIEW

**Comment by siddontang** [comment]
PTAL @BusyJay

**Comment by BusyJay** [comment]
Thanks for your contribution! New crossbeam-channel brings back the close-aware interface, so closing receiver can be detected by default. Can you remove the redundant check in mpsc?

**Comment by hawkingrei** [comment]
OK,i will fix it.

**Comment by hawkingrei** [comment]
PLAT @ice1000 @BusyJay

**Comment by hawkingrei** [comment]
I find that the #3738 has upgraded the crossbeam-channel and refactor the mpsc. so I closed it. : - )

**Comment by siddontang** [comment]
Thanks @hawkingrei 

Can you help us review # 3738?

**Pull request closed without merging**
