### PR TITLE
copr: Implement From<Utf8Error> for EvaluateError

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

### What problem does this PR solve?

Code cleanup for utf-8 error handling.

### What is changed and how it works?

Implement From<Utf8Error> for EvaluateError

### Check List

Tests

- Unit test
- Integration test

Release note

- No release note

### CODE REVIEW

**Comment by andylokandy** [comment]
Awesome! Thank you.

**Review by skyzh — APPROVED** [review]
Good work!

**Pull request merged**
