### PR TITLE
tikv_util: call _exit instead of exit in panic hook

### PR DESCRIPTION
**Pull request by Connor1996**
## What have you changed? (mandatory)
When calling exit() in panic_hook, it triggers global static to destroy, like c++ static dtors, which may cause other threads encounter `pure virtual method call`. So using `_exit` instead of `exit`.

## What are the type of the changes? (mandatory)
- Bug fix (change which fixes an issue)

### CODE REVIEW

**Comment by Connor1996** [comment]
PTAL @BusyJay @brson @nrc

**Comment by Connor1996** [comment]
As far as I understood, the `process::abort` doesn't flush buffered io either. So exit without buffered io flushed is acceptable under our mechanism? @breeswish

**Comment by zhongzc** [comment]
> By calling `_exit` instead of `exit`, buffered io is also not flushed at exit. Is this intended?

Today I lost backtrace haven't been flushed, which confusing me a lot. Can we reconsider the way to handle?

**Comment by Connor1996** [comment]
@zhongzc maybe flush manually before calling `_exit`?

**Comment by Connor1996** [comment]
@zhongzc  https://github.com/tikv/tikv/pull/10213 This PR should solve your problem.

**Pull request merged**
