### PR TITLE
*: rename Arrow to chunk

### PR DESCRIPTION
**Pull request by wshwsh12**
Signed-off-by: wshwsh12 <793703860@qq.com>

###  What have you changed?

Please explain in detail what the changes are in this PR and why they are needed:

In tidb, use `arrow` instead of `chunk` in some places. This can be misleading.
In this pr, I change all `arrow` to `chunk`.

Don't assume reviewers understand the original issue.

###  Refer to a related PR or issue link (optional)

https://github.com/pingcap/tipb/pull/151

### CODE REVIEW

**Comment by breeswish** [comment]
Actually I prefer Arrow than the Chunk, because there are too many places using chunk to refer another thing.. while Arrow is a very unique name without ambiguity.

**Comment by wshwsh12** [comment]
> Actually I prefer Arrow than the Chunk, because there are too many places using chunk to refer another thing.. while Arrow is a very unique name without ambiguity.

Arrow(in fact, it it chunk) will be confused with Apache Arrow.  Chunk is not exactly the same as Apache Arrow.   In TiDB,  Chunk is just for one thing - data storage structure.  @breeswish

**Comment by wshwsh12** [comment]
> Mostly LGTM. But I worry now we don't have any definition of the `chunk` format. People may be confused when seeing "chunk format". Can we comment about it?

Or should I add the comment back? 
```
/// `Chunk` stores multiple rows of data in Apache Arrow format.	
/// See https://arrow.apache.org/docs/memory_layout.html
```
Now we only have one place that describes `chunk` in the blog https://pingcap.com/blog-cn/tidb-source-code-reading-10/  and it only have Chinese version.

**Comment by breeswish** [comment]
@wshwsh12 However as you said it is actually not the Arrow format, so this kind of comment is also confusing.. I think we don't have good way to describe this format for now, because the specification is missing.

**Comment by wshwsh12** [comment]
I think we can merge this pr now.

**Comment by sticnarf** [comment]
> I think we can merge this pr now.

OK.
/merge

**Pull request merged**
