### PR TITLE
*: register services outside of server

### PR DESCRIPTION
**Pull request by overvenus**
# What have you changed? (mandatory)

Pull registering services outside of `Server::new`. Passing services to `Server::new` is no longer required, it would be easy for us to register more services in the future.

## What are the type of changes? (mandatory)

- Engineering (engineering change which doesn't change any feature or fix any issue)

## How has this PR been tested? (mandatory)

Unit tests.

## Does this PR affect documentation (docs) or release note? (mandatory)

No.

## Does this PR affect `tidb-ansible` update? (mandatory)

No.

### CODE REVIEW

**Comment by siddontang** [comment]
amazing, so cool

How about the compiling time now?

**Comment by overvenus** [comment]
> How about the compiling time now?

It should be the same because it does not touch dependency.

**Pull request merged**
