### PR TITLE
refactoring of server/service/kv.rs

### PR DESCRIPTION
**Pull request by nrc**
###  What have you changed?

This PR moves some code out of kv.rs and into storage (the reasoning is that all the storage logic should be in storage and the kv service should be a dumb layer for handling grpc and network stuff.

The second commit splits out parts of kv.rs that deal with batching into their own submodule. I feel kv is too big and does too much, and the batching parts of it seem pretty self-contained.

###  What is the type of the changes?

- Engineering (engineering change which doesn't change any feature or fix any issue)

PTAL @youjiali1995 @sticnarf

### CODE REVIEW

**Comment by breeswish** [comment]
@nrc Your PR does not pass clippy checks.

**Comment by nrc** [comment]
> Your PR does not pass clippy checks.

Whoops! I'm too used to false negatives 🤣

**Pull request merged**
