### PR TITLE
*: replace `failure` and `quick-error` with `anyhow` and `thiserror`

### PR DESCRIPTION
**Pull request by koushiro**
### What problem does this PR solve?

Problem Summary: 

To be honest, this is a boring PR, but I think it's worth it.

The crate `failure` has been deprecated.

And I think the syntax of `quick-error` is not as intuitive as `thiserror`.

In addition, we can unify the usage of error handling.

### What is changed and how it works?

What's Changed:

* replace `failure` with `anyhow` and `thiserror`
* replace `quick-error` with `thiserror`

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

Side effects

- No

### Release note 

No

### CODE REVIEW

**Comment by BusyJay** [comment]
This is still under discussion, see tikv/rfcs#38. Perhaps you can send a proposal or issue before working on a lot of changes next time, so that we can know if it's on correct direction or it is already WIP.

**Comment by koushiro** [comment]
I've read the discussion in this RFC before, and I agree with using the `thiserror` library instead of the `failure` and `quick-error`, but the RFC isn't going very far at the moment.

I think we can try to take the first step of removing `failure` and `quick-error`, and then discuss whether to use a customised or future version of `thiserror` (or something else) in the code.

**Comment by BusyJay** [comment]
The purpose of RPC is to reaching a consensus about how things should be done instead of relying on individual's preference. I don't think we are even reaching agreement on removing `failure` and `quick-error`.

**Comment by andylokandy** [comment]
Recommend to convert to a draft PR since it seems not going to be merged soon.

**Comment by nrc** [comment]
I commented on the RFC thread, but I think it would be great if we could rebase and land this PR - I think whatever we eventually do with error handling, moving to thiserror/anyhow is a good first step. (And apologies for the delay in getting to this, I've been too busy with other stuff :-( )

**Comment by nrc** [comment]
I think it will be easier to land this if we make multiple smaller PRs doing a crate or a few crates at a time (less to rebase, quicker to review) rather than one large one.

**Comment by koushiro** [comment]
> I think it will be easier to land this if we make multiple smaller PRs doing a crate or a few crates at a time (less to rebase, quicker to review) rather than one large one.

If others have no objection to this step, I will divide this PR into smaller PRs later.

**Comment by nrc** [comment]
> If others have no objection to this step, I will divide this PR into smaller PRs later.

Thank you!

**Pull request closed without merging**
