### PR TITLE
copr: support rest greatest/least functions

### PR DESCRIPTION
**Pull request by Yisaer**
Signed-off-by: yisaer <disxiaofei@163.com>

### What is changed and how it works?

Issue Number: Ref https://github.com/tikv/tikv/issues/5751

What's Changed:

Support rest greatest/least functions in order to let tidb push `greatest` and `least` functions down into TiKV

```commit-message
```

### Check List 

Tests 

- Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by skyzh — APPROVED** [review]
LGTM for the implementation. How is this function look like in SQL? Can we apply some techniques in `IN` expression for such functions? e.g., if there are constant cells, we can first calculate their greatest value and store them in query context; and for other columns, we can directly compare them with the greatest among the constants.

**Review by longfangsong — APPROVED** [review]

**Comment by Yisaer** [comment]
> LGTM for the implementation. How is this function look like in SQL? Can we apply some techniques in `IN` expression for such functions? e.g., if there are constant cells, we can first calculate their greatest value and store them in query context; and for other columns, we can directly compare them with the greatest among the constants.

I think your suggestion can be applied later to revise such functions.

**Pull request merged**
