### PR TITLE
copr: fix index out of range in analyze column

### PR DESCRIPTION
**Pull request by iosmanthus**
Signed-off-by: iosmanthus <myosmanthustree@gmail.com>

### What problem does this PR solve?

This pull request fixes a bug that `Analyze` encounter a single-primary-column table will panic because indexes out of range. We try to reserve all the table and shrink it only while the first column contains a `pk_handle` and only shrink once.

Problem Summary:

### What is changed and how it works?
This pull request fixes a wrong index range while encountering a primary column as the first column in the table.

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

* Fix index out of range in analyze column

### CODE REVIEW

**Comment by zhongzc** [comment]
I wonder why following passed before:
https://github.com/tikv/tikv/blob/d3b92dac4156e5e2b37a404d1fdc1e8df3007249/tests/integrations/coprocessor/test_analyze.rs#L129-L134

**Comment by breeswish** [comment]
Please give a description for your change, what is changed and why it works.

**Comment by iosmanthus** [comment]
@breeswish Done. PTAL

**Pull request merged**
