### PR TITLE
added crc64 and origin region boundary for log backup

### LINKED ISSUE #17406: Add CRC64 for logs generated by log backup.
For better compacting logs, we need some extra information in the log files:
- `CRC64XOR` of each KVs. This can help us verify the result of compaction is integrity.
- Original boundary of the region, along with the epoch of region. This can guide us to do presplit during restoring.

### PR DESCRIPTION
**Pull request by YuJuncen**
### What is changed and how it works?

Issue Number: Close #17406

What's Changed:

```commit-message
- Added crc64 / origin region boundary for flushing.
- Flush now accepts a single structure `FlushContext`, where includes all observed regions' metadata.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
Here is an example of a newly generated metadata:
```console
> protoc -I$HOME/developer/kvproto/include -I$HOME/developer/kvproto/proto --decode backup.Metadata brpb.proto < ./simple.meta
store_id: 4
resolved_ts: 451996324658413570
max_ts: 451996327004602381
min_ts: 451996295547322380
file_groups {
  path: "v1/20240821/08/4/451996295547322380-84b0a3fe-30a2-4a09-8d22-ff0b4203290c.log"
  data_files_info {
    sha256: "\302\366;7\373fMUYd\270A\262`\272\376Z\214\322\014\2206\023{\314\325\3212\2503\234\356"
    number_of_entries: 3
    min_ts: 451996295547322380
    max_ts: 451996327004602381
    resolved_ts: 451996324658413570
    region_id: 8066
    start_key: "t\200\000\000\000\000\000\000\377\022_r\200\000\000\000\000\377\000u3\000\000\000\000\000\372\371\272/\274A\033\377\362"
    end_key: "t\200\000\000\000\000\000\000\377\022_r\200\000\000\000\000\377\000u3\000\000\000\000\000\372\371\272/\303\224\033\377\363"
    cf: "write"
    type: Put
    table_id: 18
    length: 477
    min_begin_ts_in_default_cf: 451996295547322379
    range_length: 202
    compression_type: ZSTD
    crc64xor: 14080795933730650363
<<<<<<------ NEW ------>>>>>>
    region_start_key: "r\000\000\001\000\000\000\000\373" 
    region_end_key: "t\200\000\000\000\000\000\000\377j_r\373\000\000\000\000\373"
    region_epoch {
      conf_ver: 11
      version: 230
    } 
<<<<<<------ NEW ------>>>>>>
  }
  min_ts: 451996295547322380
  max_ts: 451996327004602381
  min_resolved_ts: 451996324658413570
  length: 202
}
meta_version: V2
```
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Added more information to the backup data. This allows us improve the safety and speed of PiTR in the future.
```

### CODE REVIEW

**Review by Leavrth — APPROVED** [review]

**Review by 3pointer — APPROVED** [review]
LGTM

**Comment by YuJuncen** [comment]
/test
`cases::test_replica_stale_read::test_update_apply_index_before_sync_read_state`

**Review by overvenus — APPROVED** [review]

**Pull request merged**
