### PR TITLE
Add more tests to engine_traits_tests

### PR DESCRIPTION
**Pull request by brson**
### What problem does this PR solve?

Part of https://github.com/tikv/tikv/issues/6402

Adding a test suite for future engine implementors.

### What is changed and how it works?

What's Changed:

Various new engine test cases, including commits from these two old prs:

- https://github.com/tikv/tikv/pull/9848
- https://github.com/tikv/tikv/pull/10058

This also adds two new dynamic checks to engine_rocks sst iterator to panic instead of hard crash.

I am developing these tests in conjunction with a simple alternative storage engine (engine_simple) that is designed just to prove it's possible to implement engine_traits. That engine currently passes engine_traits_tests plus 110/138 raftstore test cases.

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by brson** [comment]
I can't reach ci.pingcap.net to see the errors.

**Comment by kennytm** [comment]
```
[2021-07-06T20:02:39.575Z] error: `ref` on an entire `let` pattern is discouraged, take a reference with `&` instead
[2021-07-06T20:02:39.575Z]   --> components/engine_traits_tests/src/sst.rs:18:9
[2021-07-06T20:02:39.575Z]    |
[2021-07-06T20:02:39.575Z] 18 |     let ref sst_path = tempdir
[2021-07-06T20:02:39.575Z]    |         ^^^^^^^^^^^^
[2021-07-06T20:02:39.575Z]    |
```

**Comment by brson** [comment]
Clippy errors are fixed.

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by brson** [comment]
@kennytm can you look at this?

**Review by kennytm — APPROVED** [review]

**Pull request merged**
