### PR TITLE
resolved_ts: remove hash set to save memory

### LINKED ISSUE #15553: Remove hash set in resolved_ts::Resolver
## Development Task

The Resolver uses a hash set to keep track of locks associated with
the same timestamp. When the length of the hash set reaches zero,
it indicates that the transaction has been fully committed. To save
memory, we can replace the hash set with an integer.

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close #15553

What's Changed:

```commit-message
The Resolver uses a hash set to keep track of locks associated with
the same timestamp. When the length of the hash set reaches zero,
it indicates that the transaction has been fully committed. To save
memory, we can replace the hash set with an integer.
```

### Check List 

Tests 

- Unit test
- Integration test

```bash
sysbench --db-driver=mysql --mysql-host=<HOST> --mysql-port=<PORT> --mysql-user=root \
        --mysql-db=test --tables=2 --table-size=100000000 --create_secondary=false \
        ./oltp_update_index prepare

-- warm up cache and others.
update sbtest1 set c='a';

-- sbtest2 leak.
update sbtest2 set c='b';
```

Left master branch, righ this PR.
image

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by YuJuncen — APPROVED** [review]
rest LGTM

**Review by tonyxuqqi — APPROVED** [review]

**Pull request merged**
