### PR TITLE
metrics: fix memory metrics

### LINKED ISSUE #11662: Memory usage metrics of TiKV shows the memory information of other components
### What version of TiKV are you using?

v5.3.0

### What operating system and CPU are you using?

CentOS 7, CPU?

### Steps to reproduce

Deploy TiDB and TiKV on the same server.

### What did you expect?
Only memory usage of TiKV should be shown.
截屏2021-12-14 下午8 07 44

### What did happened?
All the components memory info.
截屏2021-12-14 下午8 04 19

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

### What is changed and how it works?

Close #11662 

What's Changed:
TiKV dashboard on Grafana gets all memory usage jobs from Prometheus, which makes user confused.
image, fix it.
image

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by youjiali1995 — APPROVED** [review]
Need to create an issue and add "close #xxx" to the commit message.

**Comment by jackysp** [comment]
> Need to create an issue and add "close #xxx" to the commit message.

Done, but it's so weird to ask to add it to the commit message.

**Comment by youjiali1995** [comment]
> 

TiDB has the same rule but it can modify commit message automatically https://github.com/pingcap/community/pull/606, maybe TiKV can apply it too later.

**Review by rleungx — APPROVED** [review]

**Pull request merged**
