### PR TITLE
[compile] fix part of compile warnings #8336

### LINKED ISSUE #8336: Fix Clippy warnings
`make clippy` results in one Clippy warning (not sure how this made it past CI) in components/tidb_query_codegen, which seems easy to fix. 

When running `make clippy` we disable a lot of warnings, when running `cargo clippy` we get the default set of lints and we see a lot of Clippy warnings. Some of those really should be ignored, but some could be easily fixed. You can see even more things that could be fixed with `-Wrust-2018-idioms` (cc #4301)

It would be great to fix a bunch of those, and perhaps re-enable the lints if appropriate.

If you have any questions about whether a warning should be fixed or not, please ask me here or in Slack.

### PR DESCRIPTION
**Pull request by haojinming**
What problem does this PR solve?
Issue Number: close #8336

### Problem Description:
There are several compile warning when build with "cargo clippy".
This PR fix part of them.

### Check List for Tests
This PR has been tested by at least one of the following methods:
Manual test (add detailed scripts or steps below)

### CODE REVIEW

**Comment by pingyu** [comment]
@haojinming 
Are all similar cases fixed ? If so, we can enable `field_reassign_with_default` of clippy.

Please fix DCO by signing off. See [here](https://github.com/tikv/tikv/pull/11843/checks?check_run_id=4773424484).

Please update release note in PR description. You can set it to "None".

Rest LGTM.

**Comment by iosmanthus** [comment]
What about the results of `make clippy` @haojinming

**Comment by haojinming** [comment]
@iosmanthus  Actually we disable this kind of warning when executing "make clippy". This issue is complaining the warning whe exexuting "cargo clippy".

**Comment by haojinming** [comment]
@pingyu sorry for missing this for much time. I will check the clippy issue and continue again.

**Pull request closed without merging**
