### PR TITLE
compaction: disable periodic-compaction and ttl as default.

### LINKED ISSUE #15355: [Compaction] Disable `periodic compaction` as default.
## Development Task
As discussed offline, we've found that upgrading to `6.5` from `6.5` and previous version will introduce extra bunch of I/Os on compaction, triggered by [periodic compaction](https://github.com/facebook/rocksdb/wiki/Leveled-Compaction#periodic-compaction). And this compaction might last a long time, which will hurt the performance of `Write` and `Read`.
So, we wanna to disable it as default unless users who really need it.

### PR DESCRIPTION
**Pull request by LykxSassinator**
### What is changed and how it works?

Issue Number: Close #15355 

What's Changed:

```commit-message
Disable `periodic-compaction` and `ttl` features as default.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
Disable `periodic-compaction` and `ttl` features as default.
```

### CODE REVIEW

**Comment by LykxSassinator** [comment]
/cc @tonyxuqqi @tabokie 
PTAL, thx.

**Review by tonyxuqqi — APPROVED** [review]

**Review by tabokie — APPROVED** [review]

**Pull request merged**
