### PR TITLE
Check lock before check commit_ts in prewrite

### PR DESCRIPTION
**Pull request by sticnarf**
Signed-off-by: Yilin Chen <sticnarf@gmail.com>

## What have you changed? (mandatory)

Now we check commit_ts first and then check if there is a lock, following the percolator paper. However, if there is a lock, it has no value to check the commit_ts.

In this PR, I want to check the lock of the key first, then we don't have this problem. The cost is that if  
there is no lock and there is a newer version, we check the lock one more time than before.

<del>I think the new way is better because the write CF contains almost all keys of multi-version while the lock CF contains only a small part of keys without MVCC. Then, it is much faster to query the lock CF than query the write CF for commit_ts. </del> (https://github.com/tikv/tikv/pull/5247#issuecomment-521135344)

## What are the type of changes? (mandatory)

- Improvement (a change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)

`make dev`

## Does this PR affect documentation (docs) or release note? (mandatory)

No

## Does this PR affect `tidb-ansible` update? (mandatory)

No

### CODE REVIEW

**Comment by siddontang** [comment]
thanks @sticnarf 

do you have some benchmark results?

**Comment by sticnarf** [comment]
@siddontang I haven't found an appropriate way to benchmark this. Built-in workloads in sysbench have few write conflicts. I think I should create a customized workload to simulate a scenario with many write conflicts.

By the way, I cannot get a release binary using `/release` now. Who should I report the problem to?

**Comment by youjiali1995** [comment]
I think you can use `sysbench.oltp_write_only` with small tables to benchmark it. 

If a prewrite request meets locks, TiDB will resolve locks and retry to prewrite every key even if some of them has been locked. So I prefer to check lock first even if there is no obvious improvement.

**Comment by siddontang** [comment]
@sticnarf 

you can use sysbench with zipfian rand type. 

Btw, for release problem, you can ask @zhouqiang-cl for help.

**Comment by sticnarf** [comment]
@siddontang Even with zipfian distribution, there is no significant QPS/latency difference according to sysbench. I think the cause is that when write conflicts happen, the write cf record is just written and thus in the memtable. Then, it is actually also very fast to query the most recent write record.
/cc @youjiali1995

**Comment by breeswish** [comment]
You may write micro benchmarks?

**Comment by sticnarf** [comment]
> You may write micro benchmarks?

Any guidance? I think if there is much difference it must be a strict condition and I cannot think of one now. However, it is more reasonable to check lock first to me.

**Comment by breeswish** [comment]
I think you can write benchmarks specifically to verify this case: "I think the new way is better because the write CF contains almost all keys of multi-version while the lock CF contains only a small part of keys without MVCC. Then, it is much faster to query the lock CF than query the write CF for commit_ts". Although this scenario may be rare to happen, notable improvements in this scenario look to be still useful.

**Comment by sticnarf** [comment]
> I think you can write benchmarks specifically to verify this case: "I think the new way is better because the write CF contains almost all keys of multi-version while the lock CF contains only a small part of keys without MVCC. Then, it is much faster to query the lock CF than query the write CF for commit_ts". Although this scenario may be rare to happen, notable improvements in this scenario look to be still useful.

I don't think it's true any more. I commented before https://github.com/tikv/tikv/pull/5247#issuecomment-521135344: "when write conflicts happen, the write cf record is just written and thus in the memtable. Then, it is actually also very fast to query the most recent write record."

In fact, I'm now neutral on this change. If @youjiali1995 doesn't have strong opinion, I think we can close this PR.

**Pull request closed without merging**
