### PR TITLE
Revert "*: deny unknown fields when deserializing config TOML (#5190)"

### PR DESCRIPTION
**Pull request by kennytm**
###  What have you changed?

This reverts commit 034379605e8805c2ce2016903e21e3bd0521f64e (PR #5190).

###  What is the type of the changes?

Pick one of the following and delete the others:

- Bugfix (a change which fixes an issue)

###  How is the PR tested?

n/a

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

None

###  Does this PR affect `tidb-ansible`?

None

###  Refer to a related PR or issue link (optional)

#5286

### CODE REVIEW

**Comment by zhouqiang-cl** [comment]
did this need to be cherry-pick to release-3.0?

**Comment by breeswish** [comment]
@zhouqiang-cl No, reverted commits are not cherry picked previously.

**Pull request merged**
