### PR TITLE
tidb_query_codegen: add max_args

### PR DESCRIPTION
**Pull request by hawkingrei**
###  What have you changed?

Add max_args for rpn_fn

###  What is the type of the changes?

Pick one of the following and delete the others:

- Improvement

###  How is the PR tested?

- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No

###  Does this PR affect `tidb-ansible`?

No

### CODE REVIEW

**Comment by TennyZhuang** [comment]
Can you add some comment about the usage of `max_args` in the header comment of `components/tidb_query_codegen/src/rpn_function.rs`?

**Comment by hawkingrei** [comment]
> Can you add some comment about the usage of `max_args` in the header comment of `components/tidb_query_codegen/src/rpn_function.rs`?

Thank you. Have added comment.

**Comment by hawkingrei** [comment]
PTAL @breeswish

**Comment by TennyZhuang** [comment]
LGTM

/approve

**Comment by hawkingrei** [comment]
@breeswish Please merge against.

**Pull request merged**
