### PR TITLE
config:consider config change in readstats

### PR DESCRIPTION
**Pull request by JayiceZ**
close https://github.com/tikv/tikv/issues/12014
Signed-off-by: Jayice <1185430411@qq.com>

### What is changed and how it works?

Issue Number: Close https://github.com/tikv/tikv/issues/12014

What's Changed:

```
add a static var `SPLIT_CONFIG`, in order to take into account the config change in the creation of `Readstats`
```

Tests 

- Unit test

### Release note 

```release-note
take into account the config change in the creation of `Readstats`
```

### CODE REVIEW

**Review by JmPotato — APPROVED** [review]
LGTM. Could you please help review this PR also? @lhy1024 @AndreMouche

**Review by lhy1024 — APPROVED** [review]

**Comment by JayiceZ** [comment]
@andylokandy Hi. Could you PTAL if you have time？😃

**Comment by JayiceZ** [comment]
Oh, is there anyone who can help review?

**Review by AndreMouche — APPROVED** [review]
LGTM

**Comment by JayiceZ** [comment]
Oh, it seems like some conflicts occurred...I will try to fix it.

**Comment by JayiceZ** [comment]
@AndreMouche Hi, I've sent a new commit to fix conflicts. PTAL again😆

**Pull request merged**
