### PR TITLE
tikv: set panic=abort for dev and release

### PR DESCRIPTION
**Pull request by brson**
## What have you changed? (mandatory)

Abort on panic in both dev and release profiles.

The panic hook already exits unconditionally, so all the unwinding
code is dead. This saves some build time and code size.

## What are the type of the changes? (mandatory)

- Engineering (engineering change which doesn't change any feature or fix any issue)

## How has this PR been tested? (mandatory)

Manual.

## Does this PR affect documentation (docs) or release note? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No

## Refer to a related PR or issue link (optional)

Fixes https://github.com/tikv/tikv/issues/4638

## Benchmark result if necessary (optional)

Measurements from February:

before:

```
real    25m13.237s
user    58m28.394s
sys     2m1.420s
```

tikv-server size: 311513464 bytes

after:

```
real    24m23.134s
user    57m37.594s
sys     2m2.737s
```

tikv-server size: 306505344 bytes

### CODE REVIEW

**Comment by kennytm** [comment]
But our current panic hook also [writes a critical log](https://github.com/tikv/tikv/blob/21a15b3294351d0750b2be71d8ae0c14a69efe6b/components/tikv_util/src/lib.rs#L499-L503) before exit(1)/abort().

**Comment by siddontang** [comment]
is it still necessary to advance #4309 ?

**Comment by BusyJay** [comment]
There are several cases in TiKV use `catch_unwind` to test those cases that are expected to panic.

**Comment by siddontang** [comment]
@brson 
Maybe we should only allow core in development mode?

**Comment by brson** [comment]
> But our current panic hook also [writes a critical log](https://github.com/tikv/tikv/blob/21a15b3294351d0750b2be71d8ae0c14a69efe6b/components/tikv_util/src/lib.rs#L499-L503) before exit(1)/abort().

The hook is still triggered prior to the abort. The runtime-invoked abort never actually happens - the panic hook does it.

**Comment by brson** [comment]
> There are several cases in TiKV use `catch_unwind` to test those cases that are expected to panic.

@BusyJay From everything I see I do not believe this is true outside of test cases, which are forced to use unwinding by cargo, and is unchanged here.

To demonstrate I have pushed another commit that moves the only explicit `catch_unwind` call (from a test case) into the `panic_hook` crate, made `panic_hook` a dev-dependency only so it cannot be called from production code.

There may be code out of tree that catches panics, e.g, async engine's typically catch (and swallow), but it is irrelevant because the sole panic hook installed by TiKV (outside of test cases) unconditionally exits, and the only mechanism in tree that I see to stop that is in the `panic_hook` dev-dependency.

It is curious that there are test cases that are expected to panic when a panic in TiKV explicitly exits the process.

>  Maybe we should only allow core in development mode?

I'm not sure what you mean by this. But since (I believe) a panic in TiKV is always a fatal error, producing a core dump seems prudent. At the moment the panic hook calls `exit(1)`, which won't core dump.

**Comment by BusyJay** [comment]
>  ...I do not believe this is true outside of test cases...

Yes. Only test cases need to do it.

> ..forced to use panic=unwind by cargo, and is unchanged here.

Do you mean that even panic=abort is set for dev profile, cargo will still panic=unwind for test?

Another problem I worry about is coredump may not be expected in production (release profile). Generally TiKV will consume a lot of memory, coredump will generate a lot of large files. And ansible seems to restart TiKV unconditionally, if it keeps coredumping, disk space can easily run out.

**Comment by siddontang** [comment]
@BusyJay 

for coredump size, I think we will use minidump to solve this problem. 

I think even we set core here, if we don't enable core in Linux, the core file can still not be generated, but the panic stack must be recorded in the log, if we can guarantee this, I am fine for this PR. @brson

**Comment by BusyJay** [comment]
> for coredump size, I think we will use minidump to solve this problem.

Why not wait till minidump is introduced?

**Comment by brson** [comment]
> Do you mean that even panic=abort is set for dev profile, cargo will still panic=unwind for test?

Yes. `test` and `bench` are their own profiles and do not accept the `panic` key. Unwinding is required for the test harness to work.

> Another problem I worry about is coredump may not be expected in production (release profile). Generally TiKV will consume a lot of memory, coredump will generate a lot of large files. And ansible seems to restart TiKV unconditionally, if it keeps coredumping, disk space can easily run out.

Acknowledged. As far as I can tell though this PR doesn't change any panic behavior at all because the panic_hook is already executing `process::exit`, and continues to do so after this PR (the "abort" implied by "panic=abort" is unreachable because of the custom panic hook). The only observable effects of this PR _should_ be reduced compile time and reduced binary size.

**Comment by brson** [comment]
> is it still necessary to advance #4309 ?

No, but my preference is yes, as a matter of correctness.

**Comment by brson** [comment]
My change to the `speed_limiter` test did not work as expected and is failing CI. I'll investigate later.

**Comment by brson** [comment]
After 10 minutes of investigation it is not obvious to me why the panic_hook library doesn't supress the backtrace in test_panic_not_aborting, so I just reverted that change so the test works again. I'll fill an issue to do the conversion later.

PTAL @nrc @BusyJay

**Pull request merged**
