### PR TITLE
Upgrade criterion to 0.3

### PR DESCRIPTION
**Pull request by YangKeao**
#  What have you changed?

Please explain in detail what the changes are in this PR and why they are needed:

- Upgrade criterion to 0.3
- Use custom measurement to get CPU time
- Upgrade version of several dependencies: `crossbeam` and `clap`. (Old version of them will meet unresolvable conflict )

###  What is the type of the changes?

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?

A relative benchmark is still running. We can check stability of the result after several days.

###  Note:

These files should be reviewed carefully:

- benches/coprocessor_executors/util/mod.rs
- Cargo.toml (maybe the performance of newer version of `crossbeam` should be checked)
- [criterion-cpu-time](https://github.com/YangKeao/criterion-cpu-time ) is this measurement suitable?

### CODE REVIEW

**Comment by siddontang** [comment]
> Use custom measurement to get CPU time

why using a customized one? does criterion not provide this?

**Comment by YangKeao** [comment]
@siddontang Now criterion only provides Wall Time measurement. But it provides us the ability to customize measurement.

[This feature (custom measurements)](https://bheisler.github.io/criterion.rs/book/user_guide/custom_measurements.html) is just added in criterion 0.3 which is published last week.

**Comment by YangKeao** [comment]
Sorry for such a long commit history. I just rebased for sign-off :cry: .

**Comment by YangKeao** [comment]
I will open up another PR to remove these ugly unbearable commit history.

**Pull request closed without merging**
