### PR TITLE
fix typo

### LINKED ISSUE #13706: Typos in `src/read_pool.rs`.
Typos in `src/read_pool.rs`, it should be `threshold` instead of `threahold `.

### PR DESCRIPTION
**Pull request by goldwind-ting**
Signed-off-by: goldwind-ting

### What is changed and how it works?

Issue Number: Close #13706

What's Changed:
replace `threahold` with `threshold `.

```commit-message
fix-typo: replace `threahold` with `threshold `.
```

### Related changes
- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by youjiali1995 — APPROVED** [review]

**Review by sticnarf — APPROVED** [review]

**Comment by sticnarf** [comment]
Can you please create an issue and link it in the PR description?

**Comment by goldwind-ting** [comment]
> Can you please create an issue and link it in the PR description?

Sure!

**Comment by goldwind-ting** [comment]
> Can you please create an issue and link it in the PR description?

created, please check.

**Comment by sticnarf** [comment]
@goldwind-ting Thanks!

**Pull request merged**
