### PR TITLE
metrics: add grafana panels for RawKV causal timestamp

### PR DESCRIPTION
**Pull request by pingyu**
Issue Number: #11965

Signed-off-by: pingyu <yuping@pingcap.com>

### What is changed and how it works?

Issue Number: ref #11965

What's Changed:

```commit-message
Add Grafana panels for RawKV causal timestamp.
```

Metrics is added by PR: https://github.com/tikv/tikv/pull/12099

Screenshot of Grafana
image

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
No.
- Need to cherry-pick to the release branch
No.
### Check List 

Tests 

- No code

Side effects
- No.

### Release note 

```release-note
Add Grafana panels for RawKV causal timestamp.
```

### CODE REVIEW

**Review by Connor1996 — COMMENTED** [review]
Please paste the screenshot of the grafana board

**Comment by pingyu** [comment]
> Please paste the screenshot of the grafana board

Added to PR description. PTAL~

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by iosmanthus — APPROVED** [review]
LGTM

**Pull request merged**
