### PR TITLE
cdc: Use compare_exchange_weak and fix incorrect configuration check msg

### PR DESCRIPTION
**Pull request by hi-rustin**
Signed-off-by: hi-rustin <rustin.liu@gmail.com>

### What problem does this PR solve?
None

Problem Summary:

### What is changed and how it works?

What's Changed:

1. Since we are already using spin, we can use compare_exchange_weak.
2. Fix wrong check message

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

None

Side effects

None

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]
LGTM

**Comment by hi-rustin** [comment]
/cc @liuzix 

Could you please take a look?

**Review by lonng — APPROVED** [review]

**Pull request merged**
