### PR TITLE
coprocessor/dag/expr: add builtin round_dec

### PR DESCRIPTION
**Pull request by colinback**
What have you changed? (mandatory)

Please explain IN DETAIL what the changes are in this PR and why they are needed:

    add round_dec function

What are the type of the changes? (mandatory)

The currently defined types are listed below, please pick one of the types for this PR by removing the others:

    New feature (non-breaking change which adds functionality)

How has this PR been tested? (mandatory)

    unit test
Does this PR affect documentation (docs/docs-cn) update? (mandatory)

    no
Does this PR affect tidb-ansible update? (mandatory)

    no
Refer to a related PR or issue link (optional)

    https://github.com/tikv/tikv/issues/3275

Benchmark result if necessary (optional)
Add a few positive/negative examples (optional)

### CODE REVIEW

**Comment by colinback** [comment]
@AndreMouche @hicqu I'm sorry when I try to fix conflict with recent commits, I accidentally delete the branch and PR #3418 is closed. So I open another one which run through all tests.

**Comment by colinback** [comment]
@AndreMouche Excuse me, why FLAG_IGNORE_TRUNCATE error mean this time? I remember all test passed last night and 'make test' still passes on my desktop.

**Comment by AndreMouche** [comment]
Here `IGNORE_TRUNCATED` makes no sense in `round_dec`, while it's useful in strToDec in the test.

**Comment by colinback** [comment]
@AndreMouche Then what should I do now? Shall we rerun a test?

**Comment by hicqu** [comment]
LGTM.

**Comment by huachaohuang** [comment]
@solotzg PTAL

**Comment by solotzg** [comment]
The branch's version under this PR is too old. Can you implement under current master's version and support more functions just like Floor*** did? 
I appreciate it.

**Comment by Connor1996** [comment]
Please fix CI

**Comment by colinback** [comment]
@solotzg @Connor1996 I can implement under current master's version and maybe I support all ROUNDxxx in this commit. In fact this PR delay because when I finished it about one month ago, I can not pass ci test. However `make test` runs clean on my laptop and I don't know why. I asked the question in this ticket but no one answered. Then I'm busy at work and had time to take another look today.

Anyway let me implement ROUNDxxx this week and check.

**Comment by huachaohuang** [comment]
@colinback Thanks, sorry for the unresponsive.

**Comment by huachaohuang** [comment]
Close this in favor of #3621

**Pull request closed without merging**
