### PR TITLE
resolved_ts: more precise RTS_MIN_RESOLVED_TS_GAP

### PR DESCRIPTION
**Pull request by andylokandy**
### What problem does this PR solve?

Problem Summary:

The metric `RTS_MIN_RESOLVED_TS_GAP`'s precision is second.

### What is changed and how it works?

Make `RTS_MIN_RESOLVED_TS_GAP`s precision to millis.

image

### Check List 

Tests 

- Unit test
- Integration test
Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by iosmanthus — APPROVED** [review]
LGTM

**Review by iosmanthus — CHANGES_REQUESTED** [review]
We should update this metric in `https://github.com/tikv/tikv/blob/master/metrics/grafana/tikv_details.json`

**Comment by iosmanthus** [comment]
@andylokandy we may post the screenshot of the TiKV's Grafana page in the pull request description.

**Comment by andylokandy** [comment]
@iosmanthus PTAL

**Review by zhongzc — APPROVED** [review]

**Comment by iosmanthus** [comment]
@andylokandy Why are there so many diffs to `tikv-detail.json`, would you like to post how do you the step to produce this file?

**Review by iosmanthus — APPROVED** [review]

**Pull request merged**
