### PR TITLE
record grpc duration correctly

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve?

In the current implementation, "grpc request duration" only represents the time of handling the request, but the time of collecting responses in batch-channel is excluded.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hicqu** [comment]
图片

I have done a manual test. The result shows the metric "GRPC message duration" is not broken.

**Review by Little-Wallace — APPROVED** [review]
LGTM

**Review by hunterlxt — APPROVED** [review]
Roughly reviewed LGTM

**Pull request merged**
