### PR TITLE
*: move lock manager to server (#5381)

### PR DESCRIPTION
**Pull request by youjiali1995**
Cherry pick #5381 which is the prerequisite for https://github.com/tikv/tikv/pull/5518, https://github.com/tikv/tikv/pull/5680 and https://github.com/tikv/tikv/pull/5483.

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by coocood** [comment]
@sticnarf @MyonKeminta PTAL

**Comment by sticnarf** [comment]
Please fix the conflicts.

**Comment by youjiali1995** [comment]
@sticnarf PTAL.

**Pull request merged**
