### PR TITLE
apply: avoid unnecessary clone

### LINKED ISSUE #13726: Unnecessary clone in apply flow
## Development Task
image

### PR DESCRIPTION
**Pull request by Connor1996**
Signed-off-by: Connor1996 <zbk602423539@gmail.com>

### What is changed and how it works?

Issue Number: Close #13726 

What's Changed:

```commit-message
avoid unnecessary clone
```

### Check List 

Tests 

- No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tabokie — APPROVED** [review]

**Review by BusyJay — APPROVED** [review]
/cc @CalvinNeo

**Comment by Connor1996** [comment]
Can't get accurate performance differences from benchbot, it's not stable enough

**Pull request merged**
