### PR TITLE
rawkv: fix flaky integration test case `test_raw_put_key_guard`

### LINKED ISSUE #14141: rawkv: integration test case `test_raw_put_key_guard` is flaky
### What version of TiKV are you using?

master (https://github.com/tikv/tikv/commit/8484ececb571a28094f3d316fcb6b71f7b2ff12e)

### What operating system and CPU are you using?

N/A

### Steps to reproduce

Run CI in PR.

### What did you expect?

CI succeed.

### What did happened?

CI failed:
img_v2_8afad2c9-6838-406a-b653-1f986529271g

### PR DESCRIPTION
**Pull request by pingyu**
Signed-off-by: Ping Yu <yuping@pingcap.com>

### What is changed and how it works?

Issue Number: Close #14141 

What's Changed:

```commit-message
rawkv: fix flaky integration test case `test_raw_put_key_guard`.
```

The original `2s` seems to be not enough occasionally in the CI environment.
So I prolong this timeout to `5s` and retry every `200ms` to speed up in most cases.

### Related changes

- No.

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- No.

### Release note 

```release-note
rawkv: fix flaky integration test case `test_raw_put_key_guard`.
```

### CODE REVIEW

**Comment by pingyu** [comment]
> /cc @haojinming @zeminzhou

PTAL, thanks~

**Review by haojinming — APPROVED** [review]
LGTM

**Review by zeminzhou — APPROVED** [review]
LGTM～

**Review by iosmanthus — APPROVED** [review]

**Pull request merged**
