### PR TITLE
update titan to use individual thread pool

### PR DESCRIPTION
**Pull request by Connor1996**
###  What have you changed?
update titan to use individual thread pool for titan GC
https://github.com/tikv/rust-rocksdb/pull/423

###  What is the type of the changes?
- Bugfix (a change which fixes an issue)

###  How is the PR tested?
- Manual test (add detailed scripts or steps below)

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?
Yes

###  Does this PR affect `tidb-ansible`?
No

### Related issue
https://github.com/tikv/tikv/issues/6518

### CODE REVIEW

**Comment by siddontang** [comment]
how to set the number of this thread pool in config?

**Comment by yiwu-arbug** [comment]
> how to set the number of this thread pool in config?

via `max-background-gc`: https://github.com/tikv/tikv/blob/d3328f2e1092de444665bd3fe4563646984f618e/etc/config-template.toml#L466

**Comment by zhangjinpeng1987** [comment]
> > how to set the number of this thread pool in config?
> 
> via `max-background-gc`. Before this PR titan GC share thread pool with rocksdb compaction, which can make compaction thread pool size hard to properly set, and can cause write stall.
> 
> https://github.com/tikv/tikv/blob/d3328f2e1092de444665bd3fe4563646984f618e/etc/config-template.toml#L466

Is 1 enough by default?

**Comment by yiwu-arbug** [comment]
> > > how to set the number of this thread pool in config?
> > 
> > 
> > via `max-background-gc`. Before this PR titan GC share thread pool with rocksdb compaction, which can make compaction thread pool size hard to properly set, and can cause write stall.
> > https://github.com/tikv/tikv/blob/d3328f2e1092de444665bd3fe4563646984f618e/etc/config-template.toml#L466
> 
> Is 1 enough by default?

Good point. Will make the default larger.

**Comment by yiwu-arbug** [comment]
@AndreMouche Please merge this PR. Thanks.

**Comment by yiwu-arbug** [comment]
Closing in favor of #6553

**Pull request closed without merging**
