### PR TITLE
metrics: add Raft Engine panel

### PR DESCRIPTION
**Pull request by tabokie**
Signed-off-by: tabokie <xy.tao@outlook.com>

### What is changed and how it works?

What's Changed:

Add Grafana monitoring for raft engine. Not all panels in this PR will display properly unless raft-engine is updated in #10937, and prometheus is updated to 0.13. But I intend to merge it upfront, in case other people jumps ahead and scrambles the layout.

### Check List 

Tests
- No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by tabokie** [comment]
Screenshots:
{F2657ED9-1B75-400A-81D5-4371318DDF81}

{27596999-5740-4598-BCB4-CA5A397BB71D}

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by hunterlxt — APPROVED** [review]
LGTM

**Pull request merged**
