### PR TITLE
raftstore: fix TiKV delete files before ingesting

### PR DESCRIPTION
**Pull request by Little-Wallace**
Signed-off-by: Little-Wallace <bupt2013211450@gmail.com>

### What problem does this PR solve?

Issue Number: close https://github.com/tikv/tikv/issues/10438

Problem Summary:
See issue

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
Check switchmode before deleting files

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- None

### CODE REVIEW

**Review by gengliqi — APPROVED** [review]

**Review by glorv — APPROVED** [review]

**Comment by Little-Wallace** [comment]
See the problem explain in #10438

**Pull request merged**
