### PR TITLE
Cherry-pick `sst_importer: download SST from external storage + key rewrite (#5581)` to release-3.1

### PR DESCRIPTION
**Pull request by kennytm**
###  What have you changed?

Cherry-pick #5581 to release-3.1.

###  What is the type of the changes?

Pick one of the following and delete the others:

- New feature (a change which adds functionality)

###  How is the PR tested?

- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No?

###  Does this PR affect `tidb-ansible`?

No

###  Refer to a related PR or issue link (optional)

#5581

### CODE REVIEW

**Comment by zhouqiang-cl** [comment]
@kennytm you should ignore copr-test. it not mettar

**Comment by kennytm** [comment]
@zhouqiang-cl OK. Will it be fixed 😂

**Pull request merged**
