### PR TITLE
Fix panic when a NIC doesn't have a mac address

### PR DESCRIPTION
**Pull request by YKG**
**Note**: The followings are just a copy of https://github.com/tikv/tikv/pull/7889

Signed-off-by: Kaige Ye <yekaige2010@gmail.com>

### What problem does this PR solve?

Problem Summary:

`pnet_datalink::NetworkInterface::mac_address()` will panic if the NIC doesn't have a mac address. For example, a point-to-point link doesn't have mac address.

### What is changed and how it works?

What's Changed:

Return a string "none" when the `NIC.mac` is `None` 

### Check List

Tests

- Manual test

  * add a point-to-point interface (e.g. with `WireGuard` or `OpenVPN` or just `ip tunnel add`)
  * run `tiup playground`
  * visit http://localhost:2379/dashboard/#cluster-info/host
  * check tikv logs
      - without this patch, tikv panics
      - with this patch, no panic any more

### CODE REVIEW

**Comment by YKG** [comment]
@breeswish Do I need to add the Cargo.lock as well?

```diff
diff --git a/Cargo.lock b/Cargo.lock
index 3352ab8a9..0b73c219a 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -4432,6 +4432,7 @@ dependencies = [
  "parking_lot 0.10.0",
  "pd_client",
  "pin-project",
+ "pnet_datalink",
  "pprof",
  "procinfo",
  "prometheus",

```

**Comment by breeswish** [comment]
@YKG Yes, you need to submit `Cargo.lock` as well, otherwise lint check won't pass

**Pull request merged**
