### PR TITLE
txn_types: ignore unknown bytes when parsing Write/Lock

### PR DESCRIPTION
**Pull request by youjiali1995**
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### What problem does this PR solve?

Problem Summary:

To make downgrading easier, Ignore unknown bytes when parsing Write/Lock. https://github.com/tikv/sig-transaction/pull/93

### What is changed and how it works?

What's Changed:

Ignore unknown bytes when parsing Write/Lock.

### Check List 

Tests 

- Unit test

### Release note 
- No release note.

### CODE REVIEW

**Review by sticnarf — APPROVED** [review]
LGTM

**Review by nrc — APPROVED** [review]
lgtm

**Comment by youjiali1995** [comment]
@MyonKeminta Downgrading is a dangerous operation, we will provide detailed downgrading docs of each version for users and users should follow it. If some new fields can't be ignored, we need to provide solutions case by case and I don't think we can handle all cases now.

**Comment by youjiali1995** [comment]
BTW, we ignore unknown fields in this PR. Should we ignore unknown types too?
```rust
        let lock_type = LockType::from_u8(b.read_u8()?).ok_or(ErrorInner::BadFormatLock)?;
```
```rust
        let write_type_bytes = b
            .read_u8()
            .map_err(|_| Error::from(ErrorInner::BadFormatWrite))?;
```

**Pull request merged**
