### PR TITLE
server: compatibility with prost-codec

### LINKED ISSUE #11479: TiKV 5.0.5 cannot be compiled using prost-codec
https://github.com/tikv/tikv/blob/81b96ebfef322ee14fe4450f6437302fdee0e111/src/server/debug.rs#L675

LHS is an `i32` in prost-codec.

### PR DESCRIPTION
**Pull request by kennytm**
Signed-off-by: kennytm <kennytm@gmail.com>

### What problem does this PR solve?

Issue Number: close #11479

Problem Summary:

TiKV cannot be compiled in prost-codec.

### What is changed and how it works?

What's Changed:

Call a codec-independent method.

### Check List 

Tests 

- No code

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by iosmanthus — APPROVED** [review]
LGTM

**Review by andylokandy — APPROVED** [review]

**Comment by Mini256** [comment]
@kennytm Maybe you want to close the issue `#11479`, not the current PR `#11480`.

image

**Comment by kennytm** [comment]
@Mini256 Thanks + It's really hard to notice 😓

**Pull request closed without merging**
