### PR TITLE
cdc: fix cdc integration test ` test_rawkv_sacn`

### LINKED ISSUE #14146: cdc: integration test case test_rawkv_sacn is unstable
### Steps to reproduce

Run CI in PR.

### What did you expect?
CI succeed.

### What did happened?
CI
image

### PR DESCRIPTION
**Pull request by zeminzhou**
Signed-off-by: zeminzhou <zhouzemin@pingcap.com>

### What is changed and how it works?

Issue Number: Close #14146

What's Changed:

```commit-message
make cdc integration test `test_rawkv_sacn` stable
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

Side effects

NO

### Release note 

```release-note
make cdc integration test `test_rawkv_sacn` stable
```

### CODE REVIEW

**Review by haojinming — APPROVED** [review]
LGTM

**Comment by zeminzhou** [comment]
@pingyu This problem may be caused by the current thread executing too slowly. If after executing `suite.set_tso(10);`, the current thread is not advanced, but` causal_ts_provider` keeps advancing the tso of pd, causing the current tso of pd to exceed 1000. What do you think?

**Comment by pingyu** [comment]
> @pingyu This problem may be caused by the current thread executing too slowly. If after executing `suite.set_tso(10);`, the current thread is not advanced, but` causal_ts_provider` keeps advancing the tso of pd, causing the current tso of pd to exceed 1000. What do you think?

LGTM~

**Review by pingyu — APPROVED** [review]

**Pull request merged**
