### PR TITLE
*: update sysinfo version to fix undiscovered disk information (#8791)

### PR DESCRIPTION
**Pull request by ti-srebot**
Fix https://github.com/tikv/tikv/issues/9555

cherry-pick #8791 to release-4.0

---

Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What problem does this PR solve?

As title said.

Related issue: https://github.com/GuillaumeGomez/sysinfo/issues/295 
Related fix: https://github.com/GuillaumeGomez/sysinfo/pull/297

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

Side effects

- No

### Release note 
- No.

### CODE REVIEW

**Comment by gengliqi** [comment]
Ping. Should this PR be merged to v4.0.8?

**Comment by gengliqi** [comment]
@breeswish @crazycs520 @BusyJay PTAL

**Comment by crazycs520** [comment]
https://github.com/tikv/tikv/pull/7682 Need cherry-pick this first.

**Comment by breeswish** [comment]
Moved to v4.0.9

**Comment by BusyJay** [comment]
@crazycs520 #7682 was merged as #8939.

**Comment by breeswish** [comment]
@crazycs520 Dependent PR has been merged, could you resolve conflicts for this PR and let's get it merged?

**Comment by tabokie** [comment]
ping @crazycs520

**Comment by hi-rustin** [comment]
This cherry pick PR is for a release branch and has not yet been approved by release team.
Adding the do-not-merge/cherry-pick-not-approved label.

To merge this cherry pick, it must first be approved (/lgtm + /merge) by the collaborators.

AFTER it has been approved by collaborators, please ping the release team in a comment to request a cherry pick review

**Comment by sticnarf** [comment]
ping @crazycs520 
This PR can solve some issues reported by users like https://asktug.com/t/topic/68102/33

**Comment by breeswish** [comment]
@crazycs520 Please fix conflicts.

**Comment by sticnarf** [comment]
The sysinfo version of component/engine  should also be updated

**Comment by crazycs520** [comment]
@breeswish @sticnarf PTAL

**Review by breeswish — APPROVED** [review]

**Review by sticnarf — APPROVED** [review]
/LGTM

**Pull request merged**
