### PR TITLE
alertmanager: no GC cannot work alert if no compaction happens

### PR DESCRIPTION
**Pull request by sticnarf**
### What problem does this PR solve?

After TiDB 5.0, compaction filter is the default GC approach. If the cluster is idle thus no compaction is triggered, the GC compaction filter will not be triggered. Then, there will be a false "GC can not work" alert which is really annoying.

### What is changed and how it works?

This PR modifies the alertmanager rule of "GC can not work". It raises the alert only if there are compaction operations while no GC compaction filter runs.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

### Release note 

```release-note
Avoid false "GC can not work" alert under low write flow.
```

### CODE REVIEW

**Comment by MyonKeminta** [comment]
Is it that when compaction is performed on WRITE_CF, there must be some records in `tikv_gc_compaction_filter_perform` (if enabled)?

**Comment by sticnarf** [comment]
> Is it that when compaction is performed on WRITE_CF, there must be some records in `tikv_gc_compaction_filter_perform` (if enabled)?

It seems so, unless there is something wrong such as no safepoint is set or the database is stall.

**Review by MyonKeminta — APPROVED** [review]
🤔 LGTM

**Review by hicqu — APPROVED** [review]

**Pull request merged**
