### PR TITLE
Remove engine::rocks::util

### PR DESCRIPTION
**Pull request by brson**
### What problem does this PR solve?

Work toward deleting engine crate in favor of engine_traits

### What is changed and how it works?

This creates a few new abstractions for things in `engine::rocks::util`, and updates code to use them. Then it moves the remaining DB constructors to `engine_rocks::raw_util`. The contents of this module reflect a lower-level version of functions already defined in `engine_rocks::util`. These constructors are still used extensively across the codebase, particularly in tests, but will eventually disappear in favor of RocksEngine constructors. Then this module will be deleted entirely.

After this there are only a few more steps before the engine crate is deleted.

### Related changes

https://github.com/tikv/tikv/issues/6402

### Release note 

- No release note.

### CODE REVIEW

**Comment by Little-Wallace** [comment]
Why we rename util/mod.rs to raw_util.rs rather than util.rs?

**Comment by brson** [comment]
@Little-Wallace I named the new module `raw_util` because a `util` module already exists in `engine_rocks` and that module already contains higher-level versions of the same types and functions. It was a simpler refactoring operation to create a new module for these types that to put them into the existing `util` module.

Ultimately it will not matter the name of this module because it will not exist long-term.

**Comment by brson** [comment]
Fixed merge conflicts.

**Pull request merged**
