### PR TITLE
grafana: update backup & import CPU to Thread CPU panels.

### LINKED ISSUE #10003: backup, restore and cdc CPU graphs should also be included in "Thread CPU"
## Bug Report

backup, restore and cdc CPU graphs should also be included in "Thread CPU".

### What version of TiKV are you using?

4.0.11

### PR DESCRIPTION
**Pull request by 3pointer**
Signed-off-by: 3pointer <luancheng@pingcap.com>

### What problem does this PR solve?

Issue Number: close #10003 
Problem Summary: Fix the lack of backup & import CPU in `Thread CPU`.

### What is changed and how it works?

What's Changed:
copy backup & import CPU panels to Thread CPU.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 
- Manual test (add detailed scripts or steps below)
屏幕快照 2021-04-12 下午8 57 07

### Release note 

- No release note.

### CODE REVIEW

**Comment by overvenus** [comment]
Could you add CDC thread CPU usage too?

**Comment by 3pointer** [comment]
> Could you add CDC thread CPU usage too?

Sure，let me test it.

**Comment by 3pointer** [comment]
屏幕快照 2021-04-13 下午3 26 13
updated @overvenus

**Pull request merged**
