### PR TITLE
bump master version to 6.1-alpha

### PR DESCRIPTION
**Pull request by tonyxuqqi**
Signed-off-by: qi.xu <tonxuqi@outlook.com>

### What is changed and how it works?

Issue Number:ref  #11966

What's Changed:

```commit-message
bump version to 6.1-alpha
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by 5kbpers — APPROVED** [review]

**Comment by BusyJay** [comment]
Lock file is not updated.

**Review by overvenus — COMMENTED** [review]
Maybe you forget to update Cargo.lock?

**Comment by tonyxuqqi** [comment]
> 

Thanks,Updated.

**Comment by tonyxuqqi** [comment]
> Lock file is not updated.

done. Thanks.

**Review by BusyJay — APPROVED** [review]

**Pull request merged**
