### PR TITLE
Fix `CompactFiles` bug

### PR DESCRIPTION
**Pull request by DorianZheng**
Signed-off-by: DorianZheng <xingzhengde72@gmail.com>

## What have you changed? (mandatory)

Just Upgrade rocksdb version

## What are the type of the changes? (mandatory)

- Bug fix

## How has this PR been tested? (mandatory)

test case

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No

### CODE REVIEW

**Comment by huachaohuang** [comment]
/run-all-tests tidb=release-2.0 pd=release-2.0 tidb-test=release-2.0 tidb-private-test=release-2.0

**Comment by zhangjinpeng1987** [comment]
@overvenus Please take a look the failed test case `test_lease`.

**Comment by overvenus** [comment]
Cc #3044

**Comment by huachaohuang** [comment]
So I think the failed test has nothing to do with this PR, merge now.

**Pull request merged**
