### PR TITLE
Add priority to coprocessor metrics

### PR DESCRIPTION
**Pull request by sunxiaoguang**
Signed-off-by: Xiaoguang Sun <sunxiaoguang@zhihu.com>

## What have you changed? (mandatory)
Add prio label to most coprocessor metrics
- Summarize your change (mandatory)
Add prior's label to most coprocessor metrics. tikv_coprocessor_outdated_request_wait_seconds and tikv_coprocessor_request_error requires more carefully reviews and therefore not changed at this time.

## What are the type of the changes? (mandatory)
- Improvement (change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)
unit tests and manual test

## Does this PR affect documentation (docs) or release note? (mandatory)
NO

## Does this PR affect tidb-ansible update? (mandatory)
Will submit a PR to tidb-ansible to reflect new priority label soon.

### CODE REVIEW

**Comment by sunxiaoguang** [comment]
Looks like CI job failed with not related tests.

**Comment by siddontang** [comment]
PTAL @breeswish

**Comment by breeswish** [comment]
CI failed because machine is full..

**Comment by BusyJay** [comment]
Seems priority is missing for some metrics.

**Comment by breeswish** [comment]
test_output_counts failed. PTAL

**Comment by sunxiaoguang** [comment]
> Seems priority is missing for some metrics.

Right, the code updating those two metrics don't have priority in context. I tried to change but the outcome looks not clean so I removed them at last. Let's try coming back and revisit it later on.

**Pull request closed without merging**
