### PR TITLE
[WIP] Static link gperftools and unwind on linux

### PR DESCRIPTION
**Pull request by YangKeao**
#  What have you changed?

- Build gperftools and unwind at compile-time
- Link them with tikv

These changes are only for Linux. Because compiling gperftools and unwind will fail on mac os (as I have tried). I think this is a bug for building script in gperftools and unwind, but I haven't found an issue about it. `libtool:   error: require no space between '-L' and '/usr/local/opt/icu4c/lib'`

- Fix bugs in profiler examples (relative path was not originally supported)

###  What is the type of the changes?

- Improvement

###  How is the PR tested?

- Manual test

It has been compiled and has run example on my laptop and a CentOS 7 machine.

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No

###  Does this PR affect `tidb-ansible`?

No

###  Refer to a related PR or issue link (optional)

#5666 The first step of this issue.

**NOTICE:** This PR will statically link profiler with gperftools and libunwind. And it will dynamically link tikv with libstdc++.

### CODE REVIEW

**Comment by YangKeao** [comment]
There is still a lot of bugs :(. Maybe statically link gperftools is a bad idea.

**Comment by siddontang** [comment]
> Because compiling gperftools and unwind will fail on mac os

@YangKeao I think only supporting Linux is fine.

**Comment by siddontang** [comment]
Great work

PTAL @breeswish

**Comment by siddontang** [comment]
another thing is how to use HTTP API to profile TiKV? the return format?

**Comment by siddontang** [comment]
> And it will dynamically link tikv with libstdc++

it is fine to dynamically link c++? @zhouqiang-cl

**Comment by zhouqiang-cl** [comment]
> > And it will dynamically link tikv with libstdc++
> 
> it is fine to dynamically link c++? @zhouqiang-cl

we need to test it

**Comment by breeswish** [comment]
> compiling gperftools and unwind will fail on mac os

However homebrew installed gperftools will work.

**Comment by YangKeao** [comment]
Static linking gperftools and unwind is much harder and will bring more bugs than writing a cpu sampler myself :( . Another PR #5697 has been submitted to do cpu profile without gperftools :laughing:

**Pull request closed without merging**
