### PR TITLE
raftstore-v2: use larger target file size

### PR DESCRIPTION
**Pull request by BusyJay**
### What is changed and how it works?
Issue Number: Ref #14352

What's Changed:
```commit-message
Use the same target file size as if compaction guard is enabled.
```

This should ease the problem in #14352.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tabokie — APPROVED** [review]
I don't think the case in internal tests can be fixed with this. For a server with 12731 regions, it will be filled with tiny L0 files (due to memtable control). Tiny L0 files will lead to tiny base level files even though target size is set large. And considering the open file limit 1048576, it only takes 82 files to trigger the limit.

But the change itself looks okay.

**Comment by BusyJay** [comment]
The problem can only be solved by share table cache. As pr body writes, it's only for easing the problem.

**Comment by BusyJay** [comment]
After the patch, file count is reduced from 240k per node to 65k on one testing cluster:
image

**Review by tonyxuqqi — APPROVED** [review]

**Pull request merged**
