### PR TITLE
copr: add vectorized char_length

### PR DESCRIPTION
**Pull request by zhongzc**
###  What have you changed?
Add vectorized version char_length and char_length_utf8

###  What is the type of the changes?
- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?
- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?
N/A

###  Does this PR affect `tidb-ansible`?
N/A

###  Refer to a related PR or issue link (optional)
Solve #6961

###  Benchmark result if necessary (optional)
N/A

###  Any examples? (optional)
N/A

### CODE REVIEW

**Comment by zhongzc** [comment]
@andylokandy PTAL :P

**Comment by andylokandy** [comment]
Congratulations!

**Comment by zhongzc** [comment]
Thanks! @andylokandy @TennyZhuang @leiysky

**Pull request merged**
