### PR TITLE
Add an engine template project - engine_panic

### PR DESCRIPTION
**Pull request by brson**
###  What have you changed?

This adds the engine_panic crate. It is a template from which other engine_traits implementations can be built, by first copying engine_panic into a new crate. Begining an engine this way eliminates hours of defining types, and organizes the crate in a way that is consistent with the existing crates.

I created this after attempting to implement a new engine and discovering that it took many hours just to organize the types correctly.

###  What is the type of the changes?
- Engineering (engineering change which doesn't change any feature or fix any issue)

###  How is the PR tested?

cargo check

###  Refer to a related PR or issue link (optional)

https://github.com/tikv/tikv/issues/4184

### CODE REVIEW

**Comment by 5kbpers** [comment]
PTAL @kennytm @Connor1996

**Comment by 5kbpers** [comment]
@brson We replaced RocksDB `IOLimiter` with [async-speed-limit](https://github.com/tikv/async-speed-limit), and removed `IOLimiterExt` from engine traits in this PR https://github.com/tikv/tikv/pull/6374

**Comment by brson** [comment]
Cool. I'll update this PR this week.

**Comment by brson** [comment]
This is updated.

**Comment by brson** [comment]
@kennytm @Connor1996 could you re-review?

**Pull request merged**
