### PR TITLE
coprocessor:cherry-pick #3774

### PR DESCRIPTION
**Pull request by AndreMouche**
Signed-off-by: AndreMouche <AndreMouche@126.com>

## What have you changed? (mandatory)

This PR cherry-pick #3774 to release-2.1:
1. fix bug in date_format
2. add functions day_name, day_of_month, day_of_week, day_of_year

Please **NOTE** that:
- Do not assume reviewers understand the original issue

## What are the type of the changes? (mandatory)

The currently defined types are listed below, please pick one of the types for this PR by removing the others:
- New feature (non-breaking change which adds functionality)
- Bug fix (non-breaking change which fixes an issue)

## How has this PR been tested? (mandatory)

yes

## Does this PR affect documentation (docs) update? (mandatory)

no

## Does this PR affect tidb-ansible update? (mandatory)

no

## Add a few positive/negative examples (optional)

@breeswish @DorianZheng PTAL

### CODE REVIEW

**Comment by AndreMouche** [comment]
/run-all-tests tidb=release-2.1 pd=release-2.1 tidb-test=release-2.1

**Comment by winkyao** [comment]
/run-integration-common-test  tidb=release-2.1 pd=release-2.1 tidb-test=release-2.1 -tidb-test=pr/721

**Pull request merged**
