### PR TITLE
engine: Fix STORE_ENGINE_SIZE metrics

### PR DESCRIPTION
**Pull request by Connor1996**
## What have you changed? (mandatory)
make STORE_ENGINE_SIZE including the size of memtable and blob files.

## What are the type of the changes? (mandatory)
- Bug fix (change which fixes an issue)

## How has this PR been tested? (mandatory)
manual-test

## Does this PR affect documentation (docs) or release note? (mandatory)
No

### CODE REVIEW

**Comment by siddontang** [comment]
> make STORE_ENGINE_SIZE including the size of memtable and blob files.

seems the previous implementation contains memtable and blob files already.

**Comment by siddontang** [comment]
btw, where is the test?

**Comment by Connor1996** [comment]
@siddontang The used size sent to PD includes these, but `STORE_ENGINE_SIZE` does not. And it is just metrics, hard to add test and unnecessary.

**Comment by breeswish** [comment]
@Connor1996 Do you want to carry this PR's cherry pick in 3.0.2?

**Comment by Connor1996** [comment]
@breeswish Yes

**Comment by breeswish** [comment]
@zhangjinpeng1987 PTAL, thanks

**Pull request merged**
