### PR TITLE
raftstore: adjust max_down_peer_duration based on hibernate timeout

### LINKED ISSUE #10017: raftstore: down peer collection did not consider hibernate region
## Bug Report

When the leader heartbeat to PD, it collects down peers by checking whether a peer did not send raft message for `raftstore.max_peer_down_duration`. When hibernate region is in use, inactive regions will go to hibernate and wake up every 5m (config through `raftstore.peer_stale_state_check_interval`) and will be not raft message when the region is hibernated. So when the leader heartbeat to PD, it collects down peers and will take the time of hibernating into count (since the last time received raft message is when the region awake), and may wrongly report normal peers as down peers to PD and this could affect PD's schedule decision

Usually, the leader won't report to PD frequently, but there are some cases the leader will heartbeat to PD even the leader is hibernated, for example when the region size change due to compaction, the leader will report the region size to PD immediately.

### PR DESCRIPTION
**Pull request by yiwu-arbug**
Signed-off-by: yiwu <yiwu@pingcap.com>

### What problem does this PR solve?

Issue Number: close #10017

Problem Summary: Adjust `max_down_peer_duration` to be at least 2 * `peer_stale_state_check_interval`, so that peers in hibernated state would not be reported as down peer by mistake.

### What is changed and how it works?

What's Changed: 
Adjust `max_down_peer_duration` to be at least 2 * `peer_stale_state_check_interval` when hibernated regions is enabled.

### Related changes

N/A

### Check List

Tests 

CI

Side effects

### Release note 

```release-note
Adjust max_down_peer_duration to 10 minutes. This is to avoid hibernated peers being reported as down peer by mistake.
```

### CODE REVIEW

**Comment by NingLin-P** [comment]
Should also change the value on `etc/config-template.toml`

**Review by NingLin-P — APPROVED** [review]

**Review by BusyJay — APPROVED** [review]

**Comment by BusyJay** [comment]
Should also send PR to change docs.

**Review by nolouch — COMMENTED** [review]
lgtm

**Comment by yiwu-arbug** [comment]
> Should also send PR to change docs.

updating in https://github.com/pingcap/docs-cn/pull/6557

**Comment by HunDunDM** [comment]
Will it cherry-pick?

**Pull request merged**
