### PR TITLE
copr: refactor internally to support new `rpn_fn` interface

### PR DESCRIPTION
**Pull request by skyzh**
### What problem does this PR solve?

**Problem Summary**

This PR refactors co-processor framework internally. Now all data flowing in copr uses the new `BytesRef`-like interface. This laid solid foundation for migrating to `ChunkedVec`

**Overview**

In [RFC: Using chunk format in coprocessor framework](https://github.com/tikv/rfcs/pull/43/files), we proposed a `ChunkedVec` struct to support Chunk-based computing. We plan to:

1. Migrate current co-processor framework to use interface compatible with `ChunkedVec`. 

This is done by adding new functionalities on current `Vec<Option<T>>`. The detailed plan can be found at [Full Chunk-based Computing PR Roadmap](https://github.com/skyzh/tikv/issues/2).

This PR follows #7979 and #8019. After migrating developer interface of vectorized functions in previous works, this PR refactored copr internally, to make the interface as compatible as possible with proposed `ChunkedVec`. After this PR gets merged, the next step is to add a `NotChunkedVec` (which has the same interface as `ChunkedVec`  as described in RFC, but stores `Option<T>` internally).

2. Introduce `ChunkedVec`.

After migrating co-processor to have interface compatible with proposed `ChunkedVec`, we can introduce `ChunkedVec` into TiKV. Then, we may further optimize performance by merging null parameters, etc.

### What is changed and how it works?

Proposal: [RFC: Using chunk format in coprocessor framework](https://github.com/tikv/rfcs/pull/43/files)

What's Changed:

**tidb_query_datatype**

* Introduce `not_chunked_vec` module. In that we will implement `NotChunkedVec`, which has the same interface as `ChunkedVec` but use `Option<Vec<T>>` internally.
* New `ChunkRef` trait. This trait will be implemented on `ChunkedVec`. `ChunkRef<'a, JsonRef>` acts like a `Vec` that can be accessed by index and returns `JsonRef`.
* `Evaluable` is split into three traits.
    * `Evaluable`: Acts like original `Evaluable` except that `into_vector_value` is removed. Now, this trait is implemented **only on primitive types** like `Int`, `Real`.
    * `EvaluableRef`: Now `EvaluableRef` flows in copr framework instead of `Evaluable`. This type is implemented on both primitive types like `&Int`, `&Decimal`, and ref-type like `JsonRef`.
    * **If T is `Evaluable`, it implies that `&T` is `EvaluableRef`**
    * `EvaluableRet`: This is the return type of all vectorized functions. It's implemented on `Bytes`, `Json`, etc. This corresponds to original `Evaluable`. It has only one function `into_vector_value`.
    * Why 3 traits: `rpn_fn` doesn't support lifetime. We can not use `EvaluableRef <'a>` as generic bound. In this way, we have to retain the `Evaluable` (without lifetime) to support generic in vectorized functions.
* `ScalarValueRef` now saves `Option<&T>` instead of `&Option<T>`.
    * Some macros have to be expanded into 7 match arms in order to support that.
* Some functions are refactored to take `JsonRef` as parameter, instead of `Json`.
* `AsRef` on `ScalarValue` and `ScalarValueRef` is removed, as now they can't return something like `&balabala`.
* Introduce `ConvertFrom`. If Y is `ConvertTo<X>`, it implies that X is `ConvertFrom<Y>`. This property is used in implementing `Json` cast in `impl_cast`.

**tidb_query_vec_expr**

* Refactored to fit the new copr framework.
* Some functions are refactored to use `JsonRef`.
* `ScalarArg` now takes `EvaluableRef`
* `VectorArg` now takes `ChunkRef` instead of `&[Option<T>]`
* `Evaluator` now takes a lifetime.
* Modules are refactored as follows:
    * As `rpn_fn` still doesn't support lifetime, we can not use `EvaluableRef` as generic parameter. In this way, we must find another way to refactor these generic functions.
    * `impl_arithmetic`: `ArithmeticOp::T` is `Evaluable + EvaluableRet`, hence fitting into the new framework. This migration can be done efficiently as we leveraged the property "If T is `Evaluable`, it implies that `&T` is `EvaluableRef`".
    * `impl_cast`: `Json` and `Bytes` require special handling. Therefore, `cast_any_as_any` is split into `cast_any_as_json`, `cast_json_as_bytes`, `cast_json_as_any`, etc. `cast_any_as_decimal` is also split.
    * Other modules: generic vectorized function is split into primitive types, bytes and json version.
    * Some functions just has one generic parameter `T: Evaluable`. In this way, we don't have to copy-paste the implementation. We just change that to `T: EvaluableRef <'a>` and create `T: Evaluable`, `JsonRef` and `BytesRef` wrapper of the original function. One example is `is_null_ref`.

**tidb_query_codegen**

* As `Evaluator` now gets a lifetime in trait, `rpn_fn` macro adds that lifetime to Evaluator implementation. e.g. `impl Evaluator <'arg_>`
* Remove workarounds introduced in previous PRs.

**tidb_query_vec_aggr**

* All `Evaluable` are changed to `EvaluableRet`.

**TODO**

* Add tests for new `Json` and `Bytes` functions split from original generic functions.
* Documentation may need updating.
* Reduce duplicated code caused by splitting generic functions.

### Check List 

Tests 

- Unit test

Side effects

* Extra overhead is introduced in `compare_in_by_hash` for `Bytes`. We converted `BytesRef` back to `Vec<u8>` before hashing them.

### CODE REVIEW

**Comment by skyzh** [comment]
@breeswish @TennyZhuang PTAL~

**Comment by breeswish** [comment]
Impressive refactor!

**Comment by skyzh** [comment]
I've resolved conflict with upstream. btw, tpch benchmark seems to have failed.

**Pull request merged**
