### PR TITLE
txn: fix wrong txn_size in acquire_pessimistic_lock

### PR DESCRIPTION
**Pull request by youjiali1995**
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

###  What have you changed?
As the title.

###  What is the type of the changes?
- Bugfix (a change which fixes an issue)

###  How is the PR tested?
- No code

I will test it in https://github.com/tikv/tikv/pull/5422.

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?
No

###  Does this PR affect `tidb-ansible`?
No

### CODE REVIEW

**Comment by sticnarf** [comment]
A bugfix needs a corresponding unit test.

This mistake lets me think maybe it's a bad idea to reuse the same `Option` for various requests...

**Comment by youjiali1995** [comment]
@sticnarf @MyonKeminta PTAL again. Thanks.

**Comment by youjiali1995** [comment]
@MyonKeminta @AndreMouche PTAL

**Pull request merged**
