### PR TITLE
br: use dashmap for br router#tasks

### LINKED ISSUE #17300: br: use dashmap for router#tasks instead of locking the entire map using mutex + hashMap
## Development Task

dashmap provides better concurrency support, operations on different keys can happen at the same time.

### PR DESCRIPTION
**Pull request by Tristan1900**
### What is changed and how it works?
Issue Number: Close  #17300

What's Changed:

Replace Mutex + hashMap with DashMap.
Change the related async method back to normal method

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note
```release-note
NA
```

### CODE REVIEW

**Comment by Tristan1900** [comment]
@YuJuncen could you take a quick look when you have time? Let me know if the change makes sense! thank you

**Review by YuJuncen — APPROVED** [review]

**Comment by YuJuncen** [comment]
cc @3pointer @Leavrth

**Comment by YuJuncen** [comment]
@Tristan1900 This change looks good to me. It looks like we won't hold the lock and `await` something. Then we don't need to use the async version of mutex. [ref](https://docs.rs/tokio/latest/tokio/sync/struct.Mutex.html#which-kind-of-mutex-should-you-use)

**Pull request merged**
