### PR TITLE
txn: Distinguish whether a key exists when acquiring pessimistic lock

### PR DESCRIPTION
**Pull request by andylokandy**
Signed-off-by: Andy Lok <andylokandy@hotmail.com>

### What problem does this PR solve?

Not existing keys and the keys with an empty value is not distinguishable in `PessimisticLockResponse`.

### What is changed and how it works?

- Added a field `not_founds` in `PessimisticLockResponse` to indicate whether the keys exist.

- https://github.com/pingcap/kvproto/pull/709

### Check List 

Tests 

- Unit test

### Release note 

- No release note

### CODE REVIEW

**Comment by youjiali1995** [comment]
https://github.com/tikv/tikv/issues/6711

**Review by youjiali1995 — COMMENTED** [review]
Please add a test case in `tests/integrations/server/kv_service.rs:test_pessimistic_lock()`.

**Comment by andylokandy** [comment]
> Please add a test case in `tests/integrations/server/kv_service.rs:test_pessimistic_lock()`.

Done

**Review by youjiali1995 — APPROVED** [review]

**Review by nrc — APPROVED** [review]
lgtm

**Pull request merged**
