### PR TITLE
cdc: fix resolved ts blocked by channel receiving & improve old value (#8878)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #8878 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:
* Fix resolved ts blocked by channel receiving
* Improve old value performance

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 
* N/A

### CODE REVIEW

**Comment by MyonKeminta** [comment]
@5kbpers Please resolve conflicts

**Comment by overvenus** [comment]
LGTM

**Review by MyonKeminta — APPROVED** [review]
LGTM

**Comment by MyonKeminta** [comment]
@5kbpers CI failed

**Pull request merged**
