### PR TITLE
Prefer unstable sort for primitive types

### PR DESCRIPTION
**Pull request by hbina**
Unstable sort uses less memory and because this is a primitive type,
equal values are indistinguishable so stability is useless.

### What problem does this PR solve?

Problem Summary:

### What is changed and how it works?

What's Changed:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note

### CODE REVIEW

**Comment by 5kbpers** [comment]
Please sign off your commits (with `git commit -s`)

**Comment by 5kbpers** [comment]
Recommend to use `--amend` to overwrite your last commit.

**Comment by andylokandy** [comment]
@hbina you pushed an empty commit.

**Comment by hbina** [comment]
@andylokandy It seems that this [PR](https://github.com/tikv/tikv/pull/8792) have basically implemented this PR. Closing this.

**Pull request closed without merging**
