### PR TITLE
config(cdc): Add the missing from

### PR DESCRIPTION
**Pull request by hi-rustin**
Signed-off-by: hi-rustin <rustin.liu@gmail.com>

### What problem does this PR solve?

None

Problem Summary:

### What is changed and how it works?

What's Changed:

Add the missing from for cdc module.

### Related changes

None

### Check List 

Tests 

None

Side effects

None

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]
LGTM, please add unitests

**Review by amyangfei — APPROVED** [review]

**Comment by hi-rustin** [comment]
/assign @overvenus 

Could you please help me trigger the merge process? Thanks!

**Pull request merged**
