### PR TITLE
[DNM] rsperftools benchmark

### PR DESCRIPTION
**Pull request by YangKeao**
###  What have you changed?

Start profiler at the beginning of tikv-server

###  What is the type of the changes?

- Misc (other changes)

### CODE REVIEW

**Comment by YangKeao** [comment]
Former benchmark is for 10Hz profiler. Next one is for 50Hz.

**Comment by siddontang** [comment]
> Former benchmark is for 10Hz profiler. Next one is for 50Hz.

Don't use 10 or 50, please use 9 or 49Hz

**Comment by siddontang** [comment]
From the book "BPF Performance Tools", to avoid lockstep sampling problem:

+ Consider 100 Hertz. This takes a sample every ten milliseconds. Now consider an application thread that wakes up every ten milliseconds to do two milliseconds of work. It’s consuming 20% of one CPU. If we sample at 100 Hertz, and by coincidence run our profiling tool at just the right time, every sample will coincide with the two-millisecond window of work, so our profile will show it on-CPU 100% of the time. Or, if we hit enter at a different time, every sample will miss, and show that application thread 0% of the time
+ close enough to 100 Hertz that we can reason about it as though it were 100. Eight CPU system for one second? Roughly 800 sample
+ The 99 Hertz strategy only works because application programmers usually pick round numbers for their timed activity: every one second, ten times per second, every 20 milliseconds, etc.

**Comment by YangKeao** [comment]
@siddontang Great! Thanks :+1:

**Pull request closed without merging**
