### PR TITLE
*: move event listener into engine_rocks

### PR DESCRIPTION
**Pull request by Rustin-Liu**
###  What have you changed?
Abstract rocks event listener.
###  What is the type of the changes?

- Engineering (engineering change which doesn't change any feature or fix any issue)
###  How is the PR tested?

cargo test --all --no-run

###  Refer to a related PR or issue link (optional)
#6402

### CODE REVIEW

**Comment by siddontang** [comment]
PTAL @zhangjinpeng1987 @brson @yiwu-arbug

**Comment by zhangjinpeng1987** [comment]
Why remove metric_flusher?

**Comment by Rustin-Liu** [comment]
> Why remove metric_flusher?

It already moved into engine_rocks in my last PR.

**Comment by brson** [comment]
Thanks @Rustin-Liu !

I think this is reasonable for now, but in the long run it isn't abstracted enough, since it is not represented in engine_traits.

But I also don't think this should be in engine_traits. When I look at how this is used, it appears to only be used in src/config.rs when setting up the database, in order to add some metric logging. And that code is very rocks-specific.

Eventually there will need to be some abstract factories that are used to instantiate a database from TiKV's very complex DbConfig type. Offhand I'm not sure where that code should live, but probably not in the engine_* crates, since it won't be reasonable to put DbConfig in those crates.

@Rustin-Liu a good follow up to this might be to abstract CompactionListener. Right now that type lives in engine_rocks and is used by raftstore, but is not abstracted in engine_traits. At the moment my main focus is on getting raftstore completely abstracted over KvEngine, so that would help.

The way to do it is to add a new extension trait to engine_traits, `CompactExt`, following the existing pattern, that defines associated types for the types in compact_listener.rs, rename the existing types to `Rocks*`, and make their methods implementations of the traits.

**Comment by Rustin-Liu** [comment]
> Thanks @Rustin-Liu !
> 
> I think this is reasonable for now, but in the long run it isn't abstracted enough, since it is not represented in engine_traits.
> 
> But I also don't think this should be in engine_traits. When I look at how this is used, it appears to only be used in src/config.rs when setting up the database, in order to add some metric logging. And that code is very rocks-specific.
> 
> Eventually there will need to be some abstract factories that are used to instantiate a database from TiKV's very complex DbConfig type. Offhand I'm not sure where that code should live, but probably not in the engine_* crates, since it won't be reasonable to put DbConfig in those crates.
> 
> @Rustin-Liu a good follow up to this might be to abstract CompactionListener. Right now that type lives in engine_rocks and is used by raftstore, but is not abstracted in engine_traits. At the moment my main focus is on getting raftstore completely abstracted over KvEngine, so that would help.
> 
> The way to do it is to add a new extension trait to engine_traits, `CompactExt`, following the existing pattern, that defines associated types for the types in compact_listener.rs, rename the existing types to `Rocks*`, and make their methods implementations of the traits.

@brson  Now I am working on this, but I don’t know how to deal the RangeProperties. Could you please give me some suggestions?

**Comment by hicqu** [comment]
@Rustin-Liu thanks for your help.

I guess you can write
```rust
trait RangeProperties {
    fn get_approximate_size_in_range;
    fn get_approximate_keys_in_range;
    ......
}
```
And Use `Box<dyn RangeProperties>` in `CompactedEvent`.

**Comment by Rustin-Liu** [comment]
> @Rustin-Liu thanks for your help.
> 
> I guess you can write
> 
> ```rust
> trait RangeProperties {
>     fn get_approximate_size_in_range;
>     fn get_approximate_keys_in_range;
>     ......
> }
> ```
> 
> And Use `Box<dyn RangeProperties>` in `CompactedEvent`.

@hicqu Do you mean we also need to abstract RangeProperties, but what confuses me is should abstract it? Is it just related to Rocks?

**Comment by hicqu** [comment]
Something is just related to Rocks, such as `output_level`. But something can be treated as generic in all `Engine` implementors, such as `approximate_size_in_range` or `approximate_keys_in_range`. What we need to do is find these generic attributes and port them into `engine_traits`.

**Comment by Rustin-Liu** [comment]
> Something is just related to Rocks, such as `output_level`. But something can be treated as generic in all `Engine` implementors, such as `approximate_size_in_range` or `approximate_keys_in_range`. What we need to do is find these generic attributes and port them into `engine_traits`.

Got it. I will try it. Thanks for your reply.

**Pull request merged**
