### PR TITLE
Coprocessor: Support SUM()

### PR DESCRIPTION
**Pull request by breeswish**
## What have you changed? (mandatory)

This PR adds batch aggregate function SUM() for all data types.

- [x] Merge https://github.com/tikv/tikv/pull/4777 first

## What are the type of the changes? (mandatory)

- New feature (change which adds functionality)

## How has this PR been tested? (mandatory)

New unit tests

### CODE REVIEW

**Comment by breeswish** [comment]
@sticnarf The integration test of AVG is `AVG(Int)`, which covers `AVG(Decimal)` as well as `CastIntAsDecimal`. For SUM, it covers `SUM(Bytes)` which will be `SUM(Real)` finally and covers `CastStringAsReal`.

**Comment by sticnarf** [comment]
> @sticnarf The integration test of AVG is `AVG(Int)`, which covers `AVG(Decimal)` as well as `CastIntAsDecimal`. For SUM, it covers `SUM(Bytes)` which will be `SUM(Real)` finally and covers `CastStringAsReal`.

Got it...

**Pull request merged**
