### PR TITLE
raftkv: fix inaccurate async write duration metric

### LINKED ISSUE #17579: Storage async write duration is inaccurate
## Bug Report

As title, because it mistakenly includes task wait time in the scheduler worker pool.
As a result, the metric is higher than the actual value, particularly when TiKV is under load.

https://github.com/tikv/tikv/blob/ff78c79606a24610f96cd5b01a9d5268795027d1/src/server/raftkv/mod.rs#L585-L601

I believe this change is made by  accident because it is introduced in a refactor PR https://github.com/tikv/tikv/pull/13854 .

### What version of TiKV are you using?

v7.5.2

### Steps to reproduce

Run go-yscb 100% update with 1000 threads.

### What did you expect?

Do not include task wait time in the scheduler worker pool.

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close #17579

What's Changed:

```commit-message
Fix inaccurate storage async write duration metric, which mistakenly
included task wait time in the scheduler worker pool. This occurs
because the metric is observed in a future running on the scheduler
worker pool, leading to inflated values, especially under load. This
can be misleading and cause confusion during troubleshooting.
This commit corrects the metric by observing it in the async write callback.
```

### Related changes

- Need to cherry-pick to the release branch

### Check List

Tests 

- Manual test (add detailed scripts or steps below)

Run go-yscb 100% update with 1000 threads.
Left: master, right: this PR

img_v3_02f0_3def8190-9fb2-422f-b32a-53c5ed1f3cdg

This PR cuts almost half of the async write duration for "99.99%".

### Release note

```release-note
None
```

### CODE REVIEW

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by SpadeA-Tang** [comment]
async snapshot duration should have the same problem.

**Review by v01dstar — APPROVED** [review]

**Review by LykxSassinator — APPROVED** [review]

**Comment by overvenus** [comment]
/hold

Fixing snapshot metrics ...

**Comment by overvenus** [comment]
/unhold

Fixed.

{97142041-EA10-4B66-BD4F-65DC8C3B685E}

**Pull request merged**
