### PR TITLE
sst_importer: fix the file exists issue in link file

### PR DESCRIPTION
**Pull request by 3pointer**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/br/issues/1179
Problem Summary:
After change `rename file` to `link file` in https://github.com/tikv/tikv/pull/9285/, TiKV will have an external [check](https://github.com/hunterlxt/tikv/blob/9d123f7b03c57679bbf410540ad05b1265ae441b/components/encryption/src/manager/mod.rs#L338-L344). which makes restore fail due to sst_importer will create an empty file in sst writer[#build](https://github.com/tikv/tikv/blob/bfc3c47d3ae6d34065892ddcd59f8599b7e59214/src/import/sst_service.rs#L309). 
This bug happenned when TDE enabled.

### What is changed and how it works?

What's Changed:
This PR tries to fix it by move sst_writer#buid into download after link_file.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

### Release note 

Fix the issue that br reports file already exists error when TDE enabled during restoration.

### CODE REVIEW

**Comment by hunterlxt** [comment]
can you explain how empty file cause existed file info in file dict? @3pointer

**Comment by 3pointer** [comment]
> can you explain how empty file cause existed file info in file dict? @3pointer

As I mentioned in the description. this build function will open a sst writer with path.save https://github.com/tikv/tikv/blob/6708ce171792df02e1e90e1fe1e67e424d1586c8/components/engine_rocks/src/sst.rs#L229
I think we can avoid it.

**Review by Little-Wallace — APPROVED** [review]
LGTM

**Review by kennytm — APPROVED** [review]

**Comment by YuJuncen** [comment]
/label needs-cherry-pick-4.0

because https://github.com/tikv/tikv/pull/10598 has bring #9285 to release-4.0

**Pull request merged**
