### PR TITLE
statitics: send original string value for sampling data (#10336)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #10336 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/10382
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/10382:release-5.1-47e48761e952
```

---

Signed-off-by: Yiding Cui <winoros@gmail.com>

### What problem does this PR solve?

Compabiliable change with https://github.com/pingcap/tidb/pull/25311

Problem Summary:

TiDB still needs the original data instead of the collation key.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

This pr sends the original string value instead of its collation key to TiDB.
This also saves the encoding CPU costs.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

### Release Note
```
None
```

### CODE REVIEW

**Review by skyzh — APPROVED** [review]

**Review by lzmhhh123 — APPROVED** [review]

**Comment by time-and-fate** [comment]
@skyzh Hi~ Could you help to merge this PR?

**Pull request merged**
