### PR TITLE
Cherry pick makefile & rust-toolchain changes

### PR DESCRIPTION
**Pull request by breeswish**
## What have you changed? (mandatory)

This PR cherry picks some recent changes about the Makefile and rust-toolchain, so that our build cache won't be invalidated when switching to release-3.0 branch from master branch.

### CODE REVIEW

**Comment by siddontang** [comment]
CI failed @breeswish

**Comment by brson** [comment]
I can't see the error in the CI report but if it's about get_mem_info then I think it needs a sys-info crate update, which can be cherry-picked from 9a14c49b33da9bfd229c88885647095893d17597.

I can't do the pick myself since I can't write to breeswish. cc @breeswish @AndreMouche @siddontang

**Comment by breeswish** [comment]
I'm deeply grateful to Brian's help, figuring out what happened. I went head to this direction previously, but made a mistake that thought release-3.0 was using latest sys-info.

**Pull request merged**
