### PR TITLE
scripts: update check-bins to make it python3.8 compatible

### PR DESCRIPTION
**Pull request by ichn-hu**
Signed-off-by: ichn-hu <zfhu16@gmail.com>

### What problem does this PR solve?

Problem Summary:

check-bins.py uses `time.clock` to estimate the running time, but it is deprecated since python 3.3 and is removed since python 3.8. Users with python 3.8+ can't run this script.

See https://docs.python.org/3.7/library/time.html?highlight=time%20clock#time.clock for details.

### What is changed and how it works?

What's Changed: use time.time instead of `time.clock`

### Related changes

- N/A

### Check List 

Tests 

- No code

Side effects

- N/A

### Release note 

- no release note.

### CODE REVIEW

**Review by BusyJay — APPROVED** [review]

**Review by breeswish — APPROVED** [review]

**Comment by hi-rustin** [comment]
> @breeswish: `/merge` is only allowed for the committers in [list](https://prow.tidb.io/ti-community-owners/repos/tikv/tikv/pulls/9428/owners).

@breeswish  You can add a sig label to get the permissions.

**Comment by breeswish** [comment]
@hi-rustin This PR doesn't belong to any sig I think..

**Comment by hi-rustin** [comment]
> @hi-rustin This PR doesn't belong to any sig I think..

Then only people with write access can review and merge it.

**Comment by hi-rustin** [comment]
> @hi-rustin This PR doesn't belong to any sig I think..

We will redesign this part permissions.

**Review by gregwebs — APPROVED** [review]

**Pull request merged**
