### PR TITLE
Remove sync-log config option (migrate #8631)

### PR DESCRIPTION
**Pull request by hunterlxt**
Signed-off-by: Xintao <hunterlxt@live.com>

### What problem does this PR solve?

Migrate #8631

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:

### Release note 
- Set sync-log true always.

### CODE REVIEW

**Review by NingLin-P — APPROVED** [review]

**Review by gengliqi — APPROVED** [review]

**Comment by BusyJay** [comment]
Given now existing users rely on the feature to get reasonable stable latency, I suggest to wait until Plan B is implemented before releasing.

**Comment by breeswish** [comment]
@hunterlxt Please confirm whether this PR should be merged in v4.0.7.

**Comment by zhangjinpeng1987** [comment]
Should after the fsync-ctl feature merged.

**Comment by breeswish** [comment]
Is this PR mergeable now? @zhangjinpeng1987

**Comment by hunterlxt** [comment]
@breeswish https://github.com/tikv/tikv/pull/8855 has not been merged. But the PR may be closed, we can do this in that PR.

**Pull request closed without merging**
