### PR TITLE
chore: update codecov.yml

### LINKED ISSUE #16772: Ignore the test folder in when upload test coverage data to codecov.io
## Development Task

Ignore these folders:
- [ ] `components/test_**`
- [ ] `components/**_tests`
- [ ] `/tests/`

### PR DESCRIPTION
**Pull request by wuhuizuo**
### What is changed and how it works?

Issue Number: Close #16772

What's Changed:

```commit-message
chore: Ignore the test folders when upload test coverage data to codecov.io
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by wuhuizuo** [comment]
We should ignore the sub test folders under `components`.

**Review by bufferflies — APPROVED** [review]

**Review by tonyxuqqi — APPROVED** [review]
LGTM

**Pull request merged**
