### PR TITLE
copr: fix wrong function cast double to double

### PR DESCRIPTION
**Pull request by lzmhhh123**
Signed-off-by: lzmhhh123 <lzmhhh123@gmail.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/25200

### What is changed and how it works?

What's Changed: cast_real_to_signed_real and cast_real_to_unsigned_real is wrong.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
fix wrong function cast double to double
```

### CODE REVIEW

**Review by wshwsh12 — APPROVED** [review]
LGTM

**Comment by lzmhhh123** [comment]
/needs-cherry-pick-5.1

**Pull request merged**
