### PR TITLE
coprocessor/dag/expr: add some un-pushed builtin UDF(CharLength)

### PR DESCRIPTION
**Pull request by spongedu**
## What have you changed? (mandatory)

implement builtin function: `CharLength` in `coprocessor`.
This is for #3275

## What are the type of the changes? (mandatory)

Improvement

## How has this PR been tested? (mandatory)

unittest

## Refer to a related PR or issue link (optional)

#3275

### CODE REVIEW

**Comment by spongedu** [comment]
Currently builtin `CharLength` doesn't deal with binary string types correctly. I'll fix it in [TiDB:#7410](https://github.com/pingcap/tidb/pull/7410/files)

**Comment by AndreMouche** [comment]
It seems you add a new builtin function in tidb for the Binary string @spongedu  [TiDB:#7410](https://github.com/pingcap/tidb/pull/7410/files). So would tidb push down `CharLength` and `CharLengthBinary` separately? @zz-jason

**Comment by hicqu** [comment]
LGTM.

**Comment by zz-jason** [comment]
We should, to be compatible with MySQL 😂

**Comment by spongedu** [comment]
@zz-jason I think maybe we could separated it into `CharLength` and `CharLengthBinary` and push down to TiKV separately, which would be more efficient at runtime. This requires a new function signature in tipb and some modification in TiDB expression module.  Before that we can keep this pr unchanged.

**Comment by zz-jason** [comment]
@spongedu +1, Agree!

**Comment by spongedu** [comment]
@AndreMouche @hicqu PTAL :)

**Comment by huachaohuang** [comment]
@hicqu Please check and approve if everything goes well.

**Comment by hicqu** [comment]
LGTM.

**Pull request merged**
