### PR TITLE
Configure default pd endpoint for tikv-server

### PR DESCRIPTION
**Pull request by aknuds1**
###  What have you changed?

Add sensible default for --pd-endpoints flag ("127.0.0.1:2379"), so that one can easily run tikv-server for local testing.

###  What is the type of the changes?

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?

I tested manually and with `make test`.

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

Not sure.

###  Does this PR affect `tidb-ansible`?

No.

### CODE REVIEW

**Comment by aknuds1** [comment]
@siddontang Do you know why the integration test fails?

**Comment by breeswish** [comment]
@aknuds1 Don't worry, it's simply unstable tests.

**Comment by H-ZeX** [comment]
I run the pd, tikv, tidb, with this config
```toml
#  tikv's config

log-level = "info"

[server]
# end-point-enable-batch-if-possible = false
## Listening address.
# addr = "127.0.0.1:20161"
# status-addr = ""

[pd]
endpoints = ["127.0.0.1:3379"]

[storage]
data-dir = "/tmp/tikv_no_batch"
```
```toml
#  pd's config

name = "pd"
data-dir = "/tmp/pd_no_batch"
client-urls = "http://127.0.0.1:3379"
# peer-urls = "http://127.0.0.1:3380"

[log]
level = "info"
```
```toml
# tidb's config

port = 4006
store = "tikv"
path = "127.0.0.1:3379"

[log]
level = "info"

# [status]
# report-status = false
```

according to tikv's log ` ["connecting to PD endpoint"] [endpoints=127.0.0.1:2379]`, although if we use command line param, it is ok.

**Comment by zhouqiang-cl** [comment]
So. It will bring default config file problem. I think the priority should be command config > config file> code config.
@aknuds1 How did you think about it

**Comment by aknuds1** [comment]
@zhouqiang-cl I wasn't aware that the default would take precedence over command line. I will see if I can figure out how to fix this.

**Comment by breeswish** [comment]
So maybe you can consider modifying the default value for PD endpoint config instead of PD endpoint command line args?

**Comment by H-ZeX** [comment]
> @zhouqiang-cl I wasn't aware that the default would take precedence over command line. I will see if I can figure out how to fix this.

The default doesn't take precedence over command line, but it take precedence over config file

**Comment by aknuds1** [comment]
@H-ZeX Sorry, I meant to say I wasn't aware the command line default took precedence over config. I'm trying now to change the config default instead of the command line default as @breeswish suggested.

**Comment by aknuds1** [comment]
@breeswish @H-ZeX @zhouqiang-cl I pushed a change where the default is defined for `TiKvConfig` instead of for the command line parser. Can you please provide feedback on whether this is the correct approach? It seems to work.

**Comment by breeswish** [comment]
According to CI, `config::tests::test_pd_cfg` failed and you need to fix it.

**Comment by aknuds1** [comment]
> LGTM
> 
> Btw, seem we can show our default values in command help output. :-)

Yeah, I was actually wondering if I should add the default value to the command line help. I can do it in another PR?

**Pull request merged**
