### PR TITLE
ignore max_row_versions in check_need_gc

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve?

Close pingcap/tidb#22612 and https://github.com/tikv/tikv/issues/9216.

### What is changed and how it works?

Ignore `max_row_versions` in `check_need_gc`. If there are too many versions for one key, they will trigger GC in `MvccReader::get_txn_commit_record`.

### Check List 

Tests 

- Unit test
- Manual test
With the patch, gc worker CPU reduces quickly:
图片

### Release note 
* No release note.

### CODE REVIEW

**Review by youjiali1995 — APPROVED** [review]
/LGTM 😀

**Review by MyonKeminta — APPROVED** [review]
LGTM

**Comment by cosven** [comment]
Do we need to cherry pick this PR to 5.0?

**Comment by youjiali1995** [comment]
> Do we need to cherry pick to 5.0?

Master is 5.0.

**Pull request merged**
