### PR TITLE
fix incomplete sub_path canonicalization

### PR DESCRIPTION
**Pull request by tabokie**
Signed-off-by: tabokie <xy.tao@outlook.com>

### What problem does this PR solve?

Issue Number:

Problem Summary:

Sub path is not canonicalized.

### What is changed and how it works?

What's Changed:

Concatenate sub path before canonicalize.

### Check List 

Tests
- Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by yiwu-arbug — APPROVED** [review]

**Comment by yiwu-arbug** [comment]
@tabokie why this one is closed?

**Comment by tabokie** [comment]
@yiwu-arbug This turns out not to be the exact cause for tikv/raft-engine#75:
By default we use `data-dir`/raft-engine as raft engine path, `data-dir`/raft as raftdb path. The user manually links `data-dir`/raft to another disk and expects TiKV to automatically create a sibling directory for storing raft engine.

But it's related if we decide to use existing raftdb directory as raft engine path. I might reopen this later.

**Comment by tabokie** [comment]
Ping @Connor1996

**Review by Connor1996 — APPROVED** [review]
rest LGTM

**Pull request merged**
