### PR TITLE
storage: reduce extra next/pre in row_scan

### PR DESCRIPTION
**Pull request by JayiceZ**
Signed-off-by: JayiceZ <1185430411@qq.com>

 optimize logic in raw_scan

### What is changed and how it works?

close https://github.com/tikv/tikv/issues/11572

What's Changed:
optimize logic in raw_scan

### Check List 

Tests 

- Unit test

### Release note 

```release-note
optimize logic in raw_scan
```

### CODE REVIEW

**Comment by JayiceZ** [comment]
old pr, see

> [REVIEW NOTIFICATION]
> 
> This pull request has not been approved.
> 
> To complete the [pull request process](https://book.prow.tidb.io/#/en/workflows/pr), please ask the reviewers in the [list](https://prow.tidb.io/tichi/repos/tikv/tikv/pulls/11625/owners) to review by filling `/cc @reviewer` in the comment. After your PR has acquired the required number of LGTMs, you can assign this pull request to the committer in the [list](https://prow.tidb.io/tichi/repos/tikv/tikv/pulls/11625/owners) by filling `/assign @committer` in the comment to help you merge this pull request.
> 
> The full list of commands accepted by this bot can be found [here](https://prow.tidb.io/command-help?repo=tikv%2Ftikv).

Oh, it seems like I have already added `close tikv#11572`

**Comment by tabokie** [comment]
> ems like I have already added `close tikv#11572`

@JayiceZ The checker forbids you adding "tikv" in front of the issue number.

**Comment by JayiceZ** [comment]
> > ems like I have already added `close tikv#11572`
> 
> @JayiceZ The checker forbids you adding "tikv" in front of the issue number.

Really? It seems that other PRs also carry ‘tikv’ in front of the issue number,  but they don’t have this warning
like https://github.com/tikv/tikv/pull/11639/commits 😢

**Comment by tabokie** [comment]
@JayiceZ This rule is added in https://github.com/ti-community-infra/tichi/pull/791. Sometimes GitHub displays `tikv#xxx` when in fact the text is `#xxx`, maybe that's why the other PR passed the check.

**Review by tabokie — APPROVED** [review]

**Review by Connor1996 — APPROVED** [review]
LGTM

**Pull request merged**
