### PR TITLE
engine_traits: Add delete_range (no cf) methods

### PR DESCRIPTION
**Pull request by brson**
Signed-off-by: Brian Anderson <andersrb@gmail.com>

### What problem does this PR solve?

The other two mutation methods, put and delete, have two versions each: one that takes a CF, and one that doesn't (it mutates CF_DEFAULT). The `delete_range_cf` method though has no corresponding `delete_range` method.

This PR adds the method.

This is not _actually_ needed by tikv - the one place it calls `delete_range_cf(CF_DEFAULT...)` makes sense to continue using the "cf" version of the method.

As a matter of API design though, these methods should exist.

But furthermore, the engine test suite I'm developing will be more self-consistent if the non-cf version of this method is available - various tests are parameterized over both the "cf" and "non-cf" versions of these mutation methods.

I've included no unit tests, but the engine_traits_test suite will include tests for it, and I intend to submit a PR for that in the next week or so.

Part of https://github.com/tikv/tikv/issues/6402

### What is changed and how it works?

Add `delete_range` methods to `SyncMutable` and `Mutable` traits in engine_traits.

### Release note 

- No release note.

### CODE REVIEW

**Comment by brson** [comment]
Rebased.

**Review by kennytm — COMMENTED** [review]
/lgtm

**Comment by brson** [comment]
@kennytm ti-chi-bot didn't recognize your lgtm. Can you try it again?

**Pull request merged**
