### PR TITLE
metrics: grafana dashboards support multiple cluster (#9563)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #9563 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/9572
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/9572:release-4.0-bf92a4a9b56f
```

---

### What problem does this PR solve?

Many users(come from DBaaS、operator、tiup) monitor multiple TiDB clusters in one Grafana, this PR make Grafana dashboards support multiple clusters and not affect single cluster usage. Cluster variable is hidden by default.

### What is changed and how it works?

- add a tidb_cluster label in all expr
- add cluster variable in Grafana templating

How it Works:
load it to your Grafana :))

Single Cluster:
No change

Multiple Cluster:
Construct a label that can uniquely identify the cluster. in tidb_operator, you can use {namespace}-{cluster_name} as your {tidb_cluster} variable.
add this configuration to your prometheus config
```
relabel_configs:
  - source_labels:
      - namespace
      - name
    separator: "-"
    target_label: tidb_cluster
```

### Related changes

- https://github.com/pingcap/tidb/pull/22503/files

### Check List 

Tests 

- No code

Side effects

- No effects

###  Release note

- metrics: grafana dashboards support multiple clusters

### CODE REVIEW

**Comment by zjj2wry** [comment]
@zhongzc @breeswish conflict fixed, PTAL

**Comment by breeswish** [comment]
It's strange that fast-tune is updated. Could you update again? @zjj2wry

**Review by breeswish — APPROVED** [review]

**Pull request merged**
