### PR TITLE
rust-rocksdb: rocksdb: Fix the bug that the key manager is not updated during the Rename

### PR DESCRIPTION
**Pull request by ti-srebot**
update rust-rocksdb to include tikv/rust-rocksdb#613 for master
### Release note
- No release note

### CODE REVIEW

**Comment by hunterlxt** [comment]
close #9701

**Comment by yiwu-arbug** [comment]
WeChatWorkScreenshot_aceda805-cd92-4887-8902-18f16b82f234

**Review by yiwu-arbug — APPROVED** [review]

**Comment by BusyJay** [comment]
CI failure should be fixed by #9738.

**Review by hunterlxt — APPROVED** [review]
/LGTM

**Pull request merged**
