### PR TITLE
raftstore: reuse v2 conf change logic for v1

### PR DESCRIPTION
**Pull request by Connor1996**
Signed-off-by: Connor1996 <zbk602423539@gmail.com>

### What is changed and how it works?

Issue Number: Ref #12876 

What's Changed: It's a precedent code clean for #12972 

```commit-message
Reuse conf change logic for both v1 and v2
```

### Check List 

Tests 

- No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by ethercflow — APPROVED** [review]
LGTM

**Comment by BusyJay** [comment]
I think making v1 use its own implementation is on purpose. So when we change the implementation of v2, we don't need to consider compatibility issue.

**Comment by Connor1996** [comment]
> I think making v1 use its own implementation is on purpose. So when we change the implementation of v2, we don't need to consider compatibility issue.

PD still adds learners and delete learners by `ChangePeerV1`, and if don't reuse, I need to implement witness logic for both v1 and v2 which is verbose.

**Comment by BusyJay** [comment]
> PD still adds learners and removes learners by `ChangePeerV1`

Why not use `ChangePeerV2`?

**Comment by Connor1996** [comment]
> > PD still adds learners and removes learners by `ChangePeerV1`
> 
> Why not use `ChangePeerV2`?

I don't know. /cc @HunDunDM

**Comment by HunDunDM** [comment]
According to [the RFC of joint-consensus](https://github.com/tikv/rfcs/blob/master/text/0054-joint-consensus.md).

> It's recommended to use ChangePeerV2 only for replacing peers for now.

It is very simple to change the logic of Add Peer and Remove Peer from using ChangePeer first to using ChangePeerV2 first in PD. In effect, extra code is added to prioritize the use of ChangePeer.

After modification, the steps of `RemoveVoter` will be changed from `RemovePeer` to `DemoteVoter + RemoveLearner`, like [pd#4444](https://github.com/tikv/pd/issues/4444).

**Comment by BusyJay** [comment]
After these years of practice, I think we can use `ConfChangeV2` for most of operations. On the other hand, we can always use V2 to do witness related operations, so we don't need to touch the v1 code. There have been cases that modifying existing conf change implementation breaks compatibility, so let's be cautious.

**Comment by Connor1996** [comment]
> After these years of practice, I think we can use ConfChangeV2 for most of operations. On the other hand, we can always use V2 to do witness related operations, so we don't need to touch the v1 code. There have been cases that modifying existing conf change implementation breaks compatibility, so let's be cautious.

If there is no issue for V2, let's all operations use V2, and only use V1 for cluster that is not support joint consensus

**Comment by Connor1996** [comment]
use V2 for all operators https://github.com/tikv/pd/pull/5408, and close this PR to keep the v1 logic unchanged for compatibility.

**Pull request closed without merging**
