### PR TITLE
br: support set compression level when write sst files (#8400)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #8400 to release-4.0

---

### What problem does this PR solve?
Add compression level for sst writers

### What is changed and how it works?
Add interface to enable br explicitly set compression level when write sst files.

### Related changes
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

### Release note 
- No release note

### CODE REVIEW

**Comment by glorv** [comment]
waiting for https://github.com/tikv/rust-rocksdb/pull/532

**Comment by glorv** [comment]
waiting for #8463 to update jemalloc deps

**Review by overvenus — APPROVED** [review]
LGTM

**Comment by glorv** [comment]
@yiwu-arbug  PTAL

**Review by yiwu-arbug — APPROVED** [review]
LGTM

**Comment by yiwu-arbug** [comment]
@Connor1996 is it okay to merge this one? are we code-freezed for v4.0.6?

**Comment by Connor1996** [comment]
@yiwu-arbug it's already freezed. If it's critical, you can send an email to QA team to merge it.

**Pull request merged**
