### PR TITLE
txn: check_txn_status Support setting write rollback or not when txn not exist

### PR DESCRIPTION
**Pull request by MyonKeminta**
###  What have you changed?

This PR makes `check_txn_status` supports specifying the behavior when neither commit/rollback record nor lock of a transaction's primary key is found. A new parameter `rollback_if_not_exist` was added. If it's `true`, it will write a rollback record in this case; otherwise, it returns a new error TxnNotFound.

This is part of supporting large transactions.

###  What is the type of the changes?

- New feature (a change which adds functionality)

###  How is the PR tested?

- Unit test
- Integration test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No

###  Does this PR affect `tidb-ansible`?

No

### CODE REVIEW

**Comment by MyonKeminta** [comment]
@coocood @tiancaiamao @youjiali1995 @sticnarf PTAL

**Comment by coocood** [comment]
LGTM

**Pull request merged**
