### PR TITLE
raftstore: change send proposal time to waterfall metrics

### PR DESCRIPTION
**Pull request by sticnarf**
### What is changed and how it works?

Issue Number: Ref #12362

What's Changed:

```commit-message
Durations related to a single query are recorded as waterfall metrics,
which means it records the duration from the very beginning to the
instant when the event happens.

Previously, proposal_send_wait_nanos was an exception. So, this
commit makes this consistent with other metrics.

This commit also adds a Grafana Raft waterfall panel for it.
```
image

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by you06 — COMMENTED** [review]
Still 2 usages of removed `tikv_raftstore_proposal_send_wait_duration_seconds` in L14007 and L14098 of `tikv_details.json`. Sorry, I can't provide a link to it because this file is too large to show on the webpage.

**Comment by sticnarf** [comment]
> Still 2 usages of removed `tikv_raftstore_proposal_send_wait_duration_seconds` in L14007 and L14098 of `tikv_details.json`. Sorry, I can't provide a link to it because this file is too large to show on the webpage.

I remove these two panels because it will not lead to meaningful result by just minusing two waterfall metrics

**Review by you06 — APPROVED** [review]

**Pull request merged**
