### PR TITLE
scheduler: handle system commands in high priority pool

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
Signed-off-by: zhangjinpeng1987 <zhangjinpeng@pingcap.com>

## What have you changed? (mandatory)

Handle system commands like `ScanLock` and `ResolveLock` in high priority pool, to reduce the impact of system commands for normal commands. Because after https://github.com/pingcap/tidb/pull/10379, there maybe several `ScanLock` and `ResolveLock` commands are running in the same time.

## What are the type of the changes? (mandatory)

- Improvement (change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)

- [x] benchmark

## Does this PR affect documentation (docs) or release note? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No

### CODE REVIEW

**Comment by siddontang** [comment]
CI failed 

```
thread 'cases::test_conf_change::test_tick_after_destroy' panicked at 'assertion failed: num_threads >= 1', components/tikv_util/src/threadpool.rs:195:9

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

stack backtrace:

   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace

             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39

   1: std::sys_common::backtrace::_print

             at src/libstd/sys_common/backtrace.rs:71

   2: std::panicking::default_hook::{{closure}}

             at src/libstd/sys_common/backtrace.rs:59

             at src/libstd/panicking.rs:197

   3: std::panicking::default_hook

             at src/libstd/panicking.rs:211

   4: std::panicking::rust_panic_with_hook

             at src/libstd/panicking.rs:474

   5: std::panicking::begin_panic

             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libstd/panicking.rs:408

   6: tikv_util::threadpool::ThreadPool<Ctx>::new

             at ./<::std::macros::panic macros>:3

   7: tikv_util::threadpool::ThreadPoolBuilder<C,F>::build

             at ./components/tikv_util/src/threadpool.rs:126

   8: tikv::storage::txn::scheduler::Scheduler<E>::new

             at ./src/storage/txn/scheduler.rs:186

   9: tikv::storage::Storage<E>::from_engine

             at ./src/storage/mod.rs:590

  10: tikv::server::node::create_raft_storage

             at ./src/server/node.rs:44

  11: <test_raftstore::server::ServerCluster as test_raftstore::cluster::Simulator>::run_node

             at components/test_raftstore/src/server.rs:133

  12: test_raftstore::cluster::Cluster<T>::run_node

             at ./components/test_raftstore/src/cluster.rs:205

  13: test_raftstore::cluster::Cluster<T>::start

             at ./components/test_raftstore/src/cluster.rs:155

  14: test_raftstore::cluster::Cluster<T>::run

             at ./components/test_raftstore/src/cluster.rs:183

  15: failpoints::cases::test_conf_change::test_tick_after_destroy

             at tests/failpoints/cases/test_conf_change.rs:155

  16: failpoints::cases::test_conf_change::test_tick_after_destroy::{{closure}}

             at tests/failpoints/cases/test_conf_change.rs:146

  17: core::ops::function::FnOnce::call_once

             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libcore/ops/function.rs:231

  18: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once

             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/liballoc/boxed.rs:704

```

**Comment by MyonKeminta** [comment]
LGTM, but CI is failing

**Pull request merged**
