### PR TITLE
coprocessor/dag/expr: add some un-pushed builtin UDF(Pow)

### PR DESCRIPTION
**Pull request by smallyard**
## What have you changed? (mandatory)

implement builtin function: Pow in coprocessor.
This is for #3275

## What are the type of the changes? (mandatory)

Improvement

## How has this PR been tested? (mandatory)

unittest

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

no

## Does this PR affect tidb-ansible update? (mandatory)

no

## Refer to a related PR or issue link (optional)

#3275

### CODE REVIEW

**Comment by smallyard** [comment]
@AndreMouche CircleCI does'n work well.

**Comment by smallyard** [comment]
@AndreMouche @siddontang Sorry, I submit some wrong code to this branch, and I have reset it, could you re-approve this PR?

**Comment by Hoverbear** [comment]
@smallyard Yes #3214 should help with Circle being unreliable.

**Comment by AndreMouche** [comment]
Please fix the `DCO`

**Comment by smallyard** [comment]
@AndreMouche To fix the DCO, I need to open a new PR.
@siddontang said the old PR can be merged even not signed. https://github.com/tikv/tikv/pull/3424#issuecomment-411984738
Please merge this PR, I will signe DCO next time.

**Comment by AndreMouche** [comment]
Seems I do not have the permission to merge PR without `DCO`. By the way, I'm sure you can use several git tools to fix the `DCO` in this branch, try to fix it?

**Comment by smallyard** [comment]
I will open a new PR.

**Comment by smallyard** [comment]
@AndreMouche  move to https://github.com/tikv/tikv/pull/3475

**Pull request closed without merging**
