### PR TITLE
image: fix logo-too-big

### PR DESCRIPTION
**Pull request by dcalvin**
## What have you changed? (mandatory)

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:
- updated a logo with a more fitting size.

## What are the type of the changes? (mandatory)

The currently defined types are listed below, please pick one of the types for this PR by removing the others:
- fix

### CODE REVIEW

**Comment by siddontang** [comment]
please fix the conflict

**Comment by breeswish** [comment]
BTW what's the difference for `tikv-logo.png` and `tikv.svg`? And if svg is available, why we use PNG then?

**Comment by dcalvin** [comment]
> tikv-logo.png

tikv-logo.png is originally used for better supportability I think.  According to github, "We have had to disable svg image rendering on GitHub.com due to potential cross-site scripting vulnerabilities."

**Comment by breeswish** [comment]
Please resolve conflicts. Additionally I prefer a high resolution logo with enough blanks (so that in Retina it won't be blurred).

**Comment by breeswish** [comment]
Close for https://github.com/tikv/tikv/pull/4713

**Pull request closed without merging**
