### PR TITLE
coprocessor/codec/mysql/duration: Fix micro_secs of Duration

### PR DESCRIPTION
**Pull request by koushiro**
## What have you changed? (mandatory)

Fix function micro_secs of struct Duration. The original function returns nanoseconds.

## What are the type of the changes? (mandatory)

- Bug fix (non-breaking change which fixes an issue)

## How has this PR been tested? (mandatory)

unit test

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

no

## Does this PR affect tidb-ansible update? (mandatory)

no

## Refer to a related PR or issue link (optional)

[3601](https://github.com/tikv/tikv/issues/3601)
[3602](https://github.com/tikv/tikv/pull/3602)

### CODE REVIEW

**Comment by koushiro** [comment]
@huachaohuang PTAL

**Comment by huachaohuang** [comment]
Thanks @koushiro , @breeswish @hicqu please approve again.

**Pull request merged**
