### PR TITLE
update grpc-rs

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

###  What have you changed?
update grpc-rs dependency to resolve a memory leak issue.

###  What is the type of the changes?

Engineering

###  How is the PR tested?
- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?
No.

###  Does this PR affect `tidb-ansible`?
No.

### CODE REVIEW

**Comment by siddontang** [comment]
do we have a way to config the sink buffer in gRPC now, not default 4k?

**Comment by hicqu** [comment]
@siddontang we can't config it now.

**Comment by mahjonp** [comment]
/bench

```
workload:
  prepare: true
```

**Pull request merged**
