### PR TITLE
*: refactor: remove the tikv_util::map macro

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve?

Problem Summary:

Since plain arrays have implemented IntoIterator since Rust 1.53, there is no need to use the `tikv_util::map!` macro to construct a HashMap anymore (especially all non-test use of the `map!` calls just create an empty map). 

### What is changed and how it works?

What's Changed:

Remove the `tikv_util::map!` macro, and refactor everywhere the `map!` macro is used.

### Check List 

Tests 

- Unit test

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by sticnarf — APPROVED** [review]
LGTM

**Review by zhongzc — APPROVED** [review]
LGTM

**Comment by zhongzc** [comment]
Please fix the lint

**Comment by kennytm** [comment]
/test

https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/7065/nodes/81/log/?start=0

```
[2021-09-03T09:25:33.238Z] test test_resolve::test_joint_confchange ... thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', components/cdc/tests/failpoints/../mod.rs:66:87
[2021-09-03T09:25:33.238Z] stack backtrace:
[2021-09-03T09:25:33.238Z]    0: rust_begin_unwind
[2021-09-03T09:25:33.238Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panicking.rs:515:5
[2021-09-03T09:25:33.238Z]    1: core::panicking::panic_fmt
[2021-09-03T09:25:33.238Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/panicking.rs:92:14
[2021-09-03T09:25:33.238Z]    2: core::result::unwrap_failed
[2021-09-03T09:25:33.238Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/result.rs:1599:5
[2021-09-03T09:25:33.238Z]    3: core::result::Result<T,E>::unwrap
[2021-09-03T09:25:33.238Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/result.rs:1281:23
[2021-09-03T09:25:33.238Z]    4: failpoints::testsuite::new_event_feed::{{closure}}
[2021-09-03T09:25:33.238Z]              at /home/jenkins/tikv-src/components/cdc/tests/failpoints/../mod.rs:66:34
[2021-09-03T09:25:33.238Z]    5: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
[2021-09-03T09:25:33.238Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/alloc/src/boxed.rs:1586:9
[2021-09-03T09:25:33.238Z]    6: failpoints::test_resolve::test_joint_confchange::{{closure}}
[2021-09-03T09:25:33.238Z]              at /home/jenkins/tikv-src/components/cdc/tests/failpoints/test_resolve.rs:194:25
[2021-09-03T09:25:33.238Z]    7: failpoints::test_resolve::test_joint_confchange
[2021-09-03T09:25:33.238Z]              at /home/jenkins/tikv-src/components/cdc/tests/failpoints/test_resolve.rs:238:5
[2021-09-03T09:25:33.238Z]    8: failpoints::test_resolve::test_joint_confchange::{{closure}}
[2021-09-03T09:25:33.238Z]              at /home/jenkins/tikv-src/components/cdc/tests/failpoints/test_resolve.rs:184:1
[2021-09-03T09:25:33.238Z]    9: core::ops::function::FnOnce::call_once
[2021-09-03T09:25:33.238Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/ops/function.rs:227:5
[2021-09-03T09:25:33.238Z]   10: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}
[2021-09-03T09:25:33.238Z]              at /home/jenkins/tikv-src/components/test_util/src/runner.rs:64:21
[2021-09-03T09:25:33.238Z]   11: core::ops::function::FnOnce::call_once{{vtable.shim}}
[2021-09-03T09:25:33.238Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/ops/function.rs:227:5
[2021-09-03T09:25:33.238Z]   12: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
[2021-09-03T09:25:33.238Z]              at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/alloc/src/boxed.rs:1572:9
```

cc @hi-rustin #10695.

**Pull request merged**
