### PR TITLE
copr: chunk time use new 8 byte format

### PR DESCRIPTION
**Pull request by TennyZhuang**
Signed-off-by: TennyZhuang <zty0826@gmail.com>

###  What have you changed?

Use new 8 byte chunk time format.

###  What is the type of the changes?

- New feature (a change which adds functionality)
- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?

- Unit test

###  Refer to a related PR or issue link (optional)

Related to https://github.com/pingcap/tidb/pull/14278

### CODE REVIEW

**Comment by siddontang** [comment]
any benchmark for this?

**Comment by breeswish** [comment]
Added a DNM label since it must be merged together with https://github.com/pingcap/tidb/pull/14278

**Comment by TennyZhuang** [comment]
@sre-bot /run-integration-tests

**Comment by lonng** [comment]
@breeswish How to handle the rolling update?

**Comment by breeswish** [comment]
@lonng Our 3.0.x does not include Chunk format, so this change is fine.

**Comment by TennyZhuang** [comment]
@sre-bot /bench +sysbench +tpch tidb=pr/14278

**Comment by TennyZhuang** [comment]
@sre-bot /bench

**Comment by TennyZhuang** [comment]
@sre-bot /bench +tpch tidb=pr/14278

**Comment by TennyZhuang** [comment]
@sre-bot /bench +tpch tidb=pr/14278

**Comment by breeswish** [comment]
/bench +tpch tidb=pr/14278
```
workload:
  queries: 15.sql
  repeat_time: 5
```

**Comment by TennyZhuang** [comment]
@sre-bot /bench +tpch tidb=pr/14278
```
workload:
  queries: 15.sql
  repeat_time: 5
```

**Comment by breeswish** [comment]
/bench +tpch tidb=pr/14278
```
workload:
  queries: 15.sql
  repeat_time: 5
```

**Comment by breeswish** [comment]
/bench +tpch tidb=pr/14278
```
workload:
  queries: 15.sql
  repeat_time: 5
```

**Comment by TennyZhuang** [comment]
/bench +tpch tidb=pr/14278
```
workload:
  queries: 15.sql
  repeat_time: 5
```

**Comment by TennyZhuang** [comment]
@sre-bot /bench +tpch tidb=pr/14278
```
workload:
  queries: 15.sql
  repeat_time: 5
```

**Comment by TennyZhuang** [comment]
@sre-bot /bench +tpch tidb=pr/14278
```
workload:
  queries: 15.sql
  repeat_time: 5
```

**Comment by breeswish** [comment]
/bench +tpch tidb=pr/14278
```
workload:
  queries: 15.sql
  repeat_time: 5
```

**Comment by breeswish** [comment]
/bench +tpch tidb=pr/14278
```
workload:
  queries: 15.sql
  repeat_time: 5
```

**Comment by TennyZhuang** [comment]
@sre-bot /bench +tpch tidb=pr/14278

**Comment by TennyZhuang** [comment]
@sre-bot /bench +tpch tidb=pr/14278

**Comment by TennyZhuang** [comment]
@sre-bot /bench +tpch tidb=pr/14278
```
workload:
  queries: 15.sql
  repeat_time: 5
```

**Comment by TennyZhuang** [comment]
@sre-bot /bench +tpch tidb=pr/14278

**Comment by TennyZhuang** [comment]
@sre-bot /bench +tpch tidb=pr/14278
```
workload:
  queries: 15.sql
  repeat_time: 5
```

**Comment by you06** [comment]
/bench +tpch tidb=pr/14278
```
workload:
  queries: 15.sql
  repeat_time: 5
```

**Comment by TennyZhuang** [comment]
@sre-bot /bench +tpch tidb=pr/14278
```
workload:
  queries: 15.sql
  repeat_time: 5
```

**Comment by TennyZhuang** [comment]
@sre-bot /bench +tpch tidb=pr/14278
```
workload:
  queries: 15.sql
  repeat_time: 5
```

**Comment by TennyZhuang** [comment]
@sre-bot /bench +tpch tidb=pr/14278

**Comment by TennyZhuang** [comment]
@sre-bot /bench +tpch tidb=pr/14278
```
workload:
  queries: 16.sql
  repeat_time: 5
```

**Comment by TennyZhuang** [comment]
@sre-bot /bench +tpch tidb=pr/14278

workload:
  queries: 16.sql
  repeat_time: 5


pingcap-github-bot <notifications@github.com>于2020年1月27日 周一10:01写道：

**Comment by TennyZhuang** [comment]
/bench +tpch tidb=pr/14278
```
workload:
  queries: 16.sql
  repeat_time: 5
```

**Comment by TennyZhuang** [comment]
@sre-bot  /bench +tpch tidb=pr/14278
```
workload:
  queries: 16.sql
  repeat_time: 5
```

**Comment by TennyZhuang** [comment]
@sre-bot  /bench +tpch tidb=pr/14278
```
workload:
  queries: 16.sql
  repeat_time: 5
```

**Comment by TennyZhuang** [comment]
@sre-bot  /bench +tpch tidb=pr/14278
```
workload:
  queries: 19.sql
  repeat_time: 5
```

**Comment by you06** [comment]
/bench +tpch tidb=pr/14278
```
workload:
  queries: 19.sql
  repeat_time: 5
```

**Comment by TennyZhuang** [comment]
/bench +tpch tidb=pr/14278
```
workload:
  queries: 16.sql
  repeat_time: 10
```

**Comment by breeswish** [comment]
/bench +tpch tidb=pr/14278
```
workload:
  queries: 16.sql
  repeat_time: 10
```

**Comment by TennyZhuang** [comment]
/bench +tpch tidb=pr/14278
```
workload:
  queries: 06.sql
  repeat_time: 10
```

**Comment by TennyZhuang** [comment]
@sre-bot /bench +tpch tidb=pr/14278
```
workload:
  queries: 06.sql
  repeat_time: 10
```

**Pull request merged**
