### PR TITLE
test: fix check split bug in pd

### PR DESCRIPTION
**Pull request by gengliqi**
cherry-pick #7841 to release-4.0

---

Signed-off-by: Liqi Geng <gengliqiii@gmail.com>

### What problem does this PR solve?

Problem Summary:

Fix check split bug in pd.

### What is changed and how it works?

What's Changed:

It's possible that a left region has an old epoch so I remove the assert in `check_split`.
1. r1  => [0, 10)  r2 => [10, 20)
r1 merge to r2
2. r2 => [0, 20)
r2 split
3. r3 => [0, 10) r2 => [10, 20)
When r1 reports to PD again, the `check_split` will panic.

Move `test_node_merge_write_data_to_source_region_after_merging` test to failpoint test.
This is a mistake.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

Side effects

No.

### Release note 

* No release note

### CODE REVIEW

**Comment by Connor1996** [comment]
Please fix the conflict @gengliqi

**Comment by gengliqi** [comment]
> Please fix the conflict @gengliqi

Fixed

**Pull request merged**
