### PR TITLE
Derive Copy for Duration

### PR DESCRIPTION
**Pull request by breeswish**
Signed-off-by: Breezewish <breezewish@pingcap.com>

## What have you changed? (mandatory)

Duration is a simple structure, so let's derive Copy for it for better efficiency.

Extracted from [batch execution PR](https://github.com/tikv/tikv/pull/3898)

## What are the type of the changes? (mandatory)

- Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)

Existing unit tests.

## Does this PR affect documentation (docs) update? (mandatory)

No.

## Does this PR affect tidb-ansible update? (mandatory)

No.

## Refer to a related PR or issue link (optional)

https://github.com/tikv/tikv/pull/3898

### CODE REVIEW

**Comment by siddontang** [comment]
> for better efficiency.

Any benchmark to compare them?

**Comment by breeswish** [comment]
@siddontang I don't think it's notable for now, but it is very useful in chunk (since there will be just large bucket of memory copies instead of field by field)

**Pull request merged**
