### PR TITLE
raftstore: skip to inspect apply latency

### LINKED ISSUE #10744: When the business has a hot spot, one node is mistakenly detected as a slow node
## Bug Report

[root@copy-of-vm-ee-centos76-v1 bin]# ./tikv-server -V
TiKV
Release Version:   5.2.0
Edition:           Community
Git Commit Hash:   d1967b87e7c47c241931fe920965febb4c37ef7f
Git Commit Branch: heads/refs/tags/v5.2.0
UTC Build Time:    2021-08-14 02:02:01
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release

### What operating system and CPU are you using?
tiup ：
1PD
1TiDB
3TiKV
all node：500G NVME、4 cores、8G mem

### Steps to reproduce
1、run sysbench prepare
threads=128
tableNum = 512
tableSize = 10000000000
sysbench --config-file=/root/config oltp_point_select --tables=512 --table-size=10000000000 --auto_inc=true prepare
2、A few minutes later，one node is mistakenly detected as a slow node 

### What did you expect?
When the business has a hot spot, node should not be detected as a slow node，and leaders of the node is evicted

### What did happened?
When the business has a hot spot, one node is mistakenly detected as a slow node

### PR DESCRIPTION
**Pull request by 5kbpers**
Signed-off-by: 5kbpers <tangminghua@pingcap.com>

### What problem does this PR solve?

Issue Number: close #10744

Problem Summary:
For now, we have serval unaddressed known issues about apply worker:
* The scan operations could hold the db mutex of rocksdb for a long time. https://github.com/tikv/rocksdb/pull/250
* `apply log duration` and `apply wait duration` could be large under some workloads with hotpots

With these issues the durations related to apply worker will introduce some uncertainty to the slow store detection. And the performance of the durations related to store worker is relatively stable in our tests. So this PR skips to inspect the durations related to apply worker.

### What is changed and how it works?

What's Changed:
* Skip to inspect apply latency

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by 5kbpers** [comment]
Here are the result of my tests.

The slow score was increased from 1 to 100 in about 2min after limiting the disk bandwidth from 600MB/s to 400MB/s: 
image
image

And the slow score was increased from 1 to 100 in about 7min after limiting the cpu usages from 800% to 400%:
image
image

So it seems that this inspecting duration works well too under some extreme limitations.

**Review by yiwu-arbug — APPROVED** [review]
LGTM

**Review by hicqu — APPROVED** [review]

**Pull request merged**
