### PR TITLE
rocksdb: fix panic caused by ingest multiple files

### PR DESCRIPTION
**Pull request by Little-Wallace**
Signed-off-by: Little-Wallace <bupt2013211450@gmail.com>

### What problem does this PR solve?

Issue Number: close https://github.com/tikv/tikv/issues/10947

Problem Summary:
TiKV will panic after ingest two sst files in once call. Because these two files are both in L0.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

### Related changes

- PR to update `tikv/rocksdb`: https://github.com/tikv/rocksdb/pull/257

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
Fix rocksdb panic after ingesting two files in once call.
```

### CODE REVIEW

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by Little-Wallace** [comment]
I check the code again and find that this bug will not occur when the binary tikv-server  is compile in release mode.

**Review by hunterlxt — APPROVED** [review]

**Pull request merged**
