### PR TITLE
causal-ts: rename `available-interval` to `alloc-ahead-buffer`

### LINKED ISSUE #13596: rawkv: Refine the name of config item "causal-ts.available-interval"
### Is your feature request related to a problem? Please describe:

The config item `causal-ts.available-interval` is not easy to be understood, as the word "available" has a wide meaning.
Besides, the "interval" is not accurate, as it's often used for periodic time.

### Describe the feature you'd like:

Change to `causal-ts.alloc-ahead-buffer`, which accurately describes the behavior that this item is controlling.

### PR DESCRIPTION
**Pull request by pingyu**
Issue Number: #13596

Signed-off-by: pingyu <yuping@pingcap.com>

### What is changed and how it works?

Issue Number: Close #13596 

What's Changed:

```commit-message
Rename `causal-ts.available-interval` to `causal-ts.alloc-ahead-buffer` for more clear meaning.
```

### Related changes

- No

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- No

### Release note 

```release-note
Rename `causal-ts.available-interval` to `causal-ts.alloc-ahead-buffer` for more clear meaning.
```

### CODE REVIEW

**Comment by pingyu** [comment]
> /cc @haojinming @zeminzhou

PTAL, thanks~

**Review by haojinming — APPROVED** [review]
LGTM

**Review by zeminzhou — APPROVED** [review]
LGTM~

**Review by iosmanthus — APPROVED** [review]
LGTM

**Pull request merged**
