### PR TITLE
raftstore: speed up conf change (#6421)

### PR DESCRIPTION
**Pull request by BusyJay**
#  What have you changed?

Cherry pick #6421.

###  What is the type of the changes?

- Bugfix

###  How is the PR tested?

- Unit test
- Integration test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?
No

###  Does this PR affect `tidb-ansible`?
No.

###  Refer to a related PR or issue link (optional)

#6421, #6420.

### CODE REVIEW

**Comment by BusyJay** [comment]
Note that snapshot task does not change for release-3.0 as it's checked before detecting ready already.

**Comment by youjiali1995** [comment]
> /run-all-tests

It will take about 20+min to build the tikv in integration-common-test. Please don't run it again...

**Pull request merged**
