### PR TITLE
tests: Fix flaky test_raw_put_key_guard

### LINKED ISSUE #16825: [flay test] test_rawkv::test_raw_put_key_guard
### What version of TiKV are you using?

master (b1715ea3070d1d0dc8a81e1cd8b5ce13b8129ee3)

### What operating system and CPU are you using?

AMD64

### Steps to reproduce

```
❯ ./scripts/env cargo test -p tests --test failpoints test_rawkv -- --nocapture
```

### What did you expect?

Test succeed.

### What did happened?

Test failed:

```
❯ ./scripts/env cargo test -p tests --test failpoints test_rawkv -- --nocapture
    Finished test [unoptimized] target(s) in 0.65s
warning: the following packages contain code that will be rejected by a future version of Rust: criterion v0.3.5, nom v2.2.1, nom v4.2.3, nom v5.1.0, quick-xml v0.22.0
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 3`
     Running failpoints/mod.rs (target/debug/deps/failpoints-04222e95374eb0c8)

running 3 tests
test cases::test_rawkv::test_leader_transfer ... ok
thread 'cases::test_rawkv::test_raw_put_key_guard' panicked at tests/failpoints/cases/test_rawkv.rs:318:23:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test cases::test_rawkv::test_raw_put_key_guard ... FAILED
test cases::test_rawkv::test_region_merge ... ok

failures:

failures:
    cases::test_rawkv::test_raw_put_key_guard

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 365 filtered out; finished in 9.00s

error: test failed, to rerun pass `-p tests --test failpoints`
make: *** [scripts/../Makefile:317: run] Error 101
❯
```

### PR DESCRIPTION
**Pull request by pingyu**
### What is changed and how it works?

Issue Number: Close #16825

What's Changed:

```commit-message
Fix flaky test_raw_put_key_guard.
```

The issue is caused by peer `0` would not be the leader of region.

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by pingyu** [comment]
> /cc @tonyxuqqi @haojinming

PTAL, thanks~

**Review by haojinming — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Review by tonyxuqqi — APPROVED** [review]

**Pull request merged**
