### PR TITLE
copr: implement macro match_template_collator

### PR DESCRIPTION
**Pull request by andylokandy**
Signed-off-by: Dian Luo <andylokandy@hotmail.com>

###  What have you changed?

1. Add a new pattern to proc macro `match_template`.

For example,

```rust
match_template! {
    T = [Foo, Bar => Baz],
    match Foo {
        EvalType::T => { panic!("{}", EvalType::T); },
    }
}
```

 generates

```rust
match Foo {
    EvalType::Foo => { panic!("{}", EvalType::Foo); },
    EvalType::Bar => { panic!("{}", EvalType::Baz); },
}
```

2. Add a new decl macro `match_template_collator!()` which maps collation variant to
a concrete `Collator` type, and it's used as

```rust
fn map_string_compare_sig<Cmp: CmpOp>(ret_field_type: &FieldType) -> RpnFnMeta {
    match_template_collator! {
        TT, match ret_field_type.as_accessor().collation() {
            Collation::TT => compare_fn_meta::<StringComparer<TT, Cmp>>()
        }
    }
}
```

3. For consistency, make `match_template_evaluable!()` and `match_template_hashable!()` decl macro 2.0 also.

###  What is the type of the changes?

- Engineering (engineering change which doesn't change any feature or fix any issue)

###  How is the PR tested?

- Unit test
- Integration test

### CODE REVIEW

**Comment by TennyZhuang** [comment]
Please resolve the conflict, and it's better if you'd like to update `map_string_compare_sig` to use the macro.

**Comment by andylokandy** [comment]
> Please resolve the conflict, and it's better if you'd like to update `map_like_sig` to use the macro.

It worth rewriting the `map_like_sig`; we can do it in other PR.

**Comment by TennyZhuang** [comment]
@sre-bot /approve

**Pull request merged**
