### PR TITLE
copr: add non-vectorized/vectorized findInSet

### PR DESCRIPTION
**Pull request by MaiCw4J**
Signed-off-by: mcw <610546069@qq.com>

PCP #5751 
###  What have you changed?

Add non-vectorized/vectorized FindInSet

###  What is the type of the changes?

Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?
Please select the tests that you ran to verify your changes:
- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No. It should not change the behavior.

###  Does this PR affect `tidb-ansible`?

No

### CODE REVIEW

**Comment by MaiCw4J** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/118

**Comment by AndreMouche** [comment]
@NingLin-P @iosmanthus PTAL and the next deadline for reviewing is 2020-02-20 24:00:00

**Pull request merged**
