### PR TITLE
copr: fix the calculation of total column size in analyze

### PR DESCRIPTION
**Pull request by xuyifangreeneyes**
Signed-off-by: xuyifangreeneyes xuyifangreeneyes@gmail.com

### What is changed and how it works?

Ref https://github.com/pingcap/tidb/issues/31744

What's Changed:

When adding column size to total_size in analyze, we need to minus 1 for the flag byte.

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by skyzh — APPROVED** [review]

**Review by sticnarf — APPROVED** [review]

**Comment by sticnarf** [comment]
Hi @xuyifangreeneyes, please sign off your commits to pass the DCO check.

**Comment by xuyifangreeneyes** [comment]
> Hi @xuyifangreeneyes, please sign off your commits to pass the DCO check.

I signed off the commit. PTAL @sticnarf

**Pull request merged**
