### PR TITLE
*: fix some typos

### PR DESCRIPTION
**Pull request by JmPotato**
### What is changed and how it works?

Issue Number: ref #5456.

What's Changed:

```commit-message
Fix some typos.
```

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
None.
```

### CODE REVIEW

**Review by nolouch — APPROVED** [review]

**Review by overvenus — APPROVED** [review]

**Comment by JmPotato** [comment]
@overvenus Could you please help leave a /merge?

**Review by Connor1996 — APPROVED** [review]

**Pull request merged**
