### PR TITLE
*: move raftkv from storage to server

### PR DESCRIPTION
**Pull request by siddontang**
Signed-off-by: siddontang <siddontang@gmail.com>

## What have you changed? (mandatory)

Move Raftkv from backend storage module to upper Server module. 
Later we will move whole storage to the standalone component, so it can't contain any Raftstore logic. 

Now I just move Raftkv to server module, maybe later I will refactor the server module to let server module use different KV engine, not only RaftKV. 

## What are the type of the changes? (mandatory)

- Engineering (engineering change which doesn't change any feature or fix any issue)

## How has this PR been tested? (mandatory)

Passing compiling and CI is fine.

## Does this PR affect documentation (docs) or release note? (mandatory)

No
## Does this PR affect tidb-ansible update? (mandatory)

No

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
But i think raftkv is a kind of storage.

**Comment by siddontang** [comment]
it just implements the Storage trait, and it is designed for Raft. So it is not proper to be put in the storage module. We need to move it to the upper module, not in the base storage.

**Comment by siddontang** [comment]
or what better place do you think we can move to?

IMO, the server is fine because it combines all together.

/cc @BusyJay

**Comment by siddontang** [comment]
Ping @zhangjinpeng1987

**Pull request merged**
