### PR TITLE
clippy: Fixing up clippy errors.

### PR DESCRIPTION
**Pull request by hdost**
ref #4301

Signed-off-by: Harold Dost <harolddost@gmail.com>

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by sticnarf** [comment]
Thanks you for contribution!

Could you please try adding `-D rust-2018-idioms` to `scripts/clippy` after fixing all the warnings? After that you can run `make clippy` locally to confirm it.

**Comment by hdost** [comment]
@sticnarf so this PR is probably blocked until: https://github.com/tikv/tikv/blob/28292ee1f3810c9e00127d59ddb7d73fe3ca02cf/components/tidb_query_codegen/src/rpn_function.rs#L202 This is fixed unless we either
A: disable the elision requirement on all functions with the rpn_fn attribute
B: disable the ellision requirement on all Cargo.toml with above functions.
C: wait for all of this until rpn_fn is fixed. (I can try my hand at it, but I'm still relatively novice when it comes to rust codegen)

**Comment by sticnarf** [comment]
> @sticnarf so this PR is probably blocked until:
> 
> https://github.com/tikv/tikv/blob/28292ee1f3810c9e00127d59ddb7d73fe3ca02cf/components/tidb_query_codegen/src/rpn_function.rs#L202
> 
> This is fixed unless we either
> A: disable the elision requirement on all functions with the rpn_fn attribute
> B: disable the ellision requirement on all Cargo.toml with above functions.
> C: wait for all of this until rpn_fn is fixed. (I can try my hand at it, but I'm still relatively novice when it comes to rust codegen)

Umm, the ideal way should be fixing the `rpn_fn` proc macro. But it might be too much work for this PR.

We can add `#![allow(elided_lifetimes_in_paths)]` to `components/tidb_query_expr/src/lib.rs` at this time. Then, we can fix the elided lifetime issue later.

PS: Please sign off your commits to pass the DCO check :)

**Comment by hdost** [comment]
> We can add `#![allow(elided_lifetimes_in_paths)]` to `components/tidb_query_expr/src/lib.rs` at this time. Then, we can fix the elided lifetime issue later.

Sounds good, and I'll open a separate ticket about alloing `rpn_fn` to accept functions with lifetimes.

> 
> PS: Please sign off your commits to pass the DCO check :)

Yup 👍🏼 just figured I would worry about that after I had an action plan 😄

**Comment by hdost** [comment]
Just waiting on the check at this point :)

**Comment by hdost** [comment]
@sticnarf There seems to be an issue with the build process :/

**Review by sticnarf — APPROVED** [review]
LGTM. Thanks very much!

**Review by 5kbpers — APPROVED** [review]
LGTM, thanks for your contribution!

**Pull request merged**
