### PR TITLE
Improve TiKV metrics performance for tidb_query&engine_rocks

### PR DESCRIPTION
**Pull request by Renkai**
### What problem does this PR solve?

Issue Number: part of https://github.com/tikv/tikv/issues/5708

Problem Summary:
Improve some metrics performance

### What is changed and how it works?
remove `with_label_values` and use local thread storage

### Related changes

- None

### Check List 

Tests 

- Unit test
Side effects
- Improve performance

### Release note

### CODE REVIEW

**Comment by Renkai** [comment]
@sre-bot /run-all-tests

**Comment by Renkai** [comment]
@sre-bot /release make dist_release

**Comment by Renkai** [comment]
@sre-bot /bench +sysbench +tpcc +tpch

**Comment by Renkai** [comment]
@sre-bot /run-all-tests

**Comment by siddontang** [comment]
TPC-H duration increased

PTAL @breeswish

**Pull request merged**
