### PR TITLE
copr: fix neg sign when decimal divide to zero

### PR DESCRIPTION
**Pull request by lzmhhh123**
Signed-off-by: lzmhhh123 <lzmhhh123@gmail.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/29586

### What is changed and how it works?

What's Changed: when decimal divide decimal to ZERO result, the negative signature should be set to false in case comparing it with zero.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
fix negative sign when decimal divide to zero
```

### CODE REVIEW

**Comment by ichn-hu** [comment]
shall we add some tests for this?

**Review by wshwsh12 — APPROVED** [review]
LGTM

**Review by ichn-hu — APPROVED** [review]
LGTM

**Review by guo-shaoge — APPROVED** [review]

**Review by breeswish — APPROVED** [review]

**Comment by zhouqiang-cl** [comment]
@ti-chi-bot

**Pull request merged**
