### PR TITLE
server: remove the limit about received message size

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

## What have you changed? (mandatory)
Remove the limit about received message size, because we meet some use cases that TiDB will send large messages.

### CODE REVIEW

**Comment by lysu** [comment]
@hicqu, tidb's limit has been removed

**Comment by overvenus** [comment]
Can we merge it? Should it be cherry-picking to release-3.0?

**Comment by hicqu** [comment]
@overvenus it's better to cherry pick into release 3.0.

**Comment by lysu** [comment]
@hicqu hi, does this cherryp-pick to 3.0?

**Comment by lysu** [comment]
@hicqu hi please help cherry-pick this to 3.0, some customer meet this question again

**Pull request merged**
