### PR TITLE
enable GC in compaction filter by default

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve?

enable GC in compaction filter by default.

### Check List 

Tests 

- No code

Side effects

### Release note 
* No release note.

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
Please update release notes.

**Review by yiwu-arbug — APPROVED** [review]

**Review by youjiali1995 — APPROVED** [review]

**Pull request merged**
