### PR TITLE
Set max-message-size to i32::MAX.

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

## What have you changed? (mandatory)
Change the max-grpc-message-size to i32::MAX.

The old configuration is:
```rust
builder.max_send_message_len(cmp::max(region_split_size * 4, i32::MAX as usize) as i32)
```
The **cmp::max** should be **cmp::min** in fact, so it's a bug. However, set it to `i32::MAX` maybe is more better because if the region doesn't split as expected, and its size grows vary large, a gRPC error will be raised.

So this PR changes it to `i32::MAX`. So we won't meet the error any more. 

## What are the type of the changes? (mandatory)
Bug fix.

## How has this PR been tested? (mandatory)
make dev.

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)
No.

## Does this PR affect tidb-ansible update? (mandatory)
No.

### CODE REVIEW

**Comment by breeswish** [comment]
How about just using -1 which means unlimited?

**Comment by hicqu** [comment]
@breeswish you mean `-1` means unlimited in `gRPC`? If so, it's better.

**Comment by breeswish** [comment]
@hicqu Yes, I was referring to the doc: https://docs.rs/grpcio/0.3.0/grpcio/struct.ChannelBuilder.html#method.max_send_message_len

**Comment by hicqu** [comment]
In extreme case a message will eat 2G memory. It could only happend on larget region. So it can make the cluster more stable in cases that regions don't split as expected.

**Pull request merged**
