### PR TITLE
metrics: grafana dashboards support multiple cluster

### PR DESCRIPTION
**Pull request by zjj2wry**
### What problem does this PR solve?

Many users(come from DBaaS、operator、tiup) monitor multiple TiDB clusters in one Grafana, this PR make Grafana dashboards support multiple clusters and not affect single cluster usage. Cluster variable is hidden by default.

### What is changed and how it works?

- add a tidb_cluster label in all expr
- add cluster variable in Grafana templating

How it Works:
load it to your Grafana :))

Single Cluster:
No change

Multiple Cluster:
Construct a label that can uniquely identify the cluster. in tidb_operator, you can use {namespace}-{cluster_name} as your {tidb_cluster} variable.
add this configuration to your prometheus config
```
relabel_configs:
  - source_labels:
      - namespace
      - name
    separator: "-"
    target_label: tidb_cluster
```

### Related changes

- https://github.com/pingcap/tidb/pull/22503/files

### Check List 

Tests 

- No code

Side effects

- No effects

###  Release note

- metrics: grafana dashboards support multiple clusters

### CODE REVIEW

**Review by breeswish — APPROVED** [review]

**Comment by zjj2wry** [comment]
https://github.com/pingcap/tidb/pull/22534

**Pull request merged**
