### PR TITLE
raft: temporarily use raft-rs master branch

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

## What have you changed? (mandatory)
Use raft-rs master branch to include some bug fixes:
* https://github.com/pingcap/raft-rs/pull/269, a bug fix about learner
* https://github.com/pingcap/raft-rs/pull/270, to fix the bug about no raft-rs logs

### CODE REVIEW

**Comment by siddontang** [comment]
why temporarily use?

**Comment by hicqu** [comment]
@siddontang after new version of raft-rs is published, we can switch the dependency to crates-io.

**Comment by overvenus** [comment]
Does it need to be cherry-picked to release-3.0?

**Comment by hicqu** [comment]
@overvenus 2 bugs are only in master branch, because release-3.0 doesn't use raft-rs master branch.

**Pull request merged**
