### PR TITLE
Fix gRPC request source duration inaccurate issue

### LINKED ISSUE #17133: TiDB Grafana gRPC request source duration is inaccurate
### What version of TiKV are you using?

v8.0.0 ~
### Steps to reproduce

Deploy a new cluster and check the gRPC request source duration metrics.

### What did you expect?
image

### What did happened?
image

### PR DESCRIPTION
**Pull request by King-Dylan**
### What is changed and how it works?

Issue Number: Close #17133

What's Changed:

```
Yaxes left_format UNITS should be microseconds rather than seconds.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by zhangjinpeng87 — APPROVED** [review]
LGTM

**Comment by glorv** [comment]
@King-Dylan  Please run `scripts/gen-tikv-details-dashboard` to update grafana config.

**Review by glorv — APPROVED** [review]

**Review by Connor1996 — APPROVED** [review]

**Comment by glorv** [comment]
@King-Dylan Please fix the conflict, thanks~

**Comment by zhangjinpeng87** [comment]
@King-Dylan Please fix the conflict.

**Pull request merged**
