### PR TITLE
[DNM] txn: parallel commit

### PR DESCRIPTION
**Pull request by youjiali1995**
###  What have you changed?
Only for test. Corresponding TiDB PR: https://github.com/pingcap/tidb/pull/13838.

### CODE REVIEW

**Comment by youjiali1995** [comment]
/bench
```
workload:
  threads: 1024
```

**Comment by siddontang** [comment]
@youjiali1995 

seems using 1024 threads doesn't gain improvement.

**Comment by youjiali1995** [comment]
> @youjiali1995
> 
> seems using 1024 threads doesn't gain improvement.

It should have some improvements in latency and it can't improve the max QPS because it's still 2PC. 
I forgot to bench with the corresponding TiDB PR.

**Comment by youjiali1995** [comment]
/bench tidb=pr/13838
```
workload:
  threads: 1024
```

**Comment by youjiali1995** [comment]
/bench tidb=pr/13838
```
workload:
  threads: 512
```

**Comment by youjiali1995** [comment]
/bench tidb=pr/13838
```
workload:
  threads: 256
```

**Pull request closed without merging**
