### PR TITLE
Components/concurrency-manager: Remove stale comments

### PR DESCRIPTION
**Pull request by mapleFU**
### What problem does this PR solve?

Problem Summary:

### What is changed and how it works?

Remove stale comments. Since after #8608, `LockTable` is already a concurrency ordered structure. And it's no longer a `BtreeMap`.

### Related changes

#8608

### Check List 

No code

Side effects

None

### Release note 

* No release note

### CODE REVIEW

**Review by youjiali1995 — APPROVED** [review]

**Comment by mapleFU** [comment]
emm...Seems that the Raft Unittest failed..

**Pull request merged**
