### PR TITLE
Remove TODO of create_key_file

### PR DESCRIPTION
**Pull request by hi-rustin**
Signed-off-by: hi-rustin <rustin.liu@gmail.com>

### What problem does this PR solve?

Issue Number: None
Problem Summary:

### What is changed and how it works?

Remove todo.

What's Changed:

### Related changes

None

### Check List 

Tests 

- Unit test

Side effects

None

### Release note 
- No release note

### CODE REVIEW

**Review by yiwu-arbug — APPROVED** [review]

**Review by hunterlxt — APPROVED** [review]

**Comment by hi-rustin** [comment]
/merge cancel

Waiting for the CI fixed.

**Comment by hi-rustin** [comment]
/merge cancel

Waiting for the CI fixed.

**Pull request merged**
