### PR TITLE
fix backward compatibility in load base split config (#9820)

### LINKED ISSUE #9816: Tiup upgrade failed because of config-check failure
### What version of TiKV are you using?

nightly

### Steps to reproduce

1. deploy a v5.0.0-rc cluster with following config
  ```
  [split]
  size-threshold = 1
  ```
2. run command `tiup cluster upgrade xxx nightly` 

### What did you expect?

Upgrade succeed.

### What did happened?

Upgrade failed.

```
Error: init config failed: 10.0.2.128:20160: executor.ssh.execute_failed: Failed to execute command over SSH for 'root@10.0.2.128:22' {ssh_stderr: unknown configuration options: split.size-thre
shold
, ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/usr/bin:/usr/sbin /disk1/deploy/tikv-20160/bin/tikv-server --config-check --config=/disk1/deploy/tikv-20160/conf/tikv.toml --pd=""}, caus
e: Process exited with status 1: check config failed

Verbose debug logs has been written to /root/.tiup/logs/tiup-cluster-debug-2021-03-16-00-22-32.log.
Error: run `/root/.tiup/components/cluster/v1.3.5/tiup-cluster` (wd:/root/.tiup/data/SRkESQU) failed: exit status 1
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #9820 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/9829
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/9829:release-5.0-a061186b9093
```

---

Signed-off-by: lhy1024 <admin@liudos.us>

### What problem does this PR solve?

Issue Number: close #9816

Problem Summary:
#9794 breaks backward compatibility. This PR will fix it.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
image

### Release note 
- No Release note

### CODE REVIEW

**Comment by cosven** [comment]
Deploy a tiup cluster with following topology and upgrade it to nightly.
```[root@f6920b48167d ~]# cat topology.yaml
...
server_configs:
  tidb: {}
  tikv:
    split.detect-times: 2
    split.qps-threshold: 500
    split.sample-num: 500
    split.size-threshold: 1
...
```

The upgrade operation susseed
```
Restarting component tidb
        Restarting instance 10.0.2.169
        Restart 10.0.2.169 success
Restarting component prometheus
        Restarting instance 10.0.2.167
        Restart 10.0.2.167 success
Restarting component grafana
        Restarting instance 10.0.2.167
        Restart 10.0.2.167 success
Upgraded cluster `st--issue-22963` successfully
```

**Review by HunDunDM — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]

**Pull request merged**
