### PR TITLE
json, copr: implement unary not for json

### LINKED ISSUE #14069: Implement unary not json
## Development Task

`UnaryNotJson` is currently implemented by casting json to double, and unary not double. However, it's not correct. I'll add a new `UnaryNotJSON` and implement it in both TiKV and TiDB.

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### What is changed and how it works?

Issue Number: Close #14069

What's Changed:

Implement the `UnaryNotJSON` defined in https://github.com/pingcap/tipb/pull/289

Related TiDB Implementation: https://github.com/pingcap/tidb/pull/40723

### Check List 

Tests 

- [x] Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### Release note 

```release-note
Fix the issue that unary not for json value is incompatible with MySQL.
```

### CODE REVIEW

**Comment by YangKeao** [comment]
Please help to cherry pick to 6.5 and 6.1? I cannot add the label :thinking:

**Review by sticnarf — APPROVED** [review]
LGTM

**Review by youjiali1995 — APPROVED** [review]

**Pull request merged**
