### PR TITLE
Disable unused features of dependencies

### PR DESCRIPTION
**Pull request by psinghal20**
## What have you changed? (mandatory)
It disables the unused features of the dependencies to reduce the build time(#4167). You can take a look at the Feature set using [cargo-feature-analyst](https://github.com/psinghal20/cargo-feature-analyst).

The PR is still WIP. Currently, unused features of only direct dependencies have been disabled. Further work to disable unused features for dependencies deeper in the dependency tree is required.

### Features disabled:
    
    Format
    (Crate Name)-(version)/(Feature Name) [Crates enabling this feature]

    backtrace-0.2.3/backtrace-sys ["tikv"]
    backtrace-0.2.3/dbghelp ["tikv"]
    backtrace-0.2.3/dbghelp-sys ["tikv"]
    backtrace-0.2.3/default ["tikv"]
    backtrace-0.2.3/dladdr ["tikv"]
    backtrace-0.2.3/kernel32-sys ["tikv"]
    backtrace-0.2.3/libbacktrace ["tikv"]
    backtrace-0.2.3/libunwind ["tikv"]
    backtrace-0.2.3/winapi ["tikv"]
    criterion-0.2.5/criterion-plot ["tikv"]
    criterion-0.2.5/default ["tikv"]
    criterion-0.2.5/handlebars ["tikv"]
    criterion-0.2.5/html_reports ["tikv"]
    hyper-0.12.18/__internal_flaky_tests ["tikv"]
    hyper-0.12.18/default ["tikv"]
    jemalloc-sys-0.1.8/bg_thread ["jemallocator"]
    jemallocator-0.1.9/bg_thread ["tikv_alloc"]
    jemallocator-0.1.9/default ["tikv_alloc"]
    num-0.2.0/default ["tikv"]
    num-0.2.0/num-bigint ["tikv"]
    num-0.2.0/num-complex ["tikv"]
    num-0.2.0/num-integer ["tikv"]
    num-0.2.0/num-iter ["tikv"]
    num-0.2.0/num-rational ["tikv"]
    num-0.2.0/num-traits ["tikv"]
    num-0.2.0/std ["tikv"]
    num-bigint-0.2.0/num-integer ["num", "num-rational"]
    num-bigint-0.2.0/num-traits ["num", "num-rational"]
    num-bigint-0.2.0/std ["num", "num-rational"]
    num-complex-0.2.0/num-traits ["num"]
    num-complex-0.2.0/std ["num"]
    num-integer-0.1.39/num-traits ["chrono", "num", "num-iter", "num-bigint", "num-rational"]
    num-integer-0.1.39/std ["chrono", "num", "num-iter", "num-bigint", "num-rational"]
    num-iter-0.1.37/num-integer ["num"]
    num-iter-0.1.37/num-traits ["num"]
    num-iter-0.1.37/std ["num"]
    num-rational-0.2.1/bigint ["num"]
    num-rational-0.2.1/num-bigint ["num"]
    num-rational-0.2.1/num-integer ["num"]
    num-rational-0.2.1/num-traits ["num"]
    num-rational-0.2.1/std ["num"]
    prometheus-static-metric-0.1.4/default ["tikv"]
    safemem-0.3.0/default ["tikv"]
    safemem-0.3.0/std ["tikv"]
    slog-async-2.3.0/default ["tikv"]

## What are the type of the changes? (mandatory)
Misc changes

## How has this PR been tested? (mandatory)
This PR is tested with `cargo check`. Due to my system limitations, I am relying on the CI tests for further testing.

## Does this PR affect documentation (docs) update? (mandatory)
No

## Does this PR affect tidb-ansible update? (mandatory)
No, I don't think so.

## Refer to a related PR or issue link (optional)
Refer to issue #4167

### CODE REVIEW

**Comment by psinghal20** [comment]
@brson Here are the initial features I could disable for TiKV's direct dependencies. Please take a look when possible. Thanks!

**Comment by siddontang** [comment]
cool work @psinghal20 

PTAL @brson

**Comment by brson** [comment]
Wow this is quite enlightening @psinghal20 ! I didn't expect to find so many features to disable.

Something we need to be careful about is disabling "silent" features. That is, features that aren't invoked directly, and that won't break the build when removed.

There are two on here that worry me: all the backtrace features, and the jemallocator bg_threads feature.

The backtrace features are all implementation details and aren't touched directly by client code. Turning off the default features will make backtraces not work.

The bg_threads feature causes jemalloc to use a thread for space reclamation. It's on today, so disabling it will change the allocator's performance characteristics, which we don't want to do in this PR.

There's also some risk that this breaks the build on non-linux platforms. Since there's no CI for those platforms I'm pretty fine with landing it and letting others fix the fallout.

I don't think you need to attempt to disable features that are enabled by tikv's dependencies for this PR. That's a harder task and could take a while.

Do you mind doing some compile-time benchmarking before and after your patch? Just run the following commands before and after:

```
# full rebuild
cargo clean && time cargo build --release
# partial rebuild
cargo clean && cargo build --release && echo >> src/lib.rs && time cargo build --release
```

And please add back the backtrace default feature and the bg_threads feature.

Great stuff. Thanks!

**Comment by psinghal20** [comment]
Hi @brson, I have enabled the backtrace and jemallocator features. Also, I ran the benchmarks and here is the output:
```
# full rebuild
# before patch:
cargo build --release  4327.60s user 247.25s system 79% cpu 1:36:08.21 total
# after patch:
cargo build --release > after_patch_benchmark  4324.21s user 158.96s system 189% cpu 39:21.18 total

# partial rebuild
# cargo clean && cargo build --release && echo >> src/lib.rs && time cargo build --release

# Before patch:
cargo build --release  1229.97s user 41.63s system 45% cpu 46:33.09 total
# After patch
cargo build --release  1254.69s user 30.00s system 72% cpu 29:39.45 total
```

**Comment by brson** [comment]
It looks like there was noise during your benchmarking. I did a run here:

```
before full
    Finished release [optimized + debuginfo] target(s) in 25m 11s
before partial
    Finished release [optimized + debuginfo] target(s) in 14m 27s
after full
    Finished release [optimized + debuginfo] target(s) in 25m 11s
after partial
    Finished release [optimized + debuginfo] target(s) in 14m 24s
```

It looks like removing these features had negligible impact :)

So the PR looks good now, but we need to think about whether it should land if it doesn't affect compile times.

Here are some reasons to land it:

- tikv will be a usable library eventually, and it's a good practice for libraries to disable features they don't use
- the maintenance burden is low
- @psinghal20 has put in quite a lot of work

Some reasons not:

- doesn't improve compile time
- increases maintenance burden because contributors need to understand why so many deps have their default features off, and _should_ do so for future deps

@siddontang what do you think?

**Comment by siddontang** [comment]
I prefer going on because I think it is a good habit that don’t introduce unnecessary features.

for every new lib added later, we should also pay attention to it, this may be a problem but I think we can handle it😎

**Comment by brson** [comment]
@psinghal20 the signoff is missing from some commits here. Please add that. You can do so with something like `git commit -a --amend --no-edit -s` (the `-s` flag), perhaps in combination with interactive rebase.

**Comment by siddontang** [comment]
Friendly ping @psinghal20

**Comment by psinghal20** [comment]
Hi! Sorry for the late reply. I have signed the last commit and rebased my branch with master.

Other than that, I feel we should disable unused features. Working on this PR, made me realize how difficult it is to remove an unused feature dependency once it gets out in the world as a crate. 

I am still new to rust and don't quite understand how the features are compiled by the rust compiler but my initial thinking was due to conditional compilation we can reduce the amount of code being compiled by disabling unused features. Am I correct? 

If yes, then is the amount of code being disabled such an insignificant amount that there are no visible improvements?

**Comment by siddontang** [comment]
PTAL @brson, @BusyJay

**Comment by siddontang** [comment]
@psinghal20 

please fix the conflict.

**Comment by brson** [comment]
I've merged with master again. Let's get this landed.

**Comment by AndreMouche** [comment]
@BusyJay PTAL, thanks

**Comment by brson** [comment]
> I am still new to rust and don't quite understand how the features are compiled by the rust compiler but my initial thinking was due to conditional compilation we can reduce the amount of code being compiled by disabling unused features. Am I correct?

Yes.

> If yes, then is the amount of code being disabled such an insignificant amount that there are no visible improvements?

I believe so, sadly. It was a worthwhile exercise still.

**Comment by brson** [comment]
Thanks for the great work, and the long wait to land @psinghal20 !

**Pull request merged**
