### PR TITLE
raftstore: make slowscore accurate

### PR DESCRIPTION
**Pull request by JayiceZ**
refer https://github.com/tikv/tikv/issues/12254
Signed-off-by: Jayice <1185430411@qq.com>

### What is changed and how it works?

Issue Number: ref https://github.com/tikv/tikv/issues/12254

What's Changed:

```
make slowscore accurate in corner case.
```

### Check List 

Tests 

- Unit test

### Release note 

```release-note
none
```

### CODE REVIEW

**Review by 5kbpers — APPROVED** [review]
LGTM, thank you!

**Review by gengliqi — APPROVED** [review]

**Pull request merged**
