### PR TITLE
raftstore: fix a bug where snapshot file is not deleted in time

### LINKED ISSUE #16976: Raft snapshot file is not deleted if the leader fails to send it out
## Bug Report
There is a minor bug where the raft snapshot file is not deleted if the leader fails to send it out. I'll link a PR with an integration test that will demonstrate this.

### PR DESCRIPTION
**Pull request by hbisheng**
### What is changed and how it works?
Issue Number: Close #16976

What's Changed:

```commit-message
The issue is that if a leader fails to send a snapshot, it doesn't delete the 
snapshot file which may accumulate and waste disk space. The idle snapshot 
files will eventually be GCed, but that might take hours. The commit ensures 
that the snapshot file is also deleted on the error path. A new integration 
test was added which would fail without the fix. 
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by SpadeA-Tang** [comment]
Do we have any situations that a snapshot is reused? @Connor1996

**Comment by Connor1996** [comment]
> Do we have any situations that a snapshot is reused? @Connor1996

Seems no

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by SpadeA-Tang — APPROVED** [review]

**Pull request merged**
