### PR TITLE
bump master version to v6.4.0-alpha

### PR DESCRIPTION
**Pull request by lijie0123**
Signed-off-by: lijie <lijie@pingcap.com>

Issue Number: close https://github.com/tikv/tikv/issues/13563

### What is changed and how it works?

What's Changed: 

```commit-message
bump master version to v6.4.0-alpha
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

Side effects

### Release note 

```release-note
Please add a release note.

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with None.
If this PR will be picked to release branch, then a release note is probably required.
```

### CODE REVIEW

**Review by purelind — APPROVED** [review]
LGTM

**Review by sticnarf — APPROVED** [review]

**Comment by sticnarf** [comment]
Please also update the version in the PR description

**Comment by purelind** [comment]
> Please also update the version in the PR description

update

**Pull request merged**
