### PR TITLE
add lockless raft client implement

### PR DESCRIPTION
**Pull request by BusyJay**
###  What have you changed?

Add a new raft client implement that avoids lock most of the time.

###  What is the type of the changes?

- New feature

###  How is the PR tested?

- Integration test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No.

###  Does this PR affect `tidb-ansible`?

No.

###  Refer to a related PR or issue link (optional)

#6227

### CODE REVIEW

**Comment by siddontang** [comment]
@zhouqiang-cl 

do we support YCSB raw mod in benchbot?

**Comment by siddontang** [comment]
@BusyJay 

seem our Benchbot only uses one TiKV, so why the performance increased?

**Comment by mahjonp** [comment]
> seem our Benchbot only uses one TiKV, so why the performance increased?

We use four TiKV instances in this YCSB workload, and we support tikv raw benching.

**Comment by mahjonp** [comment]
/bench +ycsb
```
workload:
  workload: workloada
  mode: raw
```

**Comment by BusyJay** [comment]
What's the difference between raw and non-raw mode?

**Comment by mahjonp** [comment]
> What's the difference between raw and non-raw mode?

@BusyJay the default setting uses the Mysql mode, there is no other obvious differences besides this.

**Comment by siddontang** [comment]
raw uses Raw TiKV
the default uses Txn TiKV

**Comment by BusyJay** [comment]
/bench +ycsb

```
workload:
  workload: workloada
  mode: raw
```

**Comment by siddontang** [comment]
@mahjonp 

seem YCSB benchmark is not stable?

**Comment by mahjonp** [comment]
> seem YCSB benchmark is not stable?

yes, raw mode is unstable 😢

**Comment by BusyJay** [comment]
/bench +ycsb

```
workload:
  workload: workloada
  mode: raw
```

**Comment by BusyJay** [comment]
/bench +ycsb

```
workload:
  workload: workloada
  mode: raw
```

**Pull request closed without merging**
