### PR TITLE
copr: use EvalType::Bytes as the eval type for Null type. (#9632)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #9632 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/9808
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/9808:release-4.0-26664139d742
```

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/22629 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed: refer https://github.com/pingcap/parser/blob/master/types/field_type.go#L95, all not specifically required EvalType type, the evalType should be EvalType::Bytes.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
test the issue.

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 
- No release note.

### CODE REVIEW

**Review by skyzh — APPROVED** [review]

**Comment by skyzh** [comment]
Please fix format before merging.

**Review by sticnarf — APPROVED** [review]
LGTM

**Comment by skyzh** [comment]
@wshwsh12 It seems this PR also brings changes of https://github.com/tikv/tikv/pull/9856 , seems it needs rebase.

**Pull request closed without merging**
