### PR TITLE
causal_ts: simplify the logic of pop ts

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: ref #12794

What's Changed:

A compare_exchange_weak loop with relaxed order should have the same effect of a single fetch_add. So replace the loop with fetch_add can make the logic slightly simpler and easier to understand. In theory the performance should also be slightly better.

NOTE: the only other usage of `logic_start` is to calculate the number of remain, the current logic is `logic_end.saturating_sub(logic_start)`, so after this change it is still correct when logic_start becomes bigger than logic_end.

```
simplify pop ts by replace loop of compare_exchange_weak with fetch_add
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by sticnarf — COMMENTED** [review]
I think the only difference is that the original version of `pop` won't make `logical_start` larger than `logical_end`. This may affect the correctness of `remain`.

So, now `remain` should check whether `logical_start` is larger than `logical_end`.

**Comment by glorv** [comment]
> I think the only difference is that the original version of `pop` won't make `logical_start` larger than `logical_end`. This may affect the correctness of `remain`.
> 
> So, now `remain` should check whether `logical_start` is larger than `logical_end` to avoid subtraction underflow.

@sticnarf remain is calculated by `logical_end.saturating_sub(logical_start.load())`, so it is still correct after this change.

**Review by sticnarf — APPROVED** [review]
> @sticnarf remain is calculated by logical_end.saturating_sub(logical_start.load()), so it is still correct after this change.

Sorry... I misread the code there.

LGTM

**Comment by pingyu** [comment]
Could you do some benchmark ? It may not has better performance, as there will be more atomic writes.

Besides, we had just changed from `fetch_add` to `compare_exchange_weak` :joy: . See [here](https://github.com/tikv/tikv/pull/12099#discussion_r834251244).

**Comment by BusyJay** [comment]
What I mean is if we need to do something with the atomic value instead of plus unconditionally, loop + compare_exchange_weak is better.

**Comment by glorv** [comment]
> What I mean is if we need to do something with the atomic value instead of plus unconditionally, loop + compare_exchange_weak is better.

@BusyJay  Thanks for your reply. I misunderstood the pre-condition of the original implement. So I think this change is still correct and is simpler and the performance is also better especially when the concurrency is very high.

**Comment by glorv** [comment]
@pingyu Here is a microbench mark between fetch_add and compare_exchange loop, when the concurrency is high, fetch_add is much faster than the loop, so in this condition, the extra write cost can be ignored.

image

BTW, as @BusyJay is agaist this change because he think let `start` not exceed `end` is more important. I'm ok with both as this is just a minor change and not affect the correctness of the original logic. My original thoughts is to let the code become simpler(and maybe more ergonomic?).

**Comment by BusyJay** [comment]
Or maybe we can rename `logical_start` to `alloc_offset` and comment the possible value range of the field. People may assume `logical_start` should not be larger than `logical_end`, but they may not have the same assumption on `alloc_offset`.

**Comment by nolouch** [comment]
> @pingyu Here is a microbench mark between fetch_add and compare_exchange loop, when the concurrency is high, fetch_add is much faster than the loop, so in this condition, the extra write cost can be ignored.
> 
> image
> 
> BTW, as @BusyJay is agaist this change because he think let `start` not exceed `end` is more important. I'm ok with both as this is just a minor change and not affect the correctness of the original logic. My original thoughts is to let the code become simpler(and maybe more ergonomic?).

:) maybe we can let https://github.com/tikv/yatp/pull/68 go head.

**Comment by BusyJay** [comment]
`active_workers` is used in various functions, it may not be obvious what's the impact if it can go wrong.

**Review by pingyu — APPROVED** [review]
LGTM~

**Pull request merged**
