### PR TITLE
copr: Add vectorize day_of_week

### PR DESCRIPTION
**Pull request by Poytr1**
PCP #5751

Signed-off-by: Poytr1 pooytr1@gmail.com
###  What have you changed?

Vectorize `day_of_week`

###  What is the type of the changes?

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?

- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No
###  Does this PR affect `tidb-ansible`?

No

### CODE REVIEW

**Comment by Poytr1** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/119

**Comment by sticnarf** [comment]
It looks weird that this PR makes all tests fail. Let me investigate it...

**Comment by sticnarf** [comment]
@Poytr1 It seems that you hide the head ref of this PR. So this PR is not synced with the latest master. Could you update your branch so the test can pass?

**Comment by Poytr1** [comment]
Hi @sticnarf , sry for the inconvenience. The PR has been opened for a long time and I forgot it and wrongly delete my forked repository... 

I opened a new PR for this just now: https://github.com/tikv/tikv/pull/6645. So feel free to close this one, and move on with that PR. Thanks!

Also for another two PRs: https://github.com/tikv/tikv/pull/6385 and https://github.com/tikv/tikv/pull/6386, I will do the same thing, close them and open new twos.

**Comment by sticnarf** [comment]
@Poytr1 Really sorry for the late response before.

**Pull request closed without merging**
