### PR TITLE
pd_client: reconnect leader only when members change

### LINKED ISSUE #9690: pd connection is reconnecting every 10 minutes
## Bug Report

#7028 adds a new behavior that reconnecting PD leader every 10 minutes. The motivation is avoiding unavailability during pd member changes without restarting TiKV. However, the implementation reconnecting PD unconditionally, which can drop all pd region heartbeats every 10 minutes. If hibernate region is enabled, it can make scheduler ops from PD working very slowly.

PD doesn't need to be reconnected if memberships are the same.

Perhaps related to #9681.

### PR DESCRIPTION
**Pull request by BusyJay**
### What problem does this PR solve?

Issue Number: close #9690 

What's Changed:

Reconnecting leader only when members change to avoid disturbing heartbeats report unexpectedly.

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

### Release note 
- fix frequently reconnecting pd client

### CODE REVIEW

**Review by rleungx — APPROVED** [review]

**Review by overvenus — COMMENTED** [review]
LGTM

**Comment by coocood** [comment]
Can we cherry-pick to release-4.0?

**Comment by BusyJay** [comment]
@coocood I'm afraid it's not a critical issue that will be landed at 4.0.

**Comment by coocood** [comment]
Some users worried about the error log.

**Pull request merged**
