### PR TITLE
*: lock the tipb and kvproto dependencies at some particular commits

### PR DESCRIPTION
**Pull request by kennytm**
## What have you changed? (mandatory)

Changed all tipb dependency to explicitly refer to pingcap/tipb@af5d98495e, which is the commit *before* pingcap/tipb#116 is merged. 

Similarly, changed all kvproto dependency to pingcap/kvproto@1aa667daf, which is the commit *before* pingcap/kvproto#388 is merged.

---

Currently, all TiKV components, including kvproto, depend on `protobuf = "~2.0"`. The tilde dependency means all versions `>=2.1` are explicitly denied. However, since pingcap/tipb#116 the `tipb` package requires `^2.1`,  so external dependencies of TiDB (i.e. not using the `Cargo.lock`) will get this resolution conflict:

```
error: failed to select a version for `protobuf`.
    ... required by package `tipb v0.0.1 (https://github.com/pingcap/tipb.git#535e1aba)`
    ... which is depended on by `cop_datatype v0.0.1 (https://github.com/tikv/tikv.git?rev=69680545b2721810581cdedeb5c4a975ddc4dc2b#69680545)`
    ... which is depended on by `tikv v3.0.0-beta.1 (https://github.com/tikv/tikv.git?rev=69680545b2721810581cdedeb5c4a975ddc4dc2b#69680545)`
    ... which is depended on by `tikv-importer v3.0.0-beta.1 (/root/tikv-importer)`
versions that meet the requirements `^2.1` are: 2.5.0, 2.4.2, 2.4.0, 2.3.1, 2.3.0, 2.2.5, 2.2.4, 2.2.3, 2.2.2, 2.2.1, 2.2.0, 2.1.5, 2.1.4, 2.1.3, 2.1.2, 2.1.1, 2.1.0

all possible versions conflict with previously selected packages.

  previously selected package `protobuf v2.0.0`
    ... which is depended on by `engine v0.0.1 (https://github.com/tikv/tikv.git?rev=69680545b2721810581cdedeb5c4a975ddc4dc2b#69680545)`
    ... which is depended on by `tikv v3.0.0-beta.1 (https://github.com/tikv/tikv.git?rev=69680545b2721810581cdedeb5c4a975ddc4dc2b#69680545)`
    ... which is depended on by `tikv-importer v3.0.0-beta.1 (/root/tikv-importer)`

failed to select a version for `protobuf` which could resolve this conflict
```

This PR explicitly sets the tipb dependency to pingcap/tipb@af5d98495e, so TiKV will not need protobuf ≥2.1 anymore.

Note that this is just a temporary solution so using TiKV as a dependency no longer fails. In the medium term we need to update protobuf to 2.6 to address RustSec/advisory-db#97, and in the long term we may want to move to Prost.

The change to kvproto is similar: without the explicit commit in Cargo.toml, the dependent package will try to build the latest release-3.0 code, which adds the pessimistic lock requirement and causing TiKV fail to compile without #4698.

## What are the type of the changes? (mandatory)

- Bug fix (change which fixes an issue)

## How has this PR been tested? (mandatory)

`cargo check` no longer emits the dependency and compilation error after applying this PR.
 

## Does this PR affect documentation (docs) or release note? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No

### CODE REVIEW

**Comment by kennytm** [comment]
PTAL  @brson @nrc  @lonng

**Comment by breeswish** [comment]
how about using replace or patch as suggested in https://github.com/tikv/tikv/pull/4129 ?

Also see https://github.com/tikv/tikv/pull/4606

**Comment by kennytm** [comment]
The solution you suggested in #4606 requires rust-lang/cargo#5478 🤷‍♀️. And without this PR one cannot easily depend on tikv externally.

**Comment by breeswish** [comment]
So shall we pick back the solution we reverted in #4129 ? @overvenus PTAL

**Comment by BusyJay** [comment]
Or you can use replace.

**Comment by kennytm** [comment]
(I've solved the dependency problem in https://github.com/tikv/importer/ by manually editing `Cargo.lock`...)

**Comment by brson** [comment]
I don't see any strong contrary opinions so lgtm.

**Comment by breeswish** [comment]
Any updates?

**Comment by kennytm** [comment]
This PR cannot solve #4864 unfortunately...

**Comment by kennytm** [comment]
Recent development of the protobuf dependency conflict can't be fixed by locking the git dependency anymore. Closing this PR.

**Pull request closed without merging**
