### PR TITLE
use aHash instead of FxHash

### PR DESCRIPTION
**Pull request by MaiCw4J**
Signed-off-by: mak <610546069@qq.com>

#6183  
###  What have you changed?

use aHash instead of FxHash

###  What is the type of the changes?

Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?
Please select the tests that you ran to verify your changes:
- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No. It should not change the behavior.

###  Does this PR affect `tidb-ansible`?

No

### CODE REVIEW

**Comment by MaiCw4J** [comment]
test failed, how can i fix it? Is there anything else affected? :(

**Comment by breeswish** [comment]
@MaiCw4J You need to change the test suite of `batch::executors::slow_hash_aggr_executor::tests::test_it_works_integration`, because it depends on the hash algorithm. When hash algorithm changes, the result is changed.

**Comment by MaiCw4J** [comment]
> @MaiCw4J You need to change the test suite of `batch::executors::slow_hash_aggr_executor::tests::test_it_works_integration`, because it depends on the hash algorithm. When hash algorithm changes, the result is changed.

i got it, thx

**Comment by MaiCw4J** [comment]
> When it is available aHash takes advantage of the hardware AES instruction on X86 processors. If it is not available it falls back on a lower quality (but still DOS resistant) algorithm based on multiplication.

seem `aHash` hash algorithm is indeterminacy, still need to test for hash result? or add other test case? please help me again ;-)

**Comment by breeswish** [comment]
@MaiCw4J Looks wired.. The hash function should be deterministic..

**Comment by andylokandy** [comment]
@breeswish PTAL. Is it blocked by `aHash` itself?

**Comment by AndreMouche** [comment]
Please fix the conflicts, thank you

**Comment by andylokandy** [comment]
Closed since no further updates.

**Pull request closed without merging**
