### PR TITLE
metrics: fix grid position in TiKV Details

### PR DESCRIPTION
**Pull request by tabokie**
Signed-off-by: tabokie <xy.tao@outlook.com>

### What is changed and how it works?

Issue Number: Ref #11119

What's Changed:

```commit-message
Fix grid positions in TiKV Details dashboard.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests
- No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by Connor1996 — COMMENTED** [review]
What's the problem of these

**Comment by tabokie** [comment]
@Connor1996 The physical layout doesn't match the order in the manifest. E.g. Raft Engine is placed after Resolve-TS, instead of after RocksDB.

**Review by Connor1996 — APPROVED** [review]

**Review by youjiali1995 — APPROVED** [review]

**Pull request merged**
