### PR TITLE
Make PerfContext abstract and use it in raftstore

### PR DESCRIPTION
**Pull request by brson**
### What problem does this PR solve?

Problem Summary:

PerfContext is the last concrete rocks type used in raftstore. In order to remove engine_rocks as a dependency of raftstore, it must be abstracted in some way.

This PR makes PerfContext another engine trait. Unlike in rocks, where it is accessed as a global, this patch follows the existing engine_traits pattern, and access PerfContext through accessors on an engine instance. This seems more reasonable as a general-purpose abstraction.

On the other hand, this doesn't make any attempt to make the PerfContext measurements reasonable for any non-rocks engine. Instead, it makes the PerfContext accessor, now  called `get_perf_context` return an Option. For now, other engines are just expected to return None.

This patch then entirely removes engine_rocks::PerfContext and PerfLevel from raftstore. There are a few usages in the tikv crate that I have not touched yet. The next step is to remove engine_rocks as a dependency from raftstore.

### Related changes

https://github.com/tikv/tikv/issues/6402

### Check List 

- Unit test

### Release note 

- No release note.

### CODE REVIEW

**Comment by Little-Wallace** [comment]
I think we do not need implement every field for an abstract PerfContext. I prefer follows:
```
trait PerfContext {
      fn start_observe(&self);
      fn report_metrics(&self);
}
impl PerfContext for RocksPerfContext {
     fn report_metrics(&self) {
          let mutex_time = self.0. db_condition_wait_nanos();
          APPLY_PERF_CONTEXT_TIME_HISTOGRAM_STATIC.with_label_values(&[self.name, "mutex_wait"]).observe(mutex_time);
         ....
     }
}
```

**Comment by brson** [comment]
@Little-Wallace I am working to adapt this patch to do as you suggest.

That will be sufficient to cover the use cases in raftstore, which is good enough to let me get rid of the raftstore dependency on engine_rocks. It will not be sufficient to cover the use cases in the tikv crate though, which I am happy to tackle later.

**Comment by brson** [comment]
@Little-Wallace I have completed the requested rework.

Now the API looks like

```rust
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum PerfLevel {
    Uninitialized,
    Disable,
    EnableCount,
    EnableTimeExceptForMutex,
    EnableTimeAndCPUTimeExceptForMutex,
    EnableTime,
    OutOfBounds,
}

pub trait PerfContextExt {
    type PerfContext: PerfContext;

    fn get_perf_context(&self, level: PerfLevel, kind: PerfContextKind) -> Self::PerfContext;
}

#[derive(Eq, PartialEq, Copy, Clone)]
pub enum PerfContextKind {
    RaftstoreApply,
    RaftstoreStore,
}

pub trait PerfContext: Send {
    fn start_observe(&mut self);
    fn report_metrics(&mut self);
}
```

This is still a leaky abstraction, with rocks-specific perf levels and tikv-specific context-'kind'. The 'kind' is needed to distinguish which subsystem is reporting metrics. It is better than the previous API though. In the near-term it's not really feasible to get rid of these rocks-specific perf levels, since this enum is deserialized directly from the tikv config files. Doing anything about the abstraction of these perf levels probably needs to wait until we tackle multi-engine configuration, which will probably be one of the very last tasks involved in enabling alternate engines in a running tikv instance.

As I mentioned previously, there will need to be more work done to support the use-cases within the tikv crate.

Please review @Little-Wallace @5kbpers @hicqu @Connor1996

**Comment by Little-Wallace** [comment]
Sorry for review this PR so later..... Shall we merge `APPLY_PERF_CONTEXT_TIME_HISTOGRAM_STATIC ` and `STORe_PERF_CONTEXT_TIME_HISTOGRAM_STATIC` to one? We can distinguish them by labels. Rest LGTM

**Review by Little-Wallace — APPROVED** [review]
LGTM

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by brson** [comment]
> Sorry for review this PR so later..... Shall we merge `APPLY_PERF_CONTEXT_TIME_HISTOGRAM_STATIC ` and `STORe_PERF_CONTEXT_TIME_HISTOGRAM_STATIC` to one? We can distinguish them by labels.

@Little-Wallace I don't understand prometheus enough to know how to do this. Can you explain it a bit more?

**Comment by brson** [comment]
I've updated this to master, but as indicated in my last comment I don't know how to make the change you've suggested @Little-Wallace. I'm happy to if you explain a bit more how.

**Comment by brson** [comment]
Updated to master.

**Comment by Little-Wallace** [comment]
@brson Oh, It is enough. Maybe we can keep it and make refactor another day.....

**Comment by brson** [comment]
Thanks @Little-Wallace !

**Pull request merged**
