### PR TITLE
Transfer the work of callback which is in on_write_finish from sched …

### LINKED ISSUE #9462: Reduce tasks spawned to the scheduler worker pool
## Development Task
A command has to wait for a available scheduler worker thread at least 2 times: one is from gRPC threads to the scheduler worker pool when the snapshot of the engine is ready; The other is from apply pool to the scheduler worker pool when data is written to the raft store. If the scheduler worker pool is busy, we may experience noticeable latency of it.

TPCC workload
image

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
…worker to apply worker

Signed-off-by: SpadeA-Tang <u6748471@anu.edu.au>

### What is changed and how it works?

Issue Number: Close #9462

What's Changed:

```commit-message
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
If this PR will be picked to release branch, then a release note is probably required.
```

### CODE REVIEW

**Comment by JayiceZ** [comment]
Oh. In my opinion, this PR didn't solve the problem in the referring issue.

**Comment by SpadeA-Tang** [comment]
> 

Thanks for the comment. 
Engine_cb in shceduler.rs which calls on_write_finish is exectued in apply worker. However, on_write_finish is spawned to be executed in sched worker. I transfer the work of cb from on_write_finish and make it be executed in engine_cb, so it will be executed in apply worker.
For now, I just made some simple modifications and test the correctness of it.

**Comment by SpadeA-Tang** [comment]
> Oh. In my opinion, this PR didn't solve the problem in the referring issue. Can you describe how it works?

Thanks for the comment.
Engine_cb in shceduler.rs which calls on_write_finish is exectued in apply worker. However, on_write_finish is spawned to be executed in sched worker. I transfer the work of cb from on_write_finish and make it be executed in engine_cb, so it will be executed in apply worker.
For now, I just made some simple modifications and test the correctness of it.

**Pull request closed without merging**
