### PR TITLE
github: add release-note description format to pull request template

### PR DESCRIPTION
**Pull request by CadmusJiang**
Signed-off-by: Cadmus <CadmusJiang@gmail.com>

### What problem does this PR solve?
Help Tichi to realize the information collection function of release note.
https://github.com/ti-community-infra/configs/pull/326
Problem Summary:

### What is changed and how it works?
Add a release note reference to pull_ request_template.md

What's Changed:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Review by hi-rustin — APPROVED** [review]
LGTM.

**Comment by hi-rustin** [comment]
/cc @andylokandy 

Could you please take a look?

**Review by andylokandy — APPROVED** [review]

**Comment by hi-rustin** [comment]
/hold

Needs test.

**Pull request merged**
