### PR TITLE
tidb_query: fix TopN comparison for release 3.1

### PR DESCRIPTION
**Pull request by zhongzc**
Signed-off-by: zhongzc zhongzc_arch@outlook.com

### What have you changed?
cherry-pick: #7175

### CODE REVIEW

**Comment by breeswish** [comment]
/run-all-tests tidb=release-3.1 tidb-test=release-3.1 pd=release-3.1

**Comment by zhongzc** [comment]
/run-all-tests tidb=release-3.1 tidb-test=release-3.1 pd=release-3.1

**Pull request merged**
