### PR TITLE
batch proposals correctly if disk full checks pass

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve?

Batch proposals correctly if disk full checks pass. Close https://github.com/tikv/tikv/issues/10716.

### Check List 

Tests 

- No code

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by gengliqi — APPROVED** [review]

**Comment by tier-cap** [comment]
/LGTM
only a tiny repeat judgement

**Review by 5kbpers — APPROVED** [review]

**Pull request merged**
