### PR TITLE
UCP: Migrate `GreatestInt` (Vectorize) from TiDB

### LINKED ISSUE #6743: UCP: Migrate `GreatestInt` (Vectorize) from TiDB
## Description

Port the function `GreatestInt`  (Vectorize)  from TiDB to coprocessor.

## Score 

* 50

## Mentor(s)

* @breeswish 

## Recommended Skills

* Rust programming 

## Learning Materials

Functions ported from TiDB

- https://github.com/tikv/tikv/tree/master/components/tidb_query/src/rpn_expr) 
- https://github.com/tikv/tikv/tree/master/components/tidb_query/src/expr)

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato ghzpotato@gmail.com

### What problem does this PR solve?

Issue Number: close #6743 

Problem Summary: add vectorized GreatestInt

### What is changed and how it works?

* Add vectorized GreatestInt
* Add vectorized GreatestInt unit tests

### Check List 

- Unit test

### CODE REVIEW

**Comment by JmPotato** [comment]
Signed-off-by: JmPotato ghzpotato@gmail.com

**Comment by sticnarf** [comment]
Please sign off you commits 
And you forget writing UCP id at the first line of your PR description :)

**Comment by JmPotato** [comment]
@sticnarf Thanks for reminding. First time contributing, kind of awkward :-(

So what should I do now? Close this RP, add DCO and reopen it?

**Comment by sticnarf** [comment]
You can certainly fix the DCO in the same PR but I don't know fixing the UCP id will make the robot aware. I recommend create a new PR.

**Comment by JmPotato** [comment]
@sticnarf Thanks! I have created a new PR #7847 already.

**Pull request closed without merging**
