### PR TITLE
import: add download wait duration metrics (#9373)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #9373 to release-4.0

---

### What problem does this PR solve?

Add download wait duration metrics.

### Related changes

- Need to cherry-pick to the release branch

### Release note 

- No release note

### CODE REVIEW

**Comment by hi-rustin** [comment]
This cherry pick PR is for a release branch and has not yet been approved by release team. Adding the do-not-merge/cherry-pick-not-approved label.
To merge this cherry pick, it must first be approved (/lgtm + /merge) by the collaborators.
AFTER it has been approved by collaborators, please ping the release team in a comment to request a cherry pick review

**Review by 3pointer — COMMENTED** [review]
LGTM

**Pull request merged**
