### PR TITLE
Fix typo in readme

### PR DESCRIPTION
**Pull request by senden9**
## What have you changed? (mandatory)
Fix typo in README.md "Socia" => "Social"

## What are the type of the changes? (mandatory)
- Misc (other changes)

## How has this PR been tested? (mandatory)
No

## Does this PR affect documentation (docs) or release note? (mandatory)
No & No

## Does this PR affect tidb-ansible update? (mandatory)
No

### CODE REVIEW

**Comment by kennytm** [comment]
Could you sign off the commit ae1dd03? Thanks!

**Comment by siddontang** [comment]
Thanks @senden9 

Please sign off your all commits. See https://github.com/tikv/tikv/blob/master/CONTRIBUTING.md#signing-off-the-commit

If you have already pushed some commits before, you can use `git rebase -i master --signoff` to resign them off.

**Comment by ice1000** [comment]
> If you have already pushed some commits before, you can use git rebase -i master --signoff to resign them off.

To update the most recent commit with signoff you can also `git commit --amend --signoff`

**Comment by senden9** [comment]
Done. Thanks for not only saying what to do but also how.

**Pull request merged**
