### PR TITLE
copr: Add vectorize day_of_week

### PR DESCRIPTION
**Pull request by Poytr1**
Signed-off-by: Poytr1 <pooytr1@gmail.com>

###  What have you changed?

Vectorize day_of_week

###  What is the type of the changes?

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?

- Unit test

###  Does this PR affect `tidb-ansible`?

No

###  Refer to a related PR or issue link (optional)

Duplicate https://github.com/tikv/tikv/pull/6384

### CODE REVIEW

**Comment by AndreMouche** [comment]
@hunterlxt @sticnarf PTAL and the next deadline for reviewing is 2020-02-20 24:00:00

**Comment by sticnarf** [comment]
@TennyZhuang This PR has the same code with https://github.com/tikv/tikv/pull/6384 but is valid now. :)

**Pull request merged**
