### PR TITLE
scanner: Fix the panic on loading old value when there's a rollback record with large ts (#9567)

### LINKED ISSUE #9551: TiKV panic in a resolve lock case of TiCDC
### What version of TiKV are you using?

```
[2021/01/23 14:09:28.818 +08:00] [INFO] [lib.rs:92] ["Welcome to TiKV"]
[2021/01/23 14:09:28.819 +08:00] [INFO] [lib.rs:97] ["Release Version:   5.0.0-rc.x"]
[2021/01/23 14:09:28.819 +08:00] [INFO] [lib.rs:97] ["Edition:           Community"]
[2021/01/23 14:09:28.819 +08:00] [INFO] [lib.rs:97] ["Git Commit Hash:   927e36f952f837c25e2eab2aa065a075b5502ad9"]
[2021/01/23 14:09:28.819 +08:00] [INFO] [lib.rs:97] ["Git Commit Branch: master"]
[2021/01/23 14:09:28.819 +08:00] [INFO] [lib.rs:97] ["UTC Build Time:    2021-01-22 11:02:49"]
```

### Steps to reproduce

integration test in TiCDC: [ci/job/1920](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/1920/pipeline)

tikv logs: [tikv_logs.zip](https://github.com/tikv/tikv/files/5859820/tikv_logs.zip)
cdc log: [cdc.zip](https://github.com/tikv/tikv/files/5870757/cdc.zip)

### What did you expect?

CI runs successfully

### What did happened?

```
[2021/01/23 14:10:10.209 +08:00] [FATAL] [lib.rs:465] ["assertion failed: `(left >= right)`
  left: `TimeStamp(422414173484089357)`,
 right: `TimeStamp(422414175188025351)`"] [backtrace="stack backtrace:
   0: tikv_util::set_panic_hook::{{closure}}
             at components/tikv_util/src/lib.rs:464
   1: std::panicking::rust_panic_with_hook
             at library/std/src/panicking.rs:581
   2: std::panicking::begin_panic_handler::{{closure}}
             at library/std/src/panicking.rs:484
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at library/std/src/sys_common/backtrace.rs:141
   4: rust_begin_unwind
             at library/std/src/panicking.rs:483
   5: std::panicking::begin_panic_fmt
             at library/std/src/panicking.rs:437
   6: tikv::storage::mvcc::reader::scanner::seek_for_valid_write
             at /home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/src/storage/mvcc/reader/scanner/mod.rs:414
      tikv::storage::mvcc::reader::scanner::seek_for_valid_value
             at /home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/src/storage/mvcc/reader/scanner/mod.rs:457
   7: <tikv::storage::mvcc::reader::scanner::forward::DeltaEntryPolicy as tikv::storage::mvcc::reader::scanner::forward::ScanPolicy<S>>::handle_lock
             at /home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/src/storage/mvcc/reader/scanner/forward.rs:622
      tikv::storage::mvcc::reader::scanner::forward::ForwardScanner<S,P>::read_next
             at /home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/src/storage/mvcc/reader/scanner/forward.rs:258
      <tikv::storage::mvcc::reader::scanner::forward::ForwardScanner<S,P> as tikv::storage::txn::store::TxnEntryScanner>::next_entry
             at /home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/src/storage/mvcc/reader/scanner/forward.rs:762
      cdc::endpoint::Initializer::scan_batch
             at components/cdc/src/endpoint.rs:1126
   8: cdc::endpoint::Initializer::async_incremental_scan
             at components/cdc/src/endpoint.rs:1077
      cdc::endpoint::Initializer::on_change_cmd
             at components/cdc/src/endpoint.rs:1025
   9: cdc::endpoint::Endpoint<T>::on_register::{{closure}}
             at /home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/components/cdc/src/endpoint.rs:563
      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/future/mod.rs:80
  10: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/core.rs:173
      tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/loom/std/unsafe_cell.rs:14
      tokio::runtime::task::core::Core<T,S>::poll
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/core.rs:158
      tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/harness.rs:107
      core::ops::function::FnOnce::call_once
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/ops/function.rs:227
      <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panic.rs:308
      std::panicking::try::do_call
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panicking.rs:381
      std::panicking::try
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panicking.rs:345
      std::panic::catch_unwind
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panic.rs:382
      tokio::runtime::task::harness::Harness<T,S>::poll
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/harness.rs:89
      tokio::runtime::task::raw::poll
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/raw.rs:104
  11: tokio::runtime::task::raw::RawTask::poll
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/raw.rs:66
      tokio::runtime::task::Notified<S>::run
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/mod.rs:169
      tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/thread_pool/worker.rs:349
      tokio::coop::with_budget::{{closure}}
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/coop.rs:127
      std::thread::local::LocalKey<T>::try_with
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/thread/local.rs:272
      std::thread::local::LocalKey<T>::with
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/thread/local.rs:248
      tokio::coop::with_budget
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/coop.rs:120
      tokio::coop::budget
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/coop.rs:96
      tokio::runtime::thread_pool::worker::Context::run_task
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/thread_pool/worker.rs:348
  12: tokio::runtime::thread_pool::worker::Context::run
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/thread_pool/worker.rs:320
      tokio::runtime::thread_pool::worker::run::{{closure}}
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/thread_pool/worker.rs:305
      tokio::macros::scoped_tls::ScopedKey<T>::set
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/macros/scoped_tls.rs:63
      tokio::runtime::thread_pool::worker::run
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/thread_pool/worker.rs:302
      tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/thread_pool/worker.rs:281
      <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/blocking/task.rs:41
      tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/core.rs:173
      tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/loom/std/unsafe_cell.rs:14
      tokio::runtime::task::core::Core<T,S>::poll
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/core.rs:158
      tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/harness.rs:107
      core::ops::function::FnOnce::call_once
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/ops/function.rs:227
      <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panic.rs:308
      std::panicking::try::do_call
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panicking.rs:381
      std::panicking::try
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panicking.rs:345
      std::panic::catch_unwind
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panic.rs:382
      tokio::runtime::task::harness::Harness<T,S>::poll
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/harness.rs:89
      tokio::runtime::task::raw::poll
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/raw.rs:104
  13: tokio::runtime::task::raw::RawTask::poll
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/raw.rs:66
      tokio::runtime::task::Notified<S>::run
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/task/mod.rs:169
      tokio::runtime::blocking::pool::Inner::run
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/blocking/pool.rs:250
      tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::{{closure}}
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/blocking/pool.rs:230
      tokio::runtime::context::enter
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/context.rs:72
      tokio::runtime::handle::Handle::enter
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/handle.rs:76
      tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /rust/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/blocking/pool.rs:229
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/sys_common/backtrace.rs:125
  14: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/thread/mod.rs:470
      <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panic.rs:308
      std::panicking::try::do_call
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panicking.rs:381
      std::panicking::try
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panicking.rs:345
      std::panic::catch_unwind
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panic.rs:382
      std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/thread/mod.rs:469
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/ops/function.rs:227
  15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/alloc/src/boxed.rs:1042
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/alloc/src/boxed.rs:1042
      std::sys::unix::thread::Thread::new::thread_start
             at library/std/src/sys/unix/thread.rs:89
  16: start_thread
  17: __clone
"] [location=/home/jenkins/agent/workspace/build_tikv_multi_branch_master/tikv/src/storage/mvcc/reader/scanner/mod.rs:414] [thread_name=cdcwkr]
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #9567 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/9569
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/9569:release-4.0-2f9ed554c9fc
```

---

Signed-off-by: MyonKeminta <MyonKeminta@users.noreply.github.com>

### What problem does this PR solve?

Issue Number: close #9551 

Problem Summary: When the DeltaScanner loads old value for a lock, it asserts all other write records has less `commit_ts` than the lock's `max(start_ts, for_update_ts)`. However there's a special case: a rollback record can be written at any time even the key is locked by a smaller ts.

### What is changed and how it works?

What's Changed: Moves the panicking assertion statement so that rollback records will not be asserted.

### Related changes

- Need to cherry-pick to the release branch
  - 4.0, 5.0-rc

### Check List 

Tests 

- Unit test

Side effects

-

### Release note 

- Fix the issue that when loading old value for CDC's incremental scan on a key where there's a rolled back transaction, in some cases TiKV may panic.

### CODE REVIEW

**Review by sticnarf — APPROVED** [review]

**Review by 5kbpers — COMMENTED** [review]
/lgtm

**Review by 5kbpers — APPROVED** [review]

**Pull request merged**
