### PR TITLE
raftstore: move get_region_approximate_size to split check worker (#9081)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #9081 to release-4.0

---

### What problem does this PR solve?

When peer's approximate size or keys is none，region heartbeat need to directly read rocksdb to get size and keys. It will affect other region's heartbeat. This PR move `get_region_approximate_size` and `get_region_approximate_keys`  to split worker's thread so that most regions' heartbeat will go smoothly.

### What is changed and how it works?

What's Changed:

Add a new task type `GetRegionApproximateSizeAndKeys`  to split checker.  For this task, split check worker will read rocksdb to get size and keys, and execute an callback. 

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- No release note.

### CODE REVIEW

**Comment by gozssky** [comment]
All conflicts are resolved. @Connor1996 @gengliqi @Little-Wallace PTAL.

**Review by Little-Wallace — APPROVED** [review]
LGTM

**Review by Connor1996 — APPROVED** [review]

**Review by gengliqi — APPROVED** [review]

**Pull request merged**
