### PR TITLE
server: support batch split command

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

## What have you changed? (mandatory)
Split region one by one is too slow. We need to support batch split.

## What are the type of changes? (mandatory)
- Improvement (a change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)
Not yet.

## Does this PR affect documentation (docs) or release note? (mandatory)
No

## Does this PR affect `tidb-ansible` update? (mandatory)
No

## Refer to a related PR or issue link (optional)
kvproto: https://github.com/pingcap/kvproto/pull/440
tidb: https://github.com/pingcap/tidb/pull/11739

### CODE REVIEW

**Comment by siddontang** [comment]
please add a test for it.

**Comment by disksing** [comment]
Dependent PR merged. Please review again. @siddontang @overvenus

**Comment by you06** [comment]
What's wrong with the failpoint test?

**Pull request merged**
