### PR TITLE
Abstract cdc crate over engines

### PR DESCRIPTION
**Pull request by brson**
### What problem does this PR solve?

One of the last crates needed to abstract over engines before tikv-server can be started with a non-rocks kv engine.

Part of https://github.com/tikv/tikv/issues/6402

### What is changed and how it works?

Just replacing RocksEngine with KvEngine typarams.

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by brson** [comment]
Rebased to fix the sign-off of a commit.

**Comment by brson** [comment]
Rebased

**Comment by brson** [comment]
Rebased.

**Review by tabokie — APPROVED** [review]
Looking good

**Pull request merged**
