### PR TITLE
server: use {} instead of {:?}.

### PR DESCRIPTION
**Pull request by FenFenGao**
## What have you changed?
Use ```{}``` instead of ```{:?}``` when displaying a ```String```.

## What are the type of the changes?
Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested? 
Unit test.

## Does this PR affect documentation (docs) update? 
No.

## Does this PR affect tidb-ansible update? 
No.

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
@FenFenGao Please sign-off.

**Comment by FenFenGao** [comment]
> @FenFenGao Please sign-off.

OK.

**Comment by siddontang** [comment]
Thanks @FenFenGao 

You said above that your PR is tested by unit test, but I can't see any tests added in this PR.

**Comment by FenFenGao** [comment]
> Thanks @FenFenGao
> 
> You said above that your PR is tested by unit test, but I can't see any tests added in this PR.

The changes brought by this PR is incorrect. I'll close it.

**Pull request closed without merging**
