### PR TITLE
Fix event listener issue

### PR DESCRIPTION
**Pull request by DorianZheng**
## What have you changed? (mandatory)
Check status of CompactionJobInfo at first.

## What are the type of the changes? (mandatory)
- Bug fix 

## How has this PR been tested? (mandatory)
CI

## Does this PR affect documentation (docs) update? (mandatory)
No

## Does this PR affect tidb-ansible update? (mandatory)
No

### CODE REVIEW

**Comment by DorianZheng** [comment]
@zhangjinpeng1987 @huachaohuang PTAL

**Comment by zhouqiang-cl** [comment]
@DorianZheng CI failed, PTAL

**Comment by DorianZheng** [comment]
@zhouqiang-cl my bad, fix it now

**Comment by huachaohuang** [comment]
We should fix this in release-2.0 and release-2.1 too.

**Comment by DorianZheng** [comment]
@huachaohuang It's right. PTAL

**Pull request merged**
