### PR TITLE
config: error on unrecognized keys in --config-check

### LINKED ISSUE #6498: Configuration validation doesn't find misspelled option names in config file
### What version of TiKV are you using?

```
Release Version:   3.1.0-beta.1
Git Commit Hash:   b8b9327f615e9c54a08772b53505a9f864ce55cb
Git Commit Branch: release-3.1
UTC Build Time:    2020-01-12 05:58:49
Rust Version:      rustc 1.37.0-nightly (0e4a56b4b 2019-06-13)
```

### What operating system and CPU are you using?

Darwin seastar.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

### Steps to reproduce

```
printf %s\\n > tikv.toml '[rocksdb]' 'max_open_files = 20000'
tikv-server -C ./tikv.toml --pd=127.0.0.1 --config-check
tikv-server -C ./tikv.toml --pd=127.0.0.1  2>&1 | grep -o 'max.open.files..........'
```

### What did you expect?

Using `max_open_files` should either work correctly or should cause configuration validation to fail. Silently accepting invalid configuration items can lead to serious security issues and a lot of wasted time for DBAs.

### What did happened?

TiKV silently accepted `max_open_files` instead of `max-open-files`, even though `max_open_files` is invalid and has no effect.

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve?

Issue Number: close #6498

Problem Summary: Configuration validation doesn't find misspelled option names in config file 

### What is changed and how it works?

What's Changed:

Using the [`serde_ignored` package](https://crates.io/crates/serde_ignored), we can find out unrecognized key paths in the TOML file. Thus `--config-check` is enhanced to reject them.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:

### Check List 

Tests 

- Unit test

Side effects

### Release note 

* `--config-check` now rejects a configuration file when it contains unknown items (e.g. due to typo or deprecation).

### CODE REVIEW

**Comment by NingLin-P** [comment]
Can this pr be merged or there are other concerns?

**Comment by kennytm** [comment]
(someone needs to do the /merge i don't have permission 🙃)

**Comment by kennytm** [comment]
/run-integration-common-test

```
[2020-08-28T09:27:25.753Z] 2020/08/28 17:27:25.579 main.go:713: [fatal] run test [partition] err: sql:EXPLAIN SELECT `col_int_nokey` FROM z WHERE `col_int_nokey` BETWEEN 6 AND 1;: failed to run query 

[2020-08-28T09:27:25.753Z] "EXPLAIN SELECT `col_int_nokey` FROM z WHERE `col_int_nokey` BETWEEN 6 AND 1;" 

[2020-08-28T09:27:25.753Z]  around line 400, 

[2020-08-28T09:27:25.753Z] we need(350):

[2020-08-28T09:27:25.753Z] EXPLAIN SELECT `col_int_nokey` FROM z WHERE `col_int_nokey` BETWEEN 6 AND 1;

[2020-08-28T09:27:25.753Z] id	estRows	task	access object	operator info

[2020-08-28T09:27:25.753Z] TableReader_7	0.00	root	partition:all	data:Selection_6

[2020-08-28T09:27:25.753Z] └─Selection_6	0.00	cop[tikv]		ge(test.z.col_int_nokey, 6), le(test.z.col_int_nokey, 1)

[2020-08-28T09:27:25.753Z]   └─TableFullScan_5	10000.00	cop[tikv]	table:z	keep order:false, stats:pseudo

[2020-08-28T09:27:25.753Z] S

[2020-08-28T09:27:25.753Z] but got(350):

[2020-08-28T09:27:25.753Z] EXPLAIN SELECT `col_int_nokey` FROM z WHERE `col_int_nokey` BETWEEN 6 AND 1;

[2020-08-28T09:27:25.753Z] id	estRows	task	access object	operator info

[2020-08-28T09:27:25.753Z] TableReader_7	0.00	root	partition:dual	data:Selection_6

[2020-08-28T09:27:25.754Z] └─Selection_6	0.00	cop[tikv]		ge(test.z.col_int_nokey, 6), le(test.z.col_int_nokey, 1)

[2020-08-28T09:27:25.754Z]   └─TableFullScan_5	10000.00	cop[tikv]	table:z	keep order:false, stats:pseudo

[2020-08-28T09:27:25.754Z] 

[2020-08-28T09:27:25.754Z] 
```

**Comment by kennytm** [comment]
/run-integration-copr-test

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_integration-copr-test/detail/tikv_ghpr_integration-copr-test/3593/pipeline

```
[2020-08-28T09:29:16.642Z]  > git fetch --tags --force --progress git@github.com:tikv/tikv.git +refs/pull/8194/*:refs/remotes/origin/pr/8194/* --prune
[2020-08-28T09:39:16.644Z] ERROR: Timeout after 10 minutes
[2020-08-28T09:41:17.889Z] ERROR: Error fetching remote repo 'origin'
```

**Pull request merged**
