### PR TITLE
start gc after node to fetch node id (#9486)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #9486 to release-5.0-rc
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr 9487
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/9487:ti-srebot:release-5.0-rc-49223bc9d90f
```

---

Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve?

There is a bug in the master branch that GC can't work at all. The reason is `0` is passed into the GC worker as `store_id`, which will cause all regions get skiped when doing GC.

Close https://github.com/tikv/tikv/issues/9466.

The bug is introduced in https://github.com/tikv/tikv/pull/9350.

### What is changed and how it works?

Start gc worker after node. So that `node_id` passed into the GC worker will must be valid.

### Check List 

Tests 
- Manual test (add detailed scripts or steps below)
a) starting a new tikv cluster
b) run a sysbench update_index workload, then check the gc worker cpu panel
c) check the result:
  
图片
图片

### Release note 
* No release note

### CODE REVIEW

**Review by hunterlxt — APPROVED** [review]
/lgtm

**Review by youjiali1995 — APPROVED** [review]

**Review by jebter — APPROVED** [review]

**Pull request merged**
