### PR TITLE
raftstore: make slowscore accurate (#12275)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #12275 to release-5.4
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/12384
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/12384:release-5.4-de343c145091
```

---

refer https://github.com/tikv/tikv/issues/12254
Signed-off-by: Jayice <1185430411@qq.com>

### What is changed and how it works?

Issue Number: ref https://github.com/tikv/tikv/issues/12254

What's Changed:

```
make slowscore accurate in corner case.
```

### Check List 

Tests 

- Unit test

### Release note 

```release-note
none
```

### CODE REVIEW

**Comment by cfzjywxk** [comment]
https://github.com/tikv/tikv/issues/12254

**Comment by cfzjywxk** [comment]
@5kbpers 
Need approval, ping~

**Comment by cfzjywxk** [comment]
> @5kbpers Need approval, ping~

@5kbpers Ping~

**Review by 5kbpers — APPROVED** [review]

**Review by cfzjywxk — APPROVED** [review]

**Pull request merged**
