### PR TITLE
grafana: improve Fast Tune panels (#9164)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #9164 to release-4.0

---

Signed-off-by: Liu Cong <innerr@gmail.com>

### What problem does this PR solve?

Problem Summary:
This is some improvements of Fast Tune panels based on original page https://github.com/tikv/tikv/pull/8798

### What is changed and how it works?

What's Changed:
- Add more panels to detect issues between instances
- Seperated into 3 rows
- Fixed some displaying issues, some improvements too small to mention about

### Check List 

Tests 

- No code

Side effects

- None

### Release note 

- None

### CODE REVIEW

**Review by tabokie — APPROVED** [review]
LG

**Comment by hi-rustin** [comment]
This cherry pick PR is for a release branch and has not yet been approved by release team.
Adding the do-not-merge/cherry-pick-not-approved label.

To merge this cherry pick, it must first be approved (/lgtm + /merge) by the collaborators.

AFTER it has been approved by collaborators, please ping the release team in a comment to request a cherry pick review

**Review by NingLin-P — APPROVED** [review]
/LGTM

**Pull request merged**
