### PR TITLE
grafana: Fix display of ingest SST and compaction size

### PR DESCRIPTION
**Pull request by Connor1996**
### What is changed and how it works?

Issue Number: Ref #15990 

What's Changed:

```commit-message
Fix display of ingest SST and compaction size
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by LykxSassinator — APPROVED** [review]

**Review by glorv — APPROVED** [review]

**Comment by glorv** [comment]
Do we need to cherry-pick this bugfix to older version?

**Comment by Connor1996** [comment]
> Do we need to cherry-pick this bugfix to older version?

These metrics are added recently, so no need

**Pull request merged**
