### PR TITLE
copr: Vectorize `concat`.

### PR DESCRIPTION
**Pull request by cireu**
Signed-off-by: Zhu Zihao <all_but_last@163.com>
PCP: #5751

###  What have you changed?

Vectorize concat 

###  What is the type of the changes?

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?

- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No 
###  Does this PR affect `tidb-ansible`?

No

### CODE REVIEW

**Comment by cireu** [comment]
@sre-bot  /run-integration-copr-test copr-test=pr/37

**Comment by cireu** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/37

**Comment by breeswish** [comment]
@sticnarf @lonng @andylokandy @iosmanthus PTAL

**Comment by cireu** [comment]
@sre-bot /run-all-tests

**Comment by cireu** [comment]
Please consider merge it again @lonng  @breeswish

**Comment by lonng** [comment]
@cireu Please resolve the conflicts, thanks.

**Comment by cireu** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/37

**Comment by cireu** [comment]
@lonng  Done.

**Comment by lonng** [comment]
@cireu I am very sorry because this PR was not merged in time, causing conflict again.

**Comment by cireu** [comment]
OMG :sweat:

**Pull request merged**
