### PR TITLE
fix issue #3600

### LINKED ISSUE #3600: CI target cache might be broken now
## Bug Report

From CI ([example](https://circleci.com/gh/tikv/tikv/13897)), we can see that it takes 0 seconds to download `target` cache. It might indicate that cache is not found. This lead to 30 minutes' built time. Previously when we have a target cache, it can be only 8 minutes ideally.

### PR DESCRIPTION
**Pull request by yangwenmai**
## What have you changed? (mandatory)

Ensure that the cache key is consistent.

## What are the type of the changes? (mandatory)

fix #3600 

## How has this PR been tested? (mandatory)

Check the CI

### CODE REVIEW

**Comment by breeswish** [comment]
It was set to `v3-target-master-{{ checksum "rust-toolchain" }}` because CircleCI [uses cache prefix matching](https://circleci.com/docs/2.0/caching/#restoring-cache), so it doesn't matter. While in this PR it make things worse, because the SHA1 for each build is different, then a prefix matching will fail. You can see results from [circle ci](https://circleci.com/gh/tikv/tikv/14070?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) as well, cache is not downloaded.

**Comment by yangwenmai** [comment]
Is it because the master cache was deleted when other branches were built?

This logic may be keep it.

```sh
if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
    rm -rf ~/tikv_cache_cargo
    mkdir ~/tikv_cache_cargo
...
```

**Comment by breeswish** [comment]
@yangwenmai Each build will not affect each other, they are running on isolated environments.

**Comment by yangwenmai** [comment]
So, that cache is not work for every build?

**Comment by breeswish** [comment]
@yangwenmai Cache is shared, please refer to the link above.

**Comment by huachaohuang** [comment]
Seems this PR is not necessary, close it now.

**Pull request closed without merging**
