### PR TITLE
grpc: set compression args for TiKV service

### LINKED ISSUE #17176: `grpc-compression-type` doesn't affect TiKV's response to TiDB
## Bug Report

`grpc-compression-type` doesn't affect TiKV's response to TiDB.
Corresponding args may be missing here https://github.com/tikv/tikv/blob/8e1f26bd5177d94691986a88c244844bde920479/src/server/server.rs#L96

### What version of TiKV are you using?

v6.5.2

### What operating system and CPU are you using?

Doesn't matter

### Steps to reproduce

Run one large SELECT statement. Monitor TiKV's network traffic.

### What did you expect?

Compression setting works.

### What did happened?

Compression doesn't work.

### PR DESCRIPTION
**Pull request by ekexium**
### What is changed and how it works?

Issue Number: Close #17176

What's Changed:

```commit-message
Set compression arguments for TiKV service. The compression arguments are loaded from TiKV config.
It will affect TiKV's response to TiDB.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Fix the problem that the compression config of TiKV doesn't affect TiKV service, including its response to TiDB.
```

### CODE REVIEW

**Review by LykxSassinator — APPROVED** [review]
LGTM

**Review by overvenus — APPROVED** [review]

**Comment by MimeLyc** [comment]
update

**Pull request merged**
