### PR TITLE
raftstore: add more arguments to pre_exec observer

### PR DESCRIPTION
**Pull request by CalvinNeo**
Signed-off-by: CalvinNeo <calvinneo1995@gmail.com>

### What is changed and how it works?
Issue Number: ref #12849

What's Changed:

```commit-message
Add more arguments to pre_exec observer
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by breezewish — APPROVED** [review]

**Comment by tonyxuqqi** [comment]
Please add the comment on what are the new parameters’ functionality. 
especially for the parameter index, what’s the specific meaning? Is it commit index or apply index or something else. 
Also will you add more parameters? If that I would  define a ctx struct for these parameters

**Comment by CalvinNeo** [comment]
> Please add the comment on what are the new parameters’ functionality. especially for the parameter index, what’s the specific meaning? Is it commit index or apply index or something else. Also will you add more parameters? If that I would define a ctx struct for these parameters

No parameters are planned to be added.

**Review by tonyxuqqi — APPROVED** [review]

**Pull request merged**
