### PR TITLE
*: remove CompactionJobInfo re-exports

### PR DESCRIPTION
**Pull request by Rustin-Liu**
Signed-off-by: Rustin-Liu <rustin.liu@gmail.com>

###  What have you changed?
Remove CompactionJobInfo re-exports.

###  What is the type of the changes?

- Engineering (engineering change which doesn't change any feature or fix any issue)

###  How is the PR tested?

cargo test --all --no-run

###  Refer to a related PR or issue link (optional)
#6402

### CODE REVIEW

**Comment by Rustin-Liu** [comment]
@zhangjinpeng1987 @yiwu-arbug @brson  PTAL~

**Comment by zhangjinpeng1987** [comment]
Please fix the conflicts.

**Comment by Rustin-Liu** [comment]
> Please fix the conflicts.

Fixed.

**Comment by Rustin-Liu** [comment]
@brson  ping~

**Comment by brson** [comment]
Nice work @Rustin-Liu .

**Pull request merged**
