### PR TITLE
reuse monotonic-raw-now for each round in raftstore

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
Signed-off-by: zhangjinpeng1987 <zhangjinpeng@pingcap.com>

## What have you changed? (mandatory)

In master branch, monotonic_raw_now is called in post_propose to generate lease time, it contributes a significant part for the CPU usage of the raftstore thread. This branch call monotonic_raw_now once for each round of poll and reuse it as lease time.

post-propose-clock

## What are the type of the changes? (mandatory)

The currently defined types are listed below, please pick one of the types for this PR by removing the others:
- Improvement (change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)

- [x] benchmark

As we can see, this branch has eliminate the cost of monotonic_raw_now in post_propose.
reuse-monotonic-raw-time

## Does this PR affect documentation (docs) or release note? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
@BusyJay @overvenus @hicqu PTAL

**Comment by siddontang** [comment]
how about the performance?

**Comment by zhangjinpeng1987** [comment]
> how about the performance?
This part of cost contributes 2% CPU time of `raftstore` thread.

**Comment by hicqu** [comment]
LGTM

**Pull request merged**
