### PR TITLE
Fix event listener issue (#4126)

### PR DESCRIPTION
**Pull request by overvenus**
## What have you changed? (mandatory)

Check status of CompactionJobInfo.

## What are the type of the changes? (mandatory)

- Bug fix (non-breaking change which fixes an issue)

## Does this PR affect documentation (docs) update? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No

## Refer to a related PR or issue link (optional)

Cc #4126

### CODE REVIEW

**Comment by Connor1996** [comment]
so this is a cherry-pick?

**Comment by huachaohuang** [comment]
Duplicate with https://github.com/tikv/tikv/pull/4132?

**Comment by DorianZheng** [comment]
Isn't it the same as #4132

**Comment by overvenus** [comment]
Duplicate with #4132

**Pull request closed without merging**
