### PR TITLE
storage:change configuration storage.max-key-size default value from 4096 to 8192

### LINKED ISSUE #11241: Relax default max key size
The default max key size is 4096 which is suitable for TiDB without clustered index because the max index length is 3072, but with clustered index, the length of clustered primary key + lenght of index key may be greater than 4096 which results in `tikv aborts txn: KeyTooLarge(5562, 4096)`. I think we can relax it to 8192.

### PR DESCRIPTION
**Pull request by TonsnakeLin**
### What problem does this PR solve?

Issue Number: close #11241 

Problem Summary:
Create a table from tidb-server successfully, but insert data failed if it has the length over 4096.  Set the default value of storage.max-key-size to 8192 and It insert data successfully.

### What is changed and how it works?

What's Changed:
Change the default value of storage.max-key-size from 4k to 8k.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Review by youjiali1995 — COMMENTED** [review]
Should change the value in `test_serde_custom_tikv_config` and `tests/integrations/config/test-custom.toml`. https://github.com/tikv/tikv/blob/999ca556005ed5c3b7ccbceb511806a5da365c45/tests/integrations/config/mod.rs#L615

**Comment by youjiali1995** [comment]
@TonsnakeLin You have to use `git commit -s --amend` to modify your last commit message to contain `close #11241` and add a signoff.

**Comment by TonsnakeLin** [comment]
> Should change the value in `test_serde_custom_tikv_config` and `tests/integrations/config/test-custom.toml`.
> 
> https://github.com/tikv/tikv/blob/999ca556005ed5c3b7ccbceb511806a5da365c45/tests/integrations/config/mod.rs#L615

got it！

**Comment by TonsnakeLin** [comment]
@youjiali1995 @sticnarf please review or approve, thanks

**Comment by sticnarf** [comment]
Please change https://github.com/tikv/tikv/blob/225bbdd70ea128040827a9a45d18c8518315ff12/tests/integrations/config/test-custom.toml#L83 to a different value and also change the related tests. Otherwise, we cannot verify the config can be customized successfully.

**Comment by MyonKeminta** [comment]
> Should change the value in `test_serde_custom_tikv_config` and `tests/integrations/config/test-custom.toml`.
> 
> https://github.com/tikv/tikv/blob/999ca556005ed5c3b7ccbceb511806a5da365c45/tests/integrations/config/mod.rs#L615

Looks that this comment is still not addressed?

**Review by youjiali1995 — APPROVED** [review]

**Review by sticnarf — APPROVED** [review]

**Pull request merged**
