### PR TITLE
copr: vectorize HexStrArg

### PR DESCRIPTION
**Pull request by MaiCw4J**
Signed-off-by: mak <610546069@qq.com>

PCP #5751 
###  What have you changed?

Add vectorized HexStrArg

###  What is the type of the changes?

Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?
Please select the tests that you ran to verify your changes:
- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No. It should not change the behavior.

###  Does this PR affect `tidb-ansible`?

No

### CODE REVIEW

**Comment by MaiCw4J** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/48

**Comment by breeswish** [comment]
Please fix conflicts, thanks!

**Comment by MaiCw4J** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/48

**Pull request merged**
