### PR TITLE
charset: support utf8mb4_0900_ai_ci collation

### LINKED ISSUE #15328: Support the utf8mb4_0900_ai_ci collation
## Development Task

Ref https://github.com/pingcap/tidb/issues/37566. TiDB is going to support `utf8mb4_0900_ai_ci` collation. TiKV should also support it.

### PR DESCRIPTION
**Pull request by YangKeao**
### What is changed and how it works?

Issue Number: Close #15328

What's Changed:

1. A new collation `utf8mb4_0900_ai_ci` is added into TiKV.
2. Some tiny refractor to make it easier to add UCA collations in the future.

Ref, the TiDB's implementation: https://github.com/pingcap/tidb/pull/45650

### Check List 

Tests 

- [x] Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### Release note 

```release-note
Support the `utf8mb4_0900_ai_ci` collation.
```

### CODE REVIEW

**Review by breezewish — APPROVED** [review]

**Review by sticnarf — APPROVED** [review]

**Comment by YangKeao** [comment]
@breezewish @sticnarf Can you help to merge this PR?

**Pull request merged**
