### PR TITLE
copr: Add vectorize is_ipv4/6

### PR DESCRIPTION
**Pull request by gauss1314**
Signed-off-by: gauss <gauss1314@gmail.com>

PCP #5751 

###  What have you changed?

Add vectorize is_ipv4/6

###  What is the type of the changes?

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?
- Unit test
- Integration test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No

###  Does this PR affect `tidb-ansible`?

No

### CODE REVIEW

**Comment by gauss1314** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/75

**Comment by gauss1314** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/75

**Comment by breeswish** [comment]
@nolouch PTAL, thanks!

**Comment by breeswish** [comment]
Please fix conflicts. Thanks!

**Comment by gauss1314** [comment]
> Please fix conflicts. Thanks!

Please merge. Thank you~

**Comment by breeswish** [comment]
@rleungx @nolouch Please review again. Thanks!

**Pull request merged**
