### PR TITLE
Fuzz: oss-fuzz integration

### PR DESCRIPTION
**Pull request by catenacyber**
### What problem does this PR solve?

Issue Number: none

Problem Summary:
This is a preparation for oss-fuzz integration cf https://github.com/google/oss-fuzz/pull/5702
cc @breeswish 

### What is changed and how it works?

What's Changed:
- bump fuzzers crates versions
- use another option `build` to fuzz utility (to build and not run a target)

### Check List 

Tests 
- Integration test

Well, this is adding more integrations tests...

### Release note

- No release note

### CODE REVIEW

**Review by breeswish — APPROVED** [review]
Thanks for the change! You need to [sign-off](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for) **all of** your commits in order to pass the DCO check.

/cc @nrc @overvenus PTAL, thanks!

**Comment by catenacyber** [comment]
Just did the sign-off

**Comment by catenacyber** [comment]
@breeswish do I need to do something ?
This looks good to me with current google/oss-fuzz#5702 whose CI is green

**Comment by catenacyber** [comment]
friendly ping @breeswish ?

**Comment by catenacyber** [comment]
Friendly ping @overvenus what do I need to do now ?

**Comment by catenacyber** [comment]
Should I do something or close this ?

**Comment by catenacyber** [comment]
I can do a rebase if there is interest in this...

**Comment by catenacyber** [comment]
Closing as stale cc @breezewish 
would you still want it ?

**Pull request closed without merging**
