### PR TITLE
[DNM] test the push_down_func_test of tidb-tests

### PR DESCRIPTION
**Pull request by H-ZeX**
Signed-off-by: H-ZeX <hzx20112012@gmail.com>

This PR just for test the push_down_func_test of tidb-tests

### CODE REVIEW

**Comment by H-ZeX** [comment]
/run-integration-pushDownFuncTest-test tidb=master tikv=master pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by qrr1995** [comment]
/run-all-tests  tidb=master tikv=master pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-all-tests tidb=master tikv=master pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-all-tests tidb=master tikv=master pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-all-tests tidb=master tikv=master pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-all-tests tidb=master tikv=master pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-all-tests tidb=master tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFuncTest-tests tidb=master tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFuncTest tidb=master tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by qrr1995** [comment]
/run-integration-pushDownFunc-test  tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master
--

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master
--

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master
--

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master
--

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

Merge state

**Comment by H-ZeX** [comment]
/run-integration-pushDownFunc-test tikv=pr/5098 pd=master tidb-test=pr/857 tidb-private-test=master

**Pull request closed without merging**
