### PR TITLE
multi-rocksdb: avoid mutex deadlock between open_tablet() and create_shared_db()

### LINKED ISSUE #13463: deadlock on root_db lock by open_tablet() for tablet factory
### What version of TiKV are you using?

mater

### Steps to reproduce

Call open_tablet with create or create_new option is on

### What did you expect?
Case run successfully

### What did happened?
Case hang for root_db lock contention between KvEngineFactory::open_tablet() and its callee KvEngineFactory::create_shareed_db()

### PR DESCRIPTION
**Pull request by BornChanger**
Signed-off-by: BornChanger <dawn_catcher@126.com>

### What is changed and how it works?

Issue Number: Close #13463 

What's Changed:

``` 
Avoid holding mutex to root_db when open_tablet() calling create_shared_db() since root db creation won't bring racing, otherwise, mutex deadlock occurs.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by BornChanger** [comment]
cc /@BusyJay /@tonyxuqqi

**Comment by BornChanger** [comment]
cc @BusyJay @tonyxuqqi

**Review by BusyJay — APPROVED** [review]
Interesting. This is a pitfall in Rust exists for quite a long time. Perhaps we should have some lint.

**Review by tonyxuqqi — APPROVED** [review]

**Review by SpadeA-Tang — APPROVED** [review]

**Pull request merged**
