### PR TITLE
backup: support explicitly set sst compression type (#8200)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #8200 to release-4.0

---

### What problem does this PR solve?
App support for backup to explicitly choose the sst compression algorithm.

Problem Summary:

### What is changed and how it works?
Add a associated type for `SstExt` to set Engine specified Configs.  And add `CompressionType` params for  `BackupWriter` and `BackupRawKVWriter` to make sst write compression type can be determined by BackupRequest.

What's Changed:

### Related changes
- https://github.com/pingcap/kvproto/pull/642 

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

### Release note 
- No release note

### CODE REVIEW

**Comment by glorv** [comment]
blocked by https://github.com/pingcap/kvproto/pull/647

**Comment by MyonKeminta** [comment]
@glorv  pingcap/kvproto#647 is merged. Please continue finishing this PR, thanks

**Pull request merged**
