### PR TITLE
Bump to 2.1.5

### PR DESCRIPTION
**Pull request by nolouch**
## What have you changed? (mandatory)
Bump v2.1.5.

### CODE REVIEW

**Comment by nolouch** [comment]
/run-all-tests tidb=release-2.1 pd=release-2.1 tidb-test=release-2.1 tidb-private-test=release-2.1

**Comment by nolouch** [comment]
/run-all-tests tidb=release-2.1 pd=release-2.1 tidb-test=release-2.1 tidb-private-test=release-2.1

**Comment by cwen0** [comment]
/run-integration-ddl-test tidb=release-2.1 pd=release-2.1 tidb-test=release-2.1 tidb-private-test=release-2.1

**Comment by cwen0** [comment]
/run-all-tests tidb=release-2.1 pd=release-2.1 tidb-test=release-2.1 tidb-private-test=release-2.1

**Pull request merged**
