### PR TITLE
txn: write protected rollback when cleanup with missing lock

### PR DESCRIPTION
**Pull request by andylokandy**
Signed-off-by: Dian Luo <andylokandy@hotmail.com>

### What problem does this PR solve?

Closes https://github.com/tikv/tikv/issues/7364

`MvccTxn::check_txn_status_missing_lock()` now writes protected on rollback.

### Check List 

Tests 

- Unit test
- Integration test

### Release note

### CODE REVIEW

**Comment by sticnarf** [comment]
@andylokandy Please fix the unit tests.

**Comment by sticnarf** [comment]
Please also take a look @coocood  @tiancaiamao @youjiali1995

**Comment by coocood** [comment]
LGTM

**Comment by andylokandy** [comment]
@sticnarf @MyonKeminta @coocood  Test is fixed. PTAL

**Comment by andylokandy** [comment]
Do we need to cherry-pick to 3.0?

**Comment by andylokandy** [comment]
@sticnarf @MyonKeminta I can't reason about the error...

**Pull request merged**
