### PR TITLE
external_storage: support virtual-host style for s3

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve?

Issue Number: close pingcap/br#484

Problem Summary:

TiKV uses the official `rusoto_s3` which did not support "Virtual Host" addressing style (rusoto/rusoto#1482), which is mandated by Aliyun OSS and some other third-party S3 clones.

### What is changed and how it works?

What's Changed:

There is already a PR fixing this (rusoto/rusoto#1823), but since Amazon [postponed](https://aws.amazon.com/blogs/storage/update-to-amazon-s3-path-deprecation-plan/) the path-style doomsday indefinitely, there seems to be no pressure on rusoto maintainers to review it ASAP. 

This PR thus replaced all rusoto dependencies by the version in rusoto/rusoto#1823 to get Virtual Host support. 

### Related changes

- Need to cherry-pick to the release branch (release-5.0, release-4.0)

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
   * TODO: test against S3 with virtual-host style

Side effects

### Release note 

* BR now supports S3-compatible storage using virtual-host addressing style.

### CODE REVIEW

**Comment by gregwebs** [comment]
There is risk in referencing a github repo that is not officially maintained. Can you create a rusoto fork under the TiKV org?

This PR states that rusoto maintainers are not merging a change. However, I believe that is inaccurate. The issue seems to be that the changes are still in a Draft PR that requires additional testing. Can we ensure adequate testing for these changes? Then perhaps it will get merged upstream quickly.

The PR states that this can cause issues for users that still need the old path style: can we add a configuration option for that in TiKV?

**Comment by kennytm** [comment]
> Can we ensure adequate testing for these changes? Then perhaps it will get merged upstream quickly.

Well it involves *two* parties we can't control (the PR submitter and rusoto maintainers) and the PR has been stale I won't bet on this route.

> The PR states that this can cause issues for users that still need the old path style: can we add a configuration option for that in TiKV?

There is already such config: in BR you could add `force-path-style=1` in the storage string like

```sql
BACKUP DATABASE * TO 's3://bucket/prefix?force-path-style=1';
```

**Comment by gregwebs** [comment]
> Well it involves two parties we can't control (the PR submitter and rusoto maintainers) and the PR has been stale I won't bet on this route.

We control the code we are taking in now (and thanks for putting the code under the TiKV org). So we can just submit our own PR if the original submitter is unable to. This path will avoid the maintenance burden of having a fork. Of course we won't rely on it being merged in the short-term, but it is best to start that process (of sending a completed PR) before merging here.

> There is already such config: in BR you could add force-path-style=1 in the storage string like

Oh, great, it is already documented as well.

**Comment by gregwebs** [comment]
@kennytm I can help to get a PR sent upstream, let me know.

**Comment by kennytm** [comment]
https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/167/pipeline/21

```
[2021-05-14T11:15:20.704Z] thread 'rustc' panicked at 'assertion failed: `(left == right)`
[2021-05-14T11:15:20.704Z]   left: `Some(Fingerprint(9872699086643728891, 4134961135440435754))`,
[2021-05-14T11:15:20.704Z]  right: `Some(Fingerprint(7876766839863059571, 16500784993940780497))`: found unstable fingerprints for native_libraries(grpcio_sys[acec]): 
```

The test failed with the same issue as https://blog.rust-lang.org/2021/05/10/Rust-1.52.1.html#what-should-a-rust-programmer-do-in-response. Recommendations?

**Review by yiwu-arbug — APPROVED** [review]
LGTM

**Pull request merged**
