### PR TITLE
fuzz: Bump afl version

### LINKED ISSUE #15847: Build fails due to `afl` dependency in DEBUG mode
## Bug Report

When building the project in DEBUG mode, the build script of `afl` fails with the following message

```
  [*] Testing the CC wrapper and instrumentation output...
  unset AFL_USE_ASAN AFL_USE_MSAN; AFL_QUIET=1 AFL_INST_RATIO=100 AFL_PATH=. ./afl-clang -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/lib/afl\" -DDOC_PATH=\"/share/doc/afl\" -DBIN_PATH=\"/bin\" test-instr.c -o test-instr 
  echo 0 | ./afl-showmap -m none -q -o .test-instr0 ./test-instr
  echo 1 | ./afl-showmap -m none -q -o .test-instr1 ./test-instr
  Oops, the instrumentation does not seem to be behaving correctly!
  Please ping <lcamtuf@google.com> to troubleshoot the issue.
  --- stderr
  make: *** [test_build] Error 1
  thread 'main' panicked at 'assertion failed: status.success()', /Users/xiaoyawei/.cargo/registry/src/github.com-1ecc6299db9ec823/afl-0.6.0/build.rs:33:5
```

Similar issue can be found in `afs.rs` like https://github.com/AFLplusplus/AFLplusplus/issues/533

### What version of TiKV are you using?

Master branch.

### What operating system and CPU are you using?

OS: MacOS
CPU: `machdep.cpu.brand_string: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz`

### Steps to reproduce

 
```bash
cargo run --package fuzz -- run afl fuzz_codec_bytes
```

### What did you expect?

Build succeeds

### What did happened?

It fails.

### PR DESCRIPTION
**Pull request by xiaoyawei**
### What is changed and how it works?

Issue Number: Close #15847

What's Changed:

Bump `afl` version to include the fix of the original issue

```commit-message
    bump afl version

    Bump afl to a new version that can successfully builds on MacOS.

    close tikv/tikv#15847
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`: NA
- Need to cherry-pick to the release branch: No

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

Run `cargo run --package fuzz -- run afl fuzz_codec_bytes` to make sure fuzz testing works with afl

Side effects

None

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]
Thanks!

**Review by glorv — APPROVED** [review]

**Comment by xiaoyawei** [comment]
/assign @overvenus 

Could you help me merge this? Thanks!

**Pull request merged**
