### PR TITLE
Fix unstable test about slow node detection

### LINKED ISSUE #11197: Unstable test about slow store detection
## Bug Report

See https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/9938/pipeline/

### PR DESCRIPTION
**Pull request by 5kbpers**
Signed-off-by: 5kbpers <tangminghua@pingcap.com>

### What problem does this PR solve?

Issue Number: close #11197

Problem Summary:
If there is not any write, write workers will skip replying latency inspecting, which makes `test_latency_inspect` unstable.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
* Move back latency inspecting of store loop to `end`
* Add `store_write` duration for inspecting write duration.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by gengliqi — APPROVED** [review]

**Review by sticnarf — APPROVED** [review]
LGTM

**Comment by 5kbpers** [comment]
`cases::test_merge::test_node_merge_cascade_merge_with_apply_yield` is very unstable. https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/9963/pipeline

**Pull request merged**
