### PR TITLE
copr: Add cast_year_as_time (#9287)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #9287 to release-4.0

---

Signed-off-by: Zhenchi <zhongzc_arch@outlook.com>

### What problem does this PR solve?

Issue Number: https://github.com/pingcap/tidb/issues/20121

### What is changed and how it works?

Add `cast_year_as_time`

### Related changes

- https://github.com/pingcap/tidb/pull/20233

### Check List 

Tests 

- Unit test
- Integration test

### Release note
- Add `cast_year_as_time`

### CODE REVIEW

**Review by Xuanwo — APPROVED** [review]

**Review by tabokie — APPROVED** [review]

**Comment by hi-rustin** [comment]
This cherry pick PR is for a release branch and has not yet been approved by release team.
Adding the do-not-merge/cherry-pick-not-approved label.

To merge this cherry pick, it must first be approved (/lgtm + /merge) by the collaborators.

AFTER it has been approved by collaborators, please ping the release team in a comment to request a cherry pick review

**Pull request merged**
