### PR TITLE
*: update deps

### PR DESCRIPTION
**Pull request by BusyJay**
### What problem does this PR solve?

To resolve RUSTSEC-2020-0151 and RUSTSEC-2021-0013.

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

### Release note 
- No release note.

### CODE REVIEW

**Review by sticnarf — APPROVED** [review]
LGTM. Although the two security issues should only affect tests and benches.

**Comment by BusyJay** [comment]
> Although the two security issues should only affect tests and benches.

Yes, but it keep waking up the alert.

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by BusyJay** [comment]
@5kbpers would you like to take a look at the fail case? I can reproduce it on my local machine with master.

**Pull request merged**
