### PR TITLE
copr: vectorize BitLength

### PR DESCRIPTION
**Pull request by MaiCw4J**
PCP #5751 
###  What have you changed?

Add vectorized BitLength

###  What is the type of the changes?

Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?
Please select the tests that you ran to verify your changes:
- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No. It should not change the behavior.

###  Does this PR affect `tidb-ansible`?

No

### CODE REVIEW

**Comment by MaiCw4J** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/43

**Comment by MaiCw4J** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/43

**Comment by breeswish** [comment]
@sticnarf @lonng @andylokandy @iosmanthus PTAL

**Pull request merged**
