### PR TITLE
raft_log_engine: fix managedfs create encrypted file

### LINKED ISSUE #12162: Failed to create raft engine when encryption enabled.
### What version of TiKV are you using?

```
Release Version:   6.0.0-alpha
Edition:           Community
Git Commit Hash:   1047b51285456e702b66253da26c7f14d582ff0c
Git Commit Branch: master
UTC Build Time:    2022-03-14 08:48:38
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
```

### Steps to reproduce

add some config in tikv.toml and then starts tikv-server
```
[security.encryption]
data-encryption-method = "aes256-ctr"

[security.encryption.master-key]
type = "file"
path = "/tmp/backup_restore_test/master-key-file"
```
### What did you expect?
tikv serves well.

### What did happened?
```
[2022/03/15 12:37:28.488 +08:00] [FATAL] [[server.rs:1372](http://server.rs:1372/)] ["Failed to create raft engine: \"[components/raft_log_engine/src/[engine.rs:440](http://engine.rs:440/)]: IO Error: Other error [components/encryption/src/[crypter.rs:83](http://crypter.rs:83/)]: Nonce + Counter must be 12/16 bytes, 0\""]
```

### PR DESCRIPTION
**Pull request by glorv**
Signed-off-by: glorv <glorvs@163.com>

### What is changed and how it works?

Issue Number: Close #12162

What's Changed:

```commit-message
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tabokie — APPROVED** [review]
Thanks~ I'm surprised that we don't have at least one unit test that opens TiKV with encryption. Could you add one?

**Comment by hunterlxt** [comment]
what happened if key_manager just create a new file but raft_log_engine failed to create this file?

**Comment by hunterlxt** [comment]
> > what happened if key_manager just create a new file but raft_log_engine failed to create this file? @tabokie
> 
> @hunterlxt Raft Engine creates the file, then key manager creates the key.

ok, looks like the sequence is right

**Pull request merged**
