### PR TITLE
copr: Fix panic when there is illegal push down

### PR DESCRIPTION
**Pull request by breezewish**
### What is changed and how it works?

Issue Number: Close https://github.com/tikv/tikv/issues/16531

What's Changed:

```commit-message
Fix possible panic when there is illegal push down to Coprocessor related with data type and aggregation.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by breezewish** [comment]
@YangKeao @iosmanthus PTAL, thanks!

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by wshwsh12 — APPROVED** [review]

**Pull request merged**
