### PR TITLE
Ingest SST instead of writing memtable directly when delete a large range of keys. (#7794)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #7794 to release-4.0

---

### What problem does this PR solve?

Issue Number: close [#7296](https://github.com/tikv/tikv/issues/7296)

Problem Summary:
TiKV deleted range by key and this would negatively affected write performance in apply-thread. Delete keys of each region mixed in one memtable also cause write-amplification. This PR is to solve this problem. It will insert the keys in a single SST and ingest it into RocksDB. If this file is not overlap with memtable and files in L0, it will be ingested into L1 or higher level. So it will avoid compacting with files in L0 and reduce write-amplification.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 
- No release note

### CODE REVIEW

**Comment by Connor1996** [comment]
Please fix the conflict @Little-Wallace

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by hicqu — APPROVED** [review]

**Pull request merged**
