### PR TITLE
Upgrade to Rust 2018

### PR DESCRIPTION
**Pull request by brson**
**Do not merge**

## What have you changed? (mandatory)

Upgrade Rust to nightly-2018-12-06, the final 1.32 nightly. Turn on Rust 2018.

This isn't ready to be merged yet, but this is most of the work and people can start reviewing if they want.

This is a pretty easy upgrade except for the changes to jemalloc. The compiler doesn't link to jemalloc in this version, but tikv expects it to. To fix this I've linked tikv to the jemallocator crate for all unix builds, installed the global allocator from within the library, and modified the code to not assume that jemalloc-specific symbols exist (`malloc_stats_print`).

The tikv library itself should ideally not be installing the global allocator, but we have a number of testing and bench bins, and it's a fair bit of boilerplate to instantiate in all of them. For now I think it's ok to have tikv be opinionated about its allocator, but I'm happy to make changes.

In upgrading jemalloc I moved from @BusyJay 's fork back to the published version. On cursory inspection, it _looked_ like newer jemallocs addressed the [problem patched in their fork](https://github.com/BusyJay/jemallocator/commit/871f558134b9243ecd083d1d0eefe57c56da8529), but PTAL @BusyJay.

One big question is whether jemalloc is using prefixed or unprefixed symbols. When unprefixed then RocksDB will use jemalloc; when prefixed then Rust will use jemalloc but RocksDB will use the system allocator. In production we (probably) want them both using the same allocator, so either jemalloc needs to be unprefixed, or RocksDB needs to be configured to use prefixed jemalloc.

The jemallocator crate [blacklists](https://github.com/alexcrichton/jemallocator/blob/master/jemalloc-sys/build.rs#L45) some platforms so that symbols must be prefixed. This includes macos surprisingly. But on Linux the symbols can be prefixed. So on Linux RocksDB and Rust _can_ share an allocator.

This PR does so by using the `unprefixed_malloc_on_supported_platforms` feature of the `jemallocator` crate. I have confirmed this by looking at the symbol definitions in tikv-server before and after.

Before linking to jemalloc at all `nm` reports the linkage of malloc as:

```
                 U malloc@@GLIBC_2.2.5
```

After linking to jemalloc and turning off the prefixes, it reports it as:

```
000000000231b92b T malloc
```

No other tikv dependencies needed to be upgraded for this PR - they all just worked with the chosen nightly.

I didn't bump any version numbers. If this were a stable published library we'd probably want to bump the major version since the 2018 changes likely break backwards compatibility.

Before merging the build needs to be tested on Windows and MacOS; integration tested with TiDB; rebased; and I think probably needs to be benchmarked against itself before the upgrade. Perhaps though CI does suitable integration testing so I don't need to.

There's some follow-on work to be done after this PR:

- Remove all the "extern crate"s.

- Remove instances of "raw symbols". I know that rustfix at least added some `r#async` symbols.

- It would be nice to in the future re-validate that we do want to be running jemalloc, and maybe try to tune it specifically for tikv's workload.

## What are the type of the changes? (mandatory)

Improvement

## How has this PR been tested? (mandatory)

Unit tested on Linux. I can also test on Windows, but not Mac. I suspect Windows still needs changes to build.

No integration testing or benchmarking yet.

## Does this PR affect documentation (docs) update? (mandatory)

No.

## Does this PR affect tidb-ansible update? (mandatory)

No.

**Do not merge**

## Refer to a related PR or issue link (optional)

https://github.com/tikv/tikv/issues/3896

### CODE REVIEW

**Comment by brson** [comment]
I'll check out the CI failures tomorrow.

**Comment by brson** [comment]
Ah, there are a few subprojects here that I didn't think to upgrade. I'll do those too before landing this.

**Comment by overvenus** [comment]
> I didn't bump any version numbers. If this were a stable published library we'd probably want to bump the major version since the 2018 changes likely break backwards compatibility.

FYI, we dont need to bump version number in this PR, because we have dumped to `3.0.0-alpha` already, and it is not released yet.

**Comment by brson** [comment]
I spent most of the day trying to understand and run the fuzzers, and I think both of them are broken by this patch, so I'm still trying to figure that out.

In the meantime, I'm thinking it would be safer to do this upgrade incrementally now that I've got a good idea of what's involved, so I'm probably going to step back and rebuild this patch set as a series of PRs. Here's my plan:

- Test prometheus, raft, grpc, and fail with the new compiler to make sure they work. Test the upgrades to Rust 2018 to make sure they will work later.
- Submit rustfix changes, maintaining compatibility with the current toolchain. This is the biggest part of the diff, so it would make the upgrade easier if it were already merged.
- Submit fixes for the mem-profiling build
- Upgrade the toolchain without upgrading to Rust 2018. Keep jemalloc and the fuzzers working.
- Upgrade TiKV to Rust 2018.
- Upgrade dependencies to Rust 2018.

So this PR is still useful for reviewing what the total changes are going to be, but as of now I plan to land some of this work via smaller PRs.

**Comment by brson** [comment]
I've moved the jemalloc upgrade to https://github.com/tikv/tikv/pull/3962.

Currently I'm making the clippy changes to this PR to try to get it to pass. Next I'll rebase this, and once the jemalloc PR lands, remove the jemalloc changes from this one, see how the CI feels.

**Comment by brson** [comment]
I'm going to go ahead and close this one, since doing the upgrade incrementally is working well and this branch is very out of date. Current PR is https://github.com/tikv/tikv/pull/4000

**Pull request closed without merging**
