### PR TITLE
expr/builtin_fncall: implement HexIntArg, HexStrArg

### PR DESCRIPTION
**Pull request by sweetIan**
## What have you changed? (mandatory)

expr/builtin_fncall: implement string.{HexIntArg, HexStrArg}

## What are the type of the changes? (mandatory)

- New feature (non-breaking change which adds functionality)

## How has this PR been tested? (mandatory)

unit test

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

no

## Does this PR affect tidb-ansible update? (mandatory)

no

## Refer to a related PR or issue link (optional)

#3275

### CODE REVIEW

**Comment by sweetIan** [comment]
@AndreMouche mysql and tidb both return "C" for case 12.3. Do we need to support this in HexIntArg?
```
mysql> select hex(12.3);
+-----------+
| hex(12.3) |
+-----------+
| C         |
+-----------+
1 row in set (0.00 sec)
```

**Comment by hicqu** [comment]
@sweetIan we don't need to do that because both mysql and TiDB cast `12.3` to `12` already before call `hex`.

**Comment by hicqu** [comment]
LGTM.

**Comment by zz-jason** [comment]
@sweetIan please merge master and resolve conflicts 😄

**Pull request merged**
