### PR TITLE
metrics: remove min legend

### PR DESCRIPTION
**Pull request by tabokie**
Signed-off-by: tabokie <xy.tao@outlook.com>

### What problem does this PR solve?

Problem Summary:

Minimum legend isn't very useful, and it occupied valuable visual real estate.

### What is changed and how it works?

What's Changed:

Remove some min legends from Grafana metrics, except for the following:
- Level 0 chance
- Number files at each level
- File Count
- Entry Count
- Allocator Stats
- Encrypted files
- Encryption meta files size

### Check List 

Tests
- No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by Connor1996 — COMMENTED** [review]
some are useful, do you remove all of them?

**Comment by tabokie** [comment]
> some are useful, do you remove all of them?

Yes, I didn't check. Could you give an example for me to rule out?

**Review by Connor1996 — COMMENTED** [review]
like `ingest picked level`

**Comment by tabokie** [comment]
@Connor1996 Updated, only bandwidth/latency/qps are affected.

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by hunterlxt — APPROVED** [review]

**Pull request merged**
