### PR TITLE
tikv_alloc: update jemalloc to 5.2.1

### PR DESCRIPTION
**Pull request by BusyJay**
### What problem does this PR solve?

Problem Summary:

### What is changed and how it works?

Update jemalloc to 5.2.1 to address memory allocation problem in huge page

### Related changes

tikv/tikv#4515

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 
- update jemalloc to 5.2.1

### CODE REVIEW

**Comment by BusyJay** [comment]
@innerr You can merge to get tikv compatible with rust-rocksdb.

@brson Some changes are derived from your PR, PTAL.

**Comment by brson** [comment]
Forking jemalloc doesn't strike me as a good solution no matter what the problem.

**Comment by BusyJay** [comment]
Last time a PR is merged into master in upstream is the end of last year. My PRs have not been reviewed or responded for several months. Issues are not commented either. I suspect the upstream is not active anymore.

**Comment by brson** [comment]
OK.

**Pull request merged**
