### PR TITLE
Refactor search log batcing

### PR DESCRIPTION
**Pull request by andylokandy**
Signed-off-by: Dian Luo <andylokandy@hotmail.com>

###  What have you changed?

This PR simplified the `LogStream` introduced by https://github.com/tikv/tikv/pull/6356

###  What is the type of the changes?

- Engineering (engineering change which doesn't change any feature or fix any issue)

###  How is the PR tested?

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### CODE REVIEW

**Comment by mapleFU** [comment]
The code LGTM. But I wonder if there is any difference on performance?

**Comment by andylokandy** [comment]
It should have no performance change in my point of view.

**Pull request merged**
