### PR TITLE
raftstore: disable hibernate region except on master

### PR DESCRIPTION
**Pull request by BusyJay**
### What problem does this PR solve?

Problem Summary:

This PR adds a function to check if the binary is built on master
branch. Hibernate region is an experimental features that should
not be enabled on release branch, but it's enabled by accident on
5.0.0-rc. Checking branch name at build time can prevent such mistake
from happening again.

The side effect of the PR is binary built in PR will also have hibernate
regions disabled even it's checkout from master.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 
- disable hibernate region by default as it's still unstable

### CODE REVIEW

**Comment by NingLin-P** [comment]
> The side effect of the PR is binary built in PR will also have hibernate
regions disabled even it's checkout from master.

People can enable `hibernate-regions` by config file if they needed.

**Review by NingLin-P — APPROVED** [review]
LGTM

**Review by gengliqi — APPROVED** [review]

**Pull request merged**
