### PR TITLE
unify read pools with a single multi-level thread pool

### PR DESCRIPTION
**Pull request by sticnarf**
###  What have you changed?

This PR implements a thread pool running `Future`s and supports lowering the priority of long-running tasks. It also replaces all read pools in the existing TiKV.

The thread pool implementation is in the early stage. Any suggestions are welcome.

_(But don't care about the code style at the moment, it needs polishing of course)_

_This is still work in progress:_

- [x] Implement the thread pool
- [ ] Document the thread pool implementation
- [x] Add metrics for each level
- [ ] Test the thread pool 
- [x] Replace existing read pools
- [ ] Support configs and remove hard coded values
- [x] Dynamically adjust time use in each level
- [ ] Pass task id from client
- [x] Upgrade futures 0.3
- [ ] Benchmarks

###  What is the type of the changes?

Pick one of the following and delete the others:

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?
Please select the tests that you ran to verify your changes:
- Unit test
- Integration test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No

###  Does this PR affect `tidb-ansible`?

No

### CODE REVIEW

**Comment by mahjonp** [comment]
/bench
```
workload:
  threads: 512
```

**Comment by zhangjinpeng1987** [comment]
I suggest to split this huge pr to multiple little PRs, for example, first pr only import the new thread pool.

**Comment by sticnarf** [comment]
> I suggest to split this huge pr to multiple little PRs, for example, first pr only import the new thread pool.

OK. This one is just for people who are interested. :)

**Comment by mahjonp** [comment]
> ## Benchmark Report
> > Run TPC-H 10G Performance Test on VMs
> 
> ```diff
> @@                               Benchmark Diff                               @@
> ================================================================================
> tidb: 7ccbdc12b30d8aed1ab7904a7e96a3eee2ab55ce
> --- tikv: 55909d0377a147fab763cbe007a11aee276c6389
> +++ tikv: c9217d60f449c5a240b96a620bed0d4f1e2f416c
> pd: 895ccdb38eaf12f2421fcd03e0661f00447542e3
> ================================================================================
> ```

Because benchmark tests on current PR were all failed, did error were introduced by this PR?
 
image

**Comment by sticnarf** [comment]
@mahjonp The PR hasn't been updated for quite a time. Maybe the latest tidb is too new for it.

**Pull request closed without merging**
