### PR TITLE
raftstore: continue GC  snapshot files when it encounters a corrupted snapshot (#10831)

### LINKED ISSUE #10813: corrupted snapshot can prevent snapshot files gc
### What version of TiKV are you using?
v3.0.8

### What operating system and CPU are you using?
Doesn't matter.

### Steps to reproduce
Some of snapshot files get deleted after received, so the snapshot is corrupted. And the peer is deleted before applying snapshot.

### What did you expect?
Corrupted snapshot will be deleted in the end.

### What did happened?
Store fails to delete the corrupted snapshot files. And all other stale snapshot files are not gc anymore.

The problem is it returns early here:

https://github.com/tikv/tikv/blob/master/components/raftstore/src/store/fsm/store.rs#L2129.

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #10831 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/10872
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/10872:release-5.0-56b3ae673b13
```

---

### What problem does this PR solve?

Issue Number: close #10813 

Problem Summary:

### What is changed and how it works?
When snapshot GC runs into problem (such as file corrupted), today it stopped processing other GC-able snapshot files.
This PR will make it continue processing rest of the snapshot files.

### Related changes

Tests 
- Unit test

Side effects
No.

### Release note 

```release-note
RaftStore Snapshot GC fix: fix the issue that snapshot GC missed GC snapshot files when there's one snapshot file failed to be GC-ed. 
```
/cc @BusyJay

### CODE REVIEW

**Review by BusyJay — APPROVED** [review]

**Review by hicqu — APPROVED** [review]

**Comment by BusyJay** [comment]
@ti-chi-bot

**Pull request merged**
