### PR TITLE
do not force compact unreplicated entries (#12181)

### LINKED ISSUE #12161: raft log lag is more and more when down one tikv for 38min
### What version of TiKV are you using?
[2022/03/15 10:09:22.527 +08:00] [INFO] [client.go:376] ["Cluster version information"] [type=pd] [version=6.0.0-nightly] [git_hash=38ee0a8f7eeeaefbb43ccb708b1bb4a074d55594]
[2022/03/15 10:09:22.527 +08:00] [INFO] [client.go:376] ["Cluster version information"] [type=tikv] [version=6.0.0-alpha] [git_hash=b394b4d1e88b401c58e1255da043300c00cbe5c7]
[2022/03/15 10:09:22.527 +08:00] [INFO] [client.go:376] ["Cluster version information"] [type=tidb] [version=6.0.0-nightly] [git_hash=3f3a061afe93689ece19e43915a08f393ea83582]

### What operating system and CPU are you using?
8core、16G

### Steps to reproduce
1、[2022/03/15 10:09:22.647 +08:00] sysbench --mysql-user=root --db-driver=mysql --time=0 --report-interval=10 --mysql-db=test --mysql-host=tc-tidb.glh-master-64gs8 --mysql-port=4000 --threads=512 --tables=32 --table-size=10000000 --mysql-ignore-errors=2013,1213,1105,1205,8022,8027,8028,9004,9007 --rand-type=gaussian oltp_insert run
2、[2022/03/15 10:20:22.911 +08:00] [INFO] [chaos.go:358] ["fault will last for"] [duration=38m0s]
[2022/03/15 10:20:22.911 +08:00] [INFO] [util.go:59] ["Wait QPS recover after inject fault."] [wait=2m0s] [callBy=oltp_rel_001_006_test.go:79]
[2022/03/15 10:20:22.917 +08:00] [INFO] [chaos.go:86] ["Run chaos"] [name=failure] [selectors="[glh-master-64gs8/tc-tikv-2]"] [experiment="{\"Duration\":\"\",\"Scheduler\":null}"]

### What did you expect?
after fault recover，the raft log lag can be less and less and can be a little value in short time

### What did happened?
the raft log lag is more and more
image

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #12181 to release-6.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/12228
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/12228:release-6.0-ac32d5c8099a
```

---

Signed-off-by: tabokie <xy.tao@outlook.com>

### What is changed and how it works?

Issue Number: Close #12161

What's Changed:

Do not force compact entries that aren't replicated yet,

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests
- Unit test
- Integration test

Side effects

There will be more background writes when some TiKVs are down.

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tabokie — APPROVED** [review]

**Review by 5kbpers — APPROVED** [review]

**Comment by you06** [comment]
@VelocityLight PTAL again

**Pull request merged**
