### PR TITLE
config: enlarge max-manifest-file-size to 128MB (#4140)

### PR DESCRIPTION
**Pull request by huachaohuang**
This is a cherry pick, please refer to the original PR #4140 for more information.

### CODE REVIEW

**Comment by overvenus** [comment]
/run-all-tests tidb=release-2.1 pd=release-2.1 tidb-test=release-2.1 tidb-private-test=release-2.1

**Comment by huachaohuang** [comment]
/run-all-tests tidb=release-2.0 pd=release-2.0 tidb-test=release-2.0 tidb-private-test=release-2.0

**Comment by zyguan** [comment]
/run-all-tests tidb=release-2.0 pd=release-2.0 tidb-test=release-2.0 tidb-private-test=release-2.0

**Pull request merged**
