### PR TITLE
*: Don't use Error::description

### PR DESCRIPTION
**Pull request by brson**
Signed-off-by: Brian Anderson <andersrb@gmail.com>

### What problem does this PR solve?

Problem Summary:

Remove all uses of `Error::description`. This method is deprecated in current versions of Rust. The next toolchain upgrade will spew warnings about it without this patch.

### What is changed and how it works?

No errors define `description`, and no future errors should define `description`. The user-facing impact of this should be minimal - maybe a few error messages will change, probably for the better.

### Check List 

cargo check

### Release note

### CODE REVIEW

**Comment by brson** [comment]
It doesn't look like the errors could be from my patch.

**Comment by BusyJay** [comment]
@breeswish PTAL

**Comment by brson** [comment]
/merge

I'm trying to see whether the error is the same every CI run.

**Pull request merged**
