### PR TITLE
raftstore: better mailbox

### PR DESCRIPTION
**Pull request by BusyJay**
###  What have you changed?

This PR brings several changes to the implementation of mailbox and fsm model.

First, the underlying implement of mailbox is changed from channel to queue. Batch system has its own thread park/unpark mechanism, changing the mailbox to queue can reduce unnecessary thread switch related work and lead to better performance. We can also adapt the queue to mpsc in the future to make receiving more quickly.

Second, ref count and notify state are now merged together. Such way, each send/recv can save at least one atomic operations.

Third, fsm model is simplified. There is no more weird set_mailbox/take_mailbox call. And all internal state transition is maintained by the mailbox to make it easier to write correct code.

Microbench shows that the mailbox implement is faster than before:

Now:
```
test raftstore::store::fsm::router::tests::bench_send                 ... bench:          62 ns/iter (+/- 0)
```
Before:
```
test raftstore::store::fsm::router::tests::bench_send                 ... bench:         121 ns/iter (+/- 1)
```

###  What is the type of the changes?

- Engineering

###  How is the PR tested?

integration tests

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No.

###  Does this PR affect `tidb-ansible`?

No.

### CODE REVIEW

**Comment by siddontang** [comment]
oh, performance reduced.

@BusyJay

**Comment by zhangjinpeng1987** [comment]
I suggest you to split this pr. For example one pr import queue, one pr import channel, last pr use these two utilities.

**Comment by zhangjinpeng1987** [comment]
Is it possible to do some micro bench?

**Comment by BusyJay** [comment]
Close it for now. Will reopen when have time.

**Pull request closed without merging**
