### PR TITLE
raftstore: Fix compaction guard panic on non-data key

### PR DESCRIPTION
**Pull request by Connor1996**
### What problem does this PR solve?

Issue Number: close https://github.com/tikv/tikv/issues/11290 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed: Check if it is a non-data key when calling `origin_key` in compaction guard.

### Related changes

- None

### Check List 

Tests 

- Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by yiwu-arbug — APPROVED** [review]
Thanks for the fix!

**Review by MyonKeminta — APPROVED** [review]

**Pull request merged**
