### PR TITLE
log-backup: skip locks in write cf when restoring

### LINKED ISSUE #12538: [BR] Data inconsistency after br log restore
### What version of TiKV are you using?
[root@localhost ~]#  /data2/pp2/deploy/tidb-4001/bin/tidb-server -V
Release Version: v6.1.0-alpha
Edition: Community
Git Commit Hash: bbfbe137eba05f828a9fb40708a6f6805a3453f0
Git Branch: heads/refs/tags/v6.1.0-alpha
UTC Build Time: 2022-05-13 14:58:01
GoVersion: go1.18
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### What operating system and CPU are you using?
centos7, 16u
```
processor       : 39
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
stepping        : 1
microcode       : 0xb00002a
cpu MHz         : 2399.938
cache size      : 25600 KB
physical id     : 1
siblings        : 20
core id         : 12
cpu cores       : 10
apicid          : 57
initial apicid  : 57
fpu             : yes
fpu_exception   : yes
cpuid level     : 20
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_pt ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts spec_ctrl intel_stibp
bogomips        : 4404.48
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

```

### Steps to reproduce
1. Start to log backup task in upstream when there is workload running.
2. Do a PiTR restore to  "2022-05-15 18:15:00.000 +0800"

```
./br_retry restore point --pd [172.16.6.46:2379](http://172.16.6.46:2379/) --full-backup-storage 's3://nfs/fubin/pitr/pp2_full_0514?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http%3a%2f%[2fminio.pingcap.net](http://2fminio.pingcap.net/)%3a9000&force-path-style=true' --storage 's3://nfs/fubin/pitr/pp2_log_1?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http%3a%2f%[2fminio.pingcap.net](http://2fminio.pingcap.net/)%3a9000&force-path-style=true' --restore-ts "2022-05-15 18:15:00.000 +0800"
```
3. do a log restore from "2022-05-15 18:15:00.000 +0800" to  "2022-05-16 18:00:00.000 +0800"
```
06:09:49 root@172 ~ → ./br_retry restore point --pd [172.16.6.46:2379](http://172.16.6.46:2379/) --start-ts "2022-05-15 18:15:00.000 +0800" --restored-ts "2022-05-16 18:00:00.000 +0800"  --storage "s3://nfs/fubin/pitr/pp2_log_1?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http%3a%2f%[2fminio.pingcap.net](http://2fminio.pingcap.net/)%3a9000&force-path-style=true"
```
5. Do data consistency check between upstream (snapshot: 433244130508800000) and downstream
```
08:29:34 root@172 fubin → tiup ctl:v6.0.0 pd tso 433244130508800000
Starting component `ctl`: /root/.tiup/components/ctl/v6.0.0/ctl /root/.tiup/components/ctl/v6.0.0/ctl pd tso 433244130508800000
system:  2022-05-16 18:00:00 +0800 CST
logic:   0

```
### What did you expect?
Data consistency check should pass

### What did happened?
Data consistency check fails

### PR DESCRIPTION
**Pull request by YuJuncen**
Signed-off-by: Yu Juncen <yujuncen@pingcap.com>

### What is changed and how it works?

Issue Number: Close #12538

What's Changed:
- Don't remove dups in default CF when doing restoring.
- Don't restore writes with `write_type == Lock`, or it may override some writes.

```commit-message
Skip locks in write CF when restoring.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by 3pointer — APPROVED** [review]
LGTM

**Review by overvenus — APPROVED** [review]

**Review by joccau — APPROVED** [review]
LGTM

**Comment by YuJuncen** [comment]
/run-tests
tar: This does not look like a tar archive

**Comment by 3pointer** [comment]
/run-tests


```
[2022-05-18T11:51:19.290Z]     raftstore::test_replica_read::test_read_index_retry_lock_checking
```

**Comment by 3pointer** [comment]
/run-test
`
ases::test_conf_change::test_destroy_local_reader
`

**Pull request merged**
