### PR TITLE
Remove tls metrics group

### PR DESCRIPTION
**Pull request by Renkai**
### What problem does this PR solve?
Remove  `components/tikv_util/src/metrics/tls.rs`, since macro `make_auto_flush_static_metric!` already implements similar mechanism.

### Related changes

- https://github.com/tikv/rust-prometheus/pull/304

### Check List 

Tests 

- Unit test

Side effects

- None

### Release note

### CODE REVIEW

**Comment by Renkai** [comment]
@sre-bot /run-all-tests

**Comment by breeswish** [comment]
Maybe `coarsetime` dependency can be totally removed now?

**Comment by Renkai** [comment]
> Maybe `coarsetime` dependency can be totally removed now?

removed  now.

**Pull request merged**
