### PR TITLE
*: Fix link to TiDB Release Notes

### LINKED ISSUE #13720: Fix broken TiDB changelog link
TiDB CHANGELOG.md has been removed via https://github.com/pingcap/tidb/pull/34369 then the current link shows 404.

https://github.com/tikv/tikv/blob/9f707fd941819f0bd22b2b03ea02f3e98d84a024/CHANGELOG.md?plain=1#L3

### PR DESCRIPTION
**Pull request by yahonda**
### What is changed and how it works?

Issue Number: close #13720

TiDB CHANGELOG.md has been removed via https://github.com/pingcap/tidb/pull/34369 then the current link shows 404.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 
- No code

Side effects

### Release note
```
None
```

### CODE REVIEW

**Comment by sticnarf** [comment]
Can you please sign off your commit to pass the DCO check? Thanks!

**Comment by yahonda** [comment]
Signed off my commit. Thanks for the info.

**Review by sticnarf — APPROVED** [review]

**Review by AndreMouche — APPROVED** [review]
LGTM

**Pull request merged**
