### PR TITLE
*: add shell.nix for more convenient build

### PR DESCRIPTION
**Pull request by iosmanthus**
Signed-off-by: iosmanthus <myosmanthustree@gmail.com>

### What problem does this PR solve?

Add shell.nix to enable create virtual shell enviroment using nix-shell.

What's Changed:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

```sh
nix-shell shell.nix
make
make test
```

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tisonkun — CHANGES_REQUESTED** [review]
Can you add a document on for nix user? Maybe by adding a new file under `doc` folder.

**Comment by BusyJay** [comment]
I don't think it's a good idea. We can't support every platforms and these files will not be maintained actively.

**Comment by iosmanthus** [comment]
> I don't think it's a good idea. We can't support every platforms and these files will not be maintained actively.

Nix is a package manager, `nix-shell` just like docker providing a virtual environment, besides, it could provide a formal description of all the dependencies you need to develop on TiKV instead declare them in doc. Here is an example from [kitty](https://github.com/kovidgoyal/kitty/blob/master/shell.nix)

**Comment by iosmanthus** [comment]
> I don't think it's a good idea. We can't support every platforms and these files will not be maintained actively.

Nix is a package manager, it just like docker providing a virtual enviroment 

> I don't think it's a good idea. We can't support every platforms and these files will not be maintained actively.

For maintainability, the Rust project is almost static linked, with few system dependencies we need to maintain.

**Comment by iosmanthus** [comment]
> Can you add a document on for nix user? Maybe by adding a new file under `doc` folder.

`shell.nix` for most Nix user is interpretative enough, just like `Dockerfile`

**Comment by BusyJay** [comment]
> > I don't think it's a good idea. We can't support every platforms and these files will not be maintained actively.
> 
> Nix is a package manager, it just like docker providing a virtual enviroment

It doesn't matter. We only support what we will maintain.

> > I don't think it's a good idea. We can't support every platforms and these files will not be maintained actively.
> 
> For maintainability, the Rust project is almost static linked, with few system dependencies we need to maintain.

For maintenance, I mean someone needs to understand what `Nix` is, verify it works and fix bugs.

**Comment by iosmanthus** [comment]
> > > I don't think it's a good idea. We can't support every platforms and these files will not be maintained actively.
> > 
> > 
> > Nix is a package manager, it just like docker providing a virtual enviroment
> 
> It doesn't matter. We only support what we will maintain.
> 
> > > I don't think it's a good idea. We can't support every platforms and these files will not be maintained actively.
> > 
> > 
> > For maintainability, the Rust project is almost static linked, with few system dependencies we need to maintain.
> 
> For maintenance, I mean someone needs to understand what `Nix` is, verify it works and fix bugs.

Make sense to me. However, my main concern is our projects' dependency management is some kind of annoying. For instance, If someone is working on https://github.com/pingcap/kvproto, he needs a specific version of `protoc`, which is currently locked at `3.8.0`. When he wants to work with https://github.com/pingcap/tipb, he needs `protoc 3.5.1` which is really annoying. Multiple version control could be achieved by some tools like `Dokcer` but you need to pull over lots of images and consume more resources when making some change to source code. So I am trying to use `nix` to manage these dependencies for me. It works just fine right now. I hope more people can participate in this discussion. I will close this pull request depending on the discussion.

**Comment by iosmanthus** [comment]
> > > I don't think it's a good idea. We can't support every platforms and these files will not be maintained actively.
> > 
> > 
> > Nix is a package manager, it just like docker providing a virtual enviroment
> 
> It doesn't matter. We only support what we will maintain.
> 
> > > I don't think it's a good idea. We can't support every platforms and these files will not be maintained actively.
> > 
> > 
> > For maintainability, the Rust project is almost static linked, with few system dependencies we need to maintain.
> 
> For maintenance, I mean someone needs to understand what `Nix` is, verify it works and fix bugs.

For maintenance, we could add some tests to CI/CD to check if this shell env could really build TiKV.

**Comment by BusyJay** [comment]
> If someone is working on https://github.com/pingcap/kvproto, he needs a specific version of `protoc`, which is currently locked at `3.8.0`. When he wants to work with https://github.com/pingcap/tipb, he needs `protoc 3.5.1` which is really annoying

No protoc is required for TiKV. Only when building CPP code for kvproto requires protoc.

**Comment by iosmanthus** [comment]
> > If someone is working on https://github.com/pingcap/kvproto, he needs a specific version of `protoc`, which is currently locked at `3.8.0`. When he wants to work with https://github.com/pingcap/tipb, he needs `protoc 3.5.1` which is really annoying
> 
> No protoc is required for TiKV. Only when building CPP code for kvproto requires protoc.

`prost-build` shows that it [needs](https://docs.rs/prost-build/#sourcing-protoc) `protoc` when I execute `make test`. Here is the error logs when I compile TiKV in pure shell env.
```sh
[nix-shell:~/projects/db/tikv]$ make test
./scripts/test-all
make[1]: Entering directory '/home/iosmanthus/projects/db/tikv'
   Compiling collections v0.1.0 (/home/iosmanthus/projects/db/tikv/components/collections)
   Compiling log_wrappers v0.0.1 (/home/iosmanthus/projects/db/tikv/components/log_wrappers)
   Compiling profiler v0.0.1 (/home/iosmanthus/projects/db/tikv/components/profiler)
   Compiling error_code v0.0.1 (/home/iosmanthus/projects/db/tikv/components/error_code)
   Compiling pprof v0.4.2
error: failed to run custom build command for `pprof v0.4.2`

Caused by:
  process didn't exit successfully: `/home/iosmanthus/projects/db/tikv/target/debug/build/pprof-8cf721d256ea5efd/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: NotFound, error: "failed to invoke protoc (hint: https://docs.rs/prost-build/#sourcing-protoc): No such file or directory (os error 2)" }', /home/iosmanthus/.cargo/registry/src/github.com-1ecc6299db9ec823/pprof-0.4.2/build.rs:5:72
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:493:5
     1: core::panicking::panic_fmt
               at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/panicking.rs:92:14
     2: core::result::unwrap_failed
               at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/result.rs:1355:5
     3: core::result::Result<T,E>::unwrap
               at /home/iosmanthus/.rustup/toolchains/nightly-2021-04-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1037:23
     4: build_script_build::main
               at ./build.rs:5:5
     5: core::ops::function::FnOnce::call_once
               at /home/iosmanthus/.rustup/toolchains/nightly-2021-04-15-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: build failed
make[1]: *** [Makefile:262: run] Error 101
make[1]: Leaving directory '/home/iosmanthus/projects/db/tikv'
make: *** [Makefile:270: test] Error 2
```

**Comment by BusyJay** [comment]
prost-build will use its bundled protoc unless environment variables `PROTOC` is set.

**Comment by tisonkun** [comment]
Closed as no consensus.

**Pull request closed without merging**
