### PR TITLE
1 apply thread and 1 raftstore thread is better in 8c machine

### PR DESCRIPTION
**Pull request by zhangjinpeng87**
Signed-off-by: zhangjinpeng1987 <zhangjinpeng@pingcap.com>

###  What have you changed?

Tune apply/rafstore threads in 8C machine.

###  What is the type of the changes?

Pick one of the following and delete the others:

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?
Please select the tests that you ran to verify your changes:
- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No

###  Does this PR affect `tidb-ansible`?

No

### CODE REVIEW

**Comment by siddontang** [comment]
can we combine raftstore, apply and read pool together with #5828 later?

**Comment by sticnarf** [comment]
> can we combine raftstore, apply and read pool together with #5828 later?

In the discussion yesterday, we think it mightn't be a good idea to mix read and write thread pools.

**Comment by BusyJay** [comment]
Any performance statistic that shows the difference?

**Comment by zhangjinpeng87** [comment]
Close PR since it is stale for years.

**Pull request closed without merging**
