### PR TITLE
copr: Add vectorized left and right

### PR DESCRIPTION
**Pull request by at15**
PCP #5751

###  What have you changed?

Add vectorized left and right (non UTF8 version)

###  What is the type of the changes?

- New feature (a change which adds functionality)

###  How is the PR tested?

- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No

###  Does this PR affect `tidb-ansible`?

No

###  Refer to a related PR or issue link (optional)

#5751

### CODE REVIEW

**Comment by at15** [comment]
@sre-bot /run-integration-copr-test

**Comment by TennyZhuang** [comment]
@sre-bot /run-integration-copr-test

**Comment by TennyZhuang** [comment]
@sre-bot LGTM

**Pull request merged**
