### PR TITLE
copr, json: handle u64 json correctly

### LINKED ISSUE #16512: Incorrect result for json compare and `json_contains`
### Steps to reproduce

Ref https://github.com/pingcap/tidb/issues/50826

Run `json_contains('[9223372036854775807, 9817290126226250029]', '9223372036854775808')` on TiKV, TiKV gives `true`, but TiDB gives `false`.

### PR DESCRIPTION
**Pull request by YangKeao**
### What is changed and how it works?

Issue Number: Close #16512

What's Changed:

Previously, the `u64` given by serde is parsed into `i64` or `float64`. However, it should be `u64` to be compatible with TiDB and MySQL.

```commit-message

```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [x] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Fix the issue that the JSON integers which exceed the i64 range but are within the u64 range are parsed as f64 instead of u64.
```

### CODE REVIEW

**Review by breezewish — APPROVED** [review]

**Comment by YangKeao** [comment]
@breezewish @gengliqi Could you help me to triage the issue? It seems that I cannot use `/affects` command to add tags to the issue 🤔 .

**Comment by YangKeao** [comment]
@breezewish @gengliqi and /merge, please? ❤️

**Pull request merged**
