### PR TITLE
copr: improve like algorithm performance

### PR DESCRIPTION
**Pull request by TennyZhuang**
PCP #5709
 Signed-off-by: TennyZhuang zty0826@gmail.com

###  What have you changed?

#5709

Please explain in detail what the changes are in this PR and why they are needed:

- Optimize like() implementation by a better like algorithm to avoid common glob attacks, described in https://research.swtch.com/glob.
- The main idea is backtrace always return to last `%`, so that every character will be traversed at most twice.
- Optimize the worst time complexity of `like(T, P)` from `O(2^len(P))` to `len(P) + len(T)`.

###  What is the type of the changes?

Pick one of the following and delete the others:

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?
Please select the tests that you ran to verify your changes:
- Unit test
- Manual test (add detailed scripts or steps below)

Some benchmark code in https://github.com/TennyZhuang/like-bench/

###  Does this PR affect `tidb-ansible`?

No

###  Refer to a related PR or issue link (optional)

#5709

###  Benchmark result if necessary (optional)

A little overhead on naive pattern, but some optimization on complicated pattern and huge improvement on attack.

E.g.:

For input `(r#"Hello, World"#, r#"Hello, %"#, '\\', Some(1))`

```
like 2                  time:   [12.410 ns 12.462 ns 12.525 ns]
Found 19 outliers among 100 measurements (19.00%)
  3 (3.00%) high mild
  16 (16.00%) high severe

like_optimize 2         time:   [15.834 ns 15.979 ns 16.184 ns]
Found 12 outliers among 100 measurements (12.00%)
  4 (4.00%) high mild
  8 (8.00%) high severe
```

A little overhead.

And for input `(r#"3hello"#, r#"%_hello"#, '%', Some(1))`

```
like 29                 time:   [14.004 ns 14.573 ns 15.403 ns]
Found 10 outliers among 100 measurements (10.00%)
  3 (3.00%) high mild
  7 (7.00%) high severe

like_optimize 29        time:   [9.7671 ns 9.8921 ns 10.031 ns]
Found 6 outliers among 100 measurements (6.00%)
  5 (5.00%) high mild
  1 (1.00%) high severe
```

about 50% improvement.

The most important is glob attack, for a special constructed input (target="a"*100, pattern="a%"*n+b), original like implementation will produce a terrible result.

31573469938_ pic

And after optimization, the cost is almost linear even on large input size.

51573470753_ pic

Please note that the unit of y axis in first graph is ms and in second graph is ns.

All benchmark can be reproduced by run `cargo bench` in https://github.com/TennyZhuang/like-bench/

###  Any examples? (optional)

### CODE REVIEW

**Comment by TennyZhuang** [comment]
@breeswish  @lonng  PTAL

**Comment by sticnarf** [comment]
By the way, both the original implementation and the implementation in this PR don't support wide characters like 汉字. 
@breeswish Do you have any ideas about dealing with the problem? The like function should be aware the `Bytes` is a string or a byte array.

**Comment by TennyZhuang** [comment]
@sticnarf I think it can be fixed by iterate per char instead of per byte, but it should not be done in one PR, it will affect the benchmark.

**Comment by breeswish** [comment]
@sticnarf Looks like MySQL also handles byte by byte:

https://stackoverflow.com/questions/6482531/how-to-make-mysql-aware-of-multi-byte-characters-in-like-and-regexp

**Comment by breeswish** [comment]
Update: I discovered that MySQL's LIKE both supports binary mode and character mode. Currently we only implemented the binary mode like. I think it's fine to only provide a binary mode like in this PR. However it would be better to support both.

**Comment by TennyZhuang** [comment]
@sre-bot /test

**Comment by TennyZhuang** [comment]
I'd like to fix it in another PR, and I think the char mode should be implemented in TiDB firstly (I'd like to port the new implementation to TiDB).

**Comment by TennyZhuang** [comment]
@lonng CI passed

**Comment by TennyZhuang** [comment]
ping(

**Comment by sticnarf** [comment]
The algorithm looks good to me. But it'd be better if you can add some comments to the variables used in the algorithm to make it more understandable.

**Comment by TennyZhuang** [comment]
@sticnarf PTAL

**Comment by TennyZhuang** [comment]
@sticnarf please take a look at the before implementation and the testcase, it seems that the precedence of escape is lower than wildcard.

**Comment by sticnarf** [comment]
> @sticnarf please take a look at the before implementation and the testcase, it seems that the precedence of escape is lower than wildcard.

Oh really sorry. You're right, keep it as it is now.

But it's quite an awkward situation... MySQL 5.7 thinks the precendence of escape is lower, however MySQL 8.0 and MariaDB 10.4 think it's higher...

**Comment by sticnarf** [comment]
@TennyZhuang Please fix DCO

**Comment by TennyZhuang** [comment]
image

Why DCO check blocks on waiting

**Comment by TennyZhuang** [comment]
@sre-bot /run-integration-tests

**Comment by TennyZhuang** [comment]
@sre-bot /run-integration-tests

**Comment by breeswish** [comment]
@sticnarf @lonng @andylokandy @iosmanthus

**Pull request merged**
