### PR TITLE
snap: use zstd to compress the snapshot

### PR DESCRIPTION
**Pull request by nolouch**
Signed-off-by: nolouch <nolouch@gmail.com>

### What problem does this PR solve?

close https://github.com/tikv/tikv/issues/9945.

Problem Summary:

migrate region cause the compression ratio is difference in each TiKV. because the snapshot is used `lz4` and most of the data in rocksdb (lower layers) are used `zstd`.

### Check List 

Tests 
- Manual test (add detailed scripts or steps below)
  **Note** : size amplification = store_total_region_size / store_disk_usage

    - Before:
image

     - After:
image

### Release note 
-  use `zstd` to compress the snapshot

### CODE REVIEW

**Review by Connor1996 — COMMENTED** [review]
You should change the code in `engine_rocks/src/sst.rs::L183`

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by nolouch** [comment]
> change `get_fastest_supported_compression_type` to make the `zstd` to be the first choice?

Besides `snapshot`, any external component use sstWritter?

**Comment by Connor1996** [comment]
> > change `get_fastest_supported_compression_type` to make the `zstd` to be the first choice?
> 
> Besides `snapshot`, any external component use sstWritter?

Seems nowhere, let's keep it.

**Review by hicqu — APPROVED** [review]

**Pull request merged**
