### PR TITLE
*: add config to redact log in raftstore and engine (#8670)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #8670 to release-4.0

---

### What problem does this PR solve?

This PR is simply a refactor of https://github.com/tikv/tikv/pull/7758

Problem Summary:

Add a new config `security.redact-info-log` which avoid printing user data (mostly user keys) to info log. Currently the config doesn't avoid printing user data altogether, but greatly reduce those logs.

### What is changed and how it works?

We redact user information in these occurrences in `raftstore`, `engine` and `sst_importer`:

### Keys
* in `Debug` trait
* in `Error`s
* in `debug!` and `error!`
* in `assert!` and `panic!`

### Values
* We have added `set_redact_bytes` configuration in rust-protobuf. All byte values will be replaced with `?` in rust-protobuf.

We manually go over all possible occurrences of these logging functions, and wrap a `log_wrappers::Type` outside these values. And then, we define `Debug` trait for protobuf values by using `impl_fmt` macro. After all, if the atomic flag `REDACT_INFO_LOG` is on, user data are then redacted from logs. 

### Todo

* `PROST` codec is not supported. If a user use PROST with redact-config on, the content of a protobuf object will not be shown, thus all information (including none-sensitive ones) will be redacted.

### Related changes

- PR to update rust-protobuf: https://github.com/pingcap/rust-protobuf/pull/4
- PR to update `pingcap/docs`/`pingcap/docs-cn`:

### Check List 

Tests 

- Unit test
- Integration test
- Check Log Message

```
[2020/09/16 16:06:05.428 +08:00] [INFO] [peer.rs:509] ["on split"] [split_keys="key <key>"] [peer_id=3] [region_id=2]
[2020/09/16 16:06:05.431 +08:00] [INFO] [peer.rs:509] ["on split"] [split_keys="key <key>"] [peer_id=3] [region_id=2]
[2020/09/16 16:06:05.432 +08:00] [INFO] [apply.rs:1821] ["split region"] [keys="key <key>"] [region="id: 2 start_key: <start_key> end_key: <end_key> region_epoch { conf_ver: 1 version: 8 } peers { id: 3 store_id: 1 }"] [peer_id=3] [region_id=2]
```

### Side Effects

- Every time we add a new structure in `tipb`, and we need to suppress user data, we'll need to add `PbPrint` in `log_wrappers`.

### Release note 
* add `security.redact-info-log` config, which redacts user data from logs

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
@skyzh can you fix the merge conflicts? there will be some work I presume.

**Comment by skyzh** [comment]
I’ll do it today

**Comment by skyzh** [comment]
PTAL, thanks! @yiwu-arbug @BusyJay

**Review by yiwu-arbug — APPROVED** [review]
LGTM. Thanks much!

**Review by BusyJay — APPROVED** [review]

**Comment by BusyJay** [comment]
It's on release-4.0, should wait for next milestone.

**Comment by gregwebs** [comment]
Looks great! Is it possible this will slow down logging in TiKV? Is there any benchmark?

**Comment by skyzh** [comment]
There is possibility of slowdown in rust-protobuf. Before formatting every protobuf value, it will check if redact log config is on or not. I'll add benchmark of rust-protobuf next week.

**Comment by yiwu-arbug** [comment]
It should be okay for a non-sychronized (relaxed memory order) atomic variable check, given each info log is actually doing an IO.

**Pull request merged**
