### PR TITLE
tnx_types: Reduce Error Size

### PR DESCRIPTION
**Pull request by silathdiir**
Signed-off-by: Steven Gu asongala@163.com
 
###  What have you changed?

Tries to fix Issue #6467. Reference PR #5979 to fix `tnx_types::Error`.

- Replaces original Error with ErrorInner.
- Defines a new Error as `pub struct Error(pub Box<ErrorInner>)`.
- Fixes the all compiling errors.

###  What is the type of the changes?

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?

- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No.

###  Does this PR affect `tidb-ansible`?

No.

###  Refer to a related PR or issue link (optional)

Issue #6467 and PR #5979

### CODE REVIEW

**Comment by breeswish** [comment]
Good job!

**Comment by siddontang** [comment]
Ping @breeswish

**Pull request merged**
