### PR TITLE
raftstore/store: remove unnecessary clone

### PR DESCRIPTION
**Pull request by lonng**
Signed-off-by: Lonng <heng@lonng.org>

## What have you changed? (mandatory)

Remove unnecessary clone.

## What are the type of the changes? (mandatory)

The currently defined types are listed below, please pick one of the types for this
- Improvement (change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)

Existing unit tests.

### CODE REVIEW

**Comment by lonng** [comment]
@overvenus @BusyJay

**Comment by BusyJay** [comment]
@overvenus PTAL

**Comment by lonng** [comment]
@BusyJay The `state` cannot be shared with others in Rust. So I think it's safe to remove this clone.

**Pull request merged**
