### PR TITLE
resource_control: unify wru/rru to ru

### PR DESCRIPTION
**Pull request by nolouch**
Signed-off-by: nolouch <nolouch@gmail.com>

### What is changed and how it works?

Issue Number: Close https://github.com/tikv/tikv/issues/14120

What's Changed:

```commit-message
resource_control: unify wru/rru to ru
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by JmPotato — APPROVED** [review]

**Review by BornChanger — APPROVED** [review]

**Comment by glorv** [comment]
duplicate with the change in #14106. @HuSharp

**Review by glorv — APPROVED** [review]
LGTM

**Comment by nolouch** [comment]
@Connor1996  Would you help to merge it?

**Review by youjiali1995 — APPROVED** [review]

**Pull request merged**
