### PR TITLE
raftstore, resolved_ts: clarify the use of term safe_ts and resolved_ts

### LINKED ISSUE #13437: Clarify the use of term `safe_ts` and `resolved_ts`
Internally, `safe_ts` is calculated from the `resolved_ts` and is used to indicate the upper safe read bound for a stale read request, so they are basically the same. However, [the mix of the two within TKV](https://github.com/tikv/tikv/blob/76f4a4e7ca6b15a1cc8e65c54049b816c2a1c45d/components/raftstore/src/store/worker/pd.rs#L678) can confuse the developers who do not know the intrinsic connection. So I propose the following changes to clarify the use of terms `safe_ts` and `resolved_ts`:

- Only use `safe_ts` in the stale read path to keep in line with the "safe to read with the ts" meaning.
- Use `resolved_ts` in other places to indicate the original meaning of "the biggest ts upper bound that there is no any potential uncommitted transaction before it".
- Use a different function name or comment to distinguish between the above two uses.

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

### What is changed and how it works?

Issue Number: Close #13437.

What's Changed:

```commit-message
Clarify the use of term `safe_ts` and `resolved_ts`.
```

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
None.
```

### CODE REVIEW

**Comment by JmPotato** [comment]
/cc @5kbpers @lhy1024 

PTAL, thx!

**Review by lhy1024 — APPROVED** [review]

**Review by 5kbpers — APPROVED** [review]

**Pull request merged**
