### PR TITLE
[release-2.1] Unified Log Format

### PR DESCRIPTION
**Pull request by breeswish**
Signed-off-by: Breezewish <breezewish@pingcap.com>

## What have you changed? (mandatory)

This PR cherry picks the unified log format formatter from 3.0 to 2.1.

Note: This PR does not introduce fields for log items.

## What are the type of the changes? (mandatory)

- New feature (change which adds functionality)

## How has this PR been tested? (mandatory)

Manually and unit tests:

```
$ target/debug/tikv-server
[2019/07/13 11:44:14.561 +08:00] [INFO] [mod.rs:26] ["Welcome to TiKV. \nRelease Version:   2.1.14\nGit Commit Hash:   Unknown (env var does not exist when building)\nGit Commit Branch: Unknown (env var does not exist when building)\nUTC Build Time:    Unknown (env var does not exist when building)\nRust Version:      Unknown (env var does not exist when building)"]
[2019/07/13 11:44:14.563 +08:00] [INFO] [config.rs:152] ["no advertise-addr is specified, fall back to addr."]
[2019/07/13 11:44:14.564 +08:00] [ERROR] [tikv-server.rs:441] ["invalid configuration: StringError(\"please specify pd.endpoints.\")"]
```

### CODE REVIEW

**Comment by breeswish** [comment]
/run-integration-tests tidb=release-2.1 pd=release-2.1 tidb-test=release-2.1

**Comment by breeswish** [comment]
@siddontang @BusyJay PTAL, thanks!

**Comment by breeswish** [comment]
/run-integration-ddl-test tidb=release-2.1 pd=release-2.1 tidb-test=release-2.1

**Comment by youjiali1995** [comment]
/run-integration-ddl-test tidb=release-2.1 pd=release-2.1 tidb-test=release-2.1

**Comment by BusyJay** [comment]
Why change the log format for 2.1? I think only bugfix is accepted.

**Comment by breeswish** [comment]
@BusyJay Required by TEP team. I don't want to change it either.

**Comment by mahjonp** [comment]
/run-integration-ddl-test tidb=release-2.1 pd=release-2.1 tidb-test=release-2.1

**Comment by siddontang** [comment]
PTAL @BusyJay

**Pull request merged**
