### PR TITLE
copr: merge nulls before loop in rpn_fn

### LINKED ISSUE #7724: Full chunk-based computing in coprocessor
Using [TiDB Chunk format](https://github.com/pingcap/tidb/blob/9627132db25e5cb560ba6ed89c2e39c32edb267a/util/chunk/chunk.go) in the `coprocessor` framework instead of `VectorValue`.

Detail Design (Draft): https://github.com/tikv/rfcs/pull/43/

## Development Task

- [x] Implement type safe chunk format.
- [x] Modify `rpn_fn` macro.
- [x] Modify all builtin functions using new signature.

## Mentor

* @TennyZhuang 
* @breeswish 

Please contact with mentors before start working on the task.

### PR DESCRIPTION
**Pull request by skyzh**
### What problem does this PR solve?

**Problem Summary**

Null values are merged before loop.

### What is changed and how it works?

Proposal: [RFC: Using chunk format in coprocessor framework](https://github.com/tikv/rfcs/pull/43/)

Related Issue: #7724

What's Changed:

* add `BitAndIterator` which merges bitmap vectors.
* add `get_bit_vec` for extracting bitmap vector from args.
* modify `rpn_fn`.
* add new struct `LogicalRows` for fast-path implementation.

### Check List 

Tests 

- Unit test

### CODE REVIEW

**Comment by skyzh** [comment]
PTAL, thanks~ @TennyZhuang @breeswish

**Comment by TennyZhuang** [comment]
@sre-bot /bench +tpch

**Comment by skyzh** [comment]
CI just runs previous builds instead of rebuilding. I'll add some pseudo commit to trigger rebuild.

**Comment by skyzh** [comment]
Hmm... no idea how this could fail :(

**Comment by skyzh** [comment]
Well, now we fail on a different test...

**Pull request merged**
