### PR TITLE
raftstore: add metrics for the bytes of pending apply cmds

### PR DESCRIPTION
**Pull request by 5kbpers**
Signed-off-by: 5kbpers <tangminghua@pingcap.com>

### What problem does this PR solve?

Problem Summary:
We found sometimes tikv could OOM and the apply wait is much high.
Note: sometimes this metric could be imprecise when TiKV was shutdown or ApplyFSM was destroyed.

### What is changed and how it works?

What's Changed:
Add a metric for observing the bytes of pending apply cmds.

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 
* Add metrics for the bytes of pending apply cmds

### CODE REVIEW

**Comment by BusyJay** [comment]
Isn't it duplicated with #7686?

**Comment by 5kbpers** [comment]
> Isn't it duplicated with #7686?

😯Right, how is the progress of this issue?

**Comment by BusyJay** [comment]
You can discuss it with @Rustin-Liu. This PR is subset of the issue. Better mentor him to finish the implement.

**Comment by Rustin-Liu** [comment]
> Right, how is the progress of this issue?

@5kbpers 
I have just started, and now I am working on counting the number of messages.
If you can guide me, I want to try to implement memory usage part first.

You can reach me at the slack tikv-wg: Rustin Liu.

**Comment by 5kbpers** [comment]
Closed it since duplicated with #7686.

**Pull request closed without merging**
