### PR TITLE
Fix ineffective alert rule for low space (#10807)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #10807 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/10814
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/10814:release-4.0-3b098f6703c8
```

---

Signed-off-by: tabokie <xy.tao@outlook.com>

### What problem does this PR solve?

Problem Summary:

Apply snapshot counter was disabled in #4066 and removed in #10099, but `low_space_and_add_region` alert rule still uses it as a condition.

### What is changed and how it works?

What's Changed: Unconditionally alert low space.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests

- No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tabokie — APPROVED** [review]

**Review by youjiali1995 — APPROVED** [review]

**Comment by youjiali1995** [comment]
Please add `cherry-pick-approved` label. @tikv/qa-release-merge

**Pull request merged**
