### PR TITLE
Dockerfile: fix build failure (#9887)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #9887 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/9898
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/9898:release-5.0-045c30f89c9b
```

---

Signed-off-by: 5kbpers <tangminghua@pingcap.com>

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

Fix `make docker` failure

### What is changed and how it works?

What's Changed:

Switch to gcc8 in the builder container.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 
* Dockerfile: fix build failure

### CODE REVIEW

**Comment by 5kbpers** [comment]
@liuzix PTAL

**Review by BusyJay — APPROVED** [review]

**Comment by zhouqiang-cl** [comment]
My bad, this pr will be reverted since v5.0.6 is already built but not released.

**Pull request merged**
