### PR TITLE
Fix rust-rocksdb branch for tikv 4.0

### PR DESCRIPTION
**Pull request by yiwu-arbug**
Signed-off-by: Yi Wu <yiwu@pingcap.com>

###  What have you changed?
TiKV 4.0 should use rust-rocksdb tikv-4.x branch. Fixing it.

###  What is the type of the changes?
Engineering

###  How is the PR tested?
CI

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?
No

###  Does this PR affect `tidb-ansible`?
No

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
compile error

**Comment by MyonKeminta** [comment]
Does the tikv-4.x branch match the current master of TiKV? We plan to release 4.0.0-beta.2 this week, and merge master to release-4.0 branch today.

**Comment by yiwu-arbug** [comment]
> Does the tikv-4.x branch match the current master of TiKV? We plan to release 4.0.0-beta.2 this week, and merge master to release-4.0 branch today.

It should, but I didn't check. And the hash of rust-rocksdb won't be the same - rust-rocksdb tikv-4.0 branch points to rocksdb and titan tikv-4.0 branch, which make the hash different.

Let me merge this before 4.0-rc then..

**Comment by yiwu-arbug** [comment]
After merging #7171 and this PR the content of rocksdb branches are consistent between tikv master and 4.0 (rocksdb hashes are still different).

**Pull request merged**
