### PR TITLE
docs: Add RocksDB option config doc

### PR DESCRIPTION
**Pull request by CaitinChen**
Signed-off-by: CaitinChen <chenchun@pingcap.com>

## What have you changed? (mandatory)

Add RocksDB option config doc

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

Relevant

### CODE REVIEW

**Comment by CaitinChen** [comment]
@lilin90 @DorianZheng PTAL

**Comment by siddontang** [comment]
@DorianZheng 

I think for all the configurations, we need to use rustdoc, so we only need to manage them in one place. But I don't know whether it is easy to do for RocksDB. Because now we use a macro to generate the RocksDB configurations.

**Comment by siddontang** [comment]
Now I think we can put the configurations in docs, we may move to rust doc later.

**Comment by huachaohuang** [comment]
Is it possible to replace the macro with something like this?

``` Rust
struct CfConfig {
...
}

struct DefaultCfConfig(CfConfig);

impl Default for DefaultCfConfig {
...
}

struct WriteCfConfig(CfConfig);

impl Default for WriteCfConfig {
...
}
```

**Comment by huachaohuang** [comment]
Have a try with the way above, seems `serde` cannot handle the default value as expected :(

**Comment by CaitinChen** [comment]
@DorianZheng PTAL

**Pull request merged**
