### PR TITLE
copr: Vectorize bin.

### PR DESCRIPTION
**Pull request by cireu**
PCP #5751 

###  What have you changed?
Vectorize bin in builtin_string.rs

###  What is the type of the changes?

Pick one of the following and delete the others:

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?
Please select the tests that you ran to verify your changes:
- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No

###  Does this PR affect `tidb-ansible`?

No

### CODE REVIEW

**Comment by cireu** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/28

**Comment by cireu** [comment]
Waiting https://github.com/pingcap/tidb/issues/13440 to be fixed.

**Comment by cireu** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/28

**Comment by breeswish** [comment]
@sticnarf @lonng @andylokandy @iosmanthus PTAL

**Pull request merged**
