### PR TITLE
benches/coprocessor: add some benchmark cases

### PR DESCRIPTION
**Pull request by siddontang**
## What have you changed? (mandatory)

Add some benchmark cases to ensure whether we need to introduce some optimizations from Go.

In Go, I found that using BigEndian to read u16 is faster than comparing table prefix. And sometimes, using a map is faster than switch-case. 

But in Rust, seem that we don't need these optimizations.

## What are the type of the changes? (mandatory)

No

## How has this PR been tested? (mandatory)

No need

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No

## Benchmark result if necessary (optional)

test coprocessor::dag::expr::scalar::bench_get_scalar_args_with_map   ... bench:       7,700 ns/iter (+/- 1,349)
test coprocessor::dag::expr::scalar::bench_get_scalar_args_with_match ... bench:       2,811 ns/iter (+/- 220)
test coprocessor::codec::bench_table_prefix_check                     ... bench:         555 ns/iter (+/- 24)
test coprocessor::codec::bench_table_prefix_start_with                ... bench:         563 ns/iter (+/- 31)
test coprocessor::codec::bench_record_prefix_bigendian_check          ... bench:         595 ns/iter (+/- 54)
test coprocessor::codec::bench_record_prefix_equal_check              ... bench:         671 ns/iter (+/- 23)
test coprocessor::codec::bench_record_prefix_littleendian_check       ... bench:         529 ns/iter (+/- 20)
test coprocessor::codec::bench_record_prefix_start_with               ... bench:         514 ns/iter (+/- 12)

## Add a few positive/negative examples (optional)

/cc @AndreMouche @breeswish

### CODE REVIEW

**Comment by breeswish** [comment]
use little endian to check may be faster, because memory layout is little endian.

**Comment by siddontang** [comment]
@breeswish 

You are right, little endian is faster than big endian.

**Comment by siddontang** [comment]
@AndreMouche 

em, where is the repeated code? do you mean public the check_args functions?

**Comment by AndreMouche** [comment]
yes @siddontang

**Pull request merged**
