### PR TITLE
cdc: reduce the message of advancing resolved ts (#8442)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #8442 to release-4.0

---

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 
* N/A

### CODE REVIEW

**Comment by MyonKeminta** [comment]
@5kbpers Please fix conflicts

**Review by MyonKeminta — APPROVED** [review]

**Review by overvenus — APPROVED** [review]
LGTM

**Pull request merged**
