### PR TITLE
*: update deps

### PR DESCRIPTION
**Pull request by BusyJay**
### What problem does this PR solve?

Problem Summary:

Resolve RUSTSEC-2021-0055, RUSTSEC-2021-0057, RUSTSEC-2021-0058.

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Breaking backward compatibility
    Some self-signed code may not work anymore.

### Release note 
- No release note.

### CODE REVIEW

**Review by zhouqiang-cl — APPROVED** [review]
LGTM

**Comment by tisonkun** [comment]
@BusyJay according to https://github.com/pingcap/tidb-binlog/issues/1049#issuecomment-856081837 and the description here:

```
Breaking backward compatibility
Some self-signed code may not work anymore.
```

shall we add a release note field that declare the changes as well as known case like 

```
Invalid self signed certificates will not be accepted by latest openssl. For example, CA and host's CN name can not be the same.
```

It is surely change behavior and user will be confused if he saw "some self-signed code may not work anymore", what is "some"?

**Comment by BusyJay** [comment]
> It is surely change behavior and user will be confused if he saw "some self-signed code may not work anymore", what is "some"?

Actually we don't know either. "CA and host's CN name can not be the same" is just one known cause. There is no release note from openssl that states the changes, we can't conclude what works and what doesn't.

**Comment by tisonkun** [comment]
> > It is surely change behavior and user will be confused if he saw "some self-signed code may not work anymore", what is "some"?
> 
> Actually we don't know either. "CA and host's CN name can not be the same" is just one known cause. There is no release note from openssl that states the changes, we can't conclude what works and what doesn't.

Aha. Well then 😂

**Pull request merged**
