### PR TITLE
*: move util as a component

### PR DESCRIPTION
**Pull request by BusyJay**
## What have you changed? (mandatory)

Extract util module from the TiKV sources to a standalone sub-project. It's part of process to speed up compilation by reducing code inside TiKV projects.

## What are the type of the changes? (mandatory)

- Engineering

## How has this PR been tested? (mandatory)

unit tests

## Does this PR affect documentation (docs) update? (mandatory)

No.

## Does this PR affect tidb-ansible update? (mandatory)

No.

## Refer to a related PR or issue link (optional)

#4165

### CODE REVIEW

**Comment by siddontang** [comment]
how about the rebuild time now?

**Comment by BusyJay** [comment]
No notable changes detected. But building channel benchmark is much faster than before now.

**Comment by ngaut** [comment]
Good job.

**Comment by breeswish** [comment]
(related #4504)

**Comment by siddontang** [comment]
please fix the conflicts @BusyJay

**Comment by siddontang** [comment]
@kennytm @brson 

Please approve it again.

**Pull request merged**
