### PR TITLE
Remove inline attributes

### PR DESCRIPTION
**Pull request by nrc**
Signed-off-by: Nick Cameron <nrc@ncameron.org>

## What have you changed? (mandatory)

Removed all occurances of `#[inline]` and `#[inline(always)]`

Please **NOTE** that:
- Do not assume reviewers understand the original issue

## What are the type of the changes? (mandatory)

- Engineering (engineering change which doesn't change any feature or fix any issue)

## How has this PR been tested? (mandatory)

Correctness testing is N/A. I have done some cursory benchmarking: https://gist.github.com/nrc/bf802bf6d2609e0680cabcafe26a52f7. We should do some more thorough benchmarking before landing.

## Does this PR affect documentation (docs) or release note? (mandatory)

no

## Does this PR affect tidb-ansible update? (mandatory)

no

PTAL @siddontang @breeswish

### CODE REVIEW

**Comment by siddontang** [comment]
```
thread 'raftstore::test_lease_read::test_read_index_when_transfer_leader' panicked at 'failed to transfer leader to [1] id: 3 store_id: 3', components/test_raftstore/src/cluster.rs:800:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   7: test_raftstore::cluster::Cluster<T>::must_transfer_leader
             at ./<::std::macros::panic macros>:8
   8: integrations::raftstore::test_lease_read::test_read_index_when_transfer_leader
             at tests/integrations/raftstore/test_lease_read.rs:376
   9: integrations::raftstore::test_lease_read::test_read_index_when_transfer_leader::{{closure}}
             at tests/integrations/raftstore/test_lease_read.rs:317
  10: core::ops::function::FnOnce::call_once
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libcore/ops/function.rs:231
  11: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/liballoc/boxed.rs:704
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  13: test::run_test::run_test_inner::{{closure}}
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libstd/panicking.rs:272
             at /rustc/e305df1846a6d985315917ae0c81b74af8b4e641/src/libstd/panic.rs:388
             at src/libtest/lib.rs:1468
test raftstore::test_lease_read::test_read_index_when_transfer_leader ... FAILED
test storage::test_storage::test_txn_store_delete ... ok
```

@nolouch CI failed

**Comment by siddontang** [comment]
@hicqu 

seem it has bee fixed in #4688 but still failed?

**Comment by breeswish** [comment]
How about the coprocessor_executors benchmark?

**Comment by nrc** [comment]
> How about the coprocessor_executors benchmark?

```
table_scan_primary_key  time:   [5.8185 us 5.9514 us 6.0899 us]
                        change: [-4.4546% -0.9524% +2.8499%] (p = 0.62 > 0.05)
                        No change in performance detected.

table_scan_datum_front  time:   [4.9321 us 5.0915 us 5.2583 us]
                        change: [+0.2458% +5.1799% +10.013%] (p = 0.04 < 0.05)
                        Change within noise threshold.
Found 4 outliers among 100 measurements (4.00%)
  3 (3.00%) high mild
  1 (1.00%) high severe

table_scan_datum_multi_front
                        time:   [5.1579 us 5.3425 us 5.5451 us]
                        change: [+1.3774% +7.3063% +14.994%] (p = 0.03 < 0.05)
                        Performance has regressed.
Found 6 outliers among 100 measurements (6.00%)
  2 (2.00%) high mild
  4 (4.00%) high severe

table_scan_long_datum_front
                        time:   [16.488 us 16.875 us 17.274 us]
                        change: [-8.8071% -4.7272% -0.1940%] (p = 0.03 < 0.05)
                        Change within noise threshold.
Found 3 outliers among 100 measurements (3.00%)
  2 (2.00%) high mild
  1 (1.00%) high severe

table_scan_datum_multi_front
                        time:   [4.8797 us 4.9978 us 5.1182 us]
                        change: [-12.394% -5.3226% +2.1178%] (p = 0.18 > 0.05)
                        No change in performance detected.
Found 4 outliers among 100 measurements (4.00%)
  2 (2.00%) high mild
  2 (2.00%) high severe

table_scan_datum_end    time:   [16.380 us 16.515 us 16.657 us]
                        change: [+26.898% +28.966% +31.005%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 5 outliers among 100 measurements (5.00%)
  4 (4.00%) high mild
  1 (1.00%) high severe

table_scan_datum_all    time:   [18.078 us 18.200 us 18.322 us]
                        change: [+20.106% +22.382% +24.748%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 7 outliers among 100 measurements (7.00%)
  4 (4.00%) high mild
  3 (3.00%) high severe

table_scan_datum_absent time:   [5.6588 us 5.7792 us 5.9032 us]
                        change: [-1.7598% +2.3728% +6.3737%] (p = 0.25 > 0.05)
                        No change in performance detected.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild

table_scan_datum_absent_large_row
                        time:   [16.236 us 16.372 us 16.514 us]
                        change: [+20.955% +23.788% +26.537%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 6 outliers among 100 measurements (6.00%)
  4 (4.00%) high mild
  2 (2.00%) high severe

table_scan_point_range  time:   [5.3432 us 5.4801 us 5.6326 us]
                        change: [-7.2342% -3.0339% +1.4357%] (p = 0.19 > 0.05)
                        No change in performance detected.
Found 3 outliers among 100 measurements (3.00%)
```

Interesting! Three of the benchmarks saw large regressions, one medium sized regression and the rest were pretty steady. I wonder if there is just one or two `inline`s which are causing these regressions?

In any case, I don't think we should land this without further investigation.

**Comment by nrc** [comment]
So as well as the above mixed results, I benchmarked a read-heavy workload using YCSB. The results seem very platform-specific: on my Mac laptop I got performance improvements of 0-9% (not a great benchmarking system, lots of variability, even after dismissing outliers), however, on CentOS (much closer to our deployment systems) I saw performance regressions of about 5%.

So, I think there might be things we could do better with our use of `inline`, but I don't think we should land this PR or something like it.

**Pull request closed without merging**
