### PR TITLE
backup: reduce the default thread pool size of backup, enable auto tune by default

### PR DESCRIPTION
**Pull request by YuJuncen**
### What is changed and how it works?

Close(again!) #11000 

What's Changed:

1. The default thread pool size of backup is now `clamp(CPU * 0.5, 1, 8)`.
2. Auto tune would clamp its permit to `[1, backup.num-threads]`.
3. Enable auto tune by default.
4. Moved `ControlThreadPool` to the `utils` package.
5. Auto tune remain threads is now `round(0.2 * CPU)`.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes less CPU.
    - Backup speed would be slower.

### Release note 

```release-note
Reduce the default thread pool size of backup, and enable backup restrict itself when the workload is heavy. The backup speed may be slower. You can set `backup.num-threads` by tikv-ctl or config file to rollback that change.
```

### CODE REVIEW

**Comment by kennytm** [comment]
🤔 

```
[2021-12-22T10:08:06.926Z] test endpoint::tests::test_adjust_thread_pool_size ... thread 'main' panicked at 'assertion failed: `(left == right)`
[2021-12-22T10:08:06.926Z]   left: `2`,
[2021-12-22T10:08:06.926Z]  right: `3`', components/backup/src/endpoint.rs:1617:9
```

**Comment by YuJuncen** [comment]
> 🤔
> 
> ```
> [2021-12-22T10:08:06.926Z] test endpoint::tests::test_adjust_thread_pool_size ... thread 'main' panicked at 'assertion failed: `(left == right)`
> [2021-12-22T10:08:06.926Z]   left: `2`,
> [2021-12-22T10:08:06.926Z]  right: `3`', components/backup/src/endpoint.rs:1617:9
> ```

This cannot be reproduced in local... Why...?🤔

/run-tests

**Comment by YuJuncen** [comment]
@kennytm I guess I have got what happened.
1. When dropping the runtime, the task will be 'killed'(not being polled anymore, I guess).
2. When softlimit enabled, there may not be enough permits to make the initial 2 tasks finish.
3. So, when the runtime dropped, one of the two tasks would be canceled.

I think we shouldn't adapt the origin trick (let all tasks reference the runtime) for allowing all tasks success to finish because that causes a background panic (even it is harmless, cc https://github.com/tikv/tikv/pull/11556).

Maybe we can make the trick better? 🤔
```rust
#[derive(Clone)]
struct DaemonRuntime(Option<Runtime>);

impl DaemonRuntime {
  fn spawn(self: Arc<Self>, f: impl Future) {
    self.0.unwrap().spawn(async move {
      f.await;
      drop(self)
    })
  }
}

impl Drop for DaemonRuntime {
  fn drop(&mut self){
    // it is safe because all tasks should be finished.
    self.take().shutdown_background()
  }
}
```

**Comment by YuJuncen** [comment]
(BTW, I'm not sure how can the test thread use up to 5000% CPU...)
```
[components/backup/src/softlimit.rs:126] (name, usage) = (
    "endpoint::tests",
    5000,
)
```

**Review by kennytm — APPROVED** [review]

**Review by 3pointer — APPROVED** [review]

**Comment by YuJuncen** [comment]
```
[2021-12-28T06:29:17.552Z]     raftstore::test_snap::test_inspected_snapshot
[2021-12-28T06:29:17.552Z]     raftstore::test_split_region::test_incompatible_node_auto_split_region
```
/run-tests

**Pull request merged**
