### PR TITLE
metrics: fix a expression error of unified read pool cpu

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: Close #13086

What's Changed:

```
Fix the wrong expression of `Unified Read Pool CPU`
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by sticnarf — APPROVED** [review]
LGTM. Thanks!

**Review by tabokie — APPROVED** [review]

**Pull request merged**
