### PR TITLE
[cherry-pick-6.5] raft_log_engine: update to latest version. (#16294)

### PR DESCRIPTION
**Pull request by LykxSassinator**
This is a manual cherry-pick of https://github.com/tikv/tikv/pull/16294

### What is changed and how it works?

Issue Number: close https://github.com/tikv/tikv/issues/16324 ref https://github.com/tikv/raft-engine/pull/346

What's Changed:

```commit-message
Update `raft_log_engine` lib to the latest version, to fix some issues, including:
- rewrite: optimize the interval of sync when rewriting memtables #347.
```

image

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by tonyxuqqi — APPROVED** [review]

**Review by overvenus — APPROVED** [review]

**Comment by LykxSassinator** [comment]
Performance tests

**Conclusion: no performance regression.**
Using tpcc(3000 warehouses, 16 Cores, Duration: 1h)
| Threads = 200 | QPS | avg_latency(ms) | P99_latency(ms) | P999_latency(ms) | tikv_cpu_usage(%) |
| ---- | ---- | ---- | ---- | ---- | ---- |
| Master (nightly version) | 24685 | 5.85 | 48.1 | 78.9 | 1416 | 
| this pr(#16363) | 24629 | 5.86 | 48.2 | 80.0 | 1422 | 

| Threads = 150 | QPS | avg_latency(ms) | P99_latency(ms) | P999_latency(ms) | tikv_cpu_usage(%) |
| ---- | ---- | ---- | ---- | ---- | ---- |
| Master (nightly version) | 24918 | 4.36 | 30.8 | 59.9 | 1465 | 
| this pr(#16363) | 24965 | 4.35 | 30.7 | 59.7 | 1474 | 

| Threads = 100 | QPS | avg_latency(ms) | P99_latency(ms) | P999_latency(ms) | tikv_cpu_usage(%) |
| ---- | ---- | ---- | ---- | ---- | ---- |
| Master (nightly version) | 25009 | 2.92 | 23.8 | 32.4 | 1526 | 
| this pr(#16363) | 24889 | 2.94 | 24.2 | 32.9 | 1522 | 

| Threads = 50 | QPS | avg_latency(ms) | P99_latency(ms) | P999_latency(ms) | tikv_cpu_usage(%) |
| ---- | ---- | ---- | ---- | ---- | ---- |
| Master (nightly version) | 24231 | 1.54 | 12.9 | 22.4 | 1578 | 
| this pr(#16363) | 24116 | 1.55 | 13.0 | 23.7 | 1558 | 

/cc @overvenus @tonyxuqqi It's time to merge this pr.

**Pull request merged**
