### PR TITLE
server: stop status server early when gracefully shutdown

### PR DESCRIPTION
**Pull request by youjiali1995**
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/25244

Problem Summary:

v4.0 TiDB introduced a mechanism that if a request sent to TiKV fails due to network problem, TiDB will check the liveness status of the TiKV through an HTTP API. If it's still reachable, TiDB will retry to send requests to it forever until backoff timeout.

However, TiKV may shut down slowly.
```
Jun 08 11:32:21 583d114d1e09 systemd[1]: Stopping tikv service...
Jun 08 11:33:51 583d114d1e09 systemd[1]: tikv-20160.service stop-sigterm timed out. Killing.
Jun 08 11:33:53 583d114d1e09 systemd[1]: tikv-20160.service: main process exited, code=killed, status=9/KILL
Jun 08 11:33:53 583d114d1e09 systemd[1]: Stopped tikv service.
Jun 08 11:33:53 583d114d1e09 systemd[1]: Unit tikv-20160.service entered failed state.
Jun 08 11:33:53 583d114d1e09 systemd[1]: tikv-20160.service failed.
Jun 08 11:33:53 583d114d1e09 systemd[1]: Started tikv service.
Jun 08 11:33:53 583d114d1e09 run_tikv.sh[74711]: sync ...
Jun 08 11:33:53 583d114d1e09 run_tikv.sh[74711]: real        0m0.103s
Jun 08 11:33:53 583d114d1e09 run_tikv.sh[74711]: user        0m0.000s
Jun 08 11:33:53 583d114d1e09 run_tikv.sh[74711]: sys        0m0.101s
Jun 08 11:33:53 583d114d1e09 run_tikv.sh[74711]: ok
```
The gRPC service is stopped but the liveness check API still works.
```
[2021/06/08 11:32:21.557 +08:00] [WARN] [client_batch.go:530] ["no available connections"] [target=10.0.2.222:20160]
...
[2021/06/08 11:33:53.034 +08:00] [INFO] [region_cache.go:1660] ["[liveness] request kv status fail"] [store=10.0.2.222:20180] [error="Get http://10.0.2.222:20180/status: dial tcp 10.0.2.222:20180: connect: connection refused"]
```

### What is changed and how it works?

What's Changed:

Stop the status server which provides the early.

### Check List 

Tests 

- No code

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by MyonKeminta** [comment]
May this affect metrics reporting?

**Comment by youjiali1995** [comment]
> May this affect metrics reporting?

@MyonKeminta I think it doesn't matter because the store is stopping.

**Comment by youjiali1995** [comment]
@MyonKeminta @sticnarf PTAL

**Review by sticnarf — COMMENTED** [review]
LGTM

**Review by sticnarf — APPROVED** [review]

**Review by ekexium — APPROVED** [review]

**Review by MyonKeminta — APPROVED** [review]

**Pull request merged**
