### PR TITLE
split_controller : add logging for hot keys and region split key

### PR DESCRIPTION
**Pull request by mittalrishabh**
### What is changed and how it works?

Issue Number: Close https://github.com/tikv/tikv/issues/17024

What's Changed:
Printing more logs around the split key and hot keys in a region. It might help us in identifying the hot keys in a region.
```commit-message

```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [X] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by nolouch — APPROVED** [review]

**Comment by mittalrishabh** [comment]
I think it needs one more review

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by mittalrishabh** [comment]
please merge these changes.

**Comment by wuhuizuo** [comment]
> please merge these changes.

/check-dco

@mittalrishabh please update the description, if none release note need, please fill it with "None" in this section:
image

**Comment by mittalrishabh** [comment]
please merge this change.

**Comment by mittalrishabh** [comment]
please merge this change.

**Review by cfzjywxk — APPROVED** [review]

**Pull request merged**
