### PR TITLE
metrics: update to latest and use heatmap for raftstore

### PR DESCRIPTION
**Pull request by BusyJay**
### What problem does this PR solve?

We usually need to change the expression of Grafana to analyze latency problem when raftstore is involved. It's very inconvenient when we can't edit the dashboard or even don't have permission to access. This PR changes latency summary in raftstore to heatmap. It looks like following:

image

x-axis means time, y-axis means histogram buckets. The color schema is spectral, purple means less value count in the bucket, red means more. So we can notice that many async snapshot requests return within 1ms. But we can also see that there are jitters from time to time that can reach 256ms~512ms.

Coprocessor has used heatmap in latency summary already. But the difference is raftstore hide all the zero values and use spectral schema for more friendly view.

Latency details by instance are still there:

image

### Check List 

Tests 

- Manual test

Side effects

- Breaking backward compatibility

### Release note 

use heatmap for raftstore latency summary to better jitter diagnostics

### CODE REVIEW

**Comment by BusyJay** [comment]
This PR can change the way we used to analyze jitters, make sure you feel OK and fully understood about the new way before approving it.

**Comment by BusyJay** [comment]
Technically, you only need to review the second commit. The first commit is just a copy/paste from tidb-ansible.

**Comment by breeswish** [comment]
I think it would be better to preserve the original graph, since heatmap is used to observe an *overview*. However, if we specifically want to know latency jitters, heatmap can be less obvious:

image

**Comment by BusyJay** [comment]
> I think it would be better to preserve the original graph

There will be too many graph.

>  know latency jitters, heatmap can be less obvious:

Yes. It's related to https://github.com/grafana/grafana/issues/23649.

Although it's not obvious as curve, but it still shows a precise range. We usually adapt the graph to see how high can the jitter reach in practice, which means curve shows jitters but still not very helpful.

**Pull request merged**
