### PR TITLE
storage: set in-memory pessimistic lock feature gate to 6.0.0

### PR DESCRIPTION
**Pull request by sticnarf**
Depends on:

- [x] https://github.com/tikv/tikv/pull/12077

### What is changed and how it works?

Issue Number: Ref #11452

What's Changed:

```commit-message
The in-memory pessimistic lock feature should be only enabled after
all TiKV instances have been upgraded to the new version. Otherwise,
transferring leader may be blocked because of the new protocol and
procedure when in-memory pessimistic locks exist.

So, we need to use a feature gate to make sure this feature is only
enabled after all TiKVs have been upgraded to the new version.
```

### Check List 

Tests 

- Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by youjiali1995 — APPROVED** [review]
Is it a good idea to make `FeatureGate` a lazy_static one?

**Comment by sticnarf** [comment]
> Is it a good idea to make `FeatureGate` a lazy_static one?

I don't know. Global static one may be easier to use but less easier for tests.

**Review by cfzjywxk — APPROVED** [review]

**Pull request merged**
