### PR TITLE
cdc: fix missing ResolvedTs import in prost-codec

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve?

Problem Summary:

The `ResolvedTs` name is not imported when using prost-codec, making the code fail to compile there.

### What is changed and how it works?

What's Changed:

Add back the import.

### Related changes

- Need to cherry-pick to the release branch
   * release-5.0, release-4.0

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
    * make build with prost codec 🤷

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by zhouqiang-cl — APPROVED** [review]
LGTM

**Comment by zhouqiang-cl** [comment]
@BusyJay PTAL

**Review by BusyJay — APPROVED** [review]

**Pull request merged**
