### PR TITLE
engine_rocks: update rust-rocksdb

### PR DESCRIPTION
**Pull request by tabokie**
### What problem does this PR solve?

Issue Number: #11226

### What is changed and how it works?

What's Changed:

Update rust-rocksdb so that master version is no less than previous release.

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by BusyJay** [comment]
It can't build.

**Review by yiwu-arbug — APPROVED** [review]
Please fix conflict.

**Pull request merged**
