### PR TITLE
raftstore:Fix memory metrics overflow on raft msgs (#12186)

### LINKED ISSUE #12160: raftstore: Integer overflow problems on memory metrics
### What version of TiKV are you using?

$./tikv-server --version
TiKV 
Release Version:   6.0.0-alpha
Edition:           Community
Git Commit Hash:   ce39ef6b52a050c594b2b01e8d60a6e11853faec
Git Commit Branch: fix-log-entry-oom-t
UTC Build Time:    2022-03-14 11:39:21
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure
Profile:           release

### Steps to reproduce

1. sysbench insert
### What did you expect?
1.  no overflow.
### What did happened?
1. The metrics on raft messages overflow.
2. master of 0314 + trace log
0W6TTjgjYc
EkRt8BAfRe
feOg8VakKq

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #12186 to release-6.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/12224
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/12224:release-6.0-75526df45461
```

---

### What is changed and how it works?

Issue Number: Close #12160

What's Changed:

```commit-message
Fix raft msg memory metrics overflow.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

Side effects

### Release note 

```release-note
Solve the problem of raft msg memory metrics overflow, which will cause intermittent packet loss and oom.
```

### CODE REVIEW

**Review by hicqu — APPROVED** [review]

**Review by NingLin-P — APPROVED** [review]

**Comment by you06** [comment]
@VelocityLight this PR blocks the release of v6.0.0, PTAL

**Pull request merged**
