### PR TITLE
config: increase resolved-ts.advance-ts-interval to 20s

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close https://github.com/tikv/tikv/issues/14100

What's Changed:

```commit-message
Save network traffic by increasing resolved-ts.advance-ts-interval
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:

### Check List 

Tests 

- Unit test

### Release note 

```release-note
Save network traffic by increasing resolved-ts.advance-ts-interval
```

### CODE REVIEW

**Review by 3pointer — APPROVED** [review]

**Comment by easonn7** [comment]
LGTM

**Review by JmPotato — APPROVED** [review]

**Review by Connor1996 — APPROVED** [review]

**Review by nolouch — COMMENTED** [review]
will it affect stale read?

**Pull request merged**
