### PR TITLE
Backup: add S3 metrics && add s3_multi_part_size config  (#11666)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #11666 to release-5.3
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/12457
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/12457:release-5.3-c5aa84108752
```

---

### What is changed and how it works?

Part solve https://github.com/pingcap/tidb/issues/30087

What's Changed:
1. Add metrics for backup s3 storage. to record the qps that BR send to S3. 
2. BR use multi_upload when put a big object to S3. and the split size is 5MB. which may generate too many requests. This PR tried to make the multi_part_size configurable.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)

### Release note 

```release-note
Add a new hidden config `s3_multi_part_size` to make backup can control the part size when upload big sst file to s3.
```

### CODE REVIEW

**Review by YuJuncen — APPROVED** [review]
LGTM

**Comment by YuJuncen** [comment]
Maybe we need run `make format`.

**Review by overvenus — APPROVED** [review]

**Review by glorv — APPROVED** [review]

**Pull request merged**
