### PR TITLE
backup: do not recycle backup threads

### LINKED ISSUE #10287: Backup should not recycle threads since we set thread number via config
## Bug Report

Backup threads are recycled when there is no backup task in the past 30 minutes, it becomes unnecessary since https://github.com/tikv/tikv/pull/8193 sets threads number via config. Keeping a fixed-size threads pool is very cheap.

And for v4.0.x tikv, it leaks threads because we do not shutdown thread pools properly.

### What version of TiKV are you using?

~~v4.0.0-v4.0.13~~
v4.0.0-v4.0.9

https://github.com/tikv/tikv/commit/1bdc5ffef8b8bb308ff3be69643a0d0c89aabc23 fixes the issue.

### Steps to reproduce

Run backup.

### What did you expect?

Do not recycle or spawn new threads.

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve?

Issue Number: close #10287

### What is changed and how it works?

Do not recycle backup threads.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

Run backup for every 30 minutes. 

### Release note 

For release-5.0

```release-note
None
```

For release-4.0

```release-note
Fix backup threads leak
```

### CODE REVIEW

**Comment by Leavrth** [comment]
The following code block may need to be also modified.
https://github.com/tikv/tikv/blob/master/components/backup/src/endpoint.rs#L576-L584

**Comment by Leavrth** [comment]
Since function `check_active` is deleted, `self.size in struct Enpoint` isn't changed anymore. And `new_size` in function `adjust_with` is a const number. So The fuction adjust_with always this `if block` is always true.
https://github.com/tikv/tikv/blob/master/components/backup/src/endpoint.rs#L592

Therefore self.worker will not be replace, which means this code block can be update.
https://github.com/tikv/tikv/blob/master/components/backup/src/endpoint.rs#L576-L584

**Review by Leavrth — APPROVED** [review]

**Review by glorv — APPROVED** [review]

**Review by 3pointer — APPROVED** [review]

**Pull request merged**
