### PR TITLE
Cargo.toml: Fix h2 cargo deny issue.

### LINKED ISSUE #16768: cargo build fails due to vulnerability in h2
## cargo build fails due to vulnerability in h2
```
error[vulnerability]: Degradation of service in h2 servers with CONTINUATION Flood
    ┌─ /Users/alexf/repos/tikv/Cargo.lock:165:1
    │
165 │ h2 0.3.24 registry+https://github.com/rust-lang/crates.io-index
    │ --------------------------------------------------------------- security vulnerability detected
    │
    = ID: RUSTSEC-2024-0332
    = Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0332
    = An attacker can send a flood of CONTINUATION frames, causing `h2` to process them indefinitely.
      This results in an increase in CPU usage.

      Tokio task budget helps prevent this from a complete denial-of-service, as the server can still
      respond to legitimate requests, albeit with increased latency.

      More details at "https://seanmonstar.com/blog/hyper-http2-continuation-flood/.

      Patches available for 0.4.x and 0.3.x versions.
    = Solution: Upgrade to ^0.3.26 OR >=0.4.4 (try `cargo update -p h2`)
```

### PR DESCRIPTION
**Pull request by afeinberg**
### What is changed and how it works?

Issue Number: Close #16768

What's Changed:

```commit-message
Update h2 to 0.3.26
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [X] Manual test (add detailed scripts or steps below)
```
make clippy
```
- [X] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None

```

### CODE REVIEW

**Review by tonyxuqqi — APPROVED** [review]

**Comment by afeinberg** [comment]
Could someone do a /merge? /cc @bufferflies @Connor1996

**Review by bufferflies — APPROVED** [review]

**Pull request merged**
