### PR TITLE
*: fix issue that some components depend on protobuf-codec unconditionally

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve?

Problem Summary:

Some components unconditionally imports `tikv_util` making `protobuf-codec` always be enabled even when we want `prost-codec`.

### What is changed and how it works?

What's Changed:

Change such imports to `default-features = false` and insert the appropriate `protobuf`/`prost-codec` features.

### Related changes

- Need to cherry-pick to the release branch
   * master

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
   * tikv/importer which uses `prost-codec` passes `make test` after this PR.

Side effects

### Release note 

- No release notes

### CODE REVIEW

**Review by BusyJay — APPROVED** [review]

**Comment by kennytm** [comment]
now that 5.0.0 has been released, can we approve this? @zhouqiang-cl

**Pull request merged**
