### PR TITLE
copr: fix a bug that get_index_version doesn't consider some cases.

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve?

Issue Number: For https://github.com/pingcap/tidb/issues/23205 

Problem Summary:

get_index_version() doesn't consider some cases:
1. non-unique index.
2. unique index with null value.

### What is changed and how it works?

If the length is 3 or 4, we know that it's version 1. 

### Check List 

Tests 

- Unit test

Side effects

### Release note 
- No release note

### CODE REVIEW

**Comment by wjhuang2016** [comment]
test check_release_note

**Review by lzmhhh123 — COMMENTED** [review]
Please fix the lint.

**Review by lzmhhh123 — APPROVED** [review]

**Pull request merged**
