### PR TITLE
coprocessor: tag analyze requests correctly

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve?

TiKV makes a mistake to tag analyze requests.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hicqu** [comment]
@time-and-fate please also take a look about `ReqTag`. I'm not sure the current classify is ok or not.

**Review by time-and-fate — APPROVED** [review]
LGTM

**Review by zhongzc — APPROVED** [review]

**Review by andylokandy — APPROVED** [review]

**Review by breeswish — APPROVED** [review]

**Pull request merged**
