### PR TITLE
stabilize  some cdc cases

### LINKED ISSUE #11560: unstable tests about cdc
Some threads panic when holding locks:
  0: rust_begin_unwind
             at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/result.rs:1599:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/result.rs:1281:23
   4: <test_raftstore::router::MockRaftStoreRouter as raftstore::router::RaftStoreRouter<engine_rocks::engine::RocksEngine>>::significant_send
             at /data1/qupeng/github.com/tikv/tikv/components/test_raftstore/src/router.rs:79:13
   5: cdc::endpoint::Initializer<E>::initialize::{{closure}}
             at ./src/endpoint.rs:1015:25
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/future/mod.rs:80:19
   7: cdc::endpoint::Endpoint<T,E>::on_register::{{closure}}
             at ./src/endpoint.rs:627:19
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/core/src/future/mod.rs:80:19
   9: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /data1/qupeng/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/core.rs:161:17
  10: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /data1/qupeng/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/loom/std/unsafe_cell.rs:14:9
  11: tokio::runtime::task::core::CoreStage<T>::poll
             at /data1/qupeng/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/core.rs:151:13
  12: tokio::runtime::task::harness::poll_future::{{closure}}
             at /data1/qupeng/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:461:19
  13: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/2faabf579323f5252329264cc53ba9ff803429a3/library/std/src/panic.rs:347:9
  14: std::panicking::try::do_call
             at /rustc/2faabf579323f5252329264cc53ba9ff8034

But the stack is truncated so we can't know it comes from which case.

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

### What is changed and how it works?

Close #11560 .

### Check List 

Tests 

- No code

Side effects

### Release note 

```release-note
Please add a release note.
None
```

### CODE REVIEW

**Review by hi-rustin — APPROVED** [review]
Local tests did not encounter cdc panic again.

**Review by overvenus — APPROVED** [review]
LGTM

**Pull request merged**
