### PR TITLE
server: support return simplified metrics response (#12602)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #12602 to release-6.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/12649
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/12649:release-6.1-c3c9707faed1
```

---

### What is changed and how it works?

Issue Number: ref #12355

What's Changed:

```commit-message
```

This PR is split from #12417 by only filter counter with 0 value and histogram with 0 samples. This will make it much easier to review and can be released in v6.1.

In my benchmark: By applying this simple logic, the /metrics response size can be reduced to about 35% with tpcc workload. When `simplify-metrics` is set to true, there is no much effect for the grafana charts, the only user-awareness change is some counter value show no-vaule instead of 0 value. 

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by glorv** [comment]
waiting for #12647 to be merged first

**Comment by glorv** [comment]
also cherry-pick #12671

**Review by glorv — APPROVED** [review]

**Review by BusyJay — APPROVED** [review]

**Pull request merged**
