### PR TITLE
copr: vectorize radians

### PR DESCRIPTION
**Pull request by AerysNan**
Signed-off-by: AerysNan <aerysnan@gmail.com>

PCP #5751

###  What have you changed?

Vectorize radians.

###  What is the type of the changes?

Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?

Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No.

###  Does this PR affect `tidb-ansible`?

No.

### CODE REVIEW

**Comment by AerysNan** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/46

**Comment by breeswish** [comment]
@sticnarf @lonng @andylokandy @iosmanthus

**Comment by lonng** [comment]
@AerysNan Thanks for your contribution, it's better to add a copr-test PR link in the description in the next time.

**Comment by AerysNan** [comment]
@lonng Jenkins CI seems to have failed but I don't quite understand. The failed test case doesn't even include the "radians" function implemented here. Any idea?

**Comment by breeswish** [comment]
@AerysNan It's a known unstable case that randomly fails due to a TiDB bug which is not yet fixed.

**Comment by AerysNan** [comment]
@sre-bot /run-all-tests

**Comment by AerysNan** [comment]
@sre-bot /run-all-tests

**Comment by AerysNan** [comment]
@breeswish merge failed with no error message. Maybe conduct merge once more?

**Comment by sticnarf** [comment]
Sorry it's caused by an unrelated unstable error.

**Comment by breeswish** [comment]
Currently TiDB has a bug that will cause copr-test fail. We should force merge.

**Pull request merged**
