### PR TITLE
[release-3.0] raftstore: check merge entries' length to avoid slice out of range

### PR DESCRIPTION
**Pull request by Connor1996**
## What have you changed? (mandatory)
In merge process, target region will send entries to fall-behind source region. It is possible to propose a `CompactLog` command after proposing `PrepareMerge`.  Note that, the `entries` involved in `CommitMerge` would not take the `CompactLog` record.

So during the merge process, if the source region catches up with the logs by raft append msgs, `self.raft_group.raft.raft_log.committed - log_idx` would be larger than `entries.len()` which leads to `entries[self.raft_group.raft.raft_log.committed - log_idx..]` out of slice range. 

So check the len before cutting up the slice.

## What are the type of changes? (mandatory)
- Bugfix (a change which fixes an issue)

## How has this PR been tested? (mandatory)
unit-test 

## Does this PR affect documentation (docs) or release note? (mandatory)
No

## Does this PR affect `tidb-ansible` update? (mandatory)
No

## Refer to a related PR or issue link (optional)
https://github.com/pingcap/tidb/issues/11744

### CODE REVIEW

**Comment by siddontang** [comment]
no test? @Connor1996

**Comment by Connor1996** [comment]
@siddontang Already added locally, but it shows the reason is not what I thought. So this PR's fix may be incomplete, still in investigation.

**Pull request closed without merging**
