### PR TITLE
chore: fix error message typo

### PR DESCRIPTION
**Pull request by 0o001**
### What is changed and how it works?

Issue Number: Ref https://github.com/tikv/tikv/issues/15990

What's Changed:

```commit-message
fix error message typo 
```

### Check List 

Tests 

- No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by Connor1996** [comment]
Please sign off to fix DCO

**Review by glorv — APPROVED** [review]

**Comment by glorv** [comment]
@Connor1996 Please help edit the PR description and link a related issue.

**Pull request merged**
