### PR TITLE
Use `dyn` keyword for traits objects

### LINKED ISSUE #4197: Convert trait objects to `dyn` traits
TiKV is using Rust 2018 now. Let's migrate to the `dyn` syntax for trait objects. This should be pretty easy with the `#![deny(bare_trait_objects)]` lint. Just apply that to the tikv crate root and fix all the errors.

Then do the same for the bins, tests and benches listed in `Cargo.toml`, and the same for the component projects in the `components` directory.

### PR DESCRIPTION
**Pull request by crlf0710**
Resolves #4197.  

I use windows-gnu toolchain and there're some minor compilation problems in this crate and its dependencies. For those issues in this crate i also fixed them in separate commits. If requested i can move them off the shelf.

### CODE REVIEW

**Comment by breeswish** [comment]
Thanks a lot! I really like this change, but there are few questions:
- why there is a new "code of conduct" file?
- I suggest to write your deny rule in Makefile so that you don't need to deny it in every cargo project.

**Comment by breeswish** [comment]
I merger code of conduct PR into master. Please resolve conflicts :)

**Comment by crlf0710** [comment]
@breeswish 
* Somehow i rebased the changes upon another commit. Now i've rebased it to the newest master commit.
* I know i can add '-D' argument to deny a specific lint for `rustc`, but do you have any suggestion on how to do this on the cargo command line? Or shall i check if `clippy` can enforce this lint?

**Comment by breeswish** [comment]
@crlf0710 We mostly invoke cargo command via Makefile, so you can just add it to Makefile. Also it should be fine when people invoke cargo command directly because it is a deny rule.

**Comment by brson** [comment]
Thanks for the PR @crlf0710 and the review @breeswish . I didn't get to this today, but tomorrow I will.

**Comment by brson** [comment]
This looks perfect @crlf0710. Beautifully clean and to the point. And I'm heartened to see that we use dynamic dispatch with some frequency.

Why delete the `#[cfg(unix)]` from tikv-importer, tikv-server? I see that there's no corresponding cfg in tikv-ctl, but I don't know offhand whether it's ok to remove those, and it looks unrelated to the
task at hand.

If you agree it's unrelated, can you remove those two lines, and optionally follow up with another PR/issue?

If you haven't yet you might try building with these commands to make sure you've compiled as much code as you can:

```
cargo build --all
cargo test --all --no-run
cargo bench --all --no-run
cargo build --all --features=no-jemalloc
cargo build --all --features=mem-profiling
```

The last two in particular may not be exercised by the CI.

As to @breeswish's request to put the lint in the Makefile, I don't have a particularly strong opinion w/r/t this PR, though I wish those kinds of things were somewhere that applied to `cargo` without running the makefile: 1) because I don't _think_ the CI uses the makefiles, at least not for testing, and it's best if the devs and the CI are using the same configuration; 2) because I personally do a lot of development without the makefiles. My wishes about this are beside the point of this PR though, so do go ahead and move the deny rules into the Makefile.

@breeswish where in the Makefile should the `-Dwhatever` flag be added? The only existing code to go off is the `clippy` rule, which turns off a bunch of clippy-default lints. Is it sufficient for us to just check this when running `make clippy`?

**Comment by brson** [comment]
Also, this PR is going to bitrot fast, so once the two identified issues are resolved, we'll need to be vigilant to get two approvals quickly and merge.

**Comment by crlf0710** [comment]
@brson 
1. For the `#[unix]` changes: I've removed the irrelevant commits. 

2. For the Makefile change, frankly i don't know how to set up built in deny rules from the command line. 
The closest i can find is [this feature request](https://github.com/rust-lang/cargo/issues/5034), which is still open and not yet implemented. And for `cargo clippy`, it seems it can't enforce rustc builtin lints at all.

**Comment by crlf0710** [comment]
And I've compiled as much code as I can on windows, including both of the features you mentioned.

**Comment by breeswish** [comment]
How about using rustc flags as [documented here](https://doc.rust-lang.org/rustc/lints/levels.html#via-compiler-flag)?

@brson What's your idea of the two solution: adding `#[deny]` to every project, or we reject it via command line globally?

**Comment by crlf0710** [comment]
@breeswish But that cannot be applied to the `cargo build` command, can it?

**Comment by breeswish** [comment]
@crlf0710 You can supply extra rustc arguments by `RUSTFLAGS=xx`. But this is a bit verbose. So I would like to see what's @brson 's idea.

**Comment by brson** [comment]
@BusyJay @crlf0710 I think it should go in the Makefiles. For the sake of putting all the extern lint adjustments in the same place I'd also say it should go specifically on the "clippy" rule. Bonus: clippy will accept arbitrary lints, not just clippy lints, so no need to use RUSTFLAGS. Just add `-D bare_trait_objects` to the end of the existing list and we're done.

Thanks @crlf0710!

**Comment by crlf0710** [comment]
ok, i've changed the makefile, removed the `#[deny]`, rebased the changes and modified recently involved bare trait objects.

**Comment by breeswish** [comment]
@brson @overvenus PTAL

**Comment by crlf0710** [comment]
Rebased and fixed one newly introduced bare trait object.

**Comment by crlf0710** [comment]
Somehow the modification dismissed the earlier reviews. @breeswish @ice1000 @brson @overvenus

**Comment by overvenus** [comment]
@crlf0710 Hi! There is a small conflict on the `src/pd/util.rs`, could you resolve it?

**Comment by crlf0710** [comment]
fixed~

**Pull request merged**
