### PR TITLE
raftstore: Remove deprecated seek_region from raftstore

### PR DESCRIPTION
**Pull request by MyonKeminta**
Signed-off-by: MyonKeminta <MyonKeminta@users.noreply.github.com>

## What have you changed? (mandatory)

This PR removes the deprecated functionality `seek_region` from raftstore, since now it's implemented in `region_info_accessor`. To remove this, code of integration tests is also modified.

## What are the type of the changes? (mandatory)

- Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)

By unit tests and integration tests

## Does this PR affect documentation (docs) update? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No

### CODE REVIEW

**Comment by siddontang** [comment]
Do you need to remove https://github.com/tikv/tikv/blob/279a4d9598e3c7002886d4440a0a21439644aa32/src/storage/engine/mod.rs#L148?

**Comment by MyonKeminta** [comment]
definitely not.

**Comment by siddontang** [comment]
> definitely not.

Is it proper to be put in the storage mod now? IMO, storage should not care Raft region too much.

**Comment by MyonKeminta** [comment]
Seems not to be very proper..
But this PR is to remove the `seek_region` from raftstore ASAP. Other refactoring can be done in future PRs.

**Comment by siddontang** [comment]
Got it

LGTM 

@MyonKeminta please go on to clean up the code.

**Pull request merged**
