### PR TITLE
copr: Vectorize AddDatetimeAndString

### LINKED ISSUE #9016: Coprocessor functions migration from non-vec framework
## Feature Request

Coprocessor historically has two implementations. One is based on the vectorized framework, and the other one is based on the plain (non-vec) framework, which was removed recently. A few of the functions in the legacy non-vec framework have not been ported into the vectorized framework yet.

The following is the list of functions that existed in non-vec framework but not in vectorized framework. You may also want to look into the [non-vec framework before it was removed](https://github.com/tikv/tikv/tree/1a88f12ebf50064b992fc5efc7e7f55795210521/components/tidb_query_normal_expr/src).

- [x] AddDateAndDuration
- [ ] AddDateAndString
- [x] AddDatetimeAndDuration
- [x] AddDatetimeAndString
- [x] AddDurationAndDuration
- [x] AddDurationAndString
- [ ] AddTimeDateTimeNull
- [ ] AddTimeDurationNull
- [ ] AddTimeStringNull
- [ ] Compress
- [x] Date
- [ ] DateDiff
- [ ] Instr
- [x] Locate2ArgsUtf8
- [x] Locate3ArgsUtf8
- [ ] Lower
- [x] NullTimeDiff
- [x] Quote
- [x] RegexpSig
- [x] RegexpUtf8Sig
- [ ] RpadUtf8
- [x] SubDateAndDuration
- [ ] SubDateAndString
- [x] SubDatetimeAndDuration
- [ ] SubDatetimeAndString
- [x] SubDurationAndDuration
- [x] SubDurationAndString
- [ ] SubTimeDateTimeNull
- [ ] SubTimeDurationNull
- [ ] Substring2Args
- [ ] Substring2ArgsUtf8
- [ ] Substring3Args
- [ ] Substring3ArgsUtf8
- [ ] Trim2Args
- [ ] TruncateDecimal
- [ ] TruncateUint
- [ ] Uncompress
- [x] WeekWithoutMode
- [x] YearWeekWithMode
- [x] YearWeekWithoutMode

### PR DESCRIPTION
**Pull request by weastel**
Signed-off-by: Drumil Patel <drumilpatel720@gmail.com>

### What problem does this PR solve?

Issue Number: Partially fixes #9016 

Problem Summary: Added Vectorize version for AddDatetimeAndString

### What is changed and how it works?

What's Changed: Implmented Vectorize vesion for AddDatetimeAndString

### Check List 

Tests 

- Unit test

### Release note 
- Partially fixes #9016

### CODE REVIEW

**Review by Xuanwo — APPROVED** [review]

**Review by andylokandy — APPROVED** [review]
/lgtm

**Comment by Xuanwo** [comment]
Please don't use `fixes #9016` in issue, or #9016 will be closed.

**Pull request merged**
