### PR TITLE
coprocessor/codec/mysql/duration: Fix micro_secs of Duration

### PR DESCRIPTION
**Pull request by koushiro**
Signed-off-by: koushiro <koushiro.cqx@gmail.com>

## What have you changed? (mandatory)

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:
- Fix function `micro_secs` of struct `Duration`. The original function returns nanoseconds. 

## What are the type of the changes? (mandatory)

The currently defined types are listed below, please pick one of the types for this PR by removing the others:
- Bug fix (non-breaking change which fixes an issue)

## How has this PR been tested? (mandatory)
Finished unit tests of codec/mysql/duration.rs.
No additional tests in this change.

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)
No

## Does this PR affect tidb-ansible update? (mandatory)
No

## Refer to a related PR or issue link (optional)
[issue#3601](https://github.com/tikv/tikv/issues/3601)

### CODE REVIEW

**Comment by koushiro** [comment]
@overvenus  yes, I can do that. Is a unit test about `micro_secs`  or other functions of `Duration`?

**Comment by breeswish** [comment]
You can just test the function `micro_secs` and ensure that it is indeed returning a micro second part.

**Comment by BusyJay** [comment]
I think the value returned by the method is expected, it's just the name that is wrong.

**Comment by koushiro** [comment]
After thinking about it for a long time, I found that both `nano_secs` and `micro_secs` can be obtained from the public member `StdDuration` of `Duration`. Actually, these two functions are not needed.
If you agree with me, I will submit a new commit -- remove the `micro_secs`.

**Comment by breeswish** [comment]
@koushiro I guess it is to keep similar interface as TiDB.

**Comment by koushiro** [comment]
@breeswish  There is only a `Microsecond` interface in tidb but no interface like `nanosecond`.  Even if there is an interface, it should be `microsecond`.
So I don't agree with @BusyJay ‘s thoughts.

**Comment by breeswish** [comment]
@BusyJay is the original author of this piece of code, that returns nano in a function named micro :) Maybe you can provide both functions, nanoseconds and microseconds. Seems that nano seconds is only used for tikv internal implementation.

**Comment by breeswish** [comment]
Please run make format to fix CI

**Comment by huachaohuang** [comment]
@koushiro Seems our jenkins ci cannot build this PR because the branch name "fix_issue#3601" contains a special character '#', sorry for that but it is not easy for us to fix that for now. Can you please rename the branch name without the special character?

**Comment by koushiro** [comment]
@huachaohuang Okay, I will close the pr and submit a new pr.

**Comment by huachaohuang** [comment]
Close this in favor of https://github.com/tikv/tikv/pull/3625.

**Pull request closed without merging**
