### PR TITLE
coprocesser: implement upper and lower function on GBK charset

### PR DESCRIPTION
**Pull request by xiongjiwei**
Signed-off-by: xiongjiwei <xiongjiwei1996@outlook.com>

### What is changed and how it works?

Close https://github.com/tikv/tikv/issues/11757

some characters only have lower or upper case under gbk encoding. if so, we should make its lower or upper eq to itself

see https://github.com/pingcap/tidb/pull/28869 for more details

### Check List 

Tests 

- Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by xiongjiwei** [comment]
/cc @andylokandy @zhongzc 
PTAL

**Review by zhongzc — APPROVED** [review]

**Review by breeswish — APPROVED** [review]

**Pull request merged**
