### PR TITLE
[Cherry-pick] Merge "raftstore & raftstore-v2:control grpc server according to slowness(#15088)" to 7.1.

### LINKED ISSUE #15086: TiKV provides APIs to restart grpc service
When a TiKV node becomes unhealthy  (such as slow IO, network partition from certain nodes),  we usually want to fail fast existing requests and do leader transfer. 
However, we may not want to kill a tikv server when it's unhealthy because restarting the tikv is too expensive and it may impact performance (due to warmup cache). 
So there should be a way to do a soft restart that will only start/stop grpc services

### PR DESCRIPTION
**Pull request by LykxSassinator**
This is a manual cherry-pick of https://github.com/tikv/tikv/pull/15088

### What is changed and how it works?

Issue Number: Close #15086

What's Changed:

```commit-message
Make raftstore & raftstore-v2 able to control the grpc service, according to the slowness.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
None.
```

### CODE REVIEW

**Comment by LykxSassinator** [comment]
/cc @tonyxuqqi @overvenus 
PTAL, thx.

**Review by overvenus — APPROVED** [review]

**Review by tonyxuqqi — APPROVED** [review]

**Pull request merged**
