### PR TITLE
statistic: more stable test for query test

### LINKED ISSUE #10584: Unstable test `raftstore::test_stats::test_query_stats`
## Bug Report
```
[2021-07-17T13:20:54.194Z] 21:20:42.330 runner.rs:49: [DEBG] case end, name: raftstore::test_stats::test_query_stats

[2021-07-17T13:20:54.194Z] 

[2021-07-17T13:20:54.194Z] + awk '/^failures/{flag=1}/^test result:/{flag=0}flag' tests.out

[2021-07-17T13:20:54.195Z] failures:

[2021-07-17T13:20:54.195Z] 

[2021-07-17T13:20:54.195Z] failures:

[2021-07-17T13:20:54.195Z]     raftstore::test_stats::test_query_stats

[2021-07-17T13:20:54.195Z] 

[2021-07-17T13:20:54.195Z] + gdb -c 'core.*' -batch -ex 'info threads' -ex 'thread apply all bt'

[2021-07-17T13:20:54.236Z] /home/jenkins/agent/tikv-master/build/core.*: No such file or directory.

[2021-07-17T13:20:54.236Z] No threads.

[2021-07-17T13:20:54.236Z] + exit 1
```

### Steps to reproduce

in ci https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/4372/pipeline

### PR DESCRIPTION
**Pull request by lhy1024**
Signed-off-by: lhy1024 <admin@liudos.us>

### What problem does this PR solve?

Issue Number: close #10584 

### What is changed and how it works?

What's Changed:

add more retry

### Check List 

Tests 

- Unit test
- Integration test
- Manual test
```
rm t.log
for i in {1..100}
do
    cargo test --package tests --test integrations -- raftstore::test_stats::test_query_stats --exact --nocapture &>> t.log
    sleep 1
done
cat t.log | grep panic
```
there is only panic with `No address added out of total 1 resolved`
image

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by hicqu — APPROVED** [review]

**Comment by yiwu-arbug** [comment]
@lhy1024 why the case was failing and what does the fix do?

**Comment by lhy1024** [comment]
> @lhy1024 why the case was failing and what does the fix do?

Sometimes that statistic is unstable, so I added retries and adjusted the tick interval

**Review by yiwu-arbug — APPROVED** [review]

**Pull request merged**
