### PR TITLE
engine: revert RocksDB update and update raft-engine

### PR DESCRIPTION
**Pull request by tabokie**
### What is changed and how it works?

Issue Number: Ref #13095, #13123

What's Changed:

- Revert the update and restore RocksDB version to 6.4
- Update raft-engine for a bugfix of tikv/raft-engine#250

```commit-message
None
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by Connor1996 — APPROVED** [review]

**Comment by ethercflow** [comment]
@tabokie  From CI's error info:
```
'storage::test_titan::test_delete_files_in_range_for_titan' panicked at 'called `Result::unwrap()` on an `Err` value: Engine("Not implemented: ")', tests/integrations/storage/test_titan.rs:334:10
```

It seems we need update rust-rocksdb's titan.

**Review by ethercflow — APPROVED** [review]
LGTM

**Pull request merged**
