### PR TITLE
diagnostics: fix unmatched memory info

### LINKED ISSUE #9532: TiKV reported memory is wrong
### What version of TiKV are you using?

v4.0.9

### What operating system and CPU are you using?

CentOS + tidb-operator.

### Steps to reproduce

Open TiDB Dashboard.

### What did you expect?

Memory usage should be <= 100%.

### What did happened?

We expect memory usage > 100%.

image

### Cause

In this [PR](https://github.com/tikv/tikv/pull/7074), a container memory quota is returned in the memory info, instead of a system memory capacity.

### PR DESCRIPTION
**Pull request by zhongzc**
Signed-off-by: Zhenchi <zhongzc_arch@outlook.com>

### What problem does this PR solve?

Issue Number: close #9532 

Problem Summary:

The value of total memory is from quota, while other memory infos are from system. It is improper to divide the quota memory by other system memory infos.

### What is changed and how it works?

Use the total memory from system. 

### Check List 

Tests 

- No code

### Release note 
- Fix unmatched memory information

### CODE REVIEW

**Review by breeswish — APPROVED** [review]

**Comment by breeswish** [comment]
@crazycs520 PTAL

**Review by crazycs520 — APPROVED** [review]
LGTM

**Pull request merged**
