### PR TITLE
monitors: Replace the description in English

### LINKED ISSUE #10381: Rewrite the descriptions of some monitors
## Development Task
There are some descriptions of monitors written in Chinese and perhaps we should change it to English. e.g.

Screen Shot 2021-06-17 at 5 55 35 PM

### PR DESCRIPTION
**Pull request by jackwener**
### What problem does this PR solve?

Issue Number: close #10381

### What is changed and how it works?

What's Changed:

Replace the description in English

### Related changes

None

### Check List 

Tests 

- No code

Side effects

- None

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by jackwener** [comment]
Just a little work.

**Comment by jackwener** [comment]
@hunterlxt @jackysp PTAL

**Review by jackysp — APPROVED** [review]
LGTM

**Review by hunterlxt — APPROVED** [review]

**Comment by jackwener** [comment]
@zhongzc PTAL

**Pull request merged**
