### PR TITLE
*: remove tikv-importer

### PR DESCRIPTION
**Pull request by kennytm**
Signed-off-by: kennytm <kennytm@gmail.com>

## What have you changed? (mandatory)

The KV importer service has been extracted into the [tikv/importer](https://github.com/tikv/importer) repository. Only the SST importer service needs to remain here. All code related to the KV importer has been removed here.

## What are the type of the changes? (mandatory)

- Engineering (engineering change which doesn't change any feature or fix any issue)

## How has this PR been tested? (mandatory)

cargo check

## Does this PR affect documentation (docs) or release note? (mandatory)

- May need to be included in the release note for the source code location.

## Does this PR affect tidb-ansible update? (mandatory)

No, the binary has already been switched to be packaged from tikv/importer.

### CODE REVIEW

**Comment by siddontang** [comment]
If we can support a plugin which can let the user register their own gRPC server, maybe we can make code cleaner, right?  @kennytm

**Comment by kennytm** [comment]
@siddontang Certainly. But that may make using Importer harder, since that ImportSSTService plugin will need to be installed on every TiKV node.

**Comment by overvenus** [comment]
Could you move `src/import` to `components/import`?

**Comment by kennytm** [comment]
@overvenus OK, will move in another PR.

**Comment by kennytm** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/6452/pipeline/

```
thread 'raftstore-1-1::test_node_request_snapshot_reject_merge' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:999:5
```

I guess it is spurious.

/test

**Pull request merged**
