### PR TITLE
test: add from test for config

### PR DESCRIPTION
**Pull request by hi-rustin**
Signed-off-by: hi-rustin <rustin.liu@gmail.com>

### What problem does this PR solve?

See: https://github.com/tikv/tikv/pull/10923#pullrequestreview-750038054

Problem Summary:

### What is changed and how it works?

add from test for config.

What's Changed:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

None

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]

**Comment by hi-rustin** [comment]
/cc @amyangfei 
Could you please take a look? Thanks!

**Comment by hi-rustin** [comment]
/remove-label needs-cherry-pick-5.0

/label needs-cherry-pick-4.0

Already picked into https://github.com/tikv/tikv/pull/10923

**Review by amyangfei — APPROVED** [review]

**Comment by hi-rustin** [comment]
/assign @overvenus 

Could you please help me trigger the merge process? Thanks!

**Pull request merged**
