### PR TITLE
cdc: fix incorrect resolved ts timeout (#8573)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #8573 to release-4.0

---

Signed-off-by: 5kbpers <tangminghua@pingcap.com>

### What problem does this PR solve?

Problem Summary:

Resolved ts was advanced periodically by getting tso and waiting for timeout simultaneously, which makes tso delayed.

### What is changed and how it works?

Get tso after timeout.

Proposal: [xxx](url) 

What's Changed:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 
* N/A

### CODE REVIEW

**Review by MyonKeminta — APPROVED** [review]

**Review by overvenus — APPROVED** [review]
LGTM

**Comment by Connor1996** [comment]
@5kbpers unit test failed

**Pull request merged**
