### PR TITLE
test: fix unstable test failed of test_region_heartbeat_timestamp

### PR DESCRIPTION
**Pull request by jiyingtk**
###  What have you changed?
The purpose of test_region_heartbeat_timestamp is to test the report time of region heartbeat, we want the last_report_ts be incremental in each store's region heartbeat, but previous test was unstable. Now it is fixed.

###  What is the type of the changes?

- Bugfix (a change which fixes an issue)

###  How is the PR tested?

make dev

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No.

###  Does this PR affect `tidb-ansible`?

No.

###  Refer to a related PR or issue link (optional)
https://github.com/tikv/tikv/issues/5329

### CODE REVIEW

**Comment by sticnarf** [comment]
@jiyingtk 
still fails https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/10836/log/?start=0

**Comment by jiyingtk** [comment]
Is it still failed occasionally? In this log, I found the test failed because of the network problem, not the assertion error in the test code. 
image
So could it be something else causes fail?

**Comment by sticnarf** [comment]
image

There's an assertion error. But it is indeed likely that the cause is not the test code...

**Comment by jiyingtk** [comment]
I found the "test_delay_split_region" also failed with the same reason
image
So maybe the machine occurred some problems during the test? (Should we consider this situation in the test code?)

**Pull request merged**
