### PR TITLE
copr: Add enum support for codegen

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

### What problem does this PR solve?

Add enum support in codegen, after this PR merged, we can implement copr functions like:

```rust
#[rpn_fn]
fn cast_enum_as_int(val: EnumRef) -> Result<Option<Int>> {
    Ok(Some(val.value() as i64))
}
```

### Check List

Tests

- Unit test
- Integration test

### CODE REVIEW

**Review by skyzh — APPROVED** [review]
LGTM

**Comment by skyzh** [comment]
Would you please take a look? @andylokandy

**Comment by Xuanwo** [comment]
merged into #9133

**Pull request closed without merging**
