### PR TITLE
fuzz: add tests for new codecs

### PR DESCRIPTION
**Pull request by youjiali1995**
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

## What have you changed? (mandatory)
* add fuzz test for new codecs.

## What are the type of the changes? (mandatory)
- Improvement (change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)
manual tests

## Does this PR affect documentation (docs) update? (mandatory)
no

## Does this PR affect tidb-ansible update? (mandatory)
no

## Refer to a related PR or issue link (optional)
https://github.com/tikv/tikv/issues/4041

### CODE REVIEW

**Comment by breeswish** [comment]
Wait for https://github.com/tikv/tikv/pull/4454 being merged.

**Comment by AndreMouche** [comment]
Please fix the conflicts.

**Comment by youjiali1995** [comment]
Fixed

**Comment by AndreMouche** [comment]
@breeswish PTAL

**Comment by breeswish** [comment]
Are they running on our testing infra?

**Comment by youjiali1995** [comment]
How can I confirm it? Did you mean schrodinger-test? I found a related PR https://github.com/pingcap/schrodinger-test/pull/299. @breeswish

**Comment by breeswish** [comment]
@youjiali1995 You need to log into our schrodinger platform, then manually create corresponding cats or boxes for these fuzz tests.

**Comment by AndreMouche** [comment]
any update?

**Pull request closed without merging**
