### PR TITLE
Fix unexpected panic when sampling in load base split

### PR DESCRIPTION
**Pull request by lhy1024**
Signed-off-by: lhy1024 <admin@liudos.us>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/22963 

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

- No Release note

### CODE REVIEW

**Comment by lhy1024** [comment]
@hicqu PTAL

**Review by hicqu — APPROVED** [review]

**Review by sticnarf — APPROVED** [review]

**Pull request merged**
