### PR TITLE
metric: add stale read count metric

### LINKED ISSUE #11015: Add stale read metrics
### What version of TiKV are you using?
versions support stale read

### What operating system and CPU are you using?
n/a

### Steps to reproduce
Make stale read requests from TiDB

### What did you expect?
From Grafana I want to know how many stale read requests are handled by each TiKV node.

### What did happened?
There isn't such metrics currently

### PR DESCRIPTION
**Pull request by NingLin-P**
### What problem does this PR solve?

Issue Number: close #11015 

### What is changed and how it works?

What's Changed:

Add stale read count metric to the `TiKV Details > Local reader` panel

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

### Release note 

```release-note
add stale read count metric
```

### CODE REVIEW

**Review by Yisaer — APPROVED** [review]

**Review by nolouch — APPROVED** [review]
lgtm

**Comment by nolouch** [comment]
cc @JmPotato

**Review by BusyJay — APPROVED** [review]

**Pull request merged**
