### PR TITLE
 Extract Coprocessor DAG

### PR DESCRIPTION
**Pull request by YangKeao**
## What have you changed? (mandatory)

1. Extract coprocessor/dag into a crate. It was divided into two parts: one for handling grpc request (the implementation of `RequestHandler` and handler builder), the other part is all executors. I only extract executors into new `cop_dag` crate.

2. Some mods related with these executors are also moved into `cop_dag` crate, such as `codec` mod.

3. `Store` and `Scanner` trait previously placed in `storage` mod is moved into `cop_dag`. `CFStatistics` and `Statistics` are also moved into `cop_dag` crate. The storage interface in `cop_dag` is provided by these traits and structs.

4. Most tests of executors are moved into `tests` folder, while some tests are no related with implementation of storage so they can still be placed in `cop_dag` crate.

5. Use a BTreeMap as a simple KV database to test this crate.

This PR is still WIP:

- [ ] Clean the relation of `cop_dag` and `tikv`. Delete some redundant `use` of `cop_dag`
- [ ] Provide it's own interface without protobuf structures. (But convert between two structures may affect performance. How can I do this better?)
- [ ] Merge with the latest master. ( I can image how scary it can be :cry: )
- [ ] Provide some documents on what it is and how to use it (without tikv).

## What are the type of the changes? (mandatory)

Engineering

## How has this PR been tested? (mandatory)

Yes. It has passed all previous existed tests. As most of this work is copy & paste :laughing: , no new test is needed.

However, I am not very confident of this pr (because this is a huge refactoring and most done manually). More tests should be done for this pr (but I have no idea what I need to do).

## Does this PR affect documentation (docs) or release note? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No

## Refer to a related PR or issue link (optional)

#4180

### CODE REVIEW

**Comment by YangKeao** [comment]
@breeswish Do you have any suggestion on this PR?

**Comment by breeswish** [comment]
Oh this is a huge PR 🤣But very cool anyway! Sadly we have very frequent development for Coprocessor recently and I'm afraid your PR may constantly meet conflicts. After late Aug the develop process should be not so frequent though.

I'm uncertain about your change to this:

> Store and Scanner trait previously placed in storage mod is moved into cop_dag. CFStatistics and Statistics are also moved into cop_dag crate. The storage interface in cop_dag is provided by these traits and structs.

I will take a look at your implementation and try with myself to see if there are better ways.

**Comment by YangKeao** [comment]
After extracting DAG coprocessor, this `scan` method in the implementation of Scanner for `FixtureStoreScanner` and `Scanner<S>` (in `storage::mvcc::reader::scanner::mod`)  is duplicated. `default impl` may be needed to deal with this duplicate. [RFC](https://github.com/rust-lang/rfcs/blob/master/text/1210-impl-specialization.md) is here.

Or is there any way to partially implement a trait?

**Comment by breeswish** [comment]
@YangKeao They belongs to different traits, and should not conflict each other. (For example, you can use [fully-qualified syntax](https://doc.rust-lang.org/book/ch19-03-advanced-traits.html#fully-qualified-syntax-for-disambiguation-calling-methods-with-the-same-name)).

I will extract a new scanner trait for Coprocessor that best suits current architecture (as well as be capable to be extracted) in the next several weeks. Currently the most uncomfortable part is the statistics. After that, I guess your PR can be continued like a charm!

**Comment by YangKeao** [comment]
@breeswish I mean they implement the same trait (`Scanner`) . And the implementation of `scan` method is same, so we shouldn't implement it redundantly. Before extracting it, `scan` has a default implementation. But after extracting it, without `MvccError` type we cannot implement it in extracted `cop_dag` crate.

With [impl-specialization](https://github.com/rust-lang/rfcs/blob/master/text/1210-impl-specialization.md) I can give it a default implementation only in `tikv` crate to remove the redundant codes.

Maybe you can take it into account when designing `Scanner` trait (though I don't know how).

**Comment by breeswish** [comment]
Closing for #5155

**Pull request closed without merging**
