### PR TITLE
deadlock: more solid role change observer (#6415) (#6431)

### PR DESCRIPTION
**Pull request by youjiali1995**
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

###  What have you changed?
Cherry pick #6415

### CODE REVIEW

**Comment by youjiali1995** [comment]
@AndreMouche @sticnarf @MyonKeminta PTAL

**Comment by sticnarf** [comment]
Fix the conflicts please. :)

**Comment by youjiali1995** [comment]
@MyonKeminta PTAL

**Pull request merged**
