### PR TITLE
Support batch split region command and empty batch command

### PR DESCRIPTION
**Pull request by disksing**
###  What have you changed?
Cherry-pick #5001 #5268 #5466 

###  What is the type of the changes?
- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?

unit-tests

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

NOTE: Does not support new TiDB run with old TiKV. For example, TiDB v3.0.4 + TiKV v3.0.0.

###  Does this PR affect `tidb-ansible`?

If there is a configuration or metrics change, please file a PR in [tidb-ansible](https://github.com/pingcap/tidb-ansible), and add the PR number here.

###  Refer to a related PR or issue link (optional)
#5001 #5268 #5466 

###  Benchmark result if necessary (optional)
None

###  Any examples? (optional)
None

### CODE REVIEW

**Comment by AndreMouche** [comment]
Could we use the tag `NeedCherryPickxxx`?

**Comment by disksing** [comment]
@AndreMouche I don't think bot can properly handle it because it depends on another kvproto branch.

**Pull request merged**
