### PR TITLE
*: group imports using StdExternalCrate

### LINKED ISSUE #12455: Format imports
## Development Task

Format imports for beauty.

### PR DESCRIPTION
**Pull request by youjiali1995**
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### What is changed and how it works?

Issue Number: Close #12455

What's Changed:

I remembered nrc proposed a code-style that we may group imports in some order, now we can use `rustmft` to do it.
```commit-message
group imports using StdExternalCrate for beauty.
```

### Check List 

Tests 

- No code

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by sticnarf — APPROVED** [review]
Looks neat.

**Review by innerr — APPROVED** [review]
LGTM

**Pull request merged**
