### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by zhang555**
###  What have you changed?

fix typo 

###  What is the type of the changes?

- Misc (other changes)

###  How is the PR tested?

- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

no

###  Does this PR affect `tidb-ansible`?

no

### CODE REVIEW

**Comment by overvenus** [comment]
Hi @zhang555 Could you squash and sign your commits?

**Comment by zhang555** [comment]
hello @overvenus  ,  I'm not sure, how to squash . 
I have merged several times master branch , make it more complex to squash .

**Comment by iosmanthus** [comment]
@zhang555 Please fix `DCO`

**Comment by zhang555** [comment]
> @zhang555 Please fix `DCO`

fixed

**Comment by youjiali1995** [comment]
@zhang555 Thanks!

**Pull request merged**
