### PR TITLE
copr: add vectorized json-depth

### PR DESCRIPTION
**Pull request by hawkingrei**
Signed-off-by: Wangweizhen <hawking.rei@gmail.com>

PCP #5751

###  What have you changed?

Add vectorized json-depth

###  What is the type of the changes?

- New feature

###  How is the PR tested?

Unit tested. Will run copr test later.

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No. It should not change the behavior.

###  Does this PR affect `tidb-ansible`?

No.

### CODE REVIEW

**Comment by breeswish** [comment]
Thanks! LGTM. However it shall be merged after https://github.com/tikv/tikv/pull/6167

**Comment by hawkingrei** [comment]
@breeswish @niedhui  PTAL

**Pull request merged**
