### PR TITLE
resolved_ts: do not attempt to call check_leader on tiflash

### LINKED ISSUE #12092: v5.3.1 version, run tpch workload, print lots of [advance.rs:273] ["check leader failed"]
### What version of TiKV are you using?
v5.3.1

### What operating system and CPU are you using?
linux

### Steps to reproduce
1. install v5.3.1
2. /data-sdb/tools/go-tpc/bin/go-tpc tpch -H xxx.16.5.xxx -P 4000 -D tpch --sf 1 --analyze --tiflash prepare 

### What did you expect?
run normally

### What did happened?
[2022/03/04 12:35:43.011 +08:00] [ERROR] [advance.rs:273] ["check leader failed"] [to_store=56] [store_id=1] [error="RpcFailure(RpcStatus { code: 12-UNIMPLEMENTED, message: \"\", details: [] })"]
[2022/03/04 12:35:44.011 +08:00] [INFO] [<unknown>] ["New connected subchannel at 0x7f7efa22e690 for subchannel 0x7f7e88e1d1c0"]
[2022/03/04 12:35:44.011 +08:00] [ERROR] [advance.rs:273] ["check leader failed"] [to_store=56] [store_id=1] [error="RpcFailure(RpcStatus { code: 12-UNIMPLEMENTED, message: \"\", details: [] })"]
[2022/03/04 12:35:45.012 +08:00] [INFO] [<unknown>] ["New connected subchannel at 0x7f7e4a64c0f0 for subchannel 0x7f7e88e1d1c0"]
[2022/03/04 12:35:45.012 +08:00] [ERROR] [advance.rs:273] ["check leader failed"] [to_store=56] [store_id=1] [error="RpcFailure(RpcStatus { code: 12-UNIMPLEMENTED, message: \"\", details: [] })"]
[2022/03/04 12:35:46.013 +08:00] [INFO] [<unknown>] ["New connected subchannel at 0x7f7efbb97200 for subchannel 0x7f7e88e1d1c0"]
[2022/03/04 12:35:46.013 +08:00] [ERROR] [advance.rs:273] ["check leader failed"] [to_store=56] [store_id=1] [error="RpcFailure(RpcStatus { code: 12-UNIMPLEMENTED, message: \"\", details: [] })"]
[2022/03/04 12:35:47.015 +08:00] [INFO] [<unknown>] ["New connected subchannel at 0x7f7efb329ed0 for subchannel 0x7f7e88e1d1c0"]
[2022/03/04 12:35:47.015 +08:00] [ERROR] [advance.rs:273] ["check leader failed"] [to_store=56] [store_id=1] [error="RpcFailure(RpcStatus { code: 12-UNIMPLEMENTED, message: \"\", details: [] })"]
[2022/03/04 12:35:48.015 +08:00] [INFO] [<unknown>] ["New connected subchannel at 0x7f7efaaa7790 for subchannel 0x7f7e88e1d1c0"]
[2022/03/04 12:35:48.016 +08:00] [ERROR] [advance.rs:273] ["check leader failed"] [to_store=56] [store_id=1] [error="RpcFailure(RpcStatus { code: 12-UNIMPLEMENTED, message: \"\", details: [] })"]
[2022/03/04 12:35:49.016 +08:00] [INFO] [<unknown>] ["New connected subchannel at 0x7f7efa2939d0 for subchannel 0x7f7e88e1d1c0"]
[2022/03/04 12:35:49.016 +08:00] [ERROR] [advance.rs:273] ["check leader failed"] [to_store=56] [store_id=1] [error="RpcFailure(RpcStatus { code: 12-UNIMPLEMENTED, message: \"\", details: [] })"]
[2022/03/04 12:35:50.017 +08:00] [INFO] [<unknown>] ["New connected subchannel at 0x7f7efbb83140 for subchannel 0x7f7e88e1d1c0"]
[2022/03/04 12:35:50.017 +08:00] [ERROR] [advance.rs:273] ["check leader failed"] [to_store=56] [store_id=1] [error="RpcFailure(RpcStatus { code: 12-UNIMPLEMENTED, message: \"\", details: [] })"]
[2022/03/04 12:35:51.019 +08:00] [INFO] [<unknown>] ["New connected subchannel at 0x7f7efbb1f660 for subchannel 0x7f7e88e1d1c0"]
[2022/03/04 12:35:51.019 +08:00

log file
[tikv.log](https://github.com/tikv/tikv/files/8183096/tikv.log)

### PR DESCRIPTION
**Pull request by tabokie**
Signed-off-by: tabokie <xy.tao@outlook.com>

### What is changed and how it works?

Issue Number: Close #12092

What's Changed:

Read https://github.com/tikv/tikv/pull/12190#issuecomment-1223529240 for more context.

```commit-message
resolved_ts: do not attempt to call check_leader on tiflash
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hehechen** [comment]
In fact, TiFlash has implemented check_leader RPC, the "unimplemented" error just because the [address is wrong.](https://github.com/tikv/tikv/issues/13310)

**Comment by hehechen** [comment]
I have fixed the check_leader to TiFlash in [PR](https://github.com/tikv/tikv/pull/13312).

**Comment by tabokie** [comment]
@hehechen Could you point me to the TiFlash PR that implements it? This is a bug that needs to be fixed for v5.4~v6.1, not just master.

**Comment by hehechen** [comment]
> @hehechen Could you point me to the TiFlash PR that implements it? This is a bug that needs to be fixed for v5.4~v6.1, not just master.

TiFlash proxy is forked from TiKV, the version correspondence is as follows:
VMAP = {
    # Proxy -> TiKV
    "5.0": "5.0",
    "5.1": "5.1",
    "5.2": "5.2",
    "5.3": "5.1",
    "5.4": "5.1",
    "6.0": "5.1",
    "6.1": "6.0",
    "6.2": "6.1",
}

In TiFlash v5.4, I see that [check_leader is already implemented.](https://github.com/pingcap/tidb-engine-ext/blob/2f42417f48094a72bb94a61a92cde6968a233bd4/components/raftstore/src/store/worker/check_leader.rs#L111)

**Comment by tabokie** [comment]
@hehechen Great, it would be better if you can verify this in a real setup. For the time being I'll close this one and cherry-pick #13312.

**Pull request closed without merging**
