### PR TITLE
dist_release 3.0

### PR DESCRIPTION
**Pull request by brson**
## What have you changed? (mandatory)

This PR is against the release-3.0 branch.

Cherry-picks dist_release makefile changes from https://github.com/tikv/tikv/pull/4687

See that issue and the corresponding SRE PR for discussion: https://github.com/pingcap/SRE/pull/243

## What are the type of the changes? (mandatory)

- Engineering (engineering change which doesn't change any feature or fix any issue)

## How has this PR been tested? (mandatory)

Nothing. Assuming it works as the branch it was cherry-picked from.

## Does this PR affect documentation (docs) or release note? (mandatory)

Not user-facing docs. It is documented internally. Eventually it will be documented in a developer guide.

## Does this PR affect tidb-ansible update? (mandatory)

No

## Refer to a related PR or issue link (optional)

https://github.com/tikv/tikv/issues/4674
https://github.com/tikv/tikv/pull/4687
https://github.com/pingcap/SRE/pull/243

### CODE REVIEW

**Comment by brson** [comment]
Same as https://github.com/tikv/tikv/pull/4687 but for release-3.0. Should be approved by @zhouqiang-cl before merge. Like that PR, simply merging this PR should not affect anything, since all the release targets temporarily retain their previous behavior, so little risk.

If a cherry-pick is not the right way to update release-3.0 let me know the right way and I'll do it.

PTAL @breeswish @nrc @AndreMouche

**Comment by zhouqiang-cl** [comment]
bench and build_release should not be required

**Comment by BusyJay** [comment]
No, this is just for the CI builds and developers should not notice any difference.

**Comment by brson** [comment]
I don't have the correct permissions to merge this. Can someone else hit the button?

**Comment by zhouqiang-cl** [comment]
LGTM

**Pull request merged**
