### PR TITLE
resolved_ts: refine the resolved ts metric and panels

### PR DESCRIPTION
**Pull request by NingLin-P**
### What is changed and how it works?

What's Changed:

This PR mainly change the `Resolved TS gap` from `Histogram` to `IntGaugeVec` and add the `Fail advance ts count` panel:

截屏2021-06-11 下午4 36 04

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

Side effects

### Release note 

```release-note
resolved_ts: refine the `Resolved TS gap` panel and add the `Fail advance ts count` panel
```

### CODE REVIEW

**Review by nolouch — APPROVED** [review]
lgtm

**Comment by nolouch** [comment]
PTAL @JmPotato @Yisaer

**Comment by NingLin-P** [comment]
/hold

The PR still need a few changes

**Review by 5kbpers — APPROVED** [review]

**Pull request merged**
