### PR TITLE
grafana/dashboard: adjusted for better readability 

### LINKED ISSUE #12007: Some grafana expression are wrong or suboptimal
### What version of TiKV are you using?
v5.4.0

### What operating system and CPU are you using?
Doesn't matter

### Steps to reproduce
tiup playground

### What did you expect?
Good well defined graph.

### What did happened?
1. Pending task is wrong.
    Pending task metrics is a guage instead of a counter, its value should be used directly.
2. Hitmap in coprocessor is hard to read.
    It should use similar settings like Raft IO, which makes zero values transparent and choose more colorful scheme.

### PR DESCRIPTION
**Pull request by kevin-xianliu**
### What is changed and how it works?
Issue Number:  close #12007

What's Changed:
```commit-message
- add 99%, 95% and avg graph for aysnc snapshot & write in storage panel
- adjust heatmap in coprocessor panel for better readability
- change "Raft log speed"  to "Raft propose speed" in Raft Propose panel
```
Grafana panel looks like:
1) add 99%, 95% and avg graph for aysnc snapshot & write in storage panel
Screen Shot 2022-06-10 at 10 09 02 AM

2) adjust heatmap in coprocessor panel for better readability
Screen Shot 2022-06-10 at 10 04 34 AM

3) change "Raft log speed" to "Raft propose speed" in Raft Propose panel
Screen Shot 2022-06-10 at 10 10 16 AM

BTW, the metric below mentioned in [#12007 ](https://github.com/tikv/tikv/issues/12007) has been fixed by the others.
Pending task is wrong.
Pending task metrics is a guage instead of a counter, its value should be used directly.

### Related changes
None

### Check List
Tests
- Manual test
### Release note 

```release-note
Adjusted some dashboards for better readability
```

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
Please give a screenshot of how the grafana display looks like.

**Comment by zhangjinpeng1987** [comment]
@kevin-xianliu Please singed-off

**Comment by kevin-xianliu** [comment]
> @kevin-xianliu Please singed-off

done

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by Connor1996 — COMMENTED** [review]
Please fix the format of PR description

**Comment by BusyJay** [comment]
PR title is too long.

**Comment by kevin-xianliu** [comment]
> PR title is too long.

changed.

**Comment by kevin-xianliu** [comment]
> Please fix the format of PR description

fixed.

**Comment by BusyJay** [comment]
PR title is commit title, should be within 50 charaters. PR body should have a commit message block that places your commit message.

**Pull request merged**
