### PR TITLE
tests: refine the raftstore flashback tests

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

### What is changed and how it works?

Issue Number: ref #13303.

What's Changed:

```commit-message
Refine the raftstore flashback tests.
```

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
None.
```

### CODE REVIEW

**Comment by JmPotato** [comment]
/cc @HuSharp @Connor1996

Please help take a look, thx.

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by AndreMouche — APPROVED** [review]
LGTM

**Pull request merged**
