### PR TITLE
raftstore: refine raft log gc tick. (#10599)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #10599 to release-5.3
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/11278
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/11278:release-5.3-be6bf0da1de8
```

---

Signed-off-by: MrCroxx <mrcroxx@outlook.com>

### What problem does this PR solve?

Problem Summary:

Previously (before tikv#8668), trigger gc will force WAL sync in apply thread, and use `skip_gc_raft_log_ticks` to reduce syncing. After [tikv#8668](https://github.com/tikv/tikv/pull/8668), syncing is moved to background worker thread, and `CompactLog` cmds are batched. So there is no need to use `skip_gc_raft_log_ticks` anymore.

### What is changed and how it works?

What's Changed:

Remove `skip_gc_raft_log_ticks` and related codes.

Tests 

- Unit test
- Integration test

Side effects

### Release note 

```release-note
Add new config `raftstore.raft-log-compact-sync-interval = 2s`.
`raftstore.raft-log-gc-tick-interval` default value is replaced with an optimized value (10s => 3s).
```

### CODE REVIEW

**Review by yiwu-arbug — APPROVED** [review]

**Review by gengliqi — APPROVED** [review]

**Comment by MrCroxx** [comment]
Transfer leader seems not stable.

/run-all-tests

**Comment by tabokie** [comment]
@MrCroxx You failed the format checker. The commit message must reference an *issue* in TiKV repo

**Comment by MrCroxx** [comment]
@tabokie Oh, sorry. I referenced a pr.

**Pull request merged**
