### PR TITLE
always put engine info log into data dir

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve?

If `log-file` isn't specified, info log of rocksdb and raftdb will be print into `stderr`, just like TiKV's log. It makes the output hard to read.

### What is changed and how it works?

Always print two engines' info log into `*.info` in data directory. It's reasonable because the data directory is always available whatever `log-file` is specified or not.

### Check List 

Tests 

- No code

### Release note 
* No release note.

### CODE REVIEW

**Review by tabokie — COMMENTED** [review]
Why is #10194 depending on this one? Is there a specific use case to not specifying log-file?

I'm just thinking maybe user don't specify log-file purposefully to prevent any log file landing on disk/outside stdout.

**Comment by hicqu** [comment]
> Why is #10194 depending on this one?
tikv-ctl prints logs to stderr. Without the PR many rocksdb logs will be mixed.

 > Is there a specific use case to not specifying log-file?
In quick testing (start tikv-server at console) log-file generally will not be specified.

> user don't specify log-file purposefully to prevent any log file landing on disk/outside stdout
If it's not specified, tikv logs will be print to stderr mixed with rocksdb log, which is very hard to read.

**Review by tabokie — APPROVED** [review]
LGTM, I checked this is consistent with config template spec.

**Review by yiwu-arbug — APPROVED** [review]

**Pull request merged**
