### PR TITLE
raftstore: 2nd attempt to fix deadlock when creating compaction guard (#9552)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #9552 to release-5.0-rc
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/9571
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/9571:release-5.0-rc-d5d7f63b8461
```

---

Signed-off-by: Yi Wu <yiwu@pingcap.com>

### What problem does this PR solve?

Issue Number: #9044

Problem Summary:
After the introduction of compaction guard (#8115), RocksDB compaction threads can call region info accessor to create SST partitioner, which blocks the compaction thread. After #8821 both of region info accessor and region tasks in moved into a unified background worker pool. Per #8990, the thread pool would contain 2-3 threads. The region tasks, such as `RegionTask::Apply` and `RegionTask::Destroy`, can execute file ingestions, which leads to a blocking flush in `crocksdb_ingest_external_file_optimized` in rust-rocksdb. It can create a deadlock when compaction is waiting in the background pool queue to create SST partitioner and multiple region tasks are waiting for RocksDB threads to run flush.

Since the region tasks contain blocking flush call, which could run for a while, it doesn't sound like a good idea to have them run in the background pool, which could block other background pool tasks. Moving region info access to its own worker is a precaution to avoid similar deadlock happen in the future.

### What is changed and how it works?

What's Changed: 
Move region info accessor and region tasks each out of the unified background worker pool to their own worker thread. 

Also in compaction_guard.rs, access region info provider in `should_partition()` instead of `create_partitioner()`, since the later can be invoked by RocksDB while holding db_mutex.

### Related changes

compaction guard was added in #8115. 
SST cleanup task worker is merged with background worker in #8821. 
The first attempt to fix the deadlock was #9045.
background thread pool size was default to 2 instead of 1 in #8990, which should relieve the problem, but apparently it is not.

This PR depends on https://github.com/tikv/rust-rocksdb/pull/598.

### Check List 

Tests 

Will do manual test.

### Release note 

- Fix deadlock when creating compaction guard.

### CODE REVIEW

**Review by Connor1996 — APPROVED** [review]
/LGTM

**Comment by Connor1996** [comment]
This PR includes the cherry-pick of https://github.com/tikv/tikv/pull/9285 to fix the compilation.

**Review by hunterlxt — APPROVED** [review]
/lgtm

**Comment by yiwu-arbug** [comment]
I plan to cherry-pick #9285 separately in #9575.

**Comment by Connor1996** [comment]
> I plan to cherry-pick #9285 separately in #9575.

Okay, I revert the commit.

**Pull request merged**
