### PR TITLE
raftstore: add more duration metric about PerfContext

### PR DESCRIPTION
**Pull request by Little-Wallace**
### What is changed and how it works?

Add more duration metric of `PerfContext` for raftstore, such as "duration of waiting mutex for rocksdb::DBImpl::WriteIml".

### Related changes

- PR to update `pingcap/tidb-ansible`:

### Check List 

Tests 

- No

Side effects

- Performance regression
    - Consumes more CPU

### CODE REVIEW

**Comment by siddontang** [comment]
1. can it affect performance?
2. how to change it dynamically?

**Comment by Little-Wallace** [comment]
> 1. can it affect performance?
> 2. how to change it dynamically?

The default value is `Disable`. If user or developer want to know more performance details about  TiKV, they can change it to different perf-level. Obliviously, higher perf-level will cost more CPU and make performance worse.

**Comment by zhangjinpeng1987** [comment]
Please fix the confict

**Pull request merged**
