### PR TITLE
txn: Add more tests for MvccReader

### PR DESCRIPTION
**Pull request by MyonKeminta**
###  What have you changed?

This PR adds more unit tests for MvccReader:

* Added test for `seek_write` function
* Added some more cases for `get_write` function
* Added test for `scan_locks` function

###  What is the type of the changes?

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?

By CI.

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

- No.

###  Does this PR affect `tidb-ansible`?

No.

### CODE REVIEW

**Comment by MyonKeminta** [comment]
@sticnarf Oh I forgot that case. It seems it might run into an error. Wait a minute and I'll add it.

**Comment by MyonKeminta** [comment]
@sticnarf I just found that limit=0 means unlimited, which is covered by some integration tests. I've covered this case, PTAL again.

**Comment by sticnarf** [comment]
> @sticnarf I just found that limit=0 means unlimited, which is covered by some integration tests. I've covered this case, PTAL again.

Ah, better to document the behavior of `limit = 0` somewhere?

**Comment by MyonKeminta** [comment]
@sticnarf Good idea. I'll add it right here on the `scan_locks` function of MvccReader. Please wait a minute.

**Pull request merged**
