### PR TITLE
copr: add non-vectorized truncate_uint

### PR DESCRIPTION
**Pull request by ZiheLiu**
Signed-off-by: ZiheLiu <ziheliu1024@gmail.com>
PCP #5751 

###  What have you changed?
Add non-vectorized truncate_uint.

###  What is the type of the changes?

- New feature (a change which adds functionality)

###  How is the PR tested?

- Unit test

###  Does this PR affect `tidb-ansible`?

No.
###  Refer to a related PR or issue link (optional)
#5751 

###  Benchmark result if necessary (optional)
None.

###  Any examples? (optional)
No.

### CODE REVIEW

**Comment by ZiheLiu** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/123

**Comment by AndreMouche** [comment]
@breeswish @iosmanthus PTAL and the next review deadline is 2020-02-20 24:00:00

**Comment by ZiheLiu** [comment]
> Hi, @ZiheLiu Thanks for your contribution. When I was implementing `truncate_int` (#3532), @BusyJay suggest me to using a lookup table instead of code like `10_u64.pow(-d as u32)`. I forgot about it 🤣. Could you please change it in this PR, maybe you will also implement the vectorized version, so I think it's better to do it now.
> 
> By using a lookup table, we can also get rid of the magic number `-19` and `-18`

@niedhui Thanks for your review. Should I use lookup table as follows?
```rust
    
    const U64_TEN_POWS: [u64; 20] = [
        1,
        10,
        100,
        1_000,
        10_000,
        100_000,
        1_000_000,
        10_000_000,
        100_000_000,
        1_000_000_000,
        10_000_000_000,
        100_000_000_000,
        1_000_000_000_000,
        10_000_000_000_000,
        100_000_000_000_000,
        1_000_000_000_000_000,
        10_000_000_000_000_000,
        100_000_000_000_000_000,
        1_000_000_000_000_000_000,
        10_000_000_000_000_000_000,
    ];
    #[inline]
    pub fn truncate_uint(&self, ctx: &mut EvalContext, row: &[Datum]) -> Result<Option<i64>> {
        let x = try_opt!(self.children[0].eval_int(ctx, row));
        let d = try_opt!(self.children[1].eval_int(ctx, row));
        let d = if self.children[1].is_unsigned() { 0 } else { d };
        if d >= 0 {
            Ok(Some(x))
        } else {
            if -d >= U64_TEN_POWS.len() {
                return Ok(Some(0))
            }
            let x = x as u64;
            let shift = U64_TEN_POWS[-d];
            Ok(Some((x / shift * shift) as i64))
        }
    }

```

**Comment by niedhui** [comment]
Right. Would you mind to improve the `trunctate_int`  😄 (BTW I think this branch is not needed.)https://github.com/tikv/tikv/blob/e71c034fbea027fa2b545ee7b3319157ac5e3d45/components/tidb_query/src/expr/builtin_math.rs#L361

**Comment by ZiheLiu** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/123

**Comment by ZiheLiu** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/123

**Comment by ZiheLiu** [comment]
> Right. Would you mind to improve the `trunctate_int` 😄 (BTW I think this branch is not needed.)
> 
> https://github.com/tikv/tikv/blob/e71c034fbea027fa2b545ee7b3319157ac5e3d45/components/tidb_query/src/expr/builtin_math.rs#L361

@niedhui I improved `truncate_int` in this pr #6678.

**Comment by iosmanthus** [comment]
@ZiheLiu Thanks for your contribution. :+1:

**Pull request merged**
