### PR TITLE
suppress output when unwinding panic

### PR DESCRIPTION
**Pull request by tabokie**
Signed-off-by: tabokie <xy.tao@outlook.com>

### What problem does this PR solve?

Problem Summary:

`engine_trait_tests` heavily uses `catch_unwind` to test engine properly panicking when misused. The panic message is still printed which makes the CI report messy.

### What is changed and how it works?

What's Changed:

Change `panic_unwind` to `recover_safe`.

### Check List

Tests

- Unit test

### Release note

- No release note

### CODE REVIEW

**Comment by BusyJay** [comment]
Why not use `panic_hook::recover_safe`?

**Comment by tabokie** [comment]
> recover_safe

Didn't see this nice helper before, switching to it now.

**Review by BusyJay — APPROVED** [review]

**Review by sticnarf — APPROVED** [review]

**Pull request merged**
