### PR TITLE
*: Update security policy

### LINKED ISSUE #13928: Security policy not fully setup
## Bug Report

The `SECURITY.md` file isn't in the place that GitHub expects.

image

See also: https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

### PR DESCRIPTION
**Pull request by dveeden**
### What is changed and how it works?

1. Rename `security/SECURITY.md` to `SECURITY.md` to match what GitHub expects.
2. Add version 5.x and 6.x to the list of versions

Issue Number: Close #13928 

### Check List 

Tests 

- No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by sunxiaoguang — APPROVED** [review]

**Comment by dveeden** [comment]
@BusyJay https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

**Review by BusyJay — APPROVED** [review]

**Comment by BusyJay** [comment]
I believe 2.x is not supported anymore.

**Comment by dveeden** [comment]
@BusyJay can we merge this and let the security team take care of the removal of older versions?

**Pull request merged**
