### PR TITLE
cdc: separate resolved region outliers (#11991)

### LINKED ISSUE #11993: Separate broadcasing outlier regions and normal regions
See more: https://github.com/tikv/tikv/pull/11991

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #11991 to release-5.2
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/11999
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/11999:release-5.2-ff58728e03f3
```

---

### What is changed and how it works?

Issue Number: close #11993 close pingcap/tiflow#4516 close pingcap/tiflow#4311 ref pingcap/tiflow#4146

What's Changed:

```commit-message
Separate broadcasing outlier regions and normal regions,
so 1) downstreams know where they should send resolve lock requests,
and 2) resolved ts of normal regions does not fallback.
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test (add detailed scripts or steps below)
  Restart tikv nodes one by one.

### Release note 

```release-note
Reduce CDC recovery time by reduce the number regions that need resolved lock.
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]

**Review by 5kbpers — APPROVED** [review]

**Comment by overvenus** [comment]
@ti-chi-bot

**Pull request merged**
