### PR TITLE
Bump 5.2.0-alpha

### PR DESCRIPTION
**Pull request by purelind**
Signed-off-by: purelind <purelind@gmail.com>

### What problem does this PR solve?
Bump 5.2.0-alpha

Problem Summary:

### What is changed and how it works?
Bump 5.2.0-alpha

What's Changed:

### Related changes
- Bump 5.2.0-alpha

Tests 

- Unit test
- Integration test

### Release note

```
None
```

### CODE REVIEW

**Review by sticnarf — APPROVED** [review]
As 5.1.0 has released, I think we can merge this.

**Review by zhouqiang-cl — APPROVED** [review]
LGTM

**Comment by zhouqiang-cl** [comment]
@ti-chi-bot

**Comment by hi-rustin** [comment]
@ti-chi-bot

**Comment by Mini256** [comment]
/hold

Please check if the `Allow Edits by Maintainers` option is turned on, if this option is not turned on, the robot cannot perform merge master operation, this can cause PR to be incompatible.

**Pull request closed without merging**
