### PR TITLE
default cf memtable: sort row keys & insert with hint

### PR DESCRIPTION
**Pull request by zhangjinpeng87**
Signed-off-by: zhangjinpeng1987 <zhangjinpeng@pingcap.com>

## What have you changed? (mandatory)

- Sort row keys before write to memtable
- Insert with hint for default cf memtable

## What are the type of the changes? (mandatory)

- Improvement (change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)

- [ ] benchmark
- [ ] WriteBatch level insert hint in RocksDB

## Does this PR affect documentation (docs) or release note? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No

### CODE REVIEW

**Comment by siddontang** [comment]
cool, how about the performance?

**Comment by zhangjinpeng87** [comment]
Close PR since it is stale for years.

**Pull request closed without merging**
