### PR TITLE
Build: fix build on Mac OS by cfg'ing away pprof

### LINKED ISSUE #5932: Build broken on Mac OS
Due to pprof. I filed an issue: https://github.com/tikv/pprof-rs/issues/7 But the problem may be in TiKV rather than pprof - I don't think pprof is meant to work except on Linux, so the dependency should probably be Linux-only.

### PR DESCRIPTION
**Pull request by nrc**
Closes #5932

###  What have you changed?

It seems that the build is broken because pprof is a Linux-only crate (because it depends on a function in libc which is not portable). In this PR I make pprof a Linux-only dep and cfg away any usage.

###  What is the type of the changes?

Pick one of the following and delete the others:

- Bugfix (a change which fixes an issue)

###  How is the PR tested?

it builds

PTAL @siddontang @BusyJay

### CODE REVIEW

**Comment by siddontang** [comment]
IMO, I hope we can support MacOSX, so we can profile TiKV in local development directly, this is a very useful feature.

**Comment by nrc** [comment]
> I hope we can support MacOSX, so we can profile TiKV in local development directly, this is a very useful feature.

Me too! But I don't want to block building TiKV on somebody implementing it :-)

**Comment by siddontang** [comment]
the problem is caused by `pthread_getname_np`, seem it is absent on MacOSX, do you have any idea that getting thread name on MacOSX? @nrc

**Comment by nrc** [comment]
> do you have any idea that getting thread name on MacOSX?

I don't. I assume it is possible, but no idea how.

**Pull request merged**
