### PR TITLE
engine: default set soft_pending_compaction_bytes_limit to 192GiB

### PR DESCRIPTION
**Pull request by tabokie**
Signed-off-by: tabokie <xy.tao@outlook.com>

### What problem does this PR solve?

Problem Summary:

`soft_pending_compaction_bytes_limit` is too small.

### What is changed and how it works?

What's Changed:

Set `soft_pending_compaction_bytes_limit` to 75% of `hard_pending_compaction_bytes_limit`, which is 192GiB.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:

### Release note 

```release-note
Change default value for soft_pending_compaction_bytes_limit to 192GiB.
```

### CODE REVIEW

**Comment by tabokie** [comment]
The value of choice here is pretty arbitrary. I'd prefer it dynamically configured to `current_pending_bytes + disk_available_size`, maybe later when write throttling is re-implemented.

**Review by Connor1996 — COMMENTED** [review]
Enlarging the limit just postpones the write stall, it may still touch 192G in a while

**Comment by tabokie** [comment]
> Enlarging the limit just postpones the write stall, it may still touch 192G in a while

@Connor1996 I think postponing is enough for cases where heavy write flow is only momentary, i.e. rate limiter can restrain background IOs for longer duration.

**Review by Connor1996 — APPROVED** [review]
LGTM

**Pull request merged**
