### PR TITLE
cop: fix analyze common handle in collect column stats

### PR DESCRIPTION
**Pull request by lzmhhh123**
Signed-off-by: lzmhhh123 <lzmhhh123@gmail.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/23195

Problem Summary:

### What is changed and how it works?

What's Changed:

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

- none

### CODE REVIEW

**Comment by wjhuang2016** [comment]
Need label.

**Comment by Yisaer** [comment]
close https://github.com/tikv/tikv/issues/9774

**Review by tangenta — APPROVED** [review]

**Review by iosmanthus — APPROVED** [review]
LGTM

**Pull request merged**
