### PR TITLE
txn: don't push min_commit_ts if caller_start_ts is max u64

### PR DESCRIPTION
**Pull request by youjiali1995**
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### What problem does this PR solve?

Problem Summary:
TiDB uses max u64 as start ts when doing point get in the autocommit transaction. If it meets locks, it will lead to `min_commit_ts` overflow. See https://github.com/pingcap/tidb/issues/16778.

### What is changed and how it works?

What's Changed:
Don't push `min_commit_ts` if `caller_start_ts` is max u64.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 
Fix the issue that the min commit timestamp of a transaction may overflows which breaks data safety.

### CODE REVIEW

**Comment by cfzjywxk** [comment]
@youjiali1995  maybe we need to add sql cases in `ticases` to do complete verify

**Comment by youjiali1995** [comment]
> @youjiali1995 maybe we need to add sql cases in `ticases` to do complete verify

Yes. We can do it later. I have verified it manually.

**Pull request merged**
