### PR TITLE
raftstore: validate bucket config only when it's enabled

### LINKED ISSUE #12235: Shouldn't report config related errors when bucket is disabled
### What version of TiKV are you using?

v6.0, master

### What operating system and CPU are you using?

Not related

### Steps to reproduce

Use incompatible config values of region size and bucket size.

### What did you expect?

No errors.

### What did happened?

```
Error: init config failed: tikv1-peer:30160: executor.ssh.execute_failed: Failed to execute command over SSH for 'tidb@tikv1-peer:22' {ssh_stderr: invalid configuration: [components/raftstore/src/coprocessor/[config.rs:111](http://config.rs:111/)]: region split size 4194304 must >= region bucket size 100663296
```

### PR DESCRIPTION
**Pull request by youjiali1995**
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### What is changed and how it works?

Issue Number: Close #12235, #12236

What's Changed:

```commit-message
Shouldn't report config related errors when bucket is disabled.
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by youjiali1995** [comment]
@tonyxuqqi PTAL

**Review by sticnarf — APPROVED** [review]
LGTM

**Review by 5kbpers — APPROVED** [review]

**Pull request merged**
