### PR TITLE
external_storage: support virtual-host style for s3 (#9425)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #9425 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/10243
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/10243:release-5.0-ec35729218a5
```

---

### What problem does this PR solve?

Issue Number: close pingcap/br#484

Problem Summary:

TiKV uses the official `rusoto_s3` which did not support "Virtual Host" addressing style (rusoto/rusoto#1482), which is mandated by Aliyun OSS and some other third-party S3 clones.

### What is changed and how it works?

What's Changed:

There is already a PR fixing this (rusoto/rusoto#1823), but since Amazon [postponed](https://aws.amazon.com/blogs/storage/update-to-amazon-s3-path-deprecation-plan/) the path-style doomsday indefinitely, there seems to be no pressure on rusoto maintainers to review it ASAP. 

This PR thus replaced all rusoto dependencies by the version in rusoto/rusoto#1823 to get Virtual Host support. 

### Related changes

- Need to cherry-pick to the release branch (release-5.0, release-4.0)

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
   * TODO: test against S3 with virtual-host style

Side effects

### Release note 

* BR now supports S3-compatible storage using virtual-host addressing style.

### CODE REVIEW

**Review by yiwu-arbug — APPROVED** [review]

**Comment by kennytm** [comment]
PTAL @overvenus

**Review by glorv — APPROVED** [review]

**Comment by dovefi** [comment]
👍

**Pull request merged**
