### PR TITLE
PCP: reduce size of tikv::storage::errors::Error

### PR DESCRIPTION
**Pull request by Renkai**
Signed-off-by: Renkai <gaelookair@gmail.com>

###  What have you changed?

This is an attempt to solve https://github.com/tikv/tikv/issues/5700 .
Since I am new to both Rust and TiKV, it might not be the final solution, I hope I can get some comment from reviewers to continue.

`std::mem::size_of::<tikv::storage::errors::Error>()` is now `24`, quite smaller than 200.

###  What is the type of the changes?
- Engineering (engineering change which doesn't change any feature or fix any issue)

###  How is the PR tested?
- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?
No 

###  Does this PR affect `tidb-ansible`?
No 
###  Refer to a related PR or issue link (optional)
https://github.com/tikv/tikv/issues/5700

### CODE REVIEW

**Comment by breeswish** [comment]
Thanks, this is a quite effective step! If you want to optimize further more, e.g. reduce the size to 8, you may refer to https://github.com/tikv/tikv/pull/5944 (@sticnarf PTAL about the solution in #5944). However we have not come to an agreement of the best way to do this, since your solution is also quite neat and effective.

@sticnarf @youjiali1995 @kennytm Suggestions?

**Comment by kennytm** [comment]
I think these should be a test case or static_assert that `size_of::<Error>()` is within a reasonable size 🙂.

Could we schedule a benchmark?

**Comment by breeswish** [comment]
@kennytm A benchmark is currently running for #5944. According to valgrind it eliminates a memcpy in the forward scanner for each iterate so there should be effects.

**Comment by sticnarf** [comment]
> I think these should be a test case or static_assert that `size_of::<Error>()` is within a reasonable size .
> 
> Could we schedule a benchmark?

Looks like static-asserts doesn't support less than comparisons.
I guess a clippy warning is more suitable for this, if possible.

**Comment by breeswish** [comment]
@sticnarf @kennytm How do you think about the two solutions?

Solution 1. Used in this PR. It adds Box to the enum variant, so that size can be reduced to 24.

Pros: Less code change. Simple match pattern.
Cons: Error size is still larger than bit width, requires multiple `mov` instructions.

Solution 2. Used in #5944. It adds Box to the enum, so that size can be reduced to 8.

Pros: Maybe the most possible minimum error size.
Cons: More complex match patterns (need to write out the Error Inner explicitly).

**Comment by kennytm** [comment]
I prefer this PR (box the variants) if the bench result is just similar to https://github.com/tikv/tikv/pull/5944#issuecomment-555139421.

**Comment by breeswish** [comment]
According to disassembly, I'm afraid `TxnResult` (which use `storage::txn::Error`) also need to be optimized.

```
*****
* thread #1, name = 'coprocessor_exe', stop reason = breakpoint 4.3
  * frame #0: 0x00007ffff711cad3 libc.so.6`__memmove_avx_unaligned_erms at memmove-vec-unaligned-erms.S:219
    frame #1: 0x000055555590497c coprocessor_executors-d024151be3bae1df`_$LT$tikv..storage..mvcc..reader..scanner..Scanner$LT$S$GT$$u20$as$u20$tikv..storage..txn..store..Scanner$GT$::next::h8da5d77d5725b867 [inlined] _$LT$core..result..Result$LT$T$C$E$GT$$u20$as$u20$core..ops..try..Try$GT$::into_result::h08f97c076b92a4cc(self=Result<bool, tikv::storage::kv::Error> {}) at result.rs:1438
    frame #2: 0x0000555555904951 coprocessor_executors-d024151be3bae1df`_$LT$tikv..storage..mvcc..reader..scanner..Scanner$LT$S$GT$$u20$as$u20$tikv..storage..txn..store..Scanner$GT$::next::h8da5d77d5725b867 [inlined] tikv::storage::mvcc::reader::scanner::forward::ForwardScanner$LT$S$GT$::read_next::hb9cc7bbae66bc1ed(self=<unavailable>) at forward.rs:91
    frame #3: 0x0000555555904931 coprocessor_executors-d024151be3bae1df`_$LT$tikv..storage..mvcc..reader..scanner..Scanner$LT$S$GT$$u20$as$u20$tikv..storage..txn..store..Scanner$GT$::next::h8da5d77d5725b867(self=&0x7fffe44ed170) at mod.rs:124
    frame #4: 0x0000555555901ef1 coprocessor_executors-d024151be3bae1df`_$LT$tikv..coprocessor..dag..storage_impl..TiKVStorage$LT$S$GT$$u20$as$u20$tidb_query..storage..Storage$GT$::scan_next::h903ba329380007f3(self=<unavailable>) at storage_impl.rs:58
    frame #5: 0x000055555593df94 coprocessor_executors-d024151be3bae1df`tidb_query::storage::scanner::RangesScanner$LT$T$GT$::next::h156ee3a8333e42b7(self=&0x7fffe44ecfc0) at scanner.rs:90
    frame #6: 0x0000555555966517 coprocessor_executors-d024151be3bae1df`_$LT$tidb_query..batch..executors..table_scan_executor..BatchTableScanExecutor$LT$S$GT$$u20$as$u20$tidb_query..batch..interface..BatchExecutor$GT$::next_batch::h89f131b9702cb073 at scan_executor.rs:102
    frame #7: 0x00005555559664e8 coprocessor_executors-d024151be3bae1df`_$LT$tidb_query..batch..executors..table_scan_executor..BatchTableScanExecutor$LT$S$GT$$u20$as$u20$tidb_query..batch..interface..BatchExecutor$GT$::next_batch::h89f131b9702cb073 at scan_executor.rs:168
    frame #8: 0x00005555559664a6 coprocessor_executors-d024151be3bae1df`_$LT$tidb_query..batch..executors..table_scan_executor..BatchTableScanExecutor$LT$S$GT$$u20$as$u20$tidb_query..batch..interface..BatchExecutor$GT$::next_batch::h89f131b9702cb073(self=&0x7fffe44ecf00, scan_rows=1023) at table_scan_executor.rs:101
    frame #9: 0x0000555555958852 coprocessor_executors-d024151be3bae1df`_$LT$tidb_query..execute_stats..WithSummaryCollector$LT$C$C$T$GT$$u20$as$u20$tidb_query..batch..interface..BatchExecutor$GT$::next_batch::h0c69250fd0a1d0ea(self=<unavailable>, scan_rows=<unavailable>) at interface.rs:99
```

Could you try with the method in #5944 , apply the optimize for all of the following errors?

- storage::mvcc::Error (already done in #5944)
- storage::txn::Error
- storage::kv::Error
- storage::Error

This should bring notable difference, since benchmark for #5944 already inspected some.

**Comment by Renkai** [comment]
@breeswish Yes,I'm glad to do that.Should I optimize each Error per PR or optimize them all in one PR?

**Comment by breeswish** [comment]
@Renkai You can do it once, so that we can invoke a benchmark in your PR directly to see its effect :)

**Comment by breeswish** [comment]
Correspondingly I will raise the score to 200 if your new PR is merged for considerable amount of work (since it is no longer Storage error itself, but also errors in sub modules in Storage)

**Comment by breeswish** [comment]
As a friendly hint, https://github.com/tikv/tikv/pull/5944/files#diff-b6af72e31984f03f182fefddd4face63R296-R309 in #5944 is very important to keep existing `?` operator working after changing the Error to another type using the way in the PR.

**Comment by Renkai** [comment]
@breeswish should https://github.com/tikv/tikv/pull/5944 be merged first so that I can learn and imitate easier?

**Comment by breeswish** [comment]
@Renkai Not very necessary, feel free to simply take my code change and use it in your new PR. In this way we can easily know the total improvement.

**Comment by Renkai** [comment]
new PR at https://github.com/tikv/tikv/pull/5979

**Comment by breeswish** [comment]
Close for #5979

**Pull request closed without merging**
