### PR TITLE
Delay iterator panic to data access

### PR DESCRIPTION
**Pull request by tabokie**
Signed-off-by: tabokie <xy.tao@outlook.com>

### What problem does this PR solve?

Mitigate #9913 

### Check List 

Tests

- Unit test

### Release note
- No release note

### CODE REVIEW

**Comment by tabokie** [comment]
It's an UB to call `Next` on an invalid cursor, but shipping this check to production user might also cause repercussions more than we intended.

**Review by yiwu-arbug — COMMENTED** [review]
what does "nort" stands for?

**Comment by tabokie** [comment]
> what does "nort" stands for?

"no runtime"

**Review by yiwu-arbug — APPROVED** [review]

**Review by Connor1996 — COMMENTED** [review]
Don't think it's a good idea. This just covers up the issue.

**Comment by tabokie** [comment]
This PR is not well thought to capture bugs, just to restore things as they were.
A better solution would be:
1) In `next()`/`prev()`, check `valid()` and return error if not
2) In `key()`/`value()`, assert `valid()`

This way we don't have to panic until data integrity is actually at risk.
@yiwu-arbug @Connor1996

**Comment by Connor1996** [comment]
> This PR is not well thought to capture bugs, just to restore things as they were.
> A better solution would be:
> 
> 1. In `next()`/`prev()`, check `valid()` and return error if not
> 2. In `key()`/`value()`, assert `valid()`
> 
> This way we don't have to panic until data integrity is actually at risk.
> @yiwu-arbug @Connor1996

But calling key() or value() when it is invalid is undefined behavior. It may return the wrong data to the user.

**Comment by tabokie** [comment]
> > This PR is not well thought to capture bugs, just to restore things as they were.
> > A better solution would be:
> > 
> > 1. In `next()`/`prev()`, check `valid()` and return error if not
> > 2. In `key()`/`value()`, assert `valid()`
> > 
> > This way we don't have to panic until data integrity is actually at risk.
> > @yiwu-arbug @Connor1996
> 
> But calling key() or value() when it is invalid is undefined behavior. It may return the wrong data to the user.

That's where we will panic.

**Comment by Connor1996** [comment]
> > > This PR is not well thought to capture bugs, just to restore things as they were.
> > > A better solution would be:
> > > 
> > > 1. In `next()`/`prev()`, check `valid()` and return error if not
> > > 2. In `key()`/`value()`, assert `valid()`
> > > 
> > > This way we don't have to panic until data integrity is actually at risk.
> > > @yiwu-arbug @Connor1996
> > 
> > 
> > But calling key() or value() when it is invalid is undefined behavior. It may return the wrong data to the user.
> 
> That's where we will panic.

But it wouldn't panic in release build.

**Comment by tabokie** [comment]
> > > > This PR is not well thought to capture bugs, just to restore things as they were.
> > > > A better solution would be:
> > > > 
> > > > 1. In `next()`/`prev()`, check `valid()` and return error if not
> > > > 2. In `key()`/`value()`, assert `valid()`
> > > > 
> > > > This way we don't have to panic until data integrity is actually at risk.
> > > > @yiwu-arbug @Connor1996
> > > 
> > > 
> > > But calling key() or value() when it is invalid is undefined behavior. It may return the wrong data to the user.
> > 
> > 
> > That's where we will panic.
> 
> But it wouldn't panic in release build.

Need to re-enable nortcheck if we can all agree on this solution.

**Review by Connor1996 — APPROVED** [review]

**Review by yiwu-arbug — COMMENTED** [review]
I think a rustful approach would be to have `next` (and `prev` and others) to return a result type, and caller can unwrap key and value from that type. But that will be a larger refactor. For now I'm okay just getting around the error somehow.
```
trait IterResult {
    fn key(&self) -> &[u8],
    fn value(&self) -> &[u8],
}
fn next(&mut self) -> Result<IterResult> {...}
```

**Comment by yiwu-arbug** [comment]
> I think a rustful approach would be to have `next` (and `prev` and others) to return a result type, and caller can unwrap key and value from that type. But that will be a larger refactor. For now I'm okay just getting around the error somehow.
> 
> ```
> trait IterResult {
>     fn key(&self) -> &[u8],
>     fn value(&self) -> &[u8],
> }
> fn next(&mut self) -> Result<IterResult> {...}
> ```

After a second thought I think this won't work, because it fail to invalidate the `IterResult` after the subseqent `iter.next()` is called. I think a simpler approach would be to have `key()` and `value()` return `Result<&[u8]>`.

**Pull request merged**
