### PR TITLE
[release-3.0] engine: Update rust-rocksdb to improve Titan GC efficiency

### PR DESCRIPTION
**Pull request by Connor1996**
## What have you changed? (mandatory)
Cherry-pick of https://github.com/tikv/tikv/pull/5196

## What are the type of the changes? (mandatory)
- Improvement (change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)
No

## Does this PR affect documentation (docs) or release note? (mandatory)
No

### CODE REVIEW

**Comment by breeswish** [comment]
Do we need to add `cfg.rocksdb.titan.disable_gc = true;`? @Connor1996

**Comment by Connor1996** [comment]
@breeswish release-3.0 doesn't cherry-pick the test

**Pull request merged**
