### PR TITLE
[DNM] merge append response

### PR DESCRIPTION
**Pull request by Fullstop000**
Signed-off-by: Fullstop000 <fullstop1005@gmail.com>

###  What have you changed?

Try to use merging appending response

###  What is the type of the changes?

- Improvement (a change which is an improvement to an existing feature)

### CODE REVIEW

**Comment by Fullstop000** [comment]
@sre-bot /bench

**Comment by you06** [comment]
@Fullstop000 try again please.

**Comment by Fullstop000** [comment]
@sre-bot /run-all-tests

**Comment by Fullstop000** [comment]
@sre-bot /test

**Comment by Fullstop000** [comment]
@sre-bot /bench

**Comment by Fullstop000** [comment]
@sre-bot /bench

**Comment by Fullstop000** [comment]
@zhouqiang-cl Is there any issue on the bench so that I can do some adjustments?

**Comment by Fullstop000** [comment]
Close as no improvements are oberseved.

**Pull request closed without merging**
