### PR TITLE
picks #6487 and #6539 to 3.0.5

### PR DESCRIPTION
**Pull request by BusyJay**
###  What have you changed?

Picks #6487 and #6539 to 3.0.5

###  What is the type of the changes?
- Bugfix

###  How is the PR tested?
- Integration test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?
Yes.

###  Does this PR affect `tidb-ansible`?
No.

### CODE REVIEW

**Comment by 5kbpers** [comment]
Seems the integration tests are broken and a unit test is failed.
`test storage::kv::btree_engine::tests::test_get_not_exist_cf ... thread 'main' panicked at 'CF not exist!', src/libcore/option.rs:1034:5`

**Comment by AndreMouche** [comment]
The CI failed

**Comment by BusyJay** [comment]
/run-integration-common-test /tidb-test=release-3.0.5-hot-fix

**Comment by AndreMouche** [comment]
The related PR:https://github.com/tikv/tikv/issues/6629

**Pull request merged**
