### PR TITLE
*: some tweaks on CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Sunt-ing**
Issue Number: close https://github.com/tikv/tikv/issues/12397

What's Changed:
```
some tweaks on CONTRIBUTING.md
```

### Check List

Tests
- No code

### Release note 

```release-note
NONE
```

### CODE REVIEW

**Review by ngaut — APPROVED** [review]

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by Connor1996** [comment]
Please sign-off the commit

**Review by TennyZhuang — APPROVED** [review]

**Comment by skyzh** [comment]
The CI fail rate is rather high recently 🤣 I remembered last time a PR re-runs about a week before it gets merged.

**Pull request merged**
