### PR TITLE
resolved_ts: fix high tail latency cause by time-consuming operation in raftstore  (#10354)

### LINKED ISSUE #10342: raftstore: with large number of region the CheckLeader rpc may increase the tail latency of propose wait/append log
## Bug Report

The `CheckLeader` rpc also sync the `(apply index, safe ts)` from leader to follower, it is done by `RegionReadProgress:: update_safe_ts` which invoke lock acquiring, although the lock is usually not contended, but when the number of regions is large, it may acquiring lot of lock and being time-consuming. As result, the tail latency of propose wait and append log duration may increase:

image

image

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #10354 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/10427
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/10427:release-5.1-6aafdae55f2b
```

---

### What problem does this PR solve?

Issue Number: close #10342 

Problem Summary:

Currently, the `CheckLeader` rpc is handled in `raftstore`, when the number of regions info in the `CheckLeader` request is large, handling the request could be time-consuming, and may increase the tail latency of `Append log duration`/`Propose wait duration`.

### What is changed and how it works?

What's Changed:

This PR fix the issue by:
- move the handling of `CheckLeader` request to the `resolved-ts` worker
- instead of `StoreMeta`, using another fine-grained mutex for `region_read_progress`

### Related changes

- Need to cherry-pick to the release branch

### Check List 

- Existing integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by Yisaer — APPROVED** [review]

**Review by BusyJay — APPROVED** [review]

**Comment by zhouqiang-cl** [comment]
@ti-chi-bot

**Pull request merged**
