### PR TITLE
sst_importer: remove the SST file where no kvs written into

### LINKED ISSUE #16005: sst_importer needs to clean the sst if no kv need to be saved and rewritten
### What version of TiKV are you using?

master, v7.5, v7.1, v6.5
### Steps to reproduce

1. run snapshot restore on a regions having been splitted cluster
### What did happened?
There are many empty sst files(size is 0 by `ls -l`) in the `import/` directory. Besides, there are many warning logs `download file skipped` in the BR log.
Need to remove the sst file here:
https://github.com/tikv/tikv/blob/a0dbe2d0b893489015fc99ae73c6646f7989fe32/components/sst_importer/src/sst_importer.rs#L1379-L1382

### PR DESCRIPTION
**Pull request by Leavrth**
### What is changed and how it works?

Issue Number: Close #16005 

What's Changed:

```commit-message
This PR has remove the empty SST file in the db/import.

* remove the sst file where no kvs written into
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by Connor1996 — COMMENTED** [review]
Please also clean up the already existed empty sst files

**Comment by Leavrth** [comment]
> Please also clean up the already existed empty sst files

It seems only release-6.5 would open the sst when clean ssts. I will modify in the cherry-pick PR.

**Comment by BornChanger** [comment]
@Connor1996 please take another look

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by 3pointer — APPROVED** [review]

**Pull request merged**
