### PR TITLE
config: simplify handling of nullable configurations

### PR DESCRIPTION
**Pull request by tabokie**
Signed-off-by: tabokie <xy.tao@outlook.com>

### What is changed and how it works?

Issue Number: Ref #11119

What's Changed:

Support deriving `OnlineConfig` on any `Option<T>`. One caveat is such `T` must implement `Default`.

This change is made for #12127.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests
- Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by NingLin-P** [comment]
Plz add uint test to https://github.com/tikv/tikv/blob/master/components/online_config/src/lib.rs

**Comment by NingLin-P** [comment]
ltgm

**Comment by tabokie** [comment]
@NingLin-P Test added.

**Review by NingLin-P — APPROVED** [review]

**Review by glorv — APPROVED** [review]

**Pull request merged**
