### PR TITLE
*: bump master branch version to v6.0.0-alpha

### LINKED ISSUE #12075: Bump TiKV master version to 6.0
## Development Task

TiKV 5.4 has been released. The next TiKV version is scheduled to be 6.0.0. It's time to bump the master version to 6.0.0-alpha.

### PR DESCRIPTION
**Pull request by sticnarf**
### What is changed and how it works?

Issue Number: Close #12075 

Features that should be only enabled in the next release may depend on this change.

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by BusyJay — APPROVED** [review]

**Review by zhouqiang-cl — APPROVED** [review]
LGTM

**Comment by overvenus** [comment]
This PR breaks integration tests with tiflash nodes.

Logs from tiflash proxy.

```
[2022/03/03 13:57:55.816 +00:00] [INFO] [lib.rs:37] ["Welcome To RaftStore Proxy"]
[2022/03/03 13:57:55.818 +00:00] [INFO] [lib.rs:39] ["Git Commit Hash:   1e3f15fdb93a7ae41958d81c168d9e25ef3d4570"]
[2022/03/03 13:57:55.818 +00:00] [INFO] [lib.rs:39] ["Git Commit Branch: HEAD"]
[2022/03/03 13:57:55.818 +00:00] [INFO] [lib.rs:39] ["UTC Build Time:    2022-02-24 15:49:18"]
[2022/03/03 13:57:55.818 +00:00] [INFO] [lib.rs:39] ["Rust Version:      rustc 1.53.0-nightly (16bf626a3 2021-04-14)"]
[2022/03/03 13:57:55.818 +00:00] [INFO] [lib.rs:39] ["Storage Engine:    tiflash"]
[2022/03/03 13:57:55.818 +00:00] [INFO] [lib.rs:39] ["Prometheus Prefix: tiflash_proxy_"]
[2022/03/03 13:57:55.818 +00:00] [INFO] [lib.rs:39] ["Profile:           release"]
...
[2022/03/03 13:58:00.466 +00:00] [INFO] [util.rs:354] ["trying to update PD client done"] [spend=2.539358ms]
[2022/03/03 13:58:00.467 +00:00] [ERROR] [util.rs:457] ["request failed"] [err_code=KV:PD:gRPC] [err="Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"version should compatible with version  6.0.0-alpha, got 5.5.0-alpha-161-g6ed8574\", details: [] }))"]
[2022/03/03 13:58:00.467 +00:00] [ERROR] [util.rs:466] ["reconnect failed"] [err_code=KV:PD:Unknown] [err="Other(\"[components/pd_client/src/util.rs:301]: cancel reconnection due to too small interval\")"]
[2022/03/03 13:58:01.469 +00:00] [ERROR] [util.rs:457] ["request failed"] [err_code=KV:PD:gRPC] [err="Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"version should compatible with version  6.0.0-alpha, got 5.5.0-alpha-161-g6ed8574\", details: [] }))"]
[2022/03/03 13:58:01.469 +00:00] [FATAL] [server.rs:812] ["failed to start node: Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"version should compatible with version  6.0.0-alpha, got 5.5.0-alpha-161-g6ed8574\", details: [] }))"]
```

**Comment by sticnarf** [comment]
> This PR breaks integration tests with tiflash nodes.
> 
> Logs from tiflash proxy.
> 
> ```
> [2022/03/03 13:57:55.816 +00:00] [INFO] [lib.rs:37] ["Welcome To RaftStore Proxy"]
> [2022/03/03 13:57:55.818 +00:00] [INFO] [lib.rs:39] ["Git Commit Hash:   1e3f15fdb93a7ae41958d81c168d9e25ef3d4570"]
> [2022/03/03 13:57:55.818 +00:00] [INFO] [lib.rs:39] ["Git Commit Branch: HEAD"]
> [2022/03/03 13:57:55.818 +00:00] [INFO] [lib.rs:39] ["UTC Build Time:    2022-02-24 15:49:18"]
> [2022/03/03 13:57:55.818 +00:00] [INFO] [lib.rs:39] ["Rust Version:      rustc 1.53.0-nightly (16bf626a3 2021-04-14)"]
> [2022/03/03 13:57:55.818 +00:00] [INFO] [lib.rs:39] ["Storage Engine:    tiflash"]
> [2022/03/03 13:57:55.818 +00:00] [INFO] [lib.rs:39] ["Prometheus Prefix: tiflash_proxy_"]
> [2022/03/03 13:57:55.818 +00:00] [INFO] [lib.rs:39] ["Profile:           release"]
> ...
> [2022/03/03 13:58:00.466 +00:00] [INFO] [util.rs:354] ["trying to update PD client done"] [spend=2.539358ms]
> [2022/03/03 13:58:00.467 +00:00] [ERROR] [util.rs:457] ["request failed"] [err_code=KV:PD:gRPC] [err="Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"version should compatible with version  6.0.0-alpha, got 5.5.0-alpha-161-g6ed8574\", details: [] }))"]
> [2022/03/03 13:58:00.467 +00:00] [ERROR] [util.rs:466] ["reconnect failed"] [err_code=KV:PD:Unknown] [err="Other(\"[components/pd_client/src/util.rs:301]: cancel reconnection due to too small interval\")"]
> [2022/03/03 13:58:01.469 +00:00] [ERROR] [util.rs:457] ["request failed"] [err_code=KV:PD:gRPC] [err="Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"version should compatible with version  6.0.0-alpha, got 5.5.0-alpha-161-g6ed8574\", details: [] }))"]
> [2022/03/03 13:58:01.469 +00:00] [FATAL] [server.rs:812] ["failed to start node: Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"version should compatible with version  6.0.0-alpha, got 5.5.0-alpha-161-g6ed8574\", details: [] }))"]
> ```

Does it solve the problem if the TiFlash proxy bumps its version?

**Comment by overvenus** [comment]
> > This PR breaks integration tests with tiflash nodes.
> > Logs from tiflash proxy.
> > ```
> > [2022/03/03 13:57:55.816 +00:00] [INFO] [lib.rs:37] ["Welcome To RaftStore Proxy"]
> > [2022/03/03 13:57:55.818 +00:00] [INFO] [lib.rs:39] ["Git Commit Hash:   1e3f15fdb93a7ae41958d81c168d9e25ef3d4570"]
> > [2022/03/03 13:57:55.818 +00:00] [INFO] [lib.rs:39] ["Git Commit Branch: HEAD"]
> > [2022/03/03 13:57:55.818 +00:00] [INFO] [lib.rs:39] ["UTC Build Time:    2022-02-24 15:49:18"]
> > [2022/03/03 13:57:55.818 +00:00] [INFO] [lib.rs:39] ["Rust Version:      rustc 1.53.0-nightly (16bf626a3 2021-04-14)"]
> > [2022/03/03 13:57:55.818 +00:00] [INFO] [lib.rs:39] ["Storage Engine:    tiflash"]
> > [2022/03/03 13:57:55.818 +00:00] [INFO] [lib.rs:39] ["Prometheus Prefix: tiflash_proxy_"]
> > [2022/03/03 13:57:55.818 +00:00] [INFO] [lib.rs:39] ["Profile:           release"]
> > ...
> > [2022/03/03 13:58:00.466 +00:00] [INFO] [util.rs:354] ["trying to update PD client done"] [spend=2.539358ms]
> > [2022/03/03 13:58:00.467 +00:00] [ERROR] [util.rs:457] ["request failed"] [err_code=KV:PD:gRPC] [err="Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"version should compatible with version  6.0.0-alpha, got 5.5.0-alpha-161-g6ed8574\", details: [] }))"]
> > [2022/03/03 13:58:00.467 +00:00] [ERROR] [util.rs:466] ["reconnect failed"] [err_code=KV:PD:Unknown] [err="Other(\"[components/pd_client/src/util.rs:301]: cancel reconnection due to too small interval\")"]
> > [2022/03/03 13:58:01.469 +00:00] [ERROR] [util.rs:457] ["request failed"] [err_code=KV:PD:gRPC] [err="Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"version should compatible with version  6.0.0-alpha, got 5.5.0-alpha-161-g6ed8574\", details: [] }))"]
> > [2022/03/03 13:58:01.469 +00:00] [FATAL] [server.rs:812] ["failed to start node: Grpc(RpcFailure(RpcStatus { code: 2-UNKNOWN, message: \"version should compatible with version  6.0.0-alpha, got 5.5.0-alpha-161-g6ed8574\", details: [] }))"]
> > ```
> 
> Does it solve the problem if the TiFlash proxy bumps its version?

Yes, it should solve the problem.

**Pull request merged**
