### PR TITLE
Revert "copr: add ISO 8601 support for time parsing"

### PR DESCRIPTION
**Pull request by ichn-hu**
Reverts tikv/tikv#9356

### Release note 

- No release note

### CODE REVIEW

**Comment by leiysky** [comment]
"/label status/can-merge"

**Comment by andylokandy** [comment]
> "/label status/can-merge"

Abused

**Comment by hi-rustin** [comment]
@sre-bot You're so stupid. 😆

**Review by skyzh — APPROVED** [review]

**Pull request merged**
