### PR TITLE
*: support handle search invalid logs file (#8224)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #8224 to release-4.0

---

Signed-off-by: baurine <2008.hbl@gmail.com>

### What problem does this PR solve?

Relate issues or PRs:

- https://github.com/pingcap/tiup/issues/570
- https://github.com/pingcap-incubator/tidb-dashboard/issues/665
- https://github.com/pingcap/sysutil/pull/19

Problem Summary:

Currently, if the log file contains some invalid lines in the beginning or end, the whole file is skipped to search. If the log file contains some invalid lines in the middle, the lines are just simply ignored.

### What is changed and how it works?

What's Changed: 

1. When parsing the beginning and end of the log file to check whether it is a valid file, not just read one line, but to read at most 10 lines
1. When parsing middle lines, treat the invalid line as a LogMessage with pre valid log time and level but its own whole line content

Keep the same changes as PR https://github.com/pingcap/sysutil/pull/19

### Related changes

No

### Check List 

Tests 

- Unit test

### Release note 

- Support to search log files that contain invalid lines in the beginning, end, or middle.

### CODE REVIEW

**Comment by baurine** [comment]
It seems the file structure has changed compared with the master branch.

In the master branch, `src/server/service/diagnostics` is a folder while here it is a rust file.

**Comment by breeswish** [comment]
@baurine Yes, maybe you need to manually perform a cherry pick.

**Comment by baurine** [comment]
> @baurine Yes, maybe you need to manually perform a cherry pick.

ok, I will do it.

**Comment by baurine** [comment]
The `diagnostics.rs` was split into a `diagnostics` folder and 4 small rust files (ioload.rs / log.rs / mod.rs / sys.rs) in PR #7682 3 month ago, then the PR self and its subsequent related modifications were not cherry-pick back to release-4.0 successfully, including PR #8182 , #7889, #8171 . I am a little don't know how should I do.

**Comment by baurine** [comment]
To make this cherry-pick can pass the CI, cherry-pick or manually modify the code from some other PRs:

- *: reduce dependence on our sysinfo (#7634)
- * server: move diagnostics to its own directory in service (#7682)
- diagnostics: Fix panic when a NIC doesn't have a mac address (#7889)
- *: upgrade toolchain to 2020-07-01 (#8171)
- test: fix tikv::server::service::diagnostics::test_load_info on Linux (#8182)

For PR #8182, it has created a cherry-pick in

**Comment by baurine** [comment]
@breeswish PTAL, thanks!

**Comment by hi-rustin** [comment]
This cherry pick PR is for a release branch and has not yet been approved by release team.
Adding the do-not-merge/cherry-pick-not-approved label.

To merge this cherry pick, it must first be approved (/lgtm + /merge) by the collaborators.

AFTER it has been approved by collaborators, please ping the release team in a comment to request a cherry pick review

**Pull request closed without merging**
