### PR TITLE
copr: use EvalType::Bytes as the eval type for Null type.

### PR DESCRIPTION
**Pull request by wshwsh12**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/22629 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed: refer https://github.com/pingcap/parser/blob/master/types/field_type.go#L95, all not specifically required EvalType type, the evalType should be EvalType::Bytes.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
test the issue.

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 
- No release note.

### CODE REVIEW

**Review by Xuanwo — APPROVED** [review]

**Comment by Xuanwo** [comment]
cc @andylokandy @skyzh

**Review by skyzh — APPROVED** [review]
LGTM. Have you manually tested the case for `select count(null)` in TiDB with this PR?

**Comment by skyzh** [comment]
Manual test result

image

**Pull request merged**
