### PR TITLE
copr: fix cast expr when cast empty string to float (#9704)

### LINKED ISSUE #9704: Inconsisitent with Mysql When a varchar column only have empty string
### What version of TiKV are you using?
master

### Steps to reproduce
drop table t;
create table t (a varchar(30));
insert into t values ('');
delete from t where a=10;

### What did you expect?
Query OK, 0 rows affected (0.01 sec) 

### What did happened?
ERROR 1265 (01000): Data Truncated

PS: It's cast expression'bug. It was fixed on TiDB [here](https://github.com/pingcap/tidb/issues/10806), but we still need to fix it in coprocessor.

### PR DESCRIPTION
**Pull request by guo-shaoge**
Signed-off-by: guo-shaoge <shaoge1994@163.com>

### What problem does this PR solve?

Issue Number: close #9704 

Problem Summary: 

    drop table t;
    create table t (a varchar(30));
    insert into t values ('');
    delete from t where a=10;

Delete statement should be ok. In MySQL, the result of empty stringcasting to float is zero. But in TiDB, it gives "Data Truncated" errors. Because cast expr got bug when cast empty string to float.

That was fixed in TiDB [here](https://github.com/pingcap/tidb/issues/10806), but we still need to fix it in copr. 

### What is changed and how it works?

What's Changed:  Change function cast_string_as_signed_real(). When input string is empty, result will be 0.0

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects: no side effects.

### Release note 

- fix cast expr when cast empty string to float in copr.

### CODE REVIEW

**Review by skyzh — APPROVED** [review]
LGTM. What about `cast_string_as_unsigned_real`?

**Review by Xuanwo — APPROVED** [review]

**Pull request merged**
