### PR TITLE
raftstore: enlarge ingest buffer

### PR DESCRIPTION
**Pull request by Connor1996**
## What have you changed? (mandatory)
Enlarge ingest buffer to tolerate heavy write workload, which may flush some memtables in a short time.

## What are the type of the changes? (mandatory)
- Improvement (change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)
No

## Does this PR affect documentation (docs) update? (mandatory)
No

## Does this PR affect tidb-ansible update? (mandatory)
No

### CODE REVIEW

**Comment by siddontang** [comment]
can you show some grafana metrics to prove this optimization is fine?

**Comment by Connor1996** [comment]
Nope, it just makes consistent with https://github.com/tikv/tikv/pull/4116

**Comment by siddontang** [comment]
so why do you think this optimization can work well :sob:?

**Comment by Connor1996** [comment]
Not an optimization, it just like a parameter that how we balance the demand between apply snapshot with write. For enlarging ingest buffer, we want to let apply snapshot give more way to write.

**Comment by zhangjinpeng1987** [comment]
@Connor1996 Should cherry-pick to 2.1.

**Pull request merged**
