### PR TITLE
storage/mvcc/txn: polish prewrite

### PR DESCRIPTION
**Pull request by Hijiao**
Signed-off-by: Max <xiahaijiao@hotmail.com>

## What have you changed? (mandatory)
make `prewrite` more straightforward and effective.

the original code:

conditions | comparison times | key clone times
---|---| ---
value is none | 2 | 1 
value is some && is short | 2 | 0 
value is some && is long | 3 | 1 

new code:

conditions | comparison times | key clone time s
---|---| --- 
value is none | 1 | 0 
value is some && is short | 2 | 0 
value is some && is long | 2 | 1 

 

## What are the type of the changes? (mandatory)

- Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)
unit test

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No

### CODE REVIEW

**Comment by Hijiao** [comment]
@zhangjinpeng1987  @Connor1996  PTAL

**Comment by Connor1996** [comment]
This is a little verbose.
How about writing like this
```
if value.is_some() && !is_short_value(value.as_ref().unwrap() {
   let ts = self.start_ts;
   self.put_value(key.clone(), ts, value.clone().unwrap());
} 
 self.lock_key(key, lock_type, primary.to_vec(), options.lock_ttl, value);
```
it is also effective and even more concise.

**Comment by Hijiao** [comment]
@overvenus PTAL, thanks

**Pull request merged**
