### PR TITLE
log-backup: store log files by date and keep advanced checkpoint-ts as safe point with ttl 12 hours

### LINKED ISSUE #12903: service_gc_safepoint not set and data lost after br log backup in ERROR state
### What version of TiKV are you using?
│/ # /tikv-server -V
│TiKV
│Release Version: 6.1.0-alpha
│Edition: Community
│Git Commit Hash: https://github.com/tikv/tikv/commit/900dd036829662f4e88d31fc66fc3aada09a9924
│Git Commit Branch: 6.1.0-pitr-dev
│UTC Build Time: 2022-06-13 03:03:45

### What operating system and CPU are you using?
K8S

### Steps to reproduce

1. BR log backup enters error status due to: https://github.com/tikv/tikv/issues/12902

### What did you expect?
When log backup in ERROR status, service_gc_safepoint  should be configured to make sure data not lost.

### What did happened?
service_gc_safepoint  not configured correctly, which result in data loss.
8cvWbRzGdE

Kb3VeOJVxy
V5IMG3sWDg

### PR DESCRIPTION
**Pull request by WangLe1321**
### What is changed and how it works?

Issue Number: Close #12903

this PR is cherry-picked by https://github.com/joccau/tikv/pull/13

What's Changed:

- store log files by date.
- keep advanced checkpoint-ts as safe point with ttl 12 hours.

```commit-message
1. store log files by date.
2. keep advanced checkpoint-ts as safe point with ttl 12 hours.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
Please add a release note.

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with None.
If this PR will be picked to release branch, then a release note is probably required.
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]

**Comment by WangLe1321** [comment]
this PR is cherry-picked by https://github.com/joccau/tikv/pull/13

**Comment by overvenus** [comment]
Please add a test to cover the change.

**Comment by WangLe1321** [comment]
> 

we have done manual test in this original PR https://github.com/tikv/tikv/pull/12912

**Pull request merged**
