### PR TITLE
Remove sync-log config option

### PR DESCRIPTION
**Pull request by hunterlxt**
Signed-off-by: Xintao <hunterlxt@live.com>

### What problem does this PR solve?

If `sync-log` is set to `false`, there is chance that data will be loss.

### What is changed and how it works?

Make this option true always.

### Related changes

- Need to cherry-pick to the release branch

### Release note 
- Set sync-log true always.

### CODE REVIEW

**Review by gengliqi — APPROVED** [review]
LGTM

**Review by NingLin-P — APPROVED** [review]

**Comment by lishuai87** [comment]
see:  https://www.infoq.cn/article/mFTtecC4y3Qc1egNNFym

you can set `sync-log = true` as the default value,  but please let user choose whether to change it.

**Comment by hunterlxt** [comment]
> see: https://www.infoq.cn/article/mFTtecC4y3Qc1egNNFym
> 
> you can set `sync-log = true` as the default value, but please let user choose whether to change it.

/cc @innerr

**Comment by lishuai87** [comment]
> see: https://www.infoq.cn/article/mFTtecC4y3Qc1egNNFym
> 
> you can set `sync-log = true` as the default value, but please let user choose whether to change it.

https://mp.weixin.qq.com/s/aLvkhBQ3jcBDr3r7SFHqrw

**Comment by lishuai87** [comment]
mysql also support sync options:
`sync_binlog`:  https://dev.mysql.com/doc/refman/5.7/en/replication-options-binary-log.html#sysvar_sync_binlog
`innodb_flush_log_at_trx_commit`:  https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_flush_log_at_trx_commit

**Comment by gengliqi** [comment]
@lishuai87  As I know, there are several reasons.
1. Although it can be ensured that raftstore metadata is consistent during split, merge, and some other operations if `sync-log` is false, some normal logs may be lost if failure happens which may lead to panic, e.g. committed log can not be overwritten in raft-rs. The repair process is troubling and may last a long time.
2. If some logs are lost, some guarantees of the TiDB transaction model may be violated.
3. We have a plan to reduce the fsync frequency and guarantee safety and we believe it will improve the performance of TiDB on the slow disk.

BTW, TiDB is hard to guarantee the same thing as MySQL `innodb_flush_log_at_trx_commit ` does because TiDB is a distributed database, not a standalone one.

**Comment by youjiali1995** [comment]
@hunterlxt Please update documents.

**Pull request merged**
