### PR TITLE
coprocessor/dag/expr: add some un-pushed builtin UDFs(LeftShift, RightShift)

### PR DESCRIPTION
**Pull request by spongedu**
## What have you changed? (mandatory)

implement builtin function: `LeftShift`, `RightShift` in `coprocessor`.
This is for #3275

## What are the type of the changes? (mandatory)

Improvement

## How has this PR been tested? (mandatory)

unittest

## Refer to a related PR or issue link (optional)

#3275

### CODE REVIEW

**Comment by AndreMouche** [comment]
@breeswish PTAL

**Comment by siddontang** [comment]
@AndreMouche please approve it

**Comment by siddontang** [comment]
please approve it @AndreMouche

**Comment by hicqu** [comment]
LGTM.

**Pull request merged**
