### PR TITLE
resource_control: condition compile failpoint test

### PR DESCRIPTION
**Pull request by Connor1996**
### What is changed and how it works?

Issue Number: Close https://github.com/tikv/tikv/issues/14943

What's Changed:

```commit-message
condition compile failpoint test
```

### Check List 

Tests 

- No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by glorv** [comment]
LGTM. I see many other cases also depend on failpoint but misses the feature gate, could you also add for them too?

**Comment by Connor1996** [comment]
> LGTM. I see many other cases also depend on failpoint but misses the feature gate, could you also add for them too?

Like which? Other tests in failpoint dir are controlled by custom test runner which enable the failpoint automatically

**Comment by glorv** [comment]
> > LGTM. I see many other cases also depend on failpoint but misses the feature gate, could you also add for them too?
> 
> Like which? Other tests in failpoint dir are controlled by custom test runner which enable the failpoint automatically

I searched with `fail::cfg` and found there are somes cases under ther component `backup-stream`, maybe you can also fix them too

**Comment by glorv** [comment]
> > LGTM. I see many other cases also depend on failpoint but misses the feature gate, could you also add for them too?
> 
> Like which? Other tests in failpoint dir are controlled by custom test runner which enable the failpoint automatically

Ok, I found other cases are not marked with this feature gate are actually handled in cargo.toml. Never mind.

**Review by glorv — APPROVED** [review]

**Review by tabokie — APPROVED** [review]

**Pull request merged**
