### PR TITLE
engine: fix backward compatibility issue of raft-engine.recovery-mode

### LINKED ISSUE #11489: nightly upgrade panic due to unrecognized configuration for raft-engine.recovery-mode
### What version of TiKV are you using?
Any

### What operating system and CPU are you using?
Any

### Steps to reproduce

Upgrade to nightly after #10937 

### What did you expect?

Success

### What did happened?

Panics:
```
thread 'main' panicked at 'invalid auto generated configuration file /mnt/nvmessd1/centos/three-tikv-cdc/data/tikv-20160/last_tikv.toml, err unknown variant `tolerate-corrupted-tail-records`, expected one of `absolute-consistency`, `tolerate-tail-corruption`, `tolerate-any-corruption` for key `raft-engine` at line 660 column 1', src/config.rs:2885:13
```

### PR DESCRIPTION
**Pull request by tabokie**
### What problem does this PR solve?

Issue Number: close #11489 

### What is changed and how it works?

What's Changed:

Update raft engine to include https://github.com/tikv/raft-engine/pull/159, also add a test case.

### Check List 

Tests
- Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by tabokie** [comment]
I'm not sure about downloading file in a unit test, maybe there's a better way or I can just remove it.

**Review by hicqu — APPROVED** [review]

**Review by Connor1996 — APPROVED** [review]
LGTM

**Pull request merged**
