### PR TITLE
quota-limiter: fix panic when set limiter value to 0

### LINKED ISSUE #12622: all tikv panic when update config online
### What version of TiKV are you using?
./tikv-server -V
 TiKV 
Release Version:   6.1.0-alpha
Edition:           Community
Git Commit Hash:   1fb8980ccab9ff40c1adc206df52952dab8e8ad8
Git Commit Branch: heads/refs/tags/v6.1.0
UTC Build Time:    2022-05-20 06:30:12
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
2022-05-23T21:11:43.888+0800	INFO	k8s/client.go:107	it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129
./pd-server -V
 Release Version: v6.1.0
Edition: Community
Git Commit Hash: 3f224aec835fb23fa04383b438332ef203b13c66
Git Branch: heads/refs/tags/v6.1.0
UTC Build Time:  2022-05-23 10:06:31
2022-05-23T21:11:44.075+0800	INFO	k8s/client.go:107	it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129
./tidb-server -V
 Release Version: v6.1.0
Edition: Community
Git Commit Hash: f87623664f5417497cc828e03079762bee8b0b5b
Git Branch: heads/refs/tags/v6.1.0
UTC Build Time: 2022-05-23 10:12:19
GoVersion: go1.18.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

### What operating system and CPU are you using?

8core 16GB

### Steps to reproduce
update config online 
oltp_config_update_online_fun.go

### What did you expect?
1、update success if config is valid 
2、report an error if config is invalid ，but can not panic

### What did happened?
all tikv panic when update invalid config online 
[2022/05/23 13:46:28.207 +00:00] [FATAL] [[lib.rs:491](http://lib.rs:491/)] ["can not convert float seconds to Duration: value is either too big or NaN"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/lib.rs:490:18\n](http://github.com/pingcap/tikv/components/tikv_util/src/lib.rs:490:18/n)   1: std::panicking::rust_panic_with_hook\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:702](http://panicking.rs:702/):17\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:588](http://panicking.rs:588/):13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/[backtrace.rs:138](http://backtrace.rs:138/):18\n   4: rust_begin_unwind\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:584](http://panicking.rs:584/):5\n   5: core::panicking::panic_fmt\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/[panicking.rs:143](http://panicking.rs:143/):14\n   6: core::panicking::panic_display\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/[panicking.rs:73](http://panicking.rs:73/):5\n   7: core::time::Duration::from_secs_f64\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/[time.rs:744](http://time.rs:744/):23\n      async_speed_limit::limiter::Bucket<I>::consume\n             at rust/registry/src/[github.com](http://github.com/)-1ecc6299db9ec823/async-speed-limit-0.4.0/src/[limiter.rs:55](http://limiter.rs:55/):13\n      async_speed_limit::limiter::Limiter<C>::consume_duration\n             at rust/registry/src/[github.com](http://github.com/)-1ecc6299db9ec823/async-speed-limit-0.4.0/src/[limiter.rs:319](http://limiter.rs:319/):9\n   8: tikv_util::quota_limiter::QuotaLimiter::async_consume::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/quota_limiter.rs:177:13\n](http://github.com/pingcap/tikv/components/tikv_util/src/quota_limiter.rs:177:13/n)      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/[mod.rs:84](http://mod.rs:84/):19\n   9: tikv::storage::txn::scheduler::Scheduler<E,L>::process_write::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/src/storage/txn/scheduler.rs:799:62\n](http://github.com/pingcap/tikv/src/storage/txn/scheduler.rs:799:62/n)  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/[mod.rs:84](http://mod.rs:84/):19\n      tikv::storage::txn::scheduler::Scheduler<E,L>::process::{{closure}}::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/src/storage/txn/scheduler.rs:725:68\n](http://github.com/pingcap/tikv/src/storage/txn/scheduler.rs:725:68/n)      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/[mod.rs:84](http://mod.rs:84/):19\n      <resource_metering::InTags<T> as core::future::future::Future>::poll\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/resource_metering/src/lib.rs:267:9\n](http://github.com/pingcap/tikv/components/resource_metering/src/lib.rs:267:9/n)      tikv::storage::txn::scheduler::Scheduler<E,L>::process::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/src/storage/txn/scheduler.rs:739:48\n](http://github.com/pingcap/tikv/src/storage/txn/scheduler.rs:739:48/n)      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/[mod.rs:84](http://mod.rs:84/):19\n      tikv::storage::txn::scheduler::Scheduler<E,L>::execute::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/src/storage/txn/scheduler.rs:543:54\n](http://github.com/pingcap/tikv/src/storage/txn/scheduler.rs:543:54/n)      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/[mod.rs:84](http://mod.rs:84/):19\n      tikv_util::yatp_pool::future_pool::PoolInner::spawn::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/future_pool.rs:163:27\n](http://github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/future_pool.rs:163:27/n)      <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/[mod.rs:84](http://mod.rs:84/):19\n      yatp::task::future::RawTask<F>::poll\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5f3d580/src/task/[future.rs:59](http://future.rs:59/):9\n  11: yatp::task::future::TaskCell::poll\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5f3d580/src/task/[future.rs:103](http://future.rs:103/):9\n      <yatp::task::future::Runner as yatp::pool::runner::Runner>::handle\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5f3d580/src/task/[future.rs:387](http://future.rs:387/):20\n  12: <tikv_util::yatp_pool::YatpPoolRunner<T> as yatp::pool::runner::Runner>::handle\n             at home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/mod.rs:109:24\n](http://github.com/pingcap/tikv/components/tikv_util/src/yatp_pool/mod.rs:109:24/n)      yatp::pool::worker::WorkerThread<T,R>::run\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5f3d580/src/pool/[worker.rs:48](http://worker.rs:48/):13\n      yatp::pool::builder::LazyBuilder<T>::build::{{closure}}\n             at rust/git/checkouts/yatp-e704b73c3ee279b6/5f3d580/src/pool/[builder.rs:114](http://builder.rs:114/):25\n      std::sys_common::backtrace::__rust_begin_short_backtrace\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/[backtrace.rs:122](http://backtrace.rs:122/):18\n  13: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[mod.rs:498](http://mod.rs:498/):17\n      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic/[unwind_safe.rs:271](http://unwind_safe.rs:271/):9\n      std::panicking::try::do_call\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:492](http://panicking.rs:492/):40\n      std::panicking::try\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panicking.rs:456](http://panicking.rs:456/):19\n      std::panic::catch_unwind\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/[panic.rs:137](http://panic.rs:137/):14\n      std::thread::Builder::spawn_unchecked_::{{closure}}\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/[mod.rs:497](http://mod.rs:497/):30\n      core::ops::function::FnOnce::call_once{{vtable.shim}}\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/[function.rs:227](http://function.rs:227/):5\n  14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:1854](http://boxed.rs:1854/):9\n      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/[boxed.rs:1854](http://boxed.rs:1854/):9\n      std::sys::unix::thread::Thread::new::thread_start\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/[thread.rs:108](http://thread.rs:108/):17\n  15: <unknown>\n  16: clone\n"] [location=/rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/[time.rs:744](http://time.rs:744/)] [thread_name=sched-worker-pool-0]
[2022/05/23 13:46:29.522 +00:00] [INFO] [[lib.rs:79](http://lib.rs:79/)] ["Welcome to TiKV"]

### PR DESCRIPTION
**Pull request by glorv**
Signed-off-by: glorv <glorvs@163.com>

### What is changed and how it works?

Issue Number: Close #12622

What's Changed:

```commit-message
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by glorv** [comment]
@hunterlxt  PTAL, thanks~

**Comment by hunterlxt** [comment]
looks like `set_write_bandwidth_limit` was not covered by tests before. Can you fix that?

**Review by hunterlxt — APPROVED** [review]
LGTM

**Review by Connor1996 — APPROVED** [review]
LGTM

**Pull request merged**
