### PR TITLE
copr:  fix the wrong arguments type of json_unquote (#10177)

### LINKED ISSUE #10176: json_unquote: Expect `Json`, received `Bytes`
### What version of TiKV are you using?
5.0

### What operating system and CPU are you using?
AMD Ryzen 5 PRO 4650U with Radeon Graphics

Ubuntu 18.04

### Steps to reproduce
This is a **coprocessor bug**. And should enable push down of `json_unquote`, which is not by default. But still need to fix it.

    drop table if exists t1;
    create table t1(c1 varchar(100));
    insert into t1 values('abc'), ('"abc"');
    select c1 from t1 where json_unquote(c1) = 'abc';

### What did you expect?
    mysql>     select c1 from t1 where json_unquote(c1) = 'abc';
    +-------+
    | c1    |
    +-------+
    | abc   |
    | "abc" |
    +-------+
    2 rows in set (0.00 sec)
### What did happened?

    mysql> select c1 from t1 where json_unquote(c1) = 'abc';
    ERROR 1105 (HY000): other error: [components/tidb_query_expr/src/types/expr_builder.rs:295]: Invalid json_unquote (sig = JsonUnquoteSig) signature: Evaluate error: [components/tidb_query_expr/src/types/function.rs:272]: Expect `Json`, received `Bytes`
    m

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #10177 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/10424
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/10424:release-5.0-2fb71587a699
```

---

Signed-off-by: guo-shaoge <shaoge1994@163.com>

### What problem does this PR solve?

Issue Number: close #10176 

Problem Summary: `json_unquote` implementation use `JsonRef` as argument type, which is not correct. It causes the following SQL report errors.

    drop table if exists t1;
    create table t1(c1 varchar(100));
    insert into t1 values('abc'), ('"abc"');
    select c1 from t1 where json_unquote(c1) = 'abc';

    mysql> select c1 from t1 where json_unquote(c1) = 'abc';
    ERROR 1105 (HY000): other error: [components/tidb_query_expr/src/types/expr_builder.rs:295]: Invalid json_unquote (sig = JsonUnquoteSig) signature: Evaluate error: [components/tidb_query_expr/src/types/function.rs:272]: Expect `Json`, received `Bytes`
    m

### What is changed and how it works?
What's Changed: change argument type from `JsonRef` to `BytesRef`.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 
- copr: fix the wrong arguments type of json_unquote

### CODE REVIEW

**Comment by guo-shaoge** [comment]
@skyzh PTAL

**Review by skyzh — APPROVED** [review]

**Review by Xuanwo — APPROVED** [review]

**Pull request merged**
