### PR TITLE
import: add unit tests for #4566

### PR DESCRIPTION
**Pull request by kennytm**
## What have you changed? (mandatory)

#4566 fixed a bug where upload/ingest failure is silently dropped at the gRPC interface, but without any tests. This PR adds back the test case.

## What are the type of the changes? (mandatory)

- Engineering (engineering change which doesn't change any feature or fix any issue)

## How has this PR been tested? (mandatory)

`cargo test --lib test_import_failure`

## Does this PR affect documentation (docs) or release note? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No

## Refer to a related PR or issue link (optional)

#4566

### CODE REVIEW

**Comment by overvenus** [comment]
@kennytm Could you update changelog in this PR?

**Comment by kennytm** [comment]
@overvenus change log of #4566?

**Comment by overvenus** [comment]
Yes @kennytm

**Comment by kennytm** [comment]
@overvenus PTAL again thanks.

**Comment by lonng** [comment]
Ping @kennytm 
I think we should close this PR due to the importer has separated into an individual repository.

**Pull request closed without merging**
