### PR TITLE
Storage: remove unnecessary `multi` attribute in `PointerGetter`

### LINKED ISSUE #11439: Remove `multi` option in point getter
## Development Task

Now `PointGetter` always uses prefix-seek. The `multi` option is useless and `PointGetter` can always use `ScanMode::Mixed`, see https://github.com/tikv/tikv/pull/11238#discussion_r752199356.

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
Remove unnecessary `multi` attribute in PointerGetter

### What is changed and how it works?

Issue Number: Close #11439 

What's Changed:

```
Remove the `multi` in `PointGetter` as `PointGetter` now always use `ScanMode::Mixed` which means `multi` is useless in `PointGetter`. Modify the code which is relevant to `multi`.

However, many of the mod tests in point_getter.rs depend on whether the `multi` of `PointGetter` is true or false. So I modified these tests accordingly.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
If this PR will be picked to release branch, then a release note is probably required.
```

### CODE REVIEW

**Review by youjiali1995 — APPROVED** [review]

**Comment by sticnarf** [comment]
@SpadeA-Tang Can you shorten and polish your PR title, following the [contribution guide](https://github.com/tikv/tikv/blob/master/CONTRIBUTING.md#format-of-the-commit-message)? Typically we don't have a hard limit of the title length, but it's not recommended to be too long and incomplete.

**Comment by SpadeA-Tang** [comment]
> @SpadeA-Tang Can you shorten and polish your PR title, following the [contribution guide](https://github.com/tikv/tikv/blob/master/CONTRIBUTING.md#format-of-the-commit-message)? Typically we don't have a hard limit of the title length, but it's not recommended to be too long and incomplete.
> 
> The more detailed commit messages should be put in the commit message code block in the PR description.
> 
> Thanks.

I have fixed the title. Thansk for the suggestion.

**Review by sticnarf — APPROVED** [review]
LGTM

**Pull request merged**
