### PR TITLE
compaction-filter: consider  mvcc-delete as redundant key to trigger rocksdb compaction

### LINKED ISSUE #17269: compaction: consider redundant mvcc.delete rows to trigger Rocksdb compaction
## Development Task
Now we have `region-compact-min-redundant-rows`  to trigger compaction, however it does not consider the following situation:
table A, insert 1000 rows in a transaction, with the first 999 rows being deleted in another transaction,
now for rows 1-999, each row has two mvcc versions, and the mvcc information in rocksdb could be as followings:
```
row_1_t1=> PUT
row_1_t2=> DELETE
row_2_t1=>PUT
row_2_t2=>DELETE
...
row_999_t1=>PUT
row_999_t2=> DELETE
row_1000_t1=>PUT
```
with the help of `region-compact-min-redundant-rows`, the first compact will be trigger, and then it will left 1 version for each row:
```
row_1_t2=>DELETE
row_2_t2=>DELETE
row_3_t2=>DELETE
...
row_999_t2=>DELETE
row_1000_t1=>PUT
```
and when we try to `select from table limit 1`, it will always read the 999 DELETE versions first which is with bad performace. And `region-compact-min-redundant-rows` does not consider this situation and can not trigger a compaction.  Usually, no data will be inserted between row 1 to row 999, so these old versions will never be cleared.

### PR DESCRIPTION
**Pull request by AndreMouche**
### What is changed and how it works?

Issue Number: Close #17269 

What's Changed:

```commit-message
compaction-filter: consider mvcc.delete as redundant key to trigger Rocksdb compaction
```

### Release note

```release-note
compaction-filter: consider mvcc.delete as redundant key to trigger Rocksdb compaction
```

### CODE REVIEW

**Review by MyonKeminta — APPROVED** [review]

**Review by SpadeA-Tang — APPROVED** [review]

**Comment by LykxSassinator** [comment]
Could this enhancement be cherry-picked to both v7.5 and v8.1 ?

**Comment by glorv** [comment]
> Could this enhancement be cherry-picked to both v7.5 and v8.1 ?

You can add `type/bug` to the issue and then cherry-pick to other LTS branches. 😅

**Comment by cfzjywxk** [comment]
@AndreMouche 

This change has a similar PR before https://github.com/tikv/tikv/pull/13352, it's not merged because there could be performance regression in some cases.

We need a complete and comprehensive test and decide whether this should be enabled by default.

**Comment by AndreMouche** [comment]
@cfzjywxk  I think the PR you mentioned #13352 is similar with https://github.com/tikv/tikv/pull/15342  which is already merged long day ago. So the current impact of this PR on performance is controllable, because the main feature that may impact performance  (#13352 or #15342)has already been merged in #15342

**Comment by zhangjinpeng87** [comment]
test for this change https://github.com/tikv/tikv/pull/17725/files

**Pull request merged**
