### PR TITLE
raftstore: make threads of snap-generator pool configurable

### LINKED ISSUE #11247: Make threads of `snap-generator` pool be adjustable
## Background
In recover scenario,  because we want TiDB to make up the copy as soon as possible, we release all limit, including `store limit`, `scheduling limit`,  `snap-max-write-bytes-per-sec` and so on. but the IO only reach to 150MB/s for each TiKV instance. after we change the pool size of region worker from `2` to `32`, the recover speed has been effectively improved.
https://github.com/tikv/tikv/blob/14895dc46c48586946445ebff12e6380c7b561bf/components/raftstore/src/store/worker/region.rs#L631-L635

the IO speed reach to 650MB/s：
image

### PR DESCRIPTION
**Pull request by iosmanthus**
### What problem does this PR solve?

Issue Number: close #11247 

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
make threads of snap-generator pool configurable
```

### CODE REVIEW

**Review by zhongzc — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Review by zz-jason — APPROVED** [review]
LGTM

**Comment by ekexium** [comment]
Did the document get updated for the change?

**Pull request merged**
