### PR TITLE
tikv-ctl: allow get_all_regions from remote, drop-unapplied-raftlog (…

### PR DESCRIPTION
**Pull request by andylokandy**
Signed-off-by: Andy Lok <andylokandy@hotmail.com>

### What is changed and how it works?

1. Allow getting region info for all regions from the remote store:

`tikv-ctl --host 127.0.0.1:20160 raft region --all-regions`

2. Print region start key and end key with:

`tikv-ctl --host 127.0.0.1:20160 region-properties -r 1`

3. Added subcommand:

- `tikv-ctl unsafe-recover remove-failed-stores -s 1,2,3 -r 1,2,3 --promote-learner`: Promote the learner to leader if only one learner exists
- `tikv-ctl unsafe-recover drop-unapplied-raftlog -r 1,2,3`: regress the commit index to the apply index for the region

### Related changes

- https://github.com/pingcap/kvproto/pull/797
- PR to update `pingcap/docs`/`pingcap/docs-cn`: yes

### Check List 

Tests 

### Release note 

```release-note
1. Allow getting region info for all regions on the remote store:

`tikv-ctl --host 127.0.0.1:20160 raft region --all-regions`

2. Print region start key and end key with:

`tikv-ctl --host 127.0.0.1:20160 region-properties -r 1`

3. Added subcommand:

- `tikv-ctl unsafe-recover remove-failed-stores -s 1,2,3 -r 1,2,3 --promote-learner`: Promote the learner to leader if only one learner exists
- `tikv-ctl unsafe-recover drop-unapplied-raftlog -r 1,2,3`: regress the commit index to the apply index for the region
```

### CODE REVIEW

**Comment by iosmanthus** [comment]
@andylokandy Please fix the building, it contains some unresolved confilcts.

**Review by zhongzc — APPROVED** [review]

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by andylokandy** [comment]
hotfix canceled

**Pull request closed without merging**
