### PR TITLE
 backup: do fill in the file size of each SST file in the response (#6664)

### PR DESCRIPTION
**Pull request by kennytm**
###  What have you changed?

Cherry-pick #6664 to release-3.1.

###  What is the type of the changes?

- Bugfix (a change which fixes an issue)

###  How is the PR tested?

- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No

###  Does this PR affect `tidb-ansible`?

No

###  Refer to a related PR or issue link (optional)

pingcap/br#163

### CODE REVIEW

**Comment by kennytm** [comment]
PTAL @youjiali1995 (needs a `/merge`)

**Comment by youjiali1995** [comment]
Branch release-3.1 has been frozen for the release of v3.1.0-beta.2. Can it be merged in the next release? @kennytm

**Comment by kennytm** [comment]
Yes

**Pull request merged**
