### PR TITLE
causal_ts: add benchmark

### PR DESCRIPTION
**Pull request by pingyu**
Issue Number: #12794

Signed-off-by: pingyu <yuping@pingcap.com>

### What is changed and how it works?

Issue Number: Ref #12794

What's Changed:

```commit-message
1. Add benchmark for `causal_ts.BatchTsoProvider`.
2. Change implementation of `TestPdClient.batch_get_tso` to meet interface convention of real PD.
3. Remove "TODO" of making batch removal async for `causal_ts.TsoBatchList`.
```

This is a following PR of #12970. Its original purpose is addressing 2 TODOs ([here](https://github.com/tikv/tikv/blob/90c4a0602040102fabf45ea8e8bfac33f4472d07/components/causal_ts/src/tso.rs#L221) & [here](https://github.com/tikv/tikv/blob/90c4a0602040102fabf45ea8e8bfac33f4472d07/components/causal_ts/src/tso.rs#L257), to make some batch removal operations async and reduce latency.

However, I found that the performance has regressed. See the code [here](https://github.com/tikv/tikv/compare/master...pingyu:tso_batch_list_async), and benchmark result as following. Removing batches with write lock cost `~50ns`, while async implementation by `Worker` cost `> 1us`.
```shell
batch_tso_list_pop/100 sync
                        time:   [48.856 ns 51.229 ns 54.178 ns]
                        change: [-33.633% -18.979% -3.3177%] (p = 0.03 < 0.05)
                        Performance has improved.
batch_tso_list_pop/100 async
                        time:   [1.1562 us 1.3353 us 1.5321 us]
                        change: [-24.163% -5.1578% +20.336%] (p = 0.66 > 0.05)
                        No change in performance detected.
batch_tso_list_pop/10k sync
                        time:   [49.764 ns 51.910 ns 54.444 ns]
                        change: [-28.391% -8.9375% +7.3228%] (p = 0.63 > 0.05)
                        No change in performance detected.
batch_tso_list_pop/10k async
                        time:   [1.1431 us 1.3593 us 1.5998 us]
                        change: [-14.857% +7.3530% +34.254%] (p = 0.54 > 0.05)
                        No change in performance detected.

batch_tso_list_push/sync
                        time:   [173.60 ns 177.21 ns 181.55 ns]
                        change: [-12.558% -9.0807% -5.6845%] (p = 0.00 < 0.05)
                        Performance has improved.
batch_tso_list_push/async
                        time:   [1.2271 us 1.3425 us 1.4572 us]
                        change: [-14.981% -7.4771% +1.1376%] (p = 0.08 > 0.05)
                        No change in performance detected.
```

So the change for making batch removal async is undone, and just add codes of benchmark for future use.

The result of benchmark in this PR:
```shell
❯ cargo criterion -p causal_ts -- tso
...
...
batch_tso_list_pop/100  time:   [51.912 ns 68.496 ns 89.613 ns]
batch_tso_list_pop/10k  time:   [48.877 ns 51.868 ns 55.396 ns]

batch_tso_list_push/50  time:   [152.94 ns 154.12 ns 155.38 ns]
batch_tso_list_push/1024
                        time:   [179.25 ns 181.07 ns 183.03 ns]

bench_batch_tso_provider_get_ts
                        time:   [105.93 ns 106.75 ns 107.65 ns]

bench_batch_tso_provider_flush
                        time:   [6.4969 us 7.1447 us 7.8449 us]
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`: No.
- Need to cherry-pick to the release branch: No.

### Check List 

Tests 

- Unit test

Side effects

- No.
- 
### Release note 

```release-note
Add benchmark for causal_ts.BatchTsoProvider.
```

### CODE REVIEW

**Comment by pingyu** [comment]
> /cc @haojinming @zeminzhou

PTAL, thanks~

**Review by haojinming — APPROVED** [review]
LGTM

**Comment by pingyu** [comment]
> /cc @Connor1996

PTAL, thanks~

**Review by zeminzhou — APPROVED** [review]
LGTM~

**Review by Connor1996 — APPROVED** [review]

**Pull request merged**
