### PR TITLE
copr: add duration_string_time_diff

### PR DESCRIPTION
**Pull request by awoods12**
Hi! I'm new to the project and this is my first PR. Modeled this PR after existing code and other PRs of TiDB function migration. 

### What problem does this PR solve?

Issue Number: part of https://github.com/tikv/tikv/issues/5751

Problem Summary: migrating duration_string_time_diff from TiDB

### What is changed and how it works?

What's Changed:
- Implement `duration_string_time_diff`. Wrote this similarly to go implementation in `tidb/expression/builtin_time.go` by casting the string to duration and using an existing duration diff function.

### Related changes

- No related changes

### Check List 

Tests

- Unit test

Test does not mock duration_duration_time_diff. Seems okay in this context, but let me know if this should be mocked in some way or implemented differently to avoid double testing.

### Release note

```release-note
- Implement duration_string_time_diff
```

### CODE REVIEW

**Comment by awoods12** [comment]
/cc @BusyJay 

Hey, based on instructions it seems this should be auto-assigning reviewers, but I’m not seeing anything happening. Gave auto-cc a try too.

Let me know if there’s some other way I should be requesting reviews, I picked a random reviewer off the posted list.

**Review by Xuanwo — APPROVED** [review]

**Review by skyzh — APPROVED** [review]

**Comment by skyzh** [comment]
Looks like there is a merge conflict. Would you please resolve this? @awoods12

**Comment by skyzh** [comment]
Looks like this PR is inactive. Therefore, I would close this in favor of https://github.com/tikv/tikv/pull/11372.

**Pull request closed without merging**
