### PR TITLE
copr: use lookup table and remove truncate_uint branch in non-vectori…

### PR DESCRIPTION
**Pull request by ZiheLiu**
Signed-off-by: ZiheLiu <ziheliu1024@gmail.com>

###  What have you changed?

- Use lookup table instead of i64.pow() to get shift (https://github.com/tikv/tikv/pull/3532#discussion_r213747439).
- Remove branch where `x` is u64, since there is `truncate_uint`.
- Remove test cases where `x` is u64.

###  What is the type of the changes?

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?

- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No.

###  Does this PR affect `tidb-ansible`?

No.

###  Refer to a related PR or issue link (optional)
#3532

###  Benchmark result if necessary (optional)
None.

###  Any examples? (optional)
None.

### CODE REVIEW

**Comment by sticnarf** [comment]
PTAL @iosmanthus

**Comment by iosmanthus** [comment]
@ZiheLiu Please handle the conflict. Rest LGTM.

**Comment by ZiheLiu** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/123

**Comment by ZiheLiu** [comment]
@sre-bot /run-integration-copr-test copr-test

**Comment by ZiheLiu** [comment]
> @ZiheLiu Please handle the conflict. Rest LGTM.

Thanks! Resolved the conflict.

**Comment by ZiheLiu** [comment]
@sre-bot /run-integration-common-test

**Comment by ZiheLiu** [comment]
@sre-bot /run-integration-common-test

**Comment by ZiheLiu** [comment]
@iosmanthus The errors has been fixed. Could you merge it again? Thanks!

**Pull request merged**
