### PR TITLE
raftstore: add metrics for snapshots that are dropped

### LINKED ISSUE #17836: Add metrics for Raft snapshots that are dropped
Currently, TiKV does not expose metrics to track dropped Raft snapshot tasks during sending or receiving when concurrency limits are exceeded. Adding this observability helps identify bottlenecks and improves scaling diagnostics.

### PR DESCRIPTION
**Pull request by hbisheng**
### What is changed and how it works?

Issue Number: Close #17836

What's Changed:

```commit-message
This commit adds metrics to track Raft snapshots that are dropped 
during sending or receiving due to concurrency limits. These metrics 
help identify bottlenecks during scaling.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by glorv** [comment]
```
--- TRY 3 STDERR:        backup-stream::integration all::update_config ---

thread 'br-1::update_config-0' panicked at components/backup-stream/tests/integration/mod.rs:505:13:

assertion `left == right` failed

  left: 6

 right: 4
```

@hbisheng Please fix the failed case.

**Pull request merged**
