### PR TITLE
raftstore: speed up conf change (#6421)

### PR DESCRIPTION
**Pull request by BusyJay**
#  What have you changed?

Cherry pick #6421.

###  What is the type of the changes?

- Bugfix

###  How is the PR tested?

- Unit test
- Integration test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?
No

###  Does this PR affect `tidb-ansible`?
No.

###  Refer to a related PR or issue link (optional)

#6421, #6420, #6430.

### CODE REVIEW

**Comment by BusyJay** [comment]
PTAL

**Comment by youjiali1995** [comment]
@overvenus @hicqu @gengliqi PTAL

**Comment by BusyJay** [comment]
@gengliqi Because generating snapshot won't go to apply worker in release-3.1.

**Pull request merged**
