### PR TITLE
Interactive mode command miss "-i"

### PR DESCRIPTION
**Pull request by bigzuo**
Interactive mode command miss "-i"

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note

### CODE REVIEW

**Comment by sticnarf** [comment]
LGTM. Thank you!

By the way, please sign off your commits to pass the DCO test. You may need a force push.

**Comment by andylokandy** [comment]
@bigzuo Can you commit with `git commit -s .....` to fix the DCO?

**Comment by andylokandy** [comment]
@bigzuo I'm sorry, `/docs` is going to be removed, so I have to close this PR. Your suggestion will be applied to https://github.com/tikv/website/pull/210. Thank you for your contribution!

**Comment by lilin90** [comment]
> @bigzuo I'm sorry, `/docs` is going to be removed, so I have to close this PR. Your suggestion will be applied to [tikv/website#210](https://github.com/tikv/website/pull/210). Thank you for your contribution!

FYI. Changes in this PR has been added to https://github.com/tikv/website/pull/210 in https://github.com/tikv/website/pull/210/commits/ec78851ba087c12843d8491f365e38d8c54efbc2.

**Pull request closed without merging**
