### PR TITLE
tests: should register mailbox before sending

### LINKED ISSUE #4244: raftstore::store::fsm::router::tests::test_basic failed
## Bug Report

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/1606/pipeline

### PR DESCRIPTION
**Pull request by BusyJay**
## What have you changed? (mandatory)

Otherwise mailbox may not be found and lead to `SendError`.

Close #4244.

## What are the type of the changes? (mandatory)

- Bug fix

## How has this PR been tested? (mandatory)

unit tests

## Does this PR affect documentation (docs) update? (mandatory)

No.

## Does this PR affect tidb-ansible update? (mandatory)

No.

### CODE REVIEW

**Comment by kennytm** [comment]
Test failure though...

```
thread 'raftstore::store::fsm::router::tests::test_basic' panicked at 'assertion failed: dropped.load(Ordering::SeqCst)', src/raftstore/store/fsm/router.rs:564:9
```

**Comment by BusyJay** [comment]
PTAL

**Comment by BusyJay** [comment]
Fail case is unrelated.

**Comment by ngaut** [comment]
Could you file an issue for the failed test?

**Pull request merged**
