### PR TITLE
Quota limiter: increase refill duration to avoid much context switch cost (#12264)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #12264 to release-6.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/12266
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/12266:release-6.0-a9c1e59bad94
```

---

Signed-off-by: Xintao <hunterlxt@live.com>

### What is changed and how it works?

Issue Number: Close #xxx

What's Changed:

```commit-message
Quota limiter: increase refill duration to avoid much context switch cost.
```

### Related changes

- Need to cherry-pick to the release 6.0 branch

### Check List 

Tests 

- Unit test
- Integration test
- No code

Side effects

- None

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hunterlxt** [comment]
@VelocityLight PTAL

**Review by hunterlxt — APPROVED** [review]

**Review by tabokie — APPROVED** [review]

**Comment by you06** [comment]
@VelocityLight PTAL

**Comment by hunterlxt** [comment]
> 

Can you help me

**Comment by hunterlxt** [comment]
> Merge canceled because a new commit is pushed.

Can you help me

**Pull request merged**
