### PR TITLE
copr: add a `force_no_pad` argument to `sort_compare`, and fix `like` behavior

### LINKED ISSUE #17332: copr: the behavior of `like` is not correct for string with characters equal with space
## Bug Report

The following test case will fail if it's added to the `test_like()`:

```rust
            (
                r#"a　a"#,
                r#"a a"#,
                '\\',
                Collation::Utf8Mb4UnicodeCi,
                Some(1),
            ),
```

### PR DESCRIPTION
**Pull request by YangKeao**
### What is changed and how it works?

Issue Number: Close #17332

I added a new `force_no_pad` argument to the `sort_compare` function. And fix the behavior of `like` related to space. Previously, the `like` will use `sort_compare` to compare (most of the time) a single character, which is not correct because if the collation is `PAD`, it'll remove the space, and the comparison between a space and another character which equals to the space will fail.

I admit that this change is not elegant, but I cannot think up a better way (maybe you, reviewers, have better suggestions?). I've considered the following options:

1. Require the collations to implement a function without padding, and automatically implement PAD version. However, as the character type of each collations are different (especially for `binary`), it cannot be simply done.
2. Replace the function `like` with several more specialized version. Most of the time, the collation of all arguments and return values should be the same. They are different when the TiDB didn't enable new collation framework (see https://github.com/tikv/tikv/pull/13785 ).

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Release note

```release-note
Fix the issue that the behavior of `like` for space characters and `utf8mb4_unicode_ci`/`utf8mb4_general_ci` are incorrect.
```

### CODE REVIEW

**Review by breezewish — APPROVED** [review]
I have even no idea why there is a trim_end_matches previously :) Collation is too complex.

**Review by wjhuang2016 — APPROVED** [review]

**Pull request merged**
