### PR TITLE
UCP: Migrate non-vectorized SecToTime from TiDB

### LINKED ISSUE #6873: UCP: Migrate scalar function `SecToTime` from TiDB
## Description

Port the scalar function `SecToTime` from TiDB to coprocessor.

## Score 

* 50

## Mentor(s)

* @iosmanthus 

## Recommended Skills

* Rust programming 

## Learning Materials

Already implemented expressions ported from TiDB

- https://github.com/tikv/tikv/tree/master/components/tidb_query/src/rpn_expr) 
- https://github.com/tikv/tikv/tree/master/components/tidb_query/src/expr)

### PR DESCRIPTION
**Pull request by skyzh**
Signed-off-by: Alex Chi iskyzh@gmail.com

UCP #6873

Checklist #5751

### What problem does this PR solve?

Issue Number: close #6873

Problem Summary:

### What is changed and how it works?

Migrate `SecToTime` from TiDB

What's Changed:

### Check List

Tests

- Unit test

### CODE REVIEW

**Comment by skyzh** [comment]
Hi @iosmanthus ! I'm trying to implement SecToTime, and I have some question about that.

The first question is about field type. It seems that in TiDB tests, this function can accept multiple types (real, string, int) in this function.  https://github.com/pingcap/tidb/blob/master/expression/builtin_time_test.go#L2487

Meanwhile, the implementation in TiDB uses a single `eval_real` to get this parameter. https://github.com/pingcap/tidb/blob/master/expression/builtin_time.go#L6117

Where does the conversion take place? Can I implement this in Rust using something like:

```rust
match self.children[0].eval_real(ctx, row) {
    Ok(x) => x,
    Err(_) => match match self.children[0].eval_int(ctx, row) {
        ...
    }
}
```

Another question is about the test case. In https://github.com/pingcap/tidb/blob/master/expression/builtin_time_test.go#L2487
 , I found these two test cases.

```go
		{5, types.NewFloat64Datum(86401.54321), "24:00:01.54321"}
		{-1, types.NewFloat64Datum(86401.54321), "24:00:01.543210"}
```

It seems that these two cases are the same, in condition that `sec_to_time` returns a duration struct. How to implement this in TiKV?

Thanks for your explanation in advance!

**Comment by skyzh** [comment]
I've changed my implementation of `sec_to_time`. The difference between this and golang version is that:

* only accept real field type
* remove tests for invalid string `abc`
* use maximum fsp in tests and function

**Comment by TennyZhuang** [comment]
@breeswish

**Comment by breeswish** [comment]
Unfortunately Coprocessor evaluation framework does not support variable types now...

**Comment by skyzh** [comment]
My plan is that:

- [ ] Implement SecToTimeReal, SecToTimeString, and SecToTimeInt
- [ ] It seems that we should make PR to tipb to make this work?
- [ ] Re-open this PR after new signatures are added in tipb

**Comment by breeswish** [comment]
@skyzh Yes, your understanding is correct.

**Comment by TennyZhuang** [comment]
@skyzh a PR to tipb is required, but you can implement sec_to_time<T> in tikv.

**Pull request closed without merging**
