### PR TITLE
Move engine::rocks to engine_rocks::raw

### PR DESCRIPTION
**Pull request by brson**
### What problem does this PR solve?

Work toward deleting the engine crate in favor of engine rocks.

https://github.com/tikv/tikv/issues/6402

### What is changed and how it works?

This moves the rocksdb reexports from `engine::rocks` to `engine_rocks::raw`. After this PR no new reexports should be added to the engine crate, as it is going to be deleted. If necessary, reexports can be added to `engine_rocks::raw`.

`engine_rocks::raw` will not exist forever because it does not support abstraction, and it would be preferable if new rocksdb features were exposed through traits, in ways that make sense for potential implementation by other engines.

### Related changes

https://github.com/tikv/tikv/issues/6402

### Release note 

- No release note.

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
There are some building errors
```
[2020-06-18T01:26:17.527Z] error[E0432]: unresolved import `engine::rocks`

[2020-06-18T01:26:17.527Z]  --> tests/benches/raftstore/mod.rs:7:13

[2020-06-18T01:26:17.527Z]   |

[2020-06-18T01:26:17.527Z] 7 | use engine::rocks::DB;

[2020-06-18T01:26:17.527Z]   |             ^^^^^ could not find `rocks` in `engine`

[2020-06-18T01:26:17.527Z] 

[2020-06-18T01:26:20.038Z] error: unused import: `engine_rocks::Compat`

[2020-06-18T01:26:20.038Z]  --> tests/benches/raftstore/mod.rs:8:5

[2020-06-18T01:26:20.038Z]   |

[2020-06-18T01:26:20.038Z] 8 | use engine_rocks::Compat;

[2020-06-18T01:26:20.038Z]   |     ^^^^^^^^^^^^^^^^^^^^

[2020-06-18T01:26:20.038Z]   |

[2020-06-18T01:26:20.038Z]   = note: `-D unused-imports` implied by `-D warnings`

[2020-06-18T01:26:20.038Z] 

[2020-06-18T01:26:20.038Z] error: unused import: `Mutable`

[2020-06-18T01:26:20.038Z]  --> tests/benches/raftstore/mod.rs:9:21

[2020-06-18T01:26:20.038Z]   |

[2020-06-18T01:26:20.038Z] 9 | use engine_traits::{Mutable, WriteBatchExt};

[2020-06-18T01:26:20.038Z]   |                     ^^^^^^^

[2020-06-18T01:26:20.038Z] 

[2020-06-18T01:26:20.038Z] error: unused import: `WriteBatchExt`

[2020-06-18T01:26:20.038Z]  --> tests/benches/raftstore/mod.rs:9:30

[2020-06-18T01:26:20.038Z]   |

[2020-06-18T01:26:20.038Z] 9 | use engine_traits::{Mutable, WriteBatchExt};

[2020-06-18T01:26:20.038Z]   |                              ^^^^^^^^^^^^^

[2020-06-18T01:26:20.038Z] 

[2020-06-18T01:26:20.038Z] error: aborting due to 4 previous errors
```

**Comment by Connor1996** [comment]
Oh, why QPS for oltp_update_index increases so much

**Comment by brson** [comment]
OK, I think I've fixed the benchmark build error.

**Pull request merged**
