### PR TITLE
In-memory engine: unify in-memory engine crate and struct name

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
### What is changed and how it works?

Issue Number: Ref #16141

What's Changed:

```commit-message
adjust name from range_cache_* to region_cache_*
```

Manual test for checking metrics work as expected:
image

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]
Much better!

**Review by glorv — APPROVED** [review]

**Review by zhangjinpeng87 — APPROVED** [review]
LGTM for config change.

**Pull request merged**
