### PR TITLE
[Cherry-pick 3.1] Support Follower Read

### PR DESCRIPTION
**Pull request by 5kbpers**
cherry-pick https://github.com/tikv/tikv/pull/5051 https://github.com/tikv/tikv/pull/5118 https://github.com/tikv/tikv/pull/5001

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
ci failed
match req.cmd {
          ^^^^^^^ pattern `Some(Empty(_))` not covered

**Comment by 5kbpers** [comment]
> ci failed
> 
> ```
> match req.cmd {
>           ^^^^^^^ pattern `Some(Empty(_))` not covered
> ```

Seems we require to cherry-pick: https://github.com/tikv/tikv/pull/5001

**Comment by overvenus** [comment]
Missing https://github.com/tikv/tikv/pull/5401/files ?

**Comment by 5kbpers** [comment]
> Missing #5401 ?

Will cherry-pick it in next PR (I think it not only affects follower read)

**Comment by MyonKeminta** [comment]
Is this PR on going? I have another PR that requires #5001 too.

**Comment by 5kbpers** [comment]
> Is this PR on going? I have another PR that requires #5001 too.

Yes, approval wanted!

**Pull request merged**
