### PR TITLE
upgrade lz4-sys to 1.9.4 to tackle security issue

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
### What is changed and how it works?

Issue Number: Ref #15621

What's Changed:

```commit-message
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by tonyxuqqi** [comment]
Cargo.lock cannot be manually updated. It's done automatically. @SpadeA-Tang

**Comment by SpadeA-Tang** [comment]
> Cargo.lock cannot be manually updated. It's done automatically. @SpadeA-Tang

https://github.com/tikv/raft-engine/pull/338#discussion_r1325596256

**Review by tonyxuqqi — APPROVED** [review]

**Review by bufferflies — APPROVED** [review]

**Pull request merged**
