### PR TITLE
Introduce match_template to simplify code

### PR DESCRIPTION
**Pull request by breeswish**
## What have you changed? (mandatory)

`match_template` is a macro for substituting match arms, from

```rust
match_template! {
    T = [Int, Real, Double],
    match Foo {
        EvalType::T => { panic!("{}", EvalType::T); },
    }
}
```

to:

```rust
match Foo {
    EvalType::Int => { panic!("{}", EvalType::Int); },
    EvalType::Real => { panic!("{}", EvalType::Real); },
    EvalType::Double => { panic!("{}", EvalType::Double); },
}
```

The code base are also simplified using this match_template.

- [x] Merge https://github.com/tikv/tikv/pull/4725 first.

## What are the type of the changes? (mandatory)

- Engineering (engineering change which doesn't change any feature or fix any issue)

## How has this PR been tested? (mandatory)

No need.

### CODE REVIEW

**Comment by sticnarf** [comment]
Don't forget to regenerate the Dockerfile

**Comment by sticnarf** [comment]
> In my opinion, this PR neither makes code more readable nor makes things simple.

The drawback is that it confuses people who first read the code, but I think the comments of match_template states clearly what the macro expands into. I think it increases readability by increasing information density without repeating the same pattern.

**Comment by breeswish** [comment]
> In my opinion, this PR neither makes code more readable nor makes things simple.

You can take a look at how it simplify the BatchSimpleAggrExecutor

**Pull request merged**
