### PR TITLE
In-Memory Engine: add a tag to the range for easier troubleshooting

### PR DESCRIPTION
**Pull request by tonyxuqqi**
### What is changed and how it works?

Issue Number: Ref #16141

What's Changed:

```commit-message
In-Memory Engine: add a tag into Range for diagnostics
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 
- [x] No code

### Release note

```release-note
None
```

### CODE REVIEW

**Review by afeinberg — APPROVED** [review]
LGTM, should we also support setting that tag somehow from a label rule?

**Review by v01dstar — APPROVED** [review]
LGTM

**Review by afeinberg — APPROVED** [review]
LGTM. @tonyxuqqi do you want me to pre-populate the tag from a label rule?

**Pull request merged**
