### PR TITLE
storage: remove histogram about locking key in prewrite

### LINKED ISSUE #13526: Remove useless `CONCURRENCY_MANAGER_LOCK_DURATION_HISTOGRAM`
## Development Task

It is impossible to get blocked when acquiring a lock from the concurrency manager when generating async-commit timestamp because  the latch already ensures there can't be race on the same key.

We don't need to know how long it takes to call `lock_keys` because it's always fast.

### PR DESCRIPTION
**Pull request by sticnarf**
Signed-off-by: Yilin Chen <sticnarf@gmail.com>

### What is changed and how it works?

Issue Number: Close #13526

What's Changed:

```commit-message
It is impossible to get blocked when acquiring a lock from the concurrency
manager when generating async-commit timestamp because the latch
already ensures there can't be race on the same key.

So, the histogram recording the duration is useless and is removed in
this commit.
```

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by ekexium — APPROVED** [review]

**Review by MyonKeminta — APPROVED** [review]
It's ok to me to remove it if it's confirmed to be a fact that its indeed always fast. But it seems that when reading requests checks the memory lock, it also need to lock the mutex of the key, which is not in latch. 😕

**Comment by sticnarf** [comment]
> It's ok to me to remove it if it's confirmed to be a fact that its indeed always fast. But it seems that when reading requests checks the memory lock, it also need to lock the mutex of the key, which is not in latch. 😕

It's different.

`lock_key` locks the `AsyncMutex` in `KeyHandle`. It never has mutex conflicts.

What may have conflicts is the `Mutex` on `lock_store`. We lock the `Mutex` of `lock_store` when checking or modifying the memory lock.

**Comment by sticnarf** [comment]
@MyonKeminta Will the new locking mechanism you're working on use the concurrency manager and lock the key mutex?

**Comment by MyonKeminta** [comment]
> We lock the `Mutex` of `lock_store` when checking or modifying

No. I didn't touch the concurrency manager.

**Pull request merged**
