### PR TITLE
raftstore: add more duplicate entry check before proposing write command and batching commands

### PR DESCRIPTION
**Pull request by cfzjywxk**
### What is changed and how it works?

Issue Number: Ref #16818 

What's Changed:

For the issue https://github.com/tikv/tikv/issues/16818.

Possible reasons for the occurrence of duplicate `PUT` requests to the lock CF for the same key in a single `RaftCmdRequest` are as follows:

1. **Duplicate Entries in the Proposed `RaftCmdRequest`**:  
   The `RaftCmdRequest` being proposed contains duplicate entries. For example, the transaction write command initiated during async write may have duplicate key entries. This is typically unexpected. In TiKV's transaction model, every key being written must acquire a latch before writing. Concurrent writes to the same key are sequenced through the latch and should not end up in the same `RaftCmdRequest`.

2. **Batch Builder Aggregating Writes to the Same Key**:  
   During the batch building process for proposing raft commands, writes to the same key are grouped into a single batch. However, this possibility is quite low because, as mentioned above, writes to the same key should only proceed after the latch is released during the `apply` phase. For writes to occur, `apply` must have already completed, making it unlikely that these commands are processed together in a single raft store loop.

3. **Issues with Latch Release Timing**:  
   The latch is expected to be released only after the `apply` phase is completed. If there's a problem with the latch release mechanism, it could allow duplicate writes to proceed. There is no any recent modification to this part of the code from my observation.

4. **Batch Processing In The Apply Worker**
It seems nearly impossible based on the code. While there is batch processing during the Apply phase, the panic check for duplicate entries in the change logs observed by CDC is still performed at the `RaftCmdRequest` level. In other words, batching during the Apply phase does not modify the contents of the original `RaftCmdRequest`. Therefore, it is unlikely that the problem originates from this step.

This PR attempts to add checks in the aforementioned areas. If a duplicate entry is detected, TiKV will panic, helping to narrow down the scope of the investigation. Once the issue is identified and resolved, the related checking code can be removed.

From the benchbot regression, there is no significant differences

Patched version:
image

Nightly version:
image

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [x] Performance regression: Consumes more CPU
- [x] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by MyonKeminta — APPROVED** [review]

**Comment by LykxSassinator** [comment]
One suggestion: Given the additional check on the progress of `async-write`, it is recommended to provide performance comparisons between the master branch and this PR. This will help demonstrate that this PR does not introduce any significant performance regressions.

**Comment by cfzjywxk** [comment]
> One suggestion: Given the additional check on the progress of `async-write`, it is recommended to provide performance comparisons between the master branch and this PR. This will help demonstrate that this PR does not introduce any significant performance regressions.

@LykxSassinator The sysbench write only bench test result is added to the descriptions

**Comment by LykxSassinator** [comment]
Wait for https://github.com/tikv/tikv/pull/17942 merged.

**Pull request merged**
