### PR TITLE
Add curl command into docker image

### PR DESCRIPTION
**Pull request by mikechengwei**
### What is changed and how it works?

Issue Number: ref #13781.

What's Changed:

Fix tidb operator tikv command health check, ref: https://github.com/pingcap/tidb-operator/issues/4764
```commit-message
Add curl command into docker image.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
Please add a release note.

Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with None.
If this PR will be picked to release branch, then a release note is probably required.
```

### CODE REVIEW

**Review by sticnarf — APPROVED** [review]

**Review by ngaut — APPROVED** [review]

**Comment by sticnarf** [comment]
@mikechengwei Can you create an issue under the tikv repo and link it to the PR? Our robot does not recognize issues of other repos. :(

**Comment by mikechengwei** [comment]
> @mikechengwei Can you create an issue under the tikv repo and link it to the PR? Our robot does not recognize issues of other repos. :(

ok

**Pull request merged**
