### PR TITLE
raftstore: separate RaftlogGc to an individual thread

### PR DESCRIPTION
**Pull request by 5kbpers**
Signed-off-by: 5kbpers <tangminghua@pingcap.com>

###  What have you changed?

Previous PR https://github.com/tikv/tikv/pull/5297 merged Compact, RaftlogGc, CleapSST into one thread. But we found that would cause a long-running compaction job blocks raftlog GC, then increase compaction frequency of RaftDB, take up more disk I/O bandwidth.
This PR separates RaftlogGc to an individual thread to fix this problem.

###  What is the type of the changes?

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?

CI

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No.

###  Does this PR affect `tidb-ansible`?

No.

### CODE REVIEW

**Comment by siddontang** [comment]
IMO, compacting raft logs has a higher priority than handing SST and compacting Range. and the handing SST may community with PD to check the region which may also block the following compacting raft logs if the network has a problem.

**Comment by siddontang** [comment]
PTAL @zhangjinpeng1987

**Comment by zhangjinpeng1987** [comment]
Compacting raft logs has a higher priority than the other two, it shouldn't be blocked by the other two kind jobs.

**Comment by 5kbpers** [comment]
Updated, PTAL @siddontang @zhangjinpeng1987

**Comment by Little-Wallace** [comment]
Why don't we separate CompactTask to an individual thread, instead of RaftlogGc? CompactTask cost more time than other task obviously.

**Comment by 5kbpers** [comment]
> Why don't we separate CompactTask to an individual thread, instead of RaftlogGc? CompactTask cost more time than other task obviously.

In my understanding, CleanupSST seems not a high priority task, it only triggered to remove SSTs the tikv-importer uploaded, it acceptable to delay it a few minutes. RaftlogGc has higher priority and we don't want it blocked by any other task.

**Pull request merged**
