### PR TITLE
copr: Migrate scalar function `LpadUtf8` from TiDB

### LINKED ISSUE #6941: UCP: Migrate scalar function `LpadUTF8` from TiDB
## Description

Port the scalar function `LpadUTF8` from TiDB to coprocessor.

## Score 

* 50

## Mentor(s)

* @mapleFU 

## Recommended Skills

* Rust programming 

## Learning Materials

Already implemented expressions ported from TiDB

- https://github.com/tikv/tikv/tree/master/components/tidb_query/src/rpn_expr) 
- https://github.com/tikv/tikv/tree/master/components/tidb_query/src/expr)

### PR DESCRIPTION
**Pull request by hsqlu**
Signed-off-by: Qiannan Lyu <lvqiannan@gmail.com>

UCP: #6941 

### What problem does this PR solve?

Issue Number: close #6941 

Problem Summary: Migrate scalar function `LpadUtf8` from TiDB

### What is changed and how it works?

Implemented scalar function `LpadUtf8`

### Check List 

Tests 

- Unit test

### CODE REVIEW

**Comment by zhongzc** [comment]
PTAL @breeswish

**Comment by zhongzc** [comment]
Need to resolve conflicts. @hsqlu

**Comment by hsqlu** [comment]
@zhongzc PTAL

**Comment by zhongzc** [comment]
PTAL @sticnarf

**Pull request merged**
