### PR TITLE
Remove `extern crate` statements from the repo

### PR DESCRIPTION
**Pull request by wujunze**
## What have you changed? (mandatory)
. Optimize  Rust code
. makes some automated changes to be more idiomatic, in particular post-2018 edition

## What are the type of the changes? (mandatory)
Optimize  Rust code

- Improvement (change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)
Yes

## Does this PR affect documentation (docs) update? (mandatory)
No

## Does this PR affect tidb-ansible update? (mandatory)
No

## Refer to a related PR or issue link (optional)
https://github.com/tikv/tikv/issues/4196

about issue  https://github.com/tikv/tikv/issues/4196

### CODE REVIEW

**Comment by wujunze** [comment]
@siddontang    Please help me review this PR    Thanks

**Comment by rleungx** [comment]
@wujunze Thanks for your contribution! Please sign-off the DCO.

**Comment by rleungx** [comment]
BTW, could you try to remove all `extern crate` statement?

**Comment by zhangjinpeng1987** [comment]
@rleungx I think it doesn't matter, we can merge this first.

**Comment by wujunze** [comment]
> @wujunze Thanks for your contribution! Please sign-off the DCO.

 Thanks for your review I  sign-off the DCO.

**Comment by wujunze** [comment]
> @rleungx I think it doesn't matter, we can merge this first.

Thanks for your review !

**Comment by wujunze** [comment]
Please help me review   @zhangjinpeng1987   @rleungx   
Thanks

**Comment by brson** [comment]
LGTM Thanks @wujunze !

**Pull request merged**
