### PR TITLE
makefile: update cargo sort installation to remove dependency on rust-toolchain

### PR DESCRIPTION
**Pull request by Smityz**
### What is changed and how it works?

Issue Number: Close https://github.com/tikv/tikv/issues/15818

What's Changed:

```commit-message
 update cargo sort installation to remove dependency on rust-toolchain
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]
Thanks!

**Comment by Smityz** [comment]
need another one to approve 
/cc @disksing Hi master, could you please take a look~

**Comment by Smityz** [comment]
@disksing Hi master, could you please have a look?

**Review by glorv — APPROVED** [review]

**Review by LykxSassinator — APPROVED** [review]

**Pull request merged**
