### PR TITLE
*: add wait_log_truncated to simplify code

### PR DESCRIPTION
**Pull request by BusyJay**
### What is changed and how it works?

What's Changed:

There are a lot of duplicated code for waiting log truncation. So I add
a helper function to clean it up.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 
- No release note.

### CODE REVIEW

**Comment by hicqu** [comment]
Seems still some `get_truncated_state`s are left. Could you check it by `grep truncated_state`?

**Comment by hicqu** [comment]
After a recheck, there is still one left in `tests/failpoints/cases/test_replica_read.rs`.

**Review by NingLin-P — APPROVED** [review]
/LGTM

**Review by hicqu — APPROVED** [review]

**Pull request merged**
