### PR TITLE
call _exit instead of exit (#5053)

### PR DESCRIPTION
**Pull request by Connor1996**
## What have you changed? (mandatory)
Cherry-pick of #5053 

## What are the type of the changes? (mandatory)
- Bug fix (change which fixes an issue)

## How has this PR been tested? (mandatory)
No

## Does this PR affect documentation (docs) or release note? (mandatory)
No

## Does this PR affect tidb-ansible update? (mandatory)
No

### CODE REVIEW

**Comment by Connor1996** [comment]
/run-all-tests tidb=release-3.0 pd=release-3.0 tidb-test=release-3.0

**Comment by Connor1996** [comment]
PTAL @BusyJay @breeswish

**Comment by AndreMouche** [comment]
The test is faled by https://github.com/pingcap/tidb-test/pull/850

**Pull request merged**
