### PR TITLE
cdc: Clean rawkv resolved ts code

### PR DESCRIPTION
**Pull request by haojinming**
Signed-off-by: haojinming <jinming.hao@pingcap.com>

### What is changed and how it works?

Issue Number: Ref #13284 

What's Changed:

```
Rawkv resolved_ts is now implemented by ConcurrencyManager in https://github.com/tikv/tikv/pull/13326. remove the old implementation code.
This PR is mainly revert the change of PR https://github.com/tikv/tikv/pull/12866
```

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by zeminzhou — APPROVED** [review]
LGTM~

**Review by pingyu — APPROVED** [review]
LGTM~

**Pull request merged**
