### PR TITLE
*: output error code to error logs (#8595)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #8595 to release-4.0

---

Signed-off-by: 5kbpers <tangminghua@pingcap.com>

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:
Previously we defined error codes for each error, now we need to output it as a field of error logs.

### What is changed and how it works?

What's Changed:

output error code to error logs

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 
* N/A

### CODE REVIEW

**Comment by 5kbpers** [comment]
PTAL.
FYI, "min_specialization" is not supported by the rust version of release 4.0.

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by sticnarf — APPROVED** [review]

**Pull request merged**
