### PR TITLE
Do not panic when failed to write log.

### PR DESCRIPTION
**Pull request by divinerapier**
## What have you changed? (mandatory)
Just remove the panic! when failed to log.

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:
- Summarize your change (mandatory)
Do not panic when failed to write log

Please **NOTE** that:
- Do not assume reviewers understand the original issue

## What are the type of the changes? (mandatory)

- Bug fix (change which fixes an issue)
https://github.com/tikv/tikv/issues/5042

## How has this PR been tested? (mandatory)
manually tested

## Does this PR affect documentation (docs) or release note? (mandatory)
No.

## Does this PR affect tidb-ansible update? (mandatory)
No.

### CODE REVIEW

**Comment by sunxiaoguang** [comment]
LGTM

**Comment by siddontang** [comment]
@sunxiaoguang 

can we ensure that using this way can not introduce another problem, right?

**Comment by sunxiaoguang** [comment]
> @sunxiaoguang
> 
> can we ensure that using this way can not introduce another problem, right?

Unless log file is actually stored on partition where data dir resides. That way panic would make sense somehow. However RocksDB would report I/O error anyway when disk isn't working, it's just a matter of time before tikv-server actually panics.

**Pull request merged**
