### PR TITLE
[DNM] Find performance regression in ec264b

### PR DESCRIPTION
**Pull request by YangKeao**
Only used for benchmark and find out performance regression.

### CODE REVIEW

**Comment by YangKeao** [comment]
Benchmark after updating raft:

```diff
@@                               Benchmark Diff                               @@
================================================================================
tidb: 2ef6f46a6377dbaa045c9041b4ae797dc742a2ef
--- tikv: d6e86c59183217cbbf9a5ad8f707cf6f45ed4555
+++ tikv: 73690c8abc6ddd737a8659e96b9b9a07b5500812
pd: ca5cae673101cdec5a9f5dbbe7d4b6c8d4928977
================================================================================
test-1: < oltp_insert >
    * QPS : 21428.12 ± 0.3794% (std=56.29) delta: 0.17%
    * AvgMs : 11.94 ± 0.4188% (std=0.03) delta: -0.18%
    * PercentileMs99 : 43.39 ± 0.0000% (std=0.00) delta: 1.09%
            
test-2: < oltp_update_non_index >
    * QPS : 29665.54 ± 0.3292% (std=70.71) delta: 0.00%
    * AvgMs : 8.63 ± 0.3245% (std=0.02) delta: 0.09%
    * PercentileMs99 : 30.81 ± 0.0000% (std=0.00) delta: 1.82%
            
test-3: < oltp_read_write >
    * QPS : 37110.67 ± 0.3842% (std=90.50) delta: 0.22%
    * AvgMs : 138.50 ± 0.3625% (std=0.33) delta: -0.22%
    * PercentileMs99 : 257.95 ± 0.0000% (std=0.00) delta: 0.00%
            
test-4: < oltp_point_select >
    * QPS : 74242.98 ± 0.8335% (std=376.73) delta: -1.15%
    * AvgMs : 3.45 ± 0.9281% (std=0.02) delta: 1.23%
    * PercentileMs99 : 7.48 ± 1.0425% (std=0.06) delta: 0.70%
            
test-5: < oltp_update_index >
    * QPS : 17028.52 ± 0.8608% (std=109.89) delta: 0.01%
    * AvgMs : 15.03 ± 0.8515% (std=0.10) delta: 0.00%
    * PercentileMs99 : 48.86 ± 1.0683% (std=0.43) delta: 2.18%
            
```

**Comment by YangKeao** [comment]
I can confidently say new version of grpc leads to this performance regression. I will benchmark the old version (with only raft update) once again!

**Comment by zhouqiang-cl** [comment]
Close

**Pull request closed without merging**
