### PR TITLE
build: add missing failpoint feature for raft-engine

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: ref #15462

What's Changed:

```
Add missing raft_log_engine failpoint feature to fix fail_release build
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 
- Manual test
 - After this change `make fail_release` don't return build errror.

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by glorv** [comment]
@Connor1996 @overvenus PTAL

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by nolouch — APPROVED** [review]

**Review by LykxSassinator — APPROVED** [review]
Please clean the redundant import in `tests/Cargo.toml`.
https://github.com/tikv/tikv/blob/384aaeb381ffc8f9ac881432a00e437933777c55/tests/Cargo.toml#L44

**Review by LykxSassinator — APPROVED** [review]
LGTM

**Pull request merged**
