### PR TITLE
txn_types: Add assertion field to Mutation type

### PR DESCRIPTION
**Pull request by MyonKeminta**
### What is changed and how it works?

Ref pingcap/tidb#26833

What's Changed:
This PR adds the `Assertion` field to `Mutation` type, provides helper function to create instances without assertions, and update all usages of `Mutation` to use the helpers.

This PR is part of https://github.com/tikv/tikv/pull/10977 and split out since that PR is too large.

### Related changes

\-

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by cfzjywxk — APPROVED** [review]
LGTM

**Review by ekexium — APPROVED** [review]

**Comment by MyonKeminta** [comment]
?????

**Review by youjiali1995 — APPROVED** [review]

**Pull request merged**
