### PR TITLE
coprocessor, storage: Change error, panic, and log outputs from Debug to Display

### PR DESCRIPTION
**Pull request by spongedu**
## What have you changed? (mandatory)

for #4960 , change some error, panic, and log outputs from `Debug` to `Display` in `coprocessor` and `storage`

## What are the type of the changes? (mandatory)

- Misc (code refine)

## How has this PR been tested? (mandatory)

This pr just make some output format refine for log / error / panic output. I think it's ok to make the current test base happy.

### CODE REVIEW

**Comment by breeswish** [comment]
Looks that there is something wrong with GitHub status.. Maybe you need to push a new (empty) commit to trigger them...

**Comment by spongedu** [comment]
`DCO` failed although i've got a verified signature. Anything gots wrong here?

**Comment by breeswish** [comment]
@spongedu It requires you to sign off *all* commits. You may perform a rebase to solve it.

**Comment by spongedu** [comment]
@breeswish  OK.  PTAL :) @breeswish @rleungx

**Pull request merged**
