### PR TITLE
tests: fix flaky test_rate_limited_*_flow

### LINKED ISSUE #10303: Test test_rate_limited_hybrid_flow fails
https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/1790/pipeline#step-362-log-849

```
[2021-06-04T08:03:47.396Z] test rate_limiter::tests::test_rate_limited_hybrid_flow ... thread 'main' panicked at 'assertion failed: (write_bytes as f64) >=\n    ((write_work * bytes_per_sec / 100) as f64 * duration.as_secs_f64()) * 0.9', components/file_system/src/rate_limiter.rs:758:9

[2021-06-04T08:03:47.396Z] stack backtrace:

[2021-06-04T08:03:47.668Z]    0: rust_begin_unwind

[2021-06-04T08:03:47.668Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:493:5

[2021-06-04T08:03:47.668Z]    1: core::panicking::panic_fmt

[2021-06-04T08:03:47.668Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/panicking.rs:92:14

[2021-06-04T08:03:47.668Z]    2: core::panicking::panic

[2021-06-04T08:03:47.668Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/panicking.rs:50:5

[2021-06-04T08:03:47.668Z]    3: file_system::rate_limiter::tests::test_rate_limited_hybrid_flow

[2021-06-04T08:03:47.668Z]              at ./components/file_system/src/rate_limiter.rs:758:9

[2021-06-04T08:03:47.668Z]    4: file_system::rate_limiter::tests::test_rate_limited_hybrid_flow::{{closure}}

[2021-06-04T08:03:47.668Z]              at ./components/file_system/src/rate_limiter.rs:710:5

[2021-06-04T08:03:47.668Z]    5: core::ops::function::FnOnce::call_once

[2021-06-04T08:03:47.668Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5

[2021-06-04T08:03:47.668Z]    6: core::ops::function::FnOnce::call_once

[2021-06-04T08:03:47.668Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5

[2021-06-04T08:03:47.668Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2021-06-04T08:03:47.668Z] FAILED
```

### LINKED ISSUE #10306: Test test_rate_limited_light_flow fails
## Bug Report

https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/1806/pipeline#step-356-log-204

```
[2021-06-04T09:12:37.941Z] test rate_limiter::tests::test_rate_limited_light_flow ... thread 'main' panicked at 'assertion failed: (stats.fetch(IOType::Compaction, IOOp::Write) as f64) >=\n    (actual_kbytes_per_sec as f64 * duration.as_secs_f64() * 1000.0) * 0.9', components/file_system/src/rate_limiter.rs:703:9

[2021-06-04T09:12:37.941Z] stack backtrace:

[2021-06-04T09:12:38.241Z]    0: rust_begin_unwind

[2021-06-04T09:12:38.241Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:493:5

[2021-06-04T09:12:38.241Z]    1: core::panicking::panic_fmt

[2021-06-04T09:12:38.241Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/panicking.rs:92:14

[2021-06-04T09:12:38.241Z]    2: core::panicking::panic

[2021-06-04T09:12:38.241Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/panicking.rs:50:5

[2021-06-04T09:12:38.241Z]    3: file_system::rate_limiter::tests::test_rate_limited_light_flow

[2021-06-04T09:12:38.241Z]              at ./components/file_system/src/rate_limiter.rs:703:9

[2021-06-04T09:12:38.241Z]    4: file_system::rate_limiter::tests::test_rate_limited_light_flow::{{closure}}

[2021-06-04T09:12:38.241Z]              at ./components/file_system/src/rate_limiter.rs:682:5

[2021-06-04T09:12:38.241Z]    5: core::ops::function::FnOnce::call_once

[2021-06-04T09:12:38.241Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5

[2021-06-04T09:12:38.241Z]    6: core::ops::function::FnOnce::call_once

[2021-06-04T09:12:38.241Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5

[2021-06-04T09:12:38.241Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2021-06-04T09:12:38.241Z] FAILED
```

### PR DESCRIPTION
**Pull request by tabokie**
Signed-off-by: tabokie <xy.tao@outlook.com>

### What problem does this PR solve?

Issue Number: close #10303 close #10306

test_rate_limited_hybrid_flow and test_rate_limited_light_flow sometimes failed in rush hours.

### What is changed and how it works?

What's Changed:

Reduce number of threads spawned in test (from 6 to 3), and tune up tolerance (from 10% to 15%).

### Check List 

Tests 

- Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by tabokie** [comment]
> Could you take a look #10306 too?

@overvenus Both will be fixed here, they are both sensitive to the actual time slice being allocated to thread runner.

**Comment by tabokie** [comment]
2 out of 2 tries succeeded, I think we can call this a fix.

**Review by 5kbpers — APPROVED** [review]

**Comment by tabokie** [comment]
Seems yet another unstable test test_cpu_record has popped up ;(

**Pull request merged**
