### PR TITLE
build: disable fuzzer honggfuzz & afl on Windows

### PR DESCRIPTION
**Pull request by skyline75489**
### What problem does this PR solve?

Issue Number: Supports #9103 

Problem Summary:

### What is changed and how it works?

Disable fuzzer honggfuzz & afl on Windows because they do not support Windows.

What's Changed:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

- No release note

### CODE REVIEW

**Comment by andylokandy** [comment]
Cool. Did you make libfuzzer work on Windows?

**Comment by skyline75489** [comment]
@andylokandy Not really sure what you mean. I'm new to this project. This fix is based on what I found try `cargo check --all` on Windows. 

However even with the fix , `cargo check --all` will still fail because of the RocksDB C++ code won't compile on Windows. So this is kind of a first step thing.

**Comment by andylokandy** [comment]
I mean, since tikv now has three fuzzer backend, and you've disabled two of them, i I wonder why is the last one special?

**Review by gregwebs — APPROVED** [review]
Thanks for the contribution! I am wondering if you have been able to try WSL and if we can recommend that for Windows users?

**Comment by skyline75489** [comment]
@andylokandy The hongfuzz gives me this error:

```plaintext
compile_error!("honggfuzz-rs does not currently support Windows but works well under WSL (Windows Subsystem for Linux)");
```

And afl gives me this error:

```plaintext
error[E0433]: failed to resolve: could not find `BaseDirectories` in `xdg`
 --> C:\Users\skyline\.cargo\registry\src\github.com-1ecc6299db9ec823\afl-0.6.0\src\common.rs:9:10
  |
9 |     xdg::BaseDirectories::with_prefix(prefix).unwrap()
  |          ^^^^^^^^^^^^^^^ could not find `BaseDirectories` in `xdg`
```

So I disabled this two. Libfuzzer compiles with no problem. However I still cannot make `cargo check --all` work due to compilation error in `librocksdb_sys`. So I'm not really sure how to check if libfuzzer works normally.

@gregwebs Sorry I didn't try WSL 2 but I assume it should work. It's literally just a Linux VM. The reason why I don't use WSL is that you cannot utilize all the CPU & memory in WSL 2 because it's a VM. I wouldn't recommend WSL 2 for this kind of CPU-bound workload unless the person is really desperate and just wouldn't use barebone Linux.

**Comment by andylokandy** [comment]
I see. /lgtm

**Comment by andylokandy** [comment]
Plesse fix the DCO check.

**Comment by skyline75489** [comment]
@andylokandy Done. Hope the bot is happy. Happy new year 🎉

**Comment by andylokandy** [comment]
@skyline75489 Happy new year. >_o  BTW, are you interested in the [LFX program](https://github.com/tikv/tikv/issues/9103#issuecomment-772975074)?

**Comment by skyline75489** [comment]
@andylokandy The LFX is for college students, right? I have a job, though. And TBH I don't really know Rust. I'm just a random dude from the community that try to help out 😄

**Pull request merged**
