### PR TITLE
gc_worker: collect locks after applying (#8217)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #8217 to release-4.0

---

Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### What problem does this PR solve?

Issue Number: close https://github.com/tikv/tikv/issues/8211
Problem Summary:
See the issue.

### What is changed and how it works?

What's Changed:

Notifying lock observer after applying logs.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

* Fix the issue that green GC may miss locks during transferring regions.

### CODE REVIEW

**Comment by youjiali1995** [comment]
@sticnarf @MyonKeminta PTAL.

**Comment by youjiali1995** [comment]
@sticnarf @MyonKeminta PTAL.

**Review by sticnarf — COMMENTED** [review]
LGTM

**Review by MyonKeminta — APPROVED** [review]

**Pull request merged**
