### PR TITLE
raftstore: clean up legacy code for properties

### PR DESCRIPTION
**Pull request by Connor1996**
###  What have you changed?
clean up legacy code for properties, `SizeProperties` is deprecated since v2.1.

should merge #5537 first

###  What is the type of the changes?
- Engineering (engineering change which doesn't change any feature or fix any issue)

###  How is the PR tested?
No need

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?
No

###  Does this PR affect `tidb-ansible`?
No

### CODE REVIEW

**Comment by Connor1996** [comment]
PTAL @zhangjinpeng1987 @AndreMouche

**Comment by AndreMouche** [comment]
CI failed

**Pull request merged**
