### PR TITLE
(3.1) txn: Check lock's TTL when doing cleanup (#5471)

### PR DESCRIPTION
**Pull request by MyonKeminta**
###  What have you changed?

This PR cherry-picks #5471 , which is part of refinement of pessimistic transactions, to release-3.1 branch. For more details please view #5471 .

###  What is the type of the changes?

- New feature (a change which adds functionality)

###  How is the PR tested?

- Unit test
- Integration test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

- No.

###  Does this PR affect `tidb-ansible`?

No.

###  Refer to a related PR or issue link (optional)

* Cherry-picks: #5471

### CODE REVIEW

**Comment by MyonKeminta** [comment]
Also PTAL @coocood @tiancaiamao

**Comment by coocood** [comment]
LGTM

**Pull request merged**
