### PR TITLE
*: replace RocksIOLimiter by a pure-Rust async implementation, and eliminate the extra copies to memory when backing up a file

### PR DESCRIPTION
**Pull request by kennytm**
###  What have you changed?

Apply the changes discussed in https://github.com/tikv/tikv/pull/6209#issuecomment-565920185.

1. Removed `SstWriter::finish_into()` which copies the entire content into a `Vec<u8>`. Make it return the `Read`er instead.
2. Added a `Read` wrapper to calculate SHA-256 while reading a file.
3. `RocksIOLimiter` is naturally blocking, which is incompatible with `rusoto_core::ByteStream` which expects a non-blocking stream. Here all `RocksIOLimiter` usage for `backup` and `sst_importer` has been replaced by an external package, `async-speed-limit`, which was extracted and improved from TiKV-Importer's speed limiter. Nevertheless `ExternalStorage` still not yet `async`-compatible, thus `futures_executor::block_on` is currently used everywhere.

    ~~(`RocksIOLimiter` is also used outside of BR, which currently I'm not touching yet, so the interface still remains.)~~ 

4. Update: The `RocksIOLimiter` involved in `raftstore` and `gc_worker` are also removed, and thus the entire `IOLimiter` feature is removed from `engine_traits`.
5. Since `raftstore::{Snap, SnapManager}` originally become dependent on the KvEngine by #6196, this PR reverts the generalization of these two types. The trait `Snapshot<E>` is also split into the engine-independent part `GenericSnapshot` and the engine-dependent part `Snapshot<E>`.

###  What is the type of the changes?

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?

- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No

###  Does this PR affect `tidb-ansible`?

No

###  Refer to a related PR or issue link (optional)

Blocks #6209.

~~I'll move https://github.com/kennytm/async-speed-limit.git to tikv/ and publish to crates.io if this approach is accepted.~~

### CODE REVIEW

**Comment by kennytm** [comment]
cc @yiwu-arbug @overvenus @tennix

**Comment by overvenus** [comment]
LGTM, it would be appreciated if you can move async-speed-limit to tikv.org and contribute to crate.io.

**Comment by kennytm** [comment]
@overvenus Transferred to https://github.com/tikv/async-speed-limit. Okay to publish now?

**Comment by overvenus** [comment]
> @overvenus Transferred to https://github.com/tikv/async-speed-limit. Okay to publish now?

Sure! Please go ahead!

**Comment by kennytm** [comment]
PTAL @5kbpers cc @NingLin-P @MyonKeminta  (affects `gc_worker`). 

Seems to have decreased 0.61% performance on `oltp_read_write`?

/bench +tpch

**Comment by kennytm** [comment]
Looks like a significant speed regression, probably due to use of Mutex in `Limiter::consume()` or something else (any easy way to do the test locally for getting framegraphs?).

Do we fix it here and now or later? @5kbpers @overvenus

**Comment by 5kbpers** [comment]
@kennytm The benchmark result above shows the duration is decreased, I guess that means improvement.
Also the results of TPC-H from our benchbot are not always stable.😓

**Comment by kennytm** [comment]
@5kbpers Oh OK, confused with the sysbench result which reports QPS 😅

**Pull request merged**
