### PR TITLE
raftstore: record the noop entry message temporarily like pending_votes (#8820)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #8820 to release-4.0

---

### What problem does this PR solve?

Problem Summary:

The learner of a new split region may not know its leader if it applies log slowly and drops the no-op entry from the new leader, and it had to wait for a heartbeat timeout to know its leader, and before that it can't handle any read request.

### What is changed and how it works?

What's Changed:
Record the noop entry temporarily like previously we do with `pending_votes`, and send the message again after the peer is created.

### Check List 

Tests 

- Integration test

### Release note 
- raftstore: record the noop entry message temporarily like pending_votes

### CODE REVIEW

**Comment by solotzg** [comment]
lgtm

**Comment by solotzg** [comment]
@gengliqi

**Review by gengliqi — APPROVED** [review]
LGTM

**Review by 5kbpers — APPROVED** [review]

**Pull request merged**
