### PR TITLE
make read quota limiter work for coprocessor as well (#13257)

### LINKED ISSUE #13256: QuotaLimiter: coprocessor read traffic should be controlled by foreground quota limiter's read bytes
### What version of TiKV are you using?
6.0 or later

### Steps to reproduce
set tikv config: quota.foreground_read_bytes: 5MB
run sysbench read-only workload

### What did you expect?
The coprocessor's read response size is close to 5MB/s per tikv
### What did happened?
The coprocessor's read response size is much larger than 5MB/s

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #13257 to release-6.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/13324
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/13324:release-6.1-252b44288c7e
```

---

Signed-off-by: qi.xu <tonxuqi@outlook.com>

### What is changed and how it works?

Issue Number: Close #13256

What's Changed:

```commit-message
The coprocessor's read bytes are not calculated by foreground quota limiter. 
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Manual test 

Side effects
- None

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tonyxuqqi — APPROVED** [review]

**Review by BusyJay — APPROVED** [review]

**Comment by you06** [comment]
@BusyJay Can you help merge this PR?

**Pull request merged**
