### PR TITLE
resource_control: enable by default

### PR DESCRIPTION
**Pull request by nolouch**
### What is changed and how it works?

Issue Number: Close https://github.com/tikv/tikv/issues/14353

What's Changed:
plan GA in 7.0

```commit-message
resource_control: enable resource control by default
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - performance may regression, <3%
    

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by nolouch** [comment]
ptal @kevin-xianliu

**Review by glorv — APPROVED** [review]
LGTM

**Review by Connor1996 — APPROVED** [review]
LGTM, and please make sure related docs are updated

**Comment by nolouch** [comment]
> LGTM, and please make sure related docs are updated

I will update the docs about the changes in 7.0 about resource control later.

**Pull request merged**
