### PR TITLE
Enable perf-level mutex by default

### PR DESCRIPTION
**Pull request by Little-Wallace**
Signed-off-by: Little-Wallace <bupt2013211450@gmail.com>

### What problem does this PR solve?

Help user investigate performance problem better.

### What is changed and how it works?

Show duration of each step of `RocksDB::Write`.

### Related changes

- PR to update `pingcap/tidb-ansible`:

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

Side effects

- Performance regression

### Release note 

- No release note

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
I think it should be off by default.

**Comment by Connor1996** [comment]
@yiwu-arbug seems bench doesn't work

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by yiwu-arbug** [comment]
Still waiting for benchbot ready to run a simple bench.

**Comment by yiwu-arbug** [comment]
benchbot job: feature-sysbench-benching-6gw8c

**Comment by yiwu-arbug** [comment]
sysbench dataset: sysbench-32-10000000
command:
```
sysbench oltp_{method} run --db-driver=mysql --tables=32 --table-size=10000000 --mysql-db=test --threads=800 --time=300 --report-interval=10
```

Result:
QPS,master,perf_context,diff
read_write,3344,3390,1.38%
update_index,24015,25315,5.41%
update_non_index,55697,55709,0.02%
point_select,161452,158679,-1.72%
insert,31550,31837,0.91%
,,,
avg,master,perf_context,diff
read_write,238.89,235.63,-1.36%
update_index,33.05,31.59,-4.42%
update_non_index,14.36,14.36,0.00%
point_select,4.95,5.04,1.82%
insert,25.35,25.12,-0.91%
,,,
p95,master,perf_context,diff
read_write,369.77,356.7,-3.53%
update_index,77.19,69.29,-10.23%
update_non_index,28.16,28.16,0.00%
point_select,11.24,11.45,1.87%
insert,56.84,49.21,-13.42%

No noticeable regression

**Review by yiwu-arbug — APPROVED** [review]

**Pull request merged**
