### PR TITLE
server: fix panic when a NIC doesn't have a mac address again

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve?

Problem Summary:

TiKV panics when the `server_info` gRPC method of the Diagnostic service is invoked, when there exists a NIC with no MAC address (e.g. PTP interfaces).

### What is changed and how it works?

What's Changed:

This PR reapplies #7942, which when the cherry-pick PR #8939 refactored this part of code causes the change to be lost.

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)
   * See #7942.

Side effects

### Release note 

* Fixes a crash problem when running a TiKV on a machine with a network interface lacking MAC address since v4.0.9.

### CODE REVIEW

**Comment by sticnarf** [comment]
@breeswish I don't have the permission to approve. Please find someone else in the diagnosis sig...

**Review by breeswish — APPROVED** [review]

**Comment by breeswish** [comment]
@crazycs520 PTAL

**Comment by iosmanthus** [comment]
LGTM

**Review by crazycs520 — APPROVED** [review]
lgtm

**Pull request merged**
