### PR TITLE
copr: add suspend time into tracker (#9257)

### LINKED ISSUE #9223: slow-query information is not accuracy
### What version of TiKV are you using?

Config: disable the cop-cache in TiDB.

```toml
[tikv-client.copr-cache]
enable = false
```

```sql
information_schema> select * from cluster_info;
+------+----------------------+-----------------------+--------------+------------------------------------------+---------------------------+--------------+-----------+
| TYPE | INSTANCE             | STATUS_ADDRESS        | VERSION      | GIT_HASH                                 | START_TIME                | UPTIME       | SERVER_ID |
+------+----------------------+-----------------------+--------------+------------------------------------------+---------------------------+--------------+-----------+
| tidb | 192.168.220.171:4000 | 192.168.220.171:10080 | 4.0.0-beta.2 | 0e76bd3f0462f2fb9d877e220c44cdc14a8a907c | 2020-12-11T15:38:45+08:00 | 57.671729s   | 1964616   |
| pd   | 127.0.0.1:2379       | 127.0.0.1:2379        | 4.1.0-alpha  | 3ebd9cb4306a001de1350ca4fd1b1e9875e6c7cd | 2020-12-11T15:38:29+08:00 | 1m13.671734s | 0         |
| tikv | 127.0.0.1:20160      | 127.0.0.1:20180       | 4.1.0-alpha  | 1df1cadad7e0472f5d0f6d7024bcb5102630dc08 | 2020-12-11T15:38:36+08:00 | 1m6.671736s  | 0         |
| tikv | 127.0.0.1:20164      | 127.0.0.1:20184       | 4.1.0-alpha  | 1df1cadad7e0472f5d0f6d7024bcb5102630dc08 | 2020-12-11T15:38:36+08:00 | 1m6.671737s  | 0         |
| tikv | 127.0.0.1:20162      | 127.0.0.1:20182       | 4.1.0-alpha  | 1df1cadad7e0472f5d0f6d7024bcb5102630dc08 | 2020-12-11T15:38:36+08:00 | 1m6.671739s  | 0         |
| tikv | 127.0.0.1:20161      | 127.0.0.1:20181       | 4.1.0-alpha  | 1df1cadad7e0472f5d0f6d7024bcb5102630dc08 | 2020-12-11T15:38:36+08:00 | 1m6.67174s   | 0         |
| tikv | 127.0.0.1:20163      | 127.0.0.1:20183       | 4.1.0-alpha  | 1df1cadad7e0472f5d0f6d7024bcb5102630dc08 | 2020-12-11T15:38:36+08:00 | 1m6.671742s  | 0         |
+------+----------------------+-----------------------+--------------+------------------------------------------+---------------------------+--------------+-----------+
```

### What operating system and CPU are you using?

AMD 3900, macos 

### Steps to reproduce

1.  Prepare test data. Create folowing table and insert 1000000 rows.
```sql
stress_test> show create table t_cop\G
***************************[ 1. row ]***************************
Table        | t_cop
Create Table | CREATE TABLE `t_cop` (
  `id` int(11) NOT NULL,
  `name` varchar(10) DEFAULT NULL,
  `count` bigint(20) DEFAULT NULL,
  `age` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
1 row in set
Time: 0.005s
stress_test> select * from t_cop limit 3;
+----+------------+-------+-----+
| id | name       | count | age |
+----+------------+-------+-----+
| 0  | aaaaaaaaaa | 0     | 0   |
| 1  | bbbbbbbbbb | 1     | 1   |
| 2  | cccccccccc | 2     | 2   |
+----+------------+-------+-----+
3 rows in set
Time: 0.020s
stress_test> select count(*) from t_cop; --total rows is 1000000
+----------+
| count(*) |
+----------+
| 1000000  |
+----------+
1 row in set
Time: 0.067s
stress_test>
```

2. use 100 clients to concurrently execute the following SQL:

```sql
select sum(id*count*age) from t_cop;
```

Then check the TiKV log to find `slow-query` such as below:

```sql
[2020/12/11 15:40:24.667 +08:00] [INFO] [tracker.rs:221] [slow-query] [perf_stats.internal_delete_skipped_count=5625] [perf_stats.internal_key_skipped_count=105625] [perf_stats.block_read_byte=0] [perf_stats.block_read_count=0] [perf_stats.block_cache_hit_count=86] [scan.range.first="Some(start: 7480000000000000335F72800000000007A120 end: 7480000000000000335F7280000000000927C0)"] [scan.ranges=1] [scan.total=100001] [scan.processed=100000] [scan.is_desc=false] [tag=select] [table_id=51] [txn_start_ts=421441679422128130] [total_process_time=107ms] [handler_build_time=0ns] [wait_time.snapshot=0ns] [wait_time.schedule=0ns] [wait_time=0ns] [total_lifetime=2.035s] [remote_host=ipv4:127.0.0.1:60754] [region_id=137]
```

As you can see:

```sql
[total_process_time=107ms] 
[handler_build_time=0ns] 
[wait_time.snapshot=0ns] 
[wait_time.schedule=0ns] 
[wait_time=0ns] 
[total_lifetime=2.035s] 
```

`total_lifetime` is 2.035s, `total_process_time` is `107ms`, **Where is rest time?**

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #9257 to release-4.0

---

Signed-off-by: Zhenchi <zhongzc_arch@outlook.com>

### What problem does this PR solve?

Issue Number: close #9223

Problem Summary:

With a high read load, runtime schedules cop tasks heavily. To ensure fairness, every task will be executed for a while then yield out and wait for the next execution. Previously, the process time is recorded but not for the suspend time.

### What is changed and how it works?

Record suspend time.

### Check List 

Tests 

- Unit test

### Release note
- Record suspend time for coprocessor task

### CODE REVIEW

**Review by breeswish — APPROVED** [review]

**Review by Xuanwo — APPROVED** [review]

**Comment by hi-rustin** [comment]
This cherry pick PR is for a release branch and has not yet been approved by release team.
Adding the `do-not-merge/cherry-pick-not-approved` label.
To merge this cherry pick, it must first be approved (`/lgtm` + `/merge`) by the collaborators.
**AFTER** it has been approved by collaborators, please ping the release team in a comment to request a cherry pick review.

/label do-not-merge/cherry-pick-not-approved

**Comment by hi-rustin** [comment]
/label do-not-merge/cherry-pick-not-approved

This cherry pick PR is for a release branch and has not yet been approved by release team.
Adding the `do-not-merge/cherry-pick-not-approved` label.
To merge this cherry pick, it must first be approved (`/lgtm` + `/merge`) by the collaborators.
**AFTER** it has been approved by collaborators, please ping the release team in a comment to request a cherry pick review.

**Comment by hi-rustin** [comment]
/label do-not-merge/cherry-pick-not-approved

This cherry pick PR is for a release branch and has not yet been approved by release team.
Adding the do-not-merge/cherry-pick-not-approved label.
To merge this cherry pick, it must first be approved (/lgtm + /merge) by the collaborators.
AFTER it has been approved by collaborators, please ping the release team in a comment to request a cherry pick review.

**Comment by hi-rustin** [comment]
/label do-not-merge/cherry-pick-not-approved

This cherry pick PR is for a release branch and has not yet been approved by release team.
Adding the do-not-merge/cherry-pick-not-approved label.
To merge this cherry pick, it must first be approved (/lgtm + /merge) by the collaborators.
AFTER it has been approved by collaborators, please ping the release team in a comment to request a cherry pick review.

**Comment by hi-rustin** [comment]
This cherry pick PR is for a release branch and has not yet been approved by release team.
Adding the `do-not-merge/cherry-pick-not-approved` label.

To merge this cherry pick, it must first be approved (`/lgtm` + `/merge`) by the collaborators.

**AFTER** it has been approved by collaborators, please ping the release team in a comment to request a cherry pick review.

**Comment by breeswish** [comment]
@hi-rustin How can I "ping the release team"?

**Comment by hi-rustin** [comment]
> @hi-rustin How can I "ping the release team"?

/cc @tikv/qa-release-merge

**Comment by hi-rustin** [comment]
> @hi-rustin How can I "ping the release team"?

Perhaps it would be better to change this description to send an email request for approval.
@jebter What do you think?

**Comment by hi-rustin** [comment]
Improve it in https://github.com/ti-community-infra/configs/pull/99

**Comment by breeswish** [comment]
@hi-rustin How about allowing approval before QA / release approve? Since usually code review happens first, then it comes to the release review.

**Comment by hi-rustin** [comment]
> @hi-rustin How about allowing approval before QA / release approve? Since usually code review happens first, then it comes to the release review.

To merge this cherry pick, it must first be approved (/lgtm + /merge) by the collaborators.

**AFTER** it has been approved by collaborators, please send an email to the QA team requesting approval and the QA team will help you merge the PR.


You can `/lgtm` and `/merge`, and the `do-not-merge/cherry-pick-not-approved` label will help you stop pr merging before the qa team agrees.

**Comment by breeswish** [comment]
> > @hi-rustin How about allowing approval before QA / release approve? Since usually code review happens first, then it comes to the release review.
> 
> To merge this cherry pick, it must first be approved (/lgtm + /merge) by the collaborators.
> 
> **AFTER** it has been approved by collaborators, please send an email to the QA team requesting approval and the QA team will help you merge the PR.
> 
> You can `/lgtm` and `/merge`, and the `do-not-merge/cherry-pick-not-approved` label will help you stop pr merging before the qa team agrees.

@hi-rustin Hi, is this message a mistake? We require neither QA team's approval, nor release manager's approval to merge a bug fix PR in the non code freeze stage. The author can simply merge the PR by himself after 2 LGTM is received. How can we merge this PR now?

**Comment by jebter** [comment]
> > > @hi-rustin How about allowing approval before QA / release approve? Since usually code review happens first, then it comes to the release review.
> > 
> > 
> > To merge this cherry pick, it must first be approved (/lgtm + /merge) by the collaborators.
> > **AFTER** it has been approved by collaborators, please send an email to the QA team requesting approval and the QA team will help you merge the PR.
> > You can `/lgtm` and `/merge`, and the `do-not-merge/cherry-pick-not-approved` label will help you stop pr merging before the qa team agrees.
> 
> @hi-rustin Hi, is this message a mistake? We require neither QA team's approval, nor release manager's approval to merge a bug fix PR in the non code freeze stage. The author can simply merge the PR by himself after 2 LGTM is received. How can we merge this PR now?

This pr was cherry picked during the code freeze period, and it was automatically marked with do-not-merge/cherry-pick-not-approved.I'll deal with it

**Comment by breeswish** [comment]
@jebter Sounds like we should change the bot's behaviour. The code freeze only affects when PR can be **merged**, instead of when PR is **proposed**. /cc @hi-rustin

**Comment by jebter** [comment]
> @jebter Sounds like we should change the bot's behaviour. The code freeze only affects when PR can be **merged**, instead of when PR is **proposed**. /cc @hi-rustin

Agree with you

**Pull request merged**
