### PR TITLE
metrics/grafana: fix two heatmap panel issues

### LINKED ISSUE #17586: heatmap panel should use increase instead of rate
https://github.com/tikv/tikv/blob/e6b3613ec8b689a3ed3ce5a8380490f0a9eca3c9/metrics/grafana/common.py#L919
image
image

Otherwise you will get `count/$__rate_interval` instead of real count

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close #17586

What's Changed:

```commit-message
* Show heatmap tooltip. Cherry-picked from broxus/grafana-builder#5c9e8965
* Replace `rate` with `increase` in heatmap query expression.
  Cherry-picked from https://github.com/broxus/grafana-builder/pull/1
```

These two fixes are cherry-picked from the [broxus/grafana-builder](https://github.com/broxus/grafana-builder) project, thank you @0xdeafbeef and @Rexagon!

### Check List

Tests 

- Manual test
{BF025BFA-684F-4EE4-A8D8-897896122EC5}

Tooltip and count are correctly displayed.

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by 0xdeafbeef** [comment]
Also, using `increase[scrape interval]` instead of `$__rate_interval` gives more realistic distribution.
Screenshot from 2024-09-27 11-49-18

image

**Comment by overvenus** [comment]
I see, thanks for the reminder!

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by v01dstar — APPROVED** [review]
lgtm

**Review by SpadeA-Tang — APPROVED** [review]

**Pull request merged**
