### PR TITLE
log-backup: added check leader call before flushing

### LINKED ISSUE #14099: PiTR resolved ts is not reliable and may lost data in extreme cases
## Bug Report

PiTR advances resolved ts without checking leadership. It may advance resolved ts mistakenly on an old leader whose is partitioned from other peers and there is new leader has elected.
A wrong resolved ts may cause PiTR advance checkpoint wrongly which may lost data.

### What version of TiKV are you using?

v6.5.0

### PR DESCRIPTION
**Pull request by YuJuncen**
### What is changed and how it works?

Issue Number: Close #14099

What's Changed:
This PR added leader resolver to the log backup, it would check the leadership while doing resolving for preventing stale leader advances resolved ts to wrong place.

```commit-message
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
Fixed a bug that may cause data loss when PITR meet partial network partition (only messages between TiKVs are blocked).
```

### CODE REVIEW

**Comment by YuJuncen** [comment]
image

The throughput of check leader is reasonable.

The throughput was calculated roughly by this patch:
<details>

```patch
diff --git a/components/backup-stream/src/subscription_manager.rs b/components/backup-stream/src/subscription_manager.rs
index a31a43980..1bf47e1cf 100644
--- a/components/backup-stream/src/subscription_manager.rs
+++ b/components/backup-stream/src/subscription_manager.rs
@@ -461,7 +461,7 @@ where
                             "take" => ?now.saturating_elapsed(), "timedout" => %timedout);
                     }
                     let regions = leader_checker
-                        .resolve(self.subs.current_regions(), min_ts)
+                        .resolve(self.subs.current_regions(), min_ts, "pitr")
                         .await;
                     let cps = self.subs.resolve_with(min_ts, regions);
                     let min_region = cps.iter().min_by_key(|rs| rs.checkpoint);
diff --git a/components/cdc/src/endpoint.rs b/components/cdc/src/endpoint.rs
index 6d64754d0..e98fd6007 100644
--- a/components/cdc/src/endpoint.rs
+++ b/components/cdc/src/endpoint.rs
@@ -1074,7 +1074,7 @@ impl<T: 'static + RaftStoreRouter<E>, E: KvEngine> Endpoint<T, E> {
             let regions =
                 if hibernate_regions_compatible && gate.can_enable(FEATURE_RESOLVED_TS_STORE) {
                     CDC_RESOLVED_TS_ADVANCE_METHOD.set(1);
-                    leader_resolver.resolve(regions, min_ts).await
+                    leader_resolver.resolve(regions, min_ts, "cdc").await
                 } else {
                     CDC_RESOLVED_TS_ADVANCE_METHOD.set(0);
                     leader_resolver
diff --git a/components/resolved_ts/src/advance.rs b/components/resolved_ts/src/advance.rs
index a78e903bc..80bc37629 100644
--- a/components/resolved_ts/src/advance.rs
+++ b/components/resolved_ts/src/advance.rs
@@ -110,7 +110,9 @@ impl AdvanceTsWorker {
                 }
             }
 
-            let regions = leader_resolver.resolve(regions, min_ts).await;
+            let regions = leader_resolver
+                .resolve(regions, min_ts, "advance_ts_worker")
+                .await;
             if !regions.is_empty() {
                 if let Err(e) = scheduler.schedule(Task::ResolvedTsAdvanced {
                     regions,
@@ -248,7 +250,12 @@ impl LeadershipResolver {
     // This function broadcasts a special message to all stores, gets the leader id
     // of them to confirm whether current peer has a quorum which accepts its
     // leadership.
-    pub async fn resolve(&mut self, _regions: Vec<u64>, min_ts: TimeStamp) -> Vec<u64> {
+    pub async fn resolve(
+        &mut self,
+        _regions: Vec<u64>,
+        min_ts: TimeStamp,
+        label: &'static str,
+    ) -> Vec<u64> {
         // Clear previous result before resolving.
         self.clear();
         // GC when necessary to prevent memory leak.
@@ -358,6 +365,9 @@ impl LeadershipResolver {
                         .observe(elapsed.as_secs_f64());
                 });
 
+                RTS_CHECK_LEADER_CLIENT_THROUGHPUT
+                    .with_label_values(&["out", label])
+                    .inc_by(req.compute_size() as _);
                 let rpc = match client.check_leader_async(req) {
                     Ok(rpc) => rpc,
                     Err(GrpcError::RpcFailure(status))
@@ -376,6 +386,10 @@ impl LeadershipResolver {
                     .map_err(|e| (to_store, true, format!("[timeout] {}", e)))
                     .await?
                     .map_err(|e| (to_store, true, format!("[rpc failed] {}", e)))?;
+                RTS_CHECK_LEADER_CLIENT_THROUGHPUT
+                    .with_label_values(&["in", label])
+                    .inc_by(resp.compute_size() as _);
+
                 Ok((to_store, resp))
             }
             .boxed();
diff --git a/components/resolved_ts/src/metrics.rs b/components/resolved_ts/src/metrics.rs
index 3ec35685c..9a092d526 100644
--- a/components/resolved_ts/src/metrics.rs
+++ b/components/resolved_ts/src/metrics.rs
@@ -113,4 +113,10 @@ lazy_static! {
         "The minimal (non-zero) resolved ts gap for observe leader peers"
     )
     .unwrap();
+    pub static ref RTS_CHECK_LEADER_CLIENT_THROUGHPUT: IntCounterVec = register_int_counter_vec!(
+        "tikv_resolved_ts_check_leader_client_throughput",
+        "The estimated throughput of check leader RPCs by the size of requests / responses.",
+        &["direction", "caller"],
+    )
+    .unwrap();
 }
```
</details>

**Review by overvenus — APPROVED** [review]

**Review by Leavrth — APPROVED** [review]

**Review by 3pointer — APPROVED** [review]

**Comment by YuJuncen** [comment]
```
[2023-02-02T03:43:57.587Z]   TRY 3 FAIL [   3.367s] cdc::failpoints test_endpoint::test_cdc_rawkv_resolved_ts
[2023-02-02T03:43:57.587Z]   TRY 3 FAIL [   6.719s] tests::failpoints cases::test_witness::test_non_witness_replica_read
[2023-02-02T03:43:57.588Z]   TRY 3 FAIL [   9.349s] tests::integrations raftstore::test_split_region::test_node_split_region_after_reboot_with_config_change
[2023-02-02T03:43:57.588Z]   TRY 3 FAIL [   2.956s] tests::integrations server::raft_client::test_tombstone_block_list
```

Even this PR is relative to the stale read, I don't think it would modify the stale read status during reading the code.
Let's try again.
/run-test

**Pull request merged**
