### PR TITLE
ctl: should check column family name validation when scan data using ctl

### LINKED ISSUE #11268: Wrong column family name should panic when use tikv control to scan data
### What version of TiKV are you using?

Master 

### Steps to reproduce

```
./tikv-ctl --log-level info --data-dir /tmp/data/tikv-0/data scan --from "zm" --limit 1 --show-cf lock,default,write1
```

Attention `write1` does not exist
### What did you expect?

**Should explicit show that write1 does not exsits**

### What did happened?
```
[2021/11/05 19:43:13.864 +08:00] [INFO] [mod.rs:118] ["encryption: none of key dictionary and file dictionary are found."]
[2021/11/05 19:43:13.864 +08:00] [INFO] [mod.rs:479] ["encryption is disabled."]
[2021/11/05 19:43:13.864 +08:00] [WARN] [config.rs:317] ["Memory allocator nodump is not supported, continue with default allocator"]
[2021/11/05 19:43:13.865 +08:00] [WARN] [config.rs:587] ["compaction guard is disabled due to region info provider not available"]
[2021/11/05 19:43:13.865 +08:00] [WARN] [config.rs:682] ["compaction guard is disabled due to region info provider not available"]
key: zmBootstr\377a\377pKey\000\000\377\000\000\373\000\000\000\000\000\377\000\000s\000\000\000\000\000\372
```

### PR DESCRIPTION
**Pull request by yuqi1129**
close #11268
Signed-off-by: yuqi1129 <yuqi4733@gmail.com>

### What problem does this PR solve?

Issue Number: close #11268 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
 None
```

### CODE REVIEW

**Comment by yuqi1129** [comment]
Test `test_server_transfer_leader_safe ` is not very stable

**Review by tabokie — APPROVED** [review]

**Review by Connor1996 — APPROVED** [review]
LGTM

**Pull request merged**
