### PR TITLE
copr: Vectorize FloorIntToDec

### PR DESCRIPTION
**Pull request by koushiro**
Signed-off-by: koushiro <koushiro.cqx@gmail.com>

PCP #5751

###  What have you changed?

Vectorize FloorIntToDec

###  What is the type of the changes?

- Improvement 

###  How is the PR tested?

- Unit test
- Integration test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No

###  Does this PR affect `tidb-ansible`?

No

### CODE REVIEW

**Comment by koushiro** [comment]
@sre-bot /run-integration-copr-test

**Comment by iosmanthus** [comment]
@andylokandy PTAL

**Comment by koushiro** [comment]
@sre-bot /merge

**Pull request merged**
