### PR TITLE
Cherry pick #4921

### PR DESCRIPTION
**Pull request by breeswish**
Signed-off-by: Breezewish <breezewish@pingcap.com>

## What have you changed? (mandatory)

This PR cherry picks #4921 to master.

### CODE REVIEW

**Comment by breeswish** [comment]
/run-integration-compatibility-test tidb=release-3.0 pd=release-3.0

**Comment by BusyJay** [comment]
If tikv-ctl doesn't support hex input, I would suggest not to publish it for GA. It's a bad experience for users to always decode hex key for practical commands.

**Comment by breeswish** [comment]
@BusyJay We are already outputting many kind of keys as hex in TiKV instead of escaped format. Also all keys are already outputted in hex in pd and TiDB.

**Comment by breeswish** [comment]
/run-integration-compatibility-test tidb=release-3.0 pd=release-3.0

**Comment by hicqu** [comment]
@BusyJay tikv-ctl can escape keys easily, so I guess it's ok to use hex format in GA.

**Comment by BusyJay** [comment]
> We are already outputting many kind of keys as hex in TiKV instead of escaped format. Also all keys are already outputted in hex in pd and TiDB.

Doesn't it mean the user experience has been terrible for a long time? This change makes it worse as an extra step becomes a must.

> tikv-ctl can escape keys easily, so I guess it's ok to use hex format in GA.

People have to call hex-to-escaped before actually running any commands, it works but terribly.

**Comment by breeswish** [comment]
@BusyJay The root cause is not we output keys in hex, instead it is tikv-ctl does not *directly* support hex keys.

**Comment by BusyJay** [comment]
Yes, that's exactly what I'm suggesting to fix.

**Pull request merged**
