### PR TITLE
config: fix invalid advertise-status-addr (#8875)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #8875 to release-4.0

---

Signed-off-by: linning <linningde25@gmail.com>

### What problem does this PR solve?

Problem Summary:

Previously, in order to keep compatibility with tidb-operator and according to @cofyc 's suggestion:
> - If --advertise-status-addr is specified, validates it's not a wildcard address as it will be reported to PD
> - If --advertise-status-addr is not specified, to keep compatible with 4.0.0, we can fallback to --status-addr but don't validate it's not a wildcard address as it's the address tikv-server listens on. The address reported to PD is unusable if people use wildcard address in --status-addr, but they can use --advertise-status-addr to report status address after the upgrade.

But there is a problem when `advertise-status-addr` fall back to `status-addr` and `status-addr` is start with `0.0.0.0`, if we call `config::validate` more than once, an error will return because `advertise-status-addr` is not empty and start with `0.0.0.0`. This may cause TiKV failed to update config online, because it will call `config::validate` before update any config.

### What is changed and how it works?

What's Changed:

Don't fall back to `status-addr` if it starts with `0.0.0.0`, because it is an invalid `advertise-status-addr` and is useless

### Check List 

Tests 

- Unit test

### Release note 
- config: fix invalid advertise-status-addr

### CODE REVIEW

**Comment by NingLin-P** [comment]
PTAL @rleungx @overvenus

**Review by rleungx — APPROVED** [review]
LGTM

**Comment by overvenus** [comment]
LGTM

**Review by BusyJay — APPROVED** [review]

**Pull request merged**
