### PR TITLE
[WIP] Titan blob GC by merge

### PR DESCRIPTION
**Pull request by tabokie**
tikv/titan#121

###  What have you changed?

Please explain in detail what the changes are in this PR and why they are needed:

- Summarize your change
- How does this PR work? Include a brief introduction for any changed logic (optional)
- Separately describe each logical change (optional)
- Describe any limitations of the current code (optional)

Don't assume reviewers understand the original issue.

###  What is the type of the changes?

- New feature (a change which adds functionality)
- Improvement (a change which is an improvement to an existing feature)
- Bugfix (a change which fixes an issue)
- Engineering (engineering change which doesn't change any feature or fix any issue)
- Misc (other changes)

###  How is the PR tested?

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### CODE REVIEW

**Comment by tabokie** [comment]
/bench
```
workload:
  threads: 512
```

**Comment by tabokie** [comment]
@sre-bot /run-all-test

**Comment by tabokie** [comment]
@sre-bot /run-all-tests

**Comment by tabokie** [comment]
@sre-bot /bench

**Comment by tabokie** [comment]
@sre-bot /release make dist_release

**Comment by tabokie** [comment]
@sre-bot /release

**Comment by tabokie** [comment]
@sre-bot /run-integration-test

**Comment by tabokie** [comment]
@sre-bot /run-integration-tests

**Comment by tabokie** [comment]
@sre-bot /bench

**Comment by tabokie** [comment]
@sre-bot /bench
```
workload:
  threads: 1024
```

**Comment by Connor1996** [comment]
@sre-bot /bench
```
workload:
  threads: 512
```

**Pull request closed without merging**
