### PR TITLE
[DNM] New Row Format

### PR DESCRIPTION
**Pull request by breeswish**
###  What have you changed?

This PR is based on https://github.com/tikv/tikv/pull/6132, contains some correctness fixes for testing.

###  What is the type of the changes?

- New feature (a change which adds functionality)

###  How is the PR tested?

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### CODE REVIEW

**Comment by lysu** [comment]
/bench tidb=pr/12634
```
workload:
  threads: 256
  repeat_time: 4
  benchtime: 240
  prepare: true
```

**Comment by lysu** [comment]
/bench tidb=pr/12634
```
workload:
  threads: 128
  prepare: true
```

**Comment by breeswish** [comment]
Close in favor of https://github.com/tikv/tikv/pull/6132

**Pull request closed without merging**
