### PR TITLE
txn: don't pass latches in when gen_lock()

### PR DESCRIPTION
**Pull request by andylokandy**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

`latches` is not used when `gen_lock()`

### What is changed and how it works?

remove `latches` when `gen_lock()`

### Release note 

- No release note

### CODE REVIEW

**Review by sticnarf — APPROVED** [review]
LGTM

**Review by longfangsong — APPROVED** [review]
/lgtm

**Pull request merged**
