### PR TITLE
remove community meetings' info

### PR DESCRIPTION
**Pull request by WT-Liu**
Signed-off-by: Wenting Liu <liuwenting@pingcap.com>

### What problem does this PR solve?

Problem Summary:
Running community meetings for a few months, we found the attendance from the community was not so ideal to serve its intended purpose, which was to make the TiKV community more transparent, open in communication and collaboration. 

Proposal: 
Until we come up with better planning and arrangements, we will cancel the recurring meetings indefinitely and call in a meeting when there are major issues to discuss. Also, Slack channels are always open to discuss features, issues and other project updates with contributors and adopters.

What's Changed:
Remove community meetings' info

### Related changes

- N/A

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- N/A

### Release note 
- No release note

### CODE REVIEW

**Comment by WT-Liu** [comment]
@BusyJay @youjiali1995 @andylokandy PTAL and thanks!

**Review by BusyJay — COMMENTED** [review]
So how can community find latest updates from TiKV project?

**Comment by andylokandy** [comment]
> So how can community find latest updates from TiKV project?

The mail list I think.

To be honest. I'd like to open the Github Discussion so that we can post TiKV weekly on it.

**Comment by WT-Liu** [comment]
> So how can community find latest updates from TiKV project?
I think we can keep the blog posts 'This Month in TiKV' going on the web so that the latest updates of the project are open to the public.

**Comment by WT-Liu** [comment]
@dcalvin @zhangjinpeng1987 PTAL~ Thanks!

**Review by zhangjinpeng1987 — APPROVED** [review]
LGTM

**Comment by dcalvin** [comment]
> t TiK

I think we should provide this info in the Readme file so that people would still find the channel to communicate

**Review by BusyJay — APPROVED** [review]

**Pull request merged**
