### PR TITLE
raftstore: retry pending read index requests (#6348)

### PR DESCRIPTION
**Pull request by hicqu**
cherry-pick #6348 .

### CODE REVIEW

**Comment by BusyJay** [comment]
Why so many changes are missing?

**Comment by hicqu** [comment]
@BusyJay because #6348 is missed totally. we only cherry-picked some later changes. Now it's completed. PTAL.

**Comment by BusyJay** [comment]
Any tests to cover it?

**Comment by hicqu** [comment]
> Any tests to cover it?
 tests/integrations/raftstore/test_replica_read.rs, line 73.

**Pull request merged**
