### PR TITLE
causal_ts: add async func for CausalTsProvider

### LINKED ISSUE #13428: async func for CausalTsProvider
### Is your feature request related to a problem? Please describe:

Sometime we need get causal ts or flush asynchronously.  When we call flush to flush ts in a async func (such as [register_min_ts_event](https://github.com/tikv/tikv/blob/master/components/cdc/src/endpoint.rs#L1146)), the async flush can get better performance.

### Describe the feature you'd like:

Add async func for CausalTsProvider.

### PR DESCRIPTION
**Pull request by zeminzhou**
Signed-off-by: zeminzhou <zhouzemin@pingcap.com>

### What is changed and how it works?

Issue Number: Close #13428

What's Changed:

Add async func for get_ts & flush for CausalTsProvider.

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
Add asynchronous methods for `CausalTsProvider`.
```

### CODE REVIEW

**Review by pingyu — APPROVED** [review]
LGTM~

**Review by haojinming — APPROVED** [review]
LGTM~

**Pull request merged**
