### PR TITLE
diagnoostics: return empty response if search path dose not exist

### PR DESCRIPTION
**Pull request by Fullstop000**
Signed-off-by: Fullstop000 <fullstop1005@gmail.com>

### What problem does this PR solve?

If the path of logs does not exist (e.g. the `slow_log_dir` is empty by default), `search_log` returns an error complaining about `invalid directory`, which is not specific enough for the client and make it unclear to deal with such an error. This PR changes the behavior of handling a nonexistent search path to return an empty response instead of `invalid directory` error. 

Relate to https://github.com/pingcap-incubator/tidb-dashboard/issues/303.

### CODE REVIEW

**Comment by Fullstop000** [comment]
@lonng @breeswish PTAL

**Comment by breeswish** [comment]
You need to fix CI lint issues

**Comment by TennyZhuang** [comment]
@sre-bot /run-all-tests

**Pull request merged**
