### PR TITLE
charset,collation: implement `GB18030` and 2 collations

### LINKED ISSUE #17470: Support `GB18030` charset and 2 collations

### PR DESCRIPTION
**Pull request by CbcWestwolf**
### What is changed and how it works?

Issue Number: Close #17470

What's Changed:

```commit-message
* Add a new charset `gb18030`
* Add two related collations `gb18030_chinese_ci` and `gb18030_bin`
```

### Related changes

- [x] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Support charset gb18030, and collations gb18030_bin and gb18030_chinese_ci
```

### CODE REVIEW

**Review by wjhuang2016 — APPROVED** [review]

**Comment by CbcWestwolf** [comment]
PTAL 
/cc glorv

**Review by glorv — APPROVED** [review]

**Pull request merged**
