### PR TITLE
engine: fix prefix extractor panic when delete range

### PR DESCRIPTION
**Pull request by overvenus**
## What have you changed? (mandatory)

Delete range as a kv pair is passed to prefix extractor which causes panic, because the key is less than 8 bytes.

This is a temporary workaround, the long term plan is skipping the prefix extractor for delete range in RocksDB side.

## What are the type of the changes? (mandatory)

- Bug fix (change which fixes an issue)

## How has this PR been tested? (mandatory)

Unit tests.

## Does this PR affect documentation (docs) update? (mandatory)

No.

## Does this PR affect tidb-ansible update? (mandatory)

No.

## Refer to a related PR or issue link (optional)

#4461

### CODE REVIEW

**Comment by overvenus** [comment]
@yiwu-arbug Can `RangeDeletion` be skipped when we set prefix bloom filter?

**Comment by yiwu-arbug** [comment]
@overvenus Do you have a stack trace of the panic, or can you show me how can I reproduce? I tried a simple test with RocksDB and it works fine: https://github.com/yiwu-arbug/rocksdb/commit/d72564cd618ba1f7484a37abd1b3a0247547da99

**Comment by yiwu-arbug** [comment]
Fixing prefix extractor issue on RocksDB side with https://github.com/facebook/rocksdb/pull/5190 and https://github.com/facebook/rocksdb/pull/5191

**Pull request merged**
