### PR TITLE
statistics: remove unreachable code

### PR DESCRIPTION
**Pull request by hi-rustin**
### What is changed and how it works?

Removed some unreachable code. The code is now unreachable as TiDB no longer sends mixed analyze requests to TiKV if the statistics version is set to 2.

You can only find one reference of the mixed request type in TiDB.

image

You can find it here: https://github.com/pingcap/tidb/blob/12b37d88dceb4eb4da6fe316fb4d0af2024ab58b/pkg/executor/builder.go#L2706

But for version 2, we use `buildAnalyzeSamplingPushdown` to build the analysis task.

image

Issue Number: Ref https://github.com/tikv/tikv/issues/16463

What's Changed:

```commit-message
statistics: remove unreachable code

The code is now unreachable as TiDB no longer
sends mixed analyze requests to TiKV if the
statistics version is set to 2.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by hi-rustin — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by hi-rustin — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Review by hi-rustin — COMMENTED** [review]
🔢 Self-check (PR reviewed by myself and ready for feedback.)

**Comment by hi-rustin** [comment]
Test locally:
1. Start the tidb cluster with patch: `tiup playground nightly  --kv.binpath /Volumes/t7/code/tikv/target/aarch64-apple-darwin/debug/tikv-server`

```console
mysql>  select * from information_schema.cluster_info;
+---------+-----------------+-----------------+---------------------------+------------------------------------------+---------------------+--------------+-----------+
| TYPE    | INSTANCE        | STATUS_ADDRESS  | VERSION                   | GIT_HASH                                 | START_TIME          | UPTIME       | SERVER_ID |
+---------+-----------------+-----------------+---------------------------+------------------------------------------+---------------------+--------------+-----------+
| tidb    | 127.0.0.1:4000  | 127.0.0.1:10080 | 8.2.0-alpha-3-g79c1499bec | 79c1499bec7e609a051634c87460511b203c5389 | 2024-05-11 15:01:48 | 9m0.4416s    |       713 |
| pd      | 127.0.0.1:2379  | 127.0.0.1:2379  | 8.2.0-alpha-1-g4a7bffcb3  | 4a7bffcb3baf7a8e2515e70834d8567bc17439da | 2024-05-11 15:01:18 | 9m30.441602s |         0 |
| tiflash | 127.0.0.1:3930  | 127.0.0.1:20292 | 8.2.0-alpha-17-g8e50de84e | 8e50de84e6d6ecdcc108990217b70b6bb3f50271 | 2024-05-11 15:01:55 | 8m53.441603s |         0 |
| tikv    | 127.0.0.1:20160 | 127.0.0.1:20180 | 8.2.0-alpha               | 87c9a2a0965ae512fd254e26733ccc0c424bb36a | 2024-05-11 15:01:27 | 9m21.441603s |         0 |
+---------+-----------------+-----------------+---------------------------+------------------------------------------+---------------------+--------------+-----------+
4 rows in set (0.01 sec)
```

2. Create a table and analyze with stats version 2:
```sql
create table t(a int);
```
```ts
import { Client } from "https://deno.land/x/mysql/mod.ts";

const client = await new Client().connect({
  hostname: "127.0.0.1",
  port: 4000,
  username: "root",
  db: "test",
  password: "",
});

for (let i = 0; i < 2000; i++) {
  await client.execute(`INSERT INTO t (a) VALUES (?)`, [i]);
  if (i % 2 === 0) {
    await client.execute(`INSERT INTO t (a) VALUES (?)`, [i]);
  }
}

await client.close();;
```
```sql
analyze table t;
```
3. 
image
image

**Review by time-and-fate — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]

**Comment by hi-rustin** [comment]
For the backward compatibility:
1. This code has been unreadable since v5.1.0.
2. For tidb v5.0.x, we didn't support analysis version 2.
image

**Pull request merged**
