### PR TITLE
PCP-14:localize storage metrics

### PR DESCRIPTION
**Pull request by Renkai**
###  What have you changed?

Please explain in detail what the changes are in this PR and why they are needed:

use some utility trait instead of `.on_tick` to localize and flush metrics in storage.

###  What is the type of the changes?

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?

- [x] Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?
No 

###  Does this PR affect `tidb-ansible`?
No 

###  Refer to a related PR or issue link (optional)
https://github.com/tikv/tikv/issues/5708

### CODE REVIEW

**Comment by AndreMouche** [comment]
Please fix the conflicts,thank you

**Comment by Renkai** [comment]
New PR at https://github.com/tikv/tikv/pull/6698

**Pull request closed without merging**
