### PR TITLE
avoid to banish region leaders when rolling upgrade (#12167)

### LINKED ISSUE #12166: region leaders can be banished in an election timeout when rolling upgrade a cluster
### What version of TiKV are you using?
master

The log files is in the attachment. It shows a region 27073. At `18:28:43` one replica starts an pre-election, and then the the region leader is banished about 10s.

After some investigations, I think it's caused by an issue of hibernate regions.

[27073.zip](https://github.com/tikv/tikv/files/8252692/27073.zip)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #12167 to release-5.4
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/12196
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/12196:release-5.4-d9cc44114180
```

---

Signed-off-by: qupeng <qupeng@pingcap.com>

### What is changed and how it works?

Issue Number: Close #12166 

Currently it only contains a test case. More commits will be pushed to fix the issue later.

What's Changed:

```commit-message
avoit to banish region leaders when rolling upgrade
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Integration test

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hicqu** [comment]
It's not necessary

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by hicqu — APPROVED** [review]

**Comment by Connor1996** [comment]
@hicqu Please fix the compile error

**Pull request merged**
