### PR TITLE
raftstore: only persist merge target if the merge is known to be succeeded (#12251)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #12251 to release-5.4
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/12295
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/12295:release-5.4-3364702e1903
```

---

### What is changed and how it works?

Issue Number: Close #12232 

What's Changed:

When destroying, only persist merge target if the merge is known to be succeeded

```commit-message
raftstore: only persist merge target if the merge is known to be succeeded
```

### Check List 

Tests 

- Integration test

### Release note 

```release-note
fix tikv panic and peer unexpected destroy due to fake merge target
```

### CODE REVIEW

**Review by cfzjywxk — APPROVED** [review]

**Comment by cfzjywxk** [comment]
@5kbpers @you06 
Need an approvement for the release pick.

**Review by you06 — APPROVED** [review]

**Pull request merged**
