### PR TITLE
*: Update sysinfo dependency

### PR DESCRIPTION
**Pull request by dveeden**
### What is changed and how it works?

Issue Number: ref #11276

What's Changed:

Update [sysinfo](https://crates.io/crates/sysinfo) dependency from 0.16.4 to 0.26.5

### Check List 

Tests 

- No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by BusyJay** [comment]
I can see there are several PRs that tries to update dependencies. How about also include those changes in this PR?

https://github.com/tikv/tikv/pulls/app%2Fdependabot

**Comment by dveeden** [comment]
@BusyJay I prefer to handle these in separate PRs to limit the scope and the number of changes per PR

**Comment by dveeden** [comment]
PTAL @BusyJay

**Review by BusyJay — APPROVED** [review]

**Review by hicqu — APPROVED** [review]

**Pull request merged**
