### PR TITLE
RocksDB: change compaction-guard-min-output-file-size to 1MB

### LINKED ISSUE #14888: compaction-guard-min-output-file-size default value 8MB is too big that could leads to huge compaction
### What version of TiKV are you using?

v6.5.1
### Steps to reproduce

1. Enable TiDB TTL feature, import 1TB data into 2 tables
2.  Wait 29 days 
3. manually compact cluster's data to bottom level
4. insert 100 records in each table.
### What did you expect?
NO huge compaction could happen
### What did happened?
At 30th day, there's huge compaction that includes majority data of L6.

The reason is that 8MB threshold makes compaction guard not effective for many regions. And when TTL is enabled,  the upper level SST could cover a huge range that could lead to huge compaction.

### PR DESCRIPTION
**Pull request by tonyxuqqi**
### What is changed and how it works?

Issue Number: Close #14888

What's Changed:

```commit-message
Change compaction-guard-min-output-file-size to 1MB
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM

### Release note 

```release-note
Default value of compaction-guard-min-output-file-size is changed to 1MB (from 8MB)
```

### CODE REVIEW

**Comment by tonyxuqqi** [comment]
Screen Shot 2023-06-07 at 4 04 41 PM
Sysbench OLTP_Insert and OLTP_Read_Only result.
The first and third line result is from this PR, the second and 4th line result is from nightly.

**Review by overvenus — APPROVED** [review]

**Comment by tonyxuqqi** [comment]
tpcc
Version | TPS | QPS|
This PR |3837|59484|
Nightly|3761|58308|

**Pull request merged**
