### PR TITLE
copr: add vectorized last_day

### PR DESCRIPTION
**Pull request by TommyCpp**
Signed-off-by: zhongyang.wu <zhongyang.wu@outlook.com>

PCP #5751

###  What have you changed?

Add vecorized function last day

###  What is the type of the changes?
- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?
- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

no

###  Does this PR affect `tidb-ansible`?

no

### CODE REVIEW

**Comment by breeswish** [comment]
@lonng @sticnarf PTAL

**Comment by TommyCpp** [comment]
> Error handling here is different from TiDB. But it remains controversy what's the appropriate behavior here: [pingcap/tidb#11695](https://github.com/pingcap/tidb/issues/11695)...
> /cc @TennyZhuang

I could change the behavior accoding to MySQL version for now I guess?

**Comment by TommyCpp** [comment]
@TennyZhuang @sticnarf  PTAL
For the three scenarios mentioned in https://github.com/pingcap/tidb/issues/11695
1. `2011-01 12:12:12` This one can never been parsed to `Time`, so I don't handle it or test it.
2. `2011-01-00 12:12:12` will return last day of Jan.
3. `2011-00-01 12:12:12` will return `None`

**Comment by sticnarf** [comment]
@TommyCpp Sorry we've just merged a HUGE refactoring PR about tidb_query so there are some conflicts. Could you resolve them now?
The code looks good to me.

**Comment by TommyCpp** [comment]
@sticnarf refactoring has been merged, please let know if there is anywhere that may need change, Thanks!

**Pull request merged**
