### PR TITLE
Rewritten ScannerBuilder and ScannerConfig

### LINKED ISSUE #5531: Rewrite ScannerBuilder and ScannerConfig
## Feature Request

Current `ScannerBuilder` and `ScannerConfig` is confusing.

1. It names as a builder but does not fully act as the [builder pattern](https://doc.rust-lang.org/1.0.0/style/ownership/builders.html). For example, it marks optional configs like `desc` as required.

2. `ScannerConfig::create_cf_cursor` is very easy to cause mistakes. It takes the ownership and clears the key range only for DEFAULT CF, which is not reflected according to its name or signature. We must carefully review the code to ensure the order of calling to avoid key ranges being accidentally taken.

### PR DESCRIPTION
**Pull request by shashwatj07**
Signed-off-by: Shashwat Jaiswal <shashwatjaiswal2001@gmail.com>

### What problem does this PR solve?

Issue Number: close #5531

Problem Summary: Improperly structured Builder pattern.

### What is changed and how it works?

Proposal: Simple fix.
What's Changed: ```desc``` has been made optional (false by default) in ScannerConfig

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by andylokandy — APPROVED** [review]

**Review by sticnarf — APPROVED** [review]
LGTM

**Comment by sticnarf** [comment]
Thanks for your contribution!

**Comment by shashwatj07** [comment]
@andylokandy ping

**Comment by andylokandy** [comment]
@hi-rustin The bot seems to not working. Would you like to take a look?

**Comment by andylokandy** [comment]
@hi-rustin The bot seems to not working. Would you like to take a look?

**Pull request merged**
