### PR TITLE
Titan: refine Titan dir empty check

### LINKED ISSUE #16295: TiKV fails to restart after making Titan default on
### What version of TiKV are you using?

master branch
### What operating system and CPU are you using?

any

### Steps to reproduce

Restart after creating a new cluster.

### What did you expect?
Success

### What did happened?

Failure

### PR DESCRIPTION
**Pull request by v01dstar**
### What is changed and how it works?

Issue Number: Close #16295

What's Changed:

```commit-message
Refine Titan dir empty check
```

### Related changes
N/A

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

N/A
### Release note

```release-note
None
```

### CODE REVIEW

**Review by Connor1996 — APPROVED** [review]
LGTM overall, would you mind adding `min-blob-size = 0` to `common-test.toml` to make Titan used as much as possible in tests.

**Review by tonyxuqqi — APPROVED** [review]

**Pull request merged**
