### PR TITLE
Escalate import/export priority

### PR DESCRIPTION
**Pull request by tabokie**
Signed-off-by: tabokie <xy.tao@outlook.com>

### What problem does this PR solve?

Problem Summary:

Data import will slow down when rate limit kicks in.

### What is changed and how it works?

What's Changed:

Change import/export priority from low to medium. Threshold for LOW is not accurate, thus causing regression. HIGH priority is not limited at all, we shouldn't set to that either.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hunterlxt** [comment]
can you explain more why not `low` or `high`

**Review by hunterlxt — APPROVED** [review]

**Review by Connor1996 — APPROVED** [review]
LGTM

**Pull request merged**
