### PR TITLE
A better scalable thread pool scheme

### PR DESCRIPTION
**Pull request by Pslydhh**
## What have you changed?
Introducing a new thread pool, better performance and scalability.
update `/util/threadpool.rs, /util/mod.rs, lib.rs`. add `/util/spmcqueue.rs`. 

## Why this change was made?
The current threadpool is based on single producer/mutiple consumers queue(VecDeque) with mutex(as https://gist.github.com/siddontang/fa81a59e7234e9960f8514785af69e1e), this caused bad performance with Lock Contention. **more precisely, only one of conumsers(worker threads) or the producer can be made progress at any time. this is a hot spot problem**.

**With new thread pool scheme,** 

- **Nonblocking/Better scalable**: Each operation does not block the other operations, Producers will not be blocked by consumers, threadpool's execute is very direct and fast.

- **No Lock Contention**: There is no conflicts with producer and conumsers, The only conflict is Consumers' conflict, and we conquer this problem through a fetch-and-add(common atomic operation).

- **Direct data exchange**: Just a xchg atomic operation.

- **Data structure / Organization**: Linked  node(with growing id), one node with(1<<N, 512) cells. **consumer take the last cell in node maybe try to memory reclaim(batch nods).**

## Benchmark: compare with current thread pool and spin thread pool
With this Simple benchmark, **new thread pool scheme provides an obvious performance advantage.**

@siddontang 's current thread pool: https://gist.github.com/siddontang/fa81a59e7234e9960f8514785af69e1e
@siddontang 's spin thread pool:
https://gist.github.com/siddontang/5b4b023475a55e0d4898117790a224c9
New threadpool:
https://gist.github.com/Pslydhh/4f3fda8a27fb24644aa1d77b76991c6a

base: linux 2cores Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz

cur thread pool                 spin thread pool                                 new thread pool
Using 8 threads                 Using 8 threads                                   Using 8 threads
603709 QPS                       519200 QPS                                        2228426 QPS
596301 QPS                       522523 QPS                                        2120498 QPS
1021619 QPS                     537190 QPS                                        1801233 QPS
731460 QPS                       515027 QPS                                        2072558 QPS
223569 QPS                       528928 QPS                                        1814707 QPS
280141 QPS                       486561 QPS                                        2006970 QPS
311056 QPS                       548325 QPS                                        2032390 QPS
221035 QPS                       521873 QPS                                        2009320 QPS
226694 QPS                       596767 QPS                                        1910401 QPS

cur thread pool                 spin thread pool                                 new thread pool
Using 2 threads                 Using 2 threads                                  Using 2 threads
1672643 QPS                     2321171 QPS                                      2944188 QPS
1700202 QPS                     2292505 QPS                                      3078022 QPS
1747062 QPS                     2564804 QPS                                      3131144 QPS
1673945 QPS                     2555916 QPS                                      3157857 QPS
1910982 QPS                     2429625 QPS                                      2880966 QPS
1770090 QPS                     2468685 QPS                                      2945744 QPS
1487229 QPS                     2446119 QPS                                      2979314 QPS
1580273 QPS                     2357457 QPS                                      2975794 QPS
1778112 QPS                     2288835 QPS                                      2850212 QPS

## Notes:
**The task executed by the threadpool shouldn't blocks worker thread for a long time.**

### CODE REVIEW

**Comment by breeswish** [comment]
Wow, your work is remarkable. Thanks a lot!

I have two thoughts:

- How will this thread pool perform when thread pool worker size >> actual workload? We inspected notable performance decrease for small jobs for this scenario for our current thread pool model. For example, if the workload mainly utilizes 200% cpu (i.e. 2 workers), when thread pool size is set to large (i.e. 40 workers), the utilization may drop off to 160%.

- We are actually deprecating our thread pool and slowly moving our existing tasks on it. For new tasks we prefer using [CpuPool](https://docs.rs/futures-cpupool/0.1.8/futures_cpupool/) to fully utilize the async advantage. However we have also found out that current CpuPool implementation does not work very well even compared to our current thread pool implementation. Maybe you could consider a better CpuPool implementation as well, which is more helpful for TiKV (and for the Rust community :)

**Comment by Pslydhh** [comment]
@breeswish It's a pleasure :)

- When thread pool worker size >> actual workload, the new thread pool performance decrease too. but this is based on your hardware configuration, as my test machine just has two cores, context switch caused the performance is much lower after using 40 working threads. But if your machine has 40 cores, We could use different spin strategies to reduce Performance loss. Under what scenarios do you need to use too many threads? Although I don't think you will use too many threads in practice :)

- As I know, the [CpuPool](https://github.com/rust-lang-nursery/futures-rs/blob/0.1/futures-cpupool/src/lib.rs) and It's latest version [futures-rs](https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-executor/src/thread_pool.rs), in the threadpool, data exchange between producer/consumer is passed through mpsc::channel, and on top of it, there is also a mutex. So In my opinion, it's not going to be very fast now. Yes, async features are useful :), and I think it can also gracefully add features such as 'future' feature to the new thread pool.

**Comment by breeswish** [comment]
@Pslydhh Yes! Actually we found out that many of our normal users (even our own OPS) have some misunderstandings about the thread pool size. They know that increasing thread pool size can enlarge the processing capability, but what they don't know is that it will also introduce more overheads because of contention. Some of them is likely to simply enlarge the thread pool size to the core size, to maximize the capability, without knowing the extra cost.

Your PR did remarkable job. However we may spend a long time reviewing such a large PR. As a underlying & critical component, TiKV's merging policy is very conservative. We only merge PRs when we are very sure that there is no reliability or correctness issues. Performance improvement is much less important than correctness here. If you can split your PRs into several ones which is somehow easier to review && ensure correctness, it will be accepted faster :)

**Comment by breeswish** [comment]
Hi, we recently made a study on thread pool task scheduling and learnt from modern implementations that usually a work stealing strategy can be used instead. In Rust, [crossbeam-deque](https://github.com/crossbeam-rs/crossbeam-deque) is a nice and reliable implementation for that purpose. Would you like to benchmark and try this approach? You know, TiKV is a very critical component in our system so that we are quite conservative and only accepts reliable changes (or changes that can be easily proved to be correct), please understand that we are more willing to use a mature solution :)

**Pull request closed without merging**
