### PR TITLE
backup: record errors to metrics

### PR DESCRIPTION
**Pull request by overvenus**
###  What have you changed?

Record backup errors to metrics.

###  What is the type of the changes?

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?

Unit test.

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No.

###  Does this PR affect `tidb-ansible`?

No.

### CODE REVIEW

**Comment by 5kbpers** [comment]
CI failed

**Comment by overvenus** [comment]
Test fixed thanks to #5428. PTAL

**Pull request merged**
