### PR TITLE
tikv_alloc: update jemalloc to 5.2.1 (#8324)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #8324 to release-4.0

---

### What problem does this PR solve?

Problem Summary:

### What is changed and how it works?

Update jemalloc to 5.2.1 to address memory allocation problem in huge page

### Related changes

tikv/tikv#4515

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 
- update jemalloc to 5.2.1

### CODE REVIEW

**Review by sticnarf — COMMENTED** [review]
lgtm

**Comment by innerr** [comment]
It looks CI failed

**Pull request merged**
