### PR TITLE
config: fix alias name snap-max-write-bytes-per-sec

### LINKED ISSUE #14455: tikv will upgrade fail with config: server.snap-max-write-bytes-per-sec
### What version of TiKV are you using?
<[root@localhost 700]#  /home/tidb/deploy/tikv-2360/bin/tikv-server -V 
TiKV 
Release Version:   7.0.0
Edition:           Community
Git Commit Hash:   38d6d6264e4ce25e3fe780e03b879c04890ca37b
Git Commit Branch: heads/refs/tags/v7.0.0
UTC Build Time:    2023-03-24 09:40:13
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
[root@localhost 700]# 

### Steps to reproduce
install tidb v6.6.0 version cluster with following config, then upgrade to v7.0.0
  tikv:
    raft-engine.enable-log-recycle: false
    raftdb.defaultcf.target-file-size-base: 8MiB
    resource-control.enabled: false
    server.snap-max-write-bytes-per-sec: 50MiB
    
### What did happened?
/home/tidb/deploy/prometheus-9090, data_dir=[/home/tidb/deploy/prometheus-9090/data], log_dir=/home/tidb/deploy/prometheus-9090/log, cache_dir=/root/.tiup/storage/cluster/clusters/113/config-cache

Error: init config failed: 172.16.6.113:2360: executor.ssh.execute_failed: Failed to execute command over SSH for 'tidb@172.16.6.113:22' {ssh_stderr: unknown configuration options: server.snap-max-write-bytes-per-sec
, ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin /home/tidb/deploy/tikv-2360/bin/tikv-server --config-check --config=/home/tidb/deploy/tikv-2360/conf/tikv.toml --pd "" --data-dir "/home/tidb/deploy/tikv-2360/data"}, cause: Process exited with status 1: check config failed

Verbose debug logs has been written to /root/.tiup/logs/tiup-cluster-debug-2023-03-24-18-42-47.log.

### PR DESCRIPTION
**Pull request by BusyJay**
### What is changed and how it works?
Issue Number: Close #14455.

What's Changed:

```commit-message
```

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by nolouch — APPROVED** [review]
lgtm. and will online config also works for the old name?

**Comment by BusyJay** [comment]
No, online configuration requires new name.

**Review by glorv — APPROVED** [review]

**Review by zhangjinpeng1987 — APPROVED** [review]
LGTM

**Pull request merged**
