### PR TITLE
[DNM] Zero Copy Scanner Value

### PR DESCRIPTION
**Pull request by breeswish**
Signed-off-by: Breezewish <breezewish@pingcap.com>

###  What have you changed?

This PR avoids value to be copied (and allocated) when scanning MVCC data in the Coprocessor vectorized executors.

###  What is the type of the changes?

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?

- Unit test
- Integration test

### CODE REVIEW

**Comment by mahjonp** [comment]
TiKV server restarts continuously, seems there was some serious bugs, you'd better let it pass integration-common-test before running benchmark. @breeswish

**Comment by breeswish** [comment]
@mahjonp I cannot discover the reason of TiKV restart according to CI logs. Do you have ideas?

**Comment by breeswish** [comment]
Closing this PR since it does not show notable performance improvement (around 3% for most queries) while introducing a very complex interface. Will be replaced by some more aggressive optimizations extracted from https://github.com/tikv/tikv/pull/5538

**Comment by breeswish** [comment]
Close since this PR makes the interface very complex while the effect is not very notable.

**Pull request closed without merging**
