### PR TITLE
tikv-ctl: Introduce crate vlog

### LINKED ISSUE #4005: Gabage outputs in tests
## Bug Report

During test, the following messages are outputed:

```
thread 0: no corresponding DEFAULT record for LOCK, key: k1\000\000\000\000\000\000\371, lock_ts: 100
thread 0: LOCK ts is less than WRITE ts, key: k5\000\000\000\000\000\000\371, lock_ts: 100, commit_ts: 101
thread 0: orphan DEFAULT record, key: k6\000\000\000\000\000\000\371, start_ts: 96
thread 0: no corresponding DEFAULT record for WRITE, key: k6\000\000\000\000\000\000\371, start_ts: 92, commit_ts: 93
thread 0: orphan DEFAULT record, key: k6\000\000\000\000\000\000\371, start_ts: 90
thread 0: orphan DEFAULT record, key: k6\000\000\000\000\000\000\371, start_ts: 88
thread 0: LOCK ts is less than WRITE ts, key: k7\000\000\000\000\000\000\371, lock_ts: 100, commit_ts: 100
thread 0: no corresponding DEFAULT record for WRITE, key: k7\000\000\000\000\000\000\371, start_ts: 99, commit_ts: 100
thread 0: orphan DEFAULT record, key: k7\000\000\000\000\000\000\371, start_ts: 98
thread 0: orphan DEFAULT record, key: k7\000\000\000\000\000\000\371, start_ts: 90
```

### PR DESCRIPTION
**Pull request by MyonKeminta**
Signed-off-by: MyonKeminta <MyonKeminta@users.noreply.github.com>

## What have you changed? (mandatory)

Introduce package `vlog` to replace `println`s in tikv-ctl's code.

Fixes #4005 

## What are the type of the changes? (mandatory)

- Improvement (non-breaking change which is an improvement to an existing feature)
- Bug fix (non-breaking change which fixes an issue)

## How has this PR been tested? (mandatory)

* Manual tests (run tikv-ctl manually to see whether the outputs are still printed properly).
* Unit tests (to make sure outputs stated in #4005 has disappeared).

## Does this PR affect documentation (docs) update? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No

### CODE REVIEW

**Comment by MyonKeminta** [comment]
@breeswish @zhangjinpeng1987 PTAL

**Comment by siddontang** [comment]
can you tell more that why vlog can fix this ?

**Comment by breeswish** [comment]
What kind of print should be v0 and what for v1?

**Comment by MyonKeminta** [comment]
@siddontang vlog supports setting verbose level. So if the outputs are in a higher level and in tests we set lower verbose level, then those output won't be printed out.
@breeswish v0 means it should always be printed out. I think  vlog is lack of a "quiet mode" which means every thing shouldn't be printed out, so I'm considering use v1 every where... It's not very elegant.  Maybe vlog is not very suitable for us.

**Comment by breeswish** [comment]
How about starting at v1 so that there is a quiet mode manually created by us?

**Comment by MyonKeminta** [comment]
@breeswish Although i think it's not very elegant to violate how the library was designed... If you think it's ok, I will agree with you

**Comment by zhouqiang-cl** [comment]
jenkins-ci-tikv/integration-common-test are disabled
idc-jenkins-ci-tikv/integration-common-test  are required

**Comment by siddontang** [comment]
can we use log instead? like debug, info?

**Comment by siddontang** [comment]
Btw, vlog LGTM

**Comment by MyonKeminta** [comment]
@siddontang I'm afraid it's not very friendly if a command line tool's every line of output is printed with time and source code file, and even after unifying our logs, all special characters in output are escaped...

**Pull request merged**
