### PR TITLE
copr: fix IN expr didn't handle unsigned/signed int properly (#9823)

### LINKED ISSUE #9821: coprocessor IN expr not handle max_u64 properly
### What version of TiKV are you using?
    TiKV
    Release Version:   5.0.0-rc.x
    Edition:           Community
    Git Commit Hash:   eca434da4e71d540f7201203d10bf078d2ece853
    Git Commit Branch: master
    UTC Build Time:    2021-02-24 08:22:44
    Rust Version:      rustc 1.51.0-nightly (1d0d76f8d 2021-01-24)
    Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
    Profile:           debug

### What operating system and CPU are you using?

    AMD Ryzen 5 PRO 4650U with Radeon Graphics

### Steps to reproduce

Copr bug, use following SQL can reproduce [TiDB issue](https://github.com/pingcap/tidb/issues/23198)

    use test;
    drop table if exists t;
    create table t (a int);
    insert into t values(-1);
    select * from t where a in(18446744073709551615, 1);

### What did you expect?
empty set
### What did happened?
    select a from t where a in(18446744073709551615, 1);
    +-----+
    | a   |
    |-----|
    | -1  |
    +-----+

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #9823 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/10018
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/10018:release-5.0-30d86aa5a65c
```

---

### What problem does this PR solve?

Issue Number: close #9821

Problem Summary: IN expr didn't distinguish between unsigned int and signed int. So -1(bigint) equals 18446744073709551615(bigint unsigned), which is not compatible with MySQL. Here is [TiDB issue](https://github.com/pingcap/tidb/issues/23198).

### What is changed and how it works?
What's Changed: Add a fn_meta for IN expr when first arg of IN expr is INT type. In this function, we use info which records arg's flag to tell whether two integer is really equal.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test : impl_compare_in.rs: test_unsigned_signed_int()

Side effects:
- performance regression: To fix this issue, we need to check argument's signed/unsigned flag. Also we use HashMap instread HashSet. So maybe little performance regression.

### Release note 
- fix IN expr(coprocessor) didn't handle unsigned/signed int properly

### CODE REVIEW

**Comment by guo-shaoge** [comment]
@skyzh PTAL

**Review by skyzh — APPROVED** [review]
LGTM. <del>Will this affect non-vectorized framework?</del>. I mistaken 5.0 for 4.0. If so, you may also need to propose a fix.

**Comment by guo-shaoge** [comment]
@lzmhhh123 PTAL

**Review by lzmhhh123 — APPROVED** [review]

**Pull request merged**
