### PR TITLE
UCP: Migrate scalar function `Ord` from TiDB

### LINKED ISSUE #6945: UCP: Migrate scalar function `Ord` from TiDB
## Description

Port the scalar function `Ord` from TiDB to coprocessor.

## Score 

* 50

## Mentor(s)

* @iosmanthus 

## Recommended Skills

* Rust programming 

## Learning Materials

Already implemented expressions ported from TiDB

- https://github.com/tikv/tikv/tree/master/components/tidb_query/src/rpn_expr) 
- https://github.com/tikv/tikv/tree/master/components/tidb_query/src/expr)

### PR DESCRIPTION
**Pull request by jyizheng**
Signed-off-by: jyizheng <jyizheng@gmail.com>

What's Changed:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note

### CODE REVIEW

**Comment by jyizheng** [comment]
@TennyZhuang Could you review it?

**Comment by TennyZhuang** [comment]
I’m considering about whether to introduce the bstr dependency. I implement the same function in charset.rs using unsafe code.

@breeswish  PTAL

**Comment by TennyZhuang** [comment]
can you submit a PR to introduce bstr dependency first and modify the implementation at https://github.com/tikv/tikv/blob/1de029631e09a3f9989a468a9cb4b97ec4db440e/components/tidb_query_datatype/src/codec/collation/utf8mb4.rs#L18 ?

Also remember to remove unnecessary feature flag in https://github.com/tikv/tikv/blob/master/components/tidb_query_datatype/src/lib.rs

**Comment by breeswish** [comment]
@iosmanthus @TennyZhuang PTAL

**Comment by breeswish** [comment]
@SunRunAway PTAL

**Comment by jyizheng** [comment]
Can anyone tell me why ci/test failed? Is it related to my changes?

**Comment by jyizheng** [comment]
Can anyone merge this, please? @SunRunAway @TennyZhuang

**Comment by breeswish** [comment]
Thanks for the update! @SunRunAway PTAL

**Comment by jyizheng** [comment]
@SunRunAway PTAL

**Pull request merged**
