### PR TITLE
Reserve key space id encoding in backup convert (#12759)

### LINKED ISSUE #12758: RawKV API V2 supports "key space" encoded in key
### Is your feature request related to a problem? Please describe:

The [multi-tenant](https://en.wikipedia.org/wiki/Multitenancy) is an essential feature for cloud user to reduce cost. And we need the "key space" as a fundamental to implement multi-tenant.

### Describe the feature you'd like:

RawKV API V2 support "key space" encoded in key.
As the key encoding is implemented in client (see https://github.com/tikv/client-java/issues/555), the only feature need to be implemented in TiKV now is the cross api version backup. See [backup/endpoint.rs:213](https://github.com/tikv/tikv/blob/da16e5eca3e44f8a987acdd6aad31acad3f5c05e/components/backup/src/endpoint.rs#L213), [backup/endpoint.rs:464](https://github.com/tikv/tikv/blob/da16e5eca3e44f8a987acdd6aad31acad3f5c05e/components/backup/src/endpoint.rs#L464),[backup/endpoint.rs:470](https://github.com/tikv/tikv/blob/da16e5eca3e44f8a987acdd6aad31acad3f5c05e/components/backup/src/endpoint.rs#L470).

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #12759 to release-6.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/12776
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/12776:release-6.1-62545b0c5c85
```

---

Signed-off-by: haojinming <jinming.hao@pingcap.com>

### What is changed and how it works?

Issue Number: Close #12758 

What's Changed:

Add encoding of key space id in apiv2 key when backup convert.

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 

```release-note

Add key space id encoding in apiv2 key when backup convert.
```

### CODE REVIEW

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by pingyu — APPROVED** [review]
LGTM~

**Review by iosmanthus — APPROVED** [review]
LGTM

**Pull request merged**
