### PR TITLE
charset: update the error message about can not convert error

### PR DESCRIPTION
**Pull request by xiongjiwei**
Signed-off-by: xiongjiwei <xiongjiwei1996@outlook.com>

### What is changed and how it works?

Issue Number: Close https://github.com/tikv/tikv/issues/13156

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### Release note 

```release-note
make the error message of convert charset in tikv more clear
```

### CODE REVIEW

**Review by wshwsh12 — APPROVED** [review]
LGTM

**Review by wjhuang2016 — COMMENTED** [review]
Please add some unit tests.

**Comment by xiongjiwei** [comment]
> Please add some unit tests.

it is hard to have UT to test the error message, I followed the other errors, and there is no UT either

**Review by wjhuang2016 — APPROVED** [review]

**Review by breezewish — APPROVED** [review]

**Pull request merged**
