### PR TITLE
coprocessor: do not treat deadline exceeded error as other error

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: ref #15566

What's Changed:

```
Fix the bug that coprocessor may convert DeadlineExceeded error to Other error so tidb can handle backoff correctly.
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by glorv** [comment]
@bufferflies @you06  PTAL

**Comment by you06** [comment]
Do you mean the `DeadlineExceeded` error is mistakenly converted to stale command error before this PR?

**Comment by glorv** [comment]
> Do you mean the `DeadlineExceeded` error is mistakenly converted to stale command error before this PR?

It's converted to Other error, not stale command.

**Comment by glorv** [comment]
@you06 @bufferflies  PTAL

**Review by bufferflies — APPROVED** [review]

**Comment by bufferflies** [comment]
how about add unit test for it?

**Review by nolouch — APPROVED** [review]
lgtm

**Review by you06 — APPROVED** [review]

**Pull request merged**
