### PR TITLE
Delete challenge-program.md

### LINKED ISSUE #11144: Remove Challenge Program issue template
https://github.com/tikv/tikv/blob/7b2e71ac6f844b979e33fe7d74f9cc9d0b00eab6/.github/ISSUE_TEMPLATE/challenge-program.md

We don't have to setup such an issue template and challenge program can live transparently from the project if there is a further event. Most of time this option in issue template is noise.

### PR DESCRIPTION
**Pull request by tisonkun**
This closes #11144 .

Signed-off-by: tison <wander4096@gmail.com>

### Release note 

```release-note
None
```

/cc @hi-rustin @BusyJay

### CODE REVIEW

**Review by BusyJay — APPROVED** [review]

**Review by hi-rustin — APPROVED** [review]

**Comment by tisonkun** [comment]
cc @BusyJay @skyzh could you help on merging this PR?

**Comment by BusyJay** [comment]
@Connor1996 PTAL, the failed case is probably a bug.

**Pull request merged**
