### PR TITLE
txn: Move ts to each command

### PR DESCRIPTION
**Pull request by longfangsong**
Signed-off-by: longfangsong <longfangsong@icloud.com>

### What problem does this PR solve?

Minor refactor in `src/txn/commands.rs`.

### What is changed and how it works?

Move `ts` to each command and abstract them with a `CommandExt` trait.

### Check List 

Tests 

- Unit test

### CODE REVIEW

**Comment by longfangsong** [comment]
@nrc PTAL.

**Comment by longfangsong** [comment]
> I think it is worth planning the command macro syntax a bit. `Prewrite, Vec<Result<()>>, prewrite, ts => start_ts` is getting a little confusing and if we add more (which I think we will) then it will get worse. Could you have a think about what we'll want in the final version of the macro, and how to make that readable please?

This is exactly what I'm doing now.

Currently I think something like this one is good:
```rust
Prewrite:
    cmd_ty => Vec<Result<()>>,
    tag => prewrite,
    ts => start_ts,
    is_sys_cmd => false,
    can_pipelined => false,
    content => {
        /// The set of mutations to apply.
        mutations: Vec<Mutation>,
        // ...
    }
```

But this pattern got some trouble on `readonly` and several other methods, since they might need a `&self` argument to work, and we cannot use expressions like `self.key_locks.is_empty()` in macros.

Currently, the best solution I have is use another trait, eg:
```rust
pub trait CommandReadonly {
    fn readonly(&self) -> bool;
}
pub trait CommandExt: CommandReadonly {
    // ...
}
```

And if a value is provided in the macro, it will generate the `impl` block:
```rust
$(
        impl CommandReadonly for $cmd {
            fn readonly(&self) -> bool {
                $readonly
            }
        }
)?
```
If no value is provided, then we can impl the `CommandReadonly` trait out of the macro.
The problem of this solution is that the code which want to use the commands might need to import another traits, and I don't really know it is ok.

**Comment by nrc** [comment]
I think you could just use one trait and do the same thing - either implement in the macro, or implement outside for other types.

> and we cannot use expressions like self.key_locks.is_empty() in macros.

I don't understand this, could you say why we can't use such expressions? Or give an example.

**Comment by longfangsong** [comment]
> 
> > and we cannot use expressions like self.key_locks.is_empty() in macros.
> 
> I don't understand this, could you say why we can't use such expressions? Or give an example.

What I want is 
```
command! {
    ResolveLock: 
        cmd_ty: (), tag => resolve_lock, is_sys_cmd => true, readonly => self.key_locks.is_empty() {
        // ...
    }
}
```

but due to macro hygiene, we cannot use `self` here.\

**Comment by nrc** [comment]
I see. Thanks for the explanation. I think the way to do this is to have a default readonly method that returns false, an option for the macro to return true, and for `ResolveLock` to override the method with a manual implementation.

**Comment by longfangsong** [comment]
> for `ResolveLock` to override the method with a manual implementation.

I can't figure out how to do this (override a single method in a trait which has other methods) without using a new trait. Can you show me an example?

And shall we merge this pr first?

**Comment by nrc** [comment]
> And shall we merge this pr first or continue to push further refactors into this pr?

Yes lets merge this as is.

@youjiali1995 @sticnarf @MyonKeminta could one of you take a look please?

**Comment by nrc** [comment]
> I can't figure out how to do this (override a single method in a trait which has other methods) without seperate this method into a new trait. Can you show me an example?

```
trait A {
    fn foo(&self) -> bool;
    fn bar(&self) -> bool {
        false
    }
}

struct B;
struct C;

// Macro generated
impl A for B {
    fn foo(&self) -> bool {
        true
    }
}

// Macro generated
impl A for C {
    fn foo(&self) -> bool {
        true
    }
}

// Manually implemented
impl A for C {
    fn bar(&self) -> bool {
        true
    }
}
```

I think this is a bit simpler than `Command`, but it shows the principle. Is it clear?

**Comment by longfangsong** [comment]
> > I can't figure out how to do this (override a single method in a trait which has other methods) without seperate this method into a new trait. Can you show me an example?
> 
> ```
> trait A {
>     fn foo(&self) -> bool;
>     fn bar(&self) -> bool {
>         false
>     }
> }
> 
> struct B;
> struct C;
> 
> // Macro generated
> impl A for B {
>     fn foo(&self) -> bool {
>         true
>     }
> }
> 
> // Macro generated
> impl A for C {
>     fn foo(&self) -> bool {
>         true
>     }
> }
> 
> // Manually implemented
> impl A for C {
>     fn bar(&self) -> bool {
>         true
>     }
> }
> ```
> 
> I think this is a bit simpler than `Command`, but it shows the principle. Is it clear?

The compiler will complain about conflicting implementation for `C` in this way.

**Comment by nrc** [comment]
> The compiler will complain about conflicting implementation for C in this way.

Ah, indeed, my mistake. You can have multiple `impl`s with no trait, but not for trait `impl`s.

So I think the macro needs to get a bit smarter. Either you have to take an ident token to use as self, or you could take the entire function as an item token stream (iirc). Either way, you can make it optional so that most macro instantiations don't need to use it.

**Pull request merged**
