### PR TITLE
sst_importer: always use the bottommost compression (zstd) when writing SSTs (#10577)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #10577 to release-5.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/10644
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/10644:release-5.1-3f0c72a389b4
```

---

### What problem does this PR solve?

Problem Summary:

When using BR-Restore or Lightning-Local-backend, TiKV will need to generate an SST file on-the-fly to be ingested later. These SST files are constructed with the default "fastest" compression algorithm, which is Lz4 at the moment.

The Lz4 algorithm however may be too weak for our tasks here, since the ingested SSTs are intended to be placed to the deepest level (6), especially for BR-Restore. We should be using Zstd rather than Lz4. Without using Zstd, the restored database occupies 1.5× more space than expected.

### What is changed and how it works?

Changed the sst_importer to explicitly use the "bottommost" compression settings when producing SSTs, which the default is Zstd. 

What's Changed:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
        - Zstd is more resource intensive than Lz4.

### Release note 

```release-note
Database restored from BR or Lightning Local-backend is now smaller, should be matching the original cluster size when backed up.
```

### CODE REVIEW

**Review by glorv — APPROVED** [review]

**Review by kennytm — APPROVED** [review]

**Comment by kennytm** [comment]
/test 

https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/7917/pipeline #9404

**Comment by kennytm** [comment]
/test

https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/7924/pipeline

```
curl: (6) Could not resolve host: fileserver2.pingcap.net; Unknown error
```

**Pull request closed without merging**
