### PR TITLE
copr: Add vectorize `bit_count`

### PR DESCRIPTION
**Pull request by Aloxaf**
Signed-off-by: Aloxaf <aloxafx@gmail.com>

PCP #5751 

###  What have you changed?

Add vectorize `bit_count`

###  What is the type of the changes?

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?

- Unit test
- Integration test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No

###  Does this PR affect `tidb-ansible`?

No

### CODE REVIEW

**Comment by Aloxaf** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/104

**Comment by Aloxaf** [comment]
@sre-bot /run-integration-copr-test copr-test=pr/104

**Comment by TennyZhuang** [comment]
LGTM

**Comment by Aloxaf** [comment]
@sre-bot /run-all-tests

**Pull request merged**
