### PR TITLE
raftstore: disable table split by default

### PR DESCRIPTION
**Pull request by overvenus**
###  What have you changed?

Disable table split by default.

###  What is the type of the changes?

- Engineering (engineering change which doesn't change any feature or fix any issue)

###  How is the PR tested?

- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No

###  Does this PR affect `tidb-ansible`?

No

### CODE REVIEW

**Comment by overvenus** [comment]
In case frequent `create/drop table` leads to too many regions.

**Comment by Connor1996** [comment]
what if hot small tables group into one region?

**Comment by overvenus** [comment]
> what if hot small tables group into one region?

TiDB will split regions before creating table.

**Pull request merged**
