### PR TITLE
Copr: Add year_week_with_mode and year_week_without_mode

### PR DESCRIPTION
**Pull request by koushiro**
Signed-off-by: koushiro <koushiro.cqx@gmail.com>

## What have you changed? (mandatory)

Implement builtin function: `year_week_with_mode` and `year_week_without_mode`.

## What are the type of the changes? (mandatory)

- Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)

unit test

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

no

## Does this PR affect tidb-ansible update? (mandatory)

no

## Refer to a related PR or issue link (optional)

[#3275](https://github.com/tikv/tikv/issues/3275)

### CODE REVIEW

**Comment by koushiro** [comment]
Repeat with the [#PR](https://github.com/tikv/tikv/pull/3876) ...
:tired_face:

**Comment by huachaohuang** [comment]
Oops, #3876 was submitted before this, so I think we will review that first.
@koushiro Thanks anyway, maybe you can try other builtin function?

**Comment by koushiro** [comment]
The specific implementation is the same as [#3876](https://github.com/tikv/tikv/pull/3876). Only the test cases are different.

**Comment by ice1000** [comment]
> The specific implementation is the same as #3876. Only the test cases are different.

Sorry 😅 , but I was talking to the admins about there isn't an issue label (instead of "this issue doesn't have this label).

**Pull request closed without merging**
