### PR TITLE
txn: don't protect rollback for BatchRollback

### LINKED ISSUE #7490: Rollback records of non-existent secondary keys needn't be protected.
### What version of TiKV are you using?

v3.0, v3.1, v4.0

### What did you expect?
Only `cleanup` or `check_txn_status` need to write the protected rollback record.

### What did happened?
`rollback` calls `cleanup` and it writes protected rollback record for all non-exsitent keys which may causes performance regression in heavy contention workload with optimistic transaction. See https://github.com/tikv/tikv/issues/7435

### PR DESCRIPTION
**Pull request by sticnarf**
Signed-off-by: Yilin Chen <sticnarf@gmail.com>

### What problem does this PR solve?

Issue Number: close #7490 

Problem Summary: rollback calls cleanup and it writes protected rollback record for all non-exsitent keys which may causes performance regression in heavy contention workload with optimistic transaction. See #7435

### What is changed and how it works?

What's Changed: Only cleanup or check_txn_status need to write the protected rollback record.

### Related changes

- Need to cherry-pick to the release branch

### Check List

Tests 

- Unit test

### Release note 

Do not protect rollback records written by BatchRollback to improve performance when there are many write conflicts in optimistic transactions.

### CODE REVIEW

**Comment by mahjonp** [comment]
bench result see: https://github.com/tikv/tikv/issues/7490#issuecomment-614641220

**Comment by andylokandy** [comment]
LGTM

**Comment by youjiali1995** [comment]
@MyonKeminta PTAL

**Pull request merged**
