### PR TITLE
metrics: polish the metrics on Raft IO and Raft Propose sections.

### LINKED ISSUE #16251: metrics: Raft IO and Raft Propose sections missing filters `by instance`.
## Bug Report
As the title shows, the nightly metrics has lack of the filters on `instance` in the `Raft IO` and `Raft Propose` parts.

### What version of TiKV are you using?

nightly
### What did you expect?
image

### What did happened?
image

### PR DESCRIPTION
**Pull request by LykxSassinator**
| nightly version | With this pr |
| ------ | ------ |
| image | image |

### What is changed and how it works?

Issue Number: Close #16251

What's Changed:

```commit-message
This pr add missing legend on filtering statistics by TiKV instance in Raft IO and Raft Propose sections.
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by SpadeA-Tang** [comment]
We can post a comparison of the effects.

**Comment by LykxSassinator** [comment]
> We can post a comparison of the effects.

Already specified in the issue: #16251, and Supplemented more details in the description.

**Review by overvenus — APPROVED** [review]

**Review by SpadeA-Tang — APPROVED** [review]

**Pull request merged**
