### PR TITLE
*: downgrade rust to 2021-01-16

### LINKED ISSUE #9765: Built-in profiling can cause a segmentation fault
### What version of TiKV are you using?

Latest nightly: dc8ce2cf6a8904cb3dad556f71b11bac3531689b

### What operating system and CPU are you using?

Linux. It happens on both CentOS 7 (3.10.0-957.27.2.el7.x86_64) and Arch Linux (5.11.2-arch1-1).

### Steps to reproduce

Run YCSB workloada on a 3-node TiKV cluster. Meanwhile, get `http://{TiKV_IP}:20180/debug/pprof/profile?seconds=30`.

### What did you expect?

Get a CPU profiling flamegraph.

### What did happened?

A segmentation fault happens. Backtrace of the core:

```
Program terminated with signal SIGSEGV, Segmentation fault.
[Current thread is 1 (Thread 0x7ff7f83fe640 (LWP 162560))]
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /data/deploy/tikv-20160/bin/tikv-server.
Use `info auto-load python-scripts [REGEXP]' to list them.
(gdb) bt
#0  x86_64_fallback_frame_state (context=0x7ff7f83d6a50, context=0x7ff7f83d6a50, fs=0x7ff7f83d6b40) at ./md-unwind-support.h:63
#1  uw_frame_state_for (context=0x7ff7f83d6a50, fs=0x7ff7f83d6b40) at /build/gcc/src/gcc/libgcc/unwind-dw2.c:1271
#2  0x00007ff83337433b in _Unwind_Backtrace (trace=0x556d67bdcd00 <backtrace::backtrace::libunwind::trace::trace_fn>, trace_argument=0x7ff7f83d6f40) at /build/gcc/src/gcc/libgcc/unwind.inc:302
#3  0x0000556d688c5d97 in perf_signal_handler ()
#4  <signal handler called>
#5  0x0000556d6832d941 in crossbeam_deque::Stealer<T>::steal_batch_and_pop ()
#6  0x0000000000010830 in ?? ()
#7  0x0000000000000000 in ?? ()
```

Frame 5 has many possibilities, it may not be `crossbeam_deque::Stealer<T>::steal_batch_and_pop`.

### PR DESCRIPTION
**Pull request by sticnarf**
### What problem does this PR solve?

Issue Number: close #9765

### What is changed and how it works?

Change the rust toolchain version back to before https://github.com/rust-lang/rust/pull/77885.

However, the side effect is that https://github.com/tikv/tikv/issues/9444 will be broken again :(

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

### Release note 

- No release note.

### CODE REVIEW

**Review by BusyJay — APPROVED** [review]

**Review by tabokie — APPROVED** [review]

**Comment by sticnarf** [comment]
Test failed https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/45206/nodes/206/steps/678/log/?start=0 (already reported https://github.com/tikv/tikv/issues/8700 )

**Pull request merged**
