### PR TITLE
dr-auto-sync: enable min-resolved-ts report by default

### PR DESCRIPTION
**Pull request by lhy1024**
Signed-off-by: lhy1024 <admin@liudos.us>

### What is changed and how it works?

Issue Number: Ref https://github.com/tikv/tikv/issues/13219

What's Changed:

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
dr-auto-sync: enable min-resolved-ts report by default
```

### CODE REVIEW

**Review by nolouch — APPROVED** [review]
LGTM.
BTW, make commit message  be `resolved_ts: enable min-resolved-ts report by default` more suitable.

**Review by disksing — APPROVED** [review]

**Comment by fengou1** [comment]
EBS based snapshot depends on the feature enabled by default.
Here I share some test results, we use this global min resolved ts to do EBS backup and restore. the sync-diff and snapshot checksum show it works as expected.

**Pull request merged**
