### PR TITLE
cgroup: fix a bug about mountinfo of cpuset,cpu (#11029)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #11029 to release-5.2
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/11050
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/11050:release-5.2-ba3a2e46cd70
```

---

Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve?

Multiple controllers can share one mountinfo line. Without the patch only the first controller will be attached with the mountinfo, which is incorrect.

Close https://github.com/tikv/tikv/issues/11037.

### What is changed and how it works?

Attach multiple controllers with one mountinfo correctly.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by sticnarf — APPROVED** [review]

**Comment by zhouqiang-cl** [comment]
This pr should not merge into v5.2.3, Need to be merge into release-5.2 later

**Pull request merged**
