### PR TITLE
associate a buffer to AggFuncExpr to reduce memory alloc.

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

## What have you changed? (mandatory)
Associate a buffer to AggFuncExpr so that TiKV won't alloc it for every row.

## What are the type of the changes? (mandatory)
Improvement.

## How has this PR been tested? (mandatory)
make dev.

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)
No.

## Does this PR affect tidb-ansible update? (mandatory)
No.

### CODE REVIEW

**Comment by siddontang** [comment]
any benchmark result?

**Comment by zhangjinpeng1987** [comment]
rest LGTM, Please add benchmark result.

**Comment by hicqu** [comment]
Branch master:
```
SQL statistics:
queries performed:
read: 92
write: 0
other: 0
total: 92
transactions: 92 (0.31 per sec.)
queries: 92 (0.31 per sec.)
ignored errors: 0 (0.00 per sec.)
reconnects: 0 (0.00 per sec.)

Throughput:
events/s (eps): 0.3065
time elapsed: 300.1930s

total number of events: 92

Latency (ms):
min: 2952.95
avg: 3262.95
max: 3640.41
95th percentile: 3574.99
sum: 300191.47

Threads fairness:
events (avg/stddev): 92.0000/0.00
execution time (avg/stddev): 300.1915/0.00
```

Branch count-asterisk (this PR):
```
sysbench result with branch in sub-task-1:
SQL statistics:
queries performed:
read: 106
write: 0
other: 0
total: 106
transactions: 106 (0.35 per sec.)
queries: 106 (0.35 per sec.)
ignored errors: 0 (0.00 per sec.)
reconnects: 0 (0.00 per sec.)

Throughput:
events/s (eps): 0.3506
time elapsed: 302.3701s
total number of events: 106

Latency (ms):
min: 2713.62
avg: 2852.53
max: 3022.75
95th percentile: 2985.89
sum: 302368.50

Threads fairness:
events (avg/stddev): 106.0000/0.00
execution time (avg/stddev): 302.3685/0.00
```

The sysbench test runs a `select count(*)` on a table with 5000W records, in 1 client thread. In the bench result, the QPS increases from **0.31** to **0.35**, and the avg latency decreases from **3.26s** to **2.85s**.

**Comment by siddontang** [comment]
Cool

**Pull request merged**
