### PR TITLE
update pprof

### LINKED ISSUE #14224: pipe fd leaks in tikv-6.1.0 with cpu profiler running
### The problem description
+ **See **"What did you expect"** and **"What did happen"** sections**

### What version of TiKV are you using?

tikv-6.1.0
### What operating system and CPU are you using?

CentOS-7, Linux-3.10.0-514.16.1.el7.x86_64
### Steps to reproduce

Note: If one finds this section difficult to read, he/she might go to **"Conclusion - Root cause"** and **"Explanation of the root cause"** sections and then return to this one.

#### Basic Environment in tidb/tikv.
**(1) quite a certain amount of write requests on the tidb cluster;**
(This is to trigger frequent rocksdb compaction)
**(2) configuration rocksdb.max-sub-compactions >= 2;**
(Enable parallel subcompactions from L0 to deeper-level, in order to create `short-term` threads.)
**(3) promethus for `tidb-6.1.0` is running, with `continuous-profiling.enable = true`;**
(step-(3) is optional, see Way-2)

#### Two ways to reproduce:
Based on the Basic Environment, two ways are proposed;
+ **Way-1. In a tidb/tikv-6.1.0 cluster, with the following conditions:**
**(1) Deploy promethus servers(including ng-monitoring-server) and Keep them running;**
**(2) In at least one ng-monitoring-server, set continuous-profiling.enable = true (by default in 6.1.0);**
(step-(2) is to activate the cpu profiling in tikv from promethus.)
This is the kind of environment in which we met the case and took troubleshooting to find the root cause.

**Note: Way-1 can be generalized as Way-2, in which promethus is not requied but just the tidb/tikv/pd components.**

+ **Way-2. A more general way is to send http requests to tikv-status-server (6.1.0) with conditions:**
**(1) Make sure that tidb/tikv servers receive quite a certain amount of write requests from user/sysbench;**
**(2) Send http requests to tikv-status-server with uri "/debug/pprof/profile";**

for example, if the tikv status-server port is 20180 (by default), execute the following shell command on a tikv host:
```
#### Activate the cpu profiler in tikv once.
#### One can execute this multiple times.
#f=99; time curl  -X GET  "http://127.0.0.1:20180/debug/pprof/profile?seconds=10&frequency=${f}"`; echo "response-length: `echo -e \"${out}\" | wc -c`";
```

At the same time, one can monitor the count of pipe fd(s) opened in tikv-server:
```
#### commands for monitoring the number of pipe fds for a period:
#### You should change the pid for tikv-server. You could redirect the output into a file.
#pid=13579; while true; do dt=`date '+%Y-%m-%dT%H:%M:%S'`; echo "======== ${dt} ========"; ls  -l  /proc/${pid}/fd | grep -c 'pipe'; sleep 0.8; done
```

### What did you expect?
We are running tidb clusters with quite a certain amount of QPS/TPS, in which tikv plays an important role (also with promethus servers running). One tidb cluster, including all the components such as tidb/tikv/pd/promethus/..., was upgraded to v6.1.0 from v5.4.1.
### What did happen?
One day, one instance in the `tikv-6.1.0` cluster (3 nodes) crashed with **`"Panic ... Too many open files"`** error in `tikv.log`. And we found **fd leaks** on all the three tikv-6.1.0 instances in the cluster, where the leaked fds were **(anonymous) pipes**.

tikv-server would crash once the number of opened fd(s) in tikv is over the limit (ulimit -f) due to continuous fd leaks.

So the chain is:
**`tikv-6.1.0-crashes (panic) <== "too many open files" error <== open files over limit <== anonymous pipe fd leaks in tikv-6.1.0.`**

#### Some detail in our case
The speed of pipe fd leaks is about ***1000 per hour***, which in other words is about _20,000 ~ 25,000 fd(s) per day_.
The open file limit (got by `ulimit -f`) is _1,000,000 (1 million)_. 
So a `tikv-6.1.0` instance would crash due to the above error in about _50 days_.

Actually, we found that the tikv instance crashed 54 days after its upgrading from 5.4.1 to 6.1.0.
And this indicated possible relation between the upgrading to tikv-6.1.0 and pipe fd leaks.

### Conclusion - Root cause

In simplicity, the root cause in tikv is that
+ **`the pprof module used in tikv-6.1.0 causes pipe fd leaks during cpu profiling with short-term threads.`**
> Short-term threads here means the threads created to do their jobs and then exit in the middle of the owner process life-time.

The cause in pprof-rs is that
+ **`pprof integrated in tikv would leave the fds opened in short-term threads after they exit.**

+ To see the details of pprof, please refer to this issue:
tikv/pprof-rs#197

#### others to say
+ `Logically, no such problem in tikv-5.4.1`? (the version before upgrading to 6.1.0).
It is supposed to be **_NO_** (no such problem). We read the relevent code, but we did not test it yet.

### Possible solutions
+ Use tikv version other than 6.1.0 or any one without this problem. (deploy-level)
+ In promethus (deploy-level), configure ng-monitoring-server such that continuous-profiling.enable = false and restart it, i.e. disable the cpu profiling.
(I have no resource to build a new environment right now to test this. Anyway, this is probably a workaround)
+ In tikv (project-level), use a pprof-rs version that does not introduce addr_validate module or do not use `frame-pointer` feature.
+ Wait for the issue to be solved. (source-code-level)
tikv/pprof-rs#197

### PR DESCRIPTION
**Pull request by tabokie**
### What is changed and how it works?

Issue Number: Close #14224

What's Changed:

```commit-message
Fix fd leak caused by continuous profiling
```

### Related changes

https://github.com/tikv/pprof-rs/pull/198

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

```release-note
Fix fd leak caused by continuous profiling
```

### CODE REVIEW

**Review by mornyx — APPROVED** [review]

**Comment by mornyx** [comment]
LGTM
/cc @YangKeao PTAL

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by YangKeao — APPROVED** [review]
LGTM

**Pull request merged**
