### PR TITLE
config: adjust rocksdb background compaction threads

### PR DESCRIPTION
**Pull request by glorv**
### What is changed and how it works?

Issue Number: ref #14470

What's Changed:

```
#15723 change the default rocksdb background compaction threads to cpu-num * 1/8, this default config is too small that it can easily trigger flow control because for a 8c instance there is only 1 compaction thread. If there is a on-going slow compaction, it can block the lockcf's compaction and triggers flow control. This PR changes the default to cpu-num * 1/4
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by SpadeA-Tang — APPROVED** [review]

**Comment by glorv** [comment]
@bufferflies @SpadeA-Tang PTAL.
I originally wanted to file this PR as long as the lockcf's write-buffer adjustment. But due to benchbot test failure in the last weekends, we may merge this PR first to avoid triggering other performance test regression.

**Review by bufferflies — APPROVED** [review]

**Pull request merged**
