### PR TITLE
server: add size metric for grpc messages

### PR DESCRIPTION
**Pull request by 5kbpers**
Signed-off-by: 5kbpers <tangminghua@pingcap.com>

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:
Add size metric for grpc messages.

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

Side effects

- Performance regression
    - Consumes more CPU

### Release note 
* N/A

### CODE REVIEW

**Comment by yiwu-arbug** [comment]
Can we also add a chart with multiple write amp related metrics showing together?

**Comment by 5kbpers** [comment]
> Can we also add a chart with multiple write amp related metrics showing together?

Sure, actually I reorganized them to a dashboard https://gist.github.com/5kbpers/290c4e7af9d58de2db5e19bf98b2cf31

**Pull request closed without merging**
