### PR TITLE
log-backup: limit inflight raft msg from pitr

### LINKED ISSUE #13977: pitr panic due to raft ready too large
### What version of TiKV are you using?

6.5

### What operating system and CPU are you using?

N/A

### Steps to reproduce

See #13848.

### PR DESCRIPTION
**Pull request by tabokie**
Signed-off-by: tabokie <xy.tao@outlook.com>

### What is changed and how it works?

Issue Number: Close #13977

What's Changed:

```commit-message
```

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by tabokie** [comment]
the fix was verified by @joccau

**Review by YuJuncen — APPROVED** [review]

**Review by joccau — APPROVED** [review]
LGTM

**Review by 3pointer — APPROVED** [review]

**Review by BusyJay — APPROVED** [review]

**Pull request merged**
