### PR TITLE
fix wrong coprocessor alert rules (#10792)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #10792 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/10795
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/10795:release-4.0-3cf549ac9195
```

---

Signed-off-by: tabokie <xy.tao@outlook.com>

### What problem does this PR solve?

Problem Summary:

Coprocessor error type "lock" is renamed to "meet_lock" in #5155

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tabokie — APPROVED** [review]

**Review by youjiali1995 — APPROVED** [review]

**Comment by youjiali1995** [comment]
Please add cherry-pick-approved label. @tikv/qa-release-merge

**Pull request merged**
