### PR TITLE
coprocessor: differentiate real/int/decimal for `not` expression (#5005)

### PR DESCRIPTION
**Pull request by eurekaka**
cherry-pick https://github.com/tikv/tikv/pull/5005

TiPB change: https://github.com/pingcap/tipb/pull/174
TiDB change: https://github.com/pingcap/tidb/pull/15916

### CODE REVIEW

**Comment by eurekaka** [comment]
@breeswish @lonng PTAL

**Comment by breeswish** [comment]
/run-all-tests tidb=release-3.0 pd=release-3.0 tidb-test=release-3.0

**Pull request merged**
