### PR TITLE
Fix the problem that CDC and log-backup didn't use advance-ts-interval to limit the timeout of check_leader

### LINKED ISSUE #17107: check_leader of resolved_ts used in CDC and log-backup always uses default timeout which is 5s
## Bug Report

When `check_leader` of resovled_ts is called on a unreachable (e.g. stopped) TiKV node, it might take too long time to fail, and may introduce lags to resolved_ts. [This PR](https://github.com/tikv/tikv/pull/16943) tries to limit the timeout of `check_leader` with the configuration `advance-ts-interval`, but it didn't cover CDC and log-backup. So when CDC is used, even with `advance-ts-interval` set to a very small value, it can still be observed that resolved-ts lags for too long time during TiKV upgrading.

Ref: https://github.com/tikv/tikv/issues/16698

### PR DESCRIPTION
**Pull request by MyonKeminta**
### What is changed and how it works?

Issue Number: Close #17107
Ref #16698

What's Changed:

```commit-message
Fix the problem that CDC and log-backup didn't use advance-ts-interval to limit the timeout of check_leader
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
Fix the problem that CDC and log-backup didn't use advance-ts-interval to limit the timeout of check_leader.
```

### CODE REVIEW

**Comment by MyonKeminta** [comment]
@crazycs520 PTAL thanks!

**Review by cfzjywxk — APPROVED** [review]
LGTM

**Review by overvenus — APPROVED** [review]

**Pull request merged**
