### PR TITLE
cdc: handles unordered prewrites on one same key

### LINKED ISSUE #17502: prewrite generation should be sent to TiCDC
### What did you expect?

Pipelined DML introduces a new field `generation` to `Prewrite` commands. This should be sent to TiCDC to help TiCDC sort unordered `Prewrite`s on one same key.

### PR DESCRIPTION
**Pull request by hicqu**
### What is changed and how it works?

Issue Number: Close #17502 

What's Changed:

```commit-message
add generation field into TiCDC Prewrite events
```

### Related changes

- [ ] PR to update `pingcap/docs`/`pingcap/docs-cn`:
- [ ] Need to cherry-pick to the release branch

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by zhangjinpeng87** [comment]
@hicqu Any design doc we can refer to?

**Review by MyonKeminta — APPROVED** [review]
LGTM. @ekexium PTAL.

**Review by 3AceShowHand — APPROVED** [review]

**Pull request merged**
