### PR TITLE
raftstore: handle read requests committed in last term correctly

### LINKED ISSUE #7402: one of tikv nodes crushed down during testing
## Question

I deployed a tikv cluster with binary files on centos for test env with 1 pd and 3 tikv nodes. After working for about 18 hours, one of the tikv nodes crushed down. I want to know whether is there anything wrong with my operation or configuration.

**Key configuration**

// pd
[replication]
max-replicas = 1
[schedule]
max-merge-region-size = 20
max-merge-region-keys = 200000
split-merge-interval = "1h"
max-snapshot-count = 3
max-pending-peer-count = 16
max-store-down-time = "30m"
leader-schedule-limit = 4
region-schedule-limit = 4
replica-schedule-limit = 8
merge-schedule-limit = 8
tolerant-size-ratio = 5.0

**log when crush down**
```
[2020/04/09 05:36:16.239 +08:00] [INFO] [peer.rs:1415] ["notify pd with change peer region"] [region="id: 21 start_key: 2D73746F72616765BC10B69CC1CEEEFE5B741E5A427247DE457AADF91B19634319D365DFEBB955824C3CD1DF104F941469E8C657C56FD5C26B2202F0 end_key: 2D73746F72616765BC10B69CC1CEEEFE5B741E5A427247DE457AADF91E89FC480698BC1C60905F1561F571667F71313E7DC4C1CD079D3335F9752D67 region_epoch { conf_ver: 10 version: 8 } peers { id: 107 store_id: 4 }"] [peer_id=107] [region_id=21]
[2020/04/09 05:36:28.218 +08:00] [INFO] [peer.rs:450] ["deleting applied snap file"] [snap_file=21_6_1793999] [peer_id=107] [region_id=21]
[2020/04/09 05:36:28.225 +08:00] [INFO] [peer.rs:450] ["deleting applied snap file"] [snap_file=65_6_619110] [peer_id=106] [region_id=65]
[2020/04/09 05:36:32.406 +08:00] [FATAL] [lib.rs:499] ["assertion failed: `(left == right)`\n  left: `[23, 72, 161, 100, 118, 81, 72, 150, 153, 116, 237, 163, 124, 47, 59, 220]`,\n right: `[162, 136, 174, 153, 78, 10, 77, 97, 137, 178, 123, 129, 82, 88, 195, 182]`"] [backtrace="stack backtrace:\n   0:     0x7f472c1faa5d - backtrace::backtrace::libunwind::trace::h958f5f3eb75b2917\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/libunwind.rs:54\n                         - backtrace::backtrace::trace::hdf994f7eb3c12b81\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/mod.rs:70\n   1:     0x7f472c1f0730 - tikv_util::set_panic_hook::{{closure}}::hf6c0260b2e4aea39\n                        at /home/jenkins/.target/release/build/backtrace-e20a32a05fd0b8fe/out/capture.rs:79\n   2:     0x7f472c39a78f - std::panicking::rust_panic_with_hook::h8d2408723e9a2bd4\n                        at src/libstd/panicking.rs:479\n   3:     0x7f472c39a56d - std::panicking::continue_panic_fmt::hb2aaa9386c4e5e80\n                        at src/libstd/panicking.rs:382\n   4:     0x7f472c39a51b - std::panicking::begin_panic_fmt::h1c91fada5a982dcd\n                        at src/libstd/panicking.rs:337\n   5:     0x7f472b8a8231 - tikv::raftstore::store::peer::Peer::handle_raft_ready_apply::h7a466f270c836fdb\n                        at src/raftstore/store/peer.rs:0\n

…………
```

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve?

Although follower read is not supported in release 3.0, there are still some requests could be proposed when the peer works as leader, and handled when the peer has losted the leadership. This could cause TiKV panic.

Issue Number: close #7402 .

### What is changed and how it works?

What's Changed:

The bug has already been fixed in master branch. So this PR ports the new implementation of `read_queue` from master branch.

For details the PR contains:
- #6396, which extracts ReadIndexQueue into a file.
- #6637, which clears `context` when role change so that it won't panic.
- #7101, which makes tikv handles pending reads correctly when retake leadership.
- #7313, which makes tikv handles out of order ReadIndexResp correctly.

These bugs can occur in release 3.0, just like #7402 .

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 
handle raftstore read requests committed in last term correctly

### CODE REVIEW

**Comment by BusyJay** [comment]
Too many changes, I'm afraid it may introduce more bugs than it needs to fix.

**Comment by hicqu** [comment]
@BusyJay I think all bug fixes in master branch about read queue is needed. Those fixes are almost in read_queue.rs. We can make a list about them to make it more clear.

**Comment by hicqu** [comment]
@BusyJay I have updated the PR description to include all bug fixes by the PR. Please take a look.

**Pull request closed without merging**
