### PR TITLE
copr: support enum type for in function

### PR DESCRIPTION
**Pull request by wshwsh12**
Signed-off-by: wshwsh12 <793703860@qq.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/24561 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:
Support extracting bytes/int from Enum type for IN function.

### Check List 

Tests 

- Unit test
- Integration test

Side effects

### Release note 
- No release note.

### CODE REVIEW

**Comment by skyzh** [comment]
I wonder why we should handle `Enum` specifically in this case. We could already automatically cast enum to int, and therefore it is not necessary to implement enum variant for functions like `in`, `cast`, etc. This is something that should be handled in codegen.

So the first thing I would like to know is that, why can't we directly call `in` function with enum as input?

**Comment by skyzh** [comment]
Okay, I got the point. When calling `extract`, the value is still some kind of raw value, which is not covered by what we have done before. I think the current approach is good enough.

By the way, why not directly compare int value of enum, which should be a lot more efficient?

**Comment by wshwsh12** [comment]
Because tidb will push IfStringSig to TiKV..

**Comment by skyzh** [comment]
Got it. This patch looks reasonable to me.

**Comment by Xuanwo** [comment]
We can't implement Extract for Enum? It looks so wired for me to handle extra case in this trait.

**Comment by skyzh** [comment]
> We can't implement Extract for Enum? It looks so wired for me to handle extra case in this trait.

Then we may need an extra signature for push down, and this adds extra engineering effort... But I can't come up with a better solution in the current framework.

**Review by skyzh — APPROVED** [review]
LGTM. Hope there are no more places where we need to handle the special cases for enum 😂😂😂

**Comment by skyzh** [comment]
If it is possible to go a step further and write a new function for `in_enum`, I also suggest first mapping those strings to integer in enum and then compare enum by their integer values. This should be a lot more efficient.

**Review by Xuanwo — APPROVED** [review]
Looks not good to me, but there is no better choices.

**Pull request merged**
