### PR TITLE
metrics: support multi k8s in grafana dashboards

### LINKED ISSUE #12104: support multi-k8s in grafana dashboards
## Feature Request

K8s community and organizations are increasingly deploying multiple Kubernetes clusters to improve availability, isolation and scalability. Since TiDB Operator have support [deploying tidb across-kubernetes](https://docs.pingcap.com/tidb-in-kubernetes/dev/deploy-tidb-cluster-across-multiple-kubernetes), propose to add an `k8s_cluster` and `tidb_cluster` label to address the multi-k8s issue without affecting existing single-cluster use case.

### PR DESCRIPTION
**Pull request by just1900**
### What is changed and how it works?

Issue Number: close #12104

K8s community and organizations are increasingly deploying multiple Kubernetes clusters to improve availability, isolation and scalability. Since TiDB Operator have support [deploying tidb across-kubernetes](https://docs.pingcap.com/tidb-in-kubernetes/dev/deploy-tidb-cluster-across-multiple-kubernetes), this PR will address the multi-k8s issue without affecting existing single-cluster use case.

What's Changed:

* add a k8s_cluster label in all expr
* add k8s_cluster variable in Grafana templating

How it works:

* For users with single-k8s, nothing need to be changed, just use it as before.
* For users with multi-k8s:
  * first add `kubernetes` label to identify k8s cluster in your prometheus' `external_labels`.
  * set field "hide" to '0' to show variables in grafana via `sed -i s/"hide": 2/"hide": 0/g <path/to/dashboard.json>`
  * load it to grafana

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
metrics: support multi k8s in grafana dashboards.
```

### CODE REVIEW

**Review by nolouch — APPROVED** [review]
lgtm

**Comment by just1900** [comment]
@nolouch Could you guide me on what else to do to merge this pr?

**Comment by innerr** [comment]
lgtm

**Review by innerr — APPROVED** [review]

**Review by AndreMouche — APPROVED** [review]
LGTM

**Pull request merged**
