### PR TITLE
Call cargo audit and cargo search when necessary

### PR DESCRIPTION
**Pull request by myguyy**
## What have you changed? (mandatory)

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:

- Modified the Makefile so that cargo audit and cargo search don't get called all the time.

## What are the type of the changes? (mandatory)

The currently defined types are listed below, please pick one of the types for this PR by removing the others:

- Misc (other changes)

## How has this PR been tested? (mandatory)

Just `make build`

## Does this PR affect documentation (docs) update? (mandatory)

Nope

## Does this PR affect tidb-ansible update? (mandatory)

Nope

## Refer to a related PR or issue link (optional)

https://github.com/tikv/tikv/issues/4390

### CODE REVIEW

**Comment by myguyy** [comment]
Whoops don't think i want that merge commit included. Not sure how to fix it

**Comment by kennytm** [comment]
The merge commit is fine since we merge PR using "Squash and merge".

**Pull request merged**
