### PR TITLE
Upgrade rust toolchain version

### PR DESCRIPTION
**Pull request by breeswish**
## What have you changed? (mandatory)

This PR upgrades rust toolchain to the latest. This makes our future work of introducing async/await more easier, don't need to worry about the nightly version dependency requires.

## What are the type of the changes? (mandatory)

- Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)

CI.

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

No.

## Does this PR affect tidb-ansible update? (mandatory)

No.

### CODE REVIEW

**Comment by Hoverbear** [comment]
@breeswish We should be careful introducing async/await into our codebase as it is still unstable and subject to change. But I'd like to try it. :)

**Comment by alexcrichton** [comment]
Ah I think @Hoverbear put it well, it's still experimental so I wouldn't critically rely on it, but using it for tests here and there should work great!

**Comment by siddontang** [comment]
em, maybe the best choice is just using in test now. @breeswish

**Comment by breeswish** [comment]
@alexcrichton Is it ok to use the futures-await? Currently it is not possible to use rustc's async / await in our project. I've tried futures-await in [some new PRs](https://github.com/tikv/tikv/pull/3515) and seems to work great! Is there something that can be wrong?

**Comment by siddontang** [comment]
oh, so now it is better for us not to use await/async.  @breeswish 

I think we can close this PR now.

**Comment by breeswish** [comment]
@alexcrichton Thanks for you answer!

**Pull request closed without merging**
