### PR TITLE
server: change TiKvServer to TiKVServer

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
Signed-off-by: zhangjinpeng1987 <zhangjinpeng@pingcap.com>

### What is changed and how it works?

What's Changed:

```commit-message
Typo: change TiKvServer to TiKVServer
```

### Related changes

- No

### Check List 

Tests 

- No code

Side effects

No

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by sticnarf** [comment]
Per https://rust-lang.github.io/api-guidelines/naming.html, if we consider TiKV as a single word, the camel case should be `TikvServer` instead of `TiKVServer`

**Comment by zhangjinpeng1987** [comment]
> Per https://rust-lang.github.io/api-guidelines/naming.html, if we consider TiKV as a single word, the camel case should be `TikvServer` instead of `TiKVServer`

@sticnarf TiKV is a “Distinguished Name”

**Comment by sticnarf** [comment]
> @sticnarf TiKV is a “Distinguished Name”

That doesn't account for using `TiKV` in camel case. If we have to keep the original cases in camel case, why we do not in snake case, for example it's certainly  `modify_tikv_config` instead of `modify_TiKV_config`.

**Comment by BusyJay** [comment]
It's named `TiKv` on purpose to follow rust naming convention. https://github.com/tikv/tikv/pull/12395

**Comment by zhangjinpeng1987** [comment]
> > @sticnarf TiKV is a “Distinguished Name”
> 
> That doesn't account for using `TiKV` in camel case. If we have to keep the original cases in camel case, why we do not in snake case, for example it's certainly `modify_tikv_config` instead of `modify_TiKV_config`.

both TiKV and tikv are acceptable distinguished name, but TiKv or Tikv is not.

**Comment by zhangjinpeng1987** [comment]
> It's named `TiKv` on purpose to follow rust naming convention. #12395

I think TiKv or Tikv is very ugly.

**Comment by zhangjinpeng1987** [comment]
Close this PR since above oppositions.

**Pull request closed without merging**
