### PR TITLE
unsafe recovery: Enable force leader to rollback merge

### LINKED ISSUE #15580: [dr-autosync] online recover time out after switching to backup cluster in sync_recover mode
### What version of TiKV are you using?

v6.4.5

### Steps to reproduce

When the cluster runs in sync_recover mode, shutdown the primary dc, and restore the cluster in the backup dc.
Hit following error when do online unsafe recovery.

client ctl run:
```
[2023/09/12 04:54:46.358 +08:00] [INFO] [cluster.go:397] ["will run cmd"] [cmd:="tiup ctl:v6.5.4 pd -u http://pd3-peer.e2e-dr-auto-sync-with-tiflash-tps-2340579-1-968:2379 unsafe remove-failed-stores --auto-detect"]
2023-09-12T04:54:46.364+0800	INFO	k8s/client.go:132	it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129
```
pd logs:
```
[2023/09/12 05:05:34.903 +08:00] [INFO] [unsafe_recovery_controller.go:430] ["Unsafe recovery store recovery plan execution timeout, retry"] [store-id=5]
[2023/09/12 05:05:34.967 +08:00] [INFO] [unsafe_recovery_controller.go:547] ["{\"info\":\"Unsafe recovery failed: Exceeds timeout 2023-09-12 05:04:46.513196231 +0800 CST m=+745.880814757\",\"time\":\"2023-09-12 05:05:34.967\",\"details\":[\"affected table ids: 113, 83, 84, 88, 111, 140, 281474976710651, 42, 126, 130, 138, 110, 82, 128, 132, 134, 114, 115, 116, 136, 28, 89, 90, 91, 85, 112, 26, 86, 87\"]}"]
```

### What did you expect?
unsafe remove-failed-stores can succeed.

### What did happened?

```
  {
    "info": "Unsafe recovery enters demote failed voter stage",
    "time": "2023-09-12 05:04:32.885",
    "actions": {
      "store 8": [
        "region 278 demotes peers { id:279 store_id:1 }, { id:341 store_id:9 }, { id:373 store_id:6 }"
      ]
    }
  },
  {
    "info": "Unsafe recovery enters force leader stage",
    "time": "2023-09-12 05:04:42.746",
    "actions": {
      "store 5": [
        "force leader on regions: 278"
      ],
      "store 7": [
        "force leader on regions: "
      ],
      "store 8": [
        "force leader on regions: "
      ]
    }
  },
  {
    "info": "Unsafe recovery enters exit force leader stage",
    "time": "2023-09-12 05:04:49.153",
    "details": [
      "triggered by error: Exceeds timeout 2023-09-12 05:04:46.513196231 +0800 CST m=+745.880814757"
    ]
  },
  {
    "info": "Unsafe recovery failed: Exceeds timeout 2023-09-12 05:04:46.513196231 +0800 CST m=+745.880814757",
    "time": "2023-09-12 05:05:34.967",
    "details": [
      "affected table ids: 113, 83, 84, 88, 111, 140, 281474976710651, 42, 126, 130, 138, 110, 82, 128, 132, 134, 114, 115, 116, 136, 28, 89, 90, 91, 85, 112, 26, 86, 87"
    ]
  }
]
```

### PR DESCRIPTION
**Pull request by v01dstar**
### What is changed and how it works?

Issue Number: Close #15580

What's Changed:

```commit-message
Enable force leader to rollback merges when they are not able to proceed, previously, only regions with quorum can do this.
```

### Related changes

N/A

### Check List 

Tests 

- Integration test

Side effects

n/a

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by v01dstar** [comment]
/cc @Connor1996 

PTAL

The reason unsafe recovery was blocked was:

- Demotion can not be proposed since merge state is not none
- Merge state was not able to be cleaned up, merge cannot be rolled back because it can only be proposed if there is a quorum

Will add test case later

**Review by Connor1996 — COMMENTED** [review]
Need to change raftstore-v2 as well

**Comment by v01dstar** [comment]
> Need to change raftstore-v2 as well

For sure, but let's do it separately.

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by tonyxuqqi — APPROVED** [review]

**Comment by v01dstar** [comment]
Manual cherry-picks:

6.5: #15594
7.1: #15595

**Pull request merged**
