### PR TITLE
typo: fix python client demo

### PR DESCRIPTION
**Pull request by ou-bing**
`tikv-client` modified parameter type ？I am using `tikv-client-0.0.3`.

```
client = RawClient.connect("127.0.0.1:2379")
...
Exception: Please use list as pd_endpoints. For example: `RawClient.connect([127.0.0.1:2379])`.
```

### CODE REVIEW

**Comment by glorv** [comment]
LGTM. Thanks for your contribution.  
In order to pass the DCO check, please rebase the commit message with sign. You can do this by the following command:
```
git commit -s --amend
git push your-remote branch_name --force
```

**Comment by ou-bing** [comment]
> LGTM. Thanks for your contribution. In order to pass the DCO check, please rebase the commit message with sign. You can do this by the following command:
> 
> ```
> git commit -s --amend
> git push your-remote branch_name --force
> ```

This problem has been solved. 😄

**Review by glorv — APPROVED** [review]
LGTM

**Pull request closed without merging**
