### PR TITLE
sst_importer: always use the bottommost compression (zstd) when writing SSTs

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve?

Problem Summary:

When using BR-Restore or Lightning-Local-backend, TiKV will need to generate an SST file on-the-fly to be ingested later. These SST files are constructed with the default "fastest" compression algorithm, which is Lz4 at the moment.

The Lz4 algorithm however may be too weak for our tasks here, since the ingested SSTs are intended to be placed to the deepest level (6), especially for BR-Restore. We should be using Zstd rather than Lz4. Without using Zstd, the restored database occupies 1.5× more space than expected.

### What is changed and how it works?

Changed the sst_importer to explicitly use the "bottommost" compression settings when producing SSTs, which the default is Zstd. 

What's Changed:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
        - Zstd is more resource intensive than Lz4.

### Release note 

```release-note
Database restored from BR or Lightning Local-backend is now smaller, should be matching the original cluster size when backed up.
```

### CODE REVIEW

**Comment by kennytm** [comment]
/test

https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/4269/pipeline/

```
[2021-07-15T17:58:57.545Z] thread 'main' panicked at 'assertion failed: check_query_num_read(cluster, store_id, region_id, QueryKind::Get, 1000)', tests/integrations/raftstore/test_stats.rs:317:13
[2021-07-15T17:58:57.545Z] stack backtrace:
[2021-07-15T17:58:57.545Z]    0: rust_begin_unwind
[2021-07-15T17:58:57.545Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:493:5
[2021-07-15T17:58:57.545Z]    1: core::panicking::panic_fmt
[2021-07-15T17:58:57.545Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/panicking.rs:92:14
[2021-07-15T17:58:57.545Z]    2: core::panicking::panic
[2021-07-15T17:58:57.545Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/panicking.rs:50:5
[2021-07-15T17:58:57.546Z]    3: integrations::raftstore::test_stats::test_query_stats::{{closure}}
[2021-07-15T17:58:57.546Z]              at /home/jenkins/tikv-src/tests/integrations/raftstore/test_stats.rs:317:13
[2021-07-15T17:58:57.546Z]    4: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
[2021-07-15T17:58:57.546Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/alloc/src/boxed.rs:1560:9
[2021-07-15T17:58:57.546Z]    5: integrations::raftstore::test_stats::test_query_num
[2021-07-15T17:58:57.546Z]              at /home/jenkins/tikv-src/tests/integrations/raftstore/test_stats.rs:454:5
[2021-07-15T17:58:57.546Z]    6: integrations::raftstore::test_stats::test_query_stats
[2021-07-15T17:58:57.546Z]              at /home/jenkins/tikv-src/tests/integrations/raftstore/test_stats.rs:361:5
[2021-07-15T17:58:57.546Z]    7: integrations::raftstore::test_stats::test_query_stats::{{closure}}
[2021-07-15T17:58:57.546Z]              at /home/jenkins/tikv-src/tests/integrations/raftstore/test_stats.rs:158:1
[2021-07-15T17:58:57.546Z]    8: core::ops::function::FnOnce::call_once
[2021-07-15T17:58:57.546Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5
[2021-07-15T17:58:57.546Z]    9: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}
[2021-07-15T17:58:57.546Z]              at /home/jenkins/tikv-src/components/test_util/src/runner.rs:64:21
[2021-07-15T17:58:57.546Z]   10: core::ops::function::FnOnce::call_once{{vtable.shim}}
[2021-07-15T17:58:57.546Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5
[2021-07-15T17:58:57.546Z]   11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
[2021-07-15T17:58:57.546Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/alloc/src/boxed.rs:1546:9
[2021-07-15T17:58:57.546Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-07-15T17:58:57.546Z] FAILED
[2021-07-15T17:58:57.546Z] test raftstore::test_stats::test_store_heartbeat_report_hotspots ... ok
[2021-07-15T17:58:57.546Z] test raftstore::test_status_command::test_region_detail ... ok
[2021-07-15T17:58:59.453Z] test raftstore::test_tombstone::test_node_readd_peer ... ok
[2021-07-15T17:59:00.390Z] test raftstore::test_tombstone::test_node_tombstone ... ok
[2021-07-15T17:59:03.676Z] test raftstore::test_tombstone::test_safe_tombstone_gc ... ok
[2021-07-15T17:59:05.052Z] test raftstore::test_tombstone::test_server_fast_destroy ... ok
[2021-07-15T17:59:07.584Z] test raftstore::test_tombstone::test_server_readd_peer ... ok
[2021-07-15T17:59:07.584Z] 
[2021-07-15T17:59:07.584Z] failures:
[2021-07-15T17:59:07.584Z] 
[2021-07-15T17:59:07.584Z] failures:
[2021-07-15T17:59:07.584Z]     raftstore::test_stats::test_query_stats
```

**Comment by kennytm** [comment]
/test

https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tikv_ghpr_test/runs/4272/nodes/88/log/?start=0

```
[2021-07-15T19:35:47.618Z] test raftstore::test_hibernate::test_inconsistent_configuration ... thread 'main' panicked at 'assertion failed: awakened.load(Ordering::SeqCst)', tests/integrations/raftstore/test_hibernate.rs:324:5
[2021-07-15T19:35:47.618Z] stack backtrace:
[2021-07-15T19:35:47.618Z]    0: rust_begin_unwind
[2021-07-15T19:35:47.618Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:493:5
[2021-07-15T19:35:47.618Z]    1: core::panicking::panic_fmt
[2021-07-15T19:35:47.618Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/panicking.rs:92:14
[2021-07-15T19:35:47.618Z]    2: core::panicking::panic
[2021-07-15T19:35:47.618Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/panicking.rs:50:5
[2021-07-15T19:35:47.618Z]    3: integrations::raftstore::test_hibernate::test_inconsistent_configuration
[2021-07-15T19:35:47.618Z]              at /home/jenkins/tikv-src/tests/integrations/raftstore/test_hibernate.rs:324:5
[2021-07-15T19:35:47.618Z]    4: integrations::raftstore::test_hibernate::test_inconsistent_configuration::{{closure}}
[2021-07-15T19:35:47.618Z]              at /home/jenkins/tikv-src/tests/integrations/raftstore/test_hibernate.rs:277:1
[2021-07-15T19:35:47.618Z]    5: core::ops::function::FnOnce::call_once
[2021-07-15T19:35:47.618Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5
[2021-07-15T19:35:47.618Z]    6: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}
[2021-07-15T19:35:47.618Z]              at /home/jenkins/tikv-src/components/test_util/src/runner.rs:64:21
[2021-07-15T19:35:47.618Z]    7: core::ops::function::FnOnce::call_once{{vtable.shim}}
[2021-07-15T19:35:47.618Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5
[2021-07-15T19:35:47.618Z]    8: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
[2021-07-15T19:35:47.618Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/alloc/src/boxed.rs:1546:9
[2021-07-15T19:35:47.618Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-07-15T19:35:47.618Z] FAILED
```

**Review by glorv — APPROVED** [review]

**Comment by kennytm** [comment]
/test

#7574  https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/4972/pipeline

```
[2021-07-28T11:48:21.667Z] test raftstore::test_merge::test_merge_approximate_size_and_keys ... thread 'main' panicked at 'failed to transfer leader to [1] id: 3 store_id: 3, current leader: Some(id: 1 store_id: 1)', /home/jenkins/tikv-src/components/test_raftstore/src/cluster.rs:1223:17
[2021-07-28T11:48:21.667Z] stack backtrace:
[2021-07-28T11:48:21.667Z]    0: rust_begin_unwind
[2021-07-28T11:48:21.667Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:493:5
[2021-07-28T11:48:21.667Z]    1: std::panicking::begin_panic_fmt
[2021-07-28T11:48:21.667Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/std/src/panicking.rs:435:5
[2021-07-28T11:48:21.667Z]    2: test_raftstore::cluster::Cluster<T>::must_transfer_leader
[2021-07-28T11:48:21.667Z]              at /home/jenkins/tikv-src/components/test_raftstore/src/cluster.rs:1223:17
[2021-07-28T11:48:21.667Z]    3: integrations::raftstore::test_merge::test_merge_approximate_size_and_keys
[2021-07-28T11:48:21.667Z]              at /home/jenkins/tikv-src/tests/integrations/raftstore/test_merge.rs:611:5
[2021-07-28T11:48:21.667Z]    4: integrations::raftstore::test_merge::test_merge_approximate_size_and_keys::{{closure}}
[2021-07-28T11:48:21.667Z]              at /home/jenkins/tikv-src/tests/integrations/raftstore/test_merge.rs:586:1
[2021-07-28T11:48:21.667Z]    5: core::ops::function::FnOnce::call_once
[2021-07-28T11:48:21.667Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5
[2021-07-28T11:48:21.667Z]    6: test_util::runner::run_test_with_hook::{{closure}}::{{closure}}
[2021-07-28T11:48:21.667Z]              at /home/jenkins/tikv-src/components/test_util/src/runner.rs:64:21
[2021-07-28T11:48:21.667Z]    7: core::ops::function::FnOnce::call_once{{vtable.shim}}
[2021-07-28T11:48:21.667Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/core/src/ops/function.rs:227:5
[2021-07-28T11:48:21.667Z]    8: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
[2021-07-28T11:48:21.667Z]              at /rustc/16bf626a31cb5b121d0bca2baa969b4f67eb0dab/library/alloc/src/boxed.rs:1546:9
[2021-07-28T11:48:21.667Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Pull request merged**
