### PR TITLE
*: fix forward report and use more forward connections (#9906)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #9906 to release-5.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/9926
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/9926:release-5.0-9cd094d4218f
```

---

### What problem does this PR solve?

Problem Summary:

Too small value can lead to imbalance load.

The new panel looks like:
image

### Check List 

Tests 

- Unit test
- Integration test
- Manual test

### Release note 
- no release note.

### CODE REVIEW

**Review by youjiali1995 — APPROVED** [review]

**Review by MyonKeminta — APPROVED** [review]
LGTM.  Should this be merged into 5.0 ga?

**Pull request merged**
