### PR TITLE
reader/backward_scanner: Remove near_seek_for_prev from backward_scanner

### PR DESCRIPTION
**Pull request by MyonKeminta**
Signed-off-by: MyonKeminta <MyonKeminta@users.noreply.github.com>

## What have you changed? (mandatory)

This PR is merging to #3344 .
In this PR, `near_seek_for_prev` call is removed from `BackwardScanner`. The logic of `near_seek_for_prev` was put in `BackwardScanner` itself.

## What are the type of the changes? (mandatory)

- Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)

By already-existed unit tests

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No

### CODE REVIEW

**Comment by breeswish** [comment]
LGTM

**Comment by MyonKeminta** [comment]
Ah, I didn't notice that. I haven't run tests before submitting PR. If CI fails I'll fix it then.

**Comment by breeswish** [comment]
Interesting.. CI passed.. Our existing tests are not strong enough and this case is not covered 🤣

**Pull request merged**
