### PR TITLE
add verkv unimplemented functions

### PR DESCRIPTION
**Pull request by fredchenbj**
Signed-off-by: fredchenbj <cfworking@163.com>

### What problem does this PR solve?

add `verkv` unimplemented rpc functions to make update `kvproto` work.

### CODE REVIEW

**Comment by fredchenbj** [comment]
@kennytm how to manually merge this pr?

**Comment by kennytm** [comment]
```
[2020-04-14T15:10:11.348Z] Statement: #819 -  SELECT STRCMP( '23:10:42.007765', `col_bigint_unsigned` ) AS field1, `col_varbinary_32` NOT LIKE `col_set` AS field2, `col_tinyint_unsigned_key` IS FALSE AS field3, ( INTERVAL( `col_bit`, ( INTERVAL( '2018-04-26 10:38:03.031949', `col_char_2`, NULL ) ), `col_varchar_1_key` ) ) NOT BETWEEN NULL AND NULL AS field4, COALESCE( '2018-04-27', -26901, ( `col_float_unsigned_key` <=> ( `col_float_unsigned_key` > 'pcbqbfmwpebbkyfsxemhlybhtahsdfttztbnrqjpdtwjharagadcroqtxlefjrhcokdymxvanwfvayfdbhtoxwppiavhgmizbrrxgafhbcxkosudjiyckygmuatynejcqwwbclkmfhgrrenyxlyawqekkchtjzebuphvkwswxbtqsjokzalmxfaklbeukgslyqnrheytuhbqsbseiojnyxesmnsdfyyisxjoljtdmdxwycmyxfnxnojmst' ) ), `col_binary_8_key`, `col_char_255` ) AS field5 FROM `table1000_int_autoinc` WHERE COALESCE( `col_blob`, '2030-01-04', `col_decimal_key` ) ORDER BY field1, field2, field3, field4, field5 LIMIT 3 /* QNO 824 CON_ID 112 */ ;
[2020-04-14T15:10:11.348Z] NoPushDown Output: 
[2020-04-14T15:10:11.348Z] Error 1105: runtime error: index out of range [0] with length 0
[2020-04-14T15:10:11.348Z] 
[2020-04-14T15:10:11.348Z] WithPushDown Output: 
[2020-04-14T15:10:11.348Z] field1	field2	field3	field4	field5
[2020-04-14T15:10:11.348Z] NULL	NULL	0	NULL	2018-04-27
[2020-04-14T15:10:11.348Z] NULL	NULL	0	NULL	2018-04-27
[2020-04-14T15:10:11.348Z] NULL	NULL	0	NULL	2018-04-27
```

I think the TiDB test is broken. Going to merge manually.

**Pull request merged**
