### PR TITLE
copr: Add vectorized BitAndSig

### PR DESCRIPTION
**Pull request by codeworm96**
PCP #5751

###  What have you changed?

Add vectorized BitAndSig

###  What is the type of the changes?

Improvement. Non-vectorized BitAndSig already exists. Just add a vectorized version for better performance.

###  How is the PR tested?

Unit tested. Will run copr test later.

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No. It should not change the behavior.

###  Does this PR affect `tidb-ansible`?

No.

### CODE REVIEW

**Comment by codeworm96** [comment]
PTAL. I have fixed the conflict. Seems they conflict with each other. I will handle them one by one.

**Comment by lonng** [comment]
Related copr-test PR https://github.com/tikv/copr-test/pull/21

**Pull request merged**
