### PR TITLE
Fix PointGetter performance issue when there are concurrent write

### PR DESCRIPTION
**Pull request by breeswish**
###  What have you changed?

When there are concurrent write, lock CF will likely to contain deleted locks. In this scenario, it is much slower to `seek()` compared to `get_cf()` because internally `seek()` will try its best to find a visible user key and these tombstone keys will be iterated. However we actually don't care about the first key > given seek key. What we care is the key == seek key. For this reason, this PR substitutes the lock cursor with `get_cf()`, which was used in batch get.

This PR also substitutes the default cursor with `get_cf()`, which was used in batch get as well, considering that it is very **unlikely** that the keys given to batch get are very close to each other. While keys are not close to each other, a `near_seek()` in the default CF will simply fallback to a `seek()` eventually, which is slower than `get_cf()`.

###  What is the type of the changes?

- Bugfix (a change which fixes an issue)

###  How is the PR tested?

Manually. Using command:

```bash
go-ycsb load mysql -P workloads/workloade -p mysql.host=.... -p mysql.port=.... -p mysql.user=root -p recordcount=10000000 -p operationcount=30000000 -p threadcount=1000
```

Before this PR: OPS = 462.1 after 200s.
After this PR: OPS = 29271.1 after 200s.

Metrics:

image
image

### CODE REVIEW

**Comment by mapleFU** [comment]
What about the benchmark?

**Comment by breeswish** [comment]
@sticnarf @mapleFU Updated in the PR body.

**Pull request merged**
