### PR TITLE
github: clean up outdated template instructions and fix clippy's link

### PR DESCRIPTION
**Pull request by hi-rustin**
Signed-off-by: hi-rustin <rustin.liu@gmail.com>

### What problem does this PR solve?

Issue Number: None

Problem Summary:

### What is changed and how it works?

What's Changed:

clean up outdated template instructions(The file in the description has been deleted) and fix clippy's link.

### Related changes

None

### Check List 

Tests 

- No code

Side effects

None
### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
@andylokandy Could you please take a look?

**Review by andylokandy — APPROVED** [review]

**Review by zhongzc — APPROVED** [review]

**Pull request merged**
