### PR TITLE
pd-client: tikv should continue if cluster-id is zero. (#13242)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #13242 to release-6.2
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/13261
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/13261:release-6.2-693ae46f2739
```

---

close tikv/tikv#13240

### What is changed and how it works?

Issue Number: Close https://github.com/tikv/tikv/issues/13240,

What's Changed:

```commit-message
using warn to replace panic.
```

### Check List 

Tests 

- Manual test (add detailed scripts or steps below)

Side effects

### Release note 

```release-note
 None.

```

### CODE REVIEW

**Review by nolouch — APPROVED** [review]

**Comment by iosmanthus** [comment]
LGTM

**Review by iosmanthus — APPROVED** [review]

**Comment by iosmanthus** [comment]
@pingyu PTAL

**Review by lhy1024 — APPROVED** [review]

**Pull request merged**
