### PR TITLE
copr: (non)-vectorized Date

### PR DESCRIPTION
**Pull request by wangggong**
Signed-off-by: wangggong <793160615@qq.com>

### What problem does this PR solve?

Issue Number: #9016 

Problem Summary:

### What is changed and how it works?

What's Changed:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

### Release note 

No release note.

### CODE REVIEW

**Comment by Xuanwo** [comment]
Please fix test:

```
[2020-12-26T06:22:07.829Z] test impl_time::tests::test_date ... thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Evaluate(Other("[components/tidb_query_expr/src/types/function.rs:272]: Expect `DateTime`, received `Bytes`"))', components/tidb_query_expr/src/impl_time.rs:832:18

[2020-12-26T06:22:07.829Z] stack backtrace:

[2020-12-26T06:22:07.829Z]    0: rust_begin_unwind

[2020-12-26T06:22:07.829Z]              at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panicking.rs:483:5

[2020-12-26T06:22:07.829Z]    1: core::panicking::panic_fmt

[2020-12-26T06:22:07.829Z]              at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/panicking.rs:85:14

[2020-12-26T06:22:07.829Z]    2: core::option::expect_none_failed

[2020-12-26T06:22:07.829Z]              at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/option.rs:1238:5

[2020-12-26T06:22:07.829Z]    3: core::result::Result<T,E>::unwrap

[2020-12-26T06:22:07.829Z]              at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/result.rs:973:23

[2020-12-26T06:22:07.829Z]    4: tidb_query_expr::impl_time::tests::test_date

[2020-12-26T06:22:07.829Z]              at ./components/tidb_query_expr/src/impl_time.rs:829:26

[2020-12-26T06:22:07.829Z]    5: tidb_query_expr::impl_time::tests::test_date::{{closure}}

[2020-12-26T06:22:07.829Z]              at ./components/tidb_query_expr/src/impl_time.rs:816:5

[2020-12-26T06:22:07.829Z]    6: core::ops::function::FnOnce::call_once

[2020-12-26T06:22:07.829Z]              at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/ops/function.rs:227:5

[2020-12-26T06:22:07.829Z]    7: core::ops::function::FnOnce::call_once

[2020-12-26T06:22:07.829Z]              at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/ops/function.rs:227:5

[2020-12-26T06:22:07.829Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

[2020-12-26T06:22:07.829Z] FAILED
```

**Comment by wangggong** [comment]
> Please fix test:
> 
> ```
> [2020-12-26T06:22:07.829Z] test impl_time::tests::test_date ... thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Evaluate(Other("[components/tidb_query_expr/src/types/function.rs:272]: Expect `DateTime`, received `Bytes`"))', components/tidb_query_expr/src/impl_time.rs:832:18
> 
> [2020-12-26T06:22:07.829Z] stack backtrace:
> 
> [2020-12-26T06:22:07.829Z]    0: rust_begin_unwind
> 
> [2020-12-26T06:22:07.829Z]              at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panicking.rs:483:5
> 
> [2020-12-26T06:22:07.829Z]    1: core::panicking::panic_fmt
> 
> [2020-12-26T06:22:07.829Z]              at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/panicking.rs:85:14
> 
> [2020-12-26T06:22:07.829Z]    2: core::option::expect_none_failed
> 
> [2020-12-26T06:22:07.829Z]              at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/option.rs:1238:5
> 
> [2020-12-26T06:22:07.829Z]    3: core::result::Result<T,E>::unwrap
> 
> [2020-12-26T06:22:07.829Z]              at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/result.rs:973:23
> 
> [2020-12-26T06:22:07.829Z]    4: tidb_query_expr::impl_time::tests::test_date
> 
> [2020-12-26T06:22:07.829Z]              at ./components/tidb_query_expr/src/impl_time.rs:829:26
> 
> [2020-12-26T06:22:07.829Z]    5: tidb_query_expr::impl_time::tests::test_date::{{closure}}
> 
> [2020-12-26T06:22:07.829Z]              at ./components/tidb_query_expr/src/impl_time.rs:816:5
> 
> [2020-12-26T06:22:07.829Z]    6: core::ops::function::FnOnce::call_once
> 
> [2020-12-26T06:22:07.829Z]              at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/ops/function.rs:227:5
> 
> [2020-12-26T06:22:07.829Z]    7: core::ops::function::FnOnce::call_once
> 
> [2020-12-26T06:22:07.829Z]              at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/ops/function.rs:227:5
> 
> [2020-12-26T06:22:07.829Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> 
> [2020-12-26T06:22:07.829Z] FAILED
> ```

@xuanwo done, PTAL

**Review by Xuanwo — APPROVED** [review]
LGTM

**Comment by Xuanwo** [comment]
cc @zhongzc @andylokandy

**Review by zhongzc — APPROVED** [review]

**Pull request merged**
