### PR TITLE
analyze: correct the offset used in sampling

### PR DESCRIPTION
**Pull request by winoros**
Signed-off-by: Yiding Cui <winoros@gmail.com>

### What problem does this PR solve?

Problem Summary:

The offset was wrongly used. Then we would collect the wrong stats for the column group.

### What is changed and how it works?

What's Changed:

Use the correct offsets and add tests for it.

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by lzmhhh123 — APPROVED** [review]

**Comment by sticnarf** [comment]
Please format your code :)

**Review by skyzh — COMMENTED** [review]
The behavior seems inconsistent with https://github.com/pingcap/tidb/blob/master/statistics/row_sampler.go#L190, where `total_sizes` will still be modified if the column is null. (Does it always have length of 0?)

By the way, if we only need to use `offsets[j]`, why not iterate only on `offsets`?

```rust
for j in &offsets {
   // do something
}
```

**Comment by skyzh** [comment]
Please also fix clippy warnings.

**Comment by winoros** [comment]
@skyzh I'll fix TiDB's later. TIDB's is only used for test. NULL would always be zero when do calculate.

**Review by skyzh — APPROVED** [review]

**Pull request merged**
