### PR TITLE
copr: Vectorize PI

### PR DESCRIPTION
**Pull request by Fullstop000**
PCP https://github.com/tikv/tikv/issues/5751

###  What have you changed?
Vectorize `Pi`

###  What is the type of the changes?

Pick one of the following and delete the others:

- Improvement (a change which is an improvement to an existing feature)

###  How is the PR tested?

- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No

###  Does this PR affect `tidb-ansible`?

No

@lonng @breeswish

### CODE REVIEW

**Comment by lonng** [comment]
@Fullstop000 Hi, thanks for your contribution.
1. Please add some integration test in the repo https://github.com/tikv/copr-test  for this function
2. Open the push-down switcher in TiDB, see: [canFuncBePushed](https://github.com/pingcap/tidb/blob/master/expression/expr_to_pb.go#L285)
The workflow can be found in https://github.com/tikv/community/tree/master/sig/coprocessor

**Comment by Fullstop000** [comment]
@lonng Is it a requirement to modify the `canFuncBePushed` in TiDB whatever a vectorized/non-vectorized push-down-function is added in TiKV

**Comment by lonng** [comment]
@Fullstop000 It's better to modify the `canFuncBePushed` in TiDB, but it's OK to skip this step because we can open them later in batches.

**Comment by Fullstop000** [comment]
It seems we don't have a clear consensus about this in both TiDB and TiKV based on https://github.com/pingcap/tidb/pull/13195. IMO, skipping this could be more friendly to newly joined contributors :). @lonng

**Comment by lonng** [comment]
@Fullstop000 I have commented on pingcap/tidb#13195. You can skip this step for the time being, I am sorry to bother you.

**Comment by codeworm96** [comment]
It seems to me the type of the function is not correct. PI() in MySQL has no arguments.

**Pull request merged**
