### PR TITLE
ci: stabilize case test_read_index_stale_in_suspect_lease

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve?

The test case `test_read_index_stale_in_suspect_lease` is not stable. It sometimes fails on transferring leadership.

### What is changed and how it works?

Cherry pick #7262 and #9417 .

### Release note 
* No release note.

### CODE REVIEW

**Comment by BusyJay** [comment]
> Cherry pick #7262 and #9418 .

How can a PR cherry pick itself?

**Review by BusyJay — APPROVED** [review]

**Review by 5kbpers — APPROVED** [review]
LGTM

**Pull request merged**
