### PR TITLE
docs/how-to: fix pd-ctl command

### PR DESCRIPTION
**Pull request by gregwebs**
pd-ctl no longer has a -d option

### Check List

Tests 
- Manual test: run the command in the doc

### Release note

No Release note

### CODE REVIEW

**Review by yiwu-arbug — APPROVED** [review]
LGTM

**Comment by lilin90** [comment]
Since the [Docs](https://tikv.org/docs/4.0/concepts/overview/) on tikv.org is all maintained in the [tikv/website](https://github.com/tikv/website) repo (`/content/docs`) currently, do you mind creating a PR to tikv/website?

To avoid confusion, I've talked with @dcalvin and will delete the tikv/docs directory after confirmation.

**Comment by gregwebs** [comment]
I found this by reference from CONTRIBUTING.md. There is also a link to docs from the README.md

**Comment by lilin90** [comment]
Got it. Then we also need to update them to the new link on tikv.org. I can do this update in tikv/tikv, and will update several other outdated links in README.md.

**Comment by gregwebs** [comment]
fixed in https://github.com/tikv/tikv/pull/8836

**Pull request closed without merging**
