### PR TITLE
copr: add non-vectorized time_to_sec

### PR DESCRIPTION
**Pull request by trabbart**
Signed-off-by: Bartosz Podkanowicz <podkanowicz.bartosz@gmail.com>

UCP #6874

Checklist #5751

###  What have you changed?

Add non-vectorize time_to_sec.

###  What is the type of the changes?

- New feature (a change which adds functionality)

###  How is the PR tested?

- Unit test

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No.

###  Does this PR affect `tidb-ansible`?

No.

###  Refer to a related PR or issue link (optional)

Issue #5751 
Issue #6874

### CODE REVIEW

**Comment by trabbart** [comment]
@sticnarf Can anyone review this PR, please? Thank you

**Comment by zhongzc** [comment]
LGTM, please update the branch :D

**Comment by zhongzc** [comment]
PTAL @breeswish

**Pull request merged**
