### PR TITLE
start gc after node to fetch node id

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve?

There is a bug in the master branch that GC can't work at all. The reason is `0` is passed into the GC worker as `store_id`, which will cause all regions get skiped when doing GC.

Close https://github.com/tikv/tikv/issues/9466.

The bug is introduced in https://github.com/tikv/tikv/pull/9350.

### What is changed and how it works?

Start gc worker after node. So that `node_id` passed into the GC worker will must be valid.

### Check List 

Tests 
- Manual test (add detailed scripts or steps below)
a) starting a new tikv cluster
b) run a sysbench update_index workload, then check the gc worker cpu panel
c) check the result:
  
图片
图片

### Release note 
* No release note

### CODE REVIEW

**Review by hunterlxt — APPROVED** [review]
LGTM

**Review by gengliqi — APPROVED** [review]

**Review by MyonKeminta — APPROVED** [review]
LGTM. Can you also test manually to ensure the problem is fixed?

**Comment by hicqu** [comment]
@MyonKeminta I'm testing it. Result will be posted later.

**Comment by BusyJay** [comment]
I remembered there was a benchmark result about compaction filter gc, was the result still correct?

**Pull request merged**
