### PR TITLE
fixbug:when enable api v2 , TiDB resolve lock meet error (#12596)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #12596 to release-6.1
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In tikv repo:
git pr https://github.com/tikv/tikv/pull/12635
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/tikv.git pr/12635:release-6.1-4940bc44f6f4
```

---

Signed-off-by: ystaticy <y_static_y@sina.com>

### What is changed and how it works?

Issue Number: Close https://github.com/tikv/tikv/issues/12595

What's Changed:

```
If cmd is scan_lock , it will not execute invalid_key_range_mode check.
```
### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
fix:when enable api v2 , TiDB resolve lock meet error
```

### CODE REVIEW

**Review by iosmanthus — APPROVED** [review]
LGTM

**Review by pingyu — APPROVED** [review]
LGTM~

**Review by MyonKeminta — APPROVED** [review]

**Pull request merged**
