### PR TITLE
copr: add string_duration_time_diff and string_string_time_diff function

### PR DESCRIPTION
**Pull request by ztelur**
Hi! I'm new to the project. this is my small PR about TiDB function migration. 

### What problem does this PR solve?

Issue Number: part of #5751
Problem Summary: migrating `string_duration_time_diff` and `string_string_time_diff` from TiDB

### What is changed and how it works?

What's Changed:

Implement `string_duration_time_diff` and `string_string_time_diff` function by calling `duration_duration_time_diff` function inside.

### Related changes

- No Related Changes

### Check List 

Tests 

- Unit test

### Release note 

```release-note
- Implement  string_duration_time_diff and string_string_time_diff

```

### CODE REVIEW

**Comment by ztelur** [comment]
cc @skyzh

**Review by skyzh — APPROVED** [review]
Thanks!

**Review by Xuanwo — APPROVED** [review]

**Pull request merged**
