### PR TITLE
pd_client: refine PD client codes

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

### What problem does this PR solve?

Import macros from other crates with the `use` syntax. 

### What is changed and how it works?

rust-lang/rust#50911

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

* No release note.

### CODE REVIEW

**Review by nolouch — APPROVED** [review]
lgtm

**Review by BusyJay — APPROVED** [review]
Cool, how about also cleaning other modules?

**Comment by JmPotato** [comment]
> Cool, how about also cleaning other modules?

Ok, I will take a look at other modules.

**Pull request merged**
