### PR TITLE
raftstore: lazy remove ReadDelegate when peer is destroyed asynchronously

### PR DESCRIPTION
**Pull request by overvenus**
Signed-off-by: Neil Shen <overvenus@gmail.com>

## What have you changed? (mandatory)

There is a bug when we  destroy peers asychroniously, because we destroy read delegates right after receiving a GC message, peers may send update(region) to its delegate, but the delegate is destroyed already.

This PR fix the bug by lazy remove ReadDelegate when peer is destroyed asychroniously.

## What are the type of the changes? (mandatory)

- Bug fix (non-breaking change which fixes an issue)

## How has this PR been tested? (mandatory)

Unit tests.

## Refer to a related PR or issue link (optional)

#2639

### CODE REVIEW

**Comment by siddontang** [comment]
where is the bug for this PR?

**Comment by overvenus** [comment]
@siddontang description updated.

**Comment by MyonKeminta** [comment]
@siddontang It caused panicking in my test 😢

```
2018/09/12 15:09:56.862 ERRO panic_hook.rs:112: thread 'local-reader' panicked 'unregistered ReadDelegate, region_id: 7471, Region(id: 7471 start_key: "t\200\000\000\000\000\000\000\377%_r\200\000\000\000\031\377\215kp\000\000\000\000\000\372" end_key: "t\200\000\000\000
\000\000\000\377%_r\200\000\000\000\031\377\236\025\262\000\000\000\000\000\372" region_epoch {conf_ver: 14 version: 1197} peers {id: 7472 store_id: 6} peers {id: 7474 store_id: 5} peers {id: 26830 store_id: 4})' at "src/raftstore/store/worker/read.rs:535"
stack backtrace:
   0:     0x55f3b52fd55c - backtrace::backtrace::libunwind::trace::h1817c53b3689bdb1
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/libunwind.rs:54
                         - backtrace::backtrace::trace::he086a18776abc672
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/mod.rs:70
   1:     0x55f3b4fce6ca - tikv::util::panic_hook::set_exit_hook::{{closure}}::hf714e664604a1e4f
                        at /home/jenkins/.target/release/build/backtrace-4ca9820cec07bbc1/out/capture.rs:79
   2:     0x55f3b549116f - std::panicking::rust_panic_with_hook::h60a37fb79e459606
                        at libstd/panicking.rs:479
   3:     0x55f3b5490fce - std::panicking::continue_panic_fmt::hb542a58a3d52cb5c
                        at libstd/panicking.rs:390
   4:     0x55f3b5490f72 - std::panicking::begin_panic_fmt::ha198d387c12d5535
                        at libstd/panicking.rs:345
   5:     0x55f3b54dd341 - <tikv::raftstore::store::worker::read::LocalReader<C> as tikv::util::worker::Runnable<tikv::raftstore::store::worker::read::Task>>::run_batch::h1b4f9f68c98534f6
                        at /home/jenkins/workspace/tikv_ghpr_build/go/src/github.com/tikv/tikv/<panic macros>:8
   6:     0x55f3b4bb87c1 - tikv::util::worker::poll::h07ff03091f9da9c5
                        at /home/jenkins/workspace/tikv_ghpr_build/go/src/github.com/tikv/tikv/src/util/worker/mod.rs:274
                         - <tikv::util::worker::Worker<T>>::start_with_timer::{{closure}}::h592bba004329c1b6
                        at /home/jenkins/workspace/tikv_ghpr_build/go/src/github.com/tikv/tikv/src/util/worker/mod.rs:352
                         - std::sys_common::backtrace::__rust_begin_short_backtrace::hc019b7d9d0772518
                        at /checkout/src/libstd/sys_common/backtrace.rs:136
   7:     0x55f3b5507311 - std::thread::Builder::spawn::{{closure}}::hdd4c5f34a8c50b5d
                        at /checkout/src/libstd/thread/mod.rs:409
                         - <F as alloc::boxed::FnBox<A>>::call_box::hb32b44bfc3d307bf
                        at /checkout/src/liballoc/boxed.rs:640
   8:     0x55f3b547f5c3 - std::sys::unix::thread::Thread::new::thread_start::h96884314b12ba24c
                        at /checkout/src/liballoc/boxed.rs:650
   9:     0x7fa33954ce24 - start_thread
  10:     0x7fa339060bac - __clone
  11:                0x0 - <unknown>
```

**Comment by siddontang** [comment]
please approve it @Connor1996

**Pull request merged**
