### PR TITLE
remove MAINTAINERS.md

### PR DESCRIPTION
**Pull request by xxchan**
The former MAINTAINERS is now [Steering Committee members](https://github.com/tikv/community/blob/master/GOVERNANCE.md#steering-committee) (Maintainers for the whole community, while TiKV team maintainers focus on the team scope which doesn't contain rust-prometheus, etc.).

This file is outdated, and we have a GOVERNANCE link in the README, so we can remove the file.

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by skyzh — APPROVED** [review]
/cc @tisonkun 

By the way, should we add link to view current maintainers to readme?

**Comment by xxchan** [comment]
> should we add the link to view current maintainers to readme?

@skyzh there is a [GOVERNANCE](https://github.com/tikv/community/blob/master/GOVERNANCE.md) link, so I think it is unnecessary

**Review by tisonkun — APPROVED** [review]
@skyzh I second @xxchan 's suggestion. LGTM. Thanks for submitting the PR.

**Comment by tisonkun** [comment]
@xxchan I think the former MAINTAINER is now [Steering Committee members](https://github.com/tikv/community/blob/master/GOVERNANCE.md#steering-committee). Sorry for the vocabulary overhead. And you can update the PR description to clarify it.

**Pull request merged**
