### PR TITLE
engine: remove delete range extend key hack

### PR DESCRIPTION
**Pull request by yiwu-arbug**
## What have you changed? (mandatory)

Remove the hack as the related delete range bug will be fixed after https://github.com/pingcap/rust-rocksdb/pull/288.

## What are the type of the changes? (mandatory)
Engineering

## How has this PR been tested? (mandatory)
`cargo test test_node_use_delete_range`

## Does this PR affect documentation (docs) update? (mandatory)
no

## Does this PR affect tidb-ansible update? (mandatory)
no

## Refer to a related PR or issue link (optional)
The hack was added in #4503 

## Benchmark result if necessary (optional)
n/a

## Add a few positive/negative examples (optional)
n/a

### CODE REVIEW

**Comment by siddontang** [comment]
oh, can we add more tests for it?

**Comment by yiwu-arbug** [comment]
@siddontang test added in #4503 is sufficient.

**Comment by siddontang** [comment]
CI failed

```
test raftstore::test_single::test_node_use_delete_range ... thread 'apply-0' panicked at 'attempt to subtract with overflow', components/engine/src/rocks/util/mod.rs:360:19

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

stack backtrace:

   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace

             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39

   1: std::sys_common::backtrace::_print

             at src/libstd/sys_common/backtrace.rs:71

   2: std::panicking::default_hook::{{closure}}

             at src/libstd/sys_common/backtrace.rs:59

             at src/libstd/panicking.rs:197

   3: std::panicking::default_hook

             at src/libstd/panicking.rs:211

   4: std::panicking::rust_panic_with_hook

             at src/libstd/panicking.rs:474

   5: std::panicking::continue_panic_fmt

             at src/libstd/panicking.rs:381

   6: rust_begin_unwind

             at src/libstd/panicking.rs:308

   7: core::panicking::panic_fmt

             at src/libcore/panicking.rs:85

   8: core::panicking::panic

             at src/libcore/panicking.rs:49

   9: <engine::rocks::util::FixedSuffixSliceTransform as rocksdb::slice_transform::SliceTransform>::transform

             at components/engine/src/rocks/util/mod.rs:360

  10: rocksdb::slice_transform::transform

             at /rust/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/263b82e/src/slice_transform.rs:65

  11: _ZNK25crocksdb_slicetransform_t9TransformERKN7rocksdb5SliceE

             at crocksdb/c.cc:511

  12: _ZN7rocksdb8MemTable3AddEmNS_9ValueTypeERKNS_5SliceES4_bPNS_23MemTablePostProcessInfoE

  13: _ZN7rocksdb16MemTableInserter10DeleteImplEjRKNS_5SliceES3_NS_9ValueTypeE

             at /rust/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/263b82e/librocksdb_sys/rocksdb/db/write_batch.cc:1338

  14: _ZN7rocksdb16MemTableInserter13DeleteRangeCFEjRKNS_5SliceES3_

             at /rust/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/263b82e/librocksdb_sys/rocksdb/db/write_batch.cc:1462

  15: _ZNK7rocksdb10WriteBatch7IterateEPNS0_7HandlerE

             at /rust/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/263b82e/librocksdb_sys/rocksdb/db/write_batch.cc:481

  16: _ZN7rocksdb18WriteBatchInternal10InsertIntoERNS_11WriteThread10WriteGroupEmPNS_21ColumnFamilyMemTablesEPNS_14FlushSchedulerEbmPNS_2DBEbbb

             at /rust/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/263b82e/librocksdb_sys/rocksdb/db/write_batch.cc:1780

  17: _ZN7rocksdb6DBImpl18PipelinedWriteImplERKNS_12WriteOptionsEPNS_10WriteBatchEPNS_13WriteCallbackEPmmbS8_

             at /rust/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/263b82e/librocksdb_sys/rocksdb/db/db_impl_write.cc:513

  18: _ZN7rocksdb6DBImpl9WriteImplERKNS_12WriteOptionsEPNS_10WriteBatchEPNS_13WriteCallbackEPmmbS8_mPNS_18PreReleaseCallbackE

             at /rust/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/263b82e/librocksdb_sys/rocksdb/db/db_impl_write.cc:116

  19: _ZN7rocksdb6DBImpl5WriteERKNS_12WriteOptionsEPNS_10WriteBatchE

             at /rust/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/263b82e/librocksdb_sys/rocksdb/db/db_impl_write.cc:55

  20: crocksdb_write

             at crocksdb/c.cc:938

  21: rocksdb::rocksdb::DB::write_opt

             at /rust/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/263b82e/src/rocksdb.rs:664

  22: rocksdb::rocksdb::DB::write

             at /rust/git/checkouts/rust-rocksdb-82ef6e5337b3fbe6/263b82e/src/rocksdb.rs:670

  23: engine::util::delete_all_in_range_cf

             at components/engine/src/util.rs:96

  24: tikv::raftstore::store::fsm::apply::ApplyDelegate::handle_delete_range

             at src/raftstore/store/fsm/apply.rs:1266

  25: tikv::raftstore::store::fsm::apply::ApplyDelegate::exec_write_cmd

             at src/raftstore/store/fsm/apply.rs:1090

  26: tikv::raftstore::store::fsm::apply::ApplyDelegate::exec_raft_cmd

             at src/raftstore/store/fsm/apply.rs:1027

  27: tikv::raftstore::store::fsm::apply::ApplyDelegate::apply_raft_cmd

             at src/raftstore/store/fsm/apply.rs:919

  28: tikv::raftstore::store::fsm::apply::ApplyDelegate::process_raft_cmd

             at src/raftstore/store/fsm/apply.rs:878

  29: tikv::raftstore::store::fsm::apply::ApplyDelegate::handle_raft_entry_normal

             at src/raftstore/store/fsm/apply.rs:786

  30: tikv::raftstore::store::fsm::apply::ApplyDelegate::handle_raft_committed_entries

             at src/raftstore/store/fsm/apply.rs:718

  31: tikv::raftstore::store::fsm::apply::ApplyFsm::handle_apply

             at src/raftstore/store/fsm/apply.rs:2385

  32: tikv::raftstore::store::fsm::apply::ApplyFsm::handle_tasks

             at src/raftstore/store/fsm/apply.rs:2604

  33: <tikv::raftstore::store::fsm::apply::ApplyPoller as tikv::raftstore::store::fsm::batch::PollHandler<tikv::raftstore::store::fsm::apply::ApplyFsm, tikv::raftstore::store::fsm::apply::ControlFsm>>::handle_normal

             at src/raftstore/store/fsm/apply.rs:2712

  34: <tikv::raftstore::store::fsm::batch::Poller<N, C, Handler>>::poll

             at ./src/raftstore/store/fsm/batch.rs:332

  35: <tikv::raftstore::store::fsm::batch::BatchSystem<N, C>>::spawn::{{closure}}

             at ./src/raftstore/store/fsm/batch.rs:403

```

**Comment by yiwu-arbug** [comment]
CI failure is due to pingcap/rust-rocksdb#288 haven't landed.

**Comment by yiwu-arbug** [comment]
Will wait for @zhangjinpeng1987 for bound key fix. After that CI will fix.

**Comment by yiwu-arbug** [comment]
@overvenus @Connor1996 mind give an approval? Thanks.

**Pull request merged**
