### PR TITLE
Cargo.toml: ignore empty test cases

### PR DESCRIPTION
**Pull request by kisom**
This change ignores the test cases with empty tests, as per #4391.

Signed-off-by: Kyle Isom <kyle@imap.cc>

## What have you changed? (mandatory)

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:
- I ran `cargo test --all` and removed the test suites that looked like they had no tests.

Please **NOTE** that:
- Do not assume reviewers understand the original issue

## What are the type of the changes? (mandatory)

The currently defined types are listed below, please pick one of the types for this PR by removing the others:
- Misc (other changes)

## How has this PR been tested? (mandatory)

I ran `cargo test --all`,

## Does this PR affect documentation (docs) update? (mandatory)

I don't think it does.

## Does this PR affect tidb-ansible update? (mandatory)

I don't think it does.

## Refer to a related PR or issue link (optional)

The issue filed is #4391.

## Benchmark result if necessary (optional)

This is only my second PR to a Rust project, so I'm not sure what the best way to do this is.

## Add a few positive/negative examples (optional)

I don't think this is relevant.

### CODE REVIEW

**Comment by brson** [comment]
Hey @kisom. Thank you for picking this up. To confirm, you found 2 empty test suites, for tikv-server and tikv-importer?

I see a second commit on this PR that looks unrelated. Can you force-push your first commit to get rid of the second? (Maybe that commit belongs with a different PR)

**Comment by brson** [comment]
@kisom I see a lot of empty doc tests. Can you disable those too?

Do you mind doing a simple test of compile time? Just run `time cargo test --all --no-run` before and after your commit. If you are ambitious the partial rebuild compile time is even better. To get that run `cargo test --all --no-run && echo >> src/lib.rs && time cargo test --all --no-run`.

**Comment by breeswish** [comment]
Nice finding! Please remove unrelated commits. Thank you very much

**Comment by brson** [comment]
Ping @kisom. Still some things to resolve here.

**Comment by kisom** [comment]
I haven't forgotten about this, work has just been busy.

**Comment by andylokandy** [comment]
@kisom Do you have any update?

**Comment by AndreMouche** [comment]
We really value your contribution, we are closing this PR due to inactivity (last activity: 2019-04-11). We'd like to work with you more, if you are interested on continuing work on this PR please comment and we will re-open. If you'd like to work on something else, get in touch.

**Comment by AndreMouche** [comment]
We really value your contribution, we are closing this PR due to inactivity (last activity: 2019-04-09). We'd like to work with you more, if you are interested on continuing work on this PR please comment and we will re-open. If you'd like to work on something else, get in touch.

**Pull request closed without merging**
