### PR TITLE
copr: Switch to use TiDB's Duration memory layout for Duration

### PR DESCRIPTION
**Pull request by andylokandy**
Signed-off-by: Dian Luo <andylokandy@hotmail.com>

PCP https://github.com/tikv/tikv/issues/6368

###  What have you changed?

- Removed the fsp in current Duration implementation.
- Changed to use the same memory format for the Duration.

###  What is the type of the changes?

- Engineering (engineering change which doesn't change any feature or fix any issue)

###  How is the PR tested?

- Unit test

### CODE REVIEW

**Comment by sticnarf** [comment]
The ICE looks similar to a long-existing incremental compiling issue: https://github.com/rust-lang/rust/issues/62649
I've confirmed that a clean build works on your code.

**Comment by andylokandy** [comment]
@sticnarf How do I instruct the CI to run a clean build?

**Comment by sticnarf** [comment]
@andylokandy  I have no idea. :(
You may consule @qrr1995

**Comment by andylokandy** [comment]
Closed due to CI breakage

**Pull request closed without merging**
