### PR TITLE
copr: separate expression signature `Upper` to `Upper` and `UpperUtf8`

### PR DESCRIPTION
**Pull request by wangwangwar**
Signed-off-by: wangwangwar <wangwangwar@gmail.com>

### What have you changed?

Separate expression signatuer `Upper` to `Upper` and `UpperUtf8`.

### What is the type of the changes?

Improvement

### How is the PR tested?

- Unit test
- Integration test

### Does this PR affect documentation (docs) or should it be mentioned in the release notes?

No. It should not change the behavior.

### Does this PR affect tidb-ansible?

No

### CODE REVIEW

**Comment by wangwangwar** [comment]
@sre-bot /test

**Comment by andylokandy** [comment]
@wangwangwar Please fix clipp, thank you~

**Comment by wangwangwar** [comment]
@andylokandy Fixed and PTAL:)

**Pull request merged**
