### PR TITLE
github/workflows: remove legacy actions

### LINKED ISSUE #10066: Cleanup stale projects with GitHub workflow
## Development Task

We have quite a few stale [projects](https://github.com/tikv/tikv/projects), some of which are the same as a label filter on issues.

I'm going to cleanup stale projects along with GitHub workflow.

### PR DESCRIPTION
**Pull request by tisonkun**
This closes #10066 .

Signed-off-by: tison <wander4096@gmail.com>

```release-note
None
```

### CODE REVIEW

**Comment by glorv** [comment]
I'm not sure if the scripts for finding unstable tests still depend on these labels or projects.  cc @lilinghai PTAL

**Comment by tisonkun** [comment]
@BusyJay @glorv it seems no one care about these projects.

**Review by BusyJay — APPROVED** [review]

**Review by sunxiaoguang — APPROVED** [review]
Confirmed that the associated projects were not in use.

**Pull request merged**
