### PR TITLE
Rawkv gctask metrics

### PR DESCRIPTION
**Pull request by ystaticy**
Signed-off-by: ystaticy <y_static_y@sina.com>

### What is changed and how it works?

Issue Number: Ref https://github.com/tikv/tikv/issues/12557

What's Changed: 

```release-note 
RawKV GCTask return handled and wasted count
```

### Check List 

Tests 

- Manual test 
If the data is the latest version is deleted or expired and to Compcation,it will trigger ```GcTask::RawGcKeys```
We can get ```tikv_gc_compaction_filter_mvcc_deletion_handled``` value is not ```0``` in grafana

### CODE REVIEW

**Review by MyonKeminta — APPROVED** [review]
LGTM. Not sure whether using the same metrics as transactional GC is a good idea though.

**Review by pingyu — APPROVED** [review]
LGTM

**Comment by pingyu** [comment]
> LGTM. Not sure whether using the same metrics as transactional GC is a good idea though.

I think it would be better to separate metrics for different KV modes later.

**Comment by ystaticy** [comment]
> > LGTM. Not sure whether using the same metrics as transactional GC is a good idea though.
> 
> I think it would be better to separate metrics for different KV modes later.

Ok, the metrics will be separate later.

**Review by iosmanthus — APPROVED** [review]
LGTM

**Pull request merged**
