### PR TITLE
rsmeter: fix perf regression caused by arc swap 

### LINKED ISSUE #11835: attach resource metering tag expects to be a extremely lightweight job but not now
## Bug Report

image

### What version of TiKV are you using?
master

### What operating system and CPU are you using?
no matter

### Steps to reproduce
sysbench, pprof

### What did you expect?
attach < 0.3%

### What did happened?
attach > 3%

### PR DESCRIPTION
**Pull request by zhongzc**
Signed-off-by: Zhenchi <zhongzc_arch@outlook.com>

close #11835

### What is changed and how it works?

arc_swap is optimized for read-heavy situations but our case is write-heavy

What's Changed:

use atomic_cell

#### master
image

#### this patch
image

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by breeswish — APPROVED** [review]
Generally LGTM.

**Comment by breeswish** [comment]
@BusyJay @andylokandy  PTAL, thanks!

**Comment by sticnarf** [comment]
May I ask what the UI displaying the flamegraph is?

**Comment by breeswish** [comment]
> May I ask what the UI displaying the flamegraph is?

@sticnarf  This is the new FlameGraph UI built into TiDB Dashboard. It is backed by https://www.speedscope.app .

**Comment by mornyx** [comment]
LGTM

**Review by andylokandy — APPROVED** [review]

**Pull request merged**
