### PR TITLE
Fix flaky test by extending raft gc wait timeout

### LINKED ISSUE #12809: Fix unsafe recovery flaky test
## Development Task
Failure example: https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/22055/pipeline/

### PR DESCRIPTION
**Pull request by v01dstar**
Signed-off-by: v01dstar <yang.zhang@pingcap.com>

### What is changed and how it works?

Issue Number: Close #12809

What's Changed:

```commit-message
Fix flaky test by extending raft gc wait timeout
```
I know that extending the timeout is not a permanent solution, but this seems to be the most effective way right now.

### Related changes

- N/A

### Check List 

Tests 

- Integration test

Side effects

-N/A

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by Connor1996 — COMMENTED** [review]
Please add back the period check to exit remaining force leader, and test `test_force_leader_trigger_snapshot`

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by tonyxuqqi — APPROVED** [review]

**Pull request merged**
