### PR TITLE
*: Reduce type of transport and raft-client

### PR DESCRIPTION
**Pull request by Little-Wallace**
### What is changed and how it works?

What's Changed:
I remove some type parameter in transport and raft-client because TiKV will only call `raft_router` when there is a new connection establish. This is not a high frequency operation and the most cost of latency is not `send_raft_msg` of `raft_router`, it is in network and system call.
 
### Related changes

- This PR will solve part of the problem in https://github.com/tikv/tikv/pull/8980. Because there is no `RocksEngine` in transport and raft-client now.

### Check List 

Tests 

- Unit test

### Release note 

- No release note.

### CODE REVIEW

**Comment by brson** [comment]
@Little-Wallace can you get this up to date with master? I don't quite have the insight to see what it is that makes this change work, but I see less type parameters, so I think we should get it merged.

**Comment by brson** [comment]
Actually after reading again I do have a decent understanding of what this is doing to get rid of type parameters. I think the way this uses `clone_box` to create a new boxed object out of the internals of the self value is a big ugly, and I personally don't know if I would do this just to get rid of type parameters. But I understand the distaste for them, and if others want to do this its fine by me and I'm happy to approve.

**Comment by brson** [comment]
@Little-Wallace can you give this PR another look?

**Comment by Little-Wallace** [comment]
I'm sorry to reply your comment until today. I'm busy with other jobs, I will think about whether there is better solution to reduce the type parameter.  Thanks you suggestion. @brson

**Pull request closed without merging**
