### PR TITLE
Use Cargo patch instead of replace

### PR DESCRIPTION
**Pull request by Hoverbear**
Migrate to `patch` instead of `replace` to follow best practices.

As discussed in https://doc.rust-lang.org/edition-guide/rust-2018/cargo-and-crates-io/replacing-dependencies-with-patch.html

###  What have you changed?

`replace` has some poor semantics when working with some tooling. `patch` is the preferred from.

###  What is the type of the changes?

- Engineering (engineering change which doesn't change any feature or fix any issue)

###  How is the PR tested?

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

###  Does this PR affect documentation (docs) or should it be mentioned in the release notes?

no

###  Does this PR affect `tidb-ansible`?

no

### CODE REVIEW

**Comment by siddontang** [comment]
@nr


have you added this into our Rust style?

**Comment by nrc** [comment]
@siddontang I added it in https://github.com/pingcap/style-guide/commit/404fe16c59a80ac7177de8306735dbfcf3c54780

**Comment by sticnarf** [comment]
@Hoverbear Hi, could you replace the conflicts?

**Comment by sticnarf** [comment]
Superseded by #7090

**Pull request closed without merging**
