### PR TITLE
tikv-ctl: Undesired error message about runing tikv-ctl without any parameters

### LINKED ISSUE #10957: Undesired error message about runing tikv-ctl without any parameters
### What version of TiKV are you using?

master branch

### What operating system and CPU are you using?

```
processor	: 23
vendor_id	: GenuineIntel
cpu family	: 6
model		: 22
model name	: Ksyun Virtual Senior CPU(ksyun-cpu64-senior)
stepping	: 3
microcode	: 0x1
cpu MHz		: 2599.998
cache size	: 19712 KB
physical id	: 23
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 23
initial apicid	: 23
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm fsgsbase bmi1 avx2 smep bmi2 erms xsaveopt
bugs		:
bogomips	: 5199.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```

### What did you expect?
```
➜  debug git:(issue_10734) ✗ ./tikv-ctl
TiKV Control (tikv-ctl) 
Release Version:   5.1.0-alpha
Edition:           Community
Git Commit Hash:   Unknown (env var does not exist when building)
Git Commit Branch: Unknown (env var does not exist when building)
UTC Build Time:    2021-09-16 09:03:55
Rust Version:      Unknown (env var does not exist when building)
Enable Features:   Unknown (env var does not exist when building)
Profile:           Unknown (env var does not exist when building)

A tool for interacting with TiKV deployments.

USAGE:
    TiKV Control (tikv-ctl) [FLAGS] [OPTIONS] [SUBCOMMAND]

FLAGS:
    -h, --help                    Prints help information
        --skip-paranoid-checks    Skip paranoid checks when open rocksdb
    -V, --version                 Prints version information

OPTIONS:
        --ca-path <ca_path>              Set the CA certificate path
        --cert-path <cert_path>          Set the certificate path
        --config <config>                TiKV config path, by default it's <deploy-dir>/conf/tikv.toml
        --data-dir <data_dir>            TiKV data-dir, check <deploy-dir>/scripts/run.sh to get it
        --db <db>                        Set the rocksdb path
        --decode <decode>                Decode a key in escaped format
        --encode <encode>                Encode a key in escaped format
        --to-hex <escaped-to-hex>        Convert an escaped key to hex key
        --to-escaped <hex-to-escaped>    Convert a hex key to escaped key
        --host <host>                    Set the remote host
        --key-path <key_path>            Set the private key path
        --log-level <log_level>          Set the log level [default: info]
        --pd <pd>                        Set the address of pd
        --raftdb <raftdb>                Set the raft rocksdb path

SUBCOMMANDS:
    bad-regions           Get all regions with corrupt raft
    bad-ssts              Print bad ssts related infos
    cluster               Print the cluster id
    compact               Compact a column family in a specified range
    compact-cluster       Compact the whole cluster in a specified range in one or more column families
    consistency-check     Force a consistency-check for a specified region
    decrypt-file          Decrypt an encrypted file
    diff                  Calculate difference of region keys from different dbs
    dump-snap-meta        Dump snapshot meta file
    encryption-meta       Dump encryption metadata
    fail                  Inject failures to TiKV and recovery
    help                  Prints this message or the help of the given subcommand(s)
    metrics               Print the metrics
    modify-tikv-config    Modify tikv config, eg. tikv-ctl --host ip:port modify-tikv-config -n
                          rocksdb.defaultcf.disable-auto-compactions -v true
    mvcc                  Print the mvcc value
    print                 Print the raw value
    raft                  Print a raft log entry
    range-properties      Show range properties
    raw-scan              Print all raw keys in the range
    recover-mvcc          Recover mvcc data on one node by deleting corrupted keys
    recreate-region       Recreate a region with given metadata, but alloc new id for it
    region-properties     Show region properties
    scan                  Print the range db range
    size                  Print region size
    split-region          Split the region
    store                 Print the store id
    tombstone             Set some regions on the node to tombstone by manual
    unsafe-recover        Unsafely recover when the store can not start normally, this recover may lose data% 
```

### What did happened?
```
➜  debug git:(issue_10734) ✗ ./tikv-ctl       
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cmd/tikv-ctl/src/main.rs:104:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
➜  debug git:(issue_10734) ✗ 

```

### PR DESCRIPTION
**Pull request by yuqi1129**
…arameters

Signed-off-by: yuqi1129 <yuqi4733@gmail.com>

### What problem does this PR solve?

Issue Number: close #10957 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

### Related changes

- Need to cherry-pick to the release branch

### Check List 

Tests 

- No code

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 

```release-note
None.
```

### CODE REVIEW

**Review by skyzh — APPROVED** [review]

**Review by andylokandy — APPROVED** [review]

**Comment by andylokandy** [comment]
@yuqi1129 Thank you!

**Comment by yuqi1129** [comment]
> /run-test

Seems that the test `cases::test_conf_change::test_destroy_local_reader` failed...

**Comment by tisonkun** [comment]
@yuqi1129 can you create an issue about the unstable test and ask for associated with https://github.com/tikv/tikv/issues/10506?

**Comment by hicqu** [comment]
`--host` and `--data` are deprecated and replaced by `--config`. Please check this before merge it.

**Comment by peng1999** [comment]
It seems that this PR has become unneeded since https://github.com/tikv/tikv/pull/10837 has already solved #10957 . See https://github.com/tikv/tikv/issues/10957#issuecomment-927244151

**Comment by yuqi1129** [comment]
@tisonkun @peng1999 
I have check it again and indeed, this problem have been fixed by #10837 recently. I will close this PR and issue
Thanks for your attention.

**Pull request closed without merging**
