### PR TITLE
metric: add tikv_engine_write_wal_time_micro_seconds

### PR DESCRIPTION
**Pull request by hawkingrei**
UCP [#5751](https://github.com/tikv/tikv/issues/6541)

###  What have you changed?

add tikv_engine_write_wal_time_micro_seconds for metric rocksdb's WAL write duration

###  What is the type of the changes?
- Improvement

###  How is the PR tested?
- Unit test

### CODE REVIEW

**Comment by hawkingrei** [comment]
I make a validation testing. the metric has been added rightly.

image

**Comment by Connor1996** [comment]
Please update the grafana board too

**Comment by siddontang** [comment]
@Connor1996 

I think it is hard for a contributor to add metrics in Grafana, maybe we can do it later.

**Comment by hawkingrei** [comment]
截屏2020-03-13下午2 05 13

**Comment by hawkingrei** [comment]
@Connor1996  PTAL~

**Comment by you06** [comment]
The points issue has been fixed, check it out at https://pingcap.com/community-cn/tidb-usability-challenge/
And congratulation! You have awarded a badge for usability challenge program! Please fill the form to get your reward! http://tidbcommunity.mikecrm.com/QMCv4QL

**Pull request merged**
