### PR TITLE
raftstore: do not update pending_cross_snap when peer is applying snapshot (#3873)

### PR DESCRIPTION
**Pull request by Connor1996**
cherry-pick of #3873

### CODE REVIEW

**Comment by Connor1996** [comment]
/run-all-tests tidb=release-2.0 pd=release-2.0 tidb-test=release-2.0

**Comment by Connor1996** [comment]
/run-all-tests tidb=release-2.0 pd=release-2.0 tidb-test=release-2.0

**Comment by zhouqiang-cl** [comment]
/run-integration-tests tidb=release-2.0 pd=release-2.0 tidb-test=release-2.0

**Pull request merged**
