### PR TITLE
logger: fix missing log fields

### LINKED ISSUE #16410: raftstore: Peer does not print `raft-id` and `peer-id` in `raft-rs` lib
## Bug Report
The `raftstore` do not print the `raft-id` and `region-id` in raft-rs.
```
[2024/01/18 12:23:45.245 +08:00] [INFO] [raft.rs:1532] ["starting a new election"] [term=5] [thread_id=1]
[2024/01/18 12:23:45.245 +08:00] [INFO] [raft.rs:1177] ["became pre-candidate at term 5"] [term=5] [thread_id=1]
[2024/01/18 12:23:45.245 +08:00] [INFO] [raft.rs:1151] ["became candidate at term 6"] [term=6] [thread_id=1]
[2024/01/18 12:23:45.245 +08:00] [INFO] [raft.rs:1235] ["became leader at term 6"] [term=6] [thread_id=1]
```

### What version of TiKV are you using?

Nightly branch: e2a2e87a890ad488446b3c4a2900a74d9313a8ba
### What operating system and CPU are you using?

None
### Steps to reproduce

Build with nightly branch.
### What did you expect?
`raft-rs` should print the `raft-id` and `region-id` as before.
img_v3_0277_181b7b71-6c8c-4924-a974-bd8930aa661g

### What did happened?
`raft-rs` does not print the `raft-id` and `region-id` as before.

### PR DESCRIPTION
**Pull request by overvenus**
### What is changed and how it works?

Issue Number: Close #16410

What's Changed:

```commit-message

```

### Check List

Tests 

- [x] Unit test
- [x] Integration test

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by LykxSassinator** [comment]
FYI, one more tip, it's better to do the performance tests to check whether this feature on `fixing thread-id` has performance regression or not.

**Comment by overvenus** [comment]
| Version | Benchmark results (sysbench oltp) |
|--------|--------|
| master branch fc93c89d761000580dab1623ee7f6366dd63b948| tps: 2783 qps: 55018 |
| This PR 37e3db317fbb78ea21824cc2f02e494dcb2a9617| tps: 2763 qps: 54651 |

Performance results are almost the same.

http://perf.pingcap.net/d/iarAjGo7z/benchbot-overview?orgId=1&var-email=All&var-testbed=benchbot-amd64-xl-sysbench-tps-6210094-1-971&from=1705629210000

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by LykxSassinator — APPROVED** [review]

**Pull request merged**
