### PR TITLE
raftstore: Use multi-batch-write for apply (#7111)

### PR DESCRIPTION
**Pull request by Little-Wallace**
Signed-off-by: Little-Wallace <bupt2013211450@gmail.com>

### What problem does this PR solve?

Cherry-pick https://github.com/tikv/tikv/pull/7111

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- PR to update `pingcap/tidb-ansible`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

Side effects

- Performance regression
    - Consumes more CPU
    - Consumes more MEM
- Breaking backward compatibility

### Release note 
- Improve write performance for batch-insert request.

### CODE REVIEW

**Comment by overvenus** [comment]
It breaks Titan, please do not merge until it gets fixed.

**Comment by Little-Wallace** [comment]
@overvenus The bug of Titan has been fixed and merged into release-4.0

**Pull request merged**
