### PR TITLE
Use manifest-path rather than -p for `cargo test` in the Makefile

### LINKED ISSUE #6097: Failpoint tests will not run when make dev
When calling command `make dev` on master, only integration tests are run, but failpoints is ignored.

When I run it explicitly, it refuses to run and reports:
```
% cargo test --no-default-features --features " jemalloc portable sse failpoints protobuf-codec" -p tests --test failpoints  -- --nocapture  ""
error: target `failpoints` in package `tests` requires the features: `failpoints`
Consider enabling them by passing, e.g., `--features="failpoints"`
```

### PR DESCRIPTION
**Pull request by nrc**
Since features are only passed to tests in the 'primary' manifest (I think this is a Cargo bug).

Closes #6097

###  What have you changed?

Tweak the way tests are run in the Makefile to ensure proper passing of feature flags.

###  What is the type of the changes?

Pick one of the following and delete the others:

- Bugfix (a change which fixes an issue)

PTAL @BusyJay @brson

### CODE REVIEW

**Comment by nrc** [comment]
Temporarily closed so I can land a more urgent fix :-(

**Comment by brson** [comment]
Attempting to make tikv's failpoints use tests failpoints resulted in this error:

```
cargo test --no-default-features --features "jemalloc portable sse failpoints protobuf-codec" -p tests --test failpoints  -- --nocapture
error: failed to parse manifest at `/home/brian/pingcap/tikv/Cargo.toml`

Caused by:
  Feature `failpoints` requires a feature of `tests` which is not a dependency
```

tests is in the same workspace but not a dependency of tikv so apparently tikv can't set tests' features. TIL

**Comment by nrc** [comment]
> I haven't tried to run this, but it looks incorrect to me since Cargo.toml and tests/Cargo.toml support a different set of features, so passing the same ${ENABLE_FEATURES} to both is going to end up passing the wrong features to some of them.

Good point. I think this can be fixed most easily by adding the missing features to tests/Cargo.toml

> I think the solution is to wire up Cargo.toml's features to activate various tests/Cargo.toml features. In particular, to solve the linked issue to add

This doesn't work (as you found). Features are a bit buggy and inconsistent.

PTAL @brson @BusyJay

**Comment by BusyJay** [comment]
Tried to compile the project locally, and it fails.

**Comment by nrc** [comment]
> Tried to compile the project locally, and it failed.

How were you building and what was the failure? (We should have it in CI if it is an important build).

**Comment by BusyJay** [comment]
Apparently our CI is broken, at lease it has not even noticed #6097 yet.

What I did was just `make dev`.
```
% make dev
Compiling tests v0.0.1 (/mnt/wwn-0x5002538d00000000-part1/workspace/tikv/tests)
error[E0432]: unresolved import `fail`
 --> tests/failpoints/cases/test_conf_change.rs:3:5
  |
3 | use fail;
  |     ^^^^ no `fail` external crate
...
```

**Comment by BusyJay** [comment]
Can codec be controlled by one features? We can remove protobuf-codec completely and just use prost-codec.

**Comment by breeswish** [comment]
I'm fine with this change. Our CI need to be updated to work with this PR.

**Pull request closed without merging**
