### PR TITLE
Add key and size threshold for load-base-split  (#9256)

### LINKED ISSUE #9255: Add key and size threshold for load-base-split
### Is your feature request related to a problem? Please describe:

The current load-base-split only receives the limitation of qps, so sometimes it may cut out a region with only a few keys, which is not good, especially in scenarios where there are more scan requests。

### Describe the feature you'd like:

Add limits on the size and key of the region before split.

### Describe alternatives you've considered:

If we have a more accurate distribution of keys, we can even ensure that the region after split is not smaller than the threshold of key or size, avoiding the situation of Salami tactics.

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #9256 to release-5.0-rc

---

### What problem does this PR solve?

Issue Number: close #9255

Problem Summary:：

Add key and size threshold for load-base-split  to avoid unnecessarily split

### What is changed and how it works?

add threshold and unit test

### Check List 

Tests 

- Unit test

### CODE REVIEW

**Comment by hi-rustin** [comment]
This cherry pick PR is for a release branch and has not yet been approved by release team. Adding the do-not-merge/cherry-pick-not-approved label.
To merge this cherry pick, it must first be approved (/lgtm + /merge) by the collaborators.
AFTER it has been approved by collaborators, please ping the release team in a comment to request a cherry pick review

**Comment by lhy1024** [comment]
@BusyJay @HunDunDM @nolouch PTAL

**Comment by lhy1024** [comment]
@BusyJay @HunDunDM @nolouch PTAL

**Review by HunDunDM — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Pull request merged**
