### PR TITLE
tidb_query_vec_executors: Fixed stack-borrowing undefined-behavior

### PR DESCRIPTION
**Pull request by brson**
### What problem does this PR solve?

This fixes undefined behavior in tidb_query_vec_executors. Miri reports a [stacked borrowing] error as described below.

[stacked borrowing]: https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md

Note that stacked borrowing is a way to model Rust's use of unsafe pointers, but is not officially part of Rust's memory model. Thus, this is not truly undefined behavior today, but could be eventually.

I don't understand the stacked borrowing rules enough to understand why the
existing code is a violation. It is creating a mutable unsafe pointer; then
taking some immutable borrows to the same data while doing nothing with that
pointer; then later using the pointer.

Simply moving the creation of the unsafe pointer to immediately before it
is used removes the error.

cc @RalfJung not sure if you like being tagged on miri stacked borrow reports. If you have time though maybe you could explain what's going on here.

Found with miri, which reports:

```
error: Undefined Behavior: trying to reborrow for SharedReadOnly, but parent tag <1121039> does not have an appropriate item in the borrow sta
ck
   --> components/tidb_query_vec_executors/src/slow_hash_aggr_executor.rs:281:32
    |
281 |             let offset_begin = self.group_key_buffer.len();
    |                                ^^^^^^^^^^^^^^^^^^^^^ trying to reborrow for SharedReadOnly, but parent tag <1121039> does not have an ap
propriate item in the borrow stack
    |
    = help: this indicates a potential bug in the program: it performed an invalid operation, but the rules it violated are still experimental
    = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
```

Signed-off-by: Brian Anderson <andersrb@gmail.com>

### CODE REVIEW

**Comment by RalfJung** [comment]
> I believe it is UB because the old line 280 takes a reference to self.group_key_buffer, but then inside the for loop self.group_key_buffer is mutated. This is equivalent to holding two &mut pointers, which is of course not allowed. This is only possible at all because the into creates a NonNull, which is basically a *mut pointer. It is not unsafe to have multiple *mut pointers as long as they are not dereferenced, but I guess miri is still treating it as UB.

`self.group_key_buffer` is not a `*mut` though, is it? I have a hard time understanding what the code does here, but from your summary it sounds like we have a `*mut` and an `&mut` and both are being used. That is definitely UB because `&mut` must not have any aliases being used.

(Actually isn't `buffer_ptr` a `*const`? It is created from a shared reference, so it must not be used for mutation, unless there are `UnsafeCell`.)

**Comment by nrc** [comment]
Thanks @RalfJung !

`self.group_key_buffer` is `Box<Vec<u8>>`. `self` is `&mut`, so `self.group_key_buffer` is being mutated via an implicit `&mut`.

`buffer_ptr` is a `NonNull`, which aiui is equivalent to `*mut` for this sort of thing (although I think you are right that there should be an `UnsafeCell` somewhere).

**Comment by RalfJung** [comment]
> buffer_ptr is a NonNull, which aiui is equivalent to *mut for this sort of thing

It is, but you are creating it from a shared reference it looks like, which means you must not use it for mutation.

`*(&x as *const _ as *mut _) = 5` is UB.

> (although I think you are right that there should be an UnsafeCell somewhere).

`UnsafeCell` is only needed if you truly want to mutate data behind a shared reference. If that is not, then just create your `NonNull` from an `&mut`.

**Comment by RalfJung** [comment]
> buffer_ptr is a NonNull, which aiui is equivalent to *mut for this sort of thing

I should clarify: Raw pointers, once created, do not care about their type.

But how you *create* a raw pointer initially matters. *Casting to `*const`* is very different from *casting to `*mut`*. The former creates a raw pointer that is immutable like shared references are, the latter creates a raw pointer that may be used for mutation.

`NonNull::from(&x)` creates a read-only raw pointer. [This example demonstrates the UB](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c7af985209c7f6414384d55e01e8fc18).

**Comment by nrc** [comment]
Thanks @RalfJung !

**Pull request merged**
