### PR TITLE
copr: add vec RoundWithFracReal and RoundWithFracDec

### PR DESCRIPTION
**Pull request by Rustin-Liu**
Signed-off-by: Rustin-liu <rustin.liu@gmail.com>

### What problem does this PR solve?

Problem Summary:

Add vec RoundWithFracReal fn.

### What is changed and how it works?

What's Changed:

Add vec RoundWithFracReal fn.

### Related changes

None

### Check List 

Tests 

- Unit test

Side effects

None

### Release note 
- copr: add vec RoundWithFracReal

### CODE REVIEW

**Comment by Rustin-Liu** [comment]
@TennyZhuang  @breeswish  @sticnarf  PTAL~ Thanks!

**Comment by breeswish** [comment]
@iosmanthus @TennyZhuang PTAL

**Comment by Rustin-Liu** [comment]
@breeswish  Could you please help me merge this PR?

**Comment by breeswish** [comment]
@Rustin-Liu Thanks!

**Comment by Rustin-Liu** [comment]
@ti-srebot  /integration-copr-test

**Comment by Rustin-Liu** [comment]
@ti-srebot /merge

**Pull request merged**
