### PR TITLE
Integration test: use proc-macro to reuse test cases.

### PR DESCRIPTION
**Pull request by SpadeA-Tang**
Signed-off-by: SpadeA-Tang <u6748471@anu.edu.au>

### What is changed and how it works?

Issue Number: Ref #12842

What's Changed:

```commit-message
Add proc-macro test_case to reuse test cases.
```

The way to use it:
```
#[test_case(test_raftstore::new_node_cluster)]
#[test_case(test_raftstore::new_server_cluster)]
#[test_case(test_raftstore_v2::new_node_cluster)]
fn test_something() {
    let cluster = new_cluster(...)
}
```
It actually generates the following test cases:
```
#[cfg(test)]
mod test_something {
    #[test]
    fn test_raftstore_new_node_cluster() {
        use test_raftstore::new_node_cluster as new_cluster;
        let mut cluster = new_cluster(0, 1);
    }

    #[test]
    fn test_raftstore_new_server_cluster() {
        use test_raftstore::new_server_cluster as new_cluster;
        let mut cluster = new_cluster(0, 1);
    }

    #[test]
    fn test_raftstore_v2_new_server_cluster() {
        use test_raftstore::test_raftstore_v2 as new_cluster;
        let mut cluster = new_cluster(0, 1);
    }
}
```

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by tonyxuqqi — APPROVED** [review]
So for adding a new test case, just follow the examples below?
#[test_case(test_raftstore::new_node_cluster)]
#[test_case(test_raftstore::new_server_cluster)]
fn test() {
    let mut cluster = new_cluster(0, 1);
    cluster.run();
    .....
    }

**Comment by SpadeA-Tang** [comment]
> So for adding a new test case, just follow the examples below? #[test_case(test_raftstore::new_node_cluster)] #[test_case(test_raftstore::new_server_cluster)] fn test() { let mut cluster = new_cluster(0, 1); cluster.run(); ..... }

yes.

**Review by Connor1996 — COMMENTED** [review]
LGTM, though I wonder if the panic backtrace is readable now

**Comment by SpadeA-Tang** [comment]
> wonder

I have verified manually that the panic backtrace is not changed.

**Review by Connor1996 — APPROVED** [review]

**Comment by BusyJay** [comment]
Great, another macro is added without consensus. :)

**Pull request merged**
